"""
Phase 4A.3.2 — canonical document language policy + English planner preflight.

Offline only. Does not mutate historical A.3 / A.3.1 artifacts.
"""

from __future__ import annotations

from app.editorial_planner_canary_4a1.constants import (
    PHASE_4A_ADAPTED_SCHEMA_BYTES,
    PHASE_4A_ADAPTED_SCHEMA_SHA256,
    PHASE_4A_INSTRUCTIONS_SHA256,
    PHASE_4A_PROMPT_SHA256,
    PHASE_4A_RAW_SCHEMA_BYTES,
    PHASE_4A_RAW_SCHEMA_SHA256,
    PHASE_4A_SYSTEM_SHA256,
)
from app.editorial_planner_canary_4a3.constants import (
    A2_CONSERVATIVE_COST_USD,
    A2_CONSERVATIVE_OUTPUT_TOKENS,
    A2_EXPECTED_COST_USD,
    A2_EXPECTED_OUTPUT_TOKENS,
    A2_HARD_COST_USD,
    A2_HARD_OUTPUT_TOKENS,
    A2_LOCAL_INPUT_ESTIMATE,
    A2_PROVIDER_ADJUSTED_PESSIMISTIC,
    EXPECTED_EXAMPLE_COUNT,
    EXPECTED_IDEA_COUNT,
    EXPECTED_REFERENCE_COUNT,
    EXPECTED_REQUEST_SHA256,
    EXPECTED_SOURCE_MAP_BYTES,
    EXPECTED_SOURCE_MAP_SHA256,
    EXPECTED_TOPIC_COUNT,
    EXPECTED_UNCERTAINTY_COUNT,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PROJECT_NAME,
)
from app.editorial_planning.constants import (
    EDITORIAL_PLAN_TRANSPORT_VERSION,
    EDITORIAL_PLANNER_PROMPT_VERSION,
    MODEL,
    PROVIDER,
)
from app.editorial_planning.language_policy import (
    DOCUMENT_LANGUAGE_POLICY,
    SUCCESSOR_PROMPT_VERSION,
)

PHASE = "4A.3.2"
PHASE_NAME = "CANONICAL_DOCUMENT_LANGUAGE_POLICY_AND_ENGLISH_PLANNER_PREFLIGHT"
PHASE_VERSION = "editorial-planner-language-policy-4a32-1.0"

AUTHORIZATION_SCOPE = "EDITORIAL_PLANNER_4A32_OFFLINE_LANGUAGE_POLICY_PREFLIGHT_ONLY"

REAL_PROVIDER_CALLS = 0
MAX_ENGINE_GENERATE = 0
MAX_ANTHROPIC_POST = 0
FUTURE_REAL_CALL_COUNT = 1
FUTURE_RETRIES = 0

A3_HISTORICAL_STATUS = "PARTIAL"
A31_STATUS = "PASS"
A3_CANDIDATE_STATUS = "AUDIT_ONLY_NOT_PUBLISHABLE"

A3_CANDIDATE_SHA256 = (
    "abc87e082878e0281689ecc022ed8b40ca318510fc90d960c31795d6186bd95e"
)
A3_REQUEST_SHA256 = EXPECTED_REQUEST_SHA256
assert A3_REQUEST_SHA256 == (
    "99ee7e8f4f9a732b52fceab667d9d1fe8b9ce9acedc1e7b1e7c08c1f62b7b734"
)
assert EXPECTED_SOURCE_MAP_SHA256 == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)

A3_INPUT_TOKENS = 41425
A3_OUTPUT_TOKENS = 17791
A3_THINKING_TOKENS = 6443
A3_COST_USD = 0.6519
A3_FINISH = "end_turn"

HISTORICAL_PROMPT = EDITORIAL_PLANNER_PROMPT_VERSION
NEW_PROMPT = SUCCESSOR_PROMPT_VERSION
TRANSPORT_VERSION = EDITORIAL_PLAN_TRANSPORT_VERSION
assert HISTORICAL_PROMPT == "editorial-planner-1.0"
assert NEW_PROMPT == "editorial-planner-1.0.1"
assert TRANSPORT_VERSION == "editorial-plan-transport-1.0"
assert DOCUMENT_LANGUAGE_POLICY == "TRANSCRIPTION_DERIVED_PRIMARY_LANGUAGE"

RAW_SCHEMA_BYTES = PHASE_4A_RAW_SCHEMA_BYTES
ADAPTED_SCHEMA_BYTES = PHASE_4A_ADAPTED_SCHEMA_BYTES
ADAPTED_SCHEMA_SHA256 = PHASE_4A_ADAPTED_SCHEMA_SHA256
RAW_SCHEMA_SHA256 = PHASE_4A_RAW_SCHEMA_SHA256
SYSTEM_SHA256 = PHASE_4A_SYSTEM_SHA256
INSTRUCTIONS_SHA256 = PHASE_4A_INSTRUCTIONS_SHA256
PROMPT_SHA256 = PHASE_4A_PROMPT_SHA256
assert RAW_SCHEMA_BYTES == 3661
assert ADAPTED_SCHEMA_BYTES == 3909
assert ADAPTED_SCHEMA_SHA256 == (
    "1cebcf97ed7fa5cfa4b4758d1eb1451b6770347e9508772e8287228a768ba77e"
)

assert PROVIDER == "anthropic"
assert MODEL == "claude-opus-5"
THINKING_MODE = "provider_default"
EFFORT = None
BUDGET_TOKENS = None
MAX_OUTPUT_TOKENS = PRODUCTION_MAX_OUTPUT_TOKENS
assert MAX_OUTPUT_TOKENS == 65536

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 1800.0

A2_EXPECTED_OUTPUT_TOKENS = A2_EXPECTED_OUTPUT_TOKENS
A2_CONSERVATIVE_OUTPUT_TOKENS = A2_CONSERVATIVE_OUTPUT_TOKENS
A2_HARD_OUTPUT_TOKENS = A2_HARD_OUTPUT_TOKENS
assert A2_EXPECTED_OUTPUT_TOKENS == 8670
assert A2_CONSERVATIVE_OUTPUT_TOKENS == 19666
assert A2_HARD_OUTPUT_TOKENS == 34555

PROJECT_NAME = PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"
EXPECTED_IDEA_COUNT = EXPECTED_IDEA_COUNT
EXPECTED_TOPIC_COUNT = EXPECTED_TOPIC_COUNT
EXPECTED_EXAMPLE_COUNT = EXPECTED_EXAMPLE_COUNT
EXPECTED_REFERENCE_COUNT = EXPECTED_REFERENCE_COUNT
EXPECTED_UNCERTAINTY_COUNT = EXPECTED_UNCERTAINTY_COUNT
EXPECTED_SOURCE_MAP_BYTES = EXPECTED_SOURCE_MAP_BYTES
EXPECTED_SOURCE_MAP_SHA256 = EXPECTED_SOURCE_MAP_SHA256

NEW_GRAMMAR_CANARY_REQUIRED = "NO"
LANGUAGE_POLICY = DOCUMENT_LANGUAGE_POLICY
TRANSLATION_DURING_SOURCE_GENERATION = "NO"
TRANSLATION_AFTER_SOURCE_DOCUMENT = "SUPPORTED_AS_FUTURE_SEPARATE_STAGE"

PUBLICATION_AUTHORIZED = False
BOOK_GENERATOR = "NOT STARTED"
NEXT_ACTION = "HUMAN REVIEW"

AUDIT_DIRNAME = "editorial_planner_language_policy_4a32"
AUDIT_POLICY = "editorial_planner_4a32_language_policy.json"
AUDIT_PROVENANCE = "editorial_planner_4a32_language_provenance.json"
AUDIT_PROMPT = "editorial_planner_4a32_prompt_identity.json"
AUDIT_SCHEMA = "editorial_planner_4a32_schema_identity.json"
AUDIT_REQUEST = "editorial_planner_4a32_exact_request_identity.json"
AUDIT_BUDGET = "editorial_planner_4a32_budget.json"
AUDIT_LANGUAGE_VALIDATION = "editorial_planner_4a32_language_validation_policy.json"
AUDIT_READINESS = "editorial_planner_post_4a32_readiness.json"
REPORT_NAME = (
    "PHASE_4A32_CANONICAL_DOCUMENT_LANGUAGE_POLICY_AND_ENGLISH_PLANNER_PREFLIGHT_REPORT.md"
)

A3_AUDIT_RELATIVE = "audit/real/editorial_planner_4a3"
CANDIDATE_NAME = "editorial_plan_candidate.json"

FORBIDDEN_TECHNICAL_TOKENS = (
    "analysis_window",
    "chunk_id",
    "chunk_index",
    "technical_window",
    "window_id",
    "win_id",
    "processed/chunk",
    "chunk_*.md",
)
FORBIDDEN_WINDOW_IDS = (
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
)

assert REAL_PROVIDER_CALLS == 0
assert PUBLICATION_AUTHORIZED is False
assert FUTURE_RETRIES == 0
assert A2_LOCAL_INPUT_ESTIMATE == 25313
assert A2_PROVIDER_ADJUSTED_PESSIMISTIC == 52283
assert A2_EXPECTED_COST_USD == 0.5624
assert A2_CONSERVATIVE_COST_USD == 0.8373
assert A2_HARD_COST_USD == 1.2095
