"""Rapport markdown Phase 4A.1."""

from __future__ import annotations

from typing import Any, Mapping


def _cov(contract: Mapping[str, Any], key: str, default: str = "n/a") -> Any:
    coverage = dict(contract.get("idea_coverage") or {})
    if key in coverage:
        return coverage.get(key)
    refs = dict(contract.get("unknown_refs") or {})
    if key in refs:
        return refs.get(key)
    return contract.get(key, default)


def render_report(bundle: Mapping[str, Any]) -> str:
    header = dict(bundle.get("header") or {})
    lines = [
        "# PHASE 4A.1 — EDITORIAL PLANNER TINY GRAMMAR + CONTRACT CANARY",
        "",
        "## Result",
        "",
        str(header.get("result") or "FAIL"),
        "",
        f"AUTHORIZED PROVIDER CALLS = {header.get('authorized_provider_calls', 1)}",
        "",
        f"ACTUAL PROVIDER CALLS = {header.get('actual_provider_calls', 0)}",
        "",
        f"RETRIES = {header.get('retries', 0)}",
        "",
        f"PRODUCTION DATA SENT = {header.get('production_data_sent', 'NO')}",
        "",
        f"REAL EDITORIAL PLANNING = {header.get('real_editorial_planning', 'NO')}",
        "",
        f"PROVIDER = {header.get('provider', 'Anthropic')}",
        "",
        f"MODEL = {header.get('model', 'claude-opus-5')}",
        "",
        f"PROMPT = {header.get('prompt')}",
        "",
        f"TRANSPORT = {header.get('transport')}",
        "",
        f"SCHEMA RAW / ADAPTED = {header.get('schema_raw_adapted')}",
        "",
        f"SCHEMA HASH = {header.get('schema_hash')}",
        "",
        f"SCHEMA IDENTITY = {header.get('schema_identity')}",
        "",
        f"THINKING MODE = {header.get('thinking_mode')}",
        "",
        f"EFFORT = {header.get('effort')}",
        "",
        f"BUDGET TOKENS = {header.get('budget_tokens')}",
        "",
        f"CANARY MAX_OUTPUT = {header.get('canary_max_output')}",
        "",
        f"HTTP / STATUS = {header.get('http_status')}",
        "",
        f"FINISH = {header.get('finish')}",
        "",
        f"REQUEST ID = {header.get('request_id')}",
        "",
        f"INPUT TOKENS = {header.get('input_tokens')}",
        "",
        f"OUTPUT TOKENS = {header.get('output_tokens')}",
        "",
        f"THINKING TOKENS = {header.get('thinking_tokens')}",
        "",
        f"OPUS5_PROVIDER_DEFAULT_THINKING_OBSERVED = {header.get('opus5_thinking_observed')}",
        "",
        f"ELAPSED = {header.get('elapsed')}",
        "",
        f"COST = {header.get('cost')}",
        "",
        f"STRUCTURED PARSE = {header.get('structured_parse')}",
        "",
        f"TRANSPORT DECODER = {header.get('transport_decoder')}",
        "",
        f"HANDLE VALIDATION = {header.get('handle_validation')}",
        "",
        f"CANONICAL RECONSTRUCTION = {header.get('canonical_reconstruction')}",
        "",
        f"CANONICAL IDS = {header.get('canonical_ids')}",
        "",
        f"HIERARCHY = {header.get('hierarchy')}",
        "",
        f"CHAPTERS = {header.get('chapters')}",
        "",
        f"SECTIONS = {header.get('sections')}",
        "",
        f"SYNTHETIC IDEAS = {header.get('synthetic_ideas')}",
        "",
        f"IDEA COVERAGE = {header.get('idea_coverage')}",
        "",
        f"SILENT OMISSIONS = {header.get('silent_omissions')}",
        "",
        f"ASSIGNED = {header.get('assigned')}",
        "",
        f"DEFERRED = {header.get('deferred')}",
        "",
        f"EXCLUDED = {header.get('excluded')}",
        "",
        f"REUSED = {header.get('reused')}",
        "",
        f"UNKNOWN IDEA REFS = {header.get('unknown_idea_refs')}",
        "",
        f"UNKNOWN TOPIC REFS = {header.get('unknown_topic_refs')}",
        "",
        f"UNKNOWN EXAMPLE REFS = {header.get('unknown_example_refs')}",
        "",
        f"UNKNOWN REFERENCE REFS = {header.get('unknown_reference_refs')}",
        "",
        f"UNKNOWN UNCERTAINTY REFS = {header.get('unknown_uncertainty_refs')}",
        "",
        f"TRACEABILITY = {header.get('traceability')}",
        "",
        f"INVENTION BOUNDARY = {header.get('invention_boundary')}",
        "",
        f"UNCERTAINTY PRESERVATION = {header.get('uncertainty_preservation')}",
        "",
        f"EDITORIAL PLAN VALIDATOR = {header.get('editorial_plan_validator')}",
        "",
        f"DETERMINISTIC REPLAY = {header.get('deterministic_replay')}",
        "",
        f"SEMANTIC CANARY REVIEW = {header.get('semantic_canary_review')}",
        "",
        f"EDITORIAL_PLANNER_GRAMMAR_PROOF = {header.get('grammar_proof')}",
        "",
        f"EDITORIAL_PLANNER_CONTRACT_CANARY = {header.get('contract_canary')}",
        "",
        f"PRODUCTION EXPECTED OUTPUT = {header.get('production_expected_output')}",
        "",
        f"PRODUCTION CONSERVATIVE OUTPUT = {header.get('production_conservative_output')}",
        "",
        f"PRODUCTION HARD OUTPUT = {header.get('production_hard_output')}",
        "",
        f"CURRENT PROPOSED PRODUCTION MAX_OUTPUT = {header.get('proposed_production_max_output')}",
        "",
        f"PRODUCTION_OUTPUT_BUDGET_REVIEW_REQUIRED = {header.get('production_output_budget_review_required')}",
        "",
        f"TESTS = {header.get('tests')}",
        "",
        f"NEW FAILURES = {header.get('new_failures')}",
        "",
        "editorial_plan.json = NOT PUBLISHED",
        "",
        "BOOK GENERATOR = NOT STARTED",
        "",
        f"READY_FOR_EDITORIAL_PLANNER_PRODUCTION_PREFLIGHT = {header.get('ready_for_production_preflight')}",
        "",
        "READY_FOR_REAL_EDITORIAL_PLANNER_CALL = NO",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
        "## Notes",
        "",
        str(header.get("notes") or ""),
        "",
        "WAIT FOR HUMAN REVIEW.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
