"""
Phase 4B.2.12 — Semantic Gate 2.0 contract consolidation, offline replay,
and integration decision.

STRICTLY OFFLINE. Isolated from production. Zero provider calls.
Historical canaries and the 4B.2.11 raw Terra response are not modified.
2.0-candidate and 2.0.1-candidate are not overwritten.
2.0.2-candidate is not activated. No new Terra call is authorized.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
)
from app.book_semantic_gate_4b23.reasons import REASON_CODES, REASON_DEFINITIONS
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    SEMANTIC_TOKEN_BUDGET,
)
from app.book_semantic_gate_4b210.constants import (
    CHAPTER_HANDLE,
    H01_EVIDENCE_HANDLES,
    H01_HUMAN_LABEL,
    H01_REQUEST_SHA256,
    H02_REQUEST_SHA256,
    H11_REQUEST_SHA256,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
    OVERFIT_TOKENS,
    PROMPT_VERSION_201_CANDIDATE,
    SELECTED_CASE_HANDLE as FROZEN_CASE_HANDLE,
    SELECTED_CASE_ID as FROZEN_CASE_ID,
    TRANSPORT_VERSION_20_CANDIDATE,
)
from app.book_semantic_gate_4b211.constants import (
    EXPECTED_REQUEST_SHA256 as FROZEN_4B210_REQUEST_SHA256,
    HISTORICAL_4B210_STATUS,
)
from app.book_semantic_gate_4b271.constants import DISPUTED_CLAUSE as H01_DISPUTED_CLAUSE
from app.book_semantic_gate_4b29.constants import (
    DECISION_BLOCK,
    DECISION_PASS,
    DECISION_REVIEW,
    PROMPT_VERSION_20_CANDIDATE,
)

PHASE = "4B.2.12"
PHASE_NAME = "SEMANTIC_GATE_20_CONTRACT_CONSOLIDATION_OFFLINE_REPLAY_AND_INTEGRATION_DECISION"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B212_SEMANTIC_GATE_20_CONTRACT_CONSOLIDATION_"
    "OFFLINE_REPLAY_AND_INTEGRATION_DECISION_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
REAL_TERRA_CANARY_AUTHORIZED = False
SDK_MAX_RETRIES = 0
RETRIES = 0
FALLBACKS = 0

SEMANTIC_GATE_20_ENABLED = False
SEMANTIC_GATE_201_ENABLED = False
SEMANTIC_GATE_202_ENABLED = False
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"
TOKEN_FIELD = "max_completion_tokens"
PRODUCTION_SDK_METHOD = "client.chat.completions.create"

PROMPT_VERSION_20_ACTIVATED = False
PROMPT_VERSION_201_ACTIVATED = False
PROMPT_VERSION_202_CANDIDATE = "book-semantic-validator-2.0.2-candidate"
PROMPT_VERSION_202_ACTIVATED = False
TRANSPORT_VERSION_20_ACTIVATED = False

CODE_VERSION = "app.book_semantic_gate_4b212"

SELECTED_CASE_HANDLE = FROZEN_CASE_HANDLE
SELECTED_CASE_ID = FROZEN_CASE_ID
SELECTED_CASE_HUMAN_LABEL = H01_HUMAN_LABEL
SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY = True
TARGET_UNIT_ID = "u01"
TARGET_CLAUSE = H01_DISPUTED_CLAUSE
CHAPTER_ID = CHAPTER_HANDLE
REQUIRED_UNIT_IDS = ("u00", "u01", "u02", "u03", "u04")

EXPECTED_REQUEST_SHA256 = FROZEN_4B210_REQUEST_SHA256
EXPECTED_4B211_RAW_TEXT_SHA256 = (
    "ef45c2d4262c5bb86a6ff891fb2a03b79189342c25c8cd9e5c261742992f7fe5"
)
HISTORICAL_4B211_STATUS = "PARTIAL"
HISTORICAL_4B211_COST_USD = "0.0062860 USD"
HISTORICAL_4B211_INPUT_TOKENS = 1247
HISTORICAL_4B211_COMPLETION_TOKENS = 316
HISTORICAL_4B211_REASONING_TOKENS = 136

SEMANTIC_CLASSIFICATIONS = CLASSIFICATIONS
OPERATIONAL_DECISIONS = (DECISION_PASS, DECISION_BLOCK, DECISION_REVIEW)
TECHNICAL_CONFORMANCE = ("VALID", "INVALID")
FORBIDDEN_MODEL_FIELDS = ("v", "sc", "uh", "rr")
FORBIDDEN_PARAGRAPH_FIELDS = ("v",)
OPERATIONAL_VALUES = (
    DECISION_PASS,
    DECISION_BLOCK,
    DECISION_REVIEW,
    "FAIL",
    "VALID",
    "INVALID",
)
FIXTURE_KIND = "SYNTHETIC_OFFLINE_FIXTURE"

REMOTE_STRICT_SCHEMA_COMPATIBILITY = "UNVERIFIED"

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
assert TOKEN_FIELD == "max_completion_tokens"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert SELECTED_CASE_HANDLE == "h01"
assert SELECTED_CASE_ID == "4b210_h01"
assert SELECTED_CASE_HUMAN_LABEL == CLASS_SUPPORTED
assert SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY is True
assert TARGET_CLAUSE == "that fear can calculate or bargain with"
assert TARGET_UNIT_ID == "u01"
assert H01_EVIDENCE_HANDLES == (
    "IDEA224",
    "SRC006149",
    "SRC006180",
    "SRC006182",
    "SRC006183",
    "SRC006187",
)
assert EXPECTED_REQUEST_SHA256 == (
    "d62ee35106f89d34170fb93364ce202b021fd0c60c582248c241cb296008c484"
)
assert EXPECTED_REQUEST_SHA256 != H01_REQUEST_SHA256
assert EXPECTED_REQUEST_SHA256 != H02_REQUEST_SHA256
assert EXPECTED_REQUEST_SHA256 != H11_REQUEST_SHA256
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert PROMPT_VERSION_20_CANDIDATE == "book-semantic-validator-2.0-candidate"
assert PROMPT_VERSION_201_CANDIDATE == "book-semantic-validator-2.0.1-candidate"
assert PROMPT_VERSION_202_CANDIDATE != PROMPT_VERSION_20_CANDIDATE
assert PROMPT_VERSION_202_CANDIDATE != PROMPT_VERSION_201_CANDIDATE
assert TRANSPORT_VERSION_20_CANDIDATE == (
    "book-semantic-validation-transport-2.0-candidate"
)
assert PROMPT_VERSION_20_ACTIVATED is False
assert PROMPT_VERSION_201_ACTIVATED is False
assert PROMPT_VERSION_202_ACTIVATED is False
assert TRANSPORT_VERSION_20_ACTIVATED is False
assert SEMANTIC_GATE_20_ENABLED is False
assert SEMANTIC_GATE_201_ENABLED is False
assert SEMANTIC_GATE_202_ENABLED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert REAL_TERRA_CANARY_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False
assert SDK_MAX_RETRIES == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_H11_STATUS == "PARTIAL"
assert HISTORICAL_4B210_STATUS == "PASS"
assert HISTORICAL_4B211_STATUS == "PARTIAL"
assert CLASSIFICATIONS == (
    CLASS_SUPPORTED,
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    CLASS_NON_SUBSTANTIVE,
)
assert len(REASON_CODES) == 16
assert CANONICAL_PYTHON_EXECUTABLE.endswith("python.exe")
assert EXPECTED_OPENAI_SDK_VERSION == "2.43.0"
assert EXPECTED_PYTHON_VERSION == (3, 11, 9) or isinstance(EXPECTED_PYTHON_VERSION, tuple)
assert REMOTE_STRICT_SCHEMA_COMPATIBILITY == "UNVERIFIED"

AUDIT_DIRNAME = "book_semantic_gate_4b212"
AUDIT_INVENTORY = "technical_inventory.json"
AUDIT_FORENSICS = "real_response_forensics.json"
AUDIT_MISMATCH = "schema_mismatch_analysis.json"
AUDIT_CONCEPTS = "semantic_vs_operational_verdicts.json"
AUDIT_CONTRACT = "contract_202_candidate.json"
AUDIT_SCHEMA = "strict_schema_feasibility.json"
AUDIT_REPLAY_201 = "historical_replay_201.json"
AUDIT_SEMANTIC = "historical_semantic_observations.json"
AUDIT_SYNTHETIC = "synthetic_202_fixture_replay.json"
AUDIT_FAKEAI = "negative_fakeai_tests.json"
AUDIT_POLICY = "acceptance_policy_validation.json"
AUDIT_ARCHITECTURE = "architecture_options.json"
AUDIT_RESUMPTION = "book_generator_resumption_plan.json"
AUDIT_SAFETY = "provider_safety.json"
AUDIT_HASHES = "canonical_hashes.json"
AUDIT_TESTS = "offline_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b212_index.json"
REPORT_NAME = "PHASE_4B212_SEMANTIC_GATE_20_CONSOLIDATION_AND_INTEGRATION_DECISION_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_REAL_CHAPTER_GENERATION = False
READY_FOR_FULL_BOOK_GENERATION = False

__all__ = [
    "AUDIT_ARCHITECTURE",
    "AUDIT_CONCEPTS",
    "AUDIT_CONTRACT",
    "AUDIT_DIRNAME",
    "AUDIT_FAKEAI",
    "AUDIT_FORENSICS",
    "AUDIT_HASHES",
    "AUDIT_INDEX",
    "AUDIT_INVENTORY",
    "AUDIT_MISMATCH",
    "AUDIT_POLICY",
    "AUDIT_READINESS",
    "AUDIT_REPLAY_201",
    "AUDIT_RESUMPTION",
    "AUDIT_SAFETY",
    "AUDIT_SCHEMA",
    "AUDIT_SEMANTIC",
    "AUDIT_SYNTHETIC",
    "AUDIT_TESTS",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_REMOTE_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CHAPTER_ID",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CODE_VERSION",
    "DECISION_BLOCK",
    "DECISION_PASS",
    "DECISION_REVIEW",
    "EXPECTED_4B211_RAW_TEXT_SHA256",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_OPENAI_SDK_VERSION",
    "EXPECTED_REQUEST_SHA256",
    "EXPECTED_SOURCE_MAP",
    "FALLBACKS",
    "FIXTURE_KIND",
    "FORBIDDEN_MODEL_FIELDS",
    "FORBIDDEN_PARAGRAPH_FIELDS",
    "H01_EVIDENCE_HANDLES",
    "HISTORICAL_4B210_STATUS",
    "HISTORICAL_4B211_STATUS",
    "HISTORICAL_H01_STATUS",
    "HISTORICAL_H02_STATUS",
    "HISTORICAL_H11_STATUS",
    "MODEL",
    "NEXT_ACTION",
    "OPERATIONAL_DECISIONS",
    "OPERATIONAL_VALUES",
    "OVERFIT_TOKENS",
    "PHASE",
    "PHASE_NAME",
    "PRODUCTION_CACHE_ACCEPTANCE",
    "PRODUCTION_PIPELINE_HOOK",
    "PROJECT_NAME",
    "PROMPT_VERSION_20_CANDIDATE",
    "PROMPT_VERSION_201_CANDIDATE",
    "PROMPT_VERSION_202_ACTIVATED",
    "PROMPT_VERSION_202_CANDIDATE",
    "PROVIDER",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_FULL_BOOK_GENERATION",
    "READY_FOR_NEW_REMOTE_TERRA_CALL",
    "READY_FOR_REAL_CHAPTER_GENERATION",
    "REAL_TERRA_CANARY_AUTHORIZED",
    "REASON_CODES",
    "REASON_DEFINITIONS",
    "REMOTE_STRICT_SCHEMA_COMPATIBILITY",
    "REPORT_NAME",
    "REQUIRED_UNIT_IDS",
    "RETRIES",
    "SDK_MAX_RETRIES",
    "SELECTED_CASE_HANDLE",
    "SELECTED_CASE_HUMAN_LABEL",
    "SELECTED_CASE_ID",
    "SEMANTIC_CLASSIFICATIONS",
    "SEMANTIC_GATE_20_ENABLED",
    "SEMANTIC_GATE_201_ENABLED",
    "SEMANTIC_GATE_202_ENABLED",
    "SEMANTIC_TOKEN_BUDGET",
    "TARGET_CLAUSE",
    "TARGET_UNIT_ID",
    "TECHNICAL_CONFORMANCE",
    "TERRA_EXECUTION_AUTHORIZED",
    "TRANSPORT_VERSION_20_CANDIDATE",
]
