"""Rapport markdown déterministe 3B.7.7A.14."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None:
        return "UNKNOWN"
    return str(value)


def render_report(bundle: Mapping[str, Any]) -> str:
    h = bundle.get("header") or {}
    replay = bundle.get("replay") or {}
    contract = bundle.get("contract") or {}
    prompt = bundle.get("prompt") or {}
    readiness = bundle.get("readiness") or {}
    identity = bundle.get("identity") or {}
    e2e = bundle.get("e2e") or {}
    preflight = bundle.get("preflight") or {}
    schema = bundle.get("schema") or {}
    worst = bundle.get("worst") or {}
    failures = replay.get("link_failures") or []
    lines = [
        "# PHASE 3B.7.7A.14 — V2 LINK SEMANTICS HARDENING & SEMANTIC WIN001 READINESS",
        "",
        "## Result",
        "",
        str(h.get("result") or "UNKNOWN"),
        "",
        f"REAL PROVIDER CALLS = {h.get('real_provider_calls')}",
        "",
        f"REAL WINDOW CALLS = {h.get('real_window_calls')}",
        "",
        f"A.13 GRAMMAR = {h.get('a13_grammar')}",
        "",
        f"A.13 THINKING DISABLED = {h.get('a13_thinking_disabled')}",
        "",
        f"A.13 THINKING TOKENS = {h.get('a13_thinking_tokens')}",
        "",
        f"A.13 STRUCTURED PARSE = {h.get('a13_structured_parse')}",
        "",
        f"A.13 LINK VALIDATION = {h.get('a13_link_validation')}",
        "",
        f"LINK FAILURE ROOT CAUSE = {h.get('root_cause')}",
        "",
        f"LINK INDEX BASE = {h.get('index_base')}",
        "",
        f"SELF LINKS = {h.get('self_links')}",
        "",
        f"PROMPT VERSION = {h.get('prompt_version')}",
        "",
        f"TRANSPORT = {h.get('transport')}",
        "",
        f"SCHEMA CHANGED = {h.get('schema_changed')}",
        "",
        f"RAW / ADAPTED SCHEMA = {h.get('raw_adapted_schema')}",
        "",
        f"SYNTHETIC WORST CASE = {h.get('synthetic_worst_case')} local tokens",
        "",
        f"THINKING CONTRACT = {h.get('thinking_contract')}",
        "",
        f"REAL CLEAN WINDOWS = {h.get('real_clean_windows')}",
        "",
        f"MAX FUTURE WINDOW INPUT = {h.get('max_future_window_input')}",
        "",
        f"FUTURE WIN001 SIGNATURE = {h.get('future_win001_signature')}",
        "",
        f"FUTURE WIN001 CACHE = {h.get('future_win001_cache')}",
        "",
        f"FAKEAI LOCAL V2 = {h.get('fakeai_local_v2')}",
        "",
        f"DIRECT E2E = {h.get('direct_e2e')}",
        "",
        f"HIERARCHICAL E2E = {h.get('hierarchical_e2e')}",
        "",
        f"CANONICAL VALIDATION = {h.get('canonical_validation')}",
        "",
        f"SEMANTIC QUALITY WITH THINKING DISABLED = {h.get('semantic_quality')}",
        "",
        f"SEMANTIC WIN001 READINESS = {h.get('readiness')}",
        "",
        f"SEMANTIC WIN001 AUTHORIZED = {h.get('authorized')}",
        "",
        f"PRODUCTION DEFAULT = {h.get('production_default')}",
        "",
        f"SOURCE MAP = {h.get('source_map')}",
        "",
        f"PHASE 3B = {h.get('phase_3b')}",
        "",
        f"TESTS = {h.get('tests')}",
        "",
        f"NEXT ACTION = {h.get('next_action')}",
        "",
        "## 1. Result",
        "",
        str(h.get("result") or "UNKNOWN"),
        "",
        f"Classification: {h.get('result_notes') or 'none'}",
        "",
        "## 2. Provider calls",
        "",
        "Were any provider calls made? NO.",
        "Was A.13 repeated? NO.",
        "Was WIN001 called? NO.",
        "",
        "## 3. A.13 technical facts preserved",
        "",
        "Does A.13 prove V2 grammar acceptance? YES.",
        "Does A.13 prove thinking-disabled acceptance? YES.",
        "Did A.13 use 0 provider-reported thinking tokens? YES.",
        "A.13 evidence was not edited and not repaired.",
        "",
        "## 4. Exact A.13 link failure",
        "",
        f"Recorded error: {replay.get('a13_recorded_error')}",
        f"Replay structured parse: {replay.get('structured_parse')}",
        f"Replay decoder: {replay.get('v2_decoder')}",
        f"Replay validator: {replay.get('v2_validator')}",
        f"Reproduced: {replay.get('reproduced')}",
        "",
    ]
    for item in failures:
        lines.append(
            f"- records[{item.get('record_index')}] kind={item.get('record_kind')} "
            f"l={item.get('l')} targets={item.get('targets')} "
            f"reasons={item.get('reasons')}"
        )
    lines.extend(
        [
            "",
            "## 5. What l means",
            "",
            str(contract.get("l_meaning") or ""),
            f"Index base: {contract.get('index_base')}",
            f"Self-links: {contract.get('self_links')}",
            f"Allowed targets: {contract.get('allowed_target_kinds')}",
            f"Cardinality: {contract.get('cardinality')}",
            f"Canonical mapping: {contract.get('canonical_mapping')}",
            "",
            "## 6. Root cause",
            "",
            str(h.get("root_cause")),
            "A.13 prompt/wrapper rules were ambiguous. The model is not blamed.",
            f"1.2 audit: {(prompt.get('historical_1_2') or {}).get('ambiguous_phrases')}",
            f"Wrapper: {(prompt.get('a13_wrapper') or {}).get('introduced_ambiguity_beyond_1_2')}",
            "Did an example encourage self-links? NO — 1.2 example used empty l[].",
            "Wording 'index locaux de CE transport' + 'l=TOPIC' / 'l=IDEA' could be read as current-record index.",
            "",
            "## 7. Schema",
            "",
            f"Was schema changed? {schema.get('schema_changed')}",
            "If no, A.13 grammar acceptance remains applicable: YES.",
            "Is another grammar canary needed? NO — schema still semantic-transport-v2.",
            f"RAW / ADAPTED = {schema.get('raw_bytes')} / {schema.get('adapted_bytes')}",
            "",
            "## 8. Prompt version",
            "",
            f"Candidate prompt: {h.get('prompt_version')}",
            "Historical window-analysis-1.2 is frozen and unused by the candidate path.",
            "",
            "## 9. Corrected fixture / FakeAI",
            "",
            f"FakeAI local V2: {h.get('fakeai_local_v2')}",
            f"Direct E2E: {h.get('direct_e2e')}",
            f"Hierarchical E2E: {h.get('hierarchical_e2e')}",
            f"Deferred recovered: {e2e.get('deferred_recovered')}",
            f"Canonical SourceMap published? NO. Canonical validator on FakeAI reconstruction: {h.get('canonical_validation')}",
            "",
            "## 10. Budgets and future WIN001",
            "",
            f"Synthetic worst-case: {worst.get('local_tokens')} (target <= {worst.get('target_json_local_tokens')})",
            f"Future 7-window max input: {preflight.get('max_future_window_input')}",
            f"All under 35000: {preflight.get('all_under_35000')}",
            f"Future WIN001 cache: {identity.get('cache')}",
            f"Forensic collision: {identity.get('forensic_collides')}",
            "Does future candidate cache collide with historical calls? NO.",
            "Does forensic identity collide? NO.",
            "",
            "## 11. Semantic quality",
            "",
            "Is semantic quality of thinking-disabled verified on real transcript? NO.",
            "UNVERIFIED_REAL remains the primary purpose of a future WIN001 semantic canary.",
            f"Readiness: {h.get('readiness')}",
            "Authorized now? NO.",
            "",
            "## 12. Production / state",
            "",
            "Is production default changed? NO.",
            "Is source_map absent? YES.",
            "Phase 3B remains INCOMPLETE. State is not SUCCESS.",
            "",
            "## 13. Next phase",
            "",
            "If READY_FOR_HUMAN_AUTHORIZATION: STOP.",
            "The next separately authorized phase may be 3B.7.7A.15 —",
            "REAL V2 SMALL WIN001 SEMANTIC CANARY.",
            "ONE real Anthropic semantic call maximum.",
            "Planner: window-planner-v2.1-small",
            "Prompt: window-analysis-1.2.1",
            "Transport: semantic-transport-v2",
            "Thinking: disabled",
            "max_attempts: 1. NO retry. NO WIN002–WIN007. NO consolidation.",
            "DO NOT execute A.15 in this phase.",
            "",
            f"TESTS = {h.get('tests')}",
            "",
            "NEXT ACTION = HUMAN REVIEW",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


__all__ = ["render_report"]
