"""Constantes 3B.7.7A.36 — forensics canary A.35 + durcissement contrat offline."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis_v31_global_grammar_canary.constants import (
    A34_SCHEMA_ADAPTED_BYTES,
    A34_SCHEMA_HASH,
    A34_SCHEMA_RAW_BYTES,
    AUTHORIZATION_SCOPE as A35_AUTHORIZATION_SCOPE,
    CANARY_MAX_OUTPUT_TOKENS,
    CANARY_SUBDIR,
    CANARY_TRANSCRIPT_ID,
    CANARY_WINDOW_ID,
    EXECUTION_ARTIFACT as A35_EXECUTION_ARTIFACT,
    FIXTURE_ARTIFACT as A35_FIXTURE_ARTIFACT,
    MODEL as A35_MODEL,
    PRODUCTION_LOCAL_ESTIMATE_TOKENS,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PRODUCTION_NORMALIZED_CHARS,
    PRODUCTION_PROVIDER_ADJUSTED_TOKENS,
    PROJECT_NAME,
    PROVIDER as A35_PROVIDER,
    REPORT_NAME as A35_REPORT_NAME,
    THINKING_MODE as A35_THINKING_MODE,
)
from app.source_analysis_v31_global_preflight.constants import (
    ALLOWED_DROP_REASONS,
    FORBIDDEN_DROP_REASONS,
    GLOBAL_PROMPT_VERSION as A34_PROMPT_VERSION,
    GLOBAL_TRANSPORT_VERSION as A34_TRANSPORT_VERSION,
    IDEA_DISPOSITION_COVERAGE_REQUIRED,
    IDEA_KIND_POLICY,
    PROPOSED_ARCHITECTURE,
    PROPOSED_RELATION_POLICY,
    PROPOSED_THINKING_POLICY,
    RELATION_POLICY_OPTION,
    RELATION_QUALITY_TECHNICAL_DEBT,
    REPORT_NAME as A34_REPORT_NAME,
    TRANSPORT_SCHEMA_ARTIFACT as A34_TRANSPORT_SCHEMA_ARTIFACT,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.36"
MODE = "GLOBAL_CONSOLIDATION_CANARY_FORENSICS_AND_DISPOSITION_CONTRACT_HARDENING"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
REAL_CONSOLIDATION_CALLS = 0
GRAMMAR_CANARY_CALLS = 0
CONSOLIDATION_AUTHORIZED = False
GRAMMAR_CANARY_AUTHORIZED = False
SOURCE_MAP_PUBLICATION_AUTHORIZED = False

A34_STATUS_PRESERVED = "PASS"
A35_STATUS_PRESERVED = "FAIL"
assert A34_STATUS_PRESERVED == "PASS"
assert A35_STATUS_PRESERVED == "FAIL"

PROVIDER = A35_PROVIDER
MODEL = A35_MODEL
THINKING_MODE = A35_THINKING_MODE
THINKING_POLICY = PROPOSED_THINKING_POLICY
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert THINKING_MODE == "disabled"
assert THINKING_POLICY == "THINKING_DISABLED"
assert PRODUCTION_MAX_OUTPUT_TOKENS == 32000
assert CANARY_MAX_OUTPUT_TOKENS == 2048
assert PROPOSED_ARCHITECTURE == "ONE_GLOBAL_CONSOLIDATION_CALL"
assert IDEA_KIND_POLICY == "KEEP_EMPTY_GLOBALLY"
assert RELATION_POLICY_OPTION == "C"
assert RELATION_QUALITY_TECHNICAL_DEBT == "YES"
assert IDEA_DISPOSITION_COVERAGE_REQUIRED == 100

OLD_PROMPT_VERSION = A34_PROMPT_VERSION
OLD_TRANSPORT_VERSION = A34_TRANSPORT_VERSION
assert OLD_PROMPT_VERSION == "global-consolidation-1.0"
assert OLD_TRANSPORT_VERSION == "global-consolidation-transport-1.0"

NEXT_PROMPT_VERSION = "global-consolidation-1.0.1"
NEXT_TRANSPORT_VERSION = "global-consolidation-transport-1.1"

A34_SCHEMA_RAW = A34_SCHEMA_RAW_BYTES
A34_SCHEMA_ADAPTED = A34_SCHEMA_ADAPTED_BYTES
assert A34_SCHEMA_RAW == 1040
assert A34_SCHEMA_ADAPTED == 1195
assert A34_SCHEMA_HASH.startswith("7a8ce905")
assert A34_SCHEMA_HASH.endswith("61633")

NEXT_SCHEMA_RAW_BYTES = 1182
NEXT_SCHEMA_ADAPTED_BYTES = 1337
NEXT_SCHEMA_HASH = (
    "c98e57c3497843abdf294abfb2b691638ed54bdd86e651ab813efca563c6b3e6"
)
NEXT_SCHEMA_RAW_DELTA = NEXT_SCHEMA_RAW_BYTES - A34_SCHEMA_RAW
NEXT_SCHEMA_ADAPTED_DELTA = NEXT_SCHEMA_ADAPTED_BYTES - A34_SCHEMA_ADAPTED
SCHEMA_CHANGED = True
NEW_GRAMMAR_CANARY_REQUIRED = True

A35_REQUEST_ID = "req_011CfW2QDYYiMNWoMSoeucx1"
A35_REQUEST_IDENTITY = (
    "64eb0c5d4582c06d4559d9a3cf12a1d5ac99fe8262806b113258f57468fc35a9"
)
A35_RAW_SHA256 = (
    "9e2b951e6e130b0b6600534797d333452afa6ac36d80b4adb6cdc60a1855fe96"
)
A35_RAW_SIZE = 4411
A35_HTTP_STATUS = 200
A35_FINISH_REASON = "end_turn"
A35_THINKING_TOKENS = 0
A35_COST_USD = 0.022908
A35_ELAPSED_SECONDS = 17.7
A35_ELAPSED_MS = 17717
A35_AUTHORIZED_CALLS = 1
A35_ACTUAL_CALLS = 1
A35_SUCCESSFUL_CALLS = 1
A35_RETRIES = 0
A35_PASTORAL_DATA_SENT = False
A35_INPUT_TOKENS = 3329
A35_OUTPUT_TOKENS = 1625
A35_GRAMMAR_ACCEPTED = True
A35_STRUCTURED_PARSE = "PASS"
A35_DECODER = "PASS"
A35_HANDLES = "PASS"
A35_COVERAGE = 100.0
A35_SILENT_DROPS = 0
A35_TRACEABILITY = "PASS"
A35_GLOBAL_VALIDATOR = "FAIL"
A35_CANONICAL_RECONSTRUCTION = "PASS"
A35_SEMANTIC_REVIEW = "FAIL"
A35_DROP_INPUT_ID = "SYN001:I3"
A35_DROP_OP = "DROP"
A35_DROP_PROSE = (
    "Non-substantive fragment ('and then uh') with no propositional content."
)
A35_DROP_FIELD_OP = "o"
A35_DROP_FIELD_REASON = "w"
CANONICAL_DROP_TOKEN = "non_substantive_fragment"
A35_COMPANION_INPUT_ID = "SYN002:I2"
A35_COMPANION_OP = "KEEP"
A35_REPETITION_COUNT = 0

DROP_REASON_CLASS = "MACHINE_CONTROLLED_ENUM"
SELECTED_DISPOSITION_MODEL = "REPRESENTATION_ENUM_PLUS_INDEPENDENT_RELATIONS"
LINK_RELATED_CONTRACT = "RETIRED_FROM_REPRESENTATION_ENUM"
REPETITION_REQUIREMENT = "OPTIONAL_SEMANTIC_ENRICHMENT"
FIXTURE_OVERCONSTRAINED = True

READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY = "NO"
READINESS_DECISION = "READY_FOR_SECOND_GLOBAL_GRAMMAR_CANARY"

A35_FORENSIC_RELATIVE = (
    f"audit/canary/global_consolidation_transport_v1/provider_forensics/"
    f"{CANARY_WINDOW_ID}/{A35_REQUEST_IDENTITY}"
)

FORENSICS_ARTIFACT = "global_consolidation_a35_failure_forensics.json"
DISPOSITION_ARTIFACT = "global_consolidation_disposition_semantics.json"
DROP_CONTRACT_ARTIFACT = "global_consolidation_drop_reason_contract.json"
REPETITION_ARTIFACT = "global_consolidation_repetition_policy.json"
FIXTURE_REVIEW_ARTIFACT = "global_consolidation_a35_fixture_expectation_review.json"
REDESIGN_ARTIFACT = "global_consolidation_contract_redesign.json"
NEXT_SCHEMA_ARTIFACT = "global_consolidation_next_schema.json"
NEXT_FIXTURE_ARTIFACT = "global_consolidation_next_synthetic_fixture.json"
COUNTERFACTUAL_ARTIFACT = "global_consolidation_a35_drop_only_counterfactual.json"
READINESS_ARTIFACT = "global_consolidation_post_a36_readiness.json"
TEST_DELTA_ARTIFACT = "source_analysis_a36_test_delta.json"
REPORT_NAME = "PHASE_3B77A36_GLOBAL_CONSOLIDATION_CANARY_FORENSICS_REPORT.md"

PROTECTED_A34 = (
    f"audit/{A34_REPORT_NAME}",
    f"audit/{A34_TRANSPORT_SCHEMA_ARTIFACT}",
)
PROTECTED_A35 = (
    f"audit/{A35_REPORT_NAME}",
    f"audit/canary/global_consolidation_transport_v1/{A35_EXECUTION_ARTIFACT}",
    f"audit/canary/global_consolidation_transport_v1/{A35_FIXTURE_ARTIFACT}",
    f"{A35_FORENSIC_RELATIVE}/provider_raw_response.bin",
    f"{A35_FORENSIC_RELATIVE}/provider_http_envelope.json",
    "audit/canary/global_consolidation_transport_v1/canary_real_call.lock",
)
PROTECTED_HISTORICAL = PROTECTED_A34 + PROTECTED_A35

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_canary_forensics.py",
    "app/tests/test_source_analysis_v31_global_canary_forensics_audit.py",
    "app/tests/test_source_analysis_v31_global_grammar_canary.py",
    "app/tests/test_source_analysis_v31_global_preflight.py",
)

PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
NEXT_ACTION = "HUMAN REVIEW"
LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN = "YES"

assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert REAL_WINDOW_CALLS == 0
assert REAL_CONSOLIDATION_CALLS == 0
assert GRAMMAR_CANARY_CALLS == 0
assert READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY == "NO"
assert not source_map_path(PROJECT_NAME).is_file() or SOURCE_MAP_STATUS == "NOT PUBLISHED"

__all__ = [
    "A34_PROMPT_VERSION",
    "A34_SCHEMA_ADAPTED",
    "A34_SCHEMA_HASH",
    "A34_SCHEMA_RAW",
    "A34_STATUS_PRESERVED",
    "A34_TRANSPORT_VERSION",
    "A35_ACTUAL_CALLS",
    "A35_AUTHORIZATION_SCOPE",
    "A35_AUTHORIZED_CALLS",
    "A35_CANONICAL_RECONSTRUCTION",
    "A35_COMPANION_INPUT_ID",
    "A35_COMPANION_OP",
    "A35_COST_USD",
    "A35_COVERAGE",
    "A35_DECODER",
    "A35_DROP_FIELD_OP",
    "A35_DROP_FIELD_REASON",
    "A35_DROP_INPUT_ID",
    "A35_DROP_OP",
    "A35_DROP_PROSE",
    "A35_ELAPSED_MS",
    "A35_ELAPSED_SECONDS",
    "A35_FINISH_REASON",
    "A35_FORENSIC_RELATIVE",
    "A35_GLOBAL_VALIDATOR",
    "A35_GRAMMAR_ACCEPTED",
    "A35_HANDLES",
    "A35_HTTP_STATUS",
    "A35_INPUT_TOKENS",
    "A35_MODEL",
    "A35_OUTPUT_TOKENS",
    "A35_PASTORAL_DATA_SENT",
    "A35_PROVIDER",
    "A35_RAW_SHA256",
    "A35_RAW_SIZE",
    "A35_REPETITION_COUNT",
    "A35_REPORT_NAME",
    "A35_REQUEST_ID",
    "A35_REQUEST_IDENTITY",
    "A35_RETRIES",
    "A35_SEMANTIC_REVIEW",
    "A35_SILENT_DROPS",
    "A35_STATUS_PRESERVED",
    "A35_STRUCTURED_PARSE",
    "A35_SUCCESSFUL_CALLS",
    "A35_THINKING_MODE",
    "A35_THINKING_TOKENS",
    "A35_TRACEABILITY",
    "ALLOWED_DROP_REASONS",
    "CANARY_MAX_OUTPUT_TOKENS",
    "CANARY_SUBDIR",
    "CANARY_TRANSCRIPT_ID",
    "CANARY_WINDOW_ID",
    "CANONICAL_DROP_TOKEN",
    "CONSOLIDATION_AUTHORIZED",
    "COUNTERFACTUAL_ARTIFACT",
    "DISPOSITION_ARTIFACT",
    "DROP_CONTRACT_ARTIFACT",
    "DROP_REASON_CLASS",
    "FIXTURE_OVERCONSTRAINED",
    "FIXTURE_REVIEW_ARTIFACT",
    "FOCUSED_TEST_PATHS",
    "FORBIDDEN_DROP_REASONS",
    "FORENSICS_ARTIFACT",
    "GRAMMAR_CANARY_AUTHORIZED",
    "GRAMMAR_CANARY_CALLS",
    "IDEA_DISPOSITION_COVERAGE_REQUIRED",
    "IDEA_KIND_POLICY",
    "LINK_RELATED_CONTRACT",
    "LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN",
    "MODE",
    "MODEL",
    "NEW_GRAMMAR_CANARY_REQUIRED",
    "NEXT_ACTION",
    "NEXT_FIXTURE_ARTIFACT",
    "NEXT_PROMPT_VERSION",
    "NEXT_SCHEMA_ADAPTED_BYTES",
    "NEXT_SCHEMA_ADAPTED_DELTA",
    "NEXT_SCHEMA_ARTIFACT",
    "NEXT_SCHEMA_HASH",
    "NEXT_SCHEMA_RAW_BYTES",
    "NEXT_SCHEMA_RAW_DELTA",
    "NEXT_TRANSPORT_VERSION",
    "OLD_PROMPT_VERSION",
    "OLD_TRANSPORT_VERSION",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_LOCAL_ESTIMATE_TOKENS",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PRODUCTION_NORMALIZED_CHARS",
    "PRODUCTION_PROVIDER_ADJUSTED_TOKENS",
    "PROJECT_NAME",
    "PROPOSED_ARCHITECTURE",
    "PROPOSED_RELATION_POLICY",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "READINESS_ARTIFACT",
    "READINESS_DECISION",
    "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY",
    "REAL_CONSOLIDATION_CALLS",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "REDESIGN_ARTIFACT",
    "RELATION_POLICY_OPTION",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPETITION_ARTIFACT",
    "REPETITION_REQUIREMENT",
    "REPORT_NAME",
    "SCHEMA_CHANGED",
    "SCHEMA_VERSION",
    "SELECTED_DISPOSITION_MODEL",
    "SOURCE_MAP_PUBLICATION_AUTHORIZED",
    "SOURCE_MAP_STATUS",
    "TEST_DELTA_ARTIFACT",
    "THINKING_MODE",
    "THINKING_POLICY",
]
