"""Phase 4B.2.15 — one real Terra Semantic Gate 2.0.2 h11 negative canary."""

from app.book_semantic_gate_4b215.constants import (
    AUTHORIZED_REMOTE_TERRA_INVOCATIONS,
    AUTHORIZED_SONNET_CALLS,
    HISTORICAL_4B211_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
    PHASE,
    PRODUCTION_PIPELINE_HOOK,
    SEMANTIC_GATE_202_ENABLED,
    SELECTED_CASE_HANDLE,
    SELECTED_CASE_ID,
)

assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_H11_STATUS == "PARTIAL"
assert HISTORICAL_4B211_STATUS == "PARTIAL"
assert SELECTED_CASE_HANDLE == "h11"
assert SELECTED_CASE_ID == "4b276_p4_new_implication"
assert SEMANTIC_GATE_202_ENABLED is False
assert PRODUCTION_PIPELINE_HOOK is False

__all__ = [
    "PHASE",
    "AUTHORIZED_REMOTE_TERRA_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "HISTORICAL_H01_STATUS",
    "HISTORICAL_H02_STATUS",
    "HISTORICAL_H11_STATUS",
    "HISTORICAL_4B211_STATUS",
]
