"""
Phase 4B.2.15 — One real Terra Semantic Gate 2.0.2 h11 negative canary.

NEW explicit one-shot authorization. AUTHORIZED REMOTE INVOCATIONS = 1.
Budget cap 0.10 USD. Contract 2.0.2-candidate. One paragraph only.
Does not relaunch h01 or h02. Does not modify historical canaries.
Does not activate Semantic Gate 2.0. Does not enable the 4B.2.14 bridge.
"""

from __future__ import annotations

from decimal import Decimal

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b210.constants import (
    H01_REQUEST_SHA256,
    H02_REQUEST_SHA256,
    H11_REQUEST_SHA256,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
    TRANSPORT_VERSION_20_CANDIDATE,
)
from app.book_semantic_gate_4b211.constants import HISTORICAL_4B210_STATUS
from app.book_semantic_gate_4b212.constants import (
    DECISION_BLOCK,
    DECISION_PASS,
    DECISION_REVIEW,
    HISTORICAL_4B211_COMPLETION_TOKENS,
    HISTORICAL_4B211_COST_USD,
    HISTORICAL_4B211_INPUT_TOKENS,
    HISTORICAL_4B211_REASONING_TOKENS,
    HISTORICAL_4B211_STATUS,
    PROMPT_VERSION_202_CANDIDATE,
)
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
)
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    SEMANTIC_TOKEN_BUDGET,
)
from app.book_semantic_gate_4b276.constants import (
    DISPUTED_CLAUSE,
    P4_EVIDENCE_HANDLES,
    SELECTED_CASE_HUMAN_LABEL as H11_HUMAN_LABEL,
    SELECTED_CASE_ORIGIN,
    SELECTED_CASE_REASON_CODES_ACCEPTABLE_AUDIT_ONLY,
    SELECTED_CASE_ROLE,
    TARGET_FAILURE_FAMILY,
)
from app.book_semantic_gate_4b28.constants import (
    H01_CASE_HANDLE,
    H02_CASE_HANDLE,
    H11_CASE_HANDLE,
    H11_CASE_ID,
    H11_COMPLETION_TOKENS,
    H11_COST_USD,
    H11_EVIDENCE_HANDLES,
    H11_INPUT_TOKENS,
    H11_REASONING_TOKENS,
)
from app.book_semantic_gate_4b29.constants import OFFSET_CONVENTION

PHASE = "4B.2.15"
PHASE_NAME = "ONE_REAL_TERRA_SEMANTIC_GATE_202_H11_NEGATIVE_CANARY"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B215_ONE_REAL_TERRA_SEMANTIC_GATE_202_"
    "H11_NEGATIVE_CANARY_ONLY"
)
AUTHORIZED_REMOTE_TERRA_INVOCATIONS = 1
AUTHORIZED_REMOTE_INVOCATIONS = 1
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
MAX_ENGINE_GENERATE = 1
MAX_REMOTE_INVOCATIONS = 1
MAX_HTTP_REQUESTS = 1
MAX_EXECUTION_ATTEMPTS = 1
RETRIES = 0
FALLBACKS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = True
SDK_MAX_RETRIES = 0

SEMANTIC_GATE_20_ENABLED = False
SEMANTIC_GATE_201_ENABLED = False
SEMANTIC_GATE_202_ENABLED = False
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
PROMPT_VERSION_20_ACTIVATED = False
PROMPT_VERSION_201_ACTIVATED = False
PROMPT_VERSION_202_ACTIVATED = False
TRANSPORT_VERSION_20_ACTIVATED = False
BRIDGE_4B214_ENABLED = False

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
STAGE_CANARY = "book_semantic_validation_canary_4b215"
PROMPT_VERSION = PROMPT_VERSION_202_CANDIDATE
TRANSPORT_VERSION = TRANSPORT_VERSION_20_CANDIDATE
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"
TOKEN_FIELD = "max_completion_tokens"
PRODUCTION_SDK_METHOD = "client.chat.completions.create"
GRANULARITY = "ONE_REQUEST_PER_PARAGRAPH"

SELECTED_CASE_HANDLE = H11_CASE_HANDLE
SELECTED_CASE_ID = H11_CASE_ID
SELECTED_CASE_HUMAN_LABEL = H11_HUMAN_LABEL
SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY = True
TARGET_UNIT_ID = "u04"
TARGET_CLAUSE = DISPUTED_CLAUSE
CHAPTER_ID = "CH016"
REQUIRED_UNIT_IDS = ("u00", "u01", "u02", "u03", "u04")
H11_EVIDENCE = P4_EVIDENCE_HANDLES

BUDGET_CAP_USD = Decimal("0.10")
BUDGET_CAP_DISPLAY = "0.10 USD"
PRICING_EFFECTIVE_DATE = "2026-09-18"
TERRA_INPUT_COST_PER_1M = Decimal("2.00")
TERRA_OUTPUT_COST_PER_1M = Decimal("12.00")
MIN_USABLE_OUTPUT_TOKENS = 5221
HISTORICAL_CONSERVATIVE_OUTPUT = CONSERVATIVE_MAX_OUTPUT_TOKENS
H02_COMPLETION_TOKENS = 5221
H02_COST_USD = 0.066036
H02_INPUT_TOKENS = 1692
H02_REASONING_TOKENS = 4595

HISTORICAL_4B212_STATUS = "PASS"
HISTORICAL_4B213_STATUS = "PASS"
HISTORICAL_4B214_STATUS = "PASS"
HISTORICAL_4B277_STATUS = "PARTIAL"

CODE_VERSION = "app.book_semantic_gate_4b215"

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert PROMPT_VERSION == "book-semantic-validator-2.0.2-candidate"
assert TRANSPORT_VERSION == "book-semantic-validation-transport-2.0-candidate"
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
assert TOKEN_FIELD == "max_completion_tokens"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert SELECTED_CASE_HANDLE == "h11"
assert SELECTED_CASE_ID == "4b276_p4_new_implication"
assert SELECTED_CASE_ORIGIN == "SYNTHETIC_VARIANT_OF_4B22_P4_SUPPORTED"
assert SELECTED_CASE_ROLE == "synthetic_negative"
assert SELECTED_CASE_HUMAN_LABEL == CLASS_UNSUPPORTED
assert SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY is True
assert TARGET_CLAUSE == (
    "which means that every believer is guaranteed a fearless death"
)
assert TARGET_UNIT_ID == "u04"
assert TARGET_FAILURE_FAMILY == "NEW_IMPLICATION_AND_UNCERTAINTY_STRENGTHENED"
assert H11_EVIDENCE == H11_EVIDENCE_HANDLES == (
    "IDEA226",
    "SRC006192",
    "SRC006193",
    "SRC006195",
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert H01_REQUEST_SHA256 == (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
assert H02_REQUEST_SHA256 == (
    "5ace261296d808437910f8f9efe247a80daebbb2237bc8af46bda56bf98d7897"
)
assert H11_REQUEST_SHA256 == (
    "b3cc1574858acdd5bdd0e223aa136d5058c4eb1deb1495cd9ad312d332e8c30f"
)
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_H11_STATUS == "PARTIAL"
assert HISTORICAL_4B210_STATUS == "PASS"
assert HISTORICAL_4B211_STATUS == "PARTIAL"
assert HISTORICAL_4B212_STATUS == "PASS"
assert HISTORICAL_4B213_STATUS == "PASS"
assert HISTORICAL_4B214_STATUS == "PASS"
assert HISTORICAL_4B277_STATUS == "PARTIAL"
assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert SDK_MAX_RETRIES == 0
assert PUBLICATION_AUTHORIZED is False
assert SEMANTIC_GATE_202_ENABLED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert BRIDGE_4B214_ENABLED is False
assert BUDGET_CAP_USD == Decimal("0.10")
assert CANONICAL_PYTHON_EXECUTABLE.endswith("python.exe")
assert CLASSIFICATIONS == (
    CLASS_SUPPORTED,
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    CLASS_NON_SUBSTANTIVE,
)
assert EXPECTED_OPENAI_SDK_VERSION == "2.43.0"
assert EXPECTED_PYTHON_VERSION == (3, 11, 9) or isinstance(EXPECTED_PYTHON_VERSION, tuple)
assert OFFSET_CONVENTION == "python3_str_unicode_code_points_half_open"
assert H11_COST_USD == 0.029556
assert H11_INPUT_TOKENS == 2562
assert H11_COMPLETION_TOKENS == 2036
assert H11_REASONING_TOKENS == 1647

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 600.0
CANARY_WINDOW_ID = "book-semantic-gate-4b215"

AUDIT_DIRNAME = "book_semantic_gate_4b215"
AUDIT_REAL_PARENT = "real"
AUDIT_PREFLIGHT = "preflight.json"
AUDIT_HASHES_PRE = "canonical_hashes_pre.json"
AUDIT_AUTHORIZATION = "authorization_manifest.json"
AUDIT_BUDGET = "budget_reservation.json"
AUDIT_REQUEST = "provider_request.json"
AUDIT_REQUEST_SHA = "request_sha256.json"
AUDIT_RAW_RESPONSE = "provider_response_raw.json"
AUDIT_USAGE = "provider_usage.json"
AUDIT_COST = "provider_cost.json"
AUDIT_CONTRACT = "contract_validation.json"
AUDIT_COVERAGE = "unit_coverage.json"
AUDIT_EVIDENCE = "evidence_validation.json"
AUDIT_SEMANTIC = "semantic_review.json"
AUDIT_HISTORICAL = "historical_comparison.json"
AUDIT_POLICY = "acceptance_policy.json"
AUDIT_REPLAY = "deterministic_replay.json"
AUDIT_SAFETY = "provider_safety.json"
AUDIT_HASHES_POST = "canonical_hashes_post.json"
AUDIT_TESTS = "offline_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_LOCK = "h11_202_real_call.lock"
AUDIT_INDEX = "book_semantic_gate_4b215_index.json"
REPORT_NAME = "PHASE_4B215_ONE_REAL_TERRA_SEMANTIC_GATE_202_H11_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_ONE_REAL_CHAPTER_EXPERIMENT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "AUDIT_AUTHORIZATION",
    "AUDIT_BUDGET",
    "AUDIT_CONTRACT",
    "AUDIT_COST",
    "AUDIT_COVERAGE",
    "AUDIT_DIRNAME",
    "AUDIT_EVIDENCE",
    "AUDIT_HASHES_POST",
    "AUDIT_HASHES_PRE",
    "AUDIT_HISTORICAL",
    "AUDIT_INDEX",
    "AUDIT_LOCK",
    "AUDIT_POLICY",
    "AUDIT_PREFLIGHT",
    "AUDIT_RAW_RESPONSE",
    "AUDIT_READINESS",
    "AUDIT_REAL_PARENT",
    "AUDIT_REPLAY",
    "AUDIT_REQUEST",
    "AUDIT_REQUEST_SHA",
    "AUDIT_SAFETY",
    "AUDIT_SEMANTIC",
    "AUDIT_TESTS",
    "AUDIT_USAGE",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_REMOTE_TERRA_INVOCATIONS",
    "BUDGET_CAP_USD",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CHAPTER_ID",
    "CLASSIFICATIONS",
    "DECISION_BLOCK",
    "DECISION_PASS",
    "DECISION_REVIEW",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_OPENAI_SDK_VERSION",
    "EXPECTED_SOURCE_MAP",
    "GRANULARITY",
    "H11_EVIDENCE",
    "HISTORICAL_4B211_STATUS",
    "HISTORICAL_H01_STATUS",
    "HISTORICAL_H02_STATUS",
    "HISTORICAL_H11_STATUS",
    "MIN_USABLE_OUTPUT_TOKENS",
    "MODEL",
    "PHASE",
    "PROMPT_VERSION",
    "PROVIDER",
    "REPORT_NAME",
    "REQUIRED_UNIT_IDS",
    "SELECTED_CASE_HANDLE",
    "SELECTED_CASE_ID",
    "SELECTED_CASE_REASON_CODES_ACCEPTABLE_AUDIT_ONLY",
    "TARGET_CLAUSE",
    "TARGET_UNIT_ID",
    "TRANSPORT_VERSION",
]
