"""Cover-generator constants. No provider, no download, no export."""

from __future__ import annotations

PACKAGE = "app.cover"
SCHEMA_VERSION = "cover-generator-v1"
AUTHOR_LIBRARY_SCHEMA_VERSION = "author-library-v1"

COVER_MODE = "TWO_SEPARATE_PAGES"
WRAPAROUND_COVER = False
SPINE_COMPUTED = False

TRIM_WIDTH_IN = 6.0
TRIM_HEIGHT_IN = 9.0
DEFAULT_BLEED_MM = 3.0
DEFAULT_DPI = 300
DEFAULT_SAFETY_IN = 0.25
MM_PER_INCH = 25.4

DESCRIPTION_WORD_MIN = 130
DESCRIPTION_WORD_MAX = 180

COVER_VERSION_DRAFT = "draft-v1"
COVER_STATUS_DRAFT = "DRAFT"

IMAGE_GENERATION_AUTHORIZED = False
COVER_EXPORT_AUTHORIZED = False
NETWORK_CALLS_AUTHORIZED = False
MODEL_DOWNLOADS_AUTHORIZED = False
PAID_CALLS_AUTHORIZED = False
DEFAULT_PAID_PROVIDER = None
AUTOMATIC_PAID_RETRIES = False

CONTENT_STATUSES = (
    "NOT_STARTED",
    "DRAFT",
    "PENDING_HUMAN_REVIEW",
    "APPROVED",
    "MISSING_OPTIONAL",
)

VERIFICATION_STATUSES = (
    "UNVERIFIED",
    "PROVIDED",
    "VERIFIED",
)

PUBLICATION_FACT_STATUSES = (
    "NOT_APPROVED",
    "APPROVED_FOR_PUBLICATION",
)

ATTRIBUTION_ROLES = (
    "BOOK_AUTHOR",
    "RECORDED_SPEAKER",
    "COMMISSIONING_CLIENT",
    "PROJECT_OWNER",
    "DEPOSITOR",
)

COMPATIBILITY_RATINGS = (
    "LIKELY_COMPATIBLE",
    "POSSIBLY_COMPATIBLE_WITH_OPTIMIZATION",
    "NOT_RECOMMENDED",
    "INSUFFICIENT_INFORMATION",
)

PROHIBITED_BACK_COVER_ELEMENTS = (
    "testimonial",
    "expert_endorsement",
    "award",
    "barcode",
    "isbn",
    "invented_quotation",
    "invented_result",
    "invented_promise",
)

__all__ = [
    "ATTRIBUTION_ROLES",
    "AUTHOR_LIBRARY_SCHEMA_VERSION",
    "AUTOMATIC_PAID_RETRIES",
    "COMPATIBILITY_RATINGS",
    "CONTENT_STATUSES",
    "COVER_MODE",
    "COVER_EXPORT_AUTHORIZED",
    "COVER_STATUS_DRAFT",
    "COVER_VERSION_DRAFT",
    "DEFAULT_BLEED_MM",
    "DEFAULT_DPI",
    "DEFAULT_PAID_PROVIDER",
    "DEFAULT_SAFETY_IN",
    "DESCRIPTION_WORD_MAX",
    "DESCRIPTION_WORD_MIN",
    "IMAGE_GENERATION_AUTHORIZED",
    "MM_PER_INCH",
    "MODEL_DOWNLOADS_AUTHORIZED",
    "NETWORK_CALLS_AUTHORIZED",
    "PACKAGE",
    "PAID_CALLS_AUTHORIZED",
    "PROHIBITED_BACK_COVER_ELEMENTS",
    "SCHEMA_VERSION",
    "SPINE_COMPUTED",
    "TRIM_HEIGHT_IN",
    "TRIM_WIDTH_IN",
    "WRAPAROUND_COVER",
]
