"""Constantes 3B.7.6 — readiness audit + contrat canary WIN001."""

from __future__ import annotations

from app.source_analysis.consolidation_models import (
    CONSOLIDATION_CONNECT_TIMEOUT_SECONDS,
    CONSOLIDATION_MAX_ATTEMPTS,
    CONSOLIDATION_MAX_OUTPUT_TOKENS,
    CONSOLIDATION_READ_TIMEOUT_SECONDS,
    CONSOLIDATION_SAFE_INPUT_BUDGET_TOKENS,
    STAGE_CONSOLIDATION,
)
from app.source_analysis.window_models import (
    STAGE_WINDOW,
    TARGET_MODEL,
    TARGET_PROVIDER,
    WINDOW_CONNECT_TIMEOUT_SECONDS,
    WINDOW_FALLBACK,
    WINDOW_MAX_ATTEMPTS,
    WINDOW_MAX_OUTPUT_TOKENS,
    WINDOW_READ_TIMEOUT_SECONDS,
    WINDOW_RETRY,
)
from app.source_analysis.window_prompt import WINDOW_ANALYSIS_PROMPT_VERSION_V10
from app.source_analysis_hybrid.constants import (
    CONSOLIDATION_PROMPT_VERSION,
    CONSOLIDATION_TRANSPORT_VERSION,
    HARD_MAX_INPUT_TOKENS,
    OVERLAP_POLICY,
    PLANNER_VERSION,
    TARGET_INPUT_TOKENS,
    WINDOW_TRANSPORT_VERSION,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.6"
MODE = "OFFLINE_PRODUCTION_READINESS"

READINESS_ARTIFACT_NAME = "source_analysis_hybrid_production_readiness.json"
REAL_CALL_PLAN_ARTIFACT_NAME = "source_analysis_hybrid_real_call_plan.json"
FAILURE_MATRIX_ARTIFACT_NAME = "source_analysis_hybrid_failure_matrix.json"
DRY_RUN_ARTIFACT_NAME = "source_analysis_hybrid_win001_dry_run.json"
REPORT_NAME = (
    "PHASE_3B76_HYBRID_PRODUCTION_EXECUTION_READINESS_REAL_CALL_PLAN_REPORT.md"
)

PHASE_3B_STATUS = "INCOMPLETE"
NEXT_PHASE = "3B.7.7A_REAL_WIN001_CANARY"
NEXT_PHASE_LABEL = "3B.7.7A — REAL WIN001 CANARY"

AUTHORIZATION_SCOPE_WIN001_ONLY = "WIN001_ONLY"
AUTHORIZATION_SCOPE_BOUNDED_WIN001_ONLY = "BOUNDED_WIN001_ONLY"
AUTHORIZATION_SCOPE_REMAINING_WINDOWS = "REMAINING_WINDOWS"
AUTHORIZATION_SCOPE_SMALL_V21_WIN001_ONLY = "SMALL_V21_WIN001_ONLY"
SMALL_V21_EXECUTION_CONTRACT_NAME = (
    "source_analysis_small_win001_execution_contract.json"
)
CANARY_WINDOW_ID = "WIN001"
MAX_NEW_CALLS_WIN001 = 1
MAX_NEW_CALLS_REMAINING = 2
MAX_ATTEMPTS = 1
AUTO_CONTINUE = False
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONSOLIDATION = False
AUTO_PUBLICATION = False

STAGE = STAGE_WINDOW
CONSOLIDATION_STAGE = STAGE_CONSOLIDATION
PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V10
TRANSPORT_VERSION = WINDOW_TRANSPORT_VERSION

OUTPUT_SCENARIOS = (5000, 10000, 20000, 32000)

PHASE_3B75_NOW_HISTORICAL = (
    "audit/PHASE_3B75_HYBRID_CANONICAL_RECONSTRUCTION_END_TO_END_FAKE_AI_REPORT.md",
    "audit/source_analysis_hybrid_canonical_reconstruction.json",
    "audit/source_analysis_hybrid_end_to_end_fake_ai.json",
    "audit/source_analysis_hybrid_reconstruction_real_preflight.json",
)

__all__ = [
    "AUTHORIZATION_SCOPE_BOUNDED_WIN001_ONLY",
    "AUTHORIZATION_SCOPE_REMAINING_WINDOWS",
    "AUTHORIZATION_SCOPE_SMALL_V21_WIN001_ONLY",
    "AUTHORIZATION_SCOPE_WIN001_ONLY",
    "SMALL_V21_EXECUTION_CONTRACT_NAME",
    "AUTO_CONSOLIDATION",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_PUBLICATION",
    "AUTO_RETRY",
    "CANARY_WINDOW_ID",
    "CONSOLIDATION_CONNECT_TIMEOUT_SECONDS",
    "CONSOLIDATION_MAX_ATTEMPTS",
    "CONSOLIDATION_MAX_OUTPUT_TOKENS",
    "CONSOLIDATION_PROMPT_VERSION",
    "CONSOLIDATION_READ_TIMEOUT_SECONDS",
    "CONSOLIDATION_SAFE_INPUT_BUDGET_TOKENS",
    "CONSOLIDATION_STAGE",
    "CONSOLIDATION_TRANSPORT_VERSION",
    "DRY_RUN_ARTIFACT_NAME",
    "FAILURE_MATRIX_ARTIFACT_NAME",
    "HARD_MAX_INPUT_TOKENS",
    "MAX_ATTEMPTS",
    "MAX_NEW_CALLS_REMAINING",
    "MAX_NEW_CALLS_WIN001",
    "MODE",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "OVERLAP_POLICY",
    "OUTPUT_SCENARIOS",
    "PHASE",
    "PHASE_3B75_NOW_HISTORICAL",
    "PHASE_3B_STATUS",
    "PLANNER_VERSION",
    "PROMPT_VERSION",
    "READINESS_ARTIFACT_NAME",
    "REAL_CALL_PLAN_ARTIFACT_NAME",
    "REPORT_NAME",
    "SCHEMA_VERSION",
    "STAGE",
    "TARGET_INPUT_TOKENS",
    "TARGET_MODEL",
    "TARGET_PROVIDER",
    "TRANSPORT_VERSION",
    "WINDOW_CONNECT_TIMEOUT_SECONDS",
    "WINDOW_FALLBACK",
    "WINDOW_MAX_ATTEMPTS",
    "WINDOW_MAX_OUTPUT_TOKENS",
    "WINDOW_READ_TIMEOUT_SECONDS",
    "WINDOW_RETRY",
]
