"""Constantes 3B.7.7A.33 — canonicalisation SRC étroite + revalidation WIN007. 0 provider."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis.window_signature import WindowSignatureInputs
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CURRENT_SRC_REFERENCE_POLICY_VERSION,
    HISTORICAL_SRC_REFERENCE_POLICY_VERSION,
    SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE,
    SRC_REFERENCE_POLICY_VERSION_10_STRICT,
    SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION,
    WINDOW_ANALYSIS_PROMPT_VERSION_V140,
)
from app.source_analysis_local_v3.schema import (
    semantic_transport_v3_fingerprint,
    semantic_transport_v31_local_lite_fingerprint,
)
from app.source_analysis_local_v3.src_policy import (
    CORRECTION_REASON,
    PIPELINE_POSITION,
    SIGNATURE_DECISION as SRC_SIGNATURE_DECISION,
)
from app.source_analysis_v3_second_window.constants import EXPECTED_SCHEMA_HASH
from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)
from app.source_analysis_v31_src_typo_forensics.constants import (
    A18_PROOF_STILL_APPLIES as A32_A18_PROOF,
    A19_CANONICAL,
    A19_MALFORMED,
    A19_STATUS,
    A21_STATUS,
    A22_STATUS,
    A23_STATUS,
    A24_STATUS,
    A25_STATUS,
    A26_STATUS,
    A261_STATUS,
    A27_STATUS,
    A28_STATUS,
    A29_STATUS,
    A30_STATUS,
    A31_STATUS_UNCHANGED,
    A31_VALIDATOR_ERROR,
    EXPECTED_CANONICAL,
    MALFORMED_TOKEN,
    NUMERIC_PAYLOAD,
    PROTECTED_HISTORICAL as A32_PROTECTED_HISTORICAL,
    RECORD_INDEX,
    RECORD_S_POSITION,
    REPORT_NAME as A32_REPORT_NAME,
    WIN007_COST_USD,
    WIN007_ELAPSED_MS,
    WIN007_FINISH,
    WIN007_FORENSIC,
    WIN007_FORENSIC_RELATIVE,
    WIN007_HTTP,
    WIN007_INPUT_TOKENS,
    WIN007_OUTPUT_TOKENS,
    WIN007_OWNED_SRC_COUNT,
    WIN007_RAW_SHA256,
    WIN007_RAW_SIZE,
    WIN007_REQUEST_ID,
    WIN007_SIGNATURE,
    WIN007_THINKING,
    WIN007_WORD_COUNT,
    WINDOW_ID,
    WINDOW_SPECS,
    CANONICAL_ARTIFACT as A32_CANONICAL_ARTIFACT,
    COUNTERFACTUAL_ARTIFACT as A32_COUNTERFACTUAL_ARTIFACT,
    DECISION_ARTIFACT as A32_DECISION_ARTIFACT,
    HISTORY_ARTIFACT as A32_HISTORY_ARTIFACT,
    OPTIONS_ARTIFACT as A32_OPTIONS_ARTIFACT,
    ROOT_FAILURE_ARTIFACT as A32_ROOT_FAILURE_ARTIFACT,
    SEMANTIC_ARTIFACT as A32_SEMANTIC_ARTIFACT,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.33"
MODE = "NARROW_SRC_CANONICALIZATION_WIN007_REVALIDATION_OFFLINE"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
WIN007_NEW_PROVIDER_CALL = False
CONSOLIDATION_AUTHORIZED = False
GRAMMAR_CANARY_AUTHORIZED = False

A19_STATUS_UNCHANGED = A19_STATUS
A21_STATUS_UNCHANGED = A21_STATUS
A22_STATUS_UNCHANGED = A22_STATUS
A23_STATUS_UNCHANGED = A23_STATUS
A24_STATUS_UNCHANGED = A24_STATUS
A25_STATUS_UNCHANGED = A25_STATUS
A26_STATUS_UNCHANGED = A26_STATUS
A261_STATUS_UNCHANGED = A261_STATUS
A27_STATUS_UNCHANGED = A27_STATUS
A28_STATUS_UNCHANGED = A28_STATUS
A29_STATUS_UNCHANGED = A29_STATUS
A30_STATUS_UNCHANGED = A30_STATUS
A31_HISTORICAL_STATUS = A31_STATUS_UNCHANGED
A32_STATUS = "PASS"
A32_SELECTED_POLICY = (
    "IMPLEMENT_NARROW_SRC_CANONICALIZATION_THEN_REVALIDATE_SAVED_WIN007"
)

READY_BEFORE = "6 / 7"
READY_BEFORE_COUNT = 6
TOTAL_WINDOWS = 7
READY_AFTER_IF_PROMOTED = "7 / 7"
READY_AFTER_COUNT_IF_PROMOTED = 7
PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
RELATION_QUALITY_TECHNICAL_DEBT = "YES"

SRC_POLICY_OLD = SRC_REFERENCE_POLICY_VERSION_10_STRICT
SRC_POLICY_NEW = SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION
CURRENT_SRC_POLICY = CURRENT_SRC_REFERENCE_POLICY_VERSION
HISTORICAL_SRC_POLICY = HISTORICAL_SRC_REFERENCE_POLICY_VERSION
assert SRC_POLICY_OLD == "src-reference-policy-1.0-strict"
assert SRC_POLICY_NEW == "src-reference-policy-1.1-narrow-canonicalization"
assert CURRENT_SRC_POLICY == SRC_POLICY_NEW
assert HISTORICAL_SRC_POLICY == SRC_POLICY_OLD

PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V140
TRANSPORT_VERSION = SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE
GRANULARITY_POLICY = GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION
A18_PROOF_STILL_APPLIES = A32_A18_PROOF
SCHEMA_CHANGE_REQUIRED = False
PROMPT_CHANGE_REQUIRED = False
TRANSPORT_CHANGE_REQUIRED = False

SIGNATURE_INCLUDES_SRC_POLICY = (
    "src_policy" in WindowSignatureInputs.__dataclass_fields__
    or "src_reference_policy" in WindowSignatureInputs.__dataclass_fields__
    or "src_policy_version" in WindowSignatureInputs.__dataclass_fields__
)
SIGNATURE_DECISION = (
    "NEW_SIGNATURE_REQUIRED" if SIGNATURE_INCLUDES_SRC_POLICY else SRC_SIGNATURE_DECISION
)
assert SIGNATURE_DECISION == SRC_SIGNATURE_DECISION
assert not SIGNATURE_INCLUDES_SRC_POLICY

WIN007_PROMOTION_LABEL = (
    "WIN007_REVALIDATED_FROM_SAVED_A31_RESPONSE_DERIVED_SRC_CANONICALIZATION"
)
WIN007_FIRST_OWNED = WINDOW_SPECS["WIN007"]["first_owned_src"]
WIN007_LAST_OWNED = WINDOW_SPECS["WIN007"]["last_owned_src"]
EXPECTED_RAW_SRC_TOTAL = 290
EXPECTED_RAW_EXACT_SRC = 289
EXPECTED_RAW_MALFORMED_SRC = 1
EXPECTED_CANONICALIZED_SRC = 1
EXPECTED_REJECTED_MALFORMED_SRC = 0
EXPECTED_EXAMPLE_MAX_CHARS = 211
EXPECTED_EXAMPLE_LIMIT = 225

CORRECTION_REASON_CODE = CORRECTION_REASON
PIPELINE_PLACEMENT = PIPELINE_POSITION

POLICY_ARTIFACT = "source_analysis_src_canonicalization_policy.json"
REPLAY_ARTIFACT = "source_analysis_win007_strict_vs_canonical_replay.json"
PROVENANCE_ARTIFACT = "source_analysis_win007_src_canonicalization_provenance.json"
PROMOTION_ARTIFACT = "source_analysis_win007_a33_promotion.json"
READY_ARTIFACT = "source_analysis_ready_windows_after_a33.json"
INVENTORY_ARTIFACT = (
    "source_analysis_global_consolidation_input_inventory_after_a33.json"
)
SCHEMA_ARTIFACT = "source_analysis_a33_schema_identity.json"
TEST_DELTA_ARTIFACT = "source_analysis_a33_test_delta.json"
REPORT_NAME = "PHASE_3B77A33_SRC_CANONICALIZATION_WIN007_REVALIDATION_REPORT.md"

PROTECTED_A32 = (
    f"audit/{A32_REPORT_NAME}",
    f"audit/{A32_ROOT_FAILURE_ARTIFACT}",
    f"audit/{A32_HISTORY_ARTIFACT}",
    f"audit/{A32_OPTIONS_ARTIFACT}",
    f"audit/{A32_COUNTERFACTUAL_ARTIFACT}",
    f"audit/{A32_DECISION_ARTIFACT}",
    f"audit/{A32_SEMANTIC_ARTIFACT}",
    f"audit/{A32_CANONICAL_ARTIFACT}",
)
PROTECTED_HISTORICAL = tuple(A32_PROTECTED_HISTORICAL) + PROTECTED_A32

NEXT_ACTION = "HUMAN REVIEW"
NEXT_PHASE = "HUMAN_REVIEW_A33_THEN_GLOBAL_CONSOLIDATION_DESIGN"

assert EXPECTED_SCHEMA_HASH == (
    "de42ce0f3c271e67b902a94d2f528eae56f82b1a2a5740e65161987038849425"
)
assert semantic_transport_v31_local_lite_fingerprint() == EXPECTED_SCHEMA_HASH
assert semantic_transport_v3_fingerprint() == EXPECTED_SCHEMA_HASH
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert PROMPT_VERSION == "window-analysis-1.4.0"
assert TRANSPORT_VERSION == "semantic-transport-v3.1-local-lite"
assert GRANULARITY_POLICY == "window-granularity-1.2-kind-specific"
assert A31_HISTORICAL_STATUS == "FAIL"
assert A32_STATUS == "PASS"
assert MALFORMED_TOKEN == "SRec007337"
assert EXPECTED_CANONICAL == "SRC007337"
assert A19_MALFORMED == "SRc000609"
assert A19_CANONICAL == "SRC000609"
assert WIN007_REQUEST_ID == "req_011CfVDkmr5jkE7chHzsafTc"
assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert WIN007_NEW_PROVIDER_CALL is False
assert CONSOLIDATION_AUTHORIZED is False
assert not source_map_path(PROJECT_NAME).is_file() or SOURCE_MAP_STATUS == "NOT PUBLISHED"

__all__ = [
    "A18_PROOF_STILL_APPLIES",
    "A19_CANONICAL",
    "A19_MALFORMED",
    "A19_STATUS_UNCHANGED",
    "A21_STATUS_UNCHANGED",
    "A22_STATUS_UNCHANGED",
    "A23_STATUS_UNCHANGED",
    "A24_STATUS_UNCHANGED",
    "A25_STATUS_UNCHANGED",
    "A26_STATUS_UNCHANGED",
    "A261_STATUS_UNCHANGED",
    "A27_STATUS_UNCHANGED",
    "A28_STATUS_UNCHANGED",
    "A29_STATUS_UNCHANGED",
    "A30_STATUS_UNCHANGED",
    "A31_HISTORICAL_STATUS",
    "A31_VALIDATOR_ERROR",
    "A32_CANONICAL_ARTIFACT",
    "A32_COUNTERFACTUAL_ARTIFACT",
    "A32_DECISION_ARTIFACT",
    "A32_HISTORY_ARTIFACT",
    "A32_OPTIONS_ARTIFACT",
    "A32_REPORT_NAME",
    "A32_ROOT_FAILURE_ARTIFACT",
    "A32_SELECTED_POLICY",
    "A32_SEMANTIC_ARTIFACT",
    "A32_STATUS",
    "CANDIDATE_PLANNER",
    "CONSOLIDATION_AUTHORIZED",
    "CORRECTION_REASON_CODE",
    "CURRENT_SRC_POLICY",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_CANONICAL",
    "EXPECTED_CANONICALIZED_SRC",
    "EXPECTED_EXAMPLE_LIMIT",
    "EXPECTED_EXAMPLE_MAX_CHARS",
    "EXPECTED_RAW_EXACT_SRC",
    "EXPECTED_RAW_MALFORMED_SRC",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "EXPECTED_RAW_SRC_TOTAL",
    "EXPECTED_REJECTED_MALFORMED_SRC",
    "EXPECTED_SCHEMA_HASH",
    "GRANULARITY_POLICY",
    "GRAMMAR_CANARY_AUTHORIZED",
    "HISTORICAL_SRC_POLICY",
    "INVENTORY_ARTIFACT",
    "MALFORMED_TOKEN",
    "MODE",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NUMERIC_PAYLOAD",
    "PHASE",
    "PHASE_3B_STATUS",
    "PIPELINE_PLACEMENT",
    "POLICY_ARTIFACT",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMOTION_ARTIFACT",
    "PROMPT_CHANGE_REQUIRED",
    "PROMPT_VERSION",
    "PROTECTED_HISTORICAL",
    "PROVENANCE_ARTIFACT",
    "READY_AFTER_COUNT_IF_PROMOTED",
    "READY_AFTER_IF_PROMOTED",
    "READY_ARTIFACT",
    "READY_BEFORE",
    "READY_BEFORE_COUNT",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "RECORD_INDEX",
    "RECORD_S_POSITION",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPLAY_ARTIFACT",
    "REPORT_NAME",
    "SCHEMA_ARTIFACT",
    "SCHEMA_CHANGE_REQUIRED",
    "SCHEMA_VERSION",
    "SIGNATURE_DECISION",
    "SIGNATURE_INCLUDES_SRC_POLICY",
    "SOURCE_MAP_STATUS",
    "SRC_POLICY_NEW",
    "SRC_POLICY_OLD",
    "TEST_DELTA_ARTIFACT",
    "TOTAL_WINDOWS",
    "TRANSPORT_CHANGE_REQUIRED",
    "TRANSPORT_VERSION",
    "WIN007_COST_USD",
    "WIN007_ELAPSED_MS",
    "WIN007_FINISH",
    "WIN007_FIRST_OWNED",
    "WIN007_FORENSIC",
    "WIN007_FORENSIC_RELATIVE",
    "WIN007_HTTP",
    "WIN007_INPUT_TOKENS",
    "WIN007_LAST_OWNED",
    "WIN007_NEW_PROVIDER_CALL",
    "WIN007_OUTPUT_TOKENS",
    "WIN007_OWNED_SRC_COUNT",
    "WIN007_PROMOTION_LABEL",
    "WIN007_RAW_SHA256",
    "WIN007_RAW_SIZE",
    "WIN007_REQUEST_ID",
    "WIN007_SIGNATURE",
    "WIN007_THINKING",
    "WIN007_WORD_COUNT",
    "WINDOW_ID",
    "WINDOW_SPECS",
]
