"""
Phase 4B.2.24 — CH002 offline recovery and CH001 editorial-review preparation.

STRICTLY OFFLINE. Zero provider calls. AUTHORIZED SPEND = 0 USD.
Does not regenerate CH001 or CH002. Does not generate CH003 or CH004.
Does not reset locks. Does not modify raw provider responses.
Does not modify canonical sources, CH012, or CH018. Does not publish book.json.
Does not rewrite editorial prose. Does not reuse the 4B.2.23 authorization.
"""

from __future__ import annotations

from decimal import Decimal

from app.book_authorial_voice_4b218.constants import (
    AUTHORIAL_VOICE_POLICY_VERSION,
    FAITHFUL_PROMPT_1_1_VERSION,
)
from app.book_authorial_voice_4b218.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B218_SCOPE,
)
from app.book_batch_preparation_4b222.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B222_SCOPE,
    FIRST_BATCH_ID,
)
from app.book_editorial_acceptance_4b219.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B219_SCOPE,
    EXPECTED_ACCEPTED_JSON_SHA256,
    EXPECTED_ACCEPTED_MD_SHA256,
    EXPECTED_LOCK_SHA256,
    EXPECTED_ORIGINAL_JSON_SHA256,
    EXPECTED_ORIGINAL_MD_SHA256,
)
from app.book_generation.constants import (
    BOOK_GENERATOR_VALIDATOR_VERSION,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    MODEL,
    PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_generation_4b217.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B217_SCOPE,
)
from app.book_generation_4b221.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B221_SCOPE,
)
from app.book_generation_4b223.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B223_SCOPE,
    AUTHORIZED_CHAPTER_IDS as BATCH01_CHAPTER_IDS,
    BUDGET_CAP_USD as HISTORICAL_BATCH01_CAP_USD,
    EXPECTED_CH018_JSON_SHA256,
    EXPECTED_CH018_MD_SHA256,
    EXPECTED_PROMPT_1_1_SHA256,
    PROMPT_VERSION,
)
from app.book_scale_up_preparation_4b220.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B220_SCOPE,
    FAITHFUL_PROMPT_1_1,
)
from app.book_semantic_gate_4b23.constants import EXPECTED_CLEAN_TRANSCRIPT
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE

PHASE = "4B.2.24"
PHASE_NAME = "CH002_OFFLINE_RECOVERY_AND_CH001_EDITORIAL_REVIEW_PREPARATION"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_CH002_OFFLINE_RECOVERY_4B224_CH002_RECOVERY_AND_CH001_REVIEW_ONLY"
)

AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
AUTHORIZED_SPEND_USD = Decimal("0")
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = False
REAL_CHAPTER_GENERATION_AUTHORIZED = False
REAL_PROVIDERS_ENABLED = False
RETRIES = 0
FALLBACKS = 0
SDK_MAX_RETRIES = 0

PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
FAITHFUL_PROMPT_ACTIVATED = False
FAITHFUL_PROMPT_1_1_ACTIVATED = False
EDITORIAL_POLICY_ACTIVATED = False
COVERAGE_CONTROL_ACTIVATED = False
SEMANTIC_GATE_202_ENABLED = False
BOOK_JSON_PUBLICATION = False
BATCH02_AUTHORIZED = False
EDITORIAL_REWRITE_AUTHORIZED = False
LOCK_RESET_AUTHORIZED = False
RAW_RESPONSE_MUTATION_AUTHORIZED = False

BATCH_ID = FIRST_BATCH_ID
TARGET_CHAPTER_ID = "CH002"
REVIEW_CHAPTER_ID = "CH001"
RESUME_CHAPTER_IDS = ("CH003", "CH004")
FORBIDDEN_CHAPTER_IDS = ("CH012", "CH018")
EMPTY_PARAGRAPH_ID = "P000008"
EMPTY_SECTION_ID = "SEC006"
EMPTY_PROVIDER_HANDLE = "p8"
EXPECTED_CH002_IDEA_COUNT = 15
EXPECTED_CH002_SECTION_IDS = ("SEC005", "SEC006", "SEC007", "SEC008")
EXPECTED_CH001_IDEA_COUNT = 12
EXPECTED_CH001_SECTION_IDS = ("SEC001", "SEC002", "SEC003", "SEC004")
CH001_FLAGGED_SENTENCE = "You only did not accept it there."
CH001_FLAGGED_PARAGRAPH_ID = "P000010"

HISTORICAL_BATCH01_COST_USD = Decimal("0.075284")
HISTORICAL_CH001_COST_USD = Decimal("0.035854")
HISTORICAL_CH002_COST_USD = Decimal("0.039430")
HISTORICAL_CH003_PREFLIGHT_MAX_USD = Decimal("0.140364")
HISTORICAL_CH004_PREFLIGHT_MAX_USD = Decimal("0.177370")
RESUME_THEORETICAL_MAXIMUM_USD = (
    HISTORICAL_CH003_PREFLIGHT_MAX_USD + HISTORICAL_CH004_PREFLIGHT_MAX_USD
)

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_TRANSCRIPT = EXPECTED_CLEAN_TRANSCRIPT
VALIDATOR_VERSION = BOOK_GENERATOR_VALIDATOR_VERSION

assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert PROMPT_VERSION == FAITHFUL_PROMPT_1_1 == FAITHFUL_PROMPT_1_1_VERSION
assert BATCH_ID == "BATCH-01"
assert BATCH01_CHAPTER_IDS == ("CH001", "CH002", "CH003", "CH004")
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert AUTHORIZED_ANTHROPIC_CALLS == 0
assert AUTHORIZED_OPENAI_CALLS == 0
assert AUTHORIZED_TERRA_CALLS == 0
assert AUTHORIZED_SPEND_USD == Decimal("0")
assert PUBLICATION_AUTHORIZED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert FAITHFUL_PROMPT_1_1_ACTIVATED is False
assert BATCH02_AUTHORIZED is False
assert CONSUMED_4B223_SCOPE == (
    "BOOK_GENERATION_BATCH_01_CH001_CH004_ONE_SHOT_PER_CHAPTER"
)
assert HISTORICAL_BATCH01_CAP_USD == Decimal("0.66")
assert CANONICAL_PYTHON.endswith("python.exe")
assert AUTHORIAL_VOICE_POLICY_VERSION == "authorial-voice-preservation-1.0-candidate"

AUDIT_DIRNAME = "book_ch002_offline_recovery_4b224"
BATCH01_AUDIT_REL = "audit/real/book_generation_4b223_batch01"
CH012_MANIFEST_REL = "audit/book_editorial_acceptance_4b219/ch012_accepted_editorial_manifest.json"
CH018_MANIFEST_REL = "audit/book_batch_preparation_4b222/ch018_accepted_editorial_manifest.json"

AUDIT_PREFLIGHT = "preflight.json"
AUDIT_HASHES_PRE = "canonical_hashes_pre.json"
AUDIT_FORENSIC = "ch002_empty_paragraph_forensic_review.json"
AUDIT_RECOVERED_JSON = "chapter_candidate_recovered.json"
AUDIT_RECOVERED_MD = "chapter_candidate_recovered.md"
AUDIT_DIFF = "recovery_diff.json"
AUDIT_MANIFEST = "recovery_manifest.json"
AUDIT_VALIDATION = "recovery_validation.json"
AUDIT_RECOVERY_READY = "recovery_readiness.json"
AUDIT_CH001_MD = "ch001_human_editorial_review_packet.md"
AUDIT_CH001_JSON = "ch001_human_editorial_review_packet.json"
AUDIT_PREVENTION = "empty_paragraph_prevention_analysis.md"
AUDIT_RESUME = "batch01_resume_plan.json"
AUDIT_TESTS = "offline_regression_tests.json"
AUDIT_HASHES_POST = "canonical_hashes_post.json"
AUDIT_READINESS = "readiness.json"
REPORT_NAME = "PHASE_4B224_CH002_OFFLINE_RECOVERY_AND_CH001_REVIEW_REPORT.md"

RECOVERED_STATUS = "RECOVERED_STRUCTURALLY_VALID — HUMAN_REVIEW_PENDING"
BLOCKED_STATUS = "RECOVERY = BLOCKED"
CH001_STATUS = "GENERATED — HUMAN_REVIEW_PENDING"
ARTIFACT_KIND = "OFFLINE_DERIVED_ARTIFACT"
NOT_ORIGINAL = "NOT_PROVIDER_ORIGINAL"

NEXT_ACTION = (
    "HUMAN EDITORIAL REVIEW OF CH001 AND OF THE OFFLINE-RECOVERED CH002 CANDIDATE. "
    "DO NOT CALL ANTHROPIC. DO NOT RELAUNCH CH002. DO NOT GENERATE CH003 OR CH004. "
    "DO NOT LAUNCH BATCH-02. A NEW EXPLICIT AUTHORIZATION IS REQUIRED FOR ANY "
    "PAID GENERATION. THE 4B.2.23 REMAINING BUDGET IS NOT AUTHORIZATION."
)

__all__ = [
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_SPEND_USD",
    "CANONICAL_PYTHON",
    "CH001_STATUS",
    "CONSUMED_4B223_SCOPE",
    "EMPTY_PARAGRAPH_ID",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_SOURCE_MAP",
    "EXPECTED_TRANSCRIPT",
    "PHASE",
    "RECOVERED_STATUS",
    "RESUME_CHAPTER_IDS",
    "TARGET_CHAPTER_ID",
]
