"""Phase 4B.2.7.3 — one real Terra P3 negative semantic canary."""

from app.book_semantic_gate_4b273.constants import (
    AUTHORIZED_REMOTE_TERRA_INVOCATIONS,
    AUTHORIZED_SONNET_CALLS,
    HISTORICAL_4B271_STATUS,
    HISTORICAL_4B272_STATUS,
    HISTORICAL_4B27_STATUS,
    PHASE,
    SELECTED_CASE_HANDLE,
)

assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert HISTORICAL_4B27_STATUS == "PARTIAL"
assert HISTORICAL_4B271_STATUS == "PASS"
assert HISTORICAL_4B272_STATUS == "PASS"
assert SELECTED_CASE_HANDLE == "h02"

__all__ = [
    "PHASE",
    "AUTHORIZED_REMOTE_TERRA_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "HISTORICAL_4B27_STATUS",
    "HISTORICAL_4B271_STATUS",
    "HISTORICAL_4B272_STATUS",
]
