"""
Phase 4B.2.7.3 — One real Terra P3 negative semantic canary.

NEW explicit authorization. MAX_REMOTE_TERRA_INVOCATIONS = 1.
Does not reuse consumed 4B.2.4 / 4B.2.5 / 4B.2.6 / 4B.2.7 slots.
Does not relaunch h01. Frozen P3 request from 4B.2.7.2 is unchanged.
Historical 4B.2.6 remains FAIL. 4B.2.6.1 remains PASS. 4B.2.6.2 remains PASS.
Historical 4B.2.7 remains PARTIAL. 4B.2.7.1 remains PASS. 4B.2.7.2 remains PASS.
Contract 1.1.1-candidate is not promoted. Contracts 1.0 / 1.1-candidate are not modified.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
    VERDICT_FAIL,
    VERDICT_PASS,
    VERDICT_REVIEW,
)
from app.book_semantic_gate_4b24.constants import (
    EXPECTED_BENCHMARK_DATASET_SHA256,
    EXPECTED_BENCHMARK_FILE_SHA256,
    P3_CASE_ID,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    SEMANTIC_TOKEN_BUDGET,
)
from app.book_semantic_gate_4b27.constants import (
    EXPECTED_REQUEST_SHA256 as H01_REQUEST_SHA256,
    HISTORICAL_4B241_STATUS,
    HISTORICAL_4B24_STATUS,
    HISTORICAL_4B251_STATUS,
    HISTORICAL_4B25_STATUS,
    HISTORICAL_4B261_STATUS,
    HISTORICAL_4B262_STATUS,
    HISTORICAL_4B26_STATUS,
)
from app.book_semantic_gate_4b271.constants import (
    HISTORICAL_4B27_STATUS,
    PROMPT_VERSION_111,
    TRANSPORT_VERSION_11,
    TRANSPORT_VERSION_111,
)
from app.book_semantic_gate_4b272.constants import (
    DISPUTED_CAUSAL_CLAUSE,
    HISTORICAL_4B271_STATUS,
    OBSERVED_4B27_COMPLETION_TOKENS,
    OBSERVED_4B27_COST_USD,
    OBSERVED_4B27_INPUT_TOKENS,
    OBSERVED_4B27_REASONING_TOKENS,
    P3_EVIDENCE_HANDLES,
    SELECTED_CASE_ACCEPTED_CLASSES,
    SELECTED_CASE_HANDLE,
    SELECTED_CASE_HUMAN_LABEL,
    SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY,
    SELECTED_CASE_ID,
    SELECTED_CASE_REASON_CODES_AUDIT_ONLY,
    SELECTED_CASE_ROLE,
)

PHASE = "4B.2.7.3"
PHASE_NAME = "ONE_REAL_TERRA_P3_NEGATIVE_CANARY"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B273_ONE_REAL_TERRA_P3_NEGATIVE_CANARY_ONLY"
)
AUTHORIZED_REMOTE_TERRA_INVOCATIONS = 1
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
MAX_ENGINE_GENERATE = 1
MAX_REMOTE_INVOCATIONS = 1
RETRIES = 0
FALLBACKS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = True
SDK_MAX_RETRIES = 0

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
STAGE_CANARY = "book_semantic_validation_canary_4b273"
PROMPT_VERSION = PROMPT_VERSION_111
TRANSPORT_VERSION = TRANSPORT_VERSION_11
PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"
TOKEN_FIELD = "max_completion_tokens"
PRODUCTION_SDK_METHOD = "client.chat.completions.create"

EXPECTED_REQUEST_SHA256 = (
    "5ace261296d808437910f8f9efe247a80daebbb2237bc8af46bda56bf98d7897"
)
EXPECTED_CLAUSE_START = 406
EXPECTED_CLAUSE_END = 465
RELEVANT_REASON_CODES = ("NEW_CAUSAL_LINK", "NEW_IMPLICATION")
BLOCKING_VERDICTS = (
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    VERDICT_REVIEW,
    VERDICT_FAIL,
    "REVIEW",
    "FAIL",
    "QUESTIONABLE",
    "UNSUPPORTED",
)
ACCEPTING_VERDICTS = (VERDICT_PASS, CLASS_SUPPORTED, "PASS", "SUPPORTED")

HISTORICAL_4B272_STATUS = "PASS"

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert PROMPT_VERSION == "book-semantic-validator-1.1.1-candidate"
assert TRANSPORT_VERSION == "book-semantic-validation-transport-1.1-candidate"
assert TRANSPORT_VERSION_111 is None
assert PROMPT_VERSION_HISTORICAL == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION_HISTORICAL == "book-semantic-validation-transport-1.0"
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
assert TOKEN_FIELD == "max_completion_tokens"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert SELECTED_CASE_HANDLE == "h02"
assert SELECTED_CASE_ID == "4b22_p3_new_causal"
assert SELECTED_CASE_ID == P3_CASE_ID
assert SELECTED_CASE_ROLE == "negative"
assert SELECTED_CASE_HUMAN_LABEL == CLASS_QUESTIONABLE
assert DISPUTED_CAUSAL_CLAUSE == (
    "because it still works wherever it is not resisted by truth"
)
assert P3_EVIDENCE_HANDLES == (
    "IDEA225",
    "SRC006152",
    "SRC006154",
    "SRC006155",
    "SRC006156",
    "SRC006157",
)
assert EXPECTED_REQUEST_SHA256 != H01_REQUEST_SHA256
assert H01_REQUEST_SHA256 == (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert HISTORICAL_4B262_STATUS == "PASS"
assert HISTORICAL_4B27_STATUS == "PARTIAL"
assert HISTORICAL_4B271_STATUS == "PASS"
assert HISTORICAL_4B272_STATUS == "PASS"
assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert SDK_MAX_RETRIES == 0
assert PUBLICATION_AUTHORIZED is False
assert SCORED_CASE_ORDER[1] == (SELECTED_CASE_HANDLE, SELECTED_CASE_ID)

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 300.0
CANARY_WINDOW_ID = "book-semantic-gate-4b273"

AUDIT_DIRNAME = "book_semantic_gate_4b273"
AUDIT_REAL_PARENT = "real"
AUDIT_PRECALL = "p3_real_precall.json"
AUDIT_RUNTIME = "p3_real_runtime.json"
AUDIT_REQUEST = "p3_real_request_identity.json"
AUDIT_SERIALIZATION = "p3_real_sdk_serialization.json"
AUDIT_ACCOUNTING = "p3_real_call_accounting.json"
AUDIT_PROVIDER = "p3_real_provider_evidence.json"
AUDIT_USAGE = "p3_real_token_usage.json"
AUDIT_VALIDATION = "p3_real_response_validation.json"
AUDIT_SEMANTIC = "p3_real_semantic_review.json"
AUDIT_REPLAY = "p3_real_replay.json"
AUDIT_TESTS = "p3_real_tests.json"
AUDIT_COST = "p3_real_cost.json"
AUDIT_READINESS = "p3_real_readiness.json"
AUDIT_RAW_RESPONSE = "p3_real_raw_structured_response.json"
AUDIT_RAW_TEXT = "p3_real_raw_provider_text.txt"
AUDIT_LOCK = "p3_real_call.lock"
AUDIT_INDEX = "p3_real_index.json"
REPORT_NAME = "PHASE_4B273_ONE_REAL_TERRA_P3_NEGATIVE_CANARY_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "ACCEPTING_VERDICTS",
    "AUDIT_ACCOUNTING",
    "AUDIT_COST",
    "AUDIT_DIRNAME",
    "AUDIT_INDEX",
    "AUDIT_LOCK",
    "AUDIT_PRECALL",
    "AUDIT_PROVIDER",
    "AUDIT_RAW_RESPONSE",
    "AUDIT_RAW_TEXT",
    "AUDIT_READINESS",
    "AUDIT_REAL_PARENT",
    "AUDIT_REPLAY",
    "AUDIT_REQUEST",
    "AUDIT_RUNTIME",
    "AUDIT_SEMANTIC",
    "AUDIT_SERIALIZATION",
    "AUDIT_TESTS",
    "AUDIT_USAGE",
    "AUDIT_VALIDATION",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_REMOTE_TERRA_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "BLOCKING_VERDICTS",
    "CANARY_WINDOW_ID",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CONNECT_TIMEOUT_SECONDS",
    "CONSERVATIVE_MAX_OUTPUT_TOKENS",
    "DISPUTED_CAUSAL_CLAUSE",
    "EXPECTED_BENCHMARK_DATASET_SHA256",
    "EXPECTED_BENCHMARK_FILE_SHA256",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_CLAUSE_END",
    "EXPECTED_CLAUSE_START",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_OPENAI_SDK_VERSION",
    "EXPECTED_PYTHON_VERSION",
    "EXPECTED_REQUEST_SHA256",
    "EXPECTED_SOURCE_MAP",
    "FALLBACKS",
    "H01_REQUEST_SHA256",
    "HISTORICAL_4B241_STATUS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B251_STATUS",
    "HISTORICAL_4B25_STATUS",
    "HISTORICAL_4B261_STATUS",
    "HISTORICAL_4B262_STATUS",
    "HISTORICAL_4B26_STATUS",
    "HISTORICAL_4B271_STATUS",
    "HISTORICAL_4B272_STATUS",
    "HISTORICAL_4B27_STATUS",
    "MAX_ENGINE_GENERATE",
    "MAX_REMOTE_INVOCATIONS",
    "MODEL",
    "NEXT_ACTION",
    "OBSERVED_4B27_COMPLETION_TOKENS",
    "OBSERVED_4B27_COST_USD",
    "OBSERVED_4B27_INPUT_TOKENS",
    "OBSERVED_4B27_REASONING_TOKENS",
    "OUTPUT_MODE",
    "P3_CASE_ID",
    "P3_EVIDENCE_HANDLES",
    "PHASE",
    "PHASE_NAME",
    "PRODUCTION_ENDPOINT",
    "PRODUCTION_SDK_METHOD",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROMPT_VERSION_111",
    "PROMPT_VERSION_HISTORICAL",
    "PROVIDER",
    "PUBLICATION_AUTHORIZED",
    "READ_TIMEOUT_SECONDS",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "READY_FOR_NEW_REMOTE_TERRA_CALL",
    "RELEVANT_REASON_CODES",
    "REPORT_NAME",
    "RETRIES",
    "SCORED_CASE_ORDER",
    "SDK_MAX_RETRIES",
    "SELECTED_CASE_ACCEPTED_CLASSES",
    "SELECTED_CASE_HANDLE",
    "SELECTED_CASE_HUMAN_LABEL",
    "SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY",
    "SELECTED_CASE_ID",
    "SELECTED_CASE_REASON_CODES_AUDIT_ONLY",
    "SELECTED_CASE_ROLE",
    "SEMANTIC_TOKEN_BUDGET",
    "STAGE_CANARY",
    "TEMPERATURE_POLICY",
    "TERRA_EXECUTION_AUTHORIZED",
    "THINKING_MODE",
    "TOKEN_FIELD",
    "TRANSPORT_VERSION",
    "TRANSPORT_VERSION_11",
    "TRANSPORT_VERSION_111",
    "TRANSPORT_VERSION_HISTORICAL",
    "VERDICT_FAIL",
    "VERDICT_PASS",
    "VERDICT_REVIEW",
]
