"""Constantes 3B.7.7A.6 — décision d'architecture offline. 0 appel provider."""

from __future__ import annotations

from decimal import Decimal

from app.source_analysis_provider_boundary.constants import (
    CALL1_SIGNATURE,
    CALL2_SIGNATURE,
    CLEAN_SHA,
    GENERATION_C_ANTHROPIC_SHA,
    GENERATION_C_RAW_SHA,
    PROMPT_10_SHA,
    PROMPT_11_SHA,
    PROTECTED_EVIDENCE as PROTECTED_EVIDENCE_A5,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.6"
MODE = "OFFLINE_POST_CANARY_ARCHITECTURE_DECISION"
PROJECT_NAME = "pastoral_retreat_v2_validation"
WINDOW_ID = "WIN001"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
THIRD_WIN001_CALL_AUTHORIZED = False
THIRD_WIN001_CALL = "NOT AUTHORIZED"
REAL_CALL_AUTHORIZATION = False

WINDOW_ANALYSIS_11_REAL_STATUS = "UNVALIDATED"
WINDOW_ANALYSIS_11_STATUS_DETAIL = "UNVALIDATED_REAL"
PHASE_3B_STATUS = "INCOMPLETE"
NEXT_ACTION = "HUMAN REVIEW"

NEXT_PHASE = "3B.7.7A.7"
NEXT_PHASE_LABEL = (
    "3B.7.7A.7 — SMALL-WINDOW / ADAPTIVE-HIERARCHY IMPLEMENTATION — FAKEAI ONLY"
)

SIMULATIONS_ARTIFACT = "source_analysis_post_canary_window_size_simulations.json"
COST_ARTIFACT = "source_analysis_post_canary_architecture_cost_scenarios.json"
CONSOLIDATION_ARTIFACT = "source_analysis_post_canary_consolidation_scaling.json"
OPTIONS_ARTIFACT = "source_analysis_post_canary_architecture_options.json"
DECISION_ARTIFACT = "source_analysis_post_canary_architecture_decision.json"
REPORT_NAME = "PHASE_3B77A6_POST_CANARY_ARCHITECTURE_DECISION_REPORT.md"

HISTORICAL_RATIO = Decimal("2.155975")
HISTORICAL_RATIO_LABEL = "local estimate × 2.155975"
CALL1_LOCAL_ESTIMATE = 49617
CALL1_ACTUAL_INPUT = 106973
CALL1_ACTUAL_OUTPUT = 32000
CALL1_COST_USD = Decimal("0.533946")
CALL1_ELAPSED_MS = 255703
CALL1_FAILURE = "AIStructuredOutputError"
CALL2_LOCAL_ESTIMATE = 50299
CALL2_ELAPSED_MS = 320639
CALL2_WALL_MS = 335532
CALL2_FAILURE = "AIResponseError"
CALL2_COST = "UNKNOWN"

INPUT_COST_PER_1M = Decimal("2.00")
OUTPUT_COST_PER_1M = Decimal("10.00")
TOKENS_PER_MILLION = Decimal("1000000")

CURRENT_TARGET = 50000
CURRENT_HARD_MAX = 60000
CURRENT_WINDOW_COUNT = 3
MAX_OUTPUT_FROZEN = 32000
CONSOLIDATION_GUARD_EXPECTED = 80000

CANDIDATE_PAIRS = (
    (10000, 15000),
    (15000, 20000),
    (20000, 25000),
    (25000, 30000),
    (25000, 35000),
    (30000, 40000),
    (35000, 45000),
    (50000, 60000),
)

BALANCE_MIN_RATIO = 0.70
OVERHEAD_INEFFICIENT_PCT = 40.0
PROPOSED_PLANNER_VERSION = "window-planner-v2.1-proposed"
PRODUCTION_PLANNER_VERSION = "window-planner-v2.0"

SELECTED_ARCHITECTURE = "SMALLER_WINDOWS_ADAPTIVE_HIERARCHICAL"
PROPOSED_TARGET = 25000
PROPOSED_HARD_MAX = 35000
PROPOSED_CONTEXT_POLICY = "NONE"
PROPOSED_OVERLAP_POLICY = "NO_OWNED_OVERLAP"
RESPONSE_MODE_DECISION = "OPTIONAL_FUTURE_IMPROVEMENT"

PROTECTED_EVIDENCE = PROTECTED_EVIDENCE_A5 + (
    "audit/PHASE_3B77A5_AIRESPONSEERROR_PROVIDER_BOUNDARY_FORENSICS_ARCHITECTURE_REVIEW_REPORT.md",
    "audit/source_analysis_airesponseerror_provider_boundary_diagnosis.json",
    "audit/source_analysis_provider_failure_forensic_matrix.json",
    "audit/source_analysis_provider_response_boundary_architecture.json",
    "audit/source_analysis_win001_two_call_evidence_review.json",
)

__all__ = [
    "BALANCE_MIN_RATIO",
    "CALL1_ACTUAL_INPUT",
    "CALL1_ACTUAL_OUTPUT",
    "CALL1_COST_USD",
    "CALL1_ELAPSED_MS",
    "CALL1_FAILURE",
    "CALL1_LOCAL_ESTIMATE",
    "CALL1_SIGNATURE",
    "CALL2_COST",
    "CALL2_ELAPSED_MS",
    "CALL2_FAILURE",
    "CALL2_LOCAL_ESTIMATE",
    "CALL2_SIGNATURE",
    "CALL2_WALL_MS",
    "CANDIDATE_PAIRS",
    "CLEAN_SHA",
    "CONSOLIDATION_ARTIFACT",
    "CONSOLIDATION_GUARD_EXPECTED",
    "COST_ARTIFACT",
    "CURRENT_HARD_MAX",
    "CURRENT_TARGET",
    "CURRENT_WINDOW_COUNT",
    "DECISION_ARTIFACT",
    "GENERATION_C_ANTHROPIC_SHA",
    "GENERATION_C_RAW_SHA",
    "HISTORICAL_RATIO",
    "HISTORICAL_RATIO_LABEL",
    "INPUT_COST_PER_1M",
    "MAX_OUTPUT_FROZEN",
    "MODE",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "OPTIONS_ARTIFACT",
    "OUTPUT_COST_PER_1M",
    "OVERHEAD_INEFFICIENT_PCT",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_10_SHA",
    "PROMPT_11_SHA",
    "PROPOSED_CONTEXT_POLICY",
    "PROPOSED_HARD_MAX",
    "PROPOSED_OVERLAP_POLICY",
    "PROPOSED_PLANNER_VERSION",
    "PROPOSED_TARGET",
    "PROTECTED_EVIDENCE",
    "REAL_CALL_AUTHORIZATION",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REPORT_NAME",
    "RESPONSE_MODE_DECISION",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SIMULATIONS_ARTIFACT",
    "THIRD_WIN001_CALL",
    "THIRD_WIN001_CALL_AUTHORIZED",
    "TOKENS_PER_MILLION",
    "WINDOW_ANALYSIS_11_REAL_STATUS",
    "WINDOW_ANALYSIS_11_STATUS_DETAIL",
    "WINDOW_ID",
]
