"""Rapport déterministe 3B.7.7A.6."""

from __future__ import annotations

from typing import Any, Mapping

from app.source_analysis_post_canary_architecture.constants import (
    CALL1_COST_USD,
    CALL1_FAILURE,
    CALL2_COST,
    CALL2_FAILURE,
    MAX_OUTPUT_FROZEN,
    NEXT_PHASE_LABEL,
    PHASE,
    SELECTED_ARCHITECTURE,
    THIRD_WIN001_CALL,
    WINDOW_ANALYSIS_11_REAL_STATUS,
)


def _yn(value: Any) -> str:
    return "YES" if value else "NO"


def _plans_for_target(simulations: Mapping[str, Any], target: int) -> list[dict[str, Any]]:
    return [
        row
        for row in simulations.get("candidates") or []
        if row.get("target") == target
    ]


def _plan(simulations: Mapping[str, Any], target: int) -> dict[str, Any]:
    rows = _plans_for_target(simulations, target)
    return rows[0] if rows else {}


def render_report(bundle: Mapping[str, Any]) -> str:
    simulations = bundle["simulations"]
    costs = bundle["costs"]
    consolidation = bundle["consolidation"]
    options_payload = bundle["options"]
    options = (
        options_payload.get("options")
        if isinstance(options_payload, Mapping)
        else options_payload
    )
    decision = bundle["decision"]
    response = bundle["response"]
    integrity = bundle["integrity"]
    hierarchy = bundle["hierarchy"]
    current = simulations["current_three_window"]
    proposed = decision["parameters"]
    result = bundle["result"]
    selected_row = _plan(simulations, int(proposed["target_local_request_tokens"]))
    cons_selected = next(
        (
            row
            for row in consolidation.get("plans") or []
            if row.get("label") == selected_row.get("label")
        ),
        {},
    )
    lines = [
        f"# PHASE {PHASE} — POST-CANARY ARCHITECTURE DECISION",
        "",
        "## Result",
        "",
        result,
        "",
        "REAL PROVIDER CALLS =",
        "0",
        "",
        "THIRD WIN001 CALL =",
        THIRD_WIN001_CALL,
        "",
        "REAL CALL #1 =",
        CALL1_FAILURE,
        "",
        "REAL CALL #2 =",
        CALL2_FAILURE,
        "",
        "WINDOW-ANALYSIS-1.1 REAL STATUS =",
        WINDOW_ANALYSIS_11_REAL_STATUS,
        "",
        "CURRENT WINDOWS =",
        str(current.get("window_count")),
        "",
        "CANDIDATE PLANS TESTED =",
        str(len(simulations.get("candidates") or [])),
        "",
        "SELECTED ARCHITECTURE =",
        SELECTED_ARCHITECTURE,
        "",
        "PROPOSED TARGET =",
        str(proposed["target_local_request_tokens"]),
        "",
        "PROPOSED HARD MAX =",
        str(proposed["hard_max_local_request_tokens"]),
        "",
        "PROPOSED WINDOW COUNT =",
        str(proposed["expected_clean_window_count"]),
        "",
        "PROPOSED CONTEXT POLICY =",
        str(proposed["context_policy"]),
        "",
        "GLOBAL CONSOLIDATION =",
        "ADAPTIVE HIERARCHICAL",
        "",
        "RESPONSE MODE =",
        str(response.get("decision")),
        "",
        "MAX OUTPUT =",
        f"{MAX_OUTPUT_FROZEN} CURRENTLY UNCHANGED",
        "",
        "CANONICAL SOURCEMAP =",
        "UNCHANGED",
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## 1. Result",
        "",
        f"{result}. Offline decision only. No provider call. No third WIN001 call.",
        "",
        "## 2. Objective",
        "",
        "Choose one Source Analyzer execution architecture before any further",
        "real semantic provider call, using existing evidence and offline simulation.",
        "",
        "## 3. Baseline",
        "",
        "Expected 2386 passed / 0 failed before new tests. New tests are additive.",
        "",
        "## 4. Current Phase 3B status",
        "",
        f"source_map present = {_yn(integrity.get('source_map_present'))}.",
        f"project state = {integrity['project_state']['status']}.",
        f"not SUCCESS = {_yn(integrity['project_state']['not_success'])}.",
        "Phase 3B remains INCOMPLETE.",
        "",
        "## 5. Real call #1",
        "",
        "prompt window-analysis-1.0, anthropic/claude-sonnet-5,",
        "local 49617, actual input 106973, actual output 32000, cost USD 0.533946,",
        "elapsed 255703 ms, AIStructuredOutputError. Output reached 32000 ceiling.",
        "Truncation strongly supported; stop_reason not preserved.",
        "",
        "## 6. Real call #2",
        "",
        "prompt window-analysis-1.1, local 50299, elapsed 320639 ms / wall 335532 ms,",
        "AIResponseError. HTTP response received PROVEN. Timeout NO. Connection NO.",
        "HTTP 4xx/5xx ruled out. Structured parsing NOT REACHED.",
        "actual tokens / stop_reason / request id / cost / raw body = UNKNOWN.",
        "",
        "## 7. Evidence limitations",
        "",
        "Call #2 does not prove 1.1 succeeded, failed semantically, or that",
        "bounding solved or failed to solve output explosion.",
        "Correct status: UNVALIDATED_REAL.",
        "Two failures do not statistically prove 50k impossible.",
        "They do justify avoiding a blind third 50k call.",
        "",
        "## 8. Provider forensic status",
        "",
        f"Hardened boundary active = {_yn(integrity['forensics']['active'])}.",
        "HTTP response is captured before ProviderResult / AIResponse / parse.",
        "Observability improved. Generation reliability unchanged.",
        "This phase did not modify the forensic boundary.",
        "",
        "## 9. Current three-window architecture",
        "",
        f"Production planner target/hard max = {current.get('production_planner_target')}/{current.get('production_planner_hard_max')}.",
        f"Window count = {current.get('window_count')}.",
        f"Owned SRC min/max/mean = {current['owned_src']['min']}/{current['owned_src']['max']}/{current['owned_src']['mean']}.",
        f"Words min/max/mean = {current['words']['min']}/{current['words']['max']}/{current['words']['mean']}.",
        f"Local 1.1 request min/max/mean = {current['local_estimated_request']['min']}/{current['local_estimated_request']['max']}/{current['local_estimated_request']['mean']}.",
        f"Coverage complete = {_yn(current['coverage']['coverage_complete'])}.",
        f"Duplicates = {current['coverage']['duplicate_owned_src']}.",
        f"Tiny stub = {_yn(current.get('tiny_stub'))}.",
        "",
        "## 10. Context capacity vs operational size",
        "",
        "The request fits model context (1M). That is CONTEXT_CAPACITY.",
        "It does not prove SEMANTIC_COMPLEXITY, STRUCTURED_OUTPUT_COMPLEXITY,",
        "REQUEST_RELIABILITY, COST, or RECOVERY GRANULARITY are acceptable.",
        "Context capacity alone does not justify keeping 50k windows.",
        "",
        "## 11. Decision criteria",
        "",
        "Reliability and semantic fidelity outrank minimizing provider-call count.",
        "Also: traceability, failure isolation, resume, consolidation feasibility,",
        "cost scenarios, sequential latency, implementation complexity, observability.",
        "No arbitrary weighted score.",
        "",
        "## 12. Candidate targets",
        "",
        "Pairs simulated: "
        + ", ".join(str(row.get("label")) for row in simulations.get("candidates") or []),
        "",
    ]

    for target, section in (
            (10000, 13),
            (15000, 14),
            (20000, 15),
            (25000, 16),
            (30000, 17),
            (35000, 18),
            (50000, 19),
        ):
            rows = _plans_for_target(simulations, target)
            lines.extend([f"## {section}. {target // 1000}k simulation", ""])
            if not rows:
                lines.extend(["No candidate pair for this target.", ""])
                continue
            for row in rows:
                lines.extend(
                    [
                        f"label = {row.get('label')}. feasible = {_yn(row.get('feasible'))}.",
                        f"windows = {row.get('window_count')}. tiny_stub = {_yn(row.get('tiny_stub'))}.",
                        f"balanced = {_yn(row.get('balanced'))}. balance_metric = {row.get('balance_metric')}.",
                        f"SRC min/max/mean = {(row.get('owned_src') or {}).get('min')}/{(row.get('owned_src') or {}).get('max')}/{(row.get('owned_src') or {}).get('mean')}.",
                        f"words min/max/mean = {(row.get('words') or {}).get('min')}/{(row.get('words') or {}).get('max')}/{(row.get('words') or {}).get('mean')}.",
                        f"local request min/max/mean = {(row.get('local_estimated_request') or {}).get('min')}/{(row.get('local_estimated_request') or {}).get('max')}/{(row.get('local_estimated_request') or {}).get('mean')}.",
                        f"coverage = {_yn((row.get('coverage') or {}).get('coverage_complete'))}.",
                        f"duplicates = {(row.get('coverage') or {}).get('duplicate_owned_src')}.",
                        f"missing SRC = {(row.get('coverage') or {}).get('missing_src')}.",
                        f"overhead % = {row.get('prompt_overhead_pct_of_mean_request')}.",
                        f"calls = {row.get('provider_calls_required')}.",
                        "",
                    ]
                )

    lines.extend(
        [
            "## 20. Balance",
            "",
            "balance_metric = min(min/max local request, min/max owned SRC, min/max words).",
            f"Threshold = 0.70. Current balanced = {_yn(current.get('balanced'))}.",
            "Plans with a tiny last window are not selected merely to hit a target.",
            "",
            "## 21. Prompt overhead",
            "",
            f"window-analysis-1.1 overhead = {simulations.get('prompt_overhead_1_1')} local tokens.",
            "Percentage is overhead / mean remesured request. Repeated cost = overhead × N.",
            "",
            "Duration per window is the sum of owned segment (end-start), not",
            "last.end minus first.start, because audio-file clocks reset.",
            "",
            "## 22. Words per window",
            "",
            f"Current mean words = {current['words']['mean']}.",
            f"Proposed mean words = {(selected_row.get('words') or {}).get('mean')}.",
            "",
            "## 23. SRC per window",
            "",
            f"Current mean SRC = {current['owned_src']['mean']}.",
            f"Proposed mean SRC = {(selected_row.get('owned_src') or {}).get('mean')}.",
            "",
            "## 24. Call counts",
            "",
            "Each candidate requires exactly its window_count sequential window calls,",
            "plus consolidation call(s) not yet executed.",
            "",
            "## 25. Input scenarios",
            "",
            "LOCAL_ESTIMATE uses remesured 1.1 tokens × $2 / 1M.",
            "HISTORICAL_RATIO multiplies local tokens by 2.155975 then $2 / 1M.",
            "Both are SCENARIO, NOT PREDICTION.",
            "",
            "## 26. Output scenarios",
            "",
            "LOW / MEDIUM / POLICY-STRESS scale FakeAI size-study local tokens by",
            "window word span versus current ~12.7k-word windows.",
            "No plan assumes every smaller window emits 13023 or 32000 tokens.",
            "",
            "## 27. Total cost scenarios",
            "",
            "See source_analysis_post_canary_architecture_cost_scenarios.json.",
            "Ranges are window-analysis only plus UNKNOWN consolidation spend.",
            "",
            "## 28. Historical spend",
            "",
            f"Call #1 known = USD {CALL1_COST_USD}.",
            f"Call #2 = {CALL2_COST}. Counted as zero = NO.",
            "Total actual = UNKNOWN. Known minimum = USD 0.533946.",
            "",
            "## 29. Failure blast radius",
            "",
            f"Current: one failed call affects max {current['owned_src']['max']} SRC / {current['words']['max']} words.",
            f"Proposed: one failed call affects max {(selected_row.get('owned_src') or {}).get('max')} SRC / {(selected_row.get('words') or {}).get('max')} words.",
            "Reusable windows = N-1 if one fails. Recovery unit = one window.",
            "",
            "## 30. Cache / resume",
            "",
            "Existing per-window cache remains. More windows = more metadata artifacts",
            "and finer resume. One failed smaller window leaves more reusable work.",
            "",
            "## 31. Sequential latency",
            "",
            "Current execution is sequential. Historical 50k calls lasted ~256–336 s.",
            "That is evidence, not a linear predictor. More smaller calls likely",
            "increase total wall time even if each call is shorter. Parallelism is",
            "a future possibility only.",
            "",
            "## 32. Semantic coherence",
            "",
            "Smaller windows split longer arguments. Approximate span is the words/",
            "SRC/duration reported per candidate. No owned overlap means boundary",
            "context risk exists.",
            "",
            "## 33. Boundary risk",
            "",
            "Owned-only windows can cut mid-argument. Cross-window relations remain",
            "the consolidator's job. Limited read-only context is deferred.",
            "",
            "## 34. Context overlap",
            "",
            "Proposed policy = NONE. context_src_refs stay empty.",
            "If introduced later: CONTEXT SRC are read-only; only OWNED SRC may",
            "ground substantive records. Overlap can create duplicate records that",
            "global consolidation may MERGE, but ownership must stay deterministic.",
            "",
            "## 35. Audio-source boundaries",
            "",
            f"CLEAN has {simulations['audio_sources']['audio_file_count']} source audio files.",
            "They are useful technical constraints, not editorial chapters.",
            "Each file is not assumed to be a semantic chapter.",
            "",
            "## 36. Option A — current 3 windows",
            "",
            "Few calls, large semantic context, large structured generation,",
            "large blast radius, poor recovery. Two historical failures.",
            "Rejected as the next operational unit.",
            "",
            "## 37. Option B — smaller windows",
            "",
            "Simulated with WindowPlannerV2, 1.1 overhead, SRC boundaries,",
            "no tiny stubs required for selection. Increases consolidation burden.",
            "",
            "## 38. Option C — hierarchy",
            "",
            "window → regional → global. Smaller generations and better resume,",
            "more calls and contracts, risk of summary-of-summary loss unless",
            "SRC refs and NO-DROP survive. Recommended only when adaptive trigger fires.",
            "",
            "## 39. Option D — response mode",
            "",
            f"Current = {response.get('current_mode')}.",
            f"Decision = {response.get('decision')}. Not selected as primary architecture.",
            "",
            "## 40. Streaming assessment",
            "",
            f"Implemented now = {_yn(response['streaming']['anthropic_engine_supports_streaming_now'])}.",
            f"Structured streaming support = {response['streaming']['semantic_structured_output_path_supports_streaming']}.",
            f"Provider streaming verified = {_yn(response['streaming']['provider_streaming_support_verified'])}.",
            "Could help visibility/evidence. Would not solve overgeneration or invalid JSON.",
            "",
            "## 41. Async/batch assessment",
            "",
            f"Repository support = {response['async_batch']['repository_support']}.",
            f"Verified = {_yn(response['async_batch']['provider_async_batch_verified'])}.",
            "EXTERNAL PROVIDER VERIFICATION REQUIRED. Not selected.",
            "",
            "## 42. Consolidation architecture",
            "",
            "ConsolidationInputBuilder + consolidation-1.0 + consolidation-transport-v1",
            "+ NO-DROP + HybridCanonicalReconstructor remain the contracts.",
            "WINxxx:Rxxxx still fits 6–12+ windows (WIN012:R0160).",
            "",
            "## 43. Current consolidation guard",
            "",
            f"CONSOLIDATION_SAFE_INPUT_BUDGET_TOKENS = {integrity.get('consolidation_guard')}.",
            "Exceeding raises ConsolidationContextExceeded. No silent truncation.",
            "",
            "## 44. Synthetic normal consolidation",
            "",
            f"Selected plan normal status = {(cons_selected.get('normal') or {}).get('status')}.",
            f"normal tokens = {(cons_selected.get('normal') or {}).get('consolidation_input_estimated_tokens')}.",
            f"normal records = {cons_selected.get('normal_record_count')}.",
            "",
            "## 45. Synthetic stress consolidation",
            "",
            "POLICY-STRESS / MAX_POLICY_VALID is NOT the expected case.",
            f"Selected plan stress status = {(cons_selected.get('stress') or {}).get('status')}.",
            f"stress tokens = {(cons_selected.get('stress') or {}).get('consolidation_input_estimated_tokens')}.",
            "Fail-closed if over guard. No truncation.",
            "",
            "## 46. More-window duplication burden",
            "",
            "More windows produce more local TOPIC/IDEA candidates for the same corpus.",
            "Synthetic record counts scale with window count × per-window density.",
            "This favors adaptive hierarchy if the global input exceeds 80k.",
            "",
            "## 47. Regional consolidation",
            "",
            "Deterministic source-ordered groups of 3 windows. No Python clustering.",
            f"Selected regional groups = {(cons_selected.get('hierarchy') or {}).get('regional_group_count')}.",
            "",
            "## 48. Adaptive hierarchy",
            "",
            "If ConsolidationInput fits 80k: one global consolidation.",
            "Else: regional then global. Adaptive avoids unnecessary extra calls.",
            "",
            "## 49. Traceability through hierarchy",
            "",
            f"SRC refs survive = {_yn(hierarchy.get('src_refs_survive_local_regional_global'))}.",
            f"Generated range expansion = {_yn(hierarchy.get('generated_range_expansion'))}.",
            "",
            "## 50. NO-DROP accounting",
            "",
            f"NO-DROP = {_yn(hierarchy.get('no_drop'))}.",
            "Every substantive local record is KEEP or explicit MERGE member.",
            "",
            "## 51. Uncertainty preservation",
            "",
            f"Uncertainties preserved in simulation = {_yn(hierarchy.get('uncertainties_preserved'))}.",
            "Uncertainty is not merged away merely to reduce size.",
            "",
            "## 52. Reference preservation",
            "",
            f"References preserved = {_yn(hierarchy.get('references_preserved'))}.",
            "",
            "## 53. Repetition handling",
            "",
            "Small windows should not be forced to detect global repetition.",
            "Global consolidator is the proper place for corpus-level repetition.",
            "",
            "## 54. Cross-window relations",
            "",
            "Smaller windows must not permanently isolate concepts.",
            "RELATION remains a consolidator responsibility across windows.",
            "",
            "## 55. Global metadata",
            "",
            "Theme/intent/audience/voice stay WINDOW_CANDIDATE_ONLY until consolidation.",
            "Many windows produce more metadata candidates; hierarchy may compact them",
            "without Python voting.",
            "",
            "## 56. Canonical compatibility",
            "",
            "Target canonical SourceMap schema is unchanged.",
            "",
            "## 57. Phase 4 compatibility",
            "",
            "Editorial Planner still consumes the same canonical SourceMap.",
            "Architecture details must not leak into Phase 4.",
            "",
            "## 58. Architecture comparison table",
            "",
        ]
    )
    for option in options:
        lines.append(
            f"- {option.get('option')} {option.get('name')}: windows={option.get('window_count')} "
            f"calls={option.get('provider_call_count')} overhead%={option.get('prompt_overhead_pct')} "
            f"unknown={option.get('main_unknown')}"
        )
    lines.extend(
        [
            "",
            "## 59. Selected architecture",
            "",
            SELECTED_ARCHITECTURE,
            "",
            "## 60. Why selected",
            "",
            decision.get("why_selected") or "",
            "",
            "## 61. Why alternatives rejected/deferred",
            "",
        ]
    )
    for name, text in (decision.get("why_rejected") or {}).items():
        lines.append(f"- {name}: {text}")
    lines.extend(
        [
            "",
            "## 62. Proposed planner parameters",
            "",
            f"candidate version = {proposed['planner_version_candidate']}.",
            f"algorithm remains = {proposed['algorithm']}.",
            f"target = {proposed['target_local_request_tokens']}.",
            f"hard max = {proposed['hard_max_local_request_tokens']}.",
            "These are PROPOSED, not production.",
            "",
            "## 63. Proposed window count",
            "",
            str(proposed["expected_clean_window_count"]),
            "",
            "## 64. Proposed context policy",
            "",
            f"{proposed['context_policy']}. Overlap not implemented.",
            "",
            "## 65. Proposed consolidation strategy",
            "",
            "ADAPTIVE HIERARCHICAL. Direct global if input fits 80k, else regional→global.",
            "",
            "## 66. Proposed response mode",
            "",
            f"{response.get('decision')}. Keep synchronous non-streaming now.",
            "",
            "## 67. Max-output decision",
            "",
            "32000 CURRENTLY UNCHANGED. Lower max_output is a future decision only.",
            "",
            "## 68. Cost implications",
            "",
            "More windows repeat prompt overhead. Historical-ratio input may exceed local.",
            "Consolidation spend remains UNKNOWN and is not treated as zero.",
            "",
            "## 69. Reliability implications",
            "",
            "Smaller structured generations should reduce ceiling/truncation risk.",
            "This is an architectural hypothesis, not a proven 1.1 success.",
            "",
            "## 70. Recovery implications",
            "",
            "One failed smaller window loses less corpus and costs less to repeat",
            "than one failed 50k window, if a future call is authorized.",
            "",
            "## 71. Implementation complexity",
            "",
            "Medium: parameterized planner + capacity branch. FakeAI first.",
            "No production planner change in this phase.",
            "",
            "## 72. Remaining unknowns",
            "",
        ]
    )
    for item in decision.get("remaining_unknowns") or []:
        lines.append(f"- {item}")
    lines.extend(
        [
            "",
            "## 73. Provider verification debt",
            "",
            "EXTERNAL PROVIDER VERIFICATION REQUIRED before streaming or async/batch.",
            "",
            "## 74. Tests",
            "",
            "Plan coverage/determinism/balance, cost unknown≠0, consolidation normal+stress,",
            "hierarchy SRC/NO-DROP, no local semantic merge, forensics regression.",
            "",
            "## 75. Network",
            "",
            "0.",
            "",
            "## 76. Protected artifacts",
            "",
            "Historical artifacts through 3B.7.7A.5 remain byte-identical.",
            "",
            "## 77. CLEAN integrity",
            "",
            f"CLEAN unchanged = {_yn(integrity.get('clean_unchanged'))}.",
            "",
            "## 78. Prompt integrity",
            "",
            f"1.1 unchanged = {_yn(integrity.get('prompt_1_1_unchanged'))}.",
            f"1.0 unchanged = {_yn(integrity.get('prompt_1_0_unchanged'))}.",
            "",
            "## 79. Granularity integrity",
            "",
            f"{integrity.get('granularity_policy')} unchanged = {_yn(integrity.get('granularity_unchanged'))}.",
            "",
            "## 80. Forensics integrity",
            "",
            f"Active = {_yn(integrity['forensics']['active'])}. Modified this phase = NO.",
            "",
            "## 81. SourceMap status",
            "",
            "NOT PUBLISHED.",
            "",
            "## 82. Project state",
            "",
            f"{integrity['project_state']['status']}. not SUCCESS = {_yn(integrity['project_state']['not_success'])}.",
            "",
            "## 83. Files added",
            "",
            "app/source_analysis_post_canary_architecture/*",
            "app/tests/test_source_analysis_post_canary_architecture.py",
            "app/tests/test_source_analysis_post_canary_architecture_audit.py",
            "audit artifacts listed in this phase.",
            "",
            "## 84. Files modified",
            "",
            "None required in production planner, prompt, granularity, max_output, or CLEAN.",
            "",
            "## 85. Recommended implementation phase",
            "",
            NEXT_PHASE_LABEL,
            "0 real provider calls. Do not jump to another paid canary.",
            "",
        ]
    )
    return "\n".join(lines) + "\n"
