"""
Phase 4B.2.7.2 — P3 negative Terra canary offline preflight and request freeze.

Offline only. Zero provider calls. Historical 4B.2.7 remains PARTIAL.
Historical 4B.2.7.1 remains PASS. Frozen 1.0 / 1.1-candidate are not modified.
1.1.1-candidate is not promoted.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
    VERDICT_FAIL,
    VERDICT_PASS,
    VERDICT_REVIEW,
)
from app.book_semantic_gate_4b24.constants import (
    CONNECTIVE_CASE_ID,
    EXPECTED_BENCHMARK_DATASET_SHA256,
    EXPECTED_BENCHMARK_FILE_SHA256,
    FUNERAL_CASE_ID,
    NEGATIVE_CASE_IDS,
    P3_CASE_ID,
    P8_CASE_ID,
    POSITIVE_CASE_IDS,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    SEMANTIC_TOKEN_BUDGET,
)
from app.book_semantic_gate_4b261.constants import (
    CANDIDATE_PROMPT_VERSION,
    CANDIDATE_TRANSPORT_VERSION,
)
from app.book_semantic_gate_4b27.constants import (
    EXPECTED_EVIDENCE_HANDLES as H01_EVIDENCE_HANDLES,
    EXPECTED_REQUEST_SHA256 as H01_REQUEST_SHA256,
    HISTORICAL_4B241_STATUS,
    HISTORICAL_4B24_STATUS,
    HISTORICAL_4B251_STATUS,
    HISTORICAL_4B25_STATUS,
    HISTORICAL_4B261_STATUS,
    HISTORICAL_4B262_STATUS,
    HISTORICAL_4B26_STATUS,
)
from app.book_semantic_gate_4b271.constants import (
    EXPECTED_PROMPT_11_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_11_SHA256,
    EXPECTED_PROMPT_11_SYSTEM_SHA256,
    EXPECTED_PROMPT_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_SYSTEM_SHA256,
    EXPECTED_SCHEMA_11_SHA256,
    EXPECTED_SCHEMA_SHA256,
    HISTORICAL_4B27_STATUS,
    PROMPT_VERSION_111,
    TRANSPORT_VERSION_11,
    TRANSPORT_VERSION_111,
)

PHASE = "4B.2.7.2"
PHASE_NAME = "P3_NEGATIVE_TERRA_CANARY_OFFLINE_PREFLIGHT"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B272_P3_NEGATIVE_TERRA_CANARY_OFFLINE_PREFLIGHT_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SDK_MAX_RETRIES = 0
RETRIES = 0
FALLBACKS = 0

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
PROMPT_VERSION_11 = CANDIDATE_PROMPT_VERSION
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"
TOKEN_FIELD = "max_completion_tokens"
PRODUCTION_SDK_METHOD = "client.chat.completions.create"

SELECTED_CASE_HANDLE = "h02"
SELECTED_CASE_ID = P3_CASE_ID
SELECTED_CASE_ROLE = "negative"
SELECTED_CASE_HUMAN_LABEL = CLASS_QUESTIONABLE
SELECTED_CASE_ACCEPTED_CLASSES = (CLASS_QUESTIONABLE, CLASS_UNSUPPORTED)
SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY = True
SELECTED_CASE_REASON_CODES_AUDIT_ONLY = ("NEW_CAUSAL_LINK", "NEW_IMPLICATION")
DISPUTED_CAUSAL_CLAUSE = (
    "because it still works wherever it is not resisted by truth"
)
P3_EVIDENCE_HANDLES = (
    "IDEA225",
    "SRC006152",
    "SRC006154",
    "SRC006155",
    "SRC006156",
    "SRC006157",
)
P3_SRC_IDS = (
    "SRC006152",
    "SRC006154",
    "SRC006155",
    "SRC006156",
    "SRC006157",
)
P3_CONTEXT_SRC_IDS = (
    "SRC006150",
    "SRC006151",
    "SRC006153",
    "SRC006158",
    "SRC006159",
)

REQUEST_SERIALIZATION = "json.dumps(payload, ensure_ascii=False, sort_keys=True)"
REQUEST_HASH_ENCODING = "utf-8"
REQUEST_HASH_ALGORITHM = "sha256"

HISTORICAL_4B271_STATUS = "PASS"
OBSERVED_4B27_COST_USD = 0.018812
OBSERVED_4B27_INPUT_TOKENS = 1654
OBSERVED_4B27_COMPLETION_TOKENS = 1292
OBSERVED_4B27_REASONING_TOKENS = 985

EXPECTED_PROMPT_111_SYSTEM_SHA256 = (
    "b4c634400bcfa9f643377ced3926a6c97a4d0eb23b8280cda117159cf39a0629"
)
EXPECTED_PROMPT_111_INSTRUCTIONS_SHA256 = (
    "2b0aa0ff0017ca10df960c47f661906a1c749c56022debde45a580cad966279a"
)
EXPECTED_PROMPT_111_SHA256 = (
    "4c280308ad70c850ff006c8f251e73696cee3b3afd55ca594df037a6756582ca"
)

H01_EXCLUSION_TOKENS = (
    "h01",
    "IDEA224",
    "SRC006149",
    "SRC006180",
    "SRC006182",
    "SRC006183",
    "SRC006187",
    "4b22_p2",
    "bargain with",
    "bargaining",
)

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert SELECTED_CASE_HANDLE == "h02"
assert SELECTED_CASE_ID == "4b22_p3_new_causal"
assert SELECTED_CASE_ROLE == "negative"
assert SELECTED_CASE_HUMAN_LABEL == CLASS_QUESTIONABLE
assert PROMPT_VERSION_111 == "book-semantic-validator-1.1.1-candidate"
assert TRANSPORT_VERSION_11 == "book-semantic-validation-transport-1.1-candidate"
assert TRANSPORT_VERSION_111 is None
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
assert TOKEN_FIELD == "max_completion_tokens"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False
assert SDK_MAX_RETRIES == 0
assert H01_REQUEST_SHA256 == (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B27_STATUS == "PARTIAL"
assert HISTORICAL_4B271_STATUS == "PASS"
assert SCORED_CASE_ORDER[1] == (SELECTED_CASE_HANDLE, SELECTED_CASE_ID)

AUDIT_DIRNAME = "book_semantic_gate_4b272"
AUDIT_IDENTITY = "p3_benchmark_identity.json"
AUDIT_INVENTORY = "p3_canonical_evidence_inventory.json"
AUDIT_CAUSAL = "p3_causal_claim_review.json"
AUDIT_LEAK = "p3_label_leakage_audit.json"
AUDIT_CONTRACT = "p3_contract_111_compatibility.json"
AUDIT_SPANS = "p3_span_coverage_audit.json"
AUDIT_SERIALIZATION = "p3_sdk_serialization.json"
AUDIT_REQUEST = "p3_request_identity.json"
AUDIT_BUDGET = "p3_context_budget.json"
AUDIT_COST = "p3_cost_estimate.json"
AUDIT_TESTS = "p3_offline_regression_tests.json"
AUDIT_PREFLIGHT = "p3_precall_readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b272_index.json"
REPORT_NAME = "PHASE_4B272_P3_NEGATIVE_TERRA_CANARY_OFFLINE_PREFLIGHT_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "AUDIT_BUDGET",
    "AUDIT_CAUSAL",
    "AUDIT_CONTRACT",
    "AUDIT_COST",
    "AUDIT_DIRNAME",
    "AUDIT_IDENTITY",
    "AUDIT_INDEX",
    "AUDIT_INVENTORY",
    "AUDIT_LEAK",
    "AUDIT_PREFLIGHT",
    "AUDIT_REQUEST",
    "AUDIT_SERIALIZATION",
    "AUDIT_SPANS",
    "AUDIT_TESTS",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "CANDIDATE_PROMPT_VERSION",
    "CANDIDATE_TRANSPORT_VERSION",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CONNECTIVE_CASE_ID",
    "DISPUTED_CAUSAL_CLAUSE",
    "EXPECTED_BENCHMARK_DATASET_SHA256",
    "EXPECTED_BENCHMARK_FILE_SHA256",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_OPENAI_SDK_VERSION",
    "EXPECTED_PROMPT_111_INSTRUCTIONS_SHA256",
    "EXPECTED_PROMPT_111_SHA256",
    "EXPECTED_PROMPT_111_SYSTEM_SHA256",
    "EXPECTED_PROMPT_11_INSTRUCTIONS_SHA256",
    "EXPECTED_PROMPT_11_SHA256",
    "EXPECTED_PROMPT_11_SYSTEM_SHA256",
    "EXPECTED_PROMPT_INSTRUCTIONS_SHA256",
    "EXPECTED_PROMPT_SYSTEM_SHA256",
    "EXPECTED_PYTHON_VERSION",
    "EXPECTED_SCHEMA_11_SHA256",
    "EXPECTED_SCHEMA_SHA256",
    "EXPECTED_SOURCE_MAP",
    "FALLBACKS",
    "FUNERAL_CASE_ID",
    "H01_EVIDENCE_HANDLES",
    "H01_EXCLUSION_TOKENS",
    "H01_REQUEST_SHA256",
    "HISTORICAL_4B241_STATUS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B251_STATUS",
    "HISTORICAL_4B25_STATUS",
    "HISTORICAL_4B261_STATUS",
    "HISTORICAL_4B262_STATUS",
    "HISTORICAL_4B26_STATUS",
    "HISTORICAL_4B271_STATUS",
    "HISTORICAL_4B27_STATUS",
    "MODEL",
    "NEGATIVE_CASE_IDS",
    "NEXT_ACTION",
    "OBSERVED_4B27_COMPLETION_TOKENS",
    "OBSERVED_4B27_COST_USD",
    "OBSERVED_4B27_INPUT_TOKENS",
    "OBSERVED_4B27_REASONING_TOKENS",
    "OUTPUT_MODE",
    "P3_CASE_ID",
    "P3_CONTEXT_SRC_IDS",
    "P3_EVIDENCE_HANDLES",
    "P3_SRC_IDS",
    "P8_CASE_ID",
    "PHASE",
    "PHASE_NAME",
    "POSITIVE_CASE_IDS",
    "PRODUCTION_ENDPOINT",
    "PRODUCTION_SDK_METHOD",
    "PROJECT_NAME",
    "PROMPT_VERSION_11",
    "PROMPT_VERSION_111",
    "PROMPT_VERSION_HISTORICAL",
    "PROVIDER",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "READY_FOR_NEW_REMOTE_TERRA_CALL",
    "REPORT_NAME",
    "REQUEST_HASH_ALGORITHM",
    "REQUEST_HASH_ENCODING",
    "REQUEST_SERIALIZATION",
    "RETRIES",
    "SCORED_CASE_ORDER",
    "SDK_MAX_RETRIES",
    "SELECTED_CASE_ACCEPTED_CLASSES",
    "SELECTED_CASE_HANDLE",
    "SELECTED_CASE_HUMAN_LABEL",
    "SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY",
    "SELECTED_CASE_ID",
    "SELECTED_CASE_REASON_CODES_AUDIT_ONLY",
    "SELECTED_CASE_ROLE",
    "SEMANTIC_TOKEN_BUDGET",
    "TEMPERATURE_POLICY",
    "TERRA_EXECUTION_AUTHORIZED",
    "THINKING_MODE",
    "TOKEN_FIELD",
    "TRANSPORT_VERSION_11",
    "TRANSPORT_VERSION_111",
    "TRANSPORT_VERSION_HISTORICAL",
    "VERDICT_FAIL",
    "VERDICT_PASS",
    "VERDICT_REVIEW",
]
