"""
Phase 4B.2.1 — Book Generator canary forensics + contract hardening.

Offline only. Zero provider calls. Historical 4B.2 remains FAIL.
"""

from __future__ import annotations

from app.book_generation.constants import (
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION_V10,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    EVIDENCE_STRATEGY_HYDRATED,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    MODEL,
    PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_generator_canary_4b2.constants import (
    PHASE_4B1_ADAPTED_SCHEMA_BYTES,
    PHASE_4B1_ADAPTED_SCHEMA_SHA256,
    PHASE_4B1_CH016_EVIDENCE_SHA256,
    PHASE_4B1_CH016_MAX_OUTPUT,
    PHASE_4B1_CH016_REQUEST_SHA256,
    PHASE_4B1_RAW_SCHEMA_BYTES,
    PHASE_4B1_RAW_SCHEMA_SHA256,
    PHASE_4B1_TRANSCRIPT_CONTENT_SHA256,
)

PHASE = "4B.2.1"
PHASE_NAME = "BOOK_GENERATOR_CANARY_FORENSICS_AND_HARDENING"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

TARGET_CHAPTER_ID = "CH016"
HISTORICAL_4B2_STATUS = "FAIL"
REAL_PROVIDER_CALLS = 0

HISTORICAL_PROMPT_VERSION = BOOK_GENERATOR_PROMPT_VERSION_V10
SUCCESSOR_PROMPT_VERSION = BOOK_GENERATOR_PROMPT_VERSION
TRANSPORT_VERSION = BOOK_GENERATION_TRANSPORT_VERSION
VALIDATOR_VERSION = BOOK_GENERATOR_VALIDATOR_VERSION

assert HISTORICAL_PROMPT_VERSION == "book-generator-1.0"
assert SUCCESSOR_PROMPT_VERSION == "book-generator-1.0.1"
assert TRANSPORT_VERSION == "book-generation-transport-1.0"
assert VALIDATOR_VERSION == "book-generation-validator-1.0.1"

HISTORICAL_REQUEST_SHA256 = PHASE_4B1_CH016_REQUEST_SHA256
HISTORICAL_CANDIDATE_SHA256 = (
    "51635cedf7fee34b34fd80466c2361968494e2e98c15d861682401bddd2aaad5"
)
HISTORICAL_RAW_RESPONSE_SHA256 = (
    "3a291c879d852daec8a00d0bf9f18e3e1c902643658f9e6f3aaa5066206e9749"
)
EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_CLEAN_TRANSCRIPT = PHASE_4B1_TRANSCRIPT_CONTENT_SHA256
EXPECTED_EVIDENCE_SHA256 = PHASE_4B1_CH016_EVIDENCE_SHA256
EXPECTED_MAX_OUTPUT = PHASE_4B1_CH016_MAX_OUTPUT

EMPTY_PARAGRAPH_HANDLE = "p9b"
CONNECTIVE_CLAIM_HANDLE = "p13"
INVENTED_ILLUSTRATION_HANDLE = "p8"
TARGET_SECTION_ID = "SEC063"

HYDRATION_STRATEGY = EVIDENCE_STRATEGY_HYDRATED
FUTURE_MODEL = f"{PROVIDER} / {MODEL}"
FUTURE_THINKING = "disabled"
FUTURE_MAX_OUTPUT = EXPECTED_MAX_OUTPUT

AUDIT_DIRNAME = "book_generator_4b21"
AUDIT_EMPTY = "book_generator_4b21_empty_paragraph_forensics.json"
AUDIT_CONNECTIVE = "book_generator_4b21_connective_claim_forensics.json"
AUDIT_ILLUSTRATION = "book_generator_4b21_invented_illustration_forensics.json"
AUDIT_ROOT_CAUSE = "book_generator_4b21_root_cause_matrix.json"
AUDIT_PROMPT = "book_generator_4b21_prompt_hardening.json"
AUDIT_SCHEMA = "book_generator_4b21_schema_transport_decision.json"
AUDIT_VALIDATOR = "book_generator_4b21_validator_hardening.json"
AUDIT_SEMANTIC = "book_generator_4b21_semantic_validation_architecture.json"
AUDIT_FUTURE_REQUEST = "book_generator_4b21_future_CH016_request_identity.json"
AUDIT_COST = "book_generator_4b21_future_cost_estimate.json"
AUDIT_READINESS = "book_generator_post_4b21_readiness.json"
REPORT_NAME = "PHASE_4B21_BOOK_GENERATOR_CANARY_FORENSICS_AND_HARDENING_REPORT.md"

PUBLICATION_AUTHORIZED = False
READY_FOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False
NEXT_ACTION = "HUMAN REVIEW"

assert REAL_PROVIDER_CALLS == 0
assert PUBLICATION_AUTHORIZED is False
assert READY_FOR_FULL_REAL_BOOK_GENERATION is False
assert PHASE_4B1_RAW_SCHEMA_BYTES == 1035
assert PHASE_4B1_ADAPTED_SCHEMA_BYTES == 1128
assert PHASE_4B1_RAW_SCHEMA_SHA256
assert PHASE_4B1_ADAPTED_SCHEMA_SHA256
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
