"""Constantes du design 3B.7 — aucun appel provider."""

from __future__ import annotations

SCHEMA_VERSION = "1.0"
PHASE = "3B.7"
MODE = "OFFLINE_DESIGN"

WINDOW_DESIGN_ARTIFACT_NAME = "source_analysis_hybrid_window_design.json"
CONSOLIDATION_DESIGN_ARTIFACT_NAME = (
    "source_analysis_hybrid_consolidation_design.json"
)
PLANNER_SIMULATION_ARTIFACT_NAME = (
    "source_analysis_window_planner_v2_simulation.json"
)
ARCHITECTURE_DESIGN_ARTIFACT_NAME = (
    "source_analysis_hybrid_architecture_design.json"
)
REPORT_NAME = (
    "PHASE_3B7_HYBRID_WINDOW_PLUS_GLOBAL_CONSOLIDATION_DESIGN_REPORT.md"
)

STRATEGY = "HYBRID_WINDOW_PLUS_GLOBAL_CONSOLIDATION"

PLANNER_VERSION = "window-planner-v2.0"
PLANNER_NAME = "WindowPlannerV2"

# Production planner policy — selected after candidate simulation.
TARGET_INPUT_TOKENS = 50000
HARD_MAX_INPUT_TOKENS = 60000
OVERLAP_POLICY = "NO_OWNED_OVERLAP"
BOUNDARY_CONTEXT_POLICY = "NONE"
TINY_TAIL_MIN_FRACTION_OF_TARGET = 0.15
TINY_TAIL_MIN_CONTENT_OVERHEAD_FACTOR = 2.0

CANDIDATE_TARGET_INPUT_TOKENS = (40000, 50000, 60000, 75000)

# Hard-max paired with each candidate target for simulation only.
CANDIDATE_HARD_MAX_INPUT_TOKENS = {
    40000: 50000,
    50000: 60000,
    60000: 72000,
    75000: 90000,
}

WINDOW_PROMPT_VERSION = "window-analysis-1.0"
CONSOLIDATION_PROMPT_VERSION = "consolidation-1.0"
WINDOW_TRANSPORT_VERSION = "semantic-transport-v1"
CONSOLIDATION_TRANSPORT_VERSION = "consolidation-transport-v1"

EXPECTED_PROVIDER = "anthropic"
EXPECTED_MODEL = "claude-sonnet-5"
ESTIMATION_MODEL = EXPECTED_MODEL
EXPECTED_PROMPT_VERSION = "1.3"
EXPECTED_TRANSCRIPT_ID = "TR001"
EXPECTED_INPUT_MODE = "DERIVED"
EXPECTED_SEGMENTS = 8298
EXPECTED_WORDS = 38313
EXPECTED_DURATION_SECONDS = 19954.601
EXPECTED_CLEAN_SHA256 = (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
EXPECTED_GENERATION_C_RAW_SHA256 = (
    "90885d692bf56695e33f6205013a7f81d21b6b520e90b59338f43113fc17b0f9"
)
EXPECTED_GENERATION_C_ANTHROPIC_SHA256 = (
    "5e54bc73257ee7d6c68ac74818974973bc7ece506556a8e975c56ef3ada18ae1"
)

WINDOW_MAX_OUTPUT_TOKENS = 32000
CONSOLIDATION_MAX_OUTPUT_TOKENS = 16000
CONSOLIDATION_SAFE_INPUT_TOKENS = 80000

WINDOW_CONNECT_TIMEOUT_SECONDS = 30
WINDOW_READ_TIMEOUT_SECONDS = 1800
CONSOLIDATION_CONNECT_TIMEOUT_SECONDS = 30
CONSOLIDATION_READ_TIMEOUT_SECONDS = 1800

STAGE_WINDOW = "source_analysis_window"
STAGE_CONSOLIDATION = "source_analysis_consolidation"
STAGE_AGGREGATE = "source_analysis"

EXECUTION_ORDER = "SEQUENTIAL"

BASELINE_PASSED = 2044
BASELINE_FAILED = 0
FINAL_PASSED = 2059
FINAL_FAILED = 0

PROVIDER_CALLS = 0
SOURCE_MAP_PUBLISHED = False
PHASE_3B_STATUS = "INCOMPLETE"
NEXT_PHASE = "3B.7.1_WINDOW_PLANNER_V2_AND_HYBRID_CONTRACTS"
NEXT_PHASE_LABEL = "3B.7.1 — WINDOW PLANNER V2 & HYBRID CONTRACTS"

CANONICAL_SOURCEMAP_CONTRACT = "UNCHANGED"
CANONICAL_VALIDATOR = "UNCHANGED"

__all__ = [
    "ARCHITECTURE_DESIGN_ARTIFACT_NAME",
    "CONSOLIDATION_DESIGN_ARTIFACT_NAME",
    "HARD_MAX_INPUT_TOKENS",
    "MODE",
    "NEXT_PHASE",
    "OVERLAP_POLICY",
    "PHASE",
    "PLANNER_SIMULATION_ARTIFACT_NAME",
    "PLANNER_VERSION",
    "REPORT_NAME",
    "SCHEMA_VERSION",
    "STRATEGY",
    "TARGET_INPUT_TOKENS",
    "WINDOW_DESIGN_ARTIFACT_NAME",
]
