"""
Phase 4B.2.30 — Word print profile preparation for 6x9.

STRICTLY OFFLINE. Zero provider calls. Zero USD.
Configures the Word renderer. Does not generate the book DOCX or PDF.
Does not modify book.json or chapter sources.
"""

from __future__ import annotations

from app.book_print_review_canonical_4b229.constants import (
    ACCEPTED_CHAPTER_COUNT,
    ACCEPTED_CHAPTER_IDS,
    AUTHORIZATION_SCOPE as CONSUMED_4B229_SCOPE,
    BOOK_STATUS,
    BOOK_TITLE,
    BOOK_VERSION,
    CANONICAL_CHAPTER_IDS,
    EXPECTED_IDEA_COUNT,
    EXPECTED_SECTION_COUNT,
    PENDING_CHAPTER_IDS,
    PROJECT_NAME,
    REMAINING_CHAPTER_COUNT,
)
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE
from app.word_renderer.constants import PROFILE_NAME

PHASE = "4B.2.30"
PHASE_NAME = "WORD_PRINT_PROFILE_PREPARATION"

assert PROJECT_NAME == "pastoral_retreat_v2_validation"
assert BOOK_TITLE == "The Life You Already Inherited"
assert BOOK_VERSION == "print-review-v1"
assert BOOK_STATUS == "DRAFT_FOR_PRINT_REVIEW"

AUTHORIZATION_SCOPE = "BOOK_WORD_PRINT_PROFILE_4B230_PREPARATION_ONLY"

AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_TERRA_CALLS = 0
MAX_ENGINE_GENERATE = 0
MAX_ANTHROPIC_POST = 0
MAX_HTTP_REQUESTS = 0

DOCX_GENERATION_AUTHORIZED = False
PDF_GENERATION_AUTHORIZED = False
COVER_GENERATION_AUTHORIZED = False
VISUAL_DIRECTION_AUTHORIZED = False
FINAL_PUBLICATION_AUTHORIZED = False
COMMERCIAL_PUBLICATION_AUTHORIZED = False
PUBLIC_PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
OPENAI_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = False
REAL_CHAPTER_GENERATION_AUTHORIZED = False
BOOK_JSON_MUTATION_AUTHORIZED = False

EXPECTED_BOOK_SHA256 = (
    "adde6e2344f4b94da0f7df183341885574e89abc90781c426459e850cc2b6550"
)
EXPECTED_CHAPTER_COUNT = 19
EXPECTED_HUMAN_ACCEPTED = ACCEPTED_CHAPTER_COUNT
EXPECTED_STRUCTURAL = REMAINING_CHAPTER_COUNT
assert EXPECTED_CHAPTER_COUNT == 19
assert EXPECTED_SECTION_COUNT == 72
assert EXPECTED_IDEA_COUNT == 286
assert EXPECTED_HUMAN_ACCEPTED == 6
assert EXPECTED_STRUCTURAL == 13
assert len(CANONICAL_CHAPTER_IDS) == 19
assert len(ACCEPTED_CHAPTER_IDS) == 6
assert len(PENDING_CHAPTER_IDS) == 13

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
CODE_VERSION = "app.word_print_profile_4b230"
PRINT_PROFILE = PROFILE_NAME
PRINT_FORMAT = "6 × 9 inches"

AUDIT_DIRNAME = "word_print_profile_4b230"
AUDIT_INVENTORY = "word_renderer_inventory.json"
AUDIT_PROFILE = "print_profile_6x9.json"
AUDIT_STYLES = "styles_validation.json"
AUDIT_GEOMETRY = "page_geometry_validation.json"
AUDIT_TOC = "toc_validation.json"
AUDIT_HEADERS = "headers_footers_validation.json"
AUDIT_MAPPING = "book_mapping_validation.json"
AUDIT_FINALIZER = "word_finalizer_readiness.json"
AUDIT_COVER = "cover_integration_contract.json"
AUDIT_TESTS = "offline_tests.json"
AUDIT_HASHES = "canonical_hashes_pre_post.json"
AUDIT_READINESS = "readiness.json"
REPORT_NAME = "PHASE_4B230_WORD_PRINT_PROFILE_PREPARATION_REPORT.md"

NEXT_ACTION = (
    "WAIT FOR PHASE 4B.2.31: GENERATE THE FIRST PRINTABLE DOCX AND PDF "
    "FROM book.json USING print_review_6x9_v1. DO NOT MODIFY CHAPTERS. "
    "DO NOT MODIFY book.json. DO NOT GENERATE A COVER. DO NOT CALL "
    "ANTHROPIC. DO NOT CALL OPENAI. DO NOT CALL TERRA. DO NOT PUBLISH "
    "A FINAL EDITION."
)

assert AUTHORIZED_ANTHROPIC_CALLS == 0
assert AUTHORIZED_OPENAI_CALLS == 0
assert AUTHORIZED_TERRA_CALLS == 0
assert DOCX_GENERATION_AUTHORIZED is False
assert PDF_GENERATION_AUTHORIZED is False
assert BOOK_JSON_MUTATION_AUTHORIZED is False
assert CANONICAL_PYTHON.endswith("python.exe")
assert CONSUMED_4B229_SCOPE.startswith("BOOK_PRINT_REVIEW_CANONICAL_4B229_")

__all__ = [
    "AUTHORIZATION_SCOPE",
    "BOOK_STATUS",
    "BOOK_TITLE",
    "BOOK_VERSION",
    "EXPECTED_BOOK_SHA256",
    "PHASE",
    "PRINT_PROFILE",
    "PROJECT_NAME",
    "REPORT_NAME",
]
