"""Constantes 3B.7.7A.24 — retry durci WIN004 V3 prompt 1.3.2. 1 appel max."""

from __future__ import annotations

from app.source_analysis.window_models import (
    WINDOW_CONNECT_TIMEOUT_SECONDS,
    WINDOW_READ_TIMEOUT_SECONDS,
)
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    CLEAN_SHA,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
    SELECTED_ARCHITECTURE,
    SEMANTIC_TRANSPORT_VERSION_V3,
    TARGET_JSON_LOCAL_TOKENS,
    WINDOW_ANALYSIS_PROMPT_VERSION_V13,
    WINDOW_ANALYSIS_PROMPT_VERSION_V131,
    WINDOW_ANALYSIS_PROMPT_VERSION_V132,
)
from app.source_analysis_local_v3.schema import semantic_transport_v3_fingerprint
from app.source_analysis_output_ceiling_review.constants import (
    CALL1_SIGNATURE,
    CALL2_SIGNATURE,
    SMALL_SIGNATURE,
)
from app.source_analysis_small_window_hierarchy.constants import (
    CANDIDATE_CONTEXT_POLICY,
)
from app.source_analysis_thinking_contract.constants import (
    SELECTED_CONTRACT,
    SELECTED_EFFORT,
    SELECTED_THINKING_MODE,
)
from app.source_analysis_v2_a15_forensics.constants import A15_SIGNATURE
from app.source_analysis_v2_link_semantics.constants import A13_REQUEST_IDENTITY
from app.source_analysis_v3_a19_forensics.constants import (
    A19_STATUS_UNCHANGED,
    EXAMPLE_POLICY,
    EXAMPLE_POLICY_LABEL,
    PROTECTED_A19,
    REPORT_NAME as A20_REPORT,
    V3_HANDLE_ARCHITECTURE,
)
from app.source_analysis_v3_a22_forensics.constants import (
    A21_RESULT,
    A22_COVERAGE_PCT,
    A22_DISTINCT_SRC,
    A22_EXAMPLE,
    A22_FINISH,
    A22_FORENSIC_IDENTITY,
    A22_HTTP,
    A22_IDEA,
    A22_INPUT_HASH,
    A22_LOCAL_INPUT,
    A22_OUTPUT,
    A22_OWNED,
    A22_PROMPT_FINGERPRINT,
    A22_PROMPT_SHA256,
    A22_PROVIDER_INPUT,
    A22_QUALITY_REASON_REPORTED,
    A22_QUALITY_REPORTED,
    A22_RECORDS,
    A22_REFERENCE,
    A22_RELATION,
    A22_REQUEST_ID,
    A22_SIGNATURE,
    A22_SRC_RANGE,
    A22_STATUS_UNCHANGED,
    A22_STRUCTURED_PARSE,
    A22_TARGET,
    A22_THINKING,
    A22_THINKING_TOKENS,
    A22_TOPIC,
    A22_TOTAL_SRC_OCCURRENCES,
    A22_UNCERTAINTY,
    A22_VALID_SRC_OCCURRENCES,
    A22_WORDS,
    CONTRACT_ARTIFACT as A23_CONTRACT_ARTIFACT,
    COVERAGE_ARTIFACT as A23_COVERAGE_ARTIFACT,
    FOUR_RECORDS_ARTIFACT as A23_FOUR_RECORDS_ARTIFACT,
    FUTURE_RETRY_ARTIFACT as A23_FUTURE_RETRY_ARTIFACT,
    PROTECTED_A22,
    PROTECTED_HISTORICAL as A23_PROTECTED_HISTORICAL,
    REASONING_ARTIFACT as A23_REASONING_ARTIFACT,
    REPORT_NAME as A23_REPORT_NAME,
    SEMANTIC_ARTIFACT as A23_SEMANTIC_ARTIFACT,
    VIOLATION_ARTIFACT as A23_VIOLATION_ARTIFACT,
)
from app.source_analysis_v3_hardened_win001.constants import (
    AUTHORIZATION_SCOPE as A21_AUTHORIZATION_SCOPE,
    EXPECTED_ANALYSIS_SIGNATURE as A21_SIGNATURE,
    EXPECTED_FORENSIC_IDENTITY as A21_FORENSIC,
    EXPECTED_PROMPT_SHA256 as A21_PROMPT_SHA256,
    WINDOW_ID as A21_WINDOW_ID,
)
from app.source_analysis_v3_real_win001.constants import (
    EXPECTED_A18_REQUEST_IDENTITY,
    EXPECTED_ANALYSIS_SIGNATURE as A19_SIGNATURE,
    EXPECTED_FORENSIC_IDENTITY as A19_FORENSIC,
)
from app.source_analysis_v3_second_window.constants import (
    AUTHORIZATION_SCOPE as A22_AUTHORIZATION_SCOPE,
    EXPECTED_SCHEMA_HASH,
    EXPECTED_WIN004_FIRST_OWNED_SRC,
    EXPECTED_WIN004_INPUT_HASH,
    EXPECTED_WIN004_LAST_OWNED_SRC,
    EXPECTED_WIN004_OWNED_SRC_COUNT,
    EXPECTED_WIN004_WORD_COUNT,
)
from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.24"
MODE = "REAL_V3_SMALL_WIN004_HARDENED_TYPE_CONTRACT_RETRY"

AUTHORIZATION_SCOPE = "SMALL_V21_V3_HARDENED_WIN004_ONLY"
WINDOW_ID = "WIN004"
FORBIDDEN_WINDOW_IDS = (
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN005",
    "WIN006",
    "WIN007",
    "WIN996",
)

PROVIDER = "anthropic"
MODEL = "claude-sonnet-5"
THINKING_CONTRACT = SELECTED_CONTRACT
THINKING_MODE = SELECTED_THINKING_MODE
EFFORT = SELECTED_EFFORT

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False

MAX_OUTPUT_TOKENS = MAX_OUTPUT_TOKENS_FROZEN
CONNECT_TIMEOUT_SECONDS = WINDOW_CONNECT_TIMEOUT_SECONDS
READ_TIMEOUT_SECONDS = WINDOW_READ_TIMEOUT_SECONDS
HISTORICAL_READ_TIMEOUT_SECONDS = 7200.0

EXPECTED_ANALYSIS_SIGNATURE = (
    "8c81f70cfb450d2e4f83921e32f9d3be3b020c0c6b41cd84a683f8bc75688908"
)
EXPECTED_FORENSIC_IDENTITY = (
    "96fd10c9e2563454556154c69c9b980647e1c7429b12713125f34c09730c57bd"
)
EXPECTED_PROMPT_SHA256 = (
    "d9af4d54fc73352b11ca62c2a788a5e899c3ded0b452e1827de7c2f854b16e8a"
)
EXPECTED_PROMPT_FINGERPRINT = (
    "7e1a020b6914778b06773b6b198fb8d31b9367224eadcac785053bf33bd0d5ce"
)
EXPECTED_SCHEMA_HASH = EXPECTED_SCHEMA_HASH
EXPECTED_WINDOW_INPUT_HASH = EXPECTED_WIN004_INPUT_HASH
EXPECTED_OWNED_SRC_COUNT = EXPECTED_WIN004_OWNED_SRC_COUNT
EXPECTED_WORD_COUNT = EXPECTED_WIN004_WORD_COUNT
EXPECTED_FIRST_OWNED_SRC = EXPECTED_WIN004_FIRST_OWNED_SRC
EXPECTED_LAST_OWNED_SRC = EXPECTED_WIN004_LAST_OWNED_SRC
EXPECTED_CLEAN_SHA = CLEAN_SHA
EXPECTED_CLEAN_FILE_SHA = CLEAN_SHA
EXPECTED_CONTEXT_COUNT = 0
EXPECTED_CONTEXT_POLICY = CANDIDATE_CONTEXT_POLICY
EXPECTED_LOCAL_INPUT_ESTIMATE = 22957

A13_SYNTHETIC_IDENTITY = A13_REQUEST_IDENTITY
A15_V2_SIGNATURE = A15_SIGNATURE
A18_REQUEST_IDENTITY = EXPECTED_A18_REQUEST_IDENTITY
A19_V3_SIGNATURE = A19_SIGNATURE
A19_V3_FORENSIC = A19_FORENSIC
A19_RESULT = A19_STATUS_UNCHANGED
A21_V3_SIGNATURE = A21_SIGNATURE
A21_V3_FORENSIC = A21_FORENSIC
A21_RESULT = A21_RESULT
A22_V3_SIGNATURE = A22_SIGNATURE
A22_V3_FORENSIC = A22_FORENSIC_IDENTITY
A22_RESULT = A22_STATUS_UNCHANGED
A23_RESULT = "PASS"

A22_PROMPT = WINDOW_ANALYSIS_PROMPT_VERSION_V131
A22_READY = "1 / 7"

SYNTHETIC_WORST_CASE_LOCAL_TOKENS = 12185

LOCK_NAME = "a24_real_v3_hardened_win004.lock"
CANARY_SUBDIR = "canary/v3_hardened_win004"
CANDIDATE_WINDOWS_SUBDIR = "v3_windows"
CANDIDATE_CACHE_SUBDIR = "v3_cache"

PREFLIGHT_ARTIFACT = "source_analysis_v3_hardened_win004_preflight.json"
EXECUTION_ARTIFACT = "source_analysis_v3_hardened_win004_execution.json"
METADATA_ARTIFACT = "source_analysis_v3_hardened_win004_metadata_analysis.json"
SRC_ARTIFACT = "source_analysis_v3_hardened_win004_src_analysis.json"
HANDLE_ARTIFACT = "source_analysis_v3_hardened_win004_handle_analysis.json"
REVIEW_ARTIFACT = "source_analysis_v3_hardened_win004_semantic_review.json"
COMPARISON_ARTIFACT = "source_analysis_v3_hardened_win004_vs_a22.json"
REPORT_NAME = "PHASE_3B77A24_REAL_WIN004_HARDENED_TYPE_CONTRACT_RETRY_REPORT.md"

SEMANTIC_REVIEW_STATUS = "FORENSIC_SEMANTIC_REVIEW_OF_VALID_V3_WIN004_CANDIDATE"
SEMANTIC_REVIEW_INVALID = "FORENSIC_SEMANTIC_REVIEW_OF_INVALID_V3_TRANSPORT"
EXAMPLE_POLICY = EXAMPLE_POLICY
EXAMPLE_POLICY_LABEL = EXAMPLE_POLICY_LABEL
SERVER_GRAMMAR_STATUS = "A18_PROOF_APPLICABLE"

PROTECTED_A23 = (
    f"audit/{A23_REPORT_NAME}",
    f"audit/{A23_VIOLATION_ARTIFACT}",
    f"audit/{A23_CONTRACT_ARTIFACT}",
    f"audit/{A23_FOUR_RECORDS_ARTIFACT}",
    f"audit/{A23_SEMANTIC_ARTIFACT}",
    f"audit/{A23_COVERAGE_ARTIFACT}",
    f"audit/{A23_REASONING_ARTIFACT}",
    f"audit/{A23_FUTURE_RETRY_ARTIFACT}",
)

PROTECTED_HISTORICAL = tuple(A23_PROTECTED_HISTORICAL) + PROTECTED_A23

DRY_RUN_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v3_hardened_win004 "
    "pastoral_retreat_v2_validation "
    "--authorization-scope SMALL_V21_V3_HARDENED_WIN004_ONLY "
    "--window WIN004 --dry-run"
)
REAL_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v3_hardened_win004 "
    "pastoral_retreat_v2_validation "
    "--authorization-scope SMALL_V21_V3_HARDENED_WIN004_ONLY "
    "--window WIN004 --execute-real"
)

NEXT_ACTION = "HUMAN REVIEW"
NEXT_PHASE = "3B.7.7A.25_BOUNDED_REMAINING_REAL_WINDOWS_EXECUTION"
NEXT_PHASE_LABEL = (
    "3B.7.7A.25 — BOUNDED REMAINING REAL WINDOWS EXECUTION "
    "(WIN002/003/005/006/007, 5 calls maximum, STOP ON FIRST FAILURE; "
    "do not execute in A.24)"
)
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION
PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V132
TRANSPORT_VERSION = SEMANTIC_TRANSPORT_VERSION_V3

assert EXPECTED_SCHEMA_HASH == (
    "de42ce0f3c271e67b902a94d2f528eae56f82b1a2a5740e65161987038849425"
)
assert semantic_transport_v3_fingerprint() == EXPECTED_SCHEMA_HASH
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert MAX_OUTPUT_TOKENS == 32000
assert THINKING_MODE == "disabled"
assert EFFORT is None
assert AUTHORIZATION_SCOPE == "SMALL_V21_V3_HARDENED_WIN004_ONLY"
assert AUTHORIZATION_SCOPE != A21_AUTHORIZATION_SCOPE
assert AUTHORIZATION_SCOPE != A22_AUTHORIZATION_SCOPE
assert WINDOW_ID == "WIN004"
assert WINDOW_ID != A21_WINDOW_ID
assert WINDOW_ID == A22_TARGET
assert EXPECTED_ANALYSIS_SIGNATURE != A22_V3_SIGNATURE
assert EXPECTED_ANALYSIS_SIGNATURE != A21_V3_SIGNATURE
assert EXPECTED_ANALYSIS_SIGNATURE != A19_V3_SIGNATURE
assert EXPECTED_FORENSIC_IDENTITY != A22_V3_FORENSIC
assert EXPECTED_PROMPT_SHA256 != A21_PROMPT_SHA256
assert EXPECTED_PROMPT_SHA256 != A22_PROMPT_SHA256
assert EXPECTED_LOCAL_INPUT_ESTIMATE == 22957
assert EXPECTED_OWNED_SRC_COUNT == 1180
assert EXPECTED_WORD_COUNT == 5662
assert A19_RESULT == "FAIL"
assert A21_RESULT == "PASS"
assert A22_RESULT == "FAIL"
assert A23_RESULT == "PASS"
assert PROMPT_VERSION == "window-analysis-1.3.2"
assert WINDOW_ANALYSIS_PROMPT_VERSION_V131 == "window-analysis-1.3.1"
assert WINDOW_ANALYSIS_PROMPT_VERSION_V13 == "window-analysis-1.3"

__all__ = [
    "A13_SYNTHETIC_IDENTITY",
    "A15_V2_SIGNATURE",
    "A18_REQUEST_IDENTITY",
    "A19_RESULT",
    "A19_V3_FORENSIC",
    "A19_V3_SIGNATURE",
    "A21_AUTHORIZATION_SCOPE",
    "A21_RESULT",
    "A21_V3_FORENSIC",
    "A21_V3_SIGNATURE",
    "A21_WINDOW_ID",
    "A22_AUTHORIZATION_SCOPE",
    "A22_COVERAGE_PCT",
    "A22_DISTINCT_SRC",
    "A22_EXAMPLE",
    "A22_FINISH",
    "A22_HTTP",
    "A22_IDEA",
    "A22_INPUT_HASH",
    "A22_LOCAL_INPUT",
    "A22_OUTPUT",
    "A22_OWNED",
    "A22_PROMPT",
    "A22_PROMPT_FINGERPRINT",
    "A22_PROMPT_SHA256",
    "A22_PROVIDER_INPUT",
    "A22_QUALITY_REASON_REPORTED",
    "A22_QUALITY_REPORTED",
    "A22_READY",
    "A22_RECORDS",
    "A22_REFERENCE",
    "A22_RELATION",
    "A22_REQUEST_ID",
    "A22_RESULT",
    "A22_SRC_RANGE",
    "A22_STRUCTURED_PARSE",
    "A22_TARGET",
    "A22_THINKING",
    "A22_THINKING_TOKENS",
    "A22_TOPIC",
    "A22_TOTAL_SRC_OCCURRENCES",
    "A22_UNCERTAINTY",
    "A22_VALID_SRC_OCCURRENCES",
    "A22_V3_FORENSIC",
    "A22_V3_SIGNATURE",
    "A22_WORDS",
    "A23_RESULT",
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "CALL1_SIGNATURE",
    "CALL2_SIGNATURE",
    "CANARY_SUBDIR",
    "CANDIDATE_CACHE_SUBDIR",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER",
    "CANDIDATE_WINDOWS_SUBDIR",
    "COMPARISON_ARTIFACT",
    "CONNECT_TIMEOUT_SECONDS",
    "DRY_RUN_COMMAND",
    "EFFORT",
    "EXAMPLE_POLICY",
    "EXAMPLE_POLICY_LABEL",
    "EXECUTION_ARTIFACT",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_ANALYSIS_SIGNATURE",
    "EXPECTED_CLEAN_FILE_SHA",
    "EXPECTED_CLEAN_SHA",
    "EXPECTED_CONTEXT_COUNT",
    "EXPECTED_CONTEXT_POLICY",
    "EXPECTED_FIRST_OWNED_SRC",
    "EXPECTED_FORENSIC_IDENTITY",
    "EXPECTED_LAST_OWNED_SRC",
    "EXPECTED_LOCAL_INPUT_ESTIMATE",
    "EXPECTED_OWNED_SRC_COUNT",
    "EXPECTED_PROMPT_FINGERPRINT",
    "EXPECTED_PROMPT_SHA256",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "EXPECTED_SCHEMA_HASH",
    "EXPECTED_WINDOW_INPUT_HASH",
    "EXPECTED_WORD_COUNT",
    "FORBIDDEN_WINDOW_IDS",
    "HANDLE_ARTIFACT",
    "HISTORICAL_READ_TIMEOUT_SECONDS",
    "LOCK_NAME",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MAX_OUTPUT_TOKENS",
    "METADATA_ARTIFACT",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "PHASE",
    "PHASE_3B_STATUS",
    "PREFLIGHT_ARTIFACT",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROTECTED_A22",
    "PROTECTED_A23",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "READ_TIMEOUT_SECONDS",
    "REAL_COMMAND",
    "REPORT_NAME",
    "REVIEW_ARTIFACT",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SEMANTIC_REVIEW_INVALID",
    "SEMANTIC_REVIEW_STATUS",
    "SERVER_GRAMMAR_STATUS",
    "SMALL_SIGNATURE",
    "SRC_ARTIFACT",
    "SYNTHETIC_WORST_CASE_LOCAL_TOKENS",
    "TARGET_JSON_LOCAL_TOKENS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
    "V3_HANDLE_ARCHITECTURE",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V13",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V131",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V132",
    "WINDOW_ID",
]
