"""Constantes 3B.7.7A.35 — canary grammar/transport consolidation globale synthétique."""

from __future__ import annotations

from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE,
    SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION,
    WINDOW_ANALYSIS_PROMPT_VERSION_V140,
)
from app.source_analysis_thinking_contract.constants import (
    SELECTED_CONTRACT,
    SELECTED_THINKING_MODE,
)
from app.source_analysis_v31_global_preflight.constants import (
    ALLOWED_DROP_REASONS,
    ALLOWED_IDEA_OPERATIONS,
    FORBIDDEN_DROP_REASONS,
    FROZEN_GRANULARITY,
    FROZEN_PLANNER,
    FROZEN_PROMPT,
    FROZEN_SRC_POLICY,
    FROZEN_TRANSPORT,
    GLOBAL_PROMPT_VERSION,
    GLOBAL_TRANSPORT_VERSION,
    IDEA_DISPOSITION_COVERAGE_REQUIRED,
    IDEA_KIND_POLICY,
    MODEL as A34_MODEL,
    PRODUCTION_PLANNER_VERSION,
    PROPOSED_ARCHITECTURE,
    PROPOSED_MAX_OUTPUT,
    PROPOSED_RELATION_POLICY,
    PROPOSED_THINKING_POLICY,
    PROVIDER as A34_PROVIDER,
    RELATION_POLICY_OPTION,
    RELATION_QUALITY_TECHNICAL_DEBT,
    TRANSPORT_SCHEMA_ARTIFACT as A34_TRANSPORT_SCHEMA_ARTIFACT,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.35"
MODE = "GLOBAL_CONSOLIDATION_TINY_SYNTHETIC_GRAMMAR_CANARY"

AUTHORIZATION_SCOPE = "GLOBAL_CONSOLIDATION_TINY_SYNTHETIC_GRAMMAR_CANARY_ONLY"

PROVIDER = A34_PROVIDER
MODEL = A34_MODEL
THINKING_CONTRACT = SELECTED_CONTRACT
THINKING_MODE = SELECTED_THINKING_MODE
EFFORT = None

assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert THINKING_MODE == "disabled"
assert GLOBAL_PROMPT_VERSION == "global-consolidation-1.0"
assert GLOBAL_TRANSPORT_VERSION == "global-consolidation-transport-1.0"
assert FROZEN_PLANNER == CANDIDATE_PLANNER_VERSION == "window-planner-v2.1-small"
assert FROZEN_PROMPT == WINDOW_ANALYSIS_PROMPT_VERSION_V140 == "window-analysis-1.4.0"
assert FROZEN_TRANSPORT == SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE
assert FROZEN_GRANULARITY == GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC
assert FROZEN_SRC_POLICY == SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION
assert PROPOSED_MAX_OUTPUT == MAX_OUTPUT_TOKENS_FROZEN == 32000
assert IDEA_KIND_POLICY == "KEEP_EMPTY_GLOBALLY"

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False

# Tiny canary only. Production A.34 max_output remains 32000.
CANARY_MAX_OUTPUT_TOKENS = 2048
PRODUCTION_MAX_OUTPUT_TOKENS = PROPOSED_MAX_OUTPUT

CANARY_CONNECT_TIMEOUT_SECONDS = 30.0
CANARY_READ_TIMEOUT_SECONDS = 120.0

A34_SCHEMA_RAW_BYTES = 1040
A34_SCHEMA_ADAPTED_BYTES = 1195
A34_SCHEMA_HASH = (
    "7a8ce905aee4d335ffe1691d4d9bde38dfae9fe85d068091978ab9f766161633"
)
assert A34_SCHEMA_HASH.startswith("7a8ce905")
assert A34_SCHEMA_HASH.endswith("61633")

PRODUCTION_NORMALIZED_CHARS = 141682
PRODUCTION_LOCAL_ESTIMATE_TOKENS = 36531
PRODUCTION_PROVIDER_ADJUSTED_TOKENS = 65755
PRODUCTION_WORST_CASE_OUTPUT_TOKENS = 24346
PRODUCTION_ESTIMATED_COST_USD = "0.374970 USD"
PRODUCTION_OUTPUT_HEADROOM_TOKENS = (
    PRODUCTION_MAX_OUTPUT_TOKENS - PRODUCTION_WORST_CASE_OUTPUT_TOKENS
)

CANARY_VERSION = "global-consolidation-tiny-grammar-canary-1.0"
STAGE_CANARY = "source_analysis_v31_global_grammar_canary"
CANARY_SUBDIR = "canary/global_consolidation_transport_v1"
CANARY_WINDOW_ID = "SYN_GLOBAL"
CANARY_TRANSCRIPT_ID = "TR_CANARY_GARDEN"
LOCK_NAME = "canary_real_call.lock"

# High-range SRC ids: canonical ^SRC[0-9]{6}$ but not production SRC0xxxxx.
SYNTHETIC_SRC_IDS = (
    "SRC998001",
    "SRC998002",
    "SRC998003",
    "SRC998004",
    "SRC998005",
    "SRC998006",
    "SRC998007",
    "SRC998008",
    "SRC998009",
    "SRC998010",
)
SYNTHETIC_WINDOW_IDS = ("SYN001", "SYN002")
SYNTHETIC_NAMESPACE = "SYN"

FORBIDDEN_WINDOW_IDS = (
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
)
FORBIDDEN_TRANSCRIPT_IDS = ("TR001",)
PRODUCTION_SRC_PATTERN = r"^SRC0\d{5}$"
PASTORAL_MARKERS = (
    "pastoral_retreat",
    "pastoral retreat",
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
    "SRC000001",
    "TR001",
    "SRec007337",
    "SRC007337",
)

NORMAL_FINISH_REASONS = frozenset({"end_turn", "stop", "end_turn"})
HANDLE_PREFIX_BY_KIND = {
    "TOPIC": "T",
    "IDEA": "I",
    "EXAMPLE": "E",
    "REFERENCE": "F",
    "UNCERTAINTY": "U",
    "REPETITION": "P",
}
NODE_KINDS = tuple(HANDLE_PREFIX_BY_KIND)

FIXTURE_ARTIFACT = "global_consolidation_synthetic_fixture.json"
REQUEST_ARTIFACT = "global_consolidation_canary_request_metadata.json"
CONTRACT_ARTIFACT = "global_consolidation_canary_contract_validation.json"
DISPOSITION_ARTIFACT = "global_consolidation_canary_disposition_audit.json"
CANONICAL_ARTIFACT = "global_consolidation_canary_canonical_reconstruction.json"
USAGE_ARTIFACT = "global_consolidation_canary_usage_cost.json"
READINESS_ARTIFACT = "global_consolidation_real_call_readiness.json"
EXECUTION_ARTIFACT = "global_consolidation_canary_execution.json"
REPORT_NAME = "PHASE_3B77A35_GLOBAL_CONSOLIDATION_TINY_GRAMMAR_CANARY_REPORT.md"
BASELINE_ARTIFACT = "source_analysis_a35_test_baseline.json"
POST_TEST_ARTIFACT = "source_analysis_a35_test_delta.json"

A34_REPORT_NAME = "PHASE_3B77A34_GLOBAL_CONSOLIDATION_OFFLINE_PREFLIGHT_REPORT.md"
A34_SCHEMA_ARTIFACT = A34_TRANSPORT_SCHEMA_ARTIFACT

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_grammar_canary.py",
    "app/tests/test_source_analysis_v31_global_grammar_canary_audit.py",
    "app/tests/test_source_analysis_v31_global_preflight.py",
    "app/tests/test_source_analysis_v31_global_preflight_audit.py",
)

DRY_RUN_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v31_global_grammar_canary "
    "pastoral_retreat_v2_validation "
    "--authorization-scope GLOBAL_CONSOLIDATION_TINY_SYNTHETIC_GRAMMAR_CANARY_ONLY "
    "--dry-run"
)
REAL_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v31_global_grammar_canary "
    "pastoral_retreat_v2_validation "
    "--authorization-scope GLOBAL_CONSOLIDATION_TINY_SYNTHETIC_GRAMMAR_CANARY_ONLY "
    "--execute-real"
)

PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
NEXT_ACTION = "HUMAN REVIEW"
NEXT_PHASE = "HUMAN_REVIEW_THEN_REAL_GLOBAL_CONSOLIDATION_CANARY_IF_AUTHORIZED"
LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN = "YES"

__all__ = [
    "A34_MODEL",
    "A34_PROVIDER",
    "A34_REPORT_NAME",
    "A34_SCHEMA_ADAPTED_BYTES",
    "A34_SCHEMA_ARTIFACT",
    "A34_SCHEMA_HASH",
    "A34_SCHEMA_RAW_BYTES",
    "ALLOWED_DROP_REASONS",
    "ALLOWED_IDEA_OPERATIONS",
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "BASELINE_ARTIFACT",
    "CANARY_CONNECT_TIMEOUT_SECONDS",
    "CANARY_MAX_OUTPUT_TOKENS",
    "CANARY_READ_TIMEOUT_SECONDS",
    "CANARY_SUBDIR",
    "CANARY_TRANSCRIPT_ID",
    "CANARY_VERSION",
    "CANARY_WINDOW_ID",
    "CANONICAL_ARTIFACT",
    "CONTRACT_ARTIFACT",
    "DISPOSITION_ARTIFACT",
    "DRY_RUN_COMMAND",
    "EFFORT",
    "EXECUTION_ARTIFACT",
    "FIXTURE_ARTIFACT",
    "FOCUSED_TEST_PATHS",
    "FORBIDDEN_DROP_REASONS",
    "FORBIDDEN_TRANSCRIPT_IDS",
    "FORBIDDEN_WINDOW_IDS",
    "FROZEN_GRANULARITY",
    "FROZEN_PLANNER",
    "FROZEN_PROMPT",
    "FROZEN_SRC_POLICY",
    "FROZEN_TRANSPORT",
    "GLOBAL_PROMPT_VERSION",
    "GLOBAL_TRANSPORT_VERSION",
    "HANDLE_PREFIX_BY_KIND",
    "IDEA_DISPOSITION_COVERAGE_REQUIRED",
    "IDEA_KIND_POLICY",
    "LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN",
    "LOCK_NAME",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NODE_KINDS",
    "NORMAL_FINISH_REASONS",
    "PASTORAL_MARKERS",
    "PHASE",
    "PHASE_3B_STATUS",
    "POST_TEST_ARTIFACT",
    "PRODUCTION_ESTIMATED_COST_USD",
    "PRODUCTION_LOCAL_ESTIMATE_TOKENS",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PRODUCTION_NORMALIZED_CHARS",
    "PRODUCTION_OUTPUT_HEADROOM_TOKENS",
    "PRODUCTION_PLANNER_VERSION",
    "PRODUCTION_PROVIDER_ADJUSTED_TOKENS",
    "PRODUCTION_SRC_PATTERN",
    "PRODUCTION_WORST_CASE_OUTPUT_TOKENS",
    "PROJECT_NAME",
    "PROPOSED_ARCHITECTURE",
    "PROPOSED_RELATION_POLICY",
    "PROPOSED_THINKING_POLICY",
    "PROVIDER",
    "READINESS_ARTIFACT",
    "REAL_COMMAND",
    "RELATION_POLICY_OPTION",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPORT_NAME",
    "REQUEST_ARTIFACT",
    "SCHEMA_VERSION",
    "SOURCE_MAP_STATUS",
    "STAGE_CANARY",
    "SYNTHETIC_NAMESPACE",
    "SYNTHETIC_SRC_IDS",
    "SYNTHETIC_WINDOW_IDS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "USAGE_ARTIFACT",
]
