"""Rapport markdown 3B.7.7A.35."""

from __future__ import annotations

from typing import Any, Mapping

from app.source_analysis_v31_global_grammar_canary.constants import (
    CANARY_MAX_OUTPUT_TOKENS,
    GLOBAL_PROMPT_VERSION,
    GLOBAL_TRANSPORT_VERSION,
    LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
    MODEL,
    PRODUCTION_ESTIMATED_COST_USD,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PRODUCTION_OUTPUT_HEADROOM_TOKENS,
    PRODUCTION_PROVIDER_ADJUSTED_TOKENS,
    PRODUCTION_WORST_CASE_OUTPUT_TOKENS,
    RELATION_QUALITY_TECHNICAL_DEBT,
)
from app.source_analysis_v31_global_grammar_canary.runner import CanaryRunResult


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    return str(value)


def render_report(
    result: CanaryRunResult,
    *,
    tests: str,
    extra_header: Mapping[str, Any] | None = None,
) -> str:
    exe = result.execution or {}
    dry = result.dry_run or {}
    extra = dict(extra_header or {})
    verdict = exe.get("result") or extra.get("result") or result.mode
    schema_raw = exe.get("schema_raw_bytes") or dry.get("schema_raw_bytes")
    schema_adapted = exe.get("schema_adapted_bytes") or dry.get("schema_adapted_bytes")
    schema_hash = exe.get("schema_hash") or dry.get("schema_hash")
    headroom = PRODUCTION_OUTPUT_HEADROOM_TOKENS
    if PRODUCTION_WORST_CASE_OUTPUT_TOKENS > 24000:
        headroom_label = f"{headroom} tokens (MARGINAL vs 32000)"
    else:
        headroom_label = f"{headroom} tokens"
    cost = (exe.get("cost") or {}).get("display") or (exe.get("cost") or {}).get("total_cost")
    lines = [
        "# PHASE 3B.7.7A.35 — GLOBAL CONSOLIDATION TINY GRAMMAR CANARY",
        "",
        "## Result",
        "",
        str(verdict),
        "",
        "AUTHORIZED PROVIDER CALLS =",
        "1",
        "",
        "ACTUAL PROVIDER CALLS =",
        str(exe.get("actual_calls") if exe else result.anthropic_post_attempts),
        "",
        "SUCCESSFUL PROVIDER CALLS =",
        str(exe.get("successful_calls") if exe else 0),
        "",
        "RETRIES =",
        "0",
        "",
        "REAL PASTORAL DATA SENT =",
        "NO",
        "",
        "REAL CONSOLIDATION EXECUTED =",
        "NO",
        "",
        "MODEL =",
        MODEL,
        "",
        "PROMPT =",
        GLOBAL_PROMPT_VERSION,
        "",
        "TRANSPORT =",
        GLOBAL_TRANSPORT_VERSION,
        "",
        "SCHEMA RAW / ADAPTED =",
        f"{_dash(schema_raw)} / {_dash(schema_adapted)}",
        "",
        "SCHEMA HASH =",
        _dash(schema_hash),
        "",
        "SCHEMA IDENTITY VS A.34 =",
        _dash(exe.get("schema_identity") or dry.get("schema_identity")),
        "",
        "THINKING =",
        "disabled",
        "",
        "ACTUAL THINKING TOKENS =",
        _dash(exe.get("thinking_tokens")),
        "",
        "MAX OUTPUT CANARY =",
        str(exe.get("max_output_canary") or CANARY_MAX_OUTPUT_TOKENS),
        "",
        "LOCAL INPUT ESTIMATE =",
        _dash(exe.get("local_input_estimate") or dry.get("local_input_estimate_tokens")),
        "",
        "PROVIDER INPUT =",
        _dash(exe.get("provider_input") or exe.get("input_tokens")),
        "",
        "OUTPUT TOKENS =",
        _dash(exe.get("output_tokens")),
        "",
        "FINISH REASON =",
        _dash(exe.get("finish_reason")),
        "",
        "HTTP =",
        _dash(exe.get("http_status")),
        "",
        "REQUEST ID =",
        _dash(exe.get("request_id")),
        "",
        "PROVIDER ELAPSED =",
        _dash(exe.get("provider_elapsed_ms")),
        "",
        "ACTUAL COST =",
        _dash(cost),
        "",
        "STRUCTURED PARSE =",
        _dash(exe.get("structured_parse")),
        "",
        "TRANSPORT DECODER =",
        _dash(exe.get("transport_decoder")),
        "",
        "HANDLE VALIDATION =",
        _dash(exe.get("handle_validation")),
        "",
        "IDEA DISPOSITION COVERAGE =",
        _dash(exe.get("idea_disposition_coverage")),
        "",
        "SILENT DROPS =",
        _dash(exe.get("silent_drops")),
        "",
        "TRACEABILITY =",
        _dash(exe.get("traceability")),
        "",
        "GLOBAL VALIDATOR =",
        _dash(exe.get("global_validator")),
        "",
        "CANONICAL RECONSTRUCTION =",
        _dash(exe.get("canonical_reconstruction")),
        "",
        "CANONICAL VALIDATION =",
        _dash(exe.get("canonical_validation")),
        "",
        "DETERMINISTIC REPLAY =",
        _dash(exe.get("deterministic_replay")),
        "",
        "SEMANTIC FIXTURE REVIEW =",
        _dash(exe.get("semantic_fixture_review")),
        "",
        "LOCAL EXTRACTION FUNCTIONALLY FROZEN =",
        LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        RELATION_QUALITY_TECHNICAL_DEBT,
        "",
        "PRODUCTION INPUT ESTIMATE =",
        f"~{PRODUCTION_PROVIDER_ADJUSTED_TOKENS} provider-adjusted tokens",
        "",
        "PRODUCTION MAX OUTPUT =",
        str(PRODUCTION_MAX_OUTPUT_TOKENS),
        "",
        "OUTPUT HEADROOM =",
        headroom_label,
        "",
        "ESTIMATED REAL CONSOLIDATION COST =",
        PRODUCTION_ESTIMATED_COST_USD,
        "",
        "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY =",
        _dash(exe.get("ready_for_real_global_consolidation_canary") or "NO"),
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## Notes",
        "",
        f"Tests = {tests}",
        "",
        f"Authorization scope = {result.authorization_scope}",
        "",
        f"Error = {_dash(result.error)}",
        "",
        "A successful tiny canary proves grammar/transport/provider compatibility.",
        "It does NOT prove the real 623-record consolidation will be semantically good.",
        "",
        "Do not automatically run the real global consolidation canary.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
