"""
Phase 4B.2.9 — Semantic Gate 2.0 offline implementation candidate.

STRICTLY OFFLINE. Isolated from production. Zero provider calls.
Historical canaries are not relaunched. Frozen 1.0 / 1.1 / 1.1.1 / 1.1.2 /
1.1.3-candidate and the 2.0-proposal are not modified.
2.0-candidate is not activated in the production pipeline.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
    VERDICT_FAIL,
    VERDICT_PASS,
    VERDICT_REVIEW,
)
from app.book_semantic_gate_4b23.reasons import REASON_CODES, REASON_DEFINITIONS
from app.book_semantic_gate_4b24.constants import (
    CONNECTIVE_CASE_ID,
    FUNERAL_CASE_ID,
    NEGATIVE_CASE_IDS,
    P3_CASE_ID,
    P8_CASE_ID,
    POSITIVE_CASE_IDS,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE
from app.book_semantic_gate_4b261.constants import CANDIDATE_PROMPT_VERSION
from app.book_semantic_gate_4b271.constants import (
    DISPUTED_CLAUSE as H01_DISPUTED_CLAUSE,
    TRANSPORT_VERSION_11,
)
from app.book_semantic_gate_4b272.constants import DISPUTED_CAUSAL_CLAUSE
from app.book_semantic_gate_4b274.constants import (
    H01_GAPS,
    H02_GAPS,
    OVERFIT_TOKENS as OVERFIT_TOKENS_112,
    PROMPT_VERSION_112,
)
from app.book_semantic_gate_4b275.constants import (
    EXPECTED_PROMPT_113_SHA256,
    OVERFIT_TOKENS as OVERFIT_TOKENS_113,
    PROMPT_VERSION_113,
)
from app.book_semantic_gate_4b276.constants import DISPUTED_CLAUSE as H11_DISPUTED_CLAUSE
from app.book_semantic_gate_4b28.constants import (
    H01_CASE_HANDLE,
    H01_CASE_ID,
    H01_EVIDENCE_HANDLES,
    H01_HUMAN_LABEL,
    H01_REQUEST_SHA256,
    H02_CASE_HANDLE,
    H02_CASE_ID,
    H02_EVIDENCE_HANDLES,
    H02_HUMAN_LABEL,
    H02_REQUEST_SHA256,
    H11_CASE_HANDLE,
    H11_CASE_ID,
    H11_EVIDENCE_HANDLES,
    H11_GAPS,
    H11_HUMAN_LABEL,
    H11_REQUEST_SHA256,
    HISTORICAL_4B261_STATUS,
    HISTORICAL_4B262_STATUS,
    HISTORICAL_4B26_STATUS,
    HISTORICAL_4B271_STATUS,
    HISTORICAL_4B272_STATUS,
    HISTORICAL_4B273_STATUS,
    HISTORICAL_4B274_STATUS,
    HISTORICAL_4B275_STATUS,
    HISTORICAL_4B276_STATUS,
    HISTORICAL_4B277_STATUS,
    HISTORICAL_4B27_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
    PROMPT_VERSION_11,
    PROMPT_VERSION_20_PROPOSAL,
    TARGET_ARCHITECTURE,
    TRANSPORT_VERSION_20_PROPOSAL,
)

PHASE = "4B.2.9"
PHASE_NAME = "SEMANTIC_GATE_20_OFFLINE_IMPLEMENTATION_AND_INTEGRATION_PREFLIGHT"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B29_SEMANTIC_GATE_20_OFFLINE_IMPLEMENTATION_"
    "AND_INTEGRATION_PREFLIGHT_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SDK_MAX_RETRIES = 0
RETRIES = 0
FALLBACKS = 0

SEMANTIC_GATE_20_ENABLED = False
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False

PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
PROMPT_VERSION_20_CANDIDATE = "book-semantic-validator-2.0-candidate"
TRANSPORT_VERSION_20_CANDIDATE = "book-semantic-validation-transport-2.0-candidate"
PROMPT_VERSION_20_ACTIVATED = False
TRANSPORT_VERSION_20_ACTIVATED = False

OFFSET_CONVENTION = "python3_str_unicode_code_points_half_open"
OFFSET_CONVENTION_NOTES = {
    "python3_str": (
        "Offsets are Python 3 str indices: Unicode code points, half-open "
        "[start, end). paragraph[start:end] == unit text."
    ),
    "utf8_bytes": (
        "UTF-8 byte offsets are not used. 'é' is 1 Python index and 2 UTF-8 "
        "bytes; mixing them would shift every later unit."
    ),
    "utf16_code_units": (
        "UTF-16 code-unit offsets are not used. Supplementary-plane characters "
        "such as '😀' are 1 Python index and 2 UTF-16 code units."
    ),
    "must_not_mix": True,
}

DECISION_PASS = "PASS"
DECISION_BLOCK = "BLOCK"
DECISION_REVIEW = "REVIEW"
ACCEPTANCE_DECISIONS = (DECISION_PASS, DECISION_BLOCK, DECISION_REVIEW)

MODEL_VERDICT_PASS = VERDICT_PASS
MODEL_VERDICT_REVIEW = VERDICT_REVIEW
MODEL_VERDICT_FAIL = VERDICT_FAIL
MODEL_VERDICTS = (MODEL_VERDICT_PASS, MODEL_VERDICT_REVIEW, MODEL_VERDICT_FAIL)

FAKEAI_SOURCE = "FAKEAI_SIMULATED"
RECORDED_SOURCE = "RECORDED_SIMULATED"
NOT_TERRA = True

HISTORICAL_4B28_STATUS = "PASS"

OVERFIT_TOKENS = tuple(dict.fromkeys(OVERFIT_TOKENS_112 + OVERFIT_TOKENS_113))

assert PROMPT_VERSION_HISTORICAL == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION_HISTORICAL == "book-semantic-validation-transport-1.0"
assert PROMPT_VERSION_11 == "book-semantic-validator-1.1-candidate"
assert TRANSPORT_VERSION_11 == "book-semantic-validation-transport-1.1-candidate"
assert PROMPT_VERSION_112 == "book-semantic-validator-1.1.2-candidate"
assert PROMPT_VERSION_113 == "book-semantic-validator-1.1.3-candidate"
assert PROMPT_VERSION_20_PROPOSAL == "book-semantic-validator-2.0-proposal"
assert TRANSPORT_VERSION_20_PROPOSAL == "book-semantic-validation-transport-2.0-proposal"
assert PROMPT_VERSION_20_CANDIDATE != PROMPT_VERSION_113
assert PROMPT_VERSION_20_CANDIDATE != PROMPT_VERSION_20_PROPOSAL
assert TRANSPORT_VERSION_20_CANDIDATE != TRANSPORT_VERSION_11
assert TRANSPORT_VERSION_20_CANDIDATE != TRANSPORT_VERSION_20_PROPOSAL
assert PROMPT_VERSION_20_ACTIVATED is False
assert TRANSPORT_VERSION_20_ACTIVATED is False
assert SEMANTIC_GATE_20_ENABLED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert H01_REQUEST_SHA256 == (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
assert H02_REQUEST_SHA256 == (
    "5ace261296d808437910f8f9efe247a80daebbb2237bc8af46bda56bf98d7897"
)
assert H11_REQUEST_SHA256 == (
    "b3cc1574858acdd5bdd0e223aa136d5058c4eb1deb1495cd9ad312d332e8c30f"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert EXPECTED_PROMPT_113_SHA256 == (
    "9febdcdda08a31179081564ac33842b434dcc8bcb95ca9d96f386b63addb3059"
)
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert HISTORICAL_4B262_STATUS == "PASS"
assert HISTORICAL_4B27_STATUS == "PARTIAL"
assert HISTORICAL_4B271_STATUS == "PASS"
assert HISTORICAL_4B272_STATUS == "PASS"
assert HISTORICAL_4B273_STATUS == "PARTIAL"
assert HISTORICAL_4B274_STATUS == "PASS"
assert HISTORICAL_4B275_STATUS == "PASS"
assert HISTORICAL_4B276_STATUS == "PASS"
assert HISTORICAL_4B277_STATUS == "PARTIAL"
assert HISTORICAL_4B28_STATUS == "PASS"
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_H11_STATUS == "PARTIAL"
assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False
assert CANONICAL_PYTHON_EXECUTABLE.endswith("python.exe")
assert H01_DISPUTED_CLAUSE == "that fear can calculate or bargain with"
assert DISPUTED_CAUSAL_CLAUSE == (
    "because it still works wherever it is not resisted by truth"
)
assert H11_DISPUTED_CLAUSE == (
    "which means that every believer is guaranteed a fearless death"
)
assert TARGET_ARCHITECTURE == "C_HYBRID_TWO_LEVEL_WITH_CONSERVATIVE_PRESEGMENTATION"
assert len(REASON_CODES) == 16
assert CLASSIFICATIONS == (
    CLASS_SUPPORTED,
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    CLASS_NON_SUBSTANTIVE,
)
assert H11_CASE_HANDLE not in {opaque for opaque, _ in SCORED_CASE_ORDER}

AUDIT_DIRNAME = "book_semantic_gate_4b29"
AUDIT_INVENTORY = "technical_inventory.json"
AUDIT_ARCHITECTURE = "architecture_implementation.json"
AUDIT_PREPARATION = "deterministic_preparation.json"
AUDIT_COVERAGE = "coverage_validation.json"
AUDIT_CONTRACT = "semantic_contract_20.json"
AUDIT_TRANSPORT = "semantic_transport_20.json"
AUDIT_VALIDATOR = "deterministic_response_validator.json"
AUDIT_POLICY = "acceptance_policy.json"
AUDIT_FAKEAI = "fakeai_scenarios.json"
AUDIT_H01 = "historical_replay_h01.json"
AUDIT_H02 = "historical_replay_h02.json"
AUDIT_H11 = "historical_replay_h11.json"
AUDIT_BENCHMARK = "benchmark_compatibility.json"
AUDIT_INTEGRATION = "integration_preflight.json"
AUDIT_SAFETY = "provider_safety.json"
AUDIT_TESTS = "offline_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b29_index.json"
REPORT_NAME = "PHASE_4B29_SEMANTIC_GATE_20_OFFLINE_IMPLEMENTATION_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_SEMANTIC_GATE_20_HUMAN_REVIEW = True
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "ACCEPTANCE_DECISIONS",
    "AUDIT_ARCHITECTURE",
    "AUDIT_BENCHMARK",
    "AUDIT_CONTRACT",
    "AUDIT_COVERAGE",
    "AUDIT_DIRNAME",
    "AUDIT_FAKEAI",
    "AUDIT_H01",
    "AUDIT_H02",
    "AUDIT_H11",
    "AUDIT_INDEX",
    "AUDIT_INTEGRATION",
    "AUDIT_INVENTORY",
    "AUDIT_POLICY",
    "AUDIT_PREPARATION",
    "AUDIT_READINESS",
    "AUDIT_SAFETY",
    "AUDIT_TESTS",
    "AUDIT_TRANSPORT",
    "AUDIT_VALIDATOR",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_SONNET_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CONNECTIVE_CASE_ID",
    "DECISION_BLOCK",
    "DECISION_PASS",
    "DECISION_REVIEW",
    "DISPUTED_CAUSAL_CLAUSE",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_PROMPT_113_SHA256",
    "EXPECTED_SOURCE_MAP",
    "FAKEAI_SOURCE",
    "FALLBACKS",
    "FUNERAL_CASE_ID",
    "H01_CASE_HANDLE",
    "H01_CASE_ID",
    "H01_DISPUTED_CLAUSE",
    "H01_EVIDENCE_HANDLES",
    "H01_GAPS",
    "H01_HUMAN_LABEL",
    "H01_REQUEST_SHA256",
    "H02_CASE_HANDLE",
    "H02_CASE_ID",
    "H02_EVIDENCE_HANDLES",
    "H02_GAPS",
    "H02_HUMAN_LABEL",
    "H02_REQUEST_SHA256",
    "H11_CASE_HANDLE",
    "H11_CASE_ID",
    "H11_DISPUTED_CLAUSE",
    "H11_EVIDENCE_HANDLES",
    "H11_GAPS",
    "H11_HUMAN_LABEL",
    "H11_REQUEST_SHA256",
    "HISTORICAL_4B261_STATUS",
    "HISTORICAL_4B262_STATUS",
    "HISTORICAL_4B26_STATUS",
    "HISTORICAL_4B271_STATUS",
    "HISTORICAL_4B272_STATUS",
    "HISTORICAL_4B273_STATUS",
    "HISTORICAL_4B274_STATUS",
    "HISTORICAL_4B275_STATUS",
    "HISTORICAL_4B276_STATUS",
    "HISTORICAL_4B277_STATUS",
    "HISTORICAL_4B27_STATUS",
    "HISTORICAL_4B28_STATUS",
    "HISTORICAL_H01_STATUS",
    "HISTORICAL_H02_STATUS",
    "HISTORICAL_H11_STATUS",
    "MODEL_VERDICTS",
    "MODEL_VERDICT_FAIL",
    "MODEL_VERDICT_PASS",
    "MODEL_VERDICT_REVIEW",
    "NEGATIVE_CASE_IDS",
    "NEXT_ACTION",
    "NOT_TERRA",
    "OFFSET_CONVENTION",
    "OFFSET_CONVENTION_NOTES",
    "OVERFIT_TOKENS",
    "P3_CASE_ID",
    "P8_CASE_ID",
    "PHASE",
    "PHASE_NAME",
    "POSITIVE_CASE_IDS",
    "PRODUCTION_CACHE_ACCEPTANCE",
    "PRODUCTION_PIPELINE_HOOK",
    "PROJECT_NAME",
    "PROMPT_VERSION_11",
    "PROMPT_VERSION_112",
    "PROMPT_VERSION_113",
    "PROMPT_VERSION_20_ACTIVATED",
    "PROMPT_VERSION_20_CANDIDATE",
    "PROMPT_VERSION_20_PROPOSAL",
    "PROMPT_VERSION_HISTORICAL",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "READY_FOR_NEW_REMOTE_TERRA_CALL",
    "READY_FOR_SEMANTIC_GATE_20_HUMAN_REVIEW",
    "REASON_CODES",
    "REASON_DEFINITIONS",
    "RECORDED_SOURCE",
    "REPORT_NAME",
    "RETRIES",
    "SCORED_CASE_ORDER",
    "SDK_MAX_RETRIES",
    "SEMANTIC_GATE_20_ENABLED",
    "TARGET_ARCHITECTURE",
    "TERRA_EXECUTION_AUTHORIZED",
    "TRANSPORT_VERSION_11",
    "TRANSPORT_VERSION_20_ACTIVATED",
    "TRANSPORT_VERSION_20_CANDIDATE",
    "TRANSPORT_VERSION_20_PROPOSAL",
    "TRANSPORT_VERSION_HISTORICAL",
]
