"""
Phase 4B.2.27 — remaining 13 real chapter generation.

NEW explicit one-shot authorization. Thirteen Anthropic
claude-sonnet-5 calls maximum, one per remaining chapter,
zero retries, zero fallbacks. Does not regenerate the six
accepted chapters. Does not publish book.json. Does not write
the production cache. Does not call Terra or OpenAI. Does not
reuse historical remaining budgets from 4B.2.17–4B.2.26.
"""

from __future__ import annotations

from decimal import Decimal

from app.ai.thinking import THINKING_MODE_DISABLED
from app.book_authorial_voice_4b218.constants import (
    AUTHORIAL_VOICE_POLICY_VERSION,
    FAITHFUL_PROMPT_1_0_VERSION,
    FAITHFUL_PROMPT_1_1_VERSION,
    HISTORICAL_PROMPT_V10,
    HISTORICAL_PROMPT_V101,
)
from app.book_authorial_voice_4b218.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B218_SCOPE,
)
from app.book_batch_preparation_4b222.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B222_SCOPE,
)
from app.book_ch002_offline_recovery_4b224.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B224_SCOPE,
)
from app.book_editorial_acceptance_4b219.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B219_SCOPE,
)
from app.book_editorial_alignment_4b216.constants import (
    COVERAGE_CONTRACT_VERSION,
    EDITORIAL_POLICY_VERSION,
    HISTORICAL_SEMANTIC_CONTRACT,
)
from app.book_full_generation_preparation_4b226.constants import (
    ACCEPTED_CHAPTER_IDS,
    AUTHORIZATION_SCOPE as CONSUMED_4B226_SCOPE,
    EXPECTED_CH003_JSON_SHA256,
    EXPECTED_CH003_MD_SHA256,
    EXPECTED_CH004_JSON_SHA256,
    EXPECTED_CH004_MD_SHA256,
    FUTURE_AUTHORIZATION_SCOPE,
    NORMALIZER_VERSION,
    REMAINING_CHAPTER_COUNT,
    REMAINING_CHAPTER_IDS,
    TOTAL_CHAPTER_COUNT,
)
from app.book_generation.constants import (
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION_V10,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    HARD_MAX_OUTPUT_TOKENS,
    MIN_MAX_OUTPUT_TOKENS,
    MODEL,
    PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_generation_4b217.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B217_SCOPE,
    SONNET_INPUT_COST_PER_1M,
    SONNET_OUTPUT_COST_PER_1M,
)
from app.book_generation_4b221.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B221_SCOPE,
)
from app.book_generation_4b223.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B223_SCOPE,
    EXPECTED_CH018_JSON_SHA256,
    EXPECTED_CH018_MD_SHA256,
)
from app.book_generation_4b225.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B225_SCOPE,
    EXPECTED_CH001_JSON_SHA256,
    EXPECTED_CH001_MD_SHA256,
    EXPECTED_CH002_ORIGINAL_JSON_SHA256,
    EXPECTED_CH002_ORIGINAL_MD_SHA256,
    EXPECTED_CH002_RECOVERED_JSON_SHA256,
    EXPECTED_CH002_RECOVERED_MD_SHA256,
)
from app.book_scale_up_preparation_4b220.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B220_SCOPE,
    EXPECTED_PROMPT_1_1_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_1_1_SHA256,
    EXPECTED_PROMPT_1_1_SYSTEM_SHA256,
    FAITHFUL_PROMPT_1_1,
)
from app.book_semantic_gate_4b23.constants import EXPECTED_CLEAN_TRANSCRIPT
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE

PHASE = "4B.2.27"
PHASE_NAME = "REMAINING13_REAL_GENERATION"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = FUTURE_AUTHORIZATION_SCOPE
assert AUTHORIZATION_SCOPE == "BOOK_GENERATION_REMAINING_13_CHAPTERS_ONE_SHOT"

AUTHORIZED_ANTHROPIC_CALLS = 13
AUTHORIZED_SONNET_CALLS = 13
AUTHORIZED_REMOTE_INVOCATIONS = 13
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_TERRA_CALLS = 0
MAX_ENGINE_GENERATE = 13
MAX_ANTHROPIC_POST = 13
MAX_HTTP_REQUESTS = 13
MAX_EXECUTION_ATTEMPTS = 1
MAX_CALLS_PER_CHAPTER = 1
RETRIES = 0
FALLBACKS = 0
SDK_MAX_RETRIES = 0

PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
OPENAI_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = True
REAL_CHAPTER_GENERATION_AUTHORIZED = True
REAL_PROVIDERS_ENABLED = True
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
FAITHFUL_PROMPT_ACTIVATED_IN_PRODUCTION = False
FAITHFUL_PROMPT_1_1_ACTIVATED = False
EDITORIAL_POLICY_ACTIVATED_IN_PRODUCTION = False
COVERAGE_CONTROL_ACTIVATED_IN_PRODUCTION = False
SEMANTIC_GATE_202_ENABLED = False
SEMANTIC_CERTIFICATION_PERFORMED = False
BOOK_JSON_PUBLICATION = False
HISTORICAL_REMAINDER_IS_AUTHORIZATION = False

AUTHORIZED_CHAPTER_IDS = REMAINING_CHAPTER_IDS
FORBIDDEN_CHAPTER_IDS = ACCEPTED_CHAPTER_IDS
EXPECTED_REMAINING_SECTIONS = 47
EXPECTED_REMAINING_IDEAS = 204
assert len(AUTHORIZED_CHAPTER_IDS) == REMAINING_CHAPTER_COUNT == 13
assert len(FORBIDDEN_CHAPTER_IDS) == 6
assert len(FORBIDDEN_CHAPTER_IDS) + len(AUTHORIZED_CHAPTER_IDS) == TOTAL_CHAPTER_COUNT
assert TOTAL_CHAPTER_COUNT == 19

PROMPT_VERSION = FAITHFUL_PROMPT_1_1
TRANSPORT_VERSION = BOOK_GENERATION_TRANSPORT_VERSION
VALIDATOR_VERSION = BOOK_GENERATOR_VALIDATOR_VERSION
NARRATIVE_VOICE_CONTRACT = AUTHORIAL_VOICE_POLICY_VERSION
EDITORIAL_POLICY = EDITORIAL_POLICY_VERSION

assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert PROMPT_VERSION == "book-generator-faithful-restatement-1.1-candidate"
assert PROMPT_VERSION == FAITHFUL_PROMPT_1_1_VERSION
assert FAITHFUL_PROMPT_1_0_VERSION == "book-generator-faithful-restatement-1.0-candidate"
assert HISTORICAL_PROMPT_V101 == BOOK_GENERATOR_PROMPT_VERSION == "book-generator-1.0.1"
assert HISTORICAL_PROMPT_V10 == BOOK_GENERATOR_PROMPT_VERSION_V10 == "book-generator-1.0"
assert TRANSPORT_VERSION == "book-generation-transport-1.0"
assert EDITORIAL_POLICY_VERSION == "faithful-teaching-book-editorial-policy-1.0-candidate"
assert COVERAGE_CONTRACT_VERSION == "source-coverage-control-4b216-candidate"
assert HISTORICAL_SEMANTIC_CONTRACT == "book-semantic-validator-2.0.2-candidate"
assert NARRATIVE_VOICE_CONTRACT == "authorial-voice-preservation-1.0-candidate"
assert VALIDATOR_VERSION == "book-generation-validator-1.0.1"
assert CONSUMED_4B217_SCOPE == (
    "BOOK_GENERATION_4B217_CH012_FAITHFUL_REAL_PILOT_GENERATION_ONLY"
)
assert CONSUMED_4B218_SCOPE.startswith("BOOK_AUTHORIAL_VOICE_4B218_")
assert CONSUMED_4B219_SCOPE.startswith("BOOK_EDITORIAL_ACCEPTANCE_4B219_")
assert CONSUMED_4B220_SCOPE.startswith("BOOK_SCALE_UP_PREPARATION_4B220_")
assert CONSUMED_4B221_SCOPE == (
    "BOOK_GENERATION_LATER_PHASE_CH018_FIRST_REMAINING_CHAPTER_ONE_SHOT_ONLY"
)
assert CONSUMED_4B222_SCOPE.startswith("BOOK_BATCH_PREPARATION_4B222_")
assert CONSUMED_4B223_SCOPE == (
    "BOOK_GENERATION_BATCH_01_CH001_CH004_ONE_SHOT_PER_CHAPTER"
)
assert CONSUMED_4B224_SCOPE.startswith("BOOK_CH002_OFFLINE_RECOVERY_4B224_")
assert CONSUMED_4B225_SCOPE == (
    "BOOK_GENERATION_BATCH01_RESUME_CH003_CH004_ONE_SHOT_ONLY"
)
assert CONSUMED_4B226_SCOPE.startswith("BOOK_FULL_GENERATION_PREPARATION_4B226_")

THINKING_MODE = THINKING_MODE_DISABLED
assert THINKING_MODE == "disabled"

BUDGET_CAP_USD = Decimal("2.24")
BUDGET_CAP_DISPLAY = "2.24 USD"
PREPARATION_CENTRAL_USD = Decimal("0.790424")
PREPARATION_MAX_USD = Decimal("1.942914")
PREPARATION_RECOMMENDED_USD = Decimal("2.234351")
PRICING_EFFECTIVE_DATE = "2026-09-18"
PESSIMISTIC_CHARS_PER_TOKEN = Decimal("1.9365384615384615")
RECORDING_DATE = "2026-10-04"

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 1800.0

STAGE_CANARY = "book_generation_4b227_remaining13"
CANARY_WINDOW_ID = "CANARY_BG4B227"
LOCK_NAME = "call_lock.json"
BATCH_LOCK_NAME = "batch_lock.json"
CODE_VERSION = "app.book_generation_4b227"
LOCK_VERSION = "remaining-13-call-lock-4b227-1.0"

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_TRANSCRIPT = EXPECTED_CLEAN_TRANSCRIPT

assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert EXPECTED_PROMPT_1_1_SHA256 == (
    "e39084dc9ed3b048bfdaa2e112b380d15957085eeb613dd74c97a32b880cec50"
)
assert AUTHORIZED_ANTHROPIC_CALLS == 13
assert AUTHORIZED_OPENAI_CALLS == 0
assert AUTHORIZED_TERRA_CALLS == 0
assert MAX_CALLS_PER_CHAPTER == 1
assert RETRIES == 0
assert FALLBACKS == 0
assert PUBLICATION_AUTHORIZED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert FAITHFUL_PROMPT_1_1_ACTIVATED is False
assert HISTORICAL_REMAINDER_IS_AUTHORIZATION is False
assert BUDGET_CAP_USD == Decimal("2.24")
assert PREPARATION_MAX_USD <= BUDGET_CAP_USD
assert PREPARATION_RECOMMENDED_USD <= BUDGET_CAP_USD
assert MIN_MAX_OUTPUT_TOKENS == 4096
assert HARD_MAX_OUTPUT_TOKENS == 32000
assert CANONICAL_PYTHON.endswith("python.exe")
assert SONNET_INPUT_COST_PER_1M == Decimal("2.00")
assert SONNET_OUTPUT_COST_PER_1M == Decimal("10.00")
assert NORMALIZER_VERSION == "empty-unprovenanced-paragraph-normalizer-4b226-1.0"

PREP_AUDIT_DIRNAME = "book_full_generation_preparation_4b226"
PREP_INVENTORY_REL = f"audit/{PREP_AUDIT_DIRNAME}/remaining_chapters_inventory.json"
PREP_PLAN_REL = f"audit/{PREP_AUDIT_DIRNAME}/remaining_chapters_generation_plan.json"
PREP_COST_REL = f"audit/{PREP_AUDIT_DIRNAME}/remaining_chapters_budget_forecast.json"
PREP_AUTHORIZATION_REL = f"audit/{PREP_AUDIT_DIRNAME}/global_authorization_proposal.json"
PREP_READINESS_REL = f"audit/{PREP_AUDIT_DIRNAME}/readiness.json"

HUMAN_ACCEPTANCE_STATUS = "HUMAN_EDITORIALLY_ACCEPTED"
GENERATED_STATUS = "GENERATED_STRUCTURALLY_VALID"

LOCK_STATE_NOT_STARTED = "NOT_STARTED"
LOCK_STATE_PREFLIGHT = "PREFLIGHT_VALIDATED"
LOCK_STATE_RESERVED = "CALL_RESERVED"
LOCK_STATE_MAY_HAVE_BEEN_SENT = "CALL_MAY_HAVE_BEEN_SENT"
LOCK_STATE_RESPONSE_RECEIVED = "RESPONSE_RECEIVED"
LOCK_STATE_RESPONSE_VALIDATED = "RESPONSE_VALIDATED"
LOCK_STATE_FAILED = "FAILED"
LOCK_STATE_UNCERTAIN = "UNCERTAIN"

LOCK_CONSUMED_STATES = frozenset(
    {
        LOCK_STATE_RESERVED,
        LOCK_STATE_MAY_HAVE_BEEN_SENT,
        LOCK_STATE_RESPONSE_RECEIVED,
        LOCK_STATE_RESPONSE_VALIDATED,
        LOCK_STATE_FAILED,
        LOCK_STATE_UNCERTAIN,
    }
)
LOCK_RESUME_WITHOUT_RECALL = frozenset({LOCK_STATE_RESPONSE_VALIDATED})
LOCK_STOP_STATES = frozenset(
    {
        LOCK_STATE_RESERVED,
        LOCK_STATE_MAY_HAVE_BEEN_SENT,
        LOCK_STATE_RESPONSE_RECEIVED,
        LOCK_STATE_FAILED,
        LOCK_STATE_UNCERTAIN,
    }
)

FORBIDDEN_PROMPT_CLAUSES = (
    "High stylistic freedom",
    "Stylistic expansion is allowed",
)
FORBIDDEN_PROMPTS = (
    "book-generator-1.0",
    "book-generator-1.0.1",
    "book-generator-faithful-restatement-1.0-candidate",
)

AUDIT_DIRNAME = "book_generation_4b227_remaining13"
AUDIT_REAL_PARENT = "real"
AUDIT_CHAPTERS_DIR = "chapters"
AUDIT_PREFLIGHT = "preflight.json"
AUDIT_HASHES_PRE = "canonical_hashes_pre.json"
AUDIT_HASHES_POST = "canonical_hashes_post.json"
AUDIT_HASHES_PRE_POST = "canonical_hashes_pre_post.json"
AUDIT_AUTHORIZATION = "authorization.json"
AUDIT_ACCEPTED = "accepted_chapters_manifest.json"
AUDIT_LOCK = LOCK_NAME
AUDIT_BATCH_LOCK = BATCH_LOCK_NAME
AUDIT_PROMPT = "prompt_manifest.json"
AUDIT_CONTEXT = "source_context_manifest.json"
AUDIT_COST = "cost_preflight.json"
AUDIT_RESPONSE_RAW = "provider_response_raw.json"
AUDIT_USAGE = "provider_usage.json"
AUDIT_NORMALIZATION = "normalization_report.json"
AUDIT_CANDIDATE_JSON = "chapter_candidate.json"
AUDIT_CANDIDATE_MD = "chapter_candidate.md"
AUDIT_STRUCTURAL = "structural_validation.json"
AUDIT_IDEA = "idea_traceability_review.json"
AUDIT_EX_REF = "ex_ref_traceability_review.json"
AUDIT_EDITORIAL = "editorial_readiness_review.json"
AUDIT_READINESS = "readiness.json"
AUDIT_MANIFEST = "run_manifest.json"
AUDIT_LEDGER = "budget_ledger.json"
AUDIT_PROGRESS = "progress.json"
AUDIT_SUMMARY = "summary.json"
REPORT_NAME = "PHASE_4B227_REMAINING13_REAL_GENERATION_REPORT.md"

NEXT_ACTION = (
    "HUMAN EDITORIAL REVIEW OF THE 13 NEW CHAPTER CANDIDATES. "
    "DO NOT ASSEMBLE DOCX OR PDF. DO NOT PUBLISH book.json. "
    "DO NOT CALL TERRA. DO NOT CALL OPENAI. DO NOT REGENERATE. "
    "DO NOT RETRY A CONSUMED OR UNCERTAIN CALL. "
    "DO NOT SPEND ANY REMAINING BUDGET."
)

__all__ = [
    "ACCEPTED_CHAPTER_IDS",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_CHAPTER_IDS",
    "BUDGET_CAP_USD",
    "CANONICAL_PYTHON",
    "EXPECTED_CH003_JSON_SHA256",
    "EXPECTED_CH003_MD_SHA256",
    "EXPECTED_CH004_JSON_SHA256",
    "EXPECTED_CH004_MD_SHA256",
    "EXPECTED_CH018_JSON_SHA256",
    "EXPECTED_CH018_MD_SHA256",
    "EXPECTED_CH001_JSON_SHA256",
    "EXPECTED_CH001_MD_SHA256",
    "EXPECTED_CH002_RECOVERED_JSON_SHA256",
    "EXPECTED_CH002_RECOVERED_MD_SHA256",
    "EXPECTED_CH002_ORIGINAL_JSON_SHA256",
    "EXPECTED_CH002_ORIGINAL_MD_SHA256",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_PROMPT_1_1_INSTRUCTIONS_SHA256",
    "EXPECTED_PROMPT_1_1_SHA256",
    "EXPECTED_PROMPT_1_1_SYSTEM_SHA256",
    "EXPECTED_REMAINING_IDEAS",
    "EXPECTED_REMAINING_SECTIONS",
    "EXPECTED_SOURCE_MAP",
    "EXPECTED_TRANSCRIPT",
    "FORBIDDEN_CHAPTER_IDS",
    "GENERATED_STATUS",
    "LOCK_CONSUMED_STATES",
    "LOCK_NAME",
    "MODEL",
    "NORMALIZER_VERSION",
    "PHASE",
    "PROMPT_VERSION",
    "PROVIDER",
    "REMAINING_CHAPTER_IDS",
    "CONSUMED_4B226_SCOPE",
    "SONNET_INPUT_COST_PER_1M",
    "SONNET_OUTPUT_COST_PER_1M",
]
