"""
Phase 4B.2.6.1 — Terra output-budget forensics and semantic-contract optimization.

Offline only. Zero provider calls. Historical 4B.2.6 remains FAIL.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    HARD_MAX_OUTPUT_TOKENS,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
    STRUCTURED_OUTPUT_MODE,
)
from app.book_semantic_gate_4b24.constants import (
    CONNECTIVE_CASE_ID,
    EXPECTED_BENCHMARK_FILE_SHA256,
    EXPECTED_NEGATIVE_CASES,
    EXPECTED_POSITIVE_CASES,
    EXPECTED_SCORED_CASES,
    FUNERAL_CASE_ID,
    NEGATIVE_CASE_IDS,
    P3_CASE_ID,
    P8_CASE_ID,
    POSITIVE_CASE_IDS,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    EXPECTED_REQUEST_SHA256 as EXPECTED_REQUEST_SHA256_4B26,
    EXPECTED_REQUEST_SHA256_HISTORICAL_4B25,
    HISTORICAL_4B21_STATUS,
    HISTORICAL_4B22_STATUS,
    HISTORICAL_4B23_STATUS,
    HISTORICAL_4B241_STATUS,
    HISTORICAL_4B24_STATUS,
    HISTORICAL_4B251_STATUS,
    HISTORICAL_4B25_STATUS,
    HISTORICAL_4B2_STATUS,
    SEMANTIC_TOKEN_BUDGET,
)

PHASE = "4B.2.6.1"
PHASE_NAME = "TERRA_OUTPUT_BUDGET_AND_SEMANTIC_CONTRACT_FORENSICS"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B261_TERRA_OUTPUT_BUDGET_AND_SEMANTIC_CONTRACT_FORENSICS_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"

CANDIDATE_PROMPT_VERSION = "book-semantic-validator-1.1-candidate"
CANDIDATE_TRANSPORT_VERSION = "book-semantic-validation-transport-1.1-candidate"

HISTORICAL_4B26_STATUS = "FAIL"
OBSERVED_4B26_COST_USD = 0.106456
OBSERVED_4B26_INPUT_TOKENS = 4076
OBSERVED_4B26_OUTPUT_TOKENS = 8192
OBSERVED_4B26_FINISH_REASON = "length"
OBSERVED_4B26_ELAPSED_MS = 77328
OBSERVED_4B26_REQUEST_ID = "chatcmpl-EU9Ip28ayYHuhTrVYGY0CPP4JGEH5"

STRATEGY_A_BUDGETS = (12288, 16384, 24576)
STRATEGY_C_BATCH_SIZES = (1, 2, 5, 10)

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert PROMPT_VERSION_HISTORICAL == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION_HISTORICAL == "book-semantic-validation-transport-1.0"
assert OUTPUT_MODE == "json_object"
assert CANDIDATE_PROMPT_VERSION != PROMPT_VERSION_HISTORICAL
assert CANDIDATE_TRANSPORT_VERSION != TRANSPORT_VERSION_HISTORICAL
assert EXPECTED_REQUEST_SHA256_4B26 == (
    "8a92848e412763f0e67468245f9c007ee9537ffa4f2f5469af9a6934d9ebeb31"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B2_STATUS == "FAIL"
assert HISTORICAL_4B21_STATUS == "PASS"
assert HISTORICAL_4B22_STATUS == "PARTIAL"
assert HISTORICAL_4B23_STATUS == "PASS"
assert HISTORICAL_4B24_STATUS == "FAIL"
assert HISTORICAL_4B241_STATUS == "PASS"
assert HISTORICAL_4B25_STATUS == "FAIL"
assert HISTORICAL_4B251_STATUS == "PASS"
assert HISTORICAL_4B26_STATUS == "FAIL"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False

AUDIT_DIRNAME = "book_semantic_gate_4b261"
AUDIT_RAW = "terra_4b26_raw_response_forensics.json"
AUDIT_USAGE = "terra_4b26_token_usage_analysis.json"
AUDIT_CONTRACT = "terra_api_response_contract_analysis.json"
AUDIT_COMPLEXITY = "terra_benchmark_complexity_analysis.json"
AUDIT_SCHEMA = "terra_output_schema_analysis.json"
AUDIT_STRATEGY_A = "terra_strategy_a_budget_analysis.json"
AUDIT_STRATEGY_B = "terra_strategy_b_compact_contract_analysis.json"
AUDIT_STRATEGY_C = "terra_strategy_c_batching_analysis.json"
AUDIT_COMPARISON = "terra_strategy_comparison.json"
AUDIT_DIFF = "terra_candidate_contract_diff.json"
AUDIT_COST = "terra_cost_scenarios.json"
AUDIT_TESTS = "terra_offline_regression_tests.json"
AUDIT_READINESS = "terra_4b261_readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b261_index.json"
REPORT_NAME = "PHASE_4B261_TERRA_OUTPUT_BUDGET_AND_SEMANTIC_CONTRACT_FORENSICS_REPORT.md"

CONFIDENCE_CONFIRMED = "CONFIRMED"
CONFIDENCE_LOCAL = "LOCALLY_VERIFIED"
CONFIDENCE_UNKNOWN = "UNKNOWN_SERVER_SIDE"
CONFIDENCE_HYPOTHESIS = "HYPOTHESIS"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_NEXT_TERRA_CANARY_DESIGN_REVIEW = True
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "AUDIT_COMPARISON",
    "AUDIT_COMPLEXITY",
    "AUDIT_CONTRACT",
    "AUDIT_COST",
    "AUDIT_DIFF",
    "AUDIT_DIRNAME",
    "AUDIT_INDEX",
    "AUDIT_RAW",
    "AUDIT_READINESS",
    "AUDIT_SCHEMA",
    "AUDIT_STRATEGY_A",
    "AUDIT_STRATEGY_B",
    "AUDIT_STRATEGY_C",
    "AUDIT_TESTS",
    "AUDIT_USAGE",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "CANDIDATE_PROMPT_VERSION",
    "CANDIDATE_TRANSPORT_VERSION",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CONFIDENCE_CONFIRMED",
    "CONFIDENCE_HYPOTHESIS",
    "CONFIDENCE_LOCAL",
    "CONFIDENCE_UNKNOWN",
    "CONNECTIVE_CASE_ID",
    "CONSERVATIVE_MAX_OUTPUT_TOKENS",
    "EXPECTED_BENCHMARK_FILE_SHA256",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_NEGATIVE_CASES",
    "EXPECTED_OPENAI_SDK_VERSION",
    "EXPECTED_POSITIVE_CASES",
    "EXPECTED_PYTHON_VERSION",
    "EXPECTED_REQUEST_SHA256_4B26",
    "EXPECTED_REQUEST_SHA256_HISTORICAL_4B25",
    "EXPECTED_SCORED_CASES",
    "EXPECTED_SOURCE_MAP",
    "FUNERAL_CASE_ID",
    "HARD_MAX_OUTPUT_TOKENS",
    "HISTORICAL_4B21_STATUS",
    "HISTORICAL_4B22_STATUS",
    "HISTORICAL_4B23_STATUS",
    "HISTORICAL_4B241_STATUS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B251_STATUS",
    "HISTORICAL_4B25_STATUS",
    "HISTORICAL_4B26_STATUS",
    "HISTORICAL_4B2_STATUS",
    "MODEL",
    "NEGATIVE_CASE_IDS",
    "NEXT_ACTION",
    "OBSERVED_4B26_COST_USD",
    "OBSERVED_4B26_ELAPSED_MS",
    "OBSERVED_4B26_FINISH_REASON",
    "OBSERVED_4B26_INPUT_TOKENS",
    "OBSERVED_4B26_OUTPUT_TOKENS",
    "OBSERVED_4B26_REQUEST_ID",
    "OUTPUT_MODE",
    "P3_CASE_ID",
    "P8_CASE_ID",
    "PHASE",
    "PHASE_NAME",
    "POSITIVE_CASE_IDS",
    "PRODUCTION_ENDPOINT",
    "PROJECT_NAME",
    "PROMPT_VERSION_HISTORICAL",
    "PROVIDER",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "READY_FOR_NEW_REMOTE_TERRA_CALL",
    "READY_FOR_NEXT_TERRA_CANARY_DESIGN_REVIEW",
    "REPORT_NAME",
    "SCORED_CASE_ORDER",
    "SEMANTIC_TOKEN_BUDGET",
    "STRATEGY_A_BUDGETS",
    "STRATEGY_C_BATCH_SIZES",
    "TERRA_EXECUTION_AUTHORIZED",
    "TRANSPORT_VERSION_HISTORICAL",
]
