"""4B.2.6.1 report renderer. No secrets."""

from __future__ import annotations

from typing import Any, Mapping


def _yn(value: Any) -> str:
    if value in (True, "YES", "PASS", "yes", "pass"):
        return "YES"
    if value in (False, "NO", "FAIL", "no", "fail"):
        return "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any]) -> str:
    header = dict(bundle.get("header") or {})
    usage = dict(bundle.get("usage") or {})
    raw = dict(bundle.get("raw") or {})
    comparison = dict(bundle.get("comparison") or {})
    next_canary = dict(bundle.get("next_canary") or {})
    tests = dict(bundle.get("tests") or {})
    identities = dict(bundle.get("canonical") or {})
    complexity = dict(bundle.get("complexity") or {})
    sizes = dict(complexity.get("sizes") or {})
    estimates = dict(complexity.get("output_size_estimates") or {})
    lines = [
        "# PHASE 4B.2.6.1 — TERRA OUTPUT BUDGET AND SEMANTIC CONTRACT FORENSICS",
        "",
        "## A. Executive Summary",
        "",
        f"RESULT = {header.get('result') or 'FAIL'}",
        f"PROVIDER CALLS = {header.get('provider_calls') if header.get('provider_calls') is not None else 0}",
        f"OPENAI HTTP = {header.get('openai_http') if header.get('openai_http') is not None else 0}",
        f"ANTHROPIC HTTP = {header.get('anthropic_http') if header.get('anthropic_http') is not None else 0}",
        f"PRIMARY DIAGNOSIS = {header.get('primary_diagnosis') or ''}",
        f"CERTAINTY = {header.get('certainty') or ''}",
        f"RECOMMENDATION = {header.get('recommendation') or ''}",
        "",
        str(header.get("notes") or ""),
        "",
        "## B. Historical Evidence",
        "",
        "4B.2.5 = FAIL (HTTP 400 unsupported_parameter max_tokens).",
        "4B.2.5.1 = PASS (local mapping to max_completion_tokens; no Terra call).",
        "4B.2.6 = FAIL (request accepted; 8192 completion tokens; finish_reason=length; empty JSON).",
        "",
        f"4B.2.6 request SHA-256 = {header.get('historical_4b26_request_sha256') or ''}",
        f"4B.2.5 request SHA-256 = {header.get('historical_4b25_request_sha256') or ''}",
        "Contracts used in 4B.2.6 = book-semantic-validator-1.0 / book-semantic-validation-transport-1.0 / json_object / max_completion_tokens=8192.",
        f"Observed tokens = input {usage.get('usage_fields_available', {}).get('prompt_tokens_or_input_tokens')} / completion {usage.get('usage_fields_available', {}).get('completion_tokens_or_output_tokens')}.",
        f"Reasoning tokens = {usage.get('reasoning_tokens')}",
        f"Observed cost = {header.get('observed_cost_usd')} USD",
        "0/10 is absence of decisions, not ten misclassifications.",
        "",
        f"Canonical hashes pre/post = {header.get('canonical_input_hashes') or ''}",
        "",
        "## C. Root Cause Analysis",
        "",
        "### Facts (CONFIRMED)",
        "",
        "- The server accepted max_completion_tokens=8192 and billed 8192 completion tokens.",
        "- finish_reason=length.",
        "- Visible message.content is empty (0 bytes).",
        "- parse_json_payload raised AIStructuredOutputError empty. No repair. No retry.",
        "- json_object was not HTTP 400. No usable JSON body was returned.",
        "- Ten required handles are missing. No Terra verdict exists.",
        "",
        "### Hypotheses",
        "",
        "- Hidden reasoning or other non-emitted completion tokens consumed the budget before JSON.",
        "- The ten-case contract (copied claim text + required explanations) increased planning cost enough to starve visible output.",
        "",
        "### Unknowns",
        "",
        "- reasoning_tokens = UNKNOWN. Do not infer 8192.",
        "- Whether the server sent completion_tokens_details. The field was not persisted.",
        "- Whether json_object is semantically produced by gpt-5.6-terra.",
        "- Whether a larger budget would emit JSON.",
        f"- message.refusal persisted = {(raw.get('message_refusal') or {}).get('status')}",
        "",
        "### Local extraction gap (LOCALLY_VERIFIED)",
        "",
        "- extract_thinking_tokens_from_usage reads output_tokens_details.thinking_tokens, not completion_tokens_details.reasoning_tokens.",
        "- Missing persistence is not proof the server omitted the field.",
        "",
        "## D. Semantic Contract Assessment",
        "",
        f"System prompt size = {((sizes.get('system_prompt') or {}).get('chars'))} chars / estimated {((sizes.get('system_prompt') or {}).get('estimated_tokens'))} tokens.",
        f"Instruction size = {((sizes.get('validation_instructions') or {}).get('chars'))} chars / estimated {((sizes.get('validation_instructions') or {}).get('estimated_tokens'))} tokens.",
        f"Evidence SRC size = {((sizes.get('evidence_src_text') or {}).get('chars'))} chars / estimated {((sizes.get('evidence_src_text') or {}).get('estimated_tokens'))} tokens.",
        f"Paragraph text size = {((sizes.get('paragraphs_total') or {}).get('chars'))} chars / estimated {((sizes.get('paragraphs_total') or {}).get('estimated_tokens'))} tokens.",
        f"Minimal historical JSON estimate = {((estimates.get('minimal_valid_historical_json') or {}).get('estimated_tokens'))} tokens.",
        f"Detailed historical JSON estimate = {((estimates.get('detailed_valid_historical_json') or {}).get('estimated_tokens'))} tokens.",
        f"Minimal compact JSON estimate = {((estimates.get('minimal_valid_candidate_json') or {}).get('estimated_tokens'))} tokens.",
        "",
        "These sizes are estimates. They are not Terra reasoning counts.",
        "",
        "The 1.0 contract requires copied claim text (t) and a free-form explanation (x) for every claim, plus full-paragraph offset coverage. That is useful for auditability but redundantly large. Compact 1.1-candidate keeps spans, decisions, evidence handles, reason codes, and short reservations. It does not drop semantic fidelity requirements.",
        "",
        "FUNERAL, CONNECTIVE, P3, and P8 remain frozen. External biblical memory is not authorized evidence for P8.",
        "",
        "## E. Strategy Comparison",
        "",
        "| Strategy | Evidence fit | Complexity | Truncation | Resume | Control | 19 ch. | Version |",
        "|---|---|---|---|---|---|---|---|",
        "| A raise budget | Weak: 8192 already empty | Low | High if reasoning dominates | None | Unchanged | Poor if repeated | None |",
        "| B compact 1.1 | Addresses confirmed verbosity | Medium | Medium | None if still 10-in-1 | Preserved | Better density | Candidate only |",
        "| C small batches | Isolates JSON emission | Medium | Lower per call | High | Preserved | Aligned | Orchestration |",
        "| B+C | Best match to the evidence | Medium | Lowest | High | Preserved | Aligned | Candidate 1.1 |",
        "",
        f"Recommendation = {comparison.get('recommendation')}",
        "",
        str(comparison.get("rationale") or ""),
        "",
        "A alone is not justified as the next experiment. Cost is not linear with max_completion_tokens. Unknown cost is not reported as zero.",
        "",
        "## F. Proposed Next Canary",
        "",
        "This section is a proposal only. It is not an authorization.",
        "",
        f"Model = {next_canary.get('model')}",
        f"Endpoint = {next_canary.get('endpoint')}",
        f"Prompt / transport = {next_canary.get('prompt_version')} / {next_canary.get('transport_version')}",
        f"Cases = {next_canary.get('cases')} ({next_canary.get('first_case_handle')} / {next_canary.get('first_case_id')})",
        f"Budget = {(next_canary.get('budget') or {}).get('field')}={(next_canary.get('budget') or {}).get('value')}",
        f"Estimated cost if min JSON = {(next_canary.get('estimated_cost') or {}).get('total_cost_usd')}",
        f"Worst-case if 8192 exhausted = {(next_canary.get('worst_case_if_budget_exhausted') or {}).get('total_cost_usd')}",
        "",
        str(next_canary.get("why_one_positive_first") or ""),
        "",
        "Success criteria:",
        *[f"- {item}" for item in (next_canary.get("success_criteria") or [])],
        "",
        "Stop conditions:",
        *[f"- {item}" for item in (next_canary.get("stop_conditions") or [])],
        "",
        "## G. Tests and Regressions",
        "",
        f"TESTS = {tests.get('summary') or ''}",
        f"PASSED = {tests.get('passed') if tests.get('passed') is not None else 0}",
        f"FAILED = {tests.get('failed') if tests.get('failed') is not None else 0}",
        f"NEW REGRESSIONS = {tests.get('new_failures') if tests.get('new_failures') is not None else 0}",
        "A FakeAI PASS demonstrates local orchestration and contracts, not Terra quality.",
        "",
        "## H. Readiness",
        "",
        f"READY_FOR_NEXT_TERRA_CANARY_DESIGN_REVIEW = {_yn(header.get('ready_for_next_terra_canary_design_review'))}",
        "READY_FOR_NEW_REMOTE_TERRA_CALL = NO",
        "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = NO",
        "READY_FOR_FULL_REAL_BOOK_GENERATION = NO",
        "PRODUCTION CACHE = UNCHANGED",
        "book.json = NOT PUBLISHED",
        "",
        "## Historical status",
        "",
        "4B.2 = FAIL",
        "4B.2.1 = PASS",
        "4B.2.2 = PARTIAL",
        "4B.2.3 = PASS",
        "4B.2.4 = FAIL",
        "4B.2.4.1 = PASS",
        "4B.2.5 = FAIL",
        "4B.2.5.1 = PASS",
        "4B.2.6 = FAIL",
        "",
        "Do not rewrite any historical result.",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "No Terra call. No Sonnet call. No CH016 regeneration. No 19-chapter run. No book.json. Candidate contracts stay unpromoted.",
        "",
        f"Canonical environment executable = {header.get('python_executable') or ''}",
        f"Inputs unchanged = {_yn(identities.get('inputs_unchanged') if identities else header.get('inputs_unchanged'))}",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
