"""Constantes de la politique 3B.5.2 — aucun appel provider, aucun .env réel."""

from __future__ import annotations

SCHEMA_VERSION = "1.0"
PHASE = "3B.5.2"
MODE = "OFFLINE_POLICY"

POLICY_ARTIFACT_NAME = "source_analysis_second_global_attempt_policy.json"
REPORT_NAME = "PHASE_3B52_LONG_RUN_EXECUTION_POLICY_REPORT.md"

PREVIOUS_CLASSIFICATION = "HTTP_READ_TIMEOUT_TOO_SHORT"
ATTEMPT_1_RESULT = "AITimeoutError"
ATTEMPT_1_READ_TIMEOUT_SECONDS = 3600
ATTEMPT_1_HTTP_TIMEOUT_FORM = "scalar"

GLOBAL_ATTEMPT_NUMBER = 2
MAX_REAL_CALLS = 1
MAX_ATTEMPTS = 1
RETRY = False
FALLBACK = None

LINEAR_CANARY_EXTRAPOLATION_ALLOWED = False
THIRD_GLOBAL_TIMEOUT_ESCALATION_ALLOWED = False
TIMEOUT_IS_PROVIDER_GUARANTEE = False
TIMEOUT_POLICY_BASIS = "OPERATIONAL"
TIMEOUT_POLICY_SELECTED = True

CANDIDATE_READ_TIMEOUTS_SECONDS = (5400, 7200, 9000, 10800)
FIRST_FAILURE_LOWER_BOUND_SECONDS = 3600
SELECTED_OPERATIONAL_CONNECT_TIMEOUT_SECONDS = 30
SELECTED_OPERATIONAL_READ_TIMEOUT_SECONDS = 7200
SELECTED_READ_DURATION_HUMAN = "120 minutes"
CONNECT_DURATION_HUMAN = "30 seconds"
POLICY_CONFIDENCE = "MEDIUM"

SOURCE_ANALYSIS_CONNECT_ENV = "AI_SOURCE_ANALYSIS_CONNECT_TIMEOUT_SECONDS"
SOURCE_ANALYSIS_READ_ENV = "AI_SOURCE_ANALYSIS_READ_TIMEOUT_SECONDS"
PYTHON_CODE_CHANGE_REQUIRED = False
OTHER_STAGES_AFFECTED = False

STATUS_NOT_JUSTIFIED = "NOT_JUSTIFIED"
STATUS_TECHNICALLY_AUTHORIZABLE = "TECHNICALLY_AUTHORIZABLE"
STATUS_AUTHORIZED_FOR_EXECUTION = "AUTHORIZED_FOR_EXECUTION"
SELECTED_POLICY_STATUS = STATUS_TECHNICALLY_AUTHORIZABLE

SECOND_GLOBAL_ATTEMPT_JUSTIFIED = True
EXECUTION_AUTHORIZED = False
REQUIRES_HUMAN_REVIEW = True
PROVIDER_CALL_PERFORMED = False

DECISION_ARCHITECTURE_REVIEW = "ARCHITECTURE_REVIEW"
DECISION_RETRY_WITH_LONGER_TIMEOUT = "RETRY_WITH_LONGER_TIMEOUT"
DECISION_STOP_HUMAN_REVIEW = "STOP_HUMAN_REVIEW"
DECISION_PRESERVE_TRANSPORT_OFFLINE_DIAGNOSIS = (
    "PRESERVE_TRANSPORT_OFFLINE_DIAGNOSIS"
)
DECISION_STOP_NO_RETRY = "STOP_NO_RETRY"

FAILURE_SECOND_TIMEOUT = DECISION_ARCHITECTURE_REVIEW
FAILURE_PROVIDER_ERROR = DECISION_STOP_HUMAN_REVIEW
FAILURE_POST_PROVIDER_LOCAL = DECISION_PRESERVE_TRANSPORT_OFFLINE_DIAGNOSIS
FAILURE_TRUNCATION = DECISION_STOP_NO_RETRY

NEXT_PHASE_IF_AUTHORIZABLE = (
    "3B_FINAL_GLOBAL_CLEAN_SOURCE_ANALYZER_ATTEMPT_2"
)
NEXT_PHASE_IF_SECOND_TIMEOUT = (
    "3B.6_GLOBAL_ANALYSIS_EXECUTION_STRATEGY_REVIEW"
)

EXPECTED_PROVIDER = "anthropic"
EXPECTED_MODEL = "claude-sonnet-5"
EXPECTED_STAGE = "source_analysis"
EXPECTED_PROMPT_VERSION = "1.3"
EXPECTED_STRATEGY = "global"
EXPECTED_TRANSCRIPT_ID = "TR001"
EXPECTED_INPUT_MODE = "DERIVED"
EXPECTED_SEGMENTS = 8298
EXPECTED_WORDS = 38313
EXPECTED_DURATION_SECONDS = 19954.601
EXPECTED_INPUT_TOKENS = 142953
EXPECTED_USABLE_INPUT_BUDGET = 572000
EXPECTED_REMAINING_MARGIN = 429047
EXPECTED_MAX_OUTPUT_TOKENS = 128000

CANARY_SEGMENTS = 10
CANARY_WORDS = 100
CANARY_LATENCY_SECONDS = 37.3
CANARY_OUTPUT_TOKENS = 3544

ILLUSTRATIVE_OUTPUT_TOKENS = (10000, 25000, 50000, 75000, 100000, 128000)

EDITORIAL_STAGES = (
    "source_analysis",
    "editorial_planning",
    "book_generation",
    "book_validation",
)

BASELINE_PASSED = 1982
BASELINE_FAILED = 0
FINAL_PASSED = 2008
FINAL_FAILED = 0

DEFAULT_CONNECT_SECONDS = 30.0
DEFAULT_READ_SECONDS = 300.0

__all__ = [
    "CANDIDATE_READ_TIMEOUTS_SECONDS",
    "FAILURE_SECOND_TIMEOUT",
    "GLOBAL_ATTEMPT_NUMBER",
    "LINEAR_CANARY_EXTRAPOLATION_ALLOWED",
    "MAX_ATTEMPTS",
    "MAX_REAL_CALLS",
    "MODE",
    "PHASE",
    "POLICY_ARTIFACT_NAME",
    "REPORT_NAME",
    "SCHEMA_VERSION",
    "SELECTED_OPERATIONAL_CONNECT_TIMEOUT_SECONDS",
    "SELECTED_OPERATIONAL_READ_TIMEOUT_SECONDS",
    "SELECTED_POLICY_STATUS",
    "THIRD_GLOBAL_TIMEOUT_ESCALATION_ALLOWED",
]
