"""Rapport markdown 3B.7.7A.40."""

from __future__ import annotations

from typing import Any, Mapping

from app.source_analysis_v31_global_v20_grammar_canary.constants import (
    CANARY_MAX_OUTPUT_TOKENS,
    LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
    MODEL,
    PRODUCTION_ABSOLUTE_HEADROOM,
    PRODUCTION_EXPECTED_OUTPUT_TOKENS,
    PRODUCTION_HARD_PLANNING_TOKENS,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PRODUCTION_OUTPUT_RISK,
    PRODUCTION_SAFETY_MARGIN,
    PRODUCTION_SAFETY_THRESHOLD,
    PROMPT_VERSION,
    RELATION_QUALITY_TECHNICAL_DEBT,
    SCHEMA_ADAPTED_BYTES,
    SCHEMA_HASH,
    SCHEMA_RAW_BYTES,
    TRANSPORT_VERSION,
)
from app.source_analysis_v31_global_v20_grammar_canary.runner import CanaryRunResult


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(
    result: CanaryRunResult,
    *,
    tests: str,
    extra_header: Mapping[str, Any] | None = None,
) -> str:
    exe = result.execution or {}
    dry = result.dry_run or {}
    extra = dict(extra_header or {})
    verdict = exe.get("result") or extra.get("result") or result.mode
    schema_raw = exe.get("schema_raw_bytes") or dry.get("schema_raw_bytes") or SCHEMA_RAW_BYTES
    schema_adapted = (
        exe.get("schema_adapted_bytes")
        or dry.get("schema_adapted_bytes")
        or SCHEMA_ADAPTED_BYTES
    )
    schema_hash = exe.get("schema_hash") or dry.get("schema_hash") or SCHEMA_HASH
    cost = (exe.get("cost") or {}).get("display") or (exe.get("cost") or {}).get("total_cost")
    elapsed = exe.get("provider_elapsed_ms")
    elapsed_display = f"{elapsed} ms" if elapsed is not None else "n/a"
    estimator_error = exe.get("estimator_error") or {}
    error_display = "n/a"
    if estimator_error:
        error_display = (
            f"{estimator_error.get('actual_over_predicted')} "
            f"({estimator_error.get('percent')}%)"
        )
    predicted = exe.get("predicted_canary_output")
    if predicted is None:
        predicted = ((dry.get("output_estimate") or {}).get("expected_provider_tokens"))
    lines = [
        "# PHASE 3B.7.7A.40 — COMPACT GLOBAL CONSOLIDATION V2.0 GRAMMAR CANARY",
        "",
        "## Result",
        "",
        str(verdict),
        "",
        "AUTHORIZED PROVIDER CALLS =",
        "1",
        "",
        "ACTUAL PROVIDER CALLS =",
        str(exe.get("actual_calls") if exe else result.anthropic_post_attempts),
        "",
        "SUCCESSFUL PROVIDER CALLS =",
        str(exe.get("successful_calls") if exe else 0),
        "",
        "RETRIES =",
        "0",
        "",
        "PASTORAL DATA SENT =",
        "NO",
        "",
        "REAL CONSOLIDATION EXECUTED =",
        "NO",
        "",
        "MODEL =",
        MODEL,
        "",
        "PROMPT =",
        PROMPT_VERSION,
        "",
        "TRANSPORT =",
        TRANSPORT_VERSION,
        "",
        "SCHEMA RAW / ADAPTED =",
        f"{_dash(schema_raw)} / {_dash(schema_adapted)}",
        "",
        "SCHEMA HASH =",
        _dash(schema_hash),
        "",
        "SCHEMA IDENTITY =",
        _dash(exe.get("schema_identity") or dry.get("schema_identity")),
        "",
        "HTTP =",
        _dash(exe.get("http_status")),
        "",
        "FINISH =",
        _dash(exe.get("finish_reason")),
        "",
        "THINKING =",
        "disabled",
        "",
        "ACTUAL THINKING TOKENS =",
        _dash(exe.get("thinking_tokens")),
        "",
        "CANARY MAX OUTPUT =",
        str(exe.get("max_output_canary") or CANARY_MAX_OUTPUT_TOKENS),
        "",
        "REQUEST ID =",
        _dash(exe.get("request_id")),
        "",
        "INPUT TOKENS =",
        _dash(exe.get("input_tokens") or exe.get("provider_input")),
        "",
        "OUTPUT TOKENS =",
        _dash(exe.get("output_tokens")),
        "",
        "COST =",
        _dash(cost),
        "",
        "ELAPSED =",
        elapsed_display,
        "",
        "STRUCTURED PARSE =",
        _dash(exe.get("structured_parse")),
        "",
        "TRANSPORT DECODER =",
        _dash(exe.get("transport_decoder")),
        "",
        "HANDLES =",
        _dash(exe.get("handle_validation")),
        "",
        "LOCAL IDEAS =",
        _dash(exe.get("local_ideas")),
        "",
        "GLOBAL IDEAS =",
        _dash(exe.get("global_ideas")),
        "",
        "MEMBER OCCURRENCES =",
        _dash(exe.get("member_occurrences")),
        "",
        "DISTINCT MEMBERS =",
        _dash(exe.get("distinct_members")),
        "",
        "EXPLICIT DROPS =",
        _dash(exe.get("explicit_drops")),
        "",
        "UNKNOWN MEMBERS =",
        _dash(exe.get("unknown_members")),
        "",
        "DUPLICATE MEMBERS =",
        _dash(exe.get("duplicate_members")),
        "",
        "MISSING MEMBERS =",
        _dash(exe.get("missing_members")),
        "",
        "MEMBER/DROP OVERLAP =",
        _dash(exe.get("member_drop_overlap")),
        "",
        "ACCOUNTABILITY COVERAGE =",
        _dash(exe.get("accountability_coverage")),
        "",
        "DERIVED KEEP =",
        _dash(exe.get("keep_count")),
        "",
        "DERIVED MERGE_EQUIVALENT =",
        _dash(exe.get("merge_equivalent_count")),
        "",
        "DERIVED DROP =",
        _dash(exe.get("drop_count")),
        "",
        "OTHER =",
        _dash(exe.get("other_count") if exe.get("other_count") is not None else 0),
        "",
        "LINK_RELATED =",
        _dash(exe.get("link_related") if exe.get("link_related") is not None else 0),
        "",
        "EXACT_DUPLICATE DROP =",
        _dash(
            exe.get("exact_duplicate_drop")
            if exe.get("exact_duplicate_drop") is not None
            else 0
        ),
        "",
        "DERIVED SRC UNION =",
        _dash(exe.get("derived_src_union")),
        "",
        "GLOBAL VALIDATOR =",
        _dash(exe.get("global_validator")),
        "",
        "CANONICAL RECONSTRUCTION =",
        _dash(exe.get("canonical_reconstruction")),
        "",
        "CANONICAL VALIDATION =",
        _dash(exe.get("canonical_validation")),
        "",
        "EMPTY RELATIONS VALID =",
        _dash(exe.get("empty_relations_valid")),
        "",
        "DETERMINISTIC REPLAY =",
        _dash(exe.get("deterministic_replay")),
        "",
        "SEMANTIC FIXTURE REVIEW =",
        _dash(exe.get("semantic_fixture_review")),
        "",
        "GLOBAL_TRANSPORT_2_0_GRAMMAR_PROOF =",
        _dash(exe.get("global_transport_2_0_grammar_proof")),
        "",
        "PREDICTED CANARY OUTPUT =",
        _dash(predicted),
        "",
        "ACTUAL CANARY OUTPUT =",
        _dash(exe.get("actual_canary_output") or exe.get("output_tokens")),
        "",
        "ESTIMATOR ERROR =",
        error_display,
        "",
        "PRODUCTION MAX OUTPUT =",
        str(PRODUCTION_MAX_OUTPUT_TOKENS),
        "",
        "PRODUCTION 75% THRESHOLD =",
        str(PRODUCTION_SAFETY_THRESHOLD),
        "",
        "PRODUCTION EXPECTED =",
        str(PRODUCTION_EXPECTED_OUTPUT_TOKENS),
        "",
        "PRODUCTION HARD/PLANNING BOUND =",
        str(PRODUCTION_HARD_PLANNING_TOKENS),
        "",
        "75% THRESHOLD MARGIN =",
        str(PRODUCTION_SAFETY_MARGIN),
        "",
        "ABSOLUTE MAX HEADROOM =",
        str(PRODUCTION_ABSOLUTE_HEADROOM),
        "",
        "PRODUCTION OUTPUT RISK =",
        PRODUCTION_OUTPUT_RISK,
        "",
        "LOCAL EXTRACTION FUNCTIONALLY FROZEN =",
        LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        RELATION_QUALITY_TECHNICAL_DEBT,
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        _dash(extra.get("new_failures") or "0"),
        "",
        "READY_FOR_COMPACT_GLOBAL_REAL_CALL_PREFLIGHT =",
        _dash(exe.get("ready_for_compact_global_real_call_preflight") or "NO"),
        "",
        "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY =",
        "NO",
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## Notes",
        "",
        f"Authorization scope = {result.authorization_scope}",
        "",
        f"Error = {_dash(result.error)}",
        "",
        "Tiny-canary estimator accuracy does not prove production estimator accuracy.",
        "",
        "A.40 does not authorize real consolidation even if the compact grammar canary passes.",
        "",
        "The next phase must review the real production output budget offline.",
        "",
        "WAIT FOR HUMAN REVIEW.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
