"""Constantes 3B.7.7A.43 — reuse-by-reference output-budget redesign. Offline."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis_v31_global_drop_domain.constants import (
    COMPACT_20_CHARS_PER_TOKEN_CONSERVATIVE,
    COMPACT_20_CHARS_PER_TOKEN_OBSERVED,
    DROP_DOMAIN,
    PRODUCTION_MAX_OUTPUT_TOKENS as A41_MAX_OUTPUT,
    V20_SCHEMA_ADAPTED_BYTES,
    V20_SCHEMA_HASH,
    V20_SCHEMA_RAW_BYTES,
    V20_TRANSPORT_VERSION,
)
from app.source_analysis_v31_global_grammar_canary.constants import (
    FROZEN_GRANULARITY,
    FROZEN_PLANNER,
    FROZEN_PROMPT,
    FROZEN_SRC_POLICY,
    FROZEN_TRANSPORT,
    MODEL,
    PROJECT_NAME,
    PROVIDER,
    THINKING_CONTRACT,
    THINKING_MODE,
)
from app.source_analysis_v31_global_output_architecture.constants import (
    A34_STATUS_PRESERVED,
    A35_STATUS_PRESERVED,
    A36_STATUS_PRESERVED,
    A37_STATUS_PRESERVED,
    A38_CHARS_PER_PROVIDER_OUTPUT_TOKEN,
    A38_INPUT_TOKENS,
    A38_STATUS_PRESERVED,
    DROP_REASONS_V20,
    EXPECTED_EXAMPLE,
    EXPECTED_IDEA,
    EXPECTED_REFERENCE,
    EXPECTED_RELATION,
    EXPECTED_TOPIC,
    EXPECTED_UNCERTAINTY,
    RETIRED_DISPOSITION_OPS_V20,
    RETIRED_DROP_REASONS_V20,
    TEXT_LIMITS,
)
from app.source_analysis_v31_global_preflight.constants import (
    IDEA_DISPOSITION_COVERAGE_REQUIRED,
    IDEA_KIND_POLICY,
    INPUT_COST_PER_1M,
    OUTPUT_COST_PER_1M,
    READY_LABEL,
    READY_WINDOWS,
    RELATION_QUALITY_TECHNICAL_DEBT,
)
from app.source_analysis_v31_global_v201_contract_canary.constants import (
    PRODUCTION_CONSERVATIVE_OUTPUT_TOKENS as V20_CONSERVATIVE_OUTPUT,
    PRODUCTION_EXPECTED_OUTPUT_TOKENS as V20_EXPECTED_OUTPUT,
    PRODUCTION_HARD_PLANNING_TOKENS as V20_HARD_OUTPUT,
    PRODUCTION_OUTPUT_RISK as V20_OUTPUT_RISK,
    PROMPT_VERSION as V201_PROMPT_VERSION,
    REPORT_NAME as A42_REPORT_NAME,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.43"
MODE = "GLOBAL_CONSOLIDATION_REUSE_BY_REFERENCE_OUTPUT_BUDGET_REDESIGN"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_ANTHROPIC_CALLS = 0
REAL_OPENAI_CALLS = 0
GRAMMAR_CANARY_CALLS = 0
REAL_CONSOLIDATION_CALLS = 0
CONSOLIDATION_AUTHORIZED = False
GRAMMAR_CANARY_AUTHORIZED = False
SOURCE_MAP_PUBLICATION_AUTHORIZED = False

A39_STATUS_PRESERVED = "PASS"
A40_STATUS_PRESERVED = "FAIL"
A41_STATUS_PRESERVED = "PASS"
A42_STATUS_PRESERVED = "PASS"
assert A34_STATUS_PRESERVED == "PASS"
assert A35_STATUS_PRESERVED == "FAIL"
assert A36_STATUS_PRESERVED == "PASS"
assert A37_STATUS_PRESERVED == "PASS"
assert A38_STATUS_PRESERVED == "FAIL"
assert A39_STATUS_PRESERVED == "PASS"
assert A40_STATUS_PRESERVED == "FAIL"
assert A41_STATUS_PRESERVED == "PASS"
assert A42_STATUS_PRESERVED == "PASS"
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert THINKING_MODE == "disabled"
assert V201_PROMPT_VERSION == "global-consolidation-2.0.1"
assert V20_TRANSPORT_VERSION == "global-consolidation-transport-2.0"
assert V20_SCHEMA_RAW_BYTES == 1588
assert V20_SCHEMA_ADAPTED_BYTES == 1836
assert V20_SCHEMA_HASH == (
    "90b99a38ac704d00e1304495da0c757118293e43493ddb7321b3ffb3256d8330"
)
assert DROP_REASONS_V20 == ("transport_artifact", "non_substantive_fragment")
assert RETIRED_DROP_REASONS_V20 == ("exact_duplicate",)
assert RETIRED_DISPOSITION_OPS_V20 == ("OTHER",)
assert IDEA_KIND_POLICY == "KEEP_EMPTY_GLOBALLY"
assert IDEA_DISPOSITION_COVERAGE_REQUIRED == 100
assert READY_WINDOWS == (
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
)
assert READY_LABEL == "7 / 7"
assert EXPECTED_TOPIC == 67
assert EXPECTED_IDEA == 286
assert EXPECTED_RELATION == 127
assert EXPECTED_EXAMPLE == 49
assert EXPECTED_REFERENCE == 59
assert EXPECTED_UNCERTAINTY == 35
assert A41_MAX_OUTPUT == 48000
assert V20_EXPECTED_OUTPUT == 34514
assert V20_CONSERVATIVE_OUTPUT == 40362
assert V20_HARD_OUTPUT == 41430
assert V20_OUTPUT_RISK == "NEEDS_OUTPUT_REDESIGN"
assert DROP_DOMAIN == "LOCAL_IDEA_ONLY"
assert FROZEN_PLANNER == "window-planner-v2.1-small"
assert FROZEN_PROMPT == "window-analysis-1.4.0"
assert FROZEN_TRANSPORT == "semantic-transport-v3.1-local-lite"
assert FROZEN_GRANULARITY == "window-granularity-1.2-kind-specific"
assert FROZEN_SRC_POLICY == "src-reference-policy-1.1-narrow-canonicalization"

A42_REQUEST_ID = "req_011CfXza6D59WbhBZVCLPEej"
A42_HTTP_STATUS = 200
A42_FINISH_REASON = "end_turn"
A42_THINKING_TOKENS = 0
A42_INPUT_TOKENS = 4763
A42_OUTPUT_TOKENS = 640
A42_RAW_TEXT_CHARS = 1321
A42_CHARS_PER_TOKEN = A42_RAW_TEXT_CHARS / A42_OUTPUT_TOKENS
A42_ESTIMATOR_ERROR_PERCENT = 8.84
A42_CONTRACT_PROOF = "PASS"
GLOBAL_TRANSPORT_2_0_GRAMMAR_PROOF = "PASS"
GLOBAL_CONSOLIDATION_2_0_1_CONTRACT_CANARY = "PASS"
assert abs(A42_CHARS_PER_TOKEN - 2.0640625) < 1e-9

CURRENT_PROMPT = V201_PROMPT_VERSION
CURRENT_TRANSPORT = V20_TRANSPORT_VERSION
OLD_PROMPT_VERSION = V201_PROMPT_VERSION
OLD_TRANSPORT_VERSION = V20_TRANSPORT_VERSION
NEXT_PROMPT_VERSION = "global-consolidation-3.0"
FUTURE_PROMPT_VERSION = "global-consolidation-3.0.1"
NEXT_TRANSPORT_VERSION = "global-consolidation-transport-3.0"
assert FUTURE_PROMPT_VERSION != NEXT_PROMPT_VERSION
SCHEMA_CHANGED = True
NEW_GRAMMAR_CANARY_REQUIRED = True

NEXT_SCHEMA_RAW_BYTES = 1583
NEXT_SCHEMA_ADAPTED_BYTES = 1831
NEXT_SCHEMA_HASH = (
    "822397b642b0e1724e29686962caab32bff63effe18f05bff26b404bad9b2a90"
)

SELECTED_OPTION = "B"
SELECTED_ARCHITECTURE = "HARD_SINGLE_MEMBER_REUSE_SYNTHESIZE_MERGES_ONLY"
SINGLE_MEMBER_POLICY = "DETERMINISTIC_REUSE"
MULTI_MEMBER_POLICY = "SYNTHESIZE"
REWRITE_EXCEPTION_POLICY = "FORBIDDEN"
PROVIDER_IDEA_TEXT_REQUIRED_FOR = "MULTI_MEMBER_MERGES_ONLY"
DERIVED_SRC = True
RELATION_POLICY = "RELATIONS_DEFERRED"

SYNTHESIZED_IDEA_MAX_CHARS = TEXT_LIMITS["idea"]
assert SYNTHESIZED_IDEA_MAX_CHARS == 180
EXPECTED_GLOBAL_IDEA_RANGE = (280, 286)
EXPECTED_GLOBAL_IDEAS = 285
EXPECTED_REUSED_IDEAS = 284
EXPECTED_SYNTHESIZED_IDEAS = 1
EXPECTED_DROPS = 0

PRODUCTION_MAX_OUTPUT_TOKENS = A41_MAX_OUTPUT
SAFETY_70 = int(PRODUCTION_MAX_OUTPUT_TOKENS * 0.70)
SAFETY_75 = int(PRODUCTION_MAX_OUTPUT_TOKENS * 0.75)
SAFETY_80 = int(PRODUCTION_MAX_OUTPUT_TOKENS * 0.80)
assert SAFETY_70 == 33600
assert SAFETY_75 == 36000
assert SAFETY_80 == 38400

CHARS_PER_TOKEN_EXPECTED = A42_CHARS_PER_TOKEN
CHARS_PER_TOKEN_CONSERVATIVE = COMPACT_20_CHARS_PER_TOKEN_CONSERVATIVE
assert CHARS_PER_TOKEN_CONSERVATIVE == 2.00
ESTIMATOR_ERROR_BUFFER = 1.10
A38_PRODUCTION_INPUT_TOKENS = A38_INPUT_TOKENS
assert A38_PRODUCTION_INPUT_TOKENS == 68138

LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN = "YES"
PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY = "NO"
READY_FOR_REUSE_ARCHITECTURE_GRAMMAR_CANARY = "YES"
READY_FOR_COMPACT_GLOBAL_REAL_CALL_PREFLIGHT = "NO"

A42_CANARY_SUBDIR = "canary/global_consolidation_prompt_v201"
PROTECTED_HISTORICAL = (
    "audit/PHASE_3B77A34_GLOBAL_CONSOLIDATION_OFFLINE_PREFLIGHT_REPORT.md",
    "audit/PHASE_3B77A35_GLOBAL_CONSOLIDATION_TINY_GRAMMAR_CANARY_REPORT.md",
    "audit/PHASE_3B77A36_GLOBAL_CONSOLIDATION_CANARY_FORENSICS_REPORT.md",
    "audit/PHASE_3B77A37_GLOBAL_CONSOLIDATION_V11_TINY_GRAMMAR_CANARY_REPORT.md",
    "audit/PHASE_3B77A38_FIRST_REAL_GLOBAL_CONSOLIDATION_CANARY_REPORT.md",
    "audit/PHASE_3B77A39_GLOBAL_CONSOLIDATION_OUTPUT_ARCHITECTURE_REDESIGN_REPORT.md",
    "audit/PHASE_3B77A40_COMPACT_GLOBAL_CONSOLIDATION_V20_GRAMMAR_CANARY_REPORT.md",
    "audit/PHASE_3B77A41_COMPACT_GLOBAL_CONSOLIDATION_TYPE_BOUNDARY_HARDENING_REPORT.md",
    f"audit/{A42_REPORT_NAME}",
    f"audit/{A42_CANARY_SUBDIR}/global_consolidation_v201_canary_execution.json",
    f"audit/{A42_CANARY_SUBDIR}/global_consolidation_v201_usage_cost.json",
)

REUSE_ANALYSIS_ARTIFACT = "global_consolidation_reuse_by_reference_analysis.json"
QUALITY_ARTIFACT = "global_consolidation_local_idea_reuse_quality.json"
BREAKDOWN_ARTIFACT = "global_consolidation_v20_output_component_breakdown.json"
OPTIONS_ARTIFACT = "global_consolidation_reuse_architecture_options.json"
SELECTED_ARTIFACT = "global_consolidation_selected_reuse_architecture.json"
CONTRACT_ARTIFACT = "global_consolidation_next_compact_contract.json"
BUDGET_ARTIFACT = "global_consolidation_reuse_output_budget.json"
STRESS_ARTIFACT = "global_consolidation_reuse_full_scale_stress.json"
SCHEMA_ARTIFACT = "global_consolidation_reuse_next_schema.json"
COST_ARTIFACT = "global_consolidation_reuse_cost_estimate.json"
READINESS_ARTIFACT = "global_consolidation_post_a43_readiness.json"
TEST_DELTA_ARTIFACT = "source_analysis_a43_test_delta.json"
BASELINE_ARTIFACT = "source_analysis_a43_test_baseline.json"
REPORT_NAME = (
    "PHASE_3B77A43_GLOBAL_CONSOLIDATION_REUSE_OUTPUT_BUDGET_REDESIGN_REPORT.md"
)

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_reuse_output.py",
    "app/tests/test_source_analysis_v31_global_reuse_output_audit.py",
    "app/tests/test_source_analysis_v31_global_v201_contract_canary.py",
    "app/tests/test_source_analysis_v31_global_drop_domain.py",
    "app/tests/test_source_analysis_v31_global_output_architecture.py",
)
BROADER_SLICE_TEST_PATHS = FOCUSED_TEST_PATHS + (
    "app/tests/test_source_analysis_v31_global_v201_contract_canary_audit.py",
    "app/tests/test_source_analysis_v31_global_drop_domain_audit.py",
    "app/tests/test_source_analysis_v31_global_output_architecture_audit.py",
    "app/tests/test_source_analysis_v31_global_v20_grammar_canary.py",
)

assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert REAL_ANTHROPIC_CALLS == 0
assert REAL_OPENAI_CALLS == 0
assert GRAMMAR_CANARY_CALLS == 0
assert REAL_CONSOLIDATION_CALLS == 0
assert READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY == "NO"
assert READY_FOR_REUSE_ARCHITECTURE_GRAMMAR_CANARY == "YES"
assert RELATION_QUALITY_TECHNICAL_DEBT == "YES"
assert not source_map_path(PROJECT_NAME).is_file() or SOURCE_MAP_STATUS == "NOT PUBLISHED"

__all__ = [
    "A34_STATUS_PRESERVED",
    "A35_STATUS_PRESERVED",
    "A36_STATUS_PRESERVED",
    "A37_STATUS_PRESERVED",
    "A38_CHARS_PER_PROVIDER_OUTPUT_TOKEN",
    "A38_PRODUCTION_INPUT_TOKENS",
    "A38_STATUS_PRESERVED",
    "A39_STATUS_PRESERVED",
    "A40_STATUS_PRESERVED",
    "A41_STATUS_PRESERVED",
    "A42_CANARY_SUBDIR",
    "A42_CHARS_PER_TOKEN",
    "A42_CONTRACT_PROOF",
    "A42_ESTIMATOR_ERROR_PERCENT",
    "A42_FINISH_REASON",
    "A42_HTTP_STATUS",
    "A42_INPUT_TOKENS",
    "A42_OUTPUT_TOKENS",
    "A42_RAW_TEXT_CHARS",
    "A42_REPORT_NAME",
    "A42_REQUEST_ID",
    "A42_STATUS_PRESERVED",
    "A42_THINKING_TOKENS",
    "BASELINE_ARTIFACT",
    "BREAKDOWN_ARTIFACT",
    "BROADER_SLICE_TEST_PATHS",
    "BUDGET_ARTIFACT",
    "CHARS_PER_TOKEN_CONSERVATIVE",
    "CHARS_PER_TOKEN_EXPECTED",
    "COMPACT_20_CHARS_PER_TOKEN_CONSERVATIVE",
    "COMPACT_20_CHARS_PER_TOKEN_OBSERVED",
    "CONSOLIDATION_AUTHORIZED",
    "CONTRACT_ARTIFACT",
    "COST_ARTIFACT",
    "CURRENT_PROMPT",
    "CURRENT_TRANSPORT",
    "DERIVED_SRC",
    "DROP_DOMAIN",
    "DROP_REASONS_V20",
    "ESTIMATOR_ERROR_BUFFER",
    "EXPECTED_DROPS",
    "EXPECTED_EXAMPLE",
    "EXPECTED_GLOBAL_IDEA_RANGE",
    "EXPECTED_GLOBAL_IDEAS",
    "EXPECTED_IDEA",
    "EXPECTED_REFERENCE",
    "EXPECTED_RELATION",
    "EXPECTED_REUSED_IDEAS",
    "EXPECTED_SYNTHESIZED_IDEAS",
    "EXPECTED_TOPIC",
    "EXPECTED_UNCERTAINTY",
    "FOCUSED_TEST_PATHS",
    "FROZEN_GRANULARITY",
    "FROZEN_PLANNER",
    "FROZEN_PROMPT",
    "FROZEN_SRC_POLICY",
    "FUTURE_PROMPT_VERSION",
    "FROZEN_TRANSPORT",
    "GLOBAL_CONSOLIDATION_2_0_1_CONTRACT_CANARY",
    "GLOBAL_TRANSPORT_2_0_GRAMMAR_PROOF",
    "GRAMMAR_CANARY_AUTHORIZED",
    "GRAMMAR_CANARY_CALLS",
    "IDEA_DISPOSITION_COVERAGE_REQUIRED",
    "IDEA_KIND_POLICY",
    "INPUT_COST_PER_1M",
    "LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN",
    "MODE",
    "MODEL",
    "MULTI_MEMBER_POLICY",
    "NEW_GRAMMAR_CANARY_REQUIRED",
    "NEXT_ACTION",
    "NEXT_PROMPT_VERSION",
    "NEXT_SCHEMA_ADAPTED_BYTES",
    "NEXT_SCHEMA_HASH",
    "NEXT_SCHEMA_RAW_BYTES",
    "NEXT_TRANSPORT_VERSION",
    "OLD_PROMPT_VERSION",
    "OLD_TRANSPORT_VERSION",
    "OPTIONS_ARTIFACT",
    "OUTPUT_COST_PER_1M",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PROJECT_NAME",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "PROVIDER_IDEA_TEXT_REQUIRED_FOR",
    "QUALITY_ARTIFACT",
    "READINESS_ARTIFACT",
    "READY_FOR_COMPACT_GLOBAL_REAL_CALL_PREFLIGHT",
    "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY",
    "READY_FOR_REUSE_ARCHITECTURE_GRAMMAR_CANARY",
    "READY_LABEL",
    "READY_WINDOWS",
    "REAL_ANTHROPIC_CALLS",
    "REAL_CONSOLIDATION_CALLS",
    "REAL_OPENAI_CALLS",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "RELATION_POLICY",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPORT_NAME",
    "RETIRED_DISPOSITION_OPS_V20",
    "RETIRED_DROP_REASONS_V20",
    "REUSE_ANALYSIS_ARTIFACT",
    "REWRITE_EXCEPTION_POLICY",
    "SAFETY_70",
    "SAFETY_75",
    "SAFETY_80",
    "SCHEMA_ARTIFACT",
    "SCHEMA_CHANGED",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SELECTED_ARTIFACT",
    "SELECTED_OPTION",
    "SINGLE_MEMBER_POLICY",
    "SOURCE_MAP_PUBLICATION_AUTHORIZED",
    "SOURCE_MAP_STATUS",
    "STRESS_ARTIFACT",
    "SYNTHESIZED_IDEA_MAX_CHARS",
    "TEST_DELTA_ARTIFACT",
    "TEXT_LIMITS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "V20_CONSERVATIVE_OUTPUT",
    "V20_EXPECTED_OUTPUT",
    "V20_HARD_OUTPUT",
    "V20_OUTPUT_RISK",
    "V20_SCHEMA_ADAPTED_BYTES",
    "V20_SCHEMA_HASH",
    "V20_SCHEMA_RAW_BYTES",
    "V20_TRANSPORT_VERSION",
    "V201_PROMPT_VERSION",
]
