"""Rapport markdown 3B.7.7A.43."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any], *, tests: str) -> str:
    header = bundle.get("header") or {}
    quality = bundle.get("quality") or {}
    sample = quality.get("sample_counts") or {}
    a38 = ((bundle.get("reuse_analysis") or {}).get("a38") or {})
    expected = a38.get("expected_production") or header.get("expected_global_ideas") or {}
    lines = [
        "# PHASE 3B.7.7A.43 — GLOBAL CONSOLIDATION REUSE OUTPUT-BUDGET REDESIGN",
        "",
        "## Result",
        "",
        str(header.get("result")),
        "",
        "REAL PROVIDER CALLS =",
        "0",
        "",
        "A.42 STATUS =",
        str(header.get("a42_status")),
        "",
        "A.42 REQUEST =",
        str(header.get("a42_request")),
        "",
        "A.42 CONTRACT PROOF =",
        str(header.get("a42_contract_proof")),
        "",
        "CURRENT TRANSPORT =",
        str(header.get("current_transport")),
        "",
        "CURRENT PROMPT =",
        str(header.get("current_prompt")),
        "",
        "CURRENT EXPECTED OUTPUT =",
        str(header.get("current_expected_output")),
        "",
        "CURRENT CONSERVATIVE OUTPUT =",
        str(header.get("current_conservative_output")),
        "",
        "CURRENT HARD OUTPUT =",
        str(header.get("current_hard_output")),
        "",
        "CURRENT OUTPUT RISK =",
        str(header.get("current_output_risk")),
        "",
        "LOCAL IDEA SAMPLE SIZE =",
        str(header.get("local_idea_sample_size")),
        "",
        "READY_FOR_REUSE =",
        str(sample.get("READY_FOR_REUSE", header.get("ready_for_reuse"))),
        "",
        "NEEDS_NORMALIZATION =",
        str(sample.get("NEEDS_NORMALIZATION", header.get("needs_normalization"))),
        "",
        "NOT_SELF_CONTAINED =",
        str(sample.get("NOT_SELF_CONTAINED", header.get("not_self_contained"))),
        "",
        "A.38 NEAR-COPY EVIDENCE =",
        _dash(header.get("a38_near_copy_evidence")),
        "",
        "SELECTED ARCHITECTURE =",
        str(header.get("selected_architecture")),
        "",
        "SINGLE-MEMBER POLICY =",
        str(header.get("single_member_policy")),
        "",
        "MULTI-MEMBER POLICY =",
        str(header.get("multi_member_policy")),
        "",
        "REWRITE EXCEPTION POLICY =",
        str(header.get("rewrite_exception_policy")),
        "",
        "PROVIDER IDEA TEXT REQUIRED FOR =",
        str(header.get("provider_idea_text_required_for")),
        "",
        "DERIVED SRC =",
        "YES",
        "",
        "RELATIONS =",
        "DEFERRED",
        "",
        "NEXT PROMPT =",
        str(header.get("next_prompt")),
        "",
        "NEXT TRANSPORT =",
        str(header.get("next_transport")),
        "",
        "NEXT SCHEMA RAW / ADAPTED =",
        str(header.get("next_schema_raw_adapted")),
        "",
        "NEXT SCHEMA HASH =",
        str(header.get("next_schema_hash")),
        "",
        "NEW GRAMMAR CANARY REQUIRED =",
        str(header.get("new_grammar_canary_required")),
        "",
        "EXPECTED GLOBAL IDEAS =",
        _dash(expected.get("expected_global_ideas")),
        "",
        "EXPECTED REUSED IDEAS =",
        _dash(expected.get("expected_reused_single_member")),
        "",
        "EXPECTED SYNTHESIZED IDEAS =",
        _dash(expected.get("expected_synthesized_merges")),
        "",
        "REVISED EXPECTED OUTPUT =",
        str(header.get("revised_expected")),
        "",
        "REVISED CONSERVATIVE OUTPUT =",
        str(header.get("revised_conservative")),
        "",
        "REVISED HARD OUTPUT =",
        str(header.get("revised_hard")),
        "",
        "MAX_OUTPUT =",
        "48000",
        "",
        "70% LIMIT =",
        "33600",
        "",
        "75% LIMIT =",
        "36000",
        "",
        "80% LIMIT =",
        "38400",
        "",
        "HARD UTILIZATION =",
        str(header.get("hard_utilization")),
        "",
        "ABSOLUTE HEADROOM =",
        str(header.get("absolute_headroom")),
        "",
        "OUTPUT RISK =",
        str(header.get("output_risk")),
        "",
        "ESTIMATED REAL INPUT =",
        str(header.get("estimated_real_input")),
        "",
        "ESTIMATED REAL OUTPUT =",
        str(header.get("estimated_real_output")),
        "",
        "ESTIMATED REAL COST =",
        str(header.get("estimated_real_cost")),
        "",
        "ALL-DISTINCT 286 REUSE STRESS =",
        str(header.get("all_distinct_286_reuse_stress")),
        "",
        "MIXED FULL-SCALE STRESS =",
        str(header.get("mixed_full_scale_stress")),
        "",
        "CANONICAL RECONSTRUCTION =",
        str(header.get("canonical_reconstruction")),
        "",
        "CANONICAL VALIDATION =",
        str(header.get("canonical_validation")),
        "",
        "IDEA ACCOUNTABILITY =",
        "YES" if header.get("idea_accountability") in {True, "PASS", "YES"} else str(header.get("idea_accountability")),
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        str(header.get("new_failures")),
        "",
        "LOCAL EXTRACTION FUNCTIONALLY FROZEN =",
        "YES",
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        "YES",
        "",
        "READY_FOR_REUSE_ARCHITECTURE_GRAMMAR_CANARY =",
        "YES" if header.get("readiness") == "READY_FOR_REUSE_ARCHITECTURE_GRAMMAR_CANARY" else "NO",
        "",
        "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY =",
        "NO",
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
