"""Constantes 3B.7.7A.21 — retry durci WIN001 V3. 1 appel Anthropic max."""

from __future__ import annotations

from app.source_analysis.window_models import (
    WINDOW_CONNECT_TIMEOUT_SECONDS,
    WINDOW_READ_TIMEOUT_SECONDS,
)
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    CLEAN_SHA,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
    SELECTED_ARCHITECTURE,
    SEMANTIC_TRANSPORT_VERSION_V3,
    TARGET_JSON_LOCAL_TOKENS,
    WINDOW_ANALYSIS_PROMPT_VERSION_V13,
    WINDOW_ANALYSIS_PROMPT_VERSION_V131,
)
from app.source_analysis_local_v3.schema import semantic_transport_v3_fingerprint
from app.source_analysis_output_ceiling_review.constants import (
    CALL1_SIGNATURE,
    CALL2_SIGNATURE,
    SMALL_SIGNATURE,
)
from app.source_analysis_small_window_hierarchy.constants import (
    CANDIDATE_CONTEXT_POLICY,
)
from app.source_analysis_small_window_readiness.constants import A7_WIN001_INPUT_HASH
from app.source_analysis_thinking_contract.constants import (
    SELECTED_CONTRACT,
    SELECTED_EFFORT,
    SELECTED_THINKING_MODE,
)
from app.source_analysis_v2_a15_forensics.constants import (
    A15_COVERAGE_PCT,
    A15_DISTINCT_SRC,
    A15_SIGNATURE,
)
from app.source_analysis_v2_link_semantics.constants import A13_REQUEST_IDENTITY
from app.source_analysis_v2_real_win001.constants import (
    EXPECTED_FIRST_OWNED_SRC,
    EXPECTED_LAST_OWNED_SRC,
    EXPECTED_OWNED_SRC_COUNT,
    EXPECTED_WORD_COUNT,
    WINDOW_ID,
)
from app.source_analysis_v3_a19_forensics.constants import (
    A19_CAPACITY_SIGNAL,
    A19_COVERAGE_PCT_REPORTED,
    A19_DISTINCT_SRC_REPORTED,
    A19_EXECUTION_ARTIFACT,
    A19_FINISH,
    A19_FIRST_DECODER_FAILURE,
    A19_FORENSIC_IDENTITY,
    A19_FORENSIC_RELATIVE,
    A19_HANDLE_ARTIFACT,
    A19_HTTP,
    A19_INPUT_TOKENS,
    A19_LOCAL_INPUT,
    A19_LOCK_RELATIVE,
    A19_MALFORMED_SRC,
    A19_OUTPUT_TOKENS,
    A19_PREFLIGHT_ARTIFACT,
    A19_RECORDS,
    A19_REPORT_NAME,
    A19_SIGNATURE,
    A19_STATUS_UNCHANGED,
    A19_STRUCTURED_PARSE,
    A19_THINKING,
    A19_THINKING_TOKENS,
    EXAMPLE_POLICY,
    EXAMPLE_POLICY_LABEL,
    PROTECTED_A19,
    REPORT_NAME as A20_REPORT,
    SRC_FAILURE_CLASSIFICATION,
    V3_HANDLE_ARCHITECTURE,
    VIOLATION_ARTIFACT,
    SRC_CONTRACT_ARTIFACT,
    EXAMPLE_POLICY_ARTIFACT,
    SEMANTIC_ARTIFACT,
    COVERAGE_ARTIFACT,
    FUTURE_RETRY_ARTIFACT,
)
from app.source_analysis_v3_real_win001.constants import (
    EXPECTED_A18_REQUEST_IDENTITY,
    EXPECTED_ANALYSIS_SIGNATURE as A19_EXPECTED_SIGNATURE,
    EXPECTED_FORENSIC_IDENTITY as A19_EXPECTED_FORENSIC,
    EXPECTED_LOCAL_INPUT_ESTIMATE as A19_EXPECTED_LOCAL_INPUT,
    EXPECTED_SCHEMA_HASH,
    PROTECTED_HISTORICAL as A19_PROTECTED_HISTORICAL,
    REPORT_NAME as A19_CANARY_REPORT,
)
from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.21"
MODE = "REAL_V3_SMALL_WIN001_HARDENED_RETRY"

AUTHORIZATION_SCOPE = "SMALL_V21_V3_HARDENED_WIN001_ONLY"
FORBIDDEN_WINDOW_IDS = (
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
    "WIN996",
)

PROVIDER = "anthropic"
MODEL = "claude-sonnet-5"
THINKING_CONTRACT = SELECTED_CONTRACT
THINKING_MODE = SELECTED_THINKING_MODE
EFFORT = SELECTED_EFFORT

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False

MAX_OUTPUT_TOKENS = MAX_OUTPUT_TOKENS_FROZEN
CONNECT_TIMEOUT_SECONDS = WINDOW_CONNECT_TIMEOUT_SECONDS
READ_TIMEOUT_SECONDS = WINDOW_READ_TIMEOUT_SECONDS
HISTORICAL_READ_TIMEOUT_SECONDS = 7200.0

EXPECTED_ANALYSIS_SIGNATURE = (
    "d622bd9e0e6fecd839aadd2cb4f23f4ba6475efe395cd6a1bdac97373f0e2ab2"
)
EXPECTED_FORENSIC_IDENTITY = (
    "16fd8a2468664ea2bdf382b0fe02104cae42225bce5dbcc09b8f78dc0a9451a3"
)
EXPECTED_PROMPT_SHA256 = (
    "084a1fdf7e93338de46197a0a9475951dc47d74b9a30e839c0f0016a2eba9a2e"
)
EXPECTED_PROMPT_FINGERPRINT = (
    "4d9f01cce749b0ffbc845ab79c6f7a880625c5a7accd45e6889e0b4a5cb485a3"
)
EXPECTED_SCHEMA_HASH = EXPECTED_SCHEMA_HASH
EXPECTED_WINDOW_INPUT_HASH = A7_WIN001_INPUT_HASH
EXPECTED_OWNED_SRC_COUNT = EXPECTED_OWNED_SRC_COUNT
EXPECTED_WORD_COUNT = EXPECTED_WORD_COUNT
EXPECTED_FIRST_OWNED_SRC = EXPECTED_FIRST_OWNED_SRC
EXPECTED_LAST_OWNED_SRC = EXPECTED_LAST_OWNED_SRC
EXPECTED_CLEAN_SHA = CLEAN_SHA
EXPECTED_CLEAN_FILE_SHA = CLEAN_SHA
EXPECTED_CONTEXT_COUNT = 0
EXPECTED_CONTEXT_POLICY = CANDIDATE_CONTEXT_POLICY
EXPECTED_LOCAL_INPUT_ESTIMATE = 22651

A13_SYNTHETIC_IDENTITY = A13_REQUEST_IDENTITY
A15_V2_SIGNATURE = A15_SIGNATURE
A15_COVERAGE_PCT = A15_COVERAGE_PCT
A15_DISTINCT_SRC = A15_DISTINCT_SRC
A18_REQUEST_IDENTITY = EXPECTED_A18_REQUEST_IDENTITY

A19_V3_SIGNATURE = A19_SIGNATURE
A19_V3_FORENSIC = A19_FORENSIC_IDENTITY
A19_RESULT = A19_STATUS_UNCHANGED
A19_HTTP_STATUS = A19_HTTP
A19_FINISH_REASON = A19_FINISH
A19_PARSE = A19_STRUCTURED_PARSE
A19_DECODER = "FAIL"
A19_MALFORMED_TOKEN = A19_MALFORMED_SRC
A19_VALID_CANONICAL_OCCURRENCES = 401
A19_TOTAL_SRC_OCCURRENCES = 402
A19_TOPIC = 12
A19_IDEA = 52
A19_RELATION = 21
A19_EXAMPLE = 5
A19_REFERENCE = 12
A19_UNCERTAINTY = 4
A19_ELAPSED_MS = 93608
A19_COST_DISPLAY = "0.2060880 USD"
A19_INPUT_RATIO = 2.165106
A19_PROMPT = WINDOW_ANALYSIS_PROMPT_VERSION_V13

SYNTHETIC_WORST_CASE_LOCAL_TOKENS = 12185

LOCK_NAME = "a21_real_v3_hardened_win001.lock"
CANARY_SUBDIR = "canary/v3_hardened_win001"
CANDIDATE_WINDOWS_SUBDIR = "v3_windows"
CANDIDATE_CACHE_SUBDIR = "v3_cache"

PREFLIGHT_ARTIFACT = "source_analysis_v3_hardened_win001_preflight.json"
EXECUTION_ARTIFACT = "source_analysis_v3_hardened_win001_execution.json"
SRC_ARTIFACT = "source_analysis_v3_hardened_win001_src_analysis.json"
HANDLE_ARTIFACT = "source_analysis_v3_hardened_win001_handle_analysis.json"
REVIEW_ARTIFACT = "source_analysis_v3_hardened_win001_semantic_review.json"
COMPARISON_ARTIFACT = "source_analysis_v3_hardened_win001_vs_a19.json"
REPORT_NAME = "PHASE_3B77A21_REAL_V3_SMALL_WIN001_HARDENED_RETRY_REPORT.md"

SEMANTIC_REVIEW_STATUS = "FORENSIC_SEMANTIC_REVIEW_OF_VALID_V3_WIN001_CANDIDATE"
SEMANTIC_REVIEW_INVALID = "FORENSIC_SEMANTIC_REVIEW_OF_INVALID_V3_TRANSPORT"
EXAMPLE_POLICY = EXAMPLE_POLICY
EXAMPLE_POLICY_LABEL = EXAMPLE_POLICY_LABEL

DRY_RUN_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v3_hardened_win001 "
    "pastoral_retreat_v2_validation "
    "--authorization-scope SMALL_V21_V3_HARDENED_WIN001_ONLY "
    "--window WIN001 --dry-run"
)
REAL_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v3_hardened_win001 "
    "pastoral_retreat_v2_validation "
    "--authorization-scope SMALL_V21_V3_HARDENED_WIN001_ONLY "
    "--window WIN001 --execute-real"
)

NEXT_ACTION = "HUMAN REVIEW"
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION
PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V131
TRANSPORT_VERSION = SEMANTIC_TRANSPORT_VERSION_V3

PROTECTED_HISTORICAL = A19_PROTECTED_HISTORICAL + PROTECTED_A19 + (
    f"audit/{A20_REPORT}",
    f"audit/{VIOLATION_ARTIFACT}",
    f"audit/{SRC_CONTRACT_ARTIFACT}",
    f"audit/{EXAMPLE_POLICY_ARTIFACT}",
    f"audit/{SEMANTIC_ARTIFACT}",
    f"audit/{COVERAGE_ARTIFACT}",
    f"audit/{FUTURE_RETRY_ARTIFACT}",
    f"audit/{A19_CANARY_REPORT}",
    f"audit/{A19_EXECUTION_ARTIFACT}",
    f"audit/{A19_PREFLIGHT_ARTIFACT}",
    f"audit/{A19_HANDLE_ARTIFACT}",
    A19_LOCK_RELATIVE,
    f"{A19_FORENSIC_RELATIVE}/provider_raw_response.bin",
    f"{A19_FORENSIC_RELATIVE}/provider_http_envelope.json",
)

assert EXPECTED_SCHEMA_HASH == (
    "de42ce0f3c271e67b902a94d2f528eae56f82b1a2a5740e65161987038849425"
)
assert semantic_transport_v3_fingerprint() == EXPECTED_SCHEMA_HASH
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert MAX_OUTPUT_TOKENS == 32000
assert THINKING_MODE == "disabled"
assert EFFORT is None
assert A19_EXPECTED_SIGNATURE == A19_V3_SIGNATURE
assert A19_EXPECTED_FORENSIC == A19_V3_FORENSIC
assert A19_EXPECTED_LOCAL_INPUT == A19_LOCAL_INPUT
assert EXPECTED_ANALYSIS_SIGNATURE != A19_V3_SIGNATURE
assert AUTHORIZATION_SCOPE != "SMALL_V21_V3_SYMBOLIC_WIN001_ONLY"

__all__ = [
    "A13_SYNTHETIC_IDENTITY",
    "A15_COVERAGE_PCT",
    "A15_DISTINCT_SRC",
    "A15_V2_SIGNATURE",
    "A18_REQUEST_IDENTITY",
    "A19_CAPACITY_SIGNAL",
    "A19_COST_DISPLAY",
    "A19_COVERAGE_PCT_REPORTED",
    "A19_DECODER",
    "A19_DISTINCT_SRC_REPORTED",
    "A19_ELAPSED_MS",
    "A19_EXAMPLE",
    "A19_FINISH_REASON",
    "A19_FIRST_DECODER_FAILURE",
    "A19_HTTP_STATUS",
    "A19_IDEA",
    "A19_INPUT_RATIO",
    "A19_INPUT_TOKENS",
    "A19_LOCAL_INPUT",
    "A19_MALFORMED_TOKEN",
    "A19_OUTPUT_TOKENS",
    "A19_PARSE",
    "A19_PROMPT",
    "A19_RECORDS",
    "A19_REFERENCE",
    "A19_RELATION",
    "A19_RESULT",
    "A19_THINKING",
    "A19_THINKING_TOKENS",
    "A19_TOPIC",
    "A19_TOTAL_SRC_OCCURRENCES",
    "A19_UNCERTAINTY",
    "A19_VALID_CANONICAL_OCCURRENCES",
    "A19_V3_FORENSIC",
    "A19_V3_SIGNATURE",
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "CALL1_SIGNATURE",
    "CALL2_SIGNATURE",
    "CANARY_SUBDIR",
    "CANDIDATE_CACHE_SUBDIR",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER",
    "CANDIDATE_WINDOWS_SUBDIR",
    "COMPARISON_ARTIFACT",
    "CONNECT_TIMEOUT_SECONDS",
    "DRY_RUN_COMMAND",
    "EFFORT",
    "EXAMPLE_POLICY",
    "EXAMPLE_POLICY_LABEL",
    "EXECUTION_ARTIFACT",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_ANALYSIS_SIGNATURE",
    "EXPECTED_CLEAN_FILE_SHA",
    "EXPECTED_CLEAN_SHA",
    "EXPECTED_CONTEXT_COUNT",
    "EXPECTED_CONTEXT_POLICY",
    "EXPECTED_FIRST_OWNED_SRC",
    "EXPECTED_FORENSIC_IDENTITY",
    "EXPECTED_LAST_OWNED_SRC",
    "EXPECTED_LOCAL_INPUT_ESTIMATE",
    "EXPECTED_OWNED_SRC_COUNT",
    "EXPECTED_PROMPT_FINGERPRINT",
    "EXPECTED_PROMPT_SHA256",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "EXPECTED_SCHEMA_HASH",
    "EXPECTED_WINDOW_INPUT_HASH",
    "EXPECTED_WORD_COUNT",
    "FORBIDDEN_WINDOW_IDS",
    "HANDLE_ARTIFACT",
    "HISTORICAL_READ_TIMEOUT_SECONDS",
    "LOCK_NAME",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MAX_OUTPUT_TOKENS",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "PHASE",
    "PHASE_3B_STATUS",
    "PREFLIGHT_ARTIFACT",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "READ_TIMEOUT_SECONDS",
    "REAL_COMMAND",
    "REPORT_NAME",
    "REVIEW_ARTIFACT",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SEMANTIC_REVIEW_INVALID",
    "SEMANTIC_REVIEW_STATUS",
    "SMALL_SIGNATURE",
    "SRC_ARTIFACT",
    "SRC_FAILURE_CLASSIFICATION",
    "SYNTHETIC_WORST_CASE_LOCAL_TOKENS",
    "TARGET_JSON_LOCAL_TOKENS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
    "V3_HANDLE_ARCHITECTURE",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V13",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V131",
    "WINDOW_ID",
]
