"""Constantes 3B.7.7A.17 — semantic-transport-v3. FakeAI / offline only."""

from __future__ import annotations

from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    CONSOLIDATION_RECOVERY_VERSION,
    DEFERRED_KINDS,
    HARD_CEILINGS,
    LOCAL_KINDS,
    MAX_OUTPUT_TOKENS_FROZEN,
    OVERFLOW_TOKEN,
    OVERFLOW_UNCERTAINTY_KIND,
    OVERFLOW_UNCERTAINTY_SEVERITY,
    PROJECT_NAME,
    SEMANTIC_TRANSPORT_VERSION_V2,
    SOFT_TARGETS,
    SOURCE_REFS_HARD_MAX,
    TARGET_JSON_LOCAL_TOKENS,
    TOTAL_HARD_CEILING,
    TOTAL_SOFT_TARGET,
    WINDOW_ANALYSIS_PROMPT_VERSION_V12,
    WINDOW_ANALYSIS_PROMPT_VERSION_V121,
)
from app.source_analysis_small_window_hierarchy.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.17"
MODE = "OFFLINE_LOCAL_SYMBOLIC_HANDLES_TRANSPORT_REDESIGN"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
WIN001_RETRY_AUTHORIZED = False
REAL_PROVIDER_CALL_AUTHORIZED_NEXT = False

WINDOW_ANALYSIS_PROMPT_VERSION_V13 = "window-analysis-1.3"
WINDOW_ANALYSIS_PROMPT_VERSION_V131 = "window-analysis-1.3.1"
WINDOW_ANALYSIS_PROMPT_VERSION_V132 = "window-analysis-1.3.2"
WINDOW_ANALYSIS_PROMPT_VERSION_V140 = "window-analysis-1.4.0"
SEMANTIC_TRANSPORT_VERSION_V3 = "semantic-transport-v3"
SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE = "semantic-transport-v3.1-local-lite"
SRC_REFERENCE_POLICY_VERSION_10_STRICT = "src-reference-policy-1.0-strict"
SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION = (
    "src-reference-policy-1.1-narrow-canonicalization"
)
HISTORICAL_SRC_REFERENCE_POLICY_VERSION = SRC_REFERENCE_POLICY_VERSION_10_STRICT
CURRENT_SRC_REFERENCE_POLICY_VERSION = (
    SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION
)
CANDIDATE_V3_PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V13
CANDIDATE_V3_PROMPT_VERSION_V131 = WINDOW_ANALYSIS_PROMPT_VERSION_V131
CANDIDATE_V3_PROMPT_VERSION_V132 = WINDOW_ANALYSIS_PROMPT_VERSION_V132
CANDIDATE_V31_PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V140
IDEA_METADATA_LAYOUT_V3 = "v3"
IDEA_METADATA_LAYOUT_LOCAL_LITE = "v3.1-local-lite"
LOCAL_LITE_IDEA_METADATA_FIELDS = ("importance",)

SELECTED_ARCHITECTURE = "LOCAL_SYMBOLIC_HANDLES"
HANDLE_INDEX_BASE = 1
HANDLE_OWNER_KINDS = ("TOPIC", "IDEA")
HANDLE_LINK_TOPIC_KINDS = ("IDEA",)
HANDLE_LINK_IDEA_KINDS = ("RELATION", "EXAMPLE")
NON_OWNER_KINDS = ("RELATION", "EXAMPLE", "REFERENCE", "UNCERTAINTY")

FORWARD_REFERENCES = "ALLOWED"
GAP_FREE_NUMBERING = "RECOMMENDED_NOT_REQUIRED"
GLOBAL_NUMERIC_LINK_INDEXES = "REMOVED"

NEXT_PHASE = "3B.7.7A.18_SYMBOLIC_HANDLE_TINY_GRAMMAR_CANARY"
NEXT_PHASE_LABEL = (
    "3B.7.7A.18 — SYMBOLIC-HANDLE TINY GRAMMAR CANARY "
    "(ONE tiny synthetic Anthropic call maximum; no pastoral; no WIN001)"
)
NEXT_ACTION = "HUMAN REVIEW"
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION

__all__ = [
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER_VERSION",
    "CANDIDATE_V3_PROMPT_VERSION",
    "CANDIDATE_V3_PROMPT_VERSION_V131",
    "CANDIDATE_V3_PROMPT_VERSION_V132",
    "CANDIDATE_V31_PROMPT_VERSION",
    "IDEA_METADATA_LAYOUT_LOCAL_LITE",
    "IDEA_METADATA_LAYOUT_V3",
    "LOCAL_LITE_IDEA_METADATA_FIELDS",
    "CONSOLIDATION_RECOVERY_VERSION",
    "CURRENT_SRC_REFERENCE_POLICY_VERSION",
    "DEFERRED_KINDS",
    "HISTORICAL_SRC_REFERENCE_POLICY_VERSION",
    "FORWARD_REFERENCES",
    "GAP_FREE_NUMBERING",
    "GLOBAL_NUMERIC_LINK_INDEXES",
    "HANDLE_INDEX_BASE",
    "HANDLE_LINK_IDEA_KINDS",
    "HANDLE_LINK_TOPIC_KINDS",
    "HANDLE_OWNER_KINDS",
    "HARD_CEILINGS",
    "LOCAL_KINDS",
    "MAX_OUTPUT_TOKENS_FROZEN",
    "MODE",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "NON_OWNER_KINDS",
    "OVERFLOW_TOKEN",
    "OVERFLOW_UNCERTAINTY_KIND",
    "OVERFLOW_UNCERTAINTY_SEVERITY",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "REAL_PROVIDER_CALL_AUTHORIZED_NEXT",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SEMANTIC_TRANSPORT_VERSION_V2",
    "SEMANTIC_TRANSPORT_VERSION_V3",
    "SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE",
    "SOFT_TARGETS",
    "SOURCE_REFS_HARD_MAX",
    "SRC_REFERENCE_POLICY_VERSION_10_STRICT",
    "SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION",
    "TARGET_JSON_LOCAL_TOKENS",
    "TOTAL_HARD_CEILING",
    "TOTAL_SOFT_TARGET",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V12",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V121",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V13",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V131",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V132",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V140",
    "WIN001_RETRY_AUTHORIZED",
]
