"""
Phase 4B.2.17 — CH012 faithful real pilot generation.

NEW explicit one-shot authorization. One Anthropic claude-sonnet-5 call.
Chapter CH012 only. Cost cap 0.15 USD. Zero retries. Zero fallbacks.
Uses book-generator-faithful-restatement-1.0-candidate for this isolated
execution only. Does not replace historical Book Generator prompts.
Does not publish book.json. Does not write the production cache.
Does not call Terra. Does not generate any other chapter.
"""

from __future__ import annotations

from decimal import Decimal

from app.ai.thinking import THINKING_MODE_DISABLED
from app.book_editorial_alignment_4b216.constants import (
    COVERAGE_CONTRACT_VERSION,
    EDITORIAL_POLICY_VERSION,
    FAITHFUL_PROMPT_VERSION,
    HISTORICAL_GENERATOR_PROMPT,
    HISTORICAL_GENERATOR_PROMPT_V10,
    HISTORICAL_SEMANTIC_CONTRACT,
    HUMAN_RESOLUTION_VERSION,
    THEMATIC_RULES_VERSION,
)
from app.book_generation.constants import (
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION_V10,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    HARD_MAX_OUTPUT_TOKENS,
    MIN_MAX_OUTPUT_TOKENS,
    MODEL,
    PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_semantic_gate_4b215.constants import (
    HISTORICAL_4B210_STATUS,
    HISTORICAL_4B211_STATUS,
    HISTORICAL_4B212_STATUS,
    HISTORICAL_4B213_STATUS,
    HISTORICAL_4B214_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
)
from app.book_semantic_gate_4b23.constants import EXPECTED_CLEAN_TRANSCRIPT
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE

PHASE = "4B.2.17"
PHASE_NAME = "CH012_FAITHFUL_REAL_PILOT_GENERATION"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_GENERATION_4B217_CH012_FAITHFUL_REAL_PILOT_GENERATION_ONLY"
)

AUTHORIZED_ANTHROPIC_CALLS = 1
AUTHORIZED_SONNET_CALLS = 1
AUTHORIZED_REMOTE_INVOCATIONS = 1
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_TERRA_CALLS = 0
MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_HTTP_REQUESTS = 1
MAX_EXECUTION_ATTEMPTS = 1
RETRIES = 0
FALLBACKS = 0
SDK_MAX_RETRIES = 0

PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
OPENAI_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = True
REAL_CHAPTER_GENERATION_AUTHORIZED = True
REAL_PROVIDERS_ENABLED = True
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
FAITHFUL_PROMPT_ACTIVATED_IN_PRODUCTION = False
EDITORIAL_POLICY_ACTIVATED_IN_PRODUCTION = False
COVERAGE_CONTROL_ACTIVATED_IN_PRODUCTION = False
SEMANTIC_GATE_202_ENABLED = False
BOOK_JSON_PUBLICATION = False

TARGET_CHAPTER_ID = "CH012"
TARGET_CHAPTER_TITLE = "Prayer Corrected"
EXPECTED_SECTION_IDS = ("SEC047", "SEC048", "SEC049", "SEC050")
EXPECTED_IDEA_COUNT = 11
EXPECTED_SECTION_COUNT = 4
EXPECTED_UNCERTAINTY_ID = "UNC029"

PROMPT_VERSION = FAITHFUL_PROMPT_VERSION
TRANSPORT_VERSION = BOOK_GENERATION_TRANSPORT_VERSION
VALIDATOR_VERSION = BOOK_GENERATOR_VALIDATOR_VERSION
HISTORICAL_PROMPT = HISTORICAL_GENERATOR_PROMPT
HISTORICAL_PROMPT_V10 = HISTORICAL_GENERATOR_PROMPT_V10

assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert PROMPT_VERSION == "book-generator-faithful-restatement-1.0-candidate"
assert HISTORICAL_PROMPT == BOOK_GENERATOR_PROMPT_VERSION == "book-generator-1.0.1"
assert HISTORICAL_PROMPT_V10 == BOOK_GENERATOR_PROMPT_VERSION_V10 == "book-generator-1.0"
assert TRANSPORT_VERSION == "book-generation-transport-1.0"
assert EDITORIAL_POLICY_VERSION == "faithful-teaching-book-editorial-policy-1.0-candidate"
assert COVERAGE_CONTRACT_VERSION == "source-coverage-control-4b216-candidate"
assert THEMATIC_RULES_VERSION == "thematic-reorganization-rules-4b216-candidate"
assert HUMAN_RESOLUTION_VERSION == "human-resolution-protocol-4b216-candidate"
assert HISTORICAL_SEMANTIC_CONTRACT == "book-semantic-validator-2.0.2-candidate"

THINKING_MODE = THINKING_MODE_DISABLED
assert THINKING_MODE == "disabled"

BUDGET_CAP_USD = Decimal("0.15")
BUDGET_CAP_DISPLAY = "0.15 USD"
MAX_REAL_CALL_COST_USD = BUDGET_CAP_USD
PRICING_EFFECTIVE_DATE = "2026-09-18"
SONNET_INPUT_COST_PER_1M = Decimal("2.00")
SONNET_OUTPUT_COST_PER_1M = Decimal("10.00")
HISTORICAL_CH012_CENTRAL_USD = Decimal("0.042496")
HISTORICAL_CH012_INPUT_PESSIMISTIC = 9223
HISTORICAL_CH012_EXPECTED_OUTPUT = 2405

TERRA_INPUT_COST_PER_1M = Decimal("2.00")
TERRA_OUTPUT_COST_PER_1M = Decimal("12.00")
TERRA_H01_ANALOG_USD = Decimal("0.006286")

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 1800.0

STAGE_CANARY = "book_generation_4b217_ch012"
CANARY_WINDOW_ID = "CANARY_BG4B217"
LOCK_NAME = "ch012_real_call.lock"
CODE_VERSION = "app.book_generation_4b217"

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_TRANSCRIPT = EXPECTED_CLEAN_TRANSCRIPT

assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert AUTHORIZED_ANTHROPIC_CALLS == 1
assert AUTHORIZED_OPENAI_CALLS == 0
assert AUTHORIZED_TERRA_CALLS == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert PUBLICATION_AUTHORIZED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert FAITHFUL_PROMPT_ACTIVATED_IN_PRODUCTION is False
assert TARGET_CHAPTER_ID == "CH012"
assert BUDGET_CAP_USD == Decimal("0.15")
assert MIN_MAX_OUTPUT_TOKENS == 4096
assert HARD_MAX_OUTPUT_TOKENS == 32000
assert CANONICAL_PYTHON.endswith("python.exe")

HISTORICAL_4B215_STATUS = "PARTIAL"
HISTORICAL_4B216_STATUS = "PASS"
HISTORICAL_4B217_DOES_NOT_REQUALIFY = True

AUDIT_DIRNAME = "book_generation_4b217_ch012"
AUDIT_REAL_PARENT = "real"
AUDIT_PREFLIGHT = "preflight.json"
AUDIT_HASHES_PRE = "canonical_hashes_pre.json"
AUDIT_POLICY = "editorial_policy_snapshot.json"
AUDIT_PROMPT = "generator_prompt_snapshot.json"
AUDIT_CONTEXT = "chapter_context_manifest.json"
AUDIT_HYDRATED = "hydrated_source_manifest.json"
AUDIT_COST = "cost_preflight.json"
AUDIT_AUTHORIZATION = "provider_call_authorization.json"
AUDIT_REQUEST_HASH = "provider_request_hash.json"
AUDIT_RESPONSE = "provider_response_metadata.json"
AUDIT_CANDIDATE_JSON = "chapter_candidate.json"
AUDIT_CANDIDATE_MD = "chapter_candidate.md"
AUDIT_STRUCTURAL = "structural_validation.json"
AUDIT_COVERAGE = "source_coverage.json"
AUDIT_RISKS = "editorial_risk_flags.json"
AUDIT_HASHES_POST = "canonical_hashes_post.json"
AUDIT_TESTS = "regression_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_LOCK = LOCK_NAME
REPORT_NAME = "PHASE_4B217_CH012_FAITHFUL_REAL_PILOT_GENERATION_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_FULL_BOOK_GENERATION = False
SEMANTIC_FIDELITY_VALIDATED = False

FORBIDDEN_PROMPT_CLAUSES = (
    "High stylistic freedom",
    "Stylistic expansion is allowed",
)

__all__ = [
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "BUDGET_CAP_USD",
    "CANONICAL_PYTHON",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_IDEA_COUNT",
    "EXPECTED_SECTION_IDS",
    "EXPECTED_SOURCE_MAP",
    "EXPECTED_TRANSCRIPT",
    "MODEL",
    "PHASE",
    "PROMPT_VERSION",
    "PROVIDER",
    "TARGET_CHAPTER_ID",
]
