"""Phase 4B.2.7 — one real Terra compact single-case canary."""

from app.book_semantic_gate_4b27.constants import (
    AUTHORIZED_REMOTE_TERRA_INVOCATIONS,
    AUTHORIZED_SONNET_CALLS,
    HISTORICAL_4B261_STATUS,
    HISTORICAL_4B262_STATUS,
    HISTORICAL_4B26_STATUS,
    PHASE,
)

assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert HISTORICAL_4B262_STATUS == "PASS"

__all__ = [
    "PHASE",
    "AUTHORIZED_REMOTE_TERRA_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "HISTORICAL_4B26_STATUS",
    "HISTORICAL_4B261_STATUS",
    "HISTORICAL_4B262_STATUS",
]
