"""
Phase 4B.2.7 — One real Terra compact single-case canary.

NEW explicit authorization. MAX_REMOTE_TERRA_INVOCATIONS = 1.
Does not reuse consumed 4B.2.4 / 4B.2.5 / 4B.2.6 slots.
Historical 4B.2.6 remains FAIL. 4B.2.6.1 remains PASS. 4B.2.6.2 remains PASS.
Contract 1.1-candidate is not promoted. Contract 1.0 is not modified.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
    VERDICT_FAIL,
    VERDICT_PASS,
    VERDICT_REVIEW,
)
from app.book_semantic_gate_4b24.constants import (
    EXPECTED_BENCHMARK_FILE_SHA256,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    EXPECTED_REQUEST_SHA256 as EXPECTED_REQUEST_SHA256_4B26,
    HISTORICAL_4B21_STATUS,
    HISTORICAL_4B22_STATUS,
    HISTORICAL_4B23_STATUS,
    HISTORICAL_4B241_STATUS,
    HISTORICAL_4B24_STATUS,
    HISTORICAL_4B251_STATUS,
    HISTORICAL_4B25_STATUS,
    HISTORICAL_4B2_STATUS,
    SEMANTIC_TOKEN_BUDGET,
)
from app.book_semantic_gate_4b261.constants import (
    CANDIDATE_PROMPT_VERSION,
    CANDIDATE_TRANSPORT_VERSION,
    HISTORICAL_4B26_STATUS,
)
from app.book_semantic_gate_4b262.constants import (
    HISTORICAL_4B261_STATUS,
    SELECTED_CASE_HANDLE,
    SELECTED_CASE_HUMAN_LABEL,
    SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY,
    SELECTED_CASE_ID,
    SELECTED_CASE_ROLE,
)

PHASE = "4B.2.7"
PHASE_NAME = "ONE_REAL_TERRA_COMPACT_SINGLE_CASE_CANARY"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B27_ONE_REAL_TERRA_COMPACT_SINGLE_CASE_CANARY_ONLY"
)
AUTHORIZED_REMOTE_TERRA_INVOCATIONS = 1
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
MAX_ENGINE_GENERATE = 1
MAX_REMOTE_INVOCATIONS = 1
RETRIES = 0
FALLBACKS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = True
SDK_MAX_RETRIES = 0

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
STAGE_CANARY = "book_semantic_validation_canary_4b27"
PROMPT_VERSION = CANDIDATE_PROMPT_VERSION
TRANSPORT_VERSION = CANDIDATE_TRANSPORT_VERSION
PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"
TOKEN_FIELD = "max_completion_tokens"
PRODUCTION_SDK_METHOD = "client.chat.completions.create"

EXPECTED_REQUEST_SHA256 = (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
EXPECTED_EVIDENCE_HANDLES = (
    "IDEA224",
    "SRC006149",
    "SRC006180",
    "SRC006182",
    "SRC006183",
    "SRC006187",
)

HISTORICAL_4B262_STATUS = "PASS"

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert PROMPT_VERSION == "book-semantic-validator-1.1-candidate"
assert TRANSPORT_VERSION == "book-semantic-validation-transport-1.1-candidate"
assert PROMPT_VERSION_HISTORICAL == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION_HISTORICAL == "book-semantic-validation-transport-1.0"
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
assert TOKEN_FIELD == "max_completion_tokens"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert SELECTED_CASE_HANDLE == "h01"
assert SELECTED_CASE_ID == "4b22_p2_supported"
assert SELECTED_CASE_ROLE == "positive"
assert SELECTED_CASE_HUMAN_LABEL == CLASS_SUPPORTED
assert EXPECTED_REQUEST_SHA256_4B26 == (
    "8a92848e412763f0e67468245f9c007ee9537ffa4f2f5469af9a6934d9ebeb31"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B2_STATUS == "FAIL"
assert HISTORICAL_4B21_STATUS == "PASS"
assert HISTORICAL_4B22_STATUS == "PARTIAL"
assert HISTORICAL_4B23_STATUS == "PASS"
assert HISTORICAL_4B24_STATUS == "FAIL"
assert HISTORICAL_4B241_STATUS == "PASS"
assert HISTORICAL_4B25_STATUS == "FAIL"
assert HISTORICAL_4B251_STATUS == "PASS"
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert HISTORICAL_4B262_STATUS == "PASS"
assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert SDK_MAX_RETRIES == 0
assert PUBLICATION_AUTHORIZED is False

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 300.0
CANARY_WINDOW_ID = "book-semantic-gate-4b27"

AUDIT_DIRNAME = "book_semantic_gate_4b27"
AUDIT_REAL_PARENT = "real"
AUDIT_PRECALL = "book_semantic_gate_4b27_precall.json"
AUDIT_RUNTIME = "book_semantic_gate_4b27_runtime.json"
AUDIT_REQUEST = "book_semantic_gate_4b27_request_identity.json"
AUDIT_SERIALIZATION = "book_semantic_gate_4b27_sdk_serialization.json"
AUDIT_ACCOUNTING = "book_semantic_gate_4b27_call_accounting.json"
AUDIT_PROVIDER = "book_semantic_gate_4b27_provider_evidence.json"
AUDIT_USAGE = "book_semantic_gate_4b27_token_usage.json"
AUDIT_VALIDATION = "book_semantic_gate_4b27_response_validation.json"
AUDIT_SEMANTIC = "book_semantic_gate_4b27_semantic_review.json"
AUDIT_REPLAY = "book_semantic_gate_4b27_replay.json"
AUDIT_TESTS = "book_semantic_gate_4b27_tests.json"
AUDIT_COST = "book_semantic_gate_4b27_cost.json"
AUDIT_READINESS = "book_semantic_gate_4b27_readiness.json"
AUDIT_RAW_RESPONSE = "book_semantic_gate_4b27_raw_structured_response.json"
AUDIT_RAW_TEXT = "book_semantic_gate_4b27_raw_provider_text.txt"
AUDIT_LOCK = "book_semantic_gate_4b27_real_call.lock"
AUDIT_INDEX = "book_semantic_gate_4b27_index.json"
REPORT_NAME = "PHASE_4B27_ONE_REAL_TERRA_COMPACT_SINGLE_CASE_CANARY_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "AUDIT_ACCOUNTING",
    "AUDIT_COST",
    "AUDIT_DIRNAME",
    "AUDIT_INDEX",
    "AUDIT_LOCK",
    "AUDIT_PRECALL",
    "AUDIT_PROVIDER",
    "AUDIT_RAW_RESPONSE",
    "AUDIT_RAW_TEXT",
    "AUDIT_READINESS",
    "AUDIT_REAL_PARENT",
    "AUDIT_REPLAY",
    "AUDIT_REQUEST",
    "AUDIT_RUNTIME",
    "AUDIT_SEMANTIC",
    "AUDIT_SERIALIZATION",
    "AUDIT_TESTS",
    "AUDIT_USAGE",
    "AUDIT_VALIDATION",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_REMOTE_TERRA_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "CANARY_WINDOW_ID",
    "CANDIDATE_PROMPT_VERSION",
    "CANDIDATE_TRANSPORT_VERSION",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CONNECT_TIMEOUT_SECONDS",
    "CONSERVATIVE_MAX_OUTPUT_TOKENS",
    "EXPECTED_BENCHMARK_FILE_SHA256",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_EVIDENCE_HANDLES",
    "EXPECTED_OPENAI_SDK_VERSION",
    "EXPECTED_PYTHON_VERSION",
    "EXPECTED_REQUEST_SHA256",
    "EXPECTED_REQUEST_SHA256_4B26",
    "EXPECTED_SOURCE_MAP",
    "FALLBACKS",
    "HISTORICAL_4B21_STATUS",
    "HISTORICAL_4B22_STATUS",
    "HISTORICAL_4B23_STATUS",
    "HISTORICAL_4B241_STATUS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B251_STATUS",
    "HISTORICAL_4B25_STATUS",
    "HISTORICAL_4B261_STATUS",
    "HISTORICAL_4B262_STATUS",
    "HISTORICAL_4B26_STATUS",
    "HISTORICAL_4B2_STATUS",
    "MAX_ENGINE_GENERATE",
    "MAX_REMOTE_INVOCATIONS",
    "MODEL",
    "NEXT_ACTION",
    "OUTPUT_MODE",
    "PHASE",
    "PHASE_NAME",
    "PRODUCTION_ENDPOINT",
    "PRODUCTION_SDK_METHOD",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROMPT_VERSION_HISTORICAL",
    "PROVIDER",
    "PUBLICATION_AUTHORIZED",
    "READ_TIMEOUT_SECONDS",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "REPORT_NAME",
    "RETRIES",
    "SCORED_CASE_ORDER",
    "SDK_MAX_RETRIES",
    "SELECTED_CASE_HANDLE",
    "SELECTED_CASE_HUMAN_LABEL",
    "SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY",
    "SELECTED_CASE_ID",
    "SELECTED_CASE_ROLE",
    "SEMANTIC_TOKEN_BUDGET",
    "STAGE_CANARY",
    "TEMPERATURE_POLICY",
    "TERRA_EXECUTION_AUTHORIZED",
    "THINKING_MODE",
    "TOKEN_FIELD",
    "TRANSPORT_VERSION",
    "TRANSPORT_VERSION_HISTORICAL",
    "VERDICT_FAIL",
    "VERDICT_PASS",
    "VERDICT_REVIEW",
]
