"""Constantes 3B.7.7A.49 — publication contrôlée du SourceMap A.48. 0 provider."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis_local_v2.constants import (
    GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC,
)
from app.source_analysis_local_v3.constants import (
    SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE,
    SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION,
    WINDOW_ANALYSIS_PROMPT_VERSION_V140,
)
from app.source_analysis_v31_global_a47_contract_forensics.constants import (
    A34_STATUS_PRESERVED,
    A35_STATUS_PRESERVED,
    A36_STATUS_PRESERVED,
    A37_STATUS_PRESERVED,
    A38_STATUS_PRESERVED,
    A39_STATUS_PRESERVED,
    A40_STATUS_PRESERVED,
    A41_STATUS_PRESERVED,
    A42_STATUS_PRESERVED,
    A43_STATUS_PRESERVED,
    A44_STATUS_PRESERVED,
    A45_ESTIMATED_INPUT,
    A45_EXPECTED_OUTPUT,
    A45_EXPECTED_OUTPUT_ERROR_ABS,
    A45_EXPECTED_OUTPUT_ERROR_PERCENT,
    A45_INPUT_ESTIMATE_ERROR_ABS,
    A45_INPUT_ESTIMATE_ERROR_PERCENT,
    A45_NORMALIZED_INPUT_HASH,
    A45_REQUEST_HASH,
    A45_STATUS_PRESERVED,
    A46_CANARY_SUBDIR,
    A46_COST_USD,
    A46_DROP,
    A46_ELAPSED_MS,
    A46_ELAPSED_SECONDS,
    A46_FINISH_REASON,
    A46_HTTP_STATUS,
    A46_IDEA_ACCOUNTABILITY,
    A46_INPUT_TOKENS,
    A46_INTENT_LENGTH,
    A46_KEEP,
    A46_MERGE,
    A46_NORMALIZED_INPUT_HASH,
    A46_OUTPUT_TOKENS,
    A46_OUTPUT_UTILIZATION_PERCENT,
    A46_PROTECTED_HISTORICAL,
    A46_RAW_RESPONSE_ARTIFACT,
    A46_RAW_RESPONSE_HASH,
    A46_RAW_TEXT_BYTES,
    A46_RAW_TEXT_CHARS,
    A46_REPORT_NAME,
    A46_REQUEST_HASH,
    A46_REQUEST_ID,
    A46_RESPONSE_IDENTITY_ARTIFACT,
    A46_STATUS_PRESERVED,
    A46_THINKING_TOKENS,
    EXPECTED_IDEA,
    FROZEN_PROMPT_VERSION,
    FROZEN_TRANSPORT_VERSION,
    HISTORICAL_240_ORIGIN,
    HISTORICAL_INTENT_LIMIT,
    LIMIT_JUSTIFICATION,
    LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
    LOCAL_WINDOW_INTENT_LIMIT,
    MODEL,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PROJECT_NAME,
    PROVIDER,
    RELATION_QUALITY_TECHNICAL_DEBT,
    REPORT_NAME as A47_REPORT_NAME,
    SCHEMA_ADAPTED_BYTES,
    SCHEMA_HASH,
    SCHEMA_RAW_BYTES,
    SELECTED_INTENT_LIMIT,
    TEXT_LIMITS,
    THEME_LIMIT,
    THINKING_MODE,
)
from app.source_analysis_v31_global_a48_offline_revalidation.constants import (
    A47_STATUS_PRESERVED,
    A48_COST_USD,
    ARCHITECTURE_ARTIFACT as A48_ARCHITECTURE_ARTIFACT,
    CANDIDATE_SOURCE_MAP_NAME as A48_CANDIDATE_SOURCE_MAP_NAME,
    CONTRACT_ARTIFACT as A48_CONTRACT_ARTIFACT,
    PUBLICATION_ARTIFACT as A48_PUBLICATION_ARTIFACT,
    READINESS_ARTIFACT as A48_READINESS_ARTIFACT,
    REPORT_NAME as A48_REPORT_NAME,
    SEMANTIC_ARTIFACT as A48_SEMANTIC_ARTIFACT,
    STRUCTURAL_ARTIFACT as A48_STRUCTURAL_ARTIFACT,
    TECHNICAL_ARTIFACT as A48_TECHNICAL_ARTIFACT,
)
from app.source_analysis_v31_global_grammar_canary.constants import FROZEN_PLANNER
from app.source_analysis_v31_global_output_architecture.constants import (
    A39_INTENT_COMPACTNESS_BOUND,
    GLOBAL_INTENT_MAX_CHARS,
)
from app.source_analysis_v31_global_reuse_output.constants import FUTURE_PROMPT_VERSION
from app.source_analysis_v31_global_v30_real_canary.constants import (
    CANDIDATE_SOURCE_MAP_NAME as A46_CANDIDATE_SOURCE_MAP_NAME,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.49"
MODE = "CONTROLLED_CANONICAL_SOURCE_MAP_PUBLICATION"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_ANTHROPIC_CALLS = 0
REAL_OPENAI_CALLS = 0
REAL_CONSOLIDATION_CALLS = 0
GRAMMAR_CANARY_CALLS = 0
CONSOLIDATION_AUTHORIZED = False
SOURCE_MAP_PUBLICATION_AUTHORIZED = True

A48_STATUS_PRESERVED = "PASS"
assert A34_STATUS_PRESERVED == "PASS"
assert A35_STATUS_PRESERVED == "FAIL"
assert A36_STATUS_PRESERVED == "PASS"
assert A37_STATUS_PRESERVED == "PASS"
assert A38_STATUS_PRESERVED == "FAIL"
assert A39_STATUS_PRESERVED == "PASS"
assert A40_STATUS_PRESERVED == "FAIL"
assert A41_STATUS_PRESERVED == "PASS"
assert A42_STATUS_PRESERVED == "PASS"
assert A43_STATUS_PRESERVED == "PASS"
assert A44_STATUS_PRESERVED == "PASS"
assert A45_STATUS_PRESERVED == "PASS"
assert A46_STATUS_PRESERVED == "FAIL"
assert A47_STATUS_PRESERVED == "PASS"
assert A48_STATUS_PRESERVED == "PASS"
assert FROZEN_PROMPT_VERSION == "global-consolidation-3.0"
assert FUTURE_PROMPT_VERSION == "global-consolidation-3.0.1"
assert FROZEN_TRANSPORT_VERSION == "global-consolidation-transport-3.0"
assert SCHEMA_RAW_BYTES == 1583
assert SCHEMA_ADAPTED_BYTES == 1831
assert SCHEMA_HASH == (
    "822397b642b0e1724e29686962caab32bff63effe18f05bff26b404bad9b2a90"
)
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert THINKING_MODE == "disabled"
assert GLOBAL_INTENT_MAX_CHARS == SELECTED_INTENT_LIMIT == 320
assert TEXT_LIMITS["intent"] == GLOBAL_INTENT_MAX_CHARS
assert A39_INTENT_COMPACTNESS_BOUND == HISTORICAL_INTENT_LIMIT == 240
assert LOCAL_WINDOW_INTENT_LIMIT == 280
assert THEME_LIMIT == 360
assert A46_INTENT_LENGTH == 290
assert A45_EXPECTED_OUTPUT_ERROR_ABS == 205
assert A45_EXPECTED_OUTPUT_ERROR_PERCENT == 1.56
assert EXPECTED_IDEA == A46_KEEP == 286
assert A46_MERGE == 0
assert A46_DROP == 0
assert FROZEN_PLANNER == "window-planner-v2.1-small"
assert WINDOW_ANALYSIS_PROMPT_VERSION_V140 == "window-analysis-1.4.0"
assert SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE == "semantic-transport-v3.1-local-lite"
assert GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC == (
    "window-granularity-1.2-kind-specific"
)
assert SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION == (
    "src-reference-policy-1.1-narrow-canonicalization"
)
assert LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN == "YES"
assert RELATION_QUALITY_TECHNICAL_DEBT == "YES"

A49_COST_USD = 0.0
HISTORICAL_PROMPT = FROZEN_PROMPT_VERSION
FUTURE_PROMPT = FUTURE_PROMPT_VERSION
TRANSPORT_VERSION = FROZEN_TRANSPORT_VERSION
HISTORICAL_REQUEST_HASH = A45_REQUEST_HASH
assert HISTORICAL_REQUEST_HASH.startswith("fbffc38c")

FROZEN_LOCAL_ARCHITECTURE = {
    "planner": FROZEN_PLANNER,
    "window_analysis": WINDOW_ANALYSIS_PROMPT_VERSION_V140,
    "transport": SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE,
    "granularity": GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC,
    "src_policy": SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION,
}

PUBLICATION_MODE_NEW = "NEW_ATOMIC_WRITE"
PUBLICATION_MODE_IDENTICAL = "ALREADY_PUBLISHED_IDENTICAL"
PUBLICATION_MODE_CONFLICT = "BLOCKED_PUBLICATION_CONFLICT"
PUBLICATION_MODE_BLOCKED = "BLOCKED"
BYTE_IDENTITY_EXACT = "PUBLISHED_BYTES = VALIDATED_CANDIDATE_BYTES"
A41_FULL_SUITE_NOTE = (
    "If the full historical suite is too slow, A.41 remaining-failures "
    "plus current changed-area suites are the established substitute."
)

PREPUBLICATION_ARTIFACT = "global_consolidation_a49_prepublication_gate.json"
CANDIDATE_IDENTITY_ARTIFACT = "global_consolidation_a49_candidate_identity.json"
PUBLICATION_ARTIFACT = "global_consolidation_a49_publication.json"
RELOAD_ARTIFACT = "global_consolidation_a49_published_reload_validation.json"
FREEZE_ARTIFACT = "global_consolidation_a49_phase3b_freeze.json"
READINESS_ARTIFACT = "global_consolidation_post_a49_readiness.json"
TEST_DELTA_ARTIFACT = "source_analysis_a49_test_delta.json"
BASELINE_ARTIFACT = "source_analysis_a49_test_baseline.json"
REPORT_NAME = "PHASE_3B77A49_SOURCE_MAP_PUBLICATION_AND_PHASE3B_FREEZE_REPORT.md"

PROTECTED_HISTORICAL = A46_PROTECTED_HISTORICAL + (
    f"audit/{A46_REPORT_NAME}",
    f"audit/{A46_CANARY_SUBDIR}/{A46_RAW_RESPONSE_ARTIFACT}",
    f"audit/{A46_CANARY_SUBDIR}/{A46_RESPONSE_IDENTITY_ARTIFACT}",
    f"audit/{A46_CANARY_SUBDIR}/{A46_CANDIDATE_SOURCE_MAP_NAME}",
    f"audit/{A46_CANARY_SUBDIR}/{A48_CANDIDATE_SOURCE_MAP_NAME}",
    f"audit/{A47_REPORT_NAME}",
    f"audit/{A48_REPORT_NAME}",
    f"audit/{A48_PUBLICATION_ARTIFACT}",
    f"audit/{A48_SEMANTIC_ARTIFACT}",
    f"audit/{A48_TECHNICAL_ARTIFACT}",
    f"audit/{A48_STRUCTURAL_ARTIFACT}",
    f"audit/{A48_CONTRACT_ARTIFACT}",
    f"audit/{A48_ARCHITECTURE_ARTIFACT}",
    f"audit/{A48_READINESS_ARTIFACT}",
)

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_a49_source_map_publication.py",
    "app/tests/test_source_analysis_v31_global_a49_source_map_publication_audit.py",
)
BROADER_SLICE_TEST_PATHS = FOCUSED_TEST_PATHS + (
    "app/tests/test_source_map_validator.py",
    "app/tests/test_source_map_normalization.py",
    "app/tests/test_source_map_models.py",
    "app/tests/test_source_analysis_compact_schema.py",
)
CANONICAL_VALIDATOR_TEST_PATHS = (
    "app/tests/test_source_map_validator.py",
    "app/tests/test_source_map_normalization.py",
    "app/tests/test_source_map_models.py",
    "app/tests/test_source_analysis_compact_schema.py",
)

NEXT_ACTION = "HUMAN REVIEW"
EDITORIAL_PLANNER_FORBIDDEN = True

assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert REAL_ANTHROPIC_CALLS == 0
assert REAL_OPENAI_CALLS == 0
assert SOURCE_MAP_PUBLICATION_AUTHORIZED is True
assert A46_STATUS_PRESERVED == "FAIL"
assert EDITORIAL_PLANNER_FORBIDDEN is True
assert source_map_path(PROJECT_NAME).name == "source_map.json"

__all__ = [
    "A34_STATUS_PRESERVED",
    "A35_STATUS_PRESERVED",
    "A36_STATUS_PRESERVED",
    "A37_STATUS_PRESERVED",
    "A38_STATUS_PRESERVED",
    "A39_INTENT_COMPACTNESS_BOUND",
    "A39_STATUS_PRESERVED",
    "A40_STATUS_PRESERVED",
    "A41_FULL_SUITE_NOTE",
    "A41_STATUS_PRESERVED",
    "A42_STATUS_PRESERVED",
    "A43_STATUS_PRESERVED",
    "A44_STATUS_PRESERVED",
    "A45_ESTIMATED_INPUT",
    "A45_EXPECTED_OUTPUT",
    "A45_EXPECTED_OUTPUT_ERROR_ABS",
    "A45_EXPECTED_OUTPUT_ERROR_PERCENT",
    "A45_INPUT_ESTIMATE_ERROR_ABS",
    "A45_INPUT_ESTIMATE_ERROR_PERCENT",
    "A45_NORMALIZED_INPUT_HASH",
    "A45_REQUEST_HASH",
    "A45_STATUS_PRESERVED",
    "A46_CANARY_SUBDIR",
    "A46_CANDIDATE_SOURCE_MAP_NAME",
    "A46_COST_USD",
    "A46_DROP",
    "A46_ELAPSED_MS",
    "A46_ELAPSED_SECONDS",
    "A46_FINISH_REASON",
    "A46_HTTP_STATUS",
    "A46_IDEA_ACCOUNTABILITY",
    "A46_INPUT_TOKENS",
    "A46_INTENT_LENGTH",
    "A46_KEEP",
    "A46_MERGE",
    "A46_NORMALIZED_INPUT_HASH",
    "A46_OUTPUT_TOKENS",
    "A46_OUTPUT_UTILIZATION_PERCENT",
    "A46_PROTECTED_HISTORICAL",
    "A46_RAW_RESPONSE_ARTIFACT",
    "A46_RAW_RESPONSE_HASH",
    "A46_RAW_TEXT_BYTES",
    "A46_RAW_TEXT_CHARS",
    "A46_REPORT_NAME",
    "A46_REQUEST_HASH",
    "A46_REQUEST_ID",
    "A46_RESPONSE_IDENTITY_ARTIFACT",
    "A46_STATUS_PRESERVED",
    "A46_THINKING_TOKENS",
    "A47_REPORT_NAME",
    "A47_STATUS_PRESERVED",
    "A48_ARCHITECTURE_ARTIFACT",
    "A48_CANDIDATE_SOURCE_MAP_NAME",
    "A48_CONTRACT_ARTIFACT",
    "A48_COST_USD",
    "A48_PUBLICATION_ARTIFACT",
    "A48_READINESS_ARTIFACT",
    "A48_REPORT_NAME",
    "A48_SEMANTIC_ARTIFACT",
    "A48_STATUS_PRESERVED",
    "A48_STRUCTURAL_ARTIFACT",
    "A48_TECHNICAL_ARTIFACT",
    "A49_COST_USD",
    "A41_FULL_SUITE_NOTE",
    "BASELINE_ARTIFACT",
    "BROADER_SLICE_TEST_PATHS",
    "BYTE_IDENTITY_EXACT",
    "CANDIDATE_IDENTITY_ARTIFACT",
    "CANONICAL_VALIDATOR_TEST_PATHS",
    "CONSOLIDATION_AUTHORIZED",
    "EDITORIAL_PLANNER_FORBIDDEN",
    "EXPECTED_IDEA",
    "FOCUSED_TEST_PATHS",
    "FREEZE_ARTIFACT",
    "FROZEN_LOCAL_ARCHITECTURE",
    "FROZEN_PLANNER",
    "FROZEN_PROMPT_VERSION",
    "FROZEN_TRANSPORT_VERSION",
    "FUTURE_PROMPT",
    "FUTURE_PROMPT_VERSION",
    "GLOBAL_INTENT_MAX_CHARS",
    "GRAMMAR_CANARY_CALLS",
    "GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC",
    "HISTORICAL_240_ORIGIN",
    "HISTORICAL_INTENT_LIMIT",
    "HISTORICAL_PROMPT",
    "HISTORICAL_REQUEST_HASH",
    "LIMIT_JUSTIFICATION",
    "LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN",
    "LOCAL_WINDOW_INTENT_LIMIT",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "PHASE",
    "PREPUBLICATION_ARTIFACT",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PROJECT_NAME",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "PUBLICATION_ARTIFACT",
    "PUBLICATION_MODE_BLOCKED",
    "PUBLICATION_MODE_CONFLICT",
    "PUBLICATION_MODE_IDENTICAL",
    "PUBLICATION_MODE_NEW",
    "READINESS_ARTIFACT",
    "RELOAD_ARTIFACT",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPORT_NAME",
    "SCHEMA_ADAPTED_BYTES",
    "SCHEMA_HASH",
    "SCHEMA_RAW_BYTES",
    "SCHEMA_VERSION",
    "SELECTED_INTENT_LIMIT",
    "SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE",
    "SOURCE_MAP_PUBLICATION_AUTHORIZED",
    "SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION",
    "TEST_DELTA_ARTIFACT",
    "TEXT_LIMITS",
    "THEME_LIMIT",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V140",
]
