"""Rapport markdown 3B.7.7A.49."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any], *, tests: str) -> str:
    header = bundle.get("header") or {}
    lines = [
        "# PHASE 3B.7.7A.49 — SOURCE_MAP PUBLICATION AND PHASE 3B FREEZE",
        "",
        "## Result",
        "",
        str(header.get("result")),
        "",
        "REAL PROVIDER CALLS =",
        "0",
        "",
        "A.48 STATUS =",
        _dash(header.get("a48_status")),
        "",
        "PUBLICATION_ELIGIBLE =",
        _dash(header.get("publication_eligible")),
        "",
        "A.46 RAW RESPONSE UNCHANGED =",
        _dash(header.get("a46_raw_response_unchanged")),
        "",
        "VALIDATED CANDIDATE PATH =",
        _dash(header.get("validated_candidate_path")),
        "",
        "VALIDATED CANDIDATE SHA256 =",
        _dash(header.get("validated_candidate_sha256")),
        "",
        "VALIDATED CANDIDATE BYTES =",
        _dash(header.get("validated_candidate_bytes")),
        "",
        "PRE-PUBLICATION CANONICAL VALIDATION =",
        _dash(header.get("pre_publication_canonical_validation")),
        "",
        "PRE-PUBLICATION STRUCTURAL SCAN =",
        _dash(header.get("pre_publication_structural_scan")),
        "",
        "PRE-PUBLICATION TRACEABILITY =",
        _dash(header.get("pre_publication_traceability")),
        "",
        "PRE-PUBLICATION IDEA ACCOUNTABILITY =",
        _dash(header.get("pre_publication_idea_accountability")),
        "",
        "TARGET =",
        _dash(header.get("target")),
        "",
        "TARGET PREEXISTED =",
        _dash(header.get("target_preexisted")),
        "",
        "TARGET CONFLICT =",
        _dash(header.get("target_conflict")),
        "",
        "PUBLICATION MODE =",
        _dash(header.get("publication_mode")),
        "",
        "ATOMIC PUBLICATION =",
        _dash(header.get("atomic_publication")),
        "",
        "PUBLISHED SHA256 =",
        _dash(header.get("published_sha256")),
        "",
        "PUBLISHED BYTES =",
        _dash(header.get("published_bytes")),
        "",
        "BYTE IDENTITY =",
        _dash(header.get("byte_identity")),
        "",
        "POST-WRITE JSON PARSE =",
        _dash(header.get("post_write_json_parse")),
        "",
        "POST-WRITE MODEL LOAD =",
        _dash(header.get("post_write_model_load")),
        "",
        "POST-WRITE CANONICAL VALIDATION =",
        _dash(header.get("post_write_canonical_validation")),
        "",
        "POST-WRITE STRUCTURAL SCAN =",
        _dash(header.get("post_write_structural_scan")),
        "",
        "POST-WRITE TRACEABILITY =",
        _dash(header.get("post_write_traceability")),
        "",
        "POST-WRITE DETERMINISTIC IDENTITY =",
        _dash(header.get("post_write_deterministic_identity")),
        "",
        "PUBLISHED TOPICS =",
        _dash(header.get("published_topics")),
        "",
        "PUBLISHED IDEAS =",
        _dash(header.get("published_ideas")),
        "",
        "PUBLISHED EXAMPLES =",
        _dash(header.get("published_examples")),
        "",
        "PUBLISHED REFERENCES =",
        _dash(header.get("published_references")),
        "",
        "PUBLISHED UNCERTAINTIES =",
        _dash(header.get("published_uncertainties")),
        "",
        "PUBLISHED REPETITIONS =",
        _dash(header.get("published_repetitions")),
        "",
        "GLOBAL INTENT LENGTH =",
        "290",
        "",
        "GLOBAL INTENT LIMIT =",
        "320",
        "",
        "HISTORICAL A.46 COST =",
        "0.26852 USD",
        "",
        "A.49 COST =",
        "0.00 USD",
        "",
        "FUTURE PROMPT =",
        "global-consolidation-3.0.1",
        "",
        "TRANSPORT =",
        "global-consolidation-transport-3.0",
        "",
        "GLOBAL CONSOLIDATION CORE ARCHITECTURE FUNCTIONALLY FROZEN =",
        _dash(header.get("global_consolidation_core_architecture_functionally_frozen")),
        "",
        "LOCAL EXTRACTION FUNCTIONALLY FROZEN =",
        _dash(header.get("local_extraction_functionally_frozen")),
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        "YES",
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        _dash(header.get("new_failures")),
        "",
        "SOURCE MAP =",
        _dash(header.get("source_map")),
        "",
        "SOURCE MAP PATH =",
        _dash(header.get("source_map_path")),
        "",
        "SOURCE MAP SHA256 =",
        _dash(header.get("source_map_sha256")),
        "",
        "PHASE 3B =",
        _dash(header.get("phase_3b")),
        "",
        "PHASE 3B FUNCTIONALLY FROZEN =",
        _dash(header.get("phase_3b_functionally_frozen")),
        "",
        "READY_FOR_PHASE_4_EDITORIAL_PLANNER_DESIGN =",
        _dash(header.get("ready_for_phase_4_editorial_planner_design")),
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
