"""Rapport markdown déterministe 3B.7.7A.18."""

from __future__ import annotations

from typing import Any, Mapping

from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    AUTHORIZATION_SCOPE,
    CANARY_MAX_OUTPUT_TOKENS,
    DRY_RUN_COMMAND,
    HEADROOM_TO_32000,
    REAL_COMMAND,
    SYNTHETIC_WORST_CASE_LOCAL_TOKENS,
    TARGET_12000_EXCEEDED_BY,
)


def _yn(value: Any) -> str:
    if value is True or value == "YES":
        return "YES"
    if value is False or value == "NO":
        return "NO"
    if value is None:
        return "UNKNOWN"
    return str(value)


def _dash(value: Any) -> str:
    if value is None:
        return "UNKNOWN"
    return str(value)


def _count(handles: Mapping[str, Any], key: str) -> Any:
    counts = handles.get("counts") or {}
    if key in counts:
        return counts[key]
    listed = handles.get(key)
    if isinstance(listed, list):
        return len(listed)
    return "UNKNOWN"


def render_report(bundle: Mapping[str, Any]) -> str:
    h = bundle.get("header") or {}
    dry1 = bundle.get("dry_run_1") or {}
    dry2 = bundle.get("dry_run_2") or {}
    exe = bundle.get("execution") or {}
    audit = bundle.get("payload_audit") or {}
    schema = bundle.get("schema_metrics") or {}
    freeze = bundle.get("freeze") or {}
    fixture = bundle.get("fixture") or {}
    identity = audit.get("identity_fields") or {}
    cost = exe.get("cost") or {}
    handles = exe.get("handles") or h.get("handles") or {}
    files_created = bundle.get("files_created") or []
    files_modified = bundle.get("files_modified") or []
    tests = h.get("tests") or "UNKNOWN"
    dry_cmd = bundle.get("dry_run_command") or DRY_RUN_COMMAND
    real_cmd = bundle.get("real_command") or REAL_COMMAND

    lines = [
        "# PHASE 3B.7.7A.18 — SYMBOLIC-HANDLE V3 TINY GRAMMAR CANARY",
        "",
        "## Result",
        "",
        str(h.get("result") or "UNKNOWN"),
        "",
        f"REAL PROVIDER CALLS = {h.get('real_provider_calls')}",
        "",
        "REAL WINDOW CALLS = 0",
        "",
        "PASTORAL CONTENT SENT = NO",
        "",
        f"AUTHORIZATION SCOPE = {h.get('authorization_scope')}",
        "",
        f"PROVIDER = {h.get('provider')}",
        "",
        f"MODEL = {h.get('model')}",
        "",
        "PROMPT = window-analysis-1.3",
        "",
        "TRANSPORT = semantic-transport-v3",
        "",
        "THINKING = disabled",
        "",
        "EFFORT = omitted",
        "",
        "MANUAL BUDGET = absent",
        "",
        f"RAW / ADAPTED SCHEMA = {h.get('raw_schema_bytes')} / {h.get('adapted_schema_bytes')}",
        "",
        f"SCHEMA HASH = {h.get('schema_hash')}",
        "",
        f"SERVER GRAMMAR ACCEPTED = {h.get('server_grammar_accepted')}",
        "",
        f"THINKING DISABLED ACCEPTED = {h.get('thinking_disabled_accepted')}",
        "",
        f"HTTP STATUS = {_dash(h.get('http_status'))}",
        "",
        f"REQUEST ID = {_dash(h.get('request_id'))}",
        "",
        f"ACTUAL INPUT TOKENS = {_dash(h.get('input_tokens'))}",
        "",
        f"ACTUAL OUTPUT TOKENS = {_dash(h.get('output_tokens'))}",
        "",
        f"ACTUAL THINKING TOKENS = {_dash(h.get('thinking_tokens'))}",
        "",
        f"FINISH REASON = {_dash(h.get('finish_reason'))}",
        "",
        f"STRUCTURED PARSE = {h.get('structured_parse')}",
        "",
        f"V3 DECODER = {h.get('v3_decoder')}",
        "",
        f"HANDLE REGISTRY = {h.get('handle_registry')}",
        "",
        f"HANDLE RESOLUTION = {h.get('handle_resolution')}",
        "",
        f"V3 VALIDATOR = {h.get('v3_validator')}",
        "",
        f"IDEA→TOPIC = {h.get('idea_to_topic')}",
        "",
        f"RELATION→IDEA = {h.get('relation_to_idea')}",
        "",
        f"EXAMPLE→IDEA = {h.get('example_to_idea')}",
        "",
        f"UNKNOWN HANDLES = {h.get('unknown_handles')}",
        "",
        f"WRONG-KIND HANDLES = {h.get('wrong_kind_handles')}",
        "",
        f"DUPLICATE OWNERS = {h.get('duplicate_owners')}",
        "",
        f"SELF RELATIONS = {h.get('self_relations')}",
        "",
        f"MALFORMED HANDLES = {h.get('malformed_handles')}",
        "",
        f"NUMERIC LINK REGRESSION = {h.get('numeric_link_regression')}",
        "",
        f"SYNTHETIC WORST CASE = {SYNTHETIC_WORST_CASE_LOCAL_TOKENS}",
        "",
        f"12000 DESIGN TARGET = EXCEEDED BY {TARGET_12000_EXCEEDED_BY}",
        "",
        "MAX OUTPUT PRODUCTION = 32000 unchanged",
        "",
        f"ACTUAL COST = {h.get('actual_cost')}",
        "",
        f"PROVIDER ELAPSED = {_dash(h.get('provider_elapsed'))}",
        "",
        f"FORENSICS = {_dash(h.get('forensics'))}",
        "",
        f"CANARY ARTIFACT ISOLATED = {h.get('canary_artifact_isolated')}",
        "",
        "REAL WINDOWS READY = 0 / 7",
        "",
        "REAL WIN001 AUTHORIZED = NO",
        "",
        "SOURCE MAP = NOT PUBLISHED",
        "",
        "PRODUCTION DEFAULT = window-planner-v2.0",
        "",
        "PHASE 3B = INCOMPLETE",
        "",
        f"TESTS = {tests}",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
        "## 1. Authorization",
        "",
        f"Scope required: {AUTHORIZATION_SCOPE}",
        f"Scope used: {h.get('authorization_scope')}",
        "WIN001 authorization: NO",
        "Pastoral transcript authorization: NO",
        "Authorization is consumed on the first real provider attempt.",
        "",
        "## 2. Purpose",
        "",
        "Grammar + provider configuration + minimal symbolic-handle decoding canary.",
        "This is NOT a real semantic-quality benchmark and NOT WIN001.",
        "",
        "## 3. Baseline",
        "",
        f"Pre-network baseline: {h.get('baseline') or 'see tests section'}",
        "If baseline had failed, no provider call would have been made.",
        "",
        "## 4. Historical freeze",
        "",
        f"window-analysis-1.0 unchanged: {_yn((freeze.get('integrity') or {}).get('prompt_1_0_unchanged'))}",
        f"window-analysis-1.1 unchanged: {_yn((freeze.get('integrity') or {}).get('prompt_1_1_unchanged'))}",
        f"semantic-transport-v1 / Generation C raw unchanged: {_yn((freeze.get('integrity') or {}).get('generation_c_raw_unchanged'))}",
        f"Generation C anthropic unchanged: {_yn((freeze.get('integrity') or {}).get('generation_c_anthropic_unchanged'))}",
        f"CLEAN unchanged: {_yn((freeze.get('integrity') or {}).get('clean_unchanged'))}",
        f"A.13 report hash: {(freeze.get('historical_reports') or {}).get('a13')}",
        f"A.15 report hash: {(freeze.get('historical_reports') or {}).get('a15')}",
        f"A.16 report hash: {(freeze.get('historical_reports') or {}).get('a16')}",
        f"A.17 report hash: {(freeze.get('historical_reports') or {}).get('a17')}",
        f"Production planner: {freeze.get('production_planner')}",
        "",
        "## 5. V3 contract",
        "",
        "prompt = window-analysis-1.3 (system prompt reused, not mutated)",
        "transport = semantic-transport-v3",
        "architecture = LOCAL_SYMBOLIC_HANDLES",
        "thinking = disabled, effort omitted, budget_tokens absent",
        "",
        "## 6. Synthetic fixture",
        "",
        f"transcript_id = {fixture.get('transcript_id')}",
        f"window_id = {fixture.get('window_id')}",
        f"src_ids = {fixture.get('src_ids')}",
        f"fixture_hash = {fixture.get('fixture_hash')}",
        "Texts are synthetic planning/review sentences. No pastoral content.",
        "Required coverage: 2 TOPIC, 3 IDEA, 1 RELATION, 1 EXAMPLE.",
        "",
        "## 7. Synthetic-only guard",
        "",
        f"Guard result: {_yn(h.get('synthetic_guard_passed'))}",
        "Fail-closed against WIN001–WIN007, TR001, SRC000…, pastoral markers.",
        "",
        "## 8. Prompt / wrapper",
        "",
        "window-analysis-1.3 system prompt is used unchanged.",
        "A dedicated wrapper (v3-symbolic-handle-grammar-canary-wrapper-1.0)",
        "asks for two TOPIC, three IDEA, one RELATION, one EXAMPLE.",
        f"prompt_hash = {audit.get('prompt_hash')}",
        f"wrapper_hash = {audit.get('wrapper_hash')}",
        "",
        "## 9. Schema",
        "",
        f"raw bytes = {schema.get('raw_bytes')}",
        f"adapted bytes = {schema.get('adapted_bytes')}",
        f"matches A.17 588/650: {_yn(schema.get('matches_expected'))}",
        f"matches A.17 fingerprint: {_yn(schema.get('matches_a17_fingerprint'))}",
        f"raw schema hash = {audit.get('raw_schema_hash') or schema.get('raw_hash')}",
        f"adapted schema hash = {audit.get('schema_hash') or schema.get('adapted_hash')}",
        "Server grammar status before call: UNVERIFIED.",
        "A.13 remains evidence only for semantic-transport-v2 + thinking disabled.",
        "",
        "## 10. Thinking / effort / temperature",
        "",
        f"thinking.type = {audit.get('thinking_type')}",
        f"effort present = {_yn(audit.get('effort_present'))}",
        f"budget_tokens present = {_yn(audit.get('budget_tokens_present'))}",
        f"task_budget present = {_yn(audit.get('task_budget_present'))}",
        f"temperature present = {_yn(audit.get('temperature_present'))}",
        f"output_config.format present = {_yn(audit.get('format_present'))}",
        "",
        "## 11. Canary max_tokens",
        "",
        f"canary max_tokens = {audit.get('max_tokens') or CANARY_MAX_OUTPUT_TOKENS}",
        "Selected because A.13 used 512 for 3 records (236 output tokens).",
        "This fixture requires 7 records with symbolic handles; 1024 is the",
        "smallest comfortable envelope. Production max_output remains 32000.",
        "",
        "## 12. V3 worst-case budget (design evidence only)",
        "",
        f"synthetic worst case = {SYNTHETIC_WORST_CASE_LOCAL_TOKENS}",
        f"12000 design target = EXCEEDED BY {TARGET_12000_EXCEEDED_BY}",
        f"HEADROOM_TO_32000 = {HEADROOM_TO_32000}",
        "Classification: TARGET_12000_EXCEEDED_BY_364.",
        "This is not a provider-enforced semantic bound.",
        "",
        "## 13. Request identity",
        "",
        f"request_identity = {audit.get('request_identity')}",
        f"identity fields = {identity}",
        "",
        "## 14. Dry run #1",
        "",
        f"command = {dry_cmd}",
        f"request_identity = {dry1.get('request_identity')}",
        f"schema_hash = {dry1.get('schema_hash')}",
        f"prompt_hash = {dry1.get('prompt_hash')}",
        f"fixture_hash = {dry1.get('synthetic_fixture_hash')}",
        f"provider calls = {dry1.get('actual_real_provider_calls', 0)}",
        "",
        "## 15. Dry run #2",
        "",
        f"command = {dry_cmd}",
        f"request_identity = {dry2.get('request_identity')}",
        f"schema_hash = {dry2.get('schema_hash')}",
        f"prompt_hash = {dry2.get('prompt_hash')}",
        f"fixture_hash = {dry2.get('synthetic_fixture_hash')}",
        f"provider calls = {dry2.get('actual_real_provider_calls', 0)}",
        "",
        "## 16. Determinism",
        "",
        f"same request identity: {_yn(dry1.get('request_identity') == dry2.get('request_identity') and bool(dry1.get('request_identity')))}",
        f"same schema hash: {_yn(dry1.get('schema_hash') == dry2.get('schema_hash') and bool(dry1.get('schema_hash')))}",
        f"same prompt hash: {_yn(dry1.get('prompt_hash') == dry2.get('prompt_hash') and bool(dry1.get('prompt_hash')))}",
        f"same fixture hash: {_yn(dry1.get('synthetic_fixture_hash') == dry2.get('synthetic_fixture_hash') and bool(dry1.get('synthetic_fixture_hash')))}",
        "provider calls on dry runs = 0",
        "",
        "## 17. Final pre-call gate",
        "",
        f"tests green before call: {_yn(h.get('pre_call_tests_green'))}",
        f"dry run green: {_yn(h.get('dry_run_green'))}",
        f"payload audit green: {_yn(h.get('payload_audit_green'))}",
        f"credential available: {_yn(h.get('credential_available'))}",
        f"synthetic-only guard green: {_yn(h.get('synthetic_guard_passed'))}",
        f"forensics ready: {_yn(h.get('forensics_ready'))}",
        f"schema identity correct: {_yn(schema.get('matches_expected'))}",
        f"call count before real = {h.get('pre_call_provider_calls', 0)}",
        "",
        "## 18. Real execution",
        "",
        f"command = {real_cmd}",
        f"executed once: {_yn(h.get('executed_once'))}",
        f"error = {_dash(exe.get('error') if 'error' in exe else h.get('execution_error'))}",
        f"engine.generate attempts = {h.get('engine_generate_attempts')}",
        f"Anthropic POST attempts = {h.get('anthropic_post_attempts')}",
        "Retry = NO. Fallback = NO. Auto-continue = NO.",
        "",
        "## 19. HTTP / usage",
        "",
        f"HTTP status = {_dash(h.get('http_status'))}",
        f"request id = {_dash(h.get('request_id'))}",
        f"elapsed = {_dash(h.get('provider_elapsed'))}",
        f"input tokens = {_dash(h.get('input_tokens'))}",
        f"output tokens = {_dash(h.get('output_tokens'))}",
        f"thinking tokens = {_dash(h.get('thinking_tokens'))}",
        f"thinking tokens field reported = {_yn(exe.get('thinking_tokens_reported'))}",
        f"finish_reason = {_dash(h.get('finish_reason'))}",
        "Unknown is reported as UNKNOWN, never silently zero.",
        "",
        "## 20. Grammar / thinking acceptance",
        "",
        f"V3_SERVER_GRAMMAR_ACCEPTED = {h.get('server_grammar_accepted')}",
        f"THINKING_DISABLED_ACCEPTED = {h.get('thinking_disabled_accepted')}",
        "Inferred only from HTTP/provider success or explicit schema rejection.",
        "",
        "## 21. Parse / decode / resolve / validate",
        "",
        f"structured parse = {h.get('structured_parse')}",
        f"V3 decoder = {h.get('v3_decoder')}",
        f"handle registry = {h.get('handle_registry')}",
        f"handle resolution = {h.get('handle_resolution')}",
        f"V3 validator = {h.get('v3_validator')}",
        "No fuzzy repair. No retry.",
        "",
        "## 22. Handle metrics",
        "",
        f"TOPIC owner handles = {handles.get('topic_owner_handles')}",
        f"IDEA owner handles = {handles.get('idea_owner_handles')}",
        f"IDEA→TOPIC = {handles.get('idea_to_topic_links')}",
        f"RELATION→IDEA = {handles.get('relation_to_idea_links')}",
        f"EXAMPLE→IDEA = {handles.get('example_to_idea_links')}",
        f"unknown = {handles.get('unknown_handles')}",
        f"wrong-kind = {handles.get('wrong_kind_handles')}",
        f"duplicate owners = {handles.get('duplicate_owners')}",
        f"self-relations = {handles.get('self_relations')}",
        f"malformed = {handles.get('malformed_handles')}",
        f"numeric link regression = {handles.get('numeric_link_regression')}",
        f"Python structural only = {_yn(handles.get('python_structural_only'))}",
        "",
        "## 23. Canonical diagnostic reconstruction",
        "",
        f"{exe.get('reconstruction')}",
        "Synthetic fixture only. SourceMap was not published.",
        "",
        "## 24. Isolation",
        "",
        f"canary artifact isolated = {h.get('canary_artifact_isolated')}",
        f"source_map published = {_yn(freeze.get('source_map_present'))}",
        f"production windows touched = {_yn(freeze.get('production_windows_touched'))}",
        "REAL WINDOWS READY = 0 / 7",
        "PRODUCTION DEFAULT = window-planner-v2.0",
        "CANDIDATE PLANNER = window-planner-v2.1-small (not activated)",
        "",
        "## 25. Cost",
        "",
        f"actual cost = {h.get('actual_cost')}",
        f"cost status = {cost.get('status')}",
        "",
        "## 26. Tests",
        "",
        f"{tests}",
        "Post-call suite used no_ai_network. No additional real provider calls.",
        "",
        "## 27. Files created",
        "",
        *([f"- {path}" for path in files_created] or ["- (none)"]),
        "",
        "## 28. Files modified",
        "",
        *([f"- {path}" for path in files_modified] or ["- (none)"]),
        "",
        "## 29. What PASS proves",
        "",
        "Anthropic accepts semantic-transport-v3 schema.",
        "thinking-disabled works with V3.",
        "The model can emit typed symbolic handles on a tiny synthetic task.",
        "Python can resolve them deterministically.",
        "The V3 protocol is technically viable.",
        "",
        "## 30. What PASS does not prove",
        "",
        "Real WIN001 semantic success.",
        "All 7 windows success.",
        "thinking-disabled global suitability.",
        "Consolidation success.",
        "Phase 3B completion.",
        "Editorial / title / chapter quality.",
        "",
        "## 31. Next phase decision",
        "",
        "If PASS: recommend human review before separately authorizing",
        "3B.7.7A.19 — REAL V3 SMALL WIN001 SYMBOLIC-HANDLE CANARY.",
        "That future phase is NOT executed here.",
        "",
        "## Required questions",
        "",
        "Were any pastoral SRCs sent? NO",
        "Was WIN001 called? NO",
        f"How many provider attempts occurred? {h.get('anthropic_post_attempts')}",
        f"Did Anthropic accept V3 schema? {h.get('server_grammar_accepted')}",
        f"Did Anthropic accept thinking disabled? {h.get('thinking_disabled_accepted')}",
        f"Were thinking tokens 0 according to provider evidence? {_dash(h.get('thinking_tokens'))}",
        f"Did structured parsing pass? {h.get('structured_parse')}",
        f"Did V3 decoding pass? {h.get('v3_decoder')}",
        f"Did handle registry construction pass? {h.get('handle_registry')}",
        f"Did symbolic resolution pass? {h.get('handle_resolution')}",
        f"Did V3 validation pass? {h.get('v3_validator')}",
        f"Did the model emit TOPIC T handles? {_yn(bool((handles.get('topic_owner_handles') or [])))}",
        f"Did the model emit IDEA I handles? {_yn(bool((handles.get('idea_owner_handles') or [])))}",
        f"Did IDEA→TOPIC work? {_yn(bool((handles.get('idea_to_topic_links') or [])))}",
        f"Did RELATION→IDEA work? {_yn(bool((handles.get('relation_to_idea_links') or [])))}",
        f"Did EXAMPLE→IDEA work? {_yn(bool((handles.get('example_to_idea_links') or [])))}",
        f"Were any unknown handles emitted? {_count(handles, 'unknown')}",
        f"Were any wrong-kind handles emitted? {_count(handles, 'wrong_kind')}",
        f"Were any duplicate owner handles emitted? {_count(handles, 'duplicate_owners')}",
        f"Were any malformed handles emitted? {_count(handles, 'malformed')}",
        f"Were any self-relations emitted? {_count(handles, 'self_relations')}",
        f"Did numeric global indexes reappear? {h.get('numeric_link_regression')}",
        f"Was Python purely structural? {_yn(handles.get('python_structural_only', True))}",
        f"Was schema size still compact? {schema.get('raw_bytes')}/{schema.get('adapted_bytes')}",
        f"What actual cost was incurred? {h.get('actual_cost')}",
        "Did any production artifact change? NO",
        "Did source_map remain absent? YES",
        f"Did full suite pass? {tests}",
        f"Is V3 technically ready for a FUTURE real WIN001 human authorization? {h.get('win001_technically_eligible')}",
        "Do not interpret readiness as authorization.",
        "",
        "STOP. Wait for human review.",
        "",
    ]
    return "\n".join(lines) + "\n"


def header_from_result(result, *, extra: Mapping[str, Any] | None = None) -> dict[str, Any]:
    exe = result.execution or {}
    schema = result.schema_metrics or {}
    cost = exe.get("cost") or {}
    handles = exe.get("handles") or {}
    counts = handles.get("counts") or {}
    coverage = handles.get("coverage") or {}
    payload = {
        "result": exe.get("result") or result.mode,
        "real_provider_calls": result.anthropic_post_attempts,
        "authorization_scope": result.authorization_scope,
        "provider": "anthropic",
        "model": "claude-sonnet-5",
        "raw_schema_bytes": schema.get("raw_bytes"),
        "adapted_schema_bytes": schema.get("adapted_bytes"),
        "schema_hash": (result.payload_audit or {}).get("raw_schema_hash")
        or schema.get("raw_hash"),
        "server_grammar_accepted": exe.get("server_grammar_accepted", "NO"),
        "thinking_disabled_accepted": exe.get("thinking_disabled_accepted", "NO"),
        "http_status": exe.get("http_status"),
        "request_id": exe.get("request_id"),
        "input_tokens": exe.get("input_tokens"),
        "output_tokens": exe.get("output_tokens"),
        "thinking_tokens": exe.get("thinking_tokens"),
        "finish_reason": exe.get("finish_reason"),
        "structured_parse": exe.get("structured_parse", "n/a"),
        "v3_decoder": exe.get("v3_decoder", "n/a"),
        "handle_registry": exe.get("handle_registry", "n/a"),
        "handle_resolution": exe.get("handle_resolution", "n/a"),
        "v3_validator": exe.get("v3_validator", "n/a"),
        "idea_to_topic": counts.get("idea_to_topic", 0 if exe else "n/a"),
        "relation_to_idea": counts.get("relation_to_idea", 0 if exe else "n/a"),
        "example_to_idea": counts.get("example_to_idea", 0 if exe else "n/a"),
        "unknown_handles": counts.get("unknown", 0 if exe else "n/a"),
        "wrong_kind_handles": counts.get("wrong_kind", 0 if exe else "n/a"),
        "duplicate_owners": counts.get("duplicate_owners", 0 if exe else "n/a"),
        "self_relations": counts.get("self_relations", 0 if exe else "n/a"),
        "malformed_handles": counts.get("malformed", 0 if exe else "n/a"),
        "numeric_link_regression": handles.get("numeric_link_regression", "n/a"),
        "actual_cost": cost.get("display", "UNKNOWN"),
        "provider_elapsed": exe.get("provider_elapsed_ms"),
        "forensics": exe.get("forensic_path"),
        "canary_artifact_isolated": "YES"
        if exe.get("canary_artifact_isolated") or result.mode == "DRY_RUN"
        else "NO",
        "engine_generate_attempts": result.engine_generate_attempts,
        "anthropic_post_attempts": result.anthropic_post_attempts,
        "synthetic_guard_passed": True,
        "execution_error": result.error,
        "handles": handles,
        "coverage": coverage,
        "win001_technically_eligible": (
            "YES — future human authorization only"
            if exe.get("result") == "PASS"
            else "NO"
        ),
    }
    if extra:
        payload.update(dict(extra))
    return payload


def bundle_from_result(
    result,
    *,
    dry_run_1: Mapping[str, Any] | None = None,
    dry_run_2: Mapping[str, Any] | None = None,
    extra_header: Mapping[str, Any] | None = None,
    files_created: list[str] | None = None,
    files_modified: list[str] | None = None,
    dry_run_command: str | None = None,
    real_command: str | None = None,
) -> dict[str, Any]:
    return {
        "header": header_from_result(result, extra=extra_header),
        "dry_run_1": dict(dry_run_1 or result.dry_run or {}),
        "dry_run_2": dict(dry_run_2 or {}),
        "execution": result.execution,
        "payload_audit": result.payload_audit,
        "schema_metrics": result.schema_metrics,
        "freeze": result.freeze,
        "fixture": (result.dry_run or {}).get("fixture") or {},
        "files_created": list(files_created or []),
        "files_modified": list(files_modified or []),
        "dry_run_command": dry_run_command or DRY_RUN_COMMAND,
        "real_command": real_command or REAL_COMMAND,
    }


__all__ = ["bundle_from_result", "header_from_result", "render_report"]
