"""
Phase 4B.2.7.6 — Independent discriminating canary, offline design and preflight.

Offline only. Zero provider calls. Historical canaries are not relaunched.
Historical 4B.2.6 remains FAIL. 4B.2.6.1 remains PASS. 4B.2.6.2 remains PASS.
Historical 4B.2.7 remains PARTIAL. 4B.2.7.1 remains PASS. 4B.2.7.2 remains PASS.
Historical 4B.2.7.3 remains PARTIAL. 4B.2.7.4 remains PASS. 4B.2.7.5 remains PASS.
h01 and h02 remain PARTIAL. Frozen 1.0 / 1.1 / 1.1.1 / 1.1.2 / 1.1.3 are not
modified. 1.1.3-candidate is a proposal only and is not promoted.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
)
from app.book_semantic_gate_4b24.constants import (
    CONNECTIVE_CASE_ID,
    FUNERAL_CASE_ID,
    NEGATIVE_CASE_IDS,
    P3_CASE_ID,
    P8_CASE_ID,
    POSITIVE_CASE_IDS,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    SEMANTIC_TOKEN_BUDGET,
)
from app.book_semantic_gate_4b261.constants import (
    CANDIDATE_PROMPT_VERSION,
    CANDIDATE_TRANSPORT_VERSION,
)
from app.book_semantic_gate_4b27.constants import (
    EXPECTED_EVIDENCE_HANDLES as H01_EVIDENCE_HANDLES,
    EXPECTED_REQUEST_SHA256 as H01_REQUEST_SHA256,
    HISTORICAL_4B261_STATUS,
    HISTORICAL_4B262_STATUS,
    HISTORICAL_4B26_STATUS,
)
from app.book_semantic_gate_4b271.constants import (
    DISPUTED_CLAUSE as H01_DISPUTED_CLAUSE,
    EXPECTED_PROMPT_11_SHA256,
    EXPECTED_PROMPT_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_SYSTEM_SHA256,
    EXPECTED_SCHEMA_11_SHA256,
    HISTORICAL_4B27_STATUS,
    PROMPT_VERSION_111,
    TRANSPORT_VERSION_11,
)
from app.book_semantic_gate_4b272.constants import (
    DISPUTED_CAUSAL_CLAUSE,
    HISTORICAL_4B271_STATUS,
    OBSERVED_4B27_COMPLETION_TOKENS,
    OBSERVED_4B27_COST_USD,
    OBSERVED_4B27_INPUT_TOKENS,
    OBSERVED_4B27_REASONING_TOKENS,
    P3_EVIDENCE_HANDLES,
)
from app.book_semantic_gate_4b273.constants import (
    EXPECTED_REQUEST_SHA256 as H02_REQUEST_SHA256,
    HISTORICAL_4B272_STATUS,
)
from app.book_semantic_gate_4b274.constants import HISTORICAL_4B273_STATUS
from app.book_semantic_gate_4b275.constants import (
    EXPECTED_PROMPT_111_SHA256,
    EXPECTED_PROMPT_112_SHA256,
    EXPECTED_PROMPT_113_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_113_SHA256,
    EXPECTED_PROMPT_113_SYSTEM_SHA256,
    HISTORICAL_4B274_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    OVERFIT_TOKENS,
    PROMPT_VERSION_112,
    PROMPT_VERSION_113,
    TRANSPORT_VERSION_113,
)

PHASE = "4B.2.7.6"
PHASE_NAME = "INDEPENDENT_DISCRIMINATING_CANARY_OFFLINE_PREFLIGHT"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B276_INDEPENDENT_DISCRIMINATING_CANARY_OFFLINE_PREFLIGHT_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SDK_MAX_RETRIES = 0
RETRIES = 0
FALLBACKS = 0

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
PROMPT_VERSION_11 = CANDIDATE_PROMPT_VERSION
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"
TOKEN_FIELD = "max_completion_tokens"
PRODUCTION_SDK_METHOD = "client.chat.completions.create"

SOURCE_CASE_HANDLE = "h03"
SOURCE_CASE_ID = "4b22_p4_supported"
SOURCE_CASE_ROLE = "positive"
SOURCE_HUMAN_LABEL = CLASS_SUPPORTED

SELECTED_CASE_HANDLE = "h11"
SELECTED_CASE_ID = "4b276_p4_new_implication"
SELECTED_CASE_ROLE = "synthetic_negative"
SELECTED_CASE_ORIGIN = "SYNTHETIC_VARIANT_OF_4B22_P4_SUPPORTED"
SELECTED_CASE_HUMAN_LABEL = CLASS_UNSUPPORTED
SELECTED_CASE_ACCEPTED_CLASSES = (CLASS_QUESTIONABLE, CLASS_UNSUPPORTED)
SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY = True
SELECTED_CASE_REASON_CODES_AUDIT_ONLY = (
    "NEW_IMPLICATION",
    "UNCERTAINTY_STRENGTHENED",
)
SELECTED_CASE_REASON_CODES_ACCEPTABLE_AUDIT_ONLY = (
    "NEW_IMPLICATION",
    "UNCERTAINTY_STRENGTHENED",
    "NEW_CONCLUSION",
    "NEW_DOCTRINAL_CLAIM",
)
TARGET_FAILURE_FAMILY = "NEW_IMPLICATION_AND_UNCERTAINTY_STRENGTHENED"
DISPUTED_CLAUSE = "which means that every believer is guaranteed a fearless death"
ADDED_SUFFIX = ", which means that every believer is guaranteed a fearless death."

P4_EVIDENCE_HANDLES = (
    "IDEA226",
    "SRC006192",
    "SRC006193",
    "SRC006195",
)
P4_SRC_IDS = (
    "SRC006192",
    "SRC006193",
    "SRC006195",
)
P4_CONTEXT_SRC_IDS = (
    "SRC006190",
    "SRC006191",
    "SRC006194",
    "SRC006196",
    "SRC006197",
)

REQUEST_SERIALIZATION = "json.dumps(payload, ensure_ascii=False, sort_keys=True)"
REQUEST_HASH_ENCODING = "utf-8"
REQUEST_HASH_ALGORITHM = "sha256"

H01_CASE_HANDLE = "h01"
H01_CASE_ID = "4b22_p2_supported"
H01_COST_USD = OBSERVED_4B27_COST_USD
H01_INPUT_TOKENS = OBSERVED_4B27_INPUT_TOKENS
H01_COMPLETION_TOKENS = OBSERVED_4B27_COMPLETION_TOKENS
H01_REASONING_TOKENS = OBSERVED_4B27_REASONING_TOKENS

H02_CASE_HANDLE = "h02"
H02_CASE_ID = P3_CASE_ID
H02_COST_USD = 0.066036
H02_INPUT_TOKENS = 1692
H02_COMPLETION_TOKENS = 5221
H02_REASONING_TOKENS = 4595

H01_EXCLUSION_TOKENS = (
    "h01",
    "IDEA224",
    "SRC006149",
    "SRC006180",
    "SRC006182",
    "SRC006183",
    "SRC006187",
    "4b22_p2",
    "bargain with",
    "bargaining",
)
H02_EXCLUSION_TOKENS = (
    "h02",
    "IDEA225",
    "SRC006152",
    "SRC006154",
    "SRC006155",
    "SRC006156",
    "SRC006157",
    "4b22_p3",
    "because it still works",
    "resisted by truth",
    "the devil has used it",
)

HISTORICAL_4B275_STATUS = "PASS"

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert SELECTED_CASE_HANDLE == "h11"
assert SELECTED_CASE_ID == "4b276_p4_new_implication"
assert SOURCE_CASE_ID == "4b22_p4_supported"
assert SELECTED_CASE_ORIGIN == "SYNTHETIC_VARIANT_OF_4B22_P4_SUPPORTED"
assert PROMPT_VERSION_113 == "book-semantic-validator-1.1.3-candidate"
assert TRANSPORT_VERSION_11 == "book-semantic-validation-transport-1.1-candidate"
assert TRANSPORT_VERSION_113 is None
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
assert TOKEN_FIELD == "max_completion_tokens"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False
assert SDK_MAX_RETRIES == 0
assert H01_REQUEST_SHA256 == (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
assert H02_REQUEST_SHA256 == (
    "5ace261296d808437910f8f9efe247a80daebbb2237bc8af46bda56bf98d7897"
)
assert H01_REQUEST_SHA256 != H02_REQUEST_SHA256
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert HISTORICAL_4B262_STATUS == "PASS"
assert HISTORICAL_4B27_STATUS == "PARTIAL"
assert HISTORICAL_4B271_STATUS == "PASS"
assert HISTORICAL_4B272_STATUS == "PASS"
assert HISTORICAL_4B273_STATUS == "PARTIAL"
assert HISTORICAL_4B274_STATUS == "PASS"
assert HISTORICAL_4B275_STATUS == "PASS"
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert DISPUTED_CAUSAL_CLAUSE == (
    "because it still works wherever it is not resisted by truth"
)
assert H01_DISPUTED_CLAUSE == "that fear can calculate or bargain with"
assert "because" not in DISPUTED_CLAUSE
assert "sting" not in DISPUTED_CLAUSE
assert "funeral" not in DISPUTED_CLAUSE
assert "bargain" not in DISPUTED_CLAUSE
assert SCORED_CASE_ORDER[0] == (H01_CASE_HANDLE, H01_CASE_ID)
assert SCORED_CASE_ORDER[1] == (H02_CASE_HANDLE, H02_CASE_ID)
assert SCORED_CASE_ORDER[2] == (SOURCE_CASE_HANDLE, SOURCE_CASE_ID)
assert SELECTED_CASE_HANDLE not in {opaque for opaque, _ in SCORED_CASE_ORDER}
assert CANONICAL_PYTHON_EXECUTABLE.endswith("python.exe")

AUDIT_DIRNAME = "book_semantic_gate_4b276"
AUDIT_INVENTORY = "candidate_inventory.json"
AUDIT_MATRIX = "candidate_selection_matrix.json"
AUDIT_PROVENANCE = "selected_canary_provenance.json"
AUDIT_EVIDENCE = "selected_canary_evidence.json"
AUDIT_PARAGRAPH = "selected_canary_paragraph.txt"
AUDIT_HUMAN = "selected_canary_human_reference.json"
AUDIT_REQUEST = "selected_canary_provider_request.json"
AUDIT_DETERMINISM = "request_determinism.json"
AUDIT_LEAK = "label_leakage_check.json"
AUDIT_CONTRACT = "contract_113_compatibility.json"
AUDIT_REASONS = "reason_code_compatibility.json"
AUDIT_SDK = "sdk_serialization_preflight.json"
AUDIT_COST = "cost_estimation.json"
AUDIT_CRITERIA = "future_canary_success_criteria.json"
AUDIT_TESTS = "offline_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b276_index.json"
REPORT_NAME = "PHASE_4B276_INDEPENDENT_DISCRIMINATING_CANARY_OFFLINE_PREFLIGHT_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_ONE_REAL_CANARY_HUMAN_REVIEW = True
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False
