"""
Phase 4B.2.22 — CH018 editorial acceptance and 17-chapter batch readiness.

STRICTLY OFFLINE. Isolated from production. Zero provider calls.
Does not regenerate CH012 or CH018. Does not modify accepted prose.
Does not activate prompt 1.1 globally. Does not publish book.json.
Does not write the production cache. Does not promote the Semantic Gate.
Does not execute any remaining-chapter batch.
"""

from __future__ import annotations

from decimal import Decimal

from app.book_authorial_voice_4b218.constants import (
    AUTHORIAL_VOICE_POLICY_VERSION,
    FAITHFUL_PROMPT_1_0_VERSION,
    FAITHFUL_PROMPT_1_1_VERSION,
    HISTORICAL_PROMPT_V10,
    HISTORICAL_PROMPT_V101,
)
from app.book_editorial_acceptance_4b219.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B219_SCOPE,
    CHAPTER_ID as ACCEPTED_CH012_ID,
    EXPECTED_ACCEPTED_JSON_SHA256,
    EXPECTED_ACCEPTED_MD_SHA256,
    EXPECTED_LOCK_SHA256,
    EXPECTED_ORIGINAL_JSON_SHA256,
    EXPECTED_ORIGINAL_MD_SHA256,
)
from app.book_editorial_alignment_4b216.constants import (
    COVERAGE_CONTRACT_VERSION,
    EDITORIAL_POLICY_VERSION,
    HISTORICAL_SEMANTIC_CONTRACT,
)
from app.book_generation.constants import (
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION_V10,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    MODEL,
    PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_generation_4b217.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B217_SCOPE,
    HISTORICAL_CH012_CENTRAL_USD,
    SONNET_INPUT_COST_PER_1M,
    SONNET_OUTPUT_COST_PER_1M,
    TERRA_H01_ANALOG_USD,
)
from app.book_authorial_voice_4b218.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B218_SCOPE,
)
from app.book_generation_4b221.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B221_SCOPE,
    EXPECTED_EXAMPLE_IDS as CH018_EXAMPLE_IDS,
    EXPECTED_IDEA_IDS as CH018_IDEA_IDS,
    EXPECTED_REFERENCE_IDS as CH018_REFERENCE_IDS,
    EXPECTED_SECTION_IDS as CH018_SECTION_IDS,
    LOCK_CONSUMED_STATES,
    LOCK_STATE_RESPONSE_VALIDATED,
    LOCK_STATE_UNCERTAIN,
    TARGET_CHAPTER_ID as ACCEPTED_CH018_ID,
    TARGET_CHAPTER_TITLE as ACCEPTED_CH018_TITLE,
)
from app.book_scale_up_preparation_4b220.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B220_SCOPE,
    EXPECTED_PROMPT_1_1_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_1_1_SHA256,
    EXPECTED_PROMPT_1_1_SYSTEM_SHA256,
    FAITHFUL_PROMPT_1_1,
    TOTAL_CHAPTER_COUNT,
)
from app.book_semantic_gate_4b215.constants import (
    HISTORICAL_4B210_STATUS,
    HISTORICAL_4B211_STATUS,
    HISTORICAL_4B212_STATUS,
    HISTORICAL_4B213_STATUS,
    HISTORICAL_4B214_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
)
from app.book_semantic_gate_4b23.constants import EXPECTED_CLEAN_TRANSCRIPT
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE

PHASE = "4B.2.22"
PHASE_NAME = "CH018_EDITORIAL_ACCEPTANCE_AND_17_CHAPTER_BATCH_GENERATION_READINESS"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_BATCH_PREPARATION_4B222_CH018_EDITORIAL_ACCEPTANCE_"
    "AND_17_CHAPTER_BATCH_GENERATION_READINESS_ONLY"
)

AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = False
REAL_CHAPTER_GENERATION_AUTHORIZED = False
REAL_PROVIDERS_ENABLED = False
RETRIES = 0
FALLBACKS = 0
SDK_MAX_RETRIES = 0

PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
COVERAGE_CONTROL_ACTIVATED = False
FAITHFUL_PROMPT_ACTIVATED = False
FAITHFUL_PROMPT_1_1_ACTIVATED = False
EDITORIAL_POLICY_ACTIVATED = False
AUTHORIAL_VOICE_POLICY_ACTIVATED = False
SEMANTIC_GATE_202_ENABLED = False
SEMANTIC_CERTIFICATION_PERFORMED = False
BOOK_JSON_PUBLICATION = False

CODE_VERSION = "app.book_batch_preparation_4b222"
ACCEPTANCE_RECORD_VERSION = "ch018-editorial-acceptance-4b222-1.0"
MANIFEST_VERSION = "ch018-accepted-editorial-manifest-4b222-1.0"
PROGRESS_MANIFEST_VERSION = "batch-progress-manifest-4b222-1.0"
EX046_REVIEW_VERSION = "ch018-ex046-traceability-review-4b222-1.0"
AUTHORIZATION_TEMPLATE_VERSION = "batch-authorization-template-4b222-1.0"

FAITHFUL_PROMPT_1_0 = FAITHFUL_PROMPT_1_0_VERSION
HISTORICAL_PROMPT_V10_ID = HISTORICAL_PROMPT_V10
HISTORICAL_PROMPT_V101_ID = HISTORICAL_PROMPT_V101
NARRATIVE_VOICE_CONTRACT = AUTHORIAL_VOICE_POLICY_VERSION
EDITORIAL_POLICY = EDITORIAL_POLICY_VERSION
COVERAGE_CONTRACT = COVERAGE_CONTRACT_VERSION
TRANSPORT_VERSION = BOOK_GENERATION_TRANSPORT_VERSION
VALIDATOR_VERSION = BOOK_GENERATOR_VALIDATOR_VERSION
HISTORICAL_SEMANTIC = HISTORICAL_SEMANTIC_CONTRACT

assert FAITHFUL_PROMPT_1_0 == "book-generator-faithful-restatement-1.0-candidate"
assert FAITHFUL_PROMPT_1_1 == "book-generator-faithful-restatement-1.1-candidate"
assert FAITHFUL_PROMPT_1_1 == FAITHFUL_PROMPT_1_1_VERSION
assert NARRATIVE_VOICE_CONTRACT == "authorial-voice-preservation-1.0-candidate"
assert EDITORIAL_POLICY == "faithful-teaching-book-editorial-policy-1.0-candidate"
assert HISTORICAL_PROMPT_V101_ID == BOOK_GENERATOR_PROMPT_VERSION == "book-generator-1.0.1"
assert HISTORICAL_PROMPT_V10_ID == BOOK_GENERATOR_PROMPT_VERSION_V10 == "book-generator-1.0"
assert TRANSPORT_VERSION == "book-generation-transport-1.0"
assert VALIDATOR_VERSION == "book-generation-validator-1.0.1"
assert HISTORICAL_SEMANTIC == "book-semantic-validator-2.0.2-candidate"
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert CONSUMED_4B217_SCOPE == (
    "BOOK_GENERATION_4B217_CH012_FAITHFUL_REAL_PILOT_GENERATION_ONLY"
)
assert CONSUMED_4B218_SCOPE.startswith("BOOK_AUTHORIAL_VOICE_4B218_")
assert CONSUMED_4B219_SCOPE.startswith("BOOK_EDITORIAL_ACCEPTANCE_4B219_")
assert CONSUMED_4B220_SCOPE.startswith("BOOK_SCALE_UP_PREPARATION_4B220_")
assert CONSUMED_4B221_SCOPE == (
    "BOOK_GENERATION_LATER_PHASE_CH018_FIRST_REMAINING_CHAPTER_ONE_SHOT_ONLY"
)

ACCEPTED_CHAPTERS = (ACCEPTED_CH012_ID, ACCEPTED_CH018_ID)
assert ACCEPTED_CH012_ID == "CH012"
assert ACCEPTED_CH018_ID == "CH018"
assert ACCEPTED_CH018_TITLE == "Testimonies of Resurrection"
assert TOTAL_CHAPTER_COUNT == 19
REMAINING_CHAPTER_COUNT = 17
ACCEPTED_CHAPTER_COUNT = 2
assert REMAINING_CHAPTER_COUNT + ACCEPTED_CHAPTER_COUNT == TOTAL_CHAPTER_COUNT

CH018_SECTIONS = CH018_SECTION_IDS
CH018_IDEAS = CH018_IDEA_IDS
CH018_EXAMPLES = CH018_EXAMPLE_IDS
CH018_REFERENCES = CH018_REFERENCE_IDS
CH018_EX046 = "EX046"
assert CH018_SECTIONS == ("SEC067", "SEC068", "SEC069", "SEC070")
assert CH018_IDEAS == (
    "IDEA269",
    "IDEA270",
    "IDEA271",
    "IDEA272",
    "IDEA273",
    "IDEA274",
    "IDEA275",
    "IDEA276",
    "IDEA277",
    "IDEA278",
    "IDEA279",
)
assert CH018_EXAMPLES == ("EX046", "EX047", "EX048")
assert CH018_EX046 in CH018_EXAMPLES

STATUS_PENDING = "PENDING"
STATUS_READY = "READY"
STATUS_AUTHORIZED = "AUTHORIZED"
STATUS_GENERATING = "GENERATING"
STATUS_GENERATED = "GENERATED"
STATUS_STRUCTURE_FAILED = "STRUCTURE_FAILED"
STATUS_AWAITING_REVIEW = "AWAITING_REVIEW"
STATUS_ACCEPTED = "ACCEPTED"
STATUS_BLOCKED = "BLOCKED"
STATUS_UNCERTAIN = "UNCERTAIN"

PROGRESS_STATES = (
    STATUS_PENDING,
    STATUS_READY,
    STATUS_AUTHORIZED,
    STATUS_GENERATING,
    STATUS_GENERATED,
    STATUS_STRUCTURE_FAILED,
    STATUS_AWAITING_REVIEW,
    STATUS_ACCEPTED,
    STATUS_BLOCKED,
    STATUS_UNCERTAIN,
)

DECISION_SOURCE = "explicit_user_approval"
ACCEPTANCE_SCOPE = "editorial_acceptance"
RECORDING_DATE = "2026-10-04"

EXPECTED_CH018_MD_SHA256 = (
    "3f8e0590567d431af18812505e2a5f5fa454e1648d06f2b895ceae30278df1cb"
)
EXPECTED_CH018_JSON_SHA256 = (
    "e4902da92b05dbe0875222a41d59eb99f7b3e669b685f50f36b06864a327d38b"
)

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_TRANSCRIPT = EXPECTED_CLEAN_TRANSCRIPT

assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert EXPECTED_PROMPT_1_1_SHA256 == (
    "e39084dc9ed3b048bfdaa2e112b380d15957085eeb613dd74c97a32b880cec50"
)
assert AUTHORIZED_TERRA_CALLS == 0
assert AUTHORIZED_SONNET_CALLS == 0
assert AUTHORIZED_ANTHROPIC_CALLS == 0
assert AUTHORIZED_OPENAI_CALLS == 0
assert PUBLICATION_AUTHORIZED is False
assert REAL_CHAPTER_GENERATION_AUTHORIZED is False
assert FAITHFUL_PROMPT_1_1_ACTIVATED is False
assert SEMANTIC_CERTIFICATION_PERFORMED is False
assert CANONICAL_PYTHON.endswith("python.exe")

CH012_ACTUAL_COST_USD = Decimal("0.036152")
CH012_ACTUAL_INPUT_TOKENS = 8586
CH012_ACTUAL_OUTPUT_TOKENS = 1898
CH018_ACTUAL_COST_USD = Decimal("0.041500")
CH018_ACTUAL_INPUT_TOKENS = 10400
CH018_ACTUAL_OUTPUT_TOKENS = 2070
H01_ANALOG_USD = TERRA_H01_ANALOG_USD
HISTORICAL_CHAPTER_CENTRAL_USD = HISTORICAL_CH012_CENTRAL_USD
AUTHORIZED_SPEND_USD = Decimal("0")
PRICING_EFFECTIVE_DATE = "2026-09-18"
PESSIMISTIC_CHARS_PER_TOKEN = Decimal("1.9365384615384615")
PROPOSED_CAP_MARGIN = Decimal("0.15")
OBSERVED_IDEA_SCALE = Decimal("11")

HISTORICAL_4B215_STATUS = "PARTIAL"
HISTORICAL_4B216_STATUS = "PASS"
HISTORICAL_4B217_STATUS = "PARTIAL"
HISTORICAL_4B218_STATUS = "PASS"
HISTORICAL_4B219_STATUS = "PASS"
HISTORICAL_4B220_STATUS = "PASS"
HISTORICAL_4B221_STATUS = "PASS"
HISTORICAL_4B222_DOES_NOT_REQUALIFY = True

BATCH_IDS = ("BATCH-01", "BATCH-02", "BATCH-03", "BATCH-04")
BATCH_CHAPTERS = {
    "BATCH-01": ("CH001", "CH002", "CH003", "CH004"),
    "BATCH-02": ("CH005", "CH006", "CH007", "CH008"),
    "BATCH-03": ("CH009", "CH010", "CH011", "CH013"),
    "BATCH-04": ("CH014", "CH015", "CH016", "CH017", "CH019"),
}
FIRST_BATCH_ID = "BATCH-01"
assert tuple(chapter for batch in BATCH_IDS for chapter in BATCH_CHAPTERS[batch]) == (
    "CH001",
    "CH002",
    "CH003",
    "CH004",
    "CH005",
    "CH006",
    "CH007",
    "CH008",
    "CH009",
    "CH010",
    "CH011",
    "CH013",
    "CH014",
    "CH015",
    "CH016",
    "CH017",
    "CH019",
)
assert all(chapter not in ACCEPTED_CHAPTERS for batch in BATCH_IDS for chapter in BATCH_CHAPTERS[batch])

AUDIT_DIRNAME = "book_batch_preparation_4b222"
AUDIT_PREFLIGHT = "preflight.json"
AUDIT_HASHES_PRE = "canonical_hashes_pre.json"
AUDIT_ACCEPTANCE = "ch018_editorial_acceptance.json"
AUDIT_MANIFEST = "ch018_accepted_editorial_manifest.json"
AUDIT_EX046 = "ch018_ex046_traceability_review.json"
AUDIT_INVENTORY = "remaining_17_chapters_inventory.json"
AUDIT_PLAN = "batch_generation_plan.json"
AUDIT_COST = "batch_cost_envelope.json"
AUDIT_AUTHORIZATION = "batch_authorization_template.json"
AUDIT_PROGRESS = "batch_progress_manifest.json"
AUDIT_STOP = "batch_hard_stop_conditions.json"
AUDIT_TESTS = "offline_regression_tests.json"
AUDIT_HASHES_POST = "canonical_hashes_post.json"
AUDIT_READINESS = "readiness.json"
REPORT_NAME = "PHASE_4B222_CH018_ACCEPTANCE_AND_BATCH_GENERATION_READINESS_REPORT.md"

NEXT_ACTION = (
    "HUMAN DECISION ON A DISTINCT FIRST-BATCH AUTHORIZATION FOR BATCH-01 "
    "(CH001, CH002, CH003, CH004). DO NOT RUN 17 CHAPTERS. "
    "DO NOT TREAT COST ESTIMATES AS AUTHORIZATION."
)
READY_FOR_ALL_17_REAL_GENERATIONS = False

__all__ = [
    "ACCEPTED_CHAPTERS",
    "ACCEPTED_CH012_ID",
    "ACCEPTED_CH018_ID",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_SPEND_USD",
    "BATCH_CHAPTERS",
    "BATCH_IDS",
    "CANONICAL_PYTHON",
    "CH018_EX046",
    "CH018_IDEAS",
    "CH018_SECTIONS",
    "EXPECTED_CH018_JSON_SHA256",
    "EXPECTED_CH018_MD_SHA256",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_PROMPT_1_1_SHA256",
    "EXPECTED_SOURCE_MAP",
    "EXPECTED_TRANSCRIPT",
    "FAITHFUL_PROMPT_1_1",
    "FIRST_BATCH_ID",
    "PHASE",
    "REMAINING_CHAPTER_COUNT",
]
