"""
Phase 4B.2.5.1 — OpenAI / gpt-5.6-terra API compatibility hardening.

Offline only. Zero provider calls. Historical 4B.2.5 remains FAIL.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b24.constants import (
    EXPECTED_BENCHMARK_FILE_SHA256,
    EXPECTED_NEGATIVE_CASES,
    EXPECTED_POSITIVE_CASES,
    EXPECTED_REQUEST_SHA256,
    EXPECTED_SCORED_CASES,
    MODEL,
    OUTPUT_MODE,
    PROVIDER,
)
from app.book_semantic_gate_4b241.constants import (
    CANONICAL_DEPENDENCY_MECHANISM,
    CANONICAL_PYTHON_ENV,
    OPENAI_SDK_CONSTRAINT,
)
from app.book_semantic_gate_4b25.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    EXPECTED_SOURCE_MAP,
    HISTORICAL_4B21_STATUS,
    HISTORICAL_4B22_STATUS,
    HISTORICAL_4B23_STATUS,
    HISTORICAL_4B241_STATUS,
    HISTORICAL_4B24_STATUS,
    HISTORICAL_4B2_STATUS,
)

PHASE = "4B.2.5.1"
PHASE_NAME = "OPENAI_TERRA_API_COMPATIBILITY_HARDENING"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B251_OPENAI_TERRA_API_COMPATIBILITY_HARDENING_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False

HISTORICAL_4B25_STATUS = "FAIL"

EXPECTED_REQUEST_SHA256_HISTORICAL = EXPECTED_REQUEST_SHA256
assert EXPECTED_REQUEST_SHA256_HISTORICAL == (
    "09d6472e544bc60231c77908e6608ff7ee7b6fd4746317f206301082e21eab53"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert OUTPUT_MODE == "json_object"
assert HISTORICAL_4B2_STATUS == "FAIL"
assert HISTORICAL_4B21_STATUS == "PASS"
assert HISTORICAL_4B22_STATUS == "PARTIAL"
assert HISTORICAL_4B23_STATUS == "PASS"
assert HISTORICAL_4B24_STATUS == "FAIL"
assert HISTORICAL_4B241_STATUS == "PASS"
assert HISTORICAL_4B25_STATUS == "FAIL"

SEMANTIC_TOKEN_BUDGET = 8192
PRODUCTION_ENDPOINT = "chat.completions"
CORRECTED_TOKEN_PARAMETER = "max_completion_tokens"

AUDIT_DIRNAME = "book_semantic_gate_4b251"
AUDIT_FORENSICS = "openai_terra_parameter_forensics.json"
AUDIT_MATRIX = "openai_endpoint_capability_matrix.json"
AUDIT_SDK = "openai_sdk_serialization_capture.json"
AUDIT_PREFLIGHT = "openai_provider_preflight_compatibility.json"
AUDIT_REQUEST = "terra_corrected_request_identity.json"
AUDIT_DIFF = "terra_request_semantic_diff.json"
AUDIT_COST = "terra_context_and_cost_estimate.json"
AUDIT_BENCHMARK = "terra_benchmark_identity_regression.json"
AUDIT_ACCOUNTING = "provider_call_accounting_regression.json"
AUDIT_TESTS = "book_semantic_gate_4b251_tests.json"
AUDIT_POST_READINESS = "book_semantic_gate_post_4b251_readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b251_index.json"
REPORT_NAME = "PHASE_4B251_OPENAI_TERRA_API_COMPATIBILITY_HARDENING_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False

__all__ = [
    "AUDIT_ACCOUNTING",
    "AUDIT_BENCHMARK",
    "AUDIT_COST",
    "AUDIT_DIFF",
    "AUDIT_DIRNAME",
    "AUDIT_FORENSICS",
    "AUDIT_INDEX",
    "AUDIT_MATRIX",
    "AUDIT_POST_READINESS",
    "AUDIT_PREFLIGHT",
    "AUDIT_REQUEST",
    "AUDIT_SDK",
    "AUDIT_TESTS",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "CANONICAL_DEPENDENCY_MECHANISM",
    "CANONICAL_PYTHON_ENV",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CORRECTED_TOKEN_PARAMETER",
    "EXPECTED_BENCHMARK_FILE_SHA256",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_NEGATIVE_CASES",
    "EXPECTED_OPENAI_SDK_VERSION",
    "EXPECTED_POSITIVE_CASES",
    "EXPECTED_PYTHON_VERSION",
    "EXPECTED_REQUEST_SHA256",
    "EXPECTED_REQUEST_SHA256_HISTORICAL",
    "EXPECTED_SCORED_CASES",
    "EXPECTED_SOURCE_MAP",
    "HISTORICAL_4B21_STATUS",
    "HISTORICAL_4B22_STATUS",
    "HISTORICAL_4B23_STATUS",
    "HISTORICAL_4B241_STATUS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B25_STATUS",
    "HISTORICAL_4B2_STATUS",
    "MODEL",
    "NEXT_ACTION",
    "OPENAI_SDK_CONSTRAINT",
    "OUTPUT_MODE",
    "PHASE",
    "PHASE_NAME",
    "PRODUCTION_ENDPOINT",
    "PROJECT_NAME",
    "PROVIDER",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "REPORT_NAME",
    "SEMANTIC_TOKEN_BUDGET",
    "TERRA_EXECUTION_AUTHORIZED",
]
