"""4B.2.5.1 report renderer. No secrets."""

from __future__ import annotations

from typing import Any, Mapping


def _yn(value: Any) -> str:
    if value in (True, "YES", "PASS", "yes", "pass"):
        return "YES"
    if value in (False, "NO", "FAIL", "no", "fail"):
        return "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any]) -> str:
    header = dict(bundle.get("header") or {})
    lines = [
        "# PHASE 4B.2.5.1 — OPENAI / GPT-5.6-TERRA API COMPATIBILITY HARDENING",
        "",
        "## Result",
        "",
        str(header.get("result") or "FAIL"),
        "",
        "Provider calls =",
        str(header.get("provider_calls") if header.get("provider_calls") is not None else 0),
        "",
        "OpenAI HTTP =",
        str(header.get("openai_http") if header.get("openai_http") is not None else 0),
        "",
        "Anthropic HTTP =",
        str(header.get("anthropic_http") if header.get("anthropic_http") is not None else 0),
        "",
        "Historical 4B.2.5 FAIL unchanged =",
        str(header.get("historical_4b25") or "FAIL"),
        "",
        "Canonical Python executable =",
        str(header.get("python_executable") or ""),
        "",
        "OpenAI SDK version =",
        str(header.get("openai_sdk_version") or ""),
        "",
        "Actual endpoint =",
        str(header.get("actual_endpoint") or ""),
        "",
        "Root cause =",
        str(header.get("root_cause") or ""),
        "",
        "Historical request SHA256 =",
        str(header.get("historical_request_sha256") or ""),
        "",
        "Corrected request SHA256 =",
        str(header.get("corrected_request_sha256") or ""),
        "",
        "Exact parameter changes =",
        str(header.get("exact_parameter_changes") or ""),
        "",
        "SDK serialization =",
        str(header.get("sdk_serialization") or ""),
        "",
        "Token limit 8192 =",
        str(header.get("token_limit") or ""),
        "",
        "Temperature omitted =",
        str(header.get("temperature_omitted") or ""),
        "",
        "json_object compatibility local =",
        str(header.get("json_object_local") or ""),
        "",
        "Other server-side capabilities =",
        str(header.get("other_server_capabilities") or "UNKNOWN"),
        "",
        "Benchmark identity =",
        str(header.get("benchmark_identity") or ""),
        "",
        "10/10 cases present =",
        _yn(header.get("cases_10_of_10")),
        "",
        "Label leakage =",
        str(header.get("label_leakage") if header.get("label_leakage") is not None else ""),
        "",
        "Canonical input hashes pre/post =",
        str(header.get("canonical_input_hashes") or ""),
        "",
        "Tests passed/failed =",
        str(header.get("tests") or ""),
        "",
        "New regressions =",
        str(header.get("new_regressions") if header.get("new_regressions") is not None else 0),
        "",
        "Production cache =",
        "UNCHANGED",
        "",
        "book.json =",
        "NOT PUBLISHED",
        "",
        "READY_FOR_ONE_NEW_EXPLICITLY_AUTHORIZED_TERRA_CANARY =",
        _yn(header.get("ready_for_one_new_explicitly_authorized_terra_canary")),
        "",
        "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT =",
        "NO",
        "",
        "READY_FOR_FULL_REAL_BOOK_GENERATION =",
        "NO",
        "",
        "Next action =",
        "HUMAN REVIEW",
        "",
        "## Historical status",
        "",
        "4B.2 = FAIL",
        "4B.2.1 = PASS",
        "4B.2.2 = PARTIAL",
        "4B.2.3 = PASS",
        "4B.2.4 = FAIL",
        "4B.2.4.1 = PASS",
        "4B.2.5 = FAIL",
        "",
        "Do not rewrite any historical result.",
        "",
        "## Notes",
        "",
        str(header.get("notes") or ""),
        "",
        "This phase does not authorize a Terra call.",
        "Wait for human review.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
