"""Constantes 3B.7.7A.42 — second synthetic contract canary, prompt 2.0.1."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis_v31_global_drop_domain.constants import (
    A40_FIXTURE_HASH,
    A40_PROMPT_HASH,
    A40_STATUS_PRESERVED,
    A40_VIOLATING_ID,
    COMPACT_20_CHARS_PER_TOKEN_CONSERVATIVE,
    COMPACT_20_CHARS_PER_TOKEN_OBSERVED,
    DROP_DOMAIN,
    NEXT_PROMPT_VERSION,
    OLD_PROMPT_VERSION,
    OLD_TRANSPORT_VERSION,
    PRODUCTION_MAX_OUTPUT_TOKENS as A41_MAX_OUTPUT,
    SCHEMA_CHANGED,
    SECOND_COMPACT_CONTRACT_CANARY_REQUIRED,
    SELECTED_HARDENING,
    V20_SCHEMA_ADAPTED_BYTES,
    V20_SCHEMA_HASH,
    V20_SCHEMA_RAW_BYTES,
    V20_TRANSPORT_VERSION,
)
from app.source_analysis_v31_global_grammar_canary.constants import (
    CANARY_CONNECT_TIMEOUT_SECONDS,
    CANARY_READ_TIMEOUT_SECONDS,
    FROZEN_GRANULARITY,
    FROZEN_PLANNER,
    FROZEN_PROMPT,
    FROZEN_SRC_POLICY,
    FROZEN_TRANSPORT,
    HANDLE_PREFIX_BY_KIND,
    MODEL,
    NODE_KINDS,
    NORMAL_FINISH_REASONS,
    PASTORAL_MARKERS,
    PRODUCTION_SRC_PATTERN,
    PROJECT_NAME,
    PROVIDER,
    THINKING_CONTRACT,
    THINKING_MODE,
)
from app.source_analysis_v31_global_output_architecture.constants import (
    A34_STATUS_PRESERVED,
    A35_STATUS_PRESERVED,
    A36_STATUS_PRESERVED,
    A37_STATUS_PRESERVED,
    A38_STATUS_PRESERVED,
    DROP_REASONS_V20,
    NEXT_SCHEMA_ARTIFACT,
    RETIRED_DISPOSITION_OPS_V20,
    RETIRED_DROP_REASONS_V20,
    TEXT_LIMITS,
)
from app.source_analysis_v31_global_preflight.constants import (
    IDEA_DISPOSITION_COVERAGE_REQUIRED,
    IDEA_KIND_POLICY,
    READY_LABEL,
    RELATION_QUALITY_TECHNICAL_DEBT,
)
from app.source_analysis_v31_global_v20_grammar_canary.constants import (
    FORBIDDEN_TRANSCRIPT_IDS,
    FORBIDDEN_WINDOW_IDS,
    SYNTHETIC_NAMESPACE,
    SYNTHETIC_SRC_IDS,
    SYNTHETIC_WINDOW_IDS,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.42"
MODE = "GLOBAL_CONSOLIDATION_2_0_1_SECOND_SYNTHETIC_CONTRACT_CANARY"
AUTHORIZATION_SCOPE = (
    "GLOBAL_CONSOLIDATION_2_0_1_SECOND_SYNTHETIC_CONTRACT_CANARY_ONLY"
)

A39_STATUS_PRESERVED = "PASS"
A41_STATUS_PRESERVED = "PASS"
assert A34_STATUS_PRESERVED == "PASS"
assert A35_STATUS_PRESERVED == "FAIL"
assert A36_STATUS_PRESERVED == "PASS"
assert A37_STATUS_PRESERVED == "PASS"
assert A38_STATUS_PRESERVED == "FAIL"
assert A39_STATUS_PRESERVED == "PASS"
assert A40_STATUS_PRESERVED == "FAIL"
assert A41_STATUS_PRESERVED == "PASS"
assert SECOND_COMPACT_CONTRACT_CANARY_REQUIRED is True
assert SCHEMA_CHANGED is False
assert SELECTED_HARDENING == "PROMPT_2_0_1_PLUS_HANDLE_AND_PUBLICATION_GATES"
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert THINKING_MODE == "disabled"
assert OLD_PROMPT_VERSION == "global-consolidation-2.0"
assert NEXT_PROMPT_VERSION == "global-consolidation-2.0.1"
assert V20_TRANSPORT_VERSION == "global-consolidation-transport-2.0"
assert V20_SCHEMA_RAW_BYTES == 1588
assert V20_SCHEMA_ADAPTED_BYTES == 1836
assert V20_SCHEMA_HASH == (
    "90b99a38ac704d00e1304495da0c757118293e43493ddb7321b3ffb3256d8330"
)
assert DROP_REASONS_V20 == ("transport_artifact", "non_substantive_fragment")
assert RETIRED_DROP_REASONS_V20 == ("exact_duplicate",)
assert RETIRED_DISPOSITION_OPS_V20 == ("OTHER",)
assert IDEA_KIND_POLICY == "KEEP_EMPTY_GLOBALLY"
assert IDEA_DISPOSITION_COVERAGE_REQUIRED == 100
assert READY_LABEL == "7 / 7"
assert DROP_DOMAIN == "LOCAL_IDEA_ONLY"

PROMPT_VERSION = NEXT_PROMPT_VERSION
TRANSPORT_VERSION = OLD_TRANSPORT_VERSION
SCHEMA_RAW_BYTES = V20_SCHEMA_RAW_BYTES
SCHEMA_ADAPTED_BYTES = V20_SCHEMA_ADAPTED_BYTES
SCHEMA_HASH = V20_SCHEMA_HASH
A39_SCHEMA_ARTIFACT = NEXT_SCHEMA_ARTIFACT
A40_PROMPT_VERSION = OLD_PROMPT_VERSION
GLOBAL_TRANSPORT_2_0_GRAMMAR_PROOF = "PASS"
NEW_GRAMMAR_CANARY_REQUIRED = False

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False
EFFORT = None

CANARY_MAX_OUTPUT_TOKENS = 2048
PRODUCTION_MAX_OUTPUT_TOKENS = A41_MAX_OUTPUT
PRODUCTION_EXPECTED_OUTPUT_TOKENS = 34514
PRODUCTION_CONSERVATIVE_OUTPUT_TOKENS = 40362
PRODUCTION_HARD_PLANNING_TOKENS = 41430
PRODUCTION_OUTPUT_RISK = "NEEDS_OUTPUT_REDESIGN"
assert PRODUCTION_MAX_OUTPUT_TOKENS == 48000
PRODUCTION_UTILIZATION_EXPECTED = (
    PRODUCTION_EXPECTED_OUTPUT_TOKENS / PRODUCTION_MAX_OUTPUT_TOKENS
)
PRODUCTION_UTILIZATION_CONSERVATIVE = (
    PRODUCTION_CONSERVATIVE_OUTPUT_TOKENS / PRODUCTION_MAX_OUTPUT_TOKENS
)
PRODUCTION_UTILIZATION_HARD = (
    PRODUCTION_HARD_PLANNING_TOKENS / PRODUCTION_MAX_OUTPUT_TOKENS
)

CANARY_VERSION = "global-consolidation-tiny-contract-canary-v201-1.0"
STAGE_CANARY = "source_analysis_v31_global_v201_contract_canary"
CANARY_SUBDIR = "canary/global_consolidation_prompt_v201"
CANARY_WINDOW_ID = "SYN_GLOBAL_V201"
CANARY_TRANSCRIPT_ID = "TR_CANARY_GARDEN_A42"
LOCK_NAME = "canary_real_call.lock"
RELATION_HINT_ID = A40_VIOLATING_ID
assert RELATION_HINT_ID == "SYN:L001"

FIXTURE_ARTIFACT = "global_consolidation_v201_synthetic_fixture.json"
REQUEST_ARTIFACT = "global_consolidation_v201_canary_request.json"
TYPE_BOUNDARY_ARTIFACT = "global_consolidation_v201_type_boundary_audit.json"
MEMBERSHIP_ARTIFACT = "global_consolidation_v201_membership_audit.json"
DERIVED_SRC_ARTIFACT = "global_consolidation_v201_derived_src_audit.json"
VALIDATOR_ARTIFACT = "global_consolidation_v201_validator_result.json"
CANONICAL_ARTIFACT = "global_consolidation_v201_canonical_reconstruction.json"
ESTIMATOR_ARTIFACT = "global_consolidation_v201_estimator_comparison.json"
USAGE_ARTIFACT = "global_consolidation_v201_usage_cost.json"
READINESS_ARTIFACT = "global_consolidation_post_a42_readiness.json"
EXECUTION_ARTIFACT = "global_consolidation_v201_canary_execution.json"
REPORT_NAME = (
    "PHASE_3B77A42_COMPACT_GLOBAL_CONSOLIDATION_V201_CONTRACT_CANARY_REPORT.md"
)
BASELINE_ARTIFACT = "source_analysis_a42_test_baseline.json"
POST_TEST_ARTIFACT = "source_analysis_a42_test_delta.json"

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_v201_contract_canary.py",
    "app/tests/test_source_analysis_v31_global_v201_contract_canary_audit.py",
    "app/tests/test_source_analysis_v31_global_drop_domain.py",
    "app/tests/test_source_analysis_v31_global_drop_domain_audit.py",
    "app/tests/test_source_analysis_v31_global_v20_grammar_canary.py",
    "app/tests/test_source_analysis_v31_global_output_architecture.py",
)
BROADER_SLICE_TEST_PATHS = FOCUSED_TEST_PATHS + (
    "app/tests/test_source_analysis_v31_global_v20_grammar_canary_audit.py",
    "app/tests/test_source_analysis_v31_global_output_architecture_audit.py",
)

DRY_RUN_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v31_global_v201_contract_canary "
    "pastoral_retreat_v2_validation "
    "--authorization-scope "
    "GLOBAL_CONSOLIDATION_2_0_1_SECOND_SYNTHETIC_CONTRACT_CANARY_ONLY "
    "--dry-run"
)
REAL_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v31_global_v201_contract_canary "
    "pastoral_retreat_v2_validation "
    "--authorization-scope "
    "GLOBAL_CONSOLIDATION_2_0_1_SECOND_SYNTHETIC_CONTRACT_CANARY_ONLY "
    "--execute-real"
)

PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
NEXT_ACTION = "HUMAN REVIEW"
LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN = "YES"
READY_WINDOWS = READY_LABEL
READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY = "NO"
READY_FOR_COMPACT_GLOBAL_REAL_CALL_PREFLIGHT = "NO"
CONSOLIDATION_AUTHORIZED = False
SOURCE_MAP_PUBLICATION_AUTHORIZED = False

assert not source_map_path(PROJECT_NAME).is_file() or SOURCE_MAP_STATUS == "NOT PUBLISHED"
assert RELATION_QUALITY_TECHNICAL_DEBT == "YES"
assert FROZEN_PLANNER == "window-planner-v2.1-small"
assert FROZEN_PROMPT == "window-analysis-1.4.0"
assert FROZEN_TRANSPORT == "semantic-transport-v3.1-local-lite"
assert FROZEN_GRANULARITY == "window-granularity-1.2-kind-specific"
assert FROZEN_SRC_POLICY == "src-reference-policy-1.1-narrow-canonicalization"

__all__ = [
    "A34_STATUS_PRESERVED",
    "A35_STATUS_PRESERVED",
    "A36_STATUS_PRESERVED",
    "A37_STATUS_PRESERVED",
    "A38_STATUS_PRESERVED",
    "A39_SCHEMA_ARTIFACT",
    "A39_STATUS_PRESERVED",
    "A40_FIXTURE_HASH",
    "A40_PROMPT_HASH",
    "A40_PROMPT_VERSION",
    "A40_STATUS_PRESERVED",
    "A41_STATUS_PRESERVED",
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "BASELINE_ARTIFACT",
    "BROADER_SLICE_TEST_PATHS",
    "CANARY_CONNECT_TIMEOUT_SECONDS",
    "CANARY_MAX_OUTPUT_TOKENS",
    "CANARY_READ_TIMEOUT_SECONDS",
    "CANARY_SUBDIR",
    "CANARY_TRANSCRIPT_ID",
    "CANARY_VERSION",
    "CANARY_WINDOW_ID",
    "CANONICAL_ARTIFACT",
    "COMPACT_20_CHARS_PER_TOKEN_CONSERVATIVE",
    "COMPACT_20_CHARS_PER_TOKEN_OBSERVED",
    "CONSOLIDATION_AUTHORIZED",
    "DERIVED_SRC_ARTIFACT",
    "DROP_DOMAIN",
    "DROP_REASONS_V20",
    "DRY_RUN_COMMAND",
    "EFFORT",
    "ESTIMATOR_ARTIFACT",
    "EXECUTION_ARTIFACT",
    "FIXTURE_ARTIFACT",
    "FOCUSED_TEST_PATHS",
    "FORBIDDEN_TRANSCRIPT_IDS",
    "FORBIDDEN_WINDOW_IDS",
    "FROZEN_GRANULARITY",
    "FROZEN_PLANNER",
    "FROZEN_PROMPT",
    "FROZEN_SRC_POLICY",
    "FROZEN_TRANSPORT",
    "GLOBAL_TRANSPORT_2_0_GRAMMAR_PROOF",
    "HANDLE_PREFIX_BY_KIND",
    "IDEA_DISPOSITION_COVERAGE_REQUIRED",
    "IDEA_KIND_POLICY",
    "LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN",
    "LOCK_NAME",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MEMBERSHIP_ARTIFACT",
    "MODE",
    "MODEL",
    "NEW_GRAMMAR_CANARY_REQUIRED",
    "NEXT_ACTION",
    "NODE_KINDS",
    "NORMAL_FINISH_REASONS",
    "PASTORAL_MARKERS",
    "PHASE",
    "PHASE_3B_STATUS",
    "POST_TEST_ARTIFACT",
    "PRODUCTION_CONSERVATIVE_OUTPUT_TOKENS",
    "PRODUCTION_EXPECTED_OUTPUT_TOKENS",
    "PRODUCTION_HARD_PLANNING_TOKENS",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PRODUCTION_OUTPUT_RISK",
    "PRODUCTION_SRC_PATTERN",
    "PRODUCTION_UTILIZATION_CONSERVATIVE",
    "PRODUCTION_UTILIZATION_EXPECTED",
    "PRODUCTION_UTILIZATION_HARD",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROVIDER",
    "READINESS_ARTIFACT",
    "READY_FOR_COMPACT_GLOBAL_REAL_CALL_PREFLIGHT",
    "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY",
    "READY_WINDOWS",
    "REAL_COMMAND",
    "RELATION_HINT_ID",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPORT_NAME",
    "REQUEST_ARTIFACT",
    "RETIRED_DISPOSITION_OPS_V20",
    "RETIRED_DROP_REASONS_V20",
    "SCHEMA_ADAPTED_BYTES",
    "SCHEMA_CHANGED",
    "SCHEMA_HASH",
    "SCHEMA_RAW_BYTES",
    "SCHEMA_VERSION",
    "SOURCE_MAP_PUBLICATION_AUTHORIZED",
    "SOURCE_MAP_STATUS",
    "STAGE_CANARY",
    "SYNTHETIC_NAMESPACE",
    "SYNTHETIC_SRC_IDS",
    "SYNTHETIC_WINDOW_IDS",
    "TEXT_LIMITS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
    "TYPE_BOUNDARY_ARTIFACT",
    "USAGE_ARTIFACT",
    "VALIDATOR_ARTIFACT",
]
