"""Constantes 3B.7.7A.22 — second independent real-window canary. 1 appel max."""

from __future__ import annotations

from app.source_analysis.window_models import (
    WINDOW_CONNECT_TIMEOUT_SECONDS,
    WINDOW_READ_TIMEOUT_SECONDS,
)
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    CLEAN_SHA,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
    SELECTED_ARCHITECTURE,
    SEMANTIC_TRANSPORT_VERSION_V3,
    TARGET_JSON_LOCAL_TOKENS,
    WINDOW_ANALYSIS_PROMPT_VERSION_V13,
    WINDOW_ANALYSIS_PROMPT_VERSION_V131,
)
from app.source_analysis_local_v3.schema import semantic_transport_v3_fingerprint
from app.source_analysis_output_ceiling_review.constants import (
    CALL1_SIGNATURE,
    CALL2_SIGNATURE,
    SMALL_SIGNATURE,
)
from app.source_analysis_small_window_hierarchy.constants import (
    CANDIDATE_CONTEXT_POLICY,
)
from app.source_analysis_small_window_readiness.constants import A7_EXPECTED_WINDOWS
from app.source_analysis_thinking_contract.constants import (
    SELECTED_CONTRACT,
    SELECTED_EFFORT,
    SELECTED_THINKING_MODE,
)
from app.source_analysis_v2_a15_forensics.constants import A15_SIGNATURE
from app.source_analysis_v2_link_semantics.constants import A13_REQUEST_IDENTITY
from app.source_analysis_v3_a19_forensics.constants import (
    A19_STATUS_UNCHANGED,
    EXAMPLE_POLICY,
    EXAMPLE_POLICY_LABEL,
    PROTECTED_A19,
    REPORT_NAME as A20_REPORT,
    SRC_CONTRACT_ARTIFACT,
    EXAMPLE_POLICY_ARTIFACT,
    SEMANTIC_ARTIFACT,
    COVERAGE_ARTIFACT,
    FUTURE_RETRY_ARTIFACT,
    VIOLATION_ARTIFACT,
    V3_HANDLE_ARCHITECTURE,
)
from app.source_analysis_v3_hardened_win001.constants import (
    AUTHORIZATION_SCOPE as A21_AUTHORIZATION_SCOPE,
    CANARY_SUBDIR as A21_CANARY_SUBDIR,
    COMPARISON_ARTIFACT as A21_COMPARISON_ARTIFACT,
    EXECUTION_ARTIFACT as A21_EXECUTION_ARTIFACT,
    EXPECTED_ANALYSIS_SIGNATURE as A21_SIGNATURE,
    EXPECTED_FORENSIC_IDENTITY as A21_FORENSIC,
    EXPECTED_LOCAL_INPUT_ESTIMATE as A21_LOCAL_INPUT,
    EXPECTED_OWNED_SRC_COUNT as A21_OWNED_SRC_COUNT,
    EXPECTED_PROMPT_FINGERPRINT,
    EXPECTED_PROMPT_SHA256,
    EXPECTED_SCHEMA_HASH,
    EXPECTED_WORD_COUNT as A21_WORD_COUNT,
    HANDLE_ARTIFACT as A21_HANDLE_ARTIFACT,
    LOCK_NAME as A21_LOCK_NAME,
    PREFLIGHT_ARTIFACT as A21_PREFLIGHT_ARTIFACT,
    PROTECTED_HISTORICAL as A21_PROTECTED_HISTORICAL,
    REPORT_NAME as A21_REPORT_NAME,
    REVIEW_ARTIFACT as A21_REVIEW_ARTIFACT,
    SRC_ARTIFACT as A21_SRC_ARTIFACT,
    WINDOW_ID as A21_WINDOW_ID,
)
from app.source_analysis_v3_real_win001.constants import (
    EXPECTED_A18_REQUEST_IDENTITY,
    EXPECTED_ANALYSIS_SIGNATURE as A19_SIGNATURE,
    EXPECTED_FORENSIC_IDENTITY as A19_FORENSIC,
    PROTECTED_HISTORICAL as A19_PROTECTED_HISTORICAL,
    REPORT_NAME as A19_CANARY_REPORT,
)
from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.22"
MODE = "REAL_V3_SMALL_SECOND_INDEPENDENT_WINDOW_CANARY"

AUTHORIZATION_SCOPE = "SMALL_V21_V3_SECOND_WINDOW_CANARY_ONLY"
PREFERRED_WINDOW_ID = "WIN004"
CANDIDATE_WINDOW_IDS = (
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
)
FALLBACK_ORDER = (
    "WIN003",
    "WIN005",
    "WIN002",
    "WIN006",
    "WIN007",
)
FORBIDDEN_ALWAYS = ("WIN001", "WIN996")

PROVIDER = "anthropic"
MODEL = "claude-sonnet-5"
THINKING_CONTRACT = SELECTED_CONTRACT
THINKING_MODE = SELECTED_THINKING_MODE
EFFORT = SELECTED_EFFORT

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False

MAX_OUTPUT_TOKENS = MAX_OUTPUT_TOKENS_FROZEN
CONNECT_TIMEOUT_SECONDS = WINDOW_CONNECT_TIMEOUT_SECONDS
READ_TIMEOUT_SECONDS = WINDOW_READ_TIMEOUT_SECONDS
HISTORICAL_READ_TIMEOUT_SECONDS = 7200.0

WIN004_PLAN = next(
    item for item in A7_EXPECTED_WINDOWS if item["window_id"] == "WIN004"
)
EXPECTED_WIN004_FIRST_OWNED_SRC = WIN004_PLAN["first_present_src"]
EXPECTED_WIN004_LAST_OWNED_SRC = WIN004_PLAN["last_present_src"]
EXPECTED_WIN004_OWNED_SRC_COUNT = WIN004_PLAN["owned_src_count"]
EXPECTED_WIN004_WORD_COUNT = WIN004_PLAN["word_count"]
EXPECTED_WIN004_INPUT_HASH = (
    "f212ca29f5f8748035a4fece9ce36c5a87ef11d64e19ad489ec48f0a4421b393"
)
EXPECTED_CLEAN_SHA = CLEAN_SHA
EXPECTED_CLEAN_FILE_SHA = CLEAN_SHA
EXPECTED_CONTEXT_COUNT = 0
EXPECTED_CONTEXT_POLICY = CANDIDATE_CONTEXT_POLICY

A13_SYNTHETIC_IDENTITY = A13_REQUEST_IDENTITY
A15_V2_SIGNATURE = A15_SIGNATURE
A18_REQUEST_IDENTITY = EXPECTED_A18_REQUEST_IDENTITY
A19_V3_SIGNATURE = A19_SIGNATURE
A19_V3_FORENSIC = A19_FORENSIC
A19_RESULT = A19_STATUS_UNCHANGED
A21_V3_SIGNATURE = A21_SIGNATURE
A21_V3_FORENSIC = A21_FORENSIC
A21_RESULT = "PASS"
A21_READY = "1 / 7"
A21_SRC_RANGE = "SRC000001 → SRC001201"
A21_OWNED = A21_OWNED_SRC_COUNT
A21_WORDS = A21_WORD_COUNT
A21_LOCAL = A21_LOCAL_INPUT
A21_INPUT_TOKENS = 48898
A21_OUTPUT_TOKENS = 8892
A21_THINKING_TOKENS = 0
A21_RECORDS = 89
A21_TOPIC = 11
A21_IDEA = 39
A21_RELATION = 18
A21_EXAMPLE = 5
A21_REFERENCE = 11
A21_UNCERTAINTY = 5
A21_TOTAL_SRC_OCCURRENCES = 259
A21_VALID_SRC_OCCURRENCES = 259
A21_COVERAGE_PCT = 17.24
A21_QUALITY = "ACCEPTABLE_FOR_LOCAL_EXTRACTION"
A21_COST_DISPLAY = "0.1867160 USD"
A21_ELAPSED_MS = 79202
A21_HTTP = 200
A21_FINISH = "end_turn"
A21_REQUEST_ID = "req_011CfSgK9LZacScVs5fhQjwa"
A21_PROMPT = WINDOW_ANALYSIS_PROMPT_VERSION_V131

SYNTHETIC_WORST_CASE_LOCAL_TOKENS = 12185

LOCK_NAME = "a22_real_v3_second_window.lock"
CANARY_SUBDIR = "canary/v3_second_window"
CANDIDATE_WINDOWS_SUBDIR = "v3_windows"
CANDIDATE_CACHE_SUBDIR = "v3_cache"

SELECTION_ARTIFACT = "source_analysis_v3_second_window_selection.json"
PREFLIGHT_ARTIFACT = "source_analysis_v3_second_window_preflight.json"
EXECUTION_ARTIFACT = "source_analysis_v3_second_window_execution.json"
SRC_ARTIFACT = "source_analysis_v3_second_window_src_analysis.json"
HANDLE_ARTIFACT = "source_analysis_v3_second_window_handle_analysis.json"
REVIEW_ARTIFACT = "source_analysis_v3_second_window_semantic_review.json"
COMPARISON_ARTIFACT = "source_analysis_v3_win001_vs_second_window_evidence.json"
REPORT_NAME = "PHASE_3B77A22_SECOND_INDEPENDENT_REAL_WINDOW_CANARY_REPORT.md"

SEMANTIC_REVIEW_STATUS = (
    "FORENSIC_SEMANTIC_REVIEW_OF_VALID_V3_SECOND_WINDOW_CANDIDATE"
)
SEMANTIC_REVIEW_INVALID = "FORENSIC_SEMANTIC_REVIEW_OF_INVALID_V3_TRANSPORT"
EXAMPLE_POLICY = EXAMPLE_POLICY
EXAMPLE_POLICY_LABEL = EXAMPLE_POLICY_LABEL

A21_CACHE_RELATIVE = (
    f"audit/{A21_CANARY_SUBDIR}/v3_cache/{A21_SIGNATURE}/{A21_WINDOW_ID}/transport.json"
)
A21_CACHE_META_RELATIVE = (
    f"audit/{A21_CANARY_SUBDIR}/v3_cache/{A21_SIGNATURE}/{A21_WINDOW_ID}/metadata.json"
)
A21_WINDOW_RELATIVE = (
    f"audit/{A21_CANARY_SUBDIR}/v3_windows/{A21_WINDOW_ID}/transport.json"
)
A21_WINDOW_META_RELATIVE = (
    f"audit/{A21_CANARY_SUBDIR}/v3_windows/{A21_WINDOW_ID}/metadata.json"
)
A21_LOCK_RELATIVE = f"audit/{A21_CANARY_SUBDIR}/{A21_LOCK_NAME}"
A21_FORENSIC_RELATIVE = (
    f"audit/{A21_CANARY_SUBDIR}/provider_forensics/{A21_WINDOW_ID}/{A21_SIGNATURE}"
)

PROTECTED_A21 = (
    f"audit/{A21_REPORT_NAME}",
    f"audit/{A21_PREFLIGHT_ARTIFACT}",
    f"audit/{A21_EXECUTION_ARTIFACT}",
    f"audit/{A21_SRC_ARTIFACT}",
    f"audit/{A21_HANDLE_ARTIFACT}",
    f"audit/{A21_REVIEW_ARTIFACT}",
    f"audit/{A21_COMPARISON_ARTIFACT}",
    A21_LOCK_RELATIVE,
    A21_CACHE_RELATIVE,
    A21_CACHE_META_RELATIVE,
    A21_WINDOW_RELATIVE,
    A21_WINDOW_META_RELATIVE,
    f"{A21_FORENSIC_RELATIVE}/provider_raw_response.bin",
    f"{A21_FORENSIC_RELATIVE}/provider_http_envelope.json",
)

PROTECTED_HISTORICAL = A21_PROTECTED_HISTORICAL + PROTECTED_A21

DRY_RUN_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v3_second_window "
    "pastoral_retreat_v2_validation "
    "--authorization-scope SMALL_V21_V3_SECOND_WINDOW_CANARY_ONLY "
    "--window WIN004 --dry-run"
)
REAL_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v3_second_window "
    "pastoral_retreat_v2_validation "
    "--authorization-scope SMALL_V21_V3_SECOND_WINDOW_CANARY_ONLY "
    "--window WIN004 --execute-real"
)

NEXT_ACTION = "HUMAN REVIEW"
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION
PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V131
TRANSPORT_VERSION = SEMANTIC_TRANSPORT_VERSION_V3
SERVER_GRAMMAR_STATUS = "VERIFIED ACCEPTED"

assert EXPECTED_SCHEMA_HASH == (
    "de42ce0f3c271e67b902a94d2f528eae56f82b1a2a5740e65161987038849425"
)
assert semantic_transport_v3_fingerprint() == EXPECTED_SCHEMA_HASH
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert MAX_OUTPUT_TOKENS == 32000
assert THINKING_MODE == "disabled"
assert EFFORT is None
assert AUTHORIZATION_SCOPE == "SMALL_V21_V3_SECOND_WINDOW_CANARY_ONLY"
assert AUTHORIZATION_SCOPE != A21_AUTHORIZATION_SCOPE
assert PREFERRED_WINDOW_ID != A21_WINDOW_ID
assert A21_RESULT == "PASS"
assert A19_RESULT == "FAIL"

__all__ = [
    "A13_SYNTHETIC_IDENTITY",
    "A15_V2_SIGNATURE",
    "A18_REQUEST_IDENTITY",
    "A19_RESULT",
    "A19_V3_FORENSIC",
    "A19_V3_SIGNATURE",
    "A21_AUTHORIZATION_SCOPE",
    "A21_COST_DISPLAY",
    "A21_COVERAGE_PCT",
    "A21_ELAPSED_MS",
    "A21_EXAMPLE",
    "A21_FINISH",
    "A21_HTTP",
    "A21_IDEA",
    "A21_INPUT_TOKENS",
    "A21_LOCAL",
    "A21_OUTPUT_TOKENS",
    "A21_OWNED",
    "A21_PROMPT",
    "A21_QUALITY",
    "A21_READY",
    "A21_RECORDS",
    "A21_REFERENCE",
    "A21_RELATION",
    "A21_REQUEST_ID",
    "A21_RESULT",
    "A21_SRC_RANGE",
    "A21_THINKING_TOKENS",
    "A21_TOPIC",
    "A21_TOTAL_SRC_OCCURRENCES",
    "A21_UNCERTAINTY",
    "A21_VALID_SRC_OCCURRENCES",
    "A21_V3_FORENSIC",
    "A21_V3_SIGNATURE",
    "A21_WINDOW_ID",
    "A21_WORDS",
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "CALL1_SIGNATURE",
    "CALL2_SIGNATURE",
    "CANARY_SUBDIR",
    "CANDIDATE_CACHE_SUBDIR",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER",
    "CANDIDATE_WINDOW_IDS",
    "CANDIDATE_WINDOWS_SUBDIR",
    "COMPARISON_ARTIFACT",
    "CONNECT_TIMEOUT_SECONDS",
    "DRY_RUN_COMMAND",
    "EFFORT",
    "EXAMPLE_POLICY",
    "EXAMPLE_POLICY_LABEL",
    "EXECUTION_ARTIFACT",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_CLEAN_FILE_SHA",
    "EXPECTED_CLEAN_SHA",
    "EXPECTED_CONTEXT_COUNT",
    "EXPECTED_CONTEXT_POLICY",
    "EXPECTED_PROMPT_FINGERPRINT",
    "EXPECTED_PROMPT_SHA256",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "EXPECTED_SCHEMA_HASH",
    "EXPECTED_WIN004_FIRST_OWNED_SRC",
    "EXPECTED_WIN004_INPUT_HASH",
    "EXPECTED_WIN004_LAST_OWNED_SRC",
    "EXPECTED_WIN004_OWNED_SRC_COUNT",
    "EXPECTED_WIN004_WORD_COUNT",
    "FALLBACK_ORDER",
    "FORBIDDEN_ALWAYS",
    "HANDLE_ARTIFACT",
    "HISTORICAL_READ_TIMEOUT_SECONDS",
    "LOCK_NAME",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MAX_OUTPUT_TOKENS",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "PHASE",
    "PHASE_3B_STATUS",
    "PREFERRED_WINDOW_ID",
    "PREFLIGHT_ARTIFACT",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROTECTED_A21",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "READ_TIMEOUT_SECONDS",
    "REAL_COMMAND",
    "REPORT_NAME",
    "REVIEW_ARTIFACT",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SELECTION_ARTIFACT",
    "SEMANTIC_REVIEW_INVALID",
    "SEMANTIC_REVIEW_STATUS",
    "SERVER_GRAMMAR_STATUS",
    "SMALL_SIGNATURE",
    "SRC_ARTIFACT",
    "SYNTHETIC_WORST_CASE_LOCAL_TOKENS",
    "TARGET_JSON_LOCAL_TOKENS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
    "V3_HANDLE_ARCHITECTURE",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V13",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V131",
]
