"""
Phase 4B.2.8 — Semantic gate comparative forensics and architecture design.

STRICTLY OFFLINE. Architecture and experimental prototype only.
Zero provider calls. Historical canaries are not relaunched.
Frozen 1.0 / 1.1 / 1.1.1 / 1.1.2 / 1.1.3-candidate are not modified.
1.1.3-candidate is not promoted. 2.0-proposal is not activated.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
)
from app.book_semantic_gate_4b24.constants import (
    CONNECTIVE_CASE_ID,
    FUNERAL_CASE_ID,
    NEGATIVE_CASE_IDS,
    P3_CASE_ID,
    P8_CASE_ID,
    POSITIVE_CASE_IDS,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE
from app.book_semantic_gate_4b261.constants import CANDIDATE_PROMPT_VERSION
from app.book_semantic_gate_4b27.constants import (
    EXPECTED_REQUEST_SHA256 as H01_REQUEST_SHA256,
    HISTORICAL_4B261_STATUS,
    HISTORICAL_4B262_STATUS,
    HISTORICAL_4B26_STATUS,
)
from app.book_semantic_gate_4b271.constants import (
    DISPUTED_CLAUSE as H01_DISPUTED_CLAUSE,
    HISTORICAL_4B27_STATUS,
    TRANSPORT_VERSION_11,
)
from app.book_semantic_gate_4b272.constants import (
    DISPUTED_CAUSAL_CLAUSE,
    HISTORICAL_4B271_STATUS,
    OBSERVED_4B27_COMPLETION_TOKENS,
    OBSERVED_4B27_COST_USD,
    OBSERVED_4B27_INPUT_TOKENS,
    OBSERVED_4B27_REASONING_TOKENS,
    P3_EVIDENCE_HANDLES,
)
from app.book_semantic_gate_4b273.constants import (
    EXPECTED_REQUEST_SHA256 as H02_REQUEST_SHA256,
    HISTORICAL_4B272_STATUS,
)
from app.book_semantic_gate_4b274.constants import (
    H01_GAPS,
    H02_GAPS,
    HISTORICAL_4B273_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    PROMPT_VERSION_112,
)
from app.book_semantic_gate_4b275.constants import (
    HISTORICAL_4B274_STATUS,
    PROMPT_VERSION_113,
)
from app.book_semantic_gate_4b276.constants import (
    DISPUTED_CLAUSE as H11_DISPUTED_CLAUSE,
    H02_COMPLETION_TOKENS,
    H02_COST_USD,
    H02_INPUT_TOKENS,
    H02_REASONING_TOKENS,
    HISTORICAL_4B275_STATUS,
    P4_EVIDENCE_HANDLES,
)
from app.book_semantic_gate_4b277.constants import (
    EXPECTED_REQUEST_SHA256 as H11_REQUEST_SHA256,
    HISTORICAL_4B276_STATUS,
)

PHASE = "4B.2.8"
PHASE_NAME = "SEMANTIC_GATE_COMPARATIVE_FORENSICS_AND_ARCHITECTURE_DESIGN"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B28_COMPARATIVE_FORENSICS_AND_ARCHITECTURE_DESIGN_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SDK_MAX_RETRIES = 0
RETRIES = 0
FALLBACKS = 0

PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
PROMPT_VERSION_11 = CANDIDATE_PROMPT_VERSION
PROMPT_VERSION_20_PROPOSAL = "book-semantic-validator-2.0-proposal"
TRANSPORT_VERSION_20_PROPOSAL = "book-semantic-validation-transport-2.0-proposal"
TRANSPORT_VERSION_20_ACTIVATED = False
PROMPT_VERSION_20_ACTIVATED = False

HISTORICAL_4B277_STATUS = "PARTIAL"
HISTORICAL_H11_STATUS = "PARTIAL"

H01_CASE_HANDLE = "h01"
H01_CASE_ID = "4b22_p2_supported"
H01_HUMAN_LABEL = CLASS_SUPPORTED
H01_COST_USD = OBSERVED_4B27_COST_USD
H01_INPUT_TOKENS = OBSERVED_4B27_INPUT_TOKENS
H01_COMPLETION_TOKENS = OBSERVED_4B27_COMPLETION_TOKENS
H01_REASONING_TOKENS = OBSERVED_4B27_REASONING_TOKENS

H02_CASE_HANDLE = "h02"
H02_CASE_ID = P3_CASE_ID
H02_HUMAN_LABEL = CLASS_QUESTIONABLE

H11_CASE_HANDLE = "h11"
H11_CASE_ID = "4b276_p4_new_implication"
H11_HUMAN_LABEL = CLASS_UNSUPPORTED
H11_COST_USD = 0.029556
H11_INPUT_TOKENS = 2562
H11_COMPLETION_TOKENS = 2036
H11_REASONING_TOKENS = 1647
H11_GAPS = ((137, 139), (177, 179), (232, 234), (289, 291), (353, 357))

H01_EVIDENCE_HANDLES = (
    "IDEA224",
    "SRC006149",
    "SRC006180",
    "SRC006182",
    "SRC006183",
    "SRC006187",
)
H02_EVIDENCE_HANDLES = P3_EVIDENCE_HANDLES
H11_EVIDENCE_HANDLES = P4_EVIDENCE_HANDLES

EVIDENCE_LEVELS = (
    "OBSERVED",
    "DETERMINISTICALLY_VERIFIED",
    "HUMAN_ASSESSED",
    "HYPOTHESIS",
    "NOT_TESTED",
)

TARGET_ARCHITECTURE = "C_HYBRID_TWO_LEVEL_WITH_CONSERVATIVE_PRESEGMENTATION"
PROPOSED_CONTRACT = PROMPT_VERSION_20_PROPOSAL

assert PROMPT_VERSION_HISTORICAL == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION_HISTORICAL == "book-semantic-validation-transport-1.0"
assert PROMPT_VERSION_11 == "book-semantic-validator-1.1-candidate"
assert TRANSPORT_VERSION_11 == "book-semantic-validation-transport-1.1-candidate"
assert PROMPT_VERSION_112 == "book-semantic-validator-1.1.2-candidate"
assert PROMPT_VERSION_113 == "book-semantic-validator-1.1.3-candidate"
assert PROMPT_VERSION_20_PROPOSAL != PROMPT_VERSION_113
assert PROMPT_VERSION_20_ACTIVATED is False
assert TRANSPORT_VERSION_20_ACTIVATED is False
assert H01_REQUEST_SHA256 == (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
assert H02_REQUEST_SHA256 == (
    "5ace261296d808437910f8f9efe247a80daebbb2237bc8af46bda56bf98d7897"
)
assert H11_REQUEST_SHA256 == (
    "b3cc1574858acdd5bdd0e223aa136d5058c4eb1deb1495cd9ad312d332e8c30f"
)
assert H01_REQUEST_SHA256 != H02_REQUEST_SHA256 != H11_REQUEST_SHA256
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert HISTORICAL_4B262_STATUS == "PASS"
assert HISTORICAL_4B27_STATUS == "PARTIAL"
assert HISTORICAL_4B271_STATUS == "PASS"
assert HISTORICAL_4B272_STATUS == "PASS"
assert HISTORICAL_4B273_STATUS == "PARTIAL"
assert HISTORICAL_4B274_STATUS == "PASS"
assert HISTORICAL_4B275_STATUS == "PASS"
assert HISTORICAL_4B276_STATUS == "PASS"
assert HISTORICAL_4B277_STATUS == "PARTIAL"
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_H11_STATUS == "PARTIAL"
assert H01_COST_USD == 0.018812
assert H02_COST_USD == 0.066036
assert H11_COST_USD == 0.029556
assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False
assert CANONICAL_PYTHON_EXECUTABLE.endswith("python.exe")
assert H01_DISPUTED_CLAUSE == "that fear can calculate or bargain with"
assert DISPUTED_CAUSAL_CLAUSE == (
    "because it still works wherever it is not resisted by truth"
)
assert H11_DISPUTED_CLAUSE == (
    "which means that every believer is guaranteed a fearless death"
)
assert H11_CASE_HANDLE not in {opaque for opaque, _ in SCORED_CASE_ORDER}

AUDIT_DIRNAME = "book_semantic_gate_4b28"
AUDIT_INVENTORY = "historical_evidence_inventory.json"
AUDIT_H01 = "h01_claim_forensics.json"
AUDIT_H02 = "h02_claim_forensics.json"
AUDIT_H11 = "h11_claim_forensics.json"
AUDIT_TAXONOMY = "failure_taxonomy.json"
AUDIT_ARCH_A = "architecture_a_analysis.json"
AUDIT_ARCH_B = "architecture_b_analysis.json"
AUDIT_ARCH_C = "architecture_c_analysis.json"
AUDIT_SEGMENTATION = "segmentation_design.json"
AUDIT_REPLAY = "segmentation_offline_replay.json"
AUDIT_FALSE_REJECTION = "false_rejection_analysis.json"
AUDIT_COST = "cost_comparison.json"
AUDIT_CONTRACT = "semantic_contract_20_proposal.json"
AUDIT_COMPARISON = "architecture_comparison.json"
AUDIT_MIGRATION = "migration_plan.json"
AUDIT_TESTS = "offline_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b28_index.json"
REPORT_NAME = (
    "PHASE_4B28_SEMANTIC_GATE_COMPARATIVE_FORENSICS_AND_ARCHITECTURE_REPORT.md"
)

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_ARCHITECTURE_HUMAN_REVIEW = True
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "AUDIT_ARCH_A",
    "AUDIT_ARCH_B",
    "AUDIT_ARCH_C",
    "AUDIT_COMPARISON",
    "AUDIT_CONTRACT",
    "AUDIT_COST",
    "AUDIT_DIRNAME",
    "AUDIT_FALSE_REJECTION",
    "AUDIT_H01",
    "AUDIT_H02",
    "AUDIT_H11",
    "AUDIT_INDEX",
    "AUDIT_INVENTORY",
    "AUDIT_MIGRATION",
    "AUDIT_READINESS",
    "AUDIT_REPLAY",
    "AUDIT_SEGMENTATION",
    "AUDIT_TAXONOMY",
    "AUDIT_TESTS",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_SONNET_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CONNECTIVE_CASE_ID",
    "DISPUTED_CAUSAL_CLAUSE",
    "EVIDENCE_LEVELS",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_SOURCE_MAP",
    "FALLBACKS",
    "FUNERAL_CASE_ID",
    "H01_CASE_HANDLE",
    "H01_CASE_ID",
    "H01_COMPLETION_TOKENS",
    "H01_COST_USD",
    "H01_DISPUTED_CLAUSE",
    "H01_EVIDENCE_HANDLES",
    "H01_GAPS",
    "H01_HUMAN_LABEL",
    "H01_INPUT_TOKENS",
    "H01_REASONING_TOKENS",
    "H01_REQUEST_SHA256",
    "H02_CASE_HANDLE",
    "H02_CASE_ID",
    "H02_COMPLETION_TOKENS",
    "H02_COST_USD",
    "H02_EVIDENCE_HANDLES",
    "H02_GAPS",
    "H02_HUMAN_LABEL",
    "H02_INPUT_TOKENS",
    "H02_REASONING_TOKENS",
    "H02_REQUEST_SHA256",
    "H11_CASE_HANDLE",
    "H11_CASE_ID",
    "H11_COMPLETION_TOKENS",
    "H11_COST_USD",
    "H11_DISPUTED_CLAUSE",
    "H11_EVIDENCE_HANDLES",
    "H11_GAPS",
    "H11_HUMAN_LABEL",
    "H11_INPUT_TOKENS",
    "H11_REASONING_TOKENS",
    "H11_REQUEST_SHA256",
    "HISTORICAL_4B261_STATUS",
    "HISTORICAL_4B262_STATUS",
    "HISTORICAL_4B26_STATUS",
    "HISTORICAL_4B271_STATUS",
    "HISTORICAL_4B272_STATUS",
    "HISTORICAL_4B273_STATUS",
    "HISTORICAL_4B274_STATUS",
    "HISTORICAL_4B275_STATUS",
    "HISTORICAL_4B276_STATUS",
    "HISTORICAL_4B277_STATUS",
    "HISTORICAL_4B27_STATUS",
    "HISTORICAL_H01_STATUS",
    "HISTORICAL_H02_STATUS",
    "HISTORICAL_H11_STATUS",
    "NEGATIVE_CASE_IDS",
    "NEXT_ACTION",
    "P3_CASE_ID",
    "P8_CASE_ID",
    "PHASE",
    "PHASE_NAME",
    "POSITIVE_CASE_IDS",
    "PROJECT_NAME",
    "PROMPT_VERSION_11",
    "PROMPT_VERSION_112",
    "PROMPT_VERSION_113",
    "PROMPT_VERSION_20_ACTIVATED",
    "PROMPT_VERSION_20_PROPOSAL",
    "PROMPT_VERSION_HISTORICAL",
    "PROPOSED_CONTRACT",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_ARCHITECTURE_HUMAN_REVIEW",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "READY_FOR_NEW_REMOTE_TERRA_CALL",
    "REPORT_NAME",
    "RETRIES",
    "SCORED_CASE_ORDER",
    "SDK_MAX_RETRIES",
    "TARGET_ARCHITECTURE",
    "TERRA_EXECUTION_AUTHORIZED",
    "TRANSPORT_VERSION_11",
    "TRANSPORT_VERSION_20_ACTIVATED",
    "TRANSPORT_VERSION_20_PROPOSAL",
    "TRANSPORT_VERSION_HISTORICAL",
]
