"""
Phase 4B.2.11 — One real Terra Semantic Gate 2.0 h01 canary.

NEW explicit authorization. AUTHORIZED REMOTE INVOCATIONS = 1.
Reuses the frozen 4B.2.10 request. Does not relaunch h02 or h11.
Does not modify production. Semantic Gate 2.0 is not promoted.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
    VERDICT_FAIL,
    VERDICT_PASS,
    VERDICT_REVIEW,
)
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    SEMANTIC_TOKEN_BUDGET,
)
from app.book_semantic_gate_4b210.constants import (
    CHAPTER_HANDLE,
    H01_COMPLETION_TOKENS,
    H01_COST_USD,
    H01_EVIDENCE_HANDLES,
    H01_HUMAN_LABEL,
    H01_INPUT_TOKENS,
    H01_REASONING_TOKENS,
    H01_REQUEST_SHA256,
    H02_REQUEST_SHA256,
    H11_REQUEST_SHA256,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
    PROMPT_VERSION_201_CANDIDATE,
    SELECTED_CASE_HANDLE as FROZEN_CASE_HANDLE,
    SELECTED_CASE_ID as FROZEN_CASE_ID,
    TRANSPORT_VERSION_20_CANDIDATE,
)
from app.book_semantic_gate_4b271.constants import DISPUTED_CLAUSE as H01_DISPUTED_CLAUSE

PHASE = "4B.2.11"
PHASE_NAME = "ONE_REAL_TERRA_SEMANTIC_GATE_20_H01_CANARY"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B211_ONE_REAL_TERRA_SEMANTIC_GATE_20_H01_CANARY_ONLY"
)
AUTHORIZED_REMOTE_TERRA_INVOCATIONS = 1
AUTHORIZED_REMOTE_INVOCATIONS = 1
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
MAX_ENGINE_GENERATE = 1
MAX_REMOTE_INVOCATIONS = 1
MAX_HTTP_REQUESTS = 1
MAX_EXECUTION_ATTEMPTS = 1
RETRIES = 0
FALLBACKS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = True
SDK_MAX_RETRIES = 0

SEMANTIC_GATE_20_ENABLED = False
SEMANTIC_GATE_201_ENABLED = False
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
PROMPT_VERSION_20_ACTIVATED = False
PROMPT_VERSION_201_ACTIVATED = False
TRANSPORT_VERSION_20_ACTIVATED = False

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
STAGE_CANARY = "book_semantic_validation_canary_4b211"
PROMPT_VERSION = PROMPT_VERSION_201_CANDIDATE
TRANSPORT_VERSION = TRANSPORT_VERSION_20_CANDIDATE
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"
TOKEN_FIELD = "max_completion_tokens"
PRODUCTION_SDK_METHOD = "client.chat.completions.create"

SELECTED_CASE_HANDLE = "h01"
SELECTED_CASE_ID = "4b210_h01"
SELECTED_CASE_HUMAN_LABEL = H01_HUMAN_LABEL
SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY = True
TARGET_UNIT_ID = "u01"
TARGET_CLAUSE = H01_DISPUTED_CLAUSE
CHAPTER_ID = CHAPTER_HANDLE
REQUIRED_UNIT_IDS = ("u00", "u01", "u02", "u03", "u04")

EXPECTED_REQUEST_SHA256 = (
    "d62ee35106f89d34170fb93364ce202b021fd0c60c582248c241cb296008c484"
)
CENTRAL_COST_ESTIMATE = 0.065272
THEORETICAL_MAXIMUM_ESTIMATE = 0.100924

HISTORICAL_4B210_STATUS = "PASS"

BLOCKING_VERDICTS = (
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    VERDICT_REVIEW,
    VERDICT_FAIL,
    "REVIEW",
    "FAIL",
    "QUESTIONABLE",
    "UNSUPPORTED",
)
ACCEPTING_VERDICTS = (VERDICT_PASS, CLASS_SUPPORTED, "PASS", "SUPPORTED")

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert PROMPT_VERSION == "book-semantic-validator-2.0.1-candidate"
assert TRANSPORT_VERSION == "book-semantic-validation-transport-2.0-candidate"
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
assert TOKEN_FIELD == "max_completion_tokens"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert SELECTED_CASE_HANDLE == FROZEN_CASE_HANDLE == "h01"
assert SELECTED_CASE_ID == FROZEN_CASE_ID == "4b210_h01"
assert SELECTED_CASE_HUMAN_LABEL == CLASS_SUPPORTED
assert SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY is True
assert TARGET_CLAUSE == "that fear can calculate or bargain with"
assert TARGET_UNIT_ID == "u01"
assert H01_EVIDENCE_HANDLES == (
    "IDEA224",
    "SRC006149",
    "SRC006180",
    "SRC006182",
    "SRC006183",
    "SRC006187",
)
assert EXPECTED_REQUEST_SHA256 != H01_REQUEST_SHA256
assert EXPECTED_REQUEST_SHA256 != H02_REQUEST_SHA256
assert EXPECTED_REQUEST_SHA256 != H11_REQUEST_SHA256
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_H11_STATUS == "PARTIAL"
assert HISTORICAL_4B210_STATUS == "PASS"
assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert SDK_MAX_RETRIES == 0
assert PUBLICATION_AUTHORIZED is False
assert SEMANTIC_GATE_20_ENABLED is False
assert SEMANTIC_GATE_201_ENABLED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert CANONICAL_PYTHON_EXECUTABLE.endswith("python.exe")
assert CLASSIFICATIONS == (
    CLASS_SUPPORTED,
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    CLASS_NON_SUBSTANTIVE,
)
assert EXPECTED_OPENAI_SDK_VERSION == "2.43.0"
assert EXPECTED_PYTHON_VERSION == (3, 11, 9) or isinstance(EXPECTED_PYTHON_VERSION, tuple)
assert H01_COST_USD == 0.018812
assert H01_INPUT_TOKENS == 1654
assert H01_COMPLETION_TOKENS == 1292
assert H01_REASONING_TOKENS == 985

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 600.0
CANARY_WINDOW_ID = "book-semantic-gate-4b211"

AUDIT_DIRNAME = "book_semantic_gate_4b211"
AUDIT_REAL_PARENT = "real"
AUDIT_PREFLIGHT = "preflight.json"
AUDIT_HASHES_BEFORE = "canonical_hashes_before.json"
AUDIT_REQUEST = "request_integrity.json"
AUDIT_REQUEST_SHA = "request_sha256.txt"
AUDIT_LEAK = "label_leakage_check.json"
AUDIT_SERIALIZATION = "sdk_serialization.json"
AUDIT_INVOCATION = "provider_invocation.json"
AUDIT_RAW_RESPONSE = "provider_response_raw.json"
AUDIT_USAGE = "provider_usage.json"
AUDIT_COST = "provider_cost.json"
AUDIT_CONTRACT = "contract_validation.json"
AUDIT_COVERAGE = "unit_coverage_validation.json"
AUDIT_EVIDENCE = "evidence_validation.json"
AUDIT_SEMANTIC = "semantic_human_review.json"
AUDIT_POLICY = "acceptance_policy.json"
AUDIT_REPLAY = "deterministic_replay.json"
AUDIT_TESTS = "offline_regression_tests.json"
AUDIT_HASHES_AFTER = "canonical_hashes_after.json"
AUDIT_READINESS = "readiness.json"
AUDIT_LOCK = "h01_real_call.lock"
AUDIT_INDEX = "book_semantic_gate_4b211_index.json"
REPORT_NAME = "PHASE_4B211_ONE_REAL_TERRA_SEMANTIC_GATE_20_H01_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False
