"""Constantes 3B.7.7A.41 — forensics drop-domain A.40 + durcissement offline."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis_v31_global_grammar_canary.constants import (
    FROZEN_GRANULARITY,
    FROZEN_PLANNER,
    FROZEN_PROMPT,
    FROZEN_SRC_POLICY,
    FROZEN_TRANSPORT,
    HANDLE_PREFIX_BY_KIND,
    MODEL,
    PROJECT_NAME,
    PROVIDER,
    THINKING_CONTRACT,
    THINKING_MODE,
)
from app.source_analysis_v31_global_output_architecture.constants import (
    A34_STATUS_PRESERVED,
    A35_STATUS_PRESERVED,
    A36_STATUS_PRESERVED,
    A37_STATUS_PRESERVED,
    A38_CHARS_PER_PROVIDER_OUTPUT_TOKEN,
    A38_STATUS_PRESERVED,
    DROP_REASONS_V20,
    EXPECTED_EXAMPLE,
    EXPECTED_IDEA,
    EXPECTED_REFERENCE,
    EXPECTED_RELATION,
    EXPECTED_TOPIC,
    EXPECTED_UNCERTAINTY,
    NEXT_MAX_OUTPUT_TOKENS,
    NEXT_PROMPT_VERSION as V20_PROMPT_VERSION,
    NEXT_SCHEMA_ADAPTED_BYTES as V20_SCHEMA_ADAPTED_BYTES,
    NEXT_SCHEMA_HASH as V20_SCHEMA_HASH,
    NEXT_SCHEMA_RAW_BYTES as V20_SCHEMA_RAW_BYTES,
    NEXT_TRANSPORT_VERSION as V20_TRANSPORT_VERSION,
    READINESS_DECISION as A39_READINESS_DECISION,
    RETIRED_DISPOSITION_OPS_V20,
    RETIRED_DROP_REASONS_V20,
    SAFETY_RATIO,
    TEXT_LIMITS,
)
from app.source_analysis_v31_global_preflight.constants import (
    IDEA_DISPOSITION_COVERAGE_REQUIRED,
    IDEA_KIND_POLICY,
    RELATION_QUALITY_TECHNICAL_DEBT,
)
from app.source_analysis_v31_global_v20_grammar_canary.constants import (
    CANARY_SUBDIR as A40_CANARY_SUBDIR,
    CANARY_WINDOW_ID as A40_WINDOW_ID,
    PRODUCTION_EXPECTED_OUTPUT_TOKENS as A39_EXPECTED_OUTPUT,
    PRODUCTION_HARD_PLANNING_TOKENS as A39_HARD_PLANNING,
    PRODUCTION_SAFETY_MARGIN as A39_SAFETY_MARGIN,
    PRODUCTION_SAFETY_THRESHOLD as A39_SAFETY_THRESHOLD,
    REPORT_NAME as A40_REPORT_NAME,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.41"
MODE = "COMPACT_GLOBAL_CONSOLIDATION_TYPE_BOUNDARY_HARDENING"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_ANTHROPIC_CALLS = 0
REAL_CONSOLIDATION_CALLS = 0
GRAMMAR_CANARY_CALLS = 0
CONSOLIDATION_AUTHORIZED = False
GRAMMAR_CANARY_AUTHORIZED = False
SOURCE_MAP_PUBLICATION_AUTHORIZED = False

A39_STATUS_PRESERVED = "PASS"
A40_STATUS_PRESERVED = "FAIL"
assert A34_STATUS_PRESERVED == "PASS"
assert A35_STATUS_PRESERVED == "FAIL"
assert A36_STATUS_PRESERVED == "PASS"
assert A37_STATUS_PRESERVED == "PASS"
assert A38_STATUS_PRESERVED == "FAIL"
assert A39_STATUS_PRESERVED == "PASS"
assert A40_STATUS_PRESERVED == "FAIL"
assert A39_READINESS_DECISION == "READY_FOR_COMPACT_GLOBAL_GRAMMAR_CANARY"
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert THINKING_MODE == "disabled"
assert V20_PROMPT_VERSION == "global-consolidation-2.0"
assert V20_TRANSPORT_VERSION == "global-consolidation-transport-2.0"
assert V20_SCHEMA_RAW_BYTES == 1588
assert V20_SCHEMA_ADAPTED_BYTES == 1836
assert V20_SCHEMA_HASH == (
    "90b99a38ac704d00e1304495da0c757118293e43493ddb7321b3ffb3256d8330"
)
assert DROP_REASONS_V20 == ("transport_artifact", "non_substantive_fragment")
assert RETIRED_DROP_REASONS_V20 == ("exact_duplicate",)
assert RETIRED_DISPOSITION_OPS_V20 == ("OTHER",)
assert IDEA_KIND_POLICY == "KEEP_EMPTY_GLOBALLY"
assert IDEA_DISPOSITION_COVERAGE_REQUIRED == 100
assert EXPECTED_TOPIC == 67
assert EXPECTED_IDEA == 286
assert EXPECTED_RELATION == 127
assert EXPECTED_EXAMPLE == 49
assert EXPECTED_REFERENCE == 59
assert EXPECTED_UNCERTAINTY == 35
assert NEXT_MAX_OUTPUT_TOKENS == 48000
assert SAFETY_RATIO == 0.75
assert A39_EXPECTED_OUTPUT == 28735
assert A39_HARD_PLANNING == 35284
assert A39_SAFETY_THRESHOLD == 36000
assert A39_SAFETY_MARGIN == 716
assert FROZEN_PLANNER == "window-planner-v2.1-small"
assert FROZEN_PROMPT == "window-analysis-1.4.0"
assert FROZEN_TRANSPORT == "semantic-transport-v3.1-local-lite"
assert FROZEN_GRANULARITY == "window-granularity-1.2-kind-specific"
assert FROZEN_SRC_POLICY == "src-reference-policy-1.1-narrow-canonicalization"

A40_REQUEST_ID = "req_011CfXF35hCDL2bWMsmVR7C6"
A40_REQUEST_IDENTITY = (
    "50b0f7275bbb933b4fe14303df27213b73fdfd696ba4d993c8100496456df29c"
)
A40_RAW_SHA256 = "f91a300043cd9c3c90e10a8cf77f71cfaaa9d3f05d5ff3a2ad68f760f0235efe"
A40_RAW_SIZE = 2082
A40_HTTP_STATUS = 200
A40_FINISH_REASON = "end_turn"
A40_THINKING_TOKENS = 0
A40_INPUT_TOKENS = 4626
A40_OUTPUT_TOKENS = 661
A40_COST_USD = 0.015862
A40_ELAPSED_MS = 10734
A40_RAW_TEXT_CHARS = 1357
A40_PREDICTED_OUTPUT = 514
A40_ESTIMATOR_RATIO = 1.2859922178988328
A40_ESTIMATOR_ERROR_PERCENT = 28.6
A40_FIXTURE_HASH = "ae1b402396700bf3e11c19a06809e35290cf64b949adc9f6b0bd354df48fff29"
A40_PROMPT_HASH = "6552345159a8836e92d0ec55eda10b56b883908fb667c8dbc0b51e88a6288c67"
A40_ROOT_VALIDATOR_ERROR = "drop[1]: SYN:L001 is not a local IDEA"
A40_VIOLATING_ID = "SYN:L001"
A40_VIOLATING_KIND = "RELATION"
A40_DROP_REASON = "transport_artifact"
A40_GRAMMAR = "PASS"
A40_TRANSPORT_DECODER = "PASS"
A40_GLOBAL_VALIDATOR = "FAIL"

OLD_PROMPT_VERSION = V20_PROMPT_VERSION
OLD_TRANSPORT_VERSION = V20_TRANSPORT_VERSION
NEXT_PROMPT_VERSION = "global-consolidation-2.0.1"
NEXT_TRANSPORT_VERSION = V20_TRANSPORT_VERSION
SCHEMA_CHANGED = False
NEW_GRAMMAR_CANARY_REQUIRED = False
SECOND_COMPACT_CONTRACT_CANARY_REQUIRED = True

DROP_DOMAIN = "LOCAL_IDEA_ONLY"
SELECTED_HARDENING = "PROMPT_2_0_1_PLUS_HANDLE_AND_PUBLICATION_GATES"
FIELD_RENAME_ADOPTED = False
SCHEMA_PATTERN_ADOPTED = False

LOCAL_HANDLE_KIND_LETTER = {
    "TOPIC": "T",
    "IDEA": "I",
    "EXAMPLE": "E",
    "REFERENCE": "F",
    "RELATION": "L",
    "UNCERTAINTY": "U",
    "REPETITION": "P",
}
GLOBAL_HANDLE_PREFIX_BY_KIND = dict(HANDLE_PREFIX_BY_KIND)

A37_OUTPUT_TOKENS = 1343
A37_INPUT_TOKENS = 4416
A40_CHARS_PER_PROVIDER_OUTPUT_TOKEN = A40_RAW_TEXT_CHARS / A40_OUTPUT_TOKENS
COMPACT_20_CHARS_PER_TOKEN_OBSERVED = A40_CHARS_PER_PROVIDER_OUTPUT_TOKEN
COMPACT_20_CHARS_PER_TOKEN_CONSERVATIVE = 2.00
EXPECTED_GLOBAL_IDEA_RANGE = (280, 286)
PRODUCTION_MAX_OUTPUT_TOKENS = NEXT_MAX_OUTPUT_TOKENS
SAFETY_70 = int(PRODUCTION_MAX_OUTPUT_TOKENS * 0.70)
SAFETY_75 = int(PRODUCTION_MAX_OUTPUT_TOKENS * 0.75)
SAFETY_80 = int(PRODUCTION_MAX_OUTPUT_TOKENS * 0.80)

LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN = "YES"
PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY = "NO"
READY_FOR_COMPACT_GLOBAL_REAL_CALL_PREFLIGHT = "NO"

A40_FORENSIC_RELATIVE = f"audit/canary/{A40_CANARY_SUBDIR}"
PROTECTED_HISTORICAL = (
    "audit/PHASE_3B77A34_GLOBAL_CONSOLIDATION_OFFLINE_PREFLIGHT_REPORT.md",
    "audit/PHASE_3B77A35_GLOBAL_CONSOLIDATION_TINY_GRAMMAR_CANARY_REPORT.md",
    "audit/PHASE_3B77A36_GLOBAL_CONSOLIDATION_CANARY_FORENSICS_REPORT.md",
    "audit/PHASE_3B77A37_GLOBAL_CONSOLIDATION_V11_TINY_GRAMMAR_CANARY_REPORT.md",
    "audit/PHASE_3B77A38_FIRST_REAL_GLOBAL_CONSOLIDATION_CANARY_REPORT.md",
    "audit/PHASE_3B77A39_GLOBAL_CONSOLIDATION_OUTPUT_ARCHITECTURE_REDESIGN_REPORT.md",
    f"audit/{A40_REPORT_NAME}",
    f"{A40_FORENSIC_RELATIVE}/global_consolidation_v20_canary_execution.json",
    f"{A40_FORENSIC_RELATIVE}/global_consolidation_v20_synthetic_fixture.json",
    f"{A40_FORENSIC_RELATIVE}/provider_forensics/{A40_WINDOW_ID}/{A40_REQUEST_IDENTITY}/provider_raw_response.bin",
)

FORENSICS_ARTIFACT = "global_consolidation_a40_drop_domain_forensics.json"
COUNTERFACTUAL_ARTIFACT = "global_consolidation_a40_nonidea_drop_counterfactual.json"
POLICY_ARTIFACT = "global_consolidation_v2_local_object_kind_policy.json"
HARDENING_ARTIFACT = "global_consolidation_v2_drop_domain_hardening.json"
ESTIMATOR_ARTIFACT = "global_consolidation_v2_output_estimator_calibration.json"
BUDGET_ARTIFACT = "global_consolidation_v2_revised_production_output_budget.json"
HANG_ARTIFACT = "global_consolidation_a40_full_suite_hang_diagnosis.json"
NEXT_FIXTURE_ARTIFACT = "global_consolidation_next_compact_canary_fixture.json"
READINESS_ARTIFACT = "global_consolidation_post_a41_readiness.json"
TEST_DELTA_ARTIFACT = "source_analysis_a41_test_delta.json"
REPORT_NAME = (
    "PHASE_3B77A41_COMPACT_GLOBAL_CONSOLIDATION_TYPE_BOUNDARY_HARDENING_REPORT.md"
)

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_drop_domain.py",
    "app/tests/test_source_analysis_v31_global_drop_domain_audit.py",
    "app/tests/test_source_analysis_v31_global_v20_grammar_canary.py",
    "app/tests/test_source_analysis_v31_global_output_architecture.py",
)

assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert REAL_ANTHROPIC_CALLS == 0
assert REAL_CONSOLIDATION_CALLS == 0
assert GRAMMAR_CANARY_CALLS == 0
assert READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY == "NO"
assert READY_FOR_COMPACT_GLOBAL_REAL_CALL_PREFLIGHT == "NO"
assert RELATION_QUALITY_TECHNICAL_DEBT == "YES"
assert not source_map_path(PROJECT_NAME).is_file() or SOURCE_MAP_STATUS == "NOT PUBLISHED"

__all__ = [
    "A34_STATUS_PRESERVED",
    "A35_STATUS_PRESERVED",
    "A36_STATUS_PRESERVED",
    "A37_INPUT_TOKENS",
    "A37_OUTPUT_TOKENS",
    "A37_STATUS_PRESERVED",
    "A38_CHARS_PER_PROVIDER_OUTPUT_TOKEN",
    "A38_STATUS_PRESERVED",
    "A39_EXPECTED_OUTPUT",
    "A39_HARD_PLANNING",
    "A39_READINESS_DECISION",
    "A39_SAFETY_MARGIN",
    "A39_SAFETY_THRESHOLD",
    "A39_STATUS_PRESERVED",
    "A40_CANARY_SUBDIR",
    "A40_CHARS_PER_PROVIDER_OUTPUT_TOKEN",
    "A40_COST_USD",
    "A40_DROP_REASON",
    "A40_ELAPSED_MS",
    "A40_ESTIMATOR_ERROR_PERCENT",
    "A40_ESTIMATOR_RATIO",
    "A40_FINISH_REASON",
    "A40_FIXTURE_HASH",
    "A40_FORENSIC_RELATIVE",
    "A40_GLOBAL_VALIDATOR",
    "A40_GRAMMAR",
    "A40_HTTP_STATUS",
    "A40_INPUT_TOKENS",
    "A40_OUTPUT_TOKENS",
    "A40_PREDICTED_OUTPUT",
    "A40_PROMPT_HASH",
    "A40_RAW_SHA256",
    "A40_RAW_SIZE",
    "A40_RAW_TEXT_CHARS",
    "A40_REPORT_NAME",
    "A40_REQUEST_ID",
    "A40_REQUEST_IDENTITY",
    "A40_ROOT_VALIDATOR_ERROR",
    "A40_STATUS_PRESERVED",
    "A40_THINKING_TOKENS",
    "A40_TRANSPORT_DECODER",
    "A40_VIOLATING_ID",
    "A40_VIOLATING_KIND",
    "A40_WINDOW_ID",
    "BUDGET_ARTIFACT",
    "COMPACT_20_CHARS_PER_TOKEN_CONSERVATIVE",
    "COMPACT_20_CHARS_PER_TOKEN_OBSERVED",
    "CONSOLIDATION_AUTHORIZED",
    "COUNTERFACTUAL_ARTIFACT",
    "DROP_DOMAIN",
    "DROP_REASONS_V20",
    "ESTIMATOR_ARTIFACT",
    "EXPECTED_EXAMPLE",
    "EXPECTED_GLOBAL_IDEA_RANGE",
    "EXPECTED_IDEA",
    "EXPECTED_REFERENCE",
    "EXPECTED_RELATION",
    "EXPECTED_TOPIC",
    "EXPECTED_UNCERTAINTY",
    "FIELD_RENAME_ADOPTED",
    "FOCUSED_TEST_PATHS",
    "FORENSICS_ARTIFACT",
    "FROZEN_GRANULARITY",
    "FROZEN_PLANNER",
    "FROZEN_PROMPT",
    "FROZEN_SRC_POLICY",
    "FROZEN_TRANSPORT",
    "GLOBAL_HANDLE_PREFIX_BY_KIND",
    "GRAMMAR_CANARY_AUTHORIZED",
    "GRAMMAR_CANARY_CALLS",
    "HANG_ARTIFACT",
    "HARDENING_ARTIFACT",
    "HANDLE_PREFIX_BY_KIND",
    "IDEA_DISPOSITION_COVERAGE_REQUIRED",
    "IDEA_KIND_POLICY",
    "LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN",
    "LOCAL_HANDLE_KIND_LETTER",
    "MODE",
    "MODEL",
    "NEW_GRAMMAR_CANARY_REQUIRED",
    "NEXT_ACTION",
    "NEXT_FIXTURE_ARTIFACT",
    "NEXT_PROMPT_VERSION",
    "NEXT_TRANSPORT_VERSION",
    "OLD_PROMPT_VERSION",
    "OLD_TRANSPORT_VERSION",
    "PHASE",
    "PHASE_3B_STATUS",
    "POLICY_ARTIFACT",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PROJECT_NAME",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "READINESS_ARTIFACT",
    "READY_FOR_COMPACT_GLOBAL_REAL_CALL_PREFLIGHT",
    "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY",
    "REAL_ANTHROPIC_CALLS",
    "REAL_CONSOLIDATION_CALLS",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPORT_NAME",
    "RETIRED_DISPOSITION_OPS_V20",
    "RETIRED_DROP_REASONS_V20",
    "SAFETY_70",
    "SAFETY_75",
    "SAFETY_80",
    "SAFETY_RATIO",
    "SCHEMA_CHANGED",
    "SCHEMA_PATTERN_ADOPTED",
    "SCHEMA_VERSION",
    "SECOND_COMPACT_CONTRACT_CANARY_REQUIRED",
    "SELECTED_HARDENING",
    "SOURCE_MAP_PUBLICATION_AUTHORIZED",
    "SOURCE_MAP_STATUS",
    "TEST_DELTA_ARTIFACT",
    "TEXT_LIMITS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "V20_PROMPT_VERSION",
    "V20_SCHEMA_ADAPTED_BYTES",
    "V20_SCHEMA_HASH",
    "V20_SCHEMA_RAW_BYTES",
    "V20_TRANSPORT_VERSION",
]
