"""Rapport markdown 3B.7.7A.41."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any], *, tests: str) -> str:
    header = bundle.get("header") or {}
    budget = bundle.get("budget") or {}
    hang = (bundle.get("hang") or {}).get("classification") or {}
    lines = [
        "# PHASE 3B.7.7A.41 — COMPACT GLOBAL CONSOLIDATION TYPE-BOUNDARY HARDENING",
        "",
        "## Result",
        "",
        str(header.get("result")),
        "",
        "REAL PROVIDER CALLS =",
        "0",
        "",
        "A.40 STATUS =",
        "FAIL unchanged",
        "",
        "A.40 REQUEST =",
        str(header.get("a40_request")),
        "",
        "A.40 GRAMMAR =",
        "PASS",
        "",
        "A.40 TRANSPORT DECODER =",
        "PASS",
        "",
        "A.40 ROOT VALIDATOR FAILURE =",
        str(header.get("a40_root_validator_failure")),
        "",
        "A40 SOLE TECHNICAL ROOT =",
        str(header.get("a40_sole_technical_root")),
        "",
        "COUNTERFACTUAL =",
        str(header.get("counterfactual")),
        "",
        "DROP DOMAIN =",
        "LOCAL IDEA ONLY",
        "",
        "LOCAL RELATION POLICY =",
        "DEFERRED / NO DISPOSITION REQUIRED",
        "",
        "LOCAL TOPIC POLICY =",
        str(header.get("local_topic_policy")),
        "",
        "LOCAL EXAMPLE POLICY =",
        str(header.get("local_example_policy")),
        "",
        "LOCAL REFERENCE POLICY =",
        str(header.get("local_reference_policy")),
        "",
        "LOCAL UNCERTAINTY POLICY =",
        str(header.get("local_uncertainty_policy")),
        "",
        "SELECTED HARDENING =",
        str(header.get("selected_hardening")),
        "",
        "OLD PROMPT =",
        "global-consolidation-2.0",
        "",
        "NEXT PROMPT =",
        str(header.get("next_prompt")),
        "",
        "OLD TRANSPORT =",
        "global-consolidation-transport-2.0",
        "",
        "NEXT TRANSPORT =",
        str(header.get("next_transport")),
        "",
        "SCHEMA CHANGED =",
        str(header.get("schema_changed")),
        "",
        "NEXT SCHEMA RAW / ADAPTED =",
        str(header.get("next_schema_raw_adapted")),
        "",
        "NEXT SCHEMA HASH =",
        str(header.get("next_schema_hash")),
        "",
        "NEW GRAMMAR CANARY REQUIRED =",
        str(header.get("new_grammar_canary_required")),
        "",
        "SECOND COMPACT CONTRACT CANARY REQUIRED =",
        str(header.get("second_compact_contract_canary_required")),
        "",
        "A.40 PREDICTED OUTPUT =",
        "514",
        "",
        "A.40 ACTUAL OUTPUT =",
        "661",
        "",
        "A.40 ESTIMATOR ERROR =",
        "+28.6%",
        "",
        "REVISED PRODUCTION EXPECTED =",
        _dash(header.get("revised_expected")),
        "",
        "REVISED PRODUCTION CONSERVATIVE =",
        _dash(header.get("revised_conservative")),
        "",
        "REVISED PRODUCTION HARD/PLANNING =",
        _dash(header.get("revised_hard")),
        "",
        "PRODUCTION MAX OUTPUT =",
        "48000",
        "",
        "70% MARGIN =",
        _dash(header.get("margin_70")),
        "",
        "75% MARGIN =",
        _dash(header.get("margin_75")),
        "",
        "80% MARGIN =",
        _dash(header.get("margin_80")),
        "",
        "OUTPUT RISK =",
        _dash(header.get("output_risk")),
        "",
        "FULL SUITE HANG ROOT =",
        _dash(header.get("full_suite_hang_root")),
        "",
        "FULL SUITE STATUS =",
        _dash(header.get("full_suite_status")),
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        _dash(header.get("new_failures")),
        "",
        "LOCAL EXTRACTION FUNCTIONALLY FROZEN =",
        "YES",
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        "YES",
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "READINESS =",
        _dash(header.get("readiness")),
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## Notes",
        "",
        "A.40 remains FAIL. The provider accepted grammar 2.0; global validator failed because",
        "SYN:L001 (local RELATION hint) was placed in drop[] with reason transport_artifact.",
        "Transport 2.0 drop[] is local IDEA IDs only. The original raw response was not repaired.",
        "",
        f"Hang classification = {hang.get('classification')}.",
        f"Naive 1.286× scale of 28735 was rejected. Conservative compact-2.0 chars/token = {budget.get('chars_per_token_compact_2_0_conservative')}.",
        "",
        "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY = NO",
        "READY_FOR_COMPACT_GLOBAL_REAL_CALL_PREFLIGHT = NO",
        "",
        "WAIT FOR HUMAN REVIEW.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
