"""Rapport déterministe 3B.7.7A.2."""

from __future__ import annotations

from typing import Any, Mapping

from app.source_analysis.window_granularity import (
    GRANULARITY_PRINCIPLE,
    HARD_CEILINGS,
    IDEA_HARD_CEILING,
    IDEA_SOFT_TARGET,
    MAX_OUTPUT_TOKENS_FROZEN,
    RELATION_HARD_CEILING,
    SAFETY_MARGIN_RATIO,
    SOFT_TARGETS,
    TOTAL_HARD_CEILING,
)
from app.source_analysis.window_prompt import (
    WINDOW_ANALYSIS_PROMPT_VERSION,
    WINDOW_ANALYSIS_PROMPT_VERSION_V10,
)
from app.source_analysis_hybrid.constants import WINDOW_TRANSPORT_VERSION
from app.source_analysis_window_output_bounding.constants import (
    NEXT_ACTION,
    NEXT_PHASE_LABEL,
    PHASE,
    REAL_PROVIDER_CALLS_THIS_PHASE,
    WIN001_RETRIED,
)


def _yn(value: bool) -> str:
    return "YES" if value else "NO"


def render_report(payload: Mapping[str, Any]) -> str:
    policy = payload["policy"]
    study = payload["size_study"]
    pre = payload["preflight"]
    impl = payload["implementation"]
    audit = payload["prompt_audit"]
    kinds = payload["transport_kinds"]
    max_valid = study["scenarios"]["MAX_POLICY_VALID"]
    result = payload["result"]
    lines = [
        f"# PHASE {PHASE} — WINDOW OUTPUT BOUNDING / GRANULARITY REDESIGN",
        "",
        "## Result",
        "",
        result,
        "",
        f"REAL PROVIDER CALLS = {REAL_PROVIDER_CALLS_THIS_PHASE}",
        "",
        f"WIN001 RETRIED = {_yn(WIN001_RETRIED)}",
        "",
        f"CURRENT PROMPT = {WINDOW_ANALYSIS_PROMPT_VERSION_V10}",
        "",
        f"SUCCESSOR PROMPT = {WINDOW_ANALYSIS_PROMPT_VERSION}",
        "",
        f"TRANSPORT = {WINDOW_TRANSPORT_VERSION}",
        "",
        f"MAX OUTPUT = {MAX_OUTPUT_TOKENS_FROZEN} UNCHANGED",
        "",
        "WINDOW PLAN = 3 WINDOWS UNCHANGED",
        "",
        f"GRANULARITY POLICY = {policy['policy_version']}",
        "",
        f"TOTAL HARD RECORD CEILING = {TOTAL_HARD_CEILING}",
        "",
        f"IDEA SOFT TARGET = {IDEA_SOFT_TARGET}",
        "",
        f"IDEA HARD CEILING = {IDEA_HARD_CEILING}",
        "",
        f"RELATION HARD CEILING = {RELATION_HARD_CEILING}",
        "",
        "OVERFLOW SIGNAL = UNCERTAINTY.v == analysis_capacity_exceeded",
        "",
        "MAX-POLICY-VALID SYNTHETIC OUTPUT = "
        f"{max_valid['local_estimated_tokens']} local estimated tokens",
        "",
        "OUTPUT SAFETY MARGIN = "
        f"{study['safety_margin_tokens']} local tokens "
        f"({study['percent_of_32000']}% of 32000; target ≤ "
        f"{int(SAFETY_MARGIN_RATIO * 100)}%)",
        "",
        "LOCAL SEMANTIC MERGE = NO",
        "",
        "AI WITHIN-WINDOW GROUPING = YES",
        "",
        "CANONICAL CONTRACT = UNCHANGED",
        "",
        f"NEXT ACTION = {NEXT_ACTION}",
        "",
        "## 1. Result",
        "",
        f"{result}. Offline design only. No provider call. No WIN001 retry.",
        "",
        "## 2. Objective",
        "",
        "Determine whether window-analysis-1.0 asks for too much output for a",
        "~12.7k-word / 2787-SRC window, then design a bounded granularity",
        "policy that preserves meaning, traceability, and uncertainty without",
        "raising max_output or shrinking windows.",
        "",
        "## 3. Baseline",
        "",
        f"Baseline pytest: {payload['baseline']['passed']} passed, "
        f"{payload['baseline']['failed']} failed.",
        "",
        "## 4. Failed WIN001 evidence",
        "",
        "3B.7.7A FAIL CONTROLLED. 1 generate, 1 Anthropic POST, 0 retries.",
        "provider output_tokens = 32000 = configured max_output.",
        "Proximate failure: AIStructuredOutputError after HTTP success.",
        "Evidence not rewritten.",
        "",
        "## 5. Diagnosis carried forward",
        "",
        "MULTIPLE CONTRIBUTING FACTORS. Local parse after HTTP success;",
        "output sat on the 32000 ceiling; records[] unbounded; local input",
        "estimator ≠ provider billing. This phase bounds output only.",
        "",
        "## 6. Current prompt granularity audit",
        "",
    ]
    for row in audit["dimensions"]:
        lines.append(f"- {row['dimension']}: {row['status']} — {row['evidence']}")
    lines.extend(
        [
            "",
            "## 7. Current transport audit",
            "",
            f"semantic-transport-v1 records[] has no maxItems. Generation C unchanged.",
            "",
            "## 8. Record kinds",
            "",
        ]
    )
    for row in kinds:
        lines.append(
            f"- {row['kind']} → {row['canonical_destination']}; "
            f"many={row['potentially_many']}; substantive={row['substantive']}; "
            f"grouping={row['semantic_grouping_possible']}"
        )
    lines.extend(
        [
            "",
            "## 9. Current unbounded dimensions",
            "",
            ", ".join(audit["unbounded"]) + ".",
            f"Combinatorial relations possible: {_yn(audit['combinatorial_relations_possible'])}.",
            f"Duplicate ideas from restatement possible: {_yn(audit['duplicate_ideas_from_restatement_possible'])}.",
            "",
            "## 10. Semantic grouping principle",
            "",
            GRANULARITY_PRINCIPLE + ".",
            "Not per sentence, SRC, paragraph, or repeated statement.",
            "",
            "## 11. Traceability principle",
            "",
            "Grounding SRC IDs remain explicit. Multiple refs encouraged.",
            "No numeric ranges. Canonical still requires non-empty valid ordered refs",
            "for substantive items, not every window SRC.",
            "",
            "## 12. No-silent-drop principle",
            "",
            "Bounding is grouping at the right abstraction, not first-N then stop.",
            "If faithful analysis exceeds ceilings, signal overflow.",
            "",
            "## 13. Overflow principle",
            "",
            "analysis_capacity_exceeded as exact UNCERTAINTY.v.",
            "Window is NOT READY. No canonical partial result.",
            "",
            "## 14. Output budget",
            "",
            "Typical large analysis target ~16k local estimated output tokens.",
            "Worst policy-valid structure must stay under 65% of 32000 locally.",
            "",
            "## 15. Structural size study",
            "",
            "Synthetic valid transports. Local ceil(chars/4). Not Anthropic output tokens.",
            "",
        ]
    )
    for name in ("SMALL", "MEDIUM", "LARGE", "STRESS", "MAX_POLICY_VALID"):
        section = {
            "SMALL": "16",
            "MEDIUM": "17",
            "LARGE": "18",
            "STRESS": "19",
            "MAX_POLICY_VALID": "20",
        }[name]
        row = study["scenarios"][name]
        lines.extend(
            [
                f"## {section}. {name} scenario",
                "",
                f"records={row['record_count']}; bytes={row['json_bytes']}; "
                f"local tokens={row['local_estimated_tokens']}; "
                f"{row['percent_of_32000']}% of 32000.",
                "",
            ]
        )
    lines.extend(
        [
            "## 21. Topic policy",
            "",
            f"Soft {SOFT_TARGETS['TOPIC']} / hard {HARD_CEILINGS['TOPIC']}.",
            "A ~12.7k-word oral teaching typically has one theme and several movements.",
            "14 is enough for dense multi-movement speech; 20 would invite topical sprawl.",
            "",
            "## 22. Idea policy",
            "",
            f"Soft {IDEA_SOFT_TARGET} / hard {IDEA_HARD_CEILING}.",
            "About one distinct unit per 200–300 oral words after grouping.",
            "64 is ~1 idea / 200 words worst case; 2787 SRC would be 43× over.",
            "",
            "## 23. Relation policy",
            "",
            f"Soft {SOFT_TARGETS['RELATION']} / hard {RELATION_HARD_CEILING}.",
            "Important structural links only. No complete graph.",
            "",
            "## 24. Example policy",
            "",
            f"Soft {SOFT_TARGETS['EXAMPLE']} / hard {HARD_CEILINGS['EXAMPLE']}.",
            "Identify/summarize. Do not transcribe narratives.",
            "",
            "## 25. Reference policy",
            "",
            f"Soft {SOFT_TARGETS['REFERENCE']} / hard {HARD_CEILINGS['REFERENCE']}.",
            "Source-mentioned references only. No external bibliography.",
            "",
            "## 26. Uncertainty policy",
            "",
            f"Soft {SOFT_TARGETS['UNCERTAINTY']} / hard {HARD_CEILINGS['UNCERTAINTY']}.",
            "Preserved. Repeated manifestations may be grouped.",
            "",
            "## 27. Repetition policy",
            "",
            f"Soft {SOFT_TARGETS['REPETITION']} / hard {HARD_CEILINGS['REPETITION']}.",
            "One record per repeated semantic motif, not per occurrence pair.",
            "",
            "## 28. Voice policy",
            "",
            f"Soft {SOFT_TARGETS['VOICE']} / hard {HARD_CEILINGS['VOICE']}.",
            "Compact evidence. Not dozens of stylistic fragments.",
            "",
            "## 29. Intent policy",
            "",
            f"Soft {SOFT_TARGETS['INTENT_KIND']} / hard {HARD_CEILINGS['INTENT_KIND']}.",
            "",
            "## 30. Audience policy",
            "",
            f"Soft {SOFT_TARGETS['AUDIENCE_KIND']} / hard {HARD_CEILINGS['AUDIENCE_KIND']}.",
            "",
            "## 31. Total record policy",
            "",
            f"Soft {policy['total_soft_target']} / hard {TOTAL_HARD_CEILING}.",
            "Below the sum of per-kind hards so kinds must trade off.",
            "",
            "## 32. Soft targets",
            "",
            str(SOFT_TARGETS),
            "",
            "## 33. Hard ceilings",
            "",
            str(HARD_CEILINGS),
            "",
            "## 34. Text size policy",
            "",
            "Hard character limits per semantic value. Local reject, never slice.",
            str(policy["text_hard_limits"]),
            "",
            "## 35. Source refs",
            "",
            f"Hard max {policy['source_refs_hard_max']} per record.",
            "List grounding SRCs. Multiple encouraged. No ranges.",
            "Canonical contract unchanged: non-empty, existing, source-order.",
            "",
            "## 36. Relation explosion prevention",
            "",
            "Prompt forbids exhaustive pairwise generation. Local RELATION ceiling.",
            "",
            "## 37. Repetition grouping",
            "",
            "One REPETITION may point at several related IDEA records / SRC refs.",
            "",
            "## 38. Idea grouping",
            "",
            "AI may group several SRC statements into one IDEA. Python must not.",
            "",
            "## 39. Minor ideas",
            "",
            "Importance minor remains legal. Do not promote every sentence.",
            "",
            "## 40. Questions",
            "",
            "Substantive author questions remain IDEA kind=question.",
            "Rhetorical interrogatives are not automatic records.",
            "",
            "## 41. Testimonies",
            "",
            "Represent concisely. Do not transcribe the story.",
            "",
            "## 42. Coverage",
            "",
            "Semantic/descriptive. Central regions should appear. Not every SRC.",
            "",
            "## 43. Completeness self-check",
            "",
            "Internal check only. Output is the transport, not chain-of-thought.",
            "",
            "## 44. Overflow behavior",
            "",
            "Signal → persist transport → NOT READY → no result.json → no retry.",
            "",
            "## 45. Prompt successor",
            "",
            f"{WINDOW_ANALYSIS_PROMPT_VERSION}. Historical 1.0 byte-identical.",
            "",
            "## 46. Prompt size delta",
            "",
            f"system chars {pre['old_system_chars']} → {pre['new_system_chars']} "
            f"(delta {pre['system_char_delta']}).",
            f"local estimate {pre['old_local_estimate']} → {pre['new_local_estimate']} "
            f"(delta {pre['local_estimate_delta']}).",
            "",
            "## 47. Transport version decision",
            "",
            "semantic-transport-v1 kept. Overflow uses reserved UNCERTAINTY.v.",
            "Generation C unchanged. No record-value abuse beyond a protocol token",
            "in a free-text field, locally recognized and never published as canonical.",
            "",
            "## 48. Validator changes",
            "",
            "Additive granularity checks after transport persist. Existing SRC,",
            "intermediate ID, editorial, and vocabulary checks remain.",
            "",
            "## 49. Error classification",
            "",
            "WindowSemanticCapacityExceeded vs WindowGranularityLimitExceeded.",
            "Not schema parse errors.",
            "",
            "## 50. Transport-first behavior",
            "",
            "Over-limit and overflow: transport persists, result absent, no retry.",
            "",
            "## 51. Signature invalidation",
            "",
            f"1.0 vs 1.1 signatures differ: {_yn(pre['signatures_differ'])}.",
            "",
            "## 52. Cache behavior",
            "",
            "Existing 3B.7.3 signature includes prompt version/SHA. 1.1 is a miss",
            "against a 1.0 cache. No special hack.",
            "",
            "## 53. Consolidation compatibility",
            "",
            f"{_yn(impl['consolidation_compatibility'])}. Bounded WindowSemanticResult",
            "is still the same DTO.",
            "",
            "## 54. Reconstructor compatibility",
            "",
            f"{_yn(impl['reconstructor_compatibility'])}. Successful bounded results",
            "remain HybridCanonicalReconstructor input.",
            "",
            "## 55. Canonical compatibility",
            "",
            "SourceMap schema unchanged.",
            "",
            "## 56. FakeAI bounded success",
            "",
            "Rich in-policy transport passes.",
            "",
            "## 57. FakeAI hard-limit failure",
            "",
            "IDEA over ceiling: transport kept, result rejected.",
            "",
            "## 58. FakeAI relation explosion",
            "",
            "Ideas in limit, relations over ceiling: fail closed.",
            "",
            "## 59. FakeAI overflow",
            "",
            "analysis_capacity_exceeded → NOT READY, no canonical result.",
            "",
            "## 60. Multi-SRC grouping",
            "",
            "One IDEA with several SRC refs passes.",
            "",
            "## 61. No-local-grouping proof",
            "",
            "Two similar IDEA records stay two ideas. Python does not merge.",
            "",
            "## 62. E2E FakeAI regression",
            "",
            "3B.7.5 hybrid E2E with successor prompt: valid SourceMap, validator PASS.",
            "",
            "## 63. WIN001 bounded offline preflight",
            "",
            f"Request rebuilt. real_calls={pre['real_calls']}. "
            f"payload_bytes={pre['payload_bytes_new']}.",
            "",
            "## 64. Input estimate delta",
            "",
            f"{pre['local_estimate_delta']} local estimator tokens. "
            "Not a provider billing prediction.",
            "",
            "## 65. Output safety margin",
            "",
            f"MAX_POLICY_VALID {max_valid['local_estimated_tokens']} / 32000 = "
            f"{max_valid['percent_of_32000']}%. "
            f"Within 65% target: {_yn(study['within_safety_margin'])}.",
            "",
            "## 66. Cost implications",
            "",
            "Bounding should reduce output-cost variance. Fidelity first.",
            "Input 2.16× issue is not solved here.",
            "",
            "## 67. Remaining input-token issue",
            "",
            "60000 planner units are local estimator units, not provider billing.",
            "Observed WIN001 provider input was 2.155975 × local estimate.",
            "",
            "## 68. Tests",
            "",
            ", ".join(impl["tests"]) + ".",
            "",
            "## 69. Network",
            "",
            "0.",
            "",
            "## 70. Protected artifacts",
            "",
            "3B.7.7A and 3B.7.7A.1 evidence byte-identical.",
            "",
            "## 71. CLEAN integrity",
            "",
            "Byte-identical. Not rewritten.",
            "",
            "## 72. SourceMap status",
            "",
            "Absent.",
            "",
            "## 73. Project state",
            "",
            "Not SUCCESS.",
            "",
            "## 74. Files added",
            "",
            "\n".join(f"- {name}" for name in impl["modules_added"]),
            "",
            "## 75. Files modified",
            "",
            "\n".join(f"- {name}" for name in impl["modules_changed"]),
            "",
            "## 76. Technical decision",
            "",
            "Keep max_output=32000 and the 3-window plan. Bound semantic output",
            "via 1.1 prompt + local hard ceilings + overflow signal in existing",
            "transport. Do not raise max_output. Do not shrink windows yet.",
            "",
            "## 77. Recommended next phase",
            "",
            NEXT_PHASE_LABEL + ".",
            "Rebuild the exact bounded WIN001 request, verify signature/cache/",
            "limits/forensics, estimate cost scenarios, define one-call",
            "authorization, and STOP. Do not perform the retry there.",
            "",
        ]
    )
    return "\n".join(lines)
