"""Constantes 3B.7.7A.45 — preflight exact production 3.0. Offline. 0 provider."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis.consolidation_models import CONSOLIDATION_SAFE_INPUT_BUDGET_TOKENS
from app.source_analysis_v31_global_drop_domain.constants import (
    A40_ELAPSED_MS,
    A40_OUTPUT_TOKENS,
    A40_RAW_TEXT_CHARS,
    A40_REQUEST_ID,
)
from app.source_analysis_v31_global_output_architecture.constants import (
    A34_STATUS_PRESERVED,
    A35_STATUS_PRESERVED,
    A36_STATUS_PRESERVED,
    A37_STATUS_PRESERVED,
    A38_CHARS_PER_PROVIDER_OUTPUT_TOKEN,
    A38_ELAPSED_SECONDS,
    A38_INPUT_TOKENS,
    A38_OUTPUT_TOKENS,
    A38_RAW_TEXT_CHARS,
    A38_REQUEST_ID,
    A38_STATUS_PRESERVED,
    DROP_REASONS_V20,
    EXPECTED_EXAMPLE,
    EXPECTED_IDEA,
    EXPECTED_REFERENCE,
    EXPECTED_RELATION,
    EXPECTED_TOPIC,
    EXPECTED_TOTAL_RECORDS,
    EXPECTED_UNCERTAINTY,
    RETIRED_DISPOSITION_OPS_V20,
    RETIRED_DROP_REASONS_V20,
    TEXT_LIMITS,
)
from app.source_analysis_v31_global_preflight.constants import (
    CONTEXT_WINDOW_TOKENS,
    HISTORICAL_GLOBAL_TIMEOUTS,
    IDEA_DISPOSITION_COVERAGE_REQUIRED,
    IDEA_KIND_POLICY,
    INPUT_COST_PER_1M,
    MIXED_PROVENANCE,
    OUTPUT_COST_PER_1M,
    READY_COUNT,
    READY_LABEL,
    READY_WINDOWS,
    RELATION_QUALITY_TECHNICAL_DEBT,
)
from app.source_analysis_v31_global_real_consolidation.constants import (
    EXPECTED_CROSS_WINDOW_OWNERSHIP_VIOLATIONS,
    EXPECTED_DISTINCT_SRC,
    EXPECTED_NORMALIZED_CHARS,
    EXPECTED_SRC_OCCURRENCES,
)
from app.source_analysis_v31_global_reuse_output.constants import (
    A39_STATUS_PRESERVED,
    A40_STATUS_PRESERVED,
    A41_STATUS_PRESERVED,
    A42_CHARS_PER_TOKEN,
    A42_ESTIMATOR_ERROR_PERCENT,
    A42_OUTPUT_TOKENS,
    A42_RAW_TEXT_CHARS,
    A42_REQUEST_ID,
    A42_STATUS_PRESERVED,
    ESTIMATOR_ERROR_BUFFER as A43_ESTIMATOR_ERROR_BUFFER,
    EXPECTED_DROPS,
    EXPECTED_GLOBAL_IDEAS,
    EXPECTED_REUSED_IDEAS,
    EXPECTED_SYNTHESIZED_IDEAS,
    NEXT_PROMPT_VERSION,
    NEXT_SCHEMA_ADAPTED_BYTES,
    NEXT_SCHEMA_HASH,
    NEXT_TRANSPORT_VERSION,
    NEXT_SCHEMA_RAW_BYTES,
    PRODUCTION_MAX_OUTPUT_TOKENS as A43_MAX_OUTPUT,
    REPORT_NAME as A43_REPORT_NAME,
    SELECTED_ARCHITECTURE,
    SYNTHESIZED_IDEA_MAX_CHARS,
)
from app.source_analysis_v31_global_reuse_output.estimator import revised_reuse_budget
from app.source_analysis_v31_global_v30_grammar_canary.constants import (
    A43_STATUS_PRESERVED,
    CANARY_CONNECT_TIMEOUT_SECONDS,
    CANARY_READ_TIMEOUT_SECONDS,
    FROZEN_GRANULARITY,
    FROZEN_PLANNER,
    FROZEN_PROMPT,
    FROZEN_SRC_POLICY,
    FROZEN_TRANSPORT,
    MODEL,
    PROJECT_NAME,
    PROVIDER,
    REPORT_NAME as A44_REPORT_NAME,
    THINKING_CONTRACT,
    THINKING_MODE,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.45"
MODE = "GLOBAL_CONSOLIDATION_3_0_EXACT_PRODUCTION_REQUEST_PREFLIGHT"
AUTHORIZATION_SCOPE = "GLOBAL_CONSOLIDATION_3_0_EXACT_PRODUCTION_PREFLIGHT_ONLY"
FUTURE_AUTHORIZATION_SCOPE = "GLOBAL_CONSOLIDATION_3_0_REAL_CANARY_EXACT_REQUEST_ONLY"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_ANTHROPIC_CALLS = 0
REAL_OPENAI_CALLS = 0
GRAMMAR_CANARY_CALLS = 0
REAL_CONSOLIDATION_CALLS = 0
CONSOLIDATION_AUTHORIZED = False
SOURCE_MAP_PUBLICATION_AUTHORIZED = False

A44_STATUS_PRESERVED = "PASS"
assert A34_STATUS_PRESERVED == "PASS"
assert A35_STATUS_PRESERVED == "FAIL"
assert A36_STATUS_PRESERVED == "PASS"
assert A37_STATUS_PRESERVED == "PASS"
assert A38_STATUS_PRESERVED == "FAIL"
assert A39_STATUS_PRESERVED == "PASS"
assert A40_STATUS_PRESERVED == "FAIL"
assert A41_STATUS_PRESERVED == "PASS"
assert A42_STATUS_PRESERVED == "PASS"
assert A43_STATUS_PRESERVED == "PASS"
assert A44_STATUS_PRESERVED == "PASS"
assert SELECTED_ARCHITECTURE == "HARD_SINGLE_MEMBER_REUSE_SYNTHESIZE_MERGES_ONLY"
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert THINKING_MODE == "disabled"
assert NEXT_PROMPT_VERSION == "global-consolidation-3.0"
assert NEXT_TRANSPORT_VERSION == "global-consolidation-transport-3.0"
assert NEXT_SCHEMA_RAW_BYTES == 1583
assert NEXT_SCHEMA_ADAPTED_BYTES == 1831
assert NEXT_SCHEMA_HASH == (
    "822397b642b0e1724e29686962caab32bff63effe18f05bff26b404bad9b2a90"
)
assert DROP_REASONS_V20 == ("transport_artifact", "non_substantive_fragment")
assert RETIRED_DROP_REASONS_V20 == ("exact_duplicate",)
assert RETIRED_DISPOSITION_OPS_V20 == ("OTHER",)
assert IDEA_KIND_POLICY == "KEEP_EMPTY_GLOBALLY"
assert IDEA_DISPOSITION_COVERAGE_REQUIRED == 100
assert READY_WINDOWS == (
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
)
assert READY_COUNT == 7
assert READY_LABEL == "7 / 7"
assert EXPECTED_TOPIC == 67
assert EXPECTED_IDEA == 286
assert EXPECTED_RELATION == 127
assert EXPECTED_EXAMPLE == 49
assert EXPECTED_REFERENCE == 59
assert EXPECTED_UNCERTAINTY == 35
assert EXPECTED_TOTAL_RECORDS == 623
assert EXPECTED_SRC_OCCURRENCES == 2143
assert EXPECTED_DISTINCT_SRC == 1743
assert EXPECTED_CROSS_WINDOW_OWNERSHIP_VIOLATIONS == 0
assert SYNTHESIZED_IDEA_MAX_CHARS == 180
assert A43_MAX_OUTPUT == 48000
assert CONSOLIDATION_SAFE_INPUT_BUDGET_TOKENS == 80000
assert CONTEXT_WINDOW_TOKENS == 1_000_000

PROMPT_VERSION = NEXT_PROMPT_VERSION
TRANSPORT_VERSION = NEXT_TRANSPORT_VERSION
SCHEMA_RAW_BYTES = NEXT_SCHEMA_RAW_BYTES
SCHEMA_ADAPTED_BYTES = NEXT_SCHEMA_ADAPTED_BYTES
SCHEMA_HASH = NEXT_SCHEMA_HASH
A43_SCHEMA_ARTIFACT = "global_consolidation_reuse_next_schema.json"

A44_REQUEST_ID = "req_011CfY6EGQtoB2iSvDaHNCwx"
A44_HTTP_STATUS = 200
A44_FINISH_REASON = "end_turn"
A44_THINKING_TOKENS = 0
A44_INPUT_TOKENS = 4963
A44_OUTPUT_TOKENS = 520
A44_RAW_TEXT_CHARS = 1007
A44_COST_USD = 0.015126
A44_ELAPSED_MS = 8952
A44_ELAPSED_SECONDS = 8.95
A44_LOCAL_INPUT_ESTIMATE = 2125
A44_INPUT_RATIO = A44_INPUT_TOKENS / A44_LOCAL_INPUT_ESTIMATE
A44_CHARS_PER_TOKEN = A44_RAW_TEXT_CHARS / A44_OUTPUT_TOKENS
A44_ESTIMATOR_ERROR_PERCENT = 11.83
A44_PREDICTED_OUTPUT = 465
GLOBAL_TRANSPORT_3_0_GRAMMAR_PROOF = "PASS"
GLOBAL_CONSOLIDATION_3_0_REUSE_CONTRACT_CANARY = "PASS"
assert abs(A44_CHARS_PER_TOKEN - 1.9365384615384615) < 1e-12
assert abs(A44_INPUT_RATIO - 2.335529411764706) < 1e-12

A38_PRODUCTION_INPUT_TOKENS = A38_INPUT_TOKENS
A38_INPUT_RATIO = 1.8438599339719652
A43_ESTIMATED_PRODUCTION_INPUT = 68405
assert A38_PRODUCTION_INPUT_TOKENS == 68138
assert A38_ELAPSED_SECONDS == 219.7

A40_CHARS_PER_TOKEN = A40_RAW_TEXT_CHARS / A40_OUTPUT_TOKENS
A38_CHARS_PER_TOKEN = A38_CHARS_PER_PROVIDER_OUTPUT_TOKEN

PRODUCTION_MAX_OUTPUT_TOKENS = A43_MAX_OUTPUT
SAFETY_70 = int(PRODUCTION_MAX_OUTPUT_TOKENS * 0.70)
SAFETY_75 = int(PRODUCTION_MAX_OUTPUT_TOKENS * 0.75)
SAFETY_80 = int(PRODUCTION_MAX_OUTPUT_TOKENS * 0.80)
assert PRODUCTION_MAX_OUTPUT_TOKENS == 48000
assert SAFETY_70 == 33600
assert SAFETY_75 == 36000
assert SAFETY_80 == 38400

_A43_BUDGET = revised_reuse_budget()
A43_EXPECTED_OUTPUT = int(_A43_BUDGET["p50_expected"])
A43_CONSERVATIVE_OUTPUT = int(_A43_BUDGET["conservative"])
A43_HARD_OUTPUT = int(_A43_BUDGET["hard_planning"])
assert A43_EXPECTED_OUTPUT == 12302
assert A43_CONSERVATIVE_OUTPUT == 16822
assert A43_HARD_OUTPUT == 25486

CHARS_PER_TOKEN_EXPECTED = A44_CHARS_PER_TOKEN
CHARS_PER_TOKEN_CONSERVATIVE = min(
    A44_CHARS_PER_TOKEN,
    float(A42_CHARS_PER_TOKEN),
    float(A40_CHARS_PER_TOKEN),
    2.00,
)
ESTIMATOR_ERROR_BUFFER = round(
    1.0 + max(A44_ESTIMATOR_ERROR_PERCENT, A42_ESTIMATOR_ERROR_PERCENT) / 100.0,
    4,
)
assert ESTIMATOR_ERROR_BUFFER >= A43_ESTIMATOR_ERROR_BUFFER
assert CHARS_PER_TOKEN_CONSERVATIVE == A44_CHARS_PER_TOKEN

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False
EFFORT = None

# A.38 completed in 219.7 s before max_tokens at 32k. 3.0 hard output is smaller.
# Historical 3600/7200 and A.38's 1800 s are larger than needed for one 3.0 call.
CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 600.0
assert CONNECT_TIMEOUT_SECONDS == 30.0
assert READ_TIMEOUT_SECONDS == 600.0
assert HISTORICAL_GLOBAL_TIMEOUTS == (3600, 7200)
assert CANARY_CONNECT_TIMEOUT_SECONDS > 0
assert CANARY_READ_TIMEOUT_SECONDS > 0

STAGE_PREFLIGHT = "source_analysis_v31_global_v30_exact_preflight"
MATERIAL_BOUND_DELTA_RATIO = 0.02

SINGLE_MEMBER_POLICY = "DETERMINISTIC_REUSE"
MULTI_MEMBER_POLICY = "SYNTHESIZE"
REWRITE_EXCEPTION_POLICY = "FORBIDDEN"
RELATION_POLICY = "RELATIONS_DEFERRED"
REPETITION_POLICY = "DEFERRED"

EXPECTED_GLOBAL_IDEA_RANGE = (280, 286)
MERGE_STRESS_SYNTHESIZED = 12
DROP_STRESS_COUNT = 4

A44_CANARY_SUBDIR = "canary/global_consolidation_transport_v30"
A44_USAGE_ARTIFACT = "global_consolidation_v30_usage_cost.json"
A44_EXECUTION_ARTIFACT = "global_consolidation_v30_canary_execution.json"

PROTECTED_HISTORICAL = (
    "audit/PHASE_3B77A34_GLOBAL_CONSOLIDATION_OFFLINE_PREFLIGHT_REPORT.md",
    "audit/PHASE_3B77A35_GLOBAL_CONSOLIDATION_TINY_GRAMMAR_CANARY_REPORT.md",
    "audit/PHASE_3B77A36_GLOBAL_CONSOLIDATION_CANARY_FORENSICS_REPORT.md",
    "audit/PHASE_3B77A37_GLOBAL_CONSOLIDATION_V11_TINY_GRAMMAR_CANARY_REPORT.md",
    "audit/PHASE_3B77A38_FIRST_REAL_GLOBAL_CONSOLIDATION_CANARY_REPORT.md",
    "audit/PHASE_3B77A39_GLOBAL_CONSOLIDATION_OUTPUT_ARCHITECTURE_REDESIGN_REPORT.md",
    "audit/PHASE_3B77A40_COMPACT_GLOBAL_CONSOLIDATION_V20_GRAMMAR_CANARY_REPORT.md",
    "audit/PHASE_3B77A41_COMPACT_GLOBAL_CONSOLIDATION_TYPE_BOUNDARY_HARDENING_REPORT.md",
    "audit/PHASE_3B77A42_COMPACT_GLOBAL_CONSOLIDATION_V201_CONTRACT_CANARY_REPORT.md",
    f"audit/{A43_REPORT_NAME}",
    f"audit/{A44_REPORT_NAME}",
    f"audit/{A44_CANARY_SUBDIR}/{A44_USAGE_ARTIFACT}",
    f"audit/{A44_CANARY_SUBDIR}/{A44_EXECUTION_ARTIFACT}",
)

INVENTORY_ARTIFACT = "global_consolidation_a45_exact_inventory.json"
WINDOW_MANIFEST_ARTIFACT = "global_consolidation_a45_window_manifest.json"
NORMALIZED_INPUT_ARTIFACT = "global_consolidation_a45_normalized_input_manifest.json"
REQUEST_ARTIFACT = "global_consolidation_a45_exact_request.json"
REQUEST_IDENTITY_ARTIFACT = "global_consolidation_a45_request_identity.json"
INPUT_BUDGET_ARTIFACT = "global_consolidation_a45_input_budget.json"
OUTPUT_BUDGET_ARTIFACT = "global_consolidation_a45_output_budget.json"
OUTPUT_COMPONENTS_ARTIFACT = "global_consolidation_a45_output_component_breakdown.json"
COST_ARTIFACT = "global_consolidation_a45_estimated_cost.json"
CONTRACT_ARTIFACT = "global_consolidation_a45_contract_consistency.json"
PUBLICATION_ARTIFACT = "global_consolidation_a45_publication_gate.json"
FUTURE_GUARD_ARTIFACT = "global_consolidation_a45_future_call_guard.json"
FAKEAI_ARTIFACT = "global_consolidation_a45_full_scale_fakeai.json"
SEMANTIC_PLAN_ARTIFACT = "global_consolidation_a45_post_call_semantic_review_plan.json"
READINESS_ARTIFACT = "global_consolidation_post_a45_readiness.json"
TEST_DELTA_ARTIFACT = "source_analysis_a45_test_delta.json"
BASELINE_ARTIFACT = "source_analysis_a45_test_baseline.json"
REPORT_NAME = (
    "PHASE_3B77A45_GLOBAL_CONSOLIDATION_V30_EXACT_PRODUCTION_PREFLIGHT_REPORT.md"
)

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_v30_exact_preflight.py",
    "app/tests/test_source_analysis_v31_global_v30_exact_preflight_audit.py",
)
BROADER_SLICE_TEST_PATHS = FOCUSED_TEST_PATHS + (
    "app/tests/test_source_analysis_v31_global_v30_grammar_canary.py",
    "app/tests/test_source_analysis_v31_global_v30_grammar_canary_audit.py",
    "app/tests/test_source_analysis_v31_global_reuse_output.py",
    "app/tests/test_source_analysis_v31_global_reuse_output_audit.py",
    "app/tests/test_source_analysis_v31_global_v201_contract_canary.py",
    "app/tests/test_source_analysis_v31_global_v201_contract_canary_audit.py",
    "app/tests/test_source_analysis_v31_global_drop_domain.py",
    "app/tests/test_source_analysis_v31_global_drop_domain_audit.py",
    "app/tests/test_source_analysis_v31_global_v20_grammar_canary.py",
    "app/tests/test_source_analysis_v31_global_output_architecture.py",
)

PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
NEXT_ACTION = "HUMAN REVIEW"
LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN = "YES"
READY_FOR_ONE_REAL_GLOBAL_CONSOLIDATION_CANARY = "YES"

SECRET_KEY_NAMES = (
    "api_key",
    "authorization",
    "x-api-key",
    "X-Api-Key",
    "ANTHROPIC_API_KEY",
    "OPENAI_API_KEY",
    "headers",
)
SECRET_SUBSTRINGS = (
    "sk-ant-",
    "sk-proj-",
    "Bearer ",
    "x-api-key",
)

assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert REAL_ANTHROPIC_CALLS == 0
assert REAL_OPENAI_CALLS == 0
assert GRAMMAR_CANARY_CALLS == 0
assert REAL_CONSOLIDATION_CALLS == 0
assert CONSOLIDATION_AUTHORIZED is False
assert SOURCE_MAP_PUBLICATION_AUTHORIZED is False
assert RELATION_QUALITY_TECHNICAL_DEBT == "YES"
assert not source_map_path(PROJECT_NAME).is_file() or SOURCE_MAP_STATUS == "NOT PUBLISHED"
assert FROZEN_PLANNER == "window-planner-v2.1-small"
assert FROZEN_PROMPT == "window-analysis-1.4.0"
assert FROZEN_TRANSPORT == "semantic-transport-v3.1-local-lite"
assert FROZEN_GRANULARITY == "window-granularity-1.2-kind-specific"
assert FROZEN_SRC_POLICY == "src-reference-policy-1.1-narrow-canonicalization"

__all__ = [
    "A34_STATUS_PRESERVED",
    "A35_STATUS_PRESERVED",
    "A36_STATUS_PRESERVED",
    "A37_STATUS_PRESERVED",
    "A38_CHARS_PER_TOKEN",
    "A38_ELAPSED_SECONDS",
    "A38_INPUT_RATIO",
    "A38_PRODUCTION_INPUT_TOKENS",
    "A38_REQUEST_ID",
    "A38_STATUS_PRESERVED",
    "A39_STATUS_PRESERVED",
    "A40_CHARS_PER_TOKEN",
    "A40_ELAPSED_MS",
    "A40_REQUEST_ID",
    "A40_STATUS_PRESERVED",
    "A41_STATUS_PRESERVED",
    "A42_CHARS_PER_TOKEN",
    "A42_REQUEST_ID",
    "A42_STATUS_PRESERVED",
    "A43_CONSERVATIVE_OUTPUT",
    "A43_ESTIMATED_PRODUCTION_INPUT",
    "A43_EXPECTED_OUTPUT",
    "A43_HARD_OUTPUT",
    "A43_REPORT_NAME",
    "A43_SCHEMA_ARTIFACT",
    "A43_STATUS_PRESERVED",
    "A44_CANARY_SUBDIR",
    "A44_CHARS_PER_TOKEN",
    "A44_COST_USD",
    "A44_ELAPSED_MS",
    "A44_ELAPSED_SECONDS",
    "A44_ESTIMATOR_ERROR_PERCENT",
    "A44_EXECUTION_ARTIFACT",
    "A44_FINISH_REASON",
    "A44_HTTP_STATUS",
    "A44_INPUT_RATIO",
    "A44_INPUT_TOKENS",
    "A44_LOCAL_INPUT_ESTIMATE",
    "A44_OUTPUT_TOKENS",
    "A44_PREDICTED_OUTPUT",
    "A44_RAW_TEXT_CHARS",
    "A44_REPORT_NAME",
    "A44_REQUEST_ID",
    "A44_STATUS_PRESERVED",
    "A44_THINKING_TOKENS",
    "A44_USAGE_ARTIFACT",
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "BASELINE_ARTIFACT",
    "BROADER_SLICE_TEST_PATHS",
    "CHARS_PER_TOKEN_CONSERVATIVE",
    "CHARS_PER_TOKEN_EXPECTED",
    "CONSOLIDATION_AUTHORIZED",
    "CONSOLIDATION_SAFE_INPUT_BUDGET_TOKENS",
    "CONTEXT_WINDOW_TOKENS",
    "CONTRACT_ARTIFACT",
    "CONNECT_TIMEOUT_SECONDS",
    "COST_ARTIFACT",
    "DROP_REASONS_V20",
    "DROP_STRESS_COUNT",
    "EFFORT",
    "ESTIMATOR_ERROR_BUFFER",
    "EXPECTED_CROSS_WINDOW_OWNERSHIP_VIOLATIONS",
    "EXPECTED_DISTINCT_SRC",
    "EXPECTED_DROPS",
    "EXPECTED_EXAMPLE",
    "EXPECTED_GLOBAL_IDEA_RANGE",
    "EXPECTED_GLOBAL_IDEAS",
    "EXPECTED_IDEA",
    "EXPECTED_NORMALIZED_CHARS",
    "EXPECTED_REFERENCE",
    "EXPECTED_RELATION",
    "EXPECTED_REUSED_IDEAS",
    "EXPECTED_SRC_OCCURRENCES",
    "EXPECTED_SYNTHESIZED_IDEAS",
    "EXPECTED_TOPIC",
    "EXPECTED_TOTAL_RECORDS",
    "EXPECTED_UNCERTAINTY",
    "FAKEAI_ARTIFACT",
    "FOCUSED_TEST_PATHS",
    "FROZEN_GRANULARITY",
    "FROZEN_PLANNER",
    "FROZEN_PROMPT",
    "FROZEN_SRC_POLICY",
    "FROZEN_TRANSPORT",
    "FUTURE_AUTHORIZATION_SCOPE",
    "FUTURE_GUARD_ARTIFACT",
    "GLOBAL_CONSOLIDATION_3_0_REUSE_CONTRACT_CANARY",
    "GLOBAL_TRANSPORT_3_0_GRAMMAR_PROOF",
    "GRAMMAR_CANARY_CALLS",
    "HISTORICAL_GLOBAL_TIMEOUTS",
    "IDEA_DISPOSITION_COVERAGE_REQUIRED",
    "IDEA_KIND_POLICY",
    "INPUT_BUDGET_ARTIFACT",
    "INPUT_COST_PER_1M",
    "INVENTORY_ARTIFACT",
    "LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN",
    "MATERIAL_BOUND_DELTA_RATIO",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MERGE_STRESS_SYNTHESIZED",
    "MIXED_PROVENANCE",
    "MODE",
    "MODEL",
    "MULTI_MEMBER_POLICY",
    "NEXT_ACTION",
    "NORMALIZED_INPUT_ARTIFACT",
    "OUTPUT_BUDGET_ARTIFACT",
    "OUTPUT_COMPONENTS_ARTIFACT",
    "OUTPUT_COST_PER_1M",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "PUBLICATION_ARTIFACT",
    "READINESS_ARTIFACT",
    "READY_COUNT",
    "READY_FOR_ONE_REAL_GLOBAL_CONSOLIDATION_CANARY",
    "READY_LABEL",
    "READY_WINDOWS",
    "READ_TIMEOUT_SECONDS",
    "REAL_ANTHROPIC_CALLS",
    "REAL_CONSOLIDATION_CALLS",
    "REAL_OPENAI_CALLS",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "RELATION_POLICY",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPETITION_POLICY",
    "REPORT_NAME",
    "REQUEST_ARTIFACT",
    "REQUEST_IDENTITY_ARTIFACT",
    "REWRITE_EXCEPTION_POLICY",
    "SAFETY_70",
    "SAFETY_75",
    "SAFETY_80",
    "SCHEMA_ADAPTED_BYTES",
    "SCHEMA_HASH",
    "SCHEMA_RAW_BYTES",
    "SCHEMA_VERSION",
    "SECRET_KEY_NAMES",
    "SECRET_SUBSTRINGS",
    "SELECTED_ARCHITECTURE",
    "SEMANTIC_PLAN_ARTIFACT",
    "SINGLE_MEMBER_POLICY",
    "SOURCE_MAP_PUBLICATION_AUTHORIZED",
    "SOURCE_MAP_STATUS",
    "STAGE_PREFLIGHT",
    "SYNTHESIZED_IDEA_MAX_CHARS",
    "TEST_DELTA_ARTIFACT",
    "TEXT_LIMITS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
    "WINDOW_MANIFEST_ARTIFACT",
]
