"""Rapport markdown 3B.7.7A.45."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any], *, tests: str) -> str:
    header = bundle.get("header") or {}
    lines = [
        "# PHASE 3B.7.7A.45 — GLOBAL CONSOLIDATION V3.0 EXACT PRODUCTION PREFLIGHT",
        "",
        "## Result",
        "",
        str(header.get("result")),
        "",
        "REAL PROVIDER CALLS =",
        "0",
        "",
        "A.44 STATUS =",
        str(header.get("a44_status")),
        "",
        "A.44 REQUEST =",
        str(header.get("a44_request")),
        "",
        "READY WINDOWS =",
        str(header.get("ready_windows")),
        "",
        "LOCAL RECORDS =",
        str(header.get("local_records")),
        "",
        "LOCAL TOPICS =",
        str(header.get("local_topics")),
        "",
        "LOCAL IDEAS =",
        str(header.get("local_ideas")),
        "",
        "LOCAL RELATIONS =",
        str(header.get("local_relations")),
        "",
        "LOCAL EXAMPLES =",
        str(header.get("local_examples")),
        "",
        "LOCAL REFERENCES =",
        str(header.get("local_references")),
        "",
        "LOCAL UNCERTAINTIES =",
        str(header.get("local_uncertainties")),
        "",
        "PROMPT =",
        "global-consolidation-3.0",
        "",
        "TRANSPORT =",
        "global-consolidation-transport-3.0",
        "",
        "SCHEMA RAW / ADAPTED =",
        "1583 / 1831",
        "",
        "SCHEMA HASH =",
        "822397b642b0e1724e29686962caab32bff63effe18f05bff26b404bad9b2a90",
        "",
        "SCHEMA IDENTITY =",
        str(header.get("schema_identity")),
        "",
        "MODEL =",
        "claude-sonnet-5",
        "",
        "THINKING =",
        "disabled",
        "",
        "MAX_OUTPUT =",
        "48000",
        "",
        "NORMALIZED INPUT HASH =",
        str(header.get("normalized_input_hash")),
        "",
        "EXACT REQUEST HASH =",
        str(header.get("exact_request_hash")),
        "",
        "REQUEST DETERMINISM =",
        str(header.get("request_determinism")),
        "",
        "REQUEST CHARS =",
        str(header.get("request_chars")),
        "",
        "REQUEST BYTES =",
        str(header.get("request_bytes")),
        "",
        "ESTIMATED INPUT TOKENS =",
        str(header.get("estimated_input_tokens")),
        "",
        "INPUT SAFETY =",
        str(header.get("input_safety")),
        "",
        "EXPECTED OUTPUT =",
        str(header.get("expected_output")),
        "",
        "CONSERVATIVE OUTPUT =",
        str(header.get("conservative_output")),
        "",
        "HARD/PLANNING OUTPUT =",
        str(header.get("hard_planning_output")),
        "",
        "70% LIMIT =",
        "33600",
        "",
        "75% LIMIT =",
        "36000",
        "",
        "80% LIMIT =",
        "38400",
        "",
        "HARD UTILIZATION =",
        str(header.get("hard_utilization")),
        "",
        "ABSOLUTE HEADROOM =",
        str(header.get("absolute_headroom")),
        "",
        "OUTPUT SAFETY =",
        str(header.get("output_safety")),
        "",
        "LARGEST OUTPUT COMPONENT =",
        str(header.get("largest_output_component")),
        "",
        "ALL-DISTINCT 286 REUSE STRESS =",
        str(header.get("all_distinct_286_reuse_stress")),
        "",
        "EXPECTED-MIX STRESS =",
        str(header.get("expected_mix_stress")),
        "",
        "MERGE STRESS =",
        str(header.get("merge_stress")),
        "",
        "DROP STRESS =",
        str(header.get("drop_stress")),
        "",
        "FAKEAI IDEA ACCOUNTABILITY =",
        str(header.get("fakeai_idea_accountability")),
        "",
        "FAKEAI CANONICAL RECONSTRUCTION =",
        str(header.get("fakeai_canonical_reconstruction")),
        "",
        "FAKEAI CANONICAL VALIDATION =",
        str(header.get("fakeai_canonical_validation")),
        "",
        "PROMPT/SCHEMA CONSISTENCY =",
        str(header.get("prompt_schema_consistency")),
        "",
        "DECODER CONSISTENCY =",
        str(header.get("decoder_consistency")),
        "",
        "VALIDATOR CONSISTENCY =",
        str(header.get("validator_consistency")),
        "",
        "RECONSTRUCTOR CONSISTENCY =",
        str(header.get("reconstructor_consistency")),
        "",
        "PUBLICATION GATE =",
        str(header.get("publication_gate")),
        "",
        "REQUEST HASH LOCK =",
        str(header.get("request_hash_lock")),
        "",
        "WINDOW HASH LOCK =",
        str(header.get("window_hash_lock")),
        "",
        "FUTURE CALL COUNT =",
        "1",
        "",
        "FUTURE RETRIES =",
        "0",
        "",
        "FUTURE CONNECT TIMEOUT =",
        str(header.get("future_connect_timeout")),
        "",
        "FUTURE READ TIMEOUT =",
        str(header.get("future_read_timeout")),
        "",
        "ESTIMATED EXPECTED COST =",
        str(header.get("estimated_expected_cost")),
        "",
        "ESTIMATED CONSERVATIVE COST =",
        str(header.get("estimated_conservative_cost")),
        "",
        "ESTIMATED HARD COST =",
        str(header.get("estimated_hard_cost")),
        "",
        "LOCAL EXTRACTION FUNCTIONALLY FROZEN =",
        "YES",
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        "YES",
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        _dash(header.get("new_failures")),
        "",
        "READY_FOR_ONE_REAL_GLOBAL_CONSOLIDATION_CANARY =",
        str(header.get("ready_for_one_real_global_consolidation_canary")),
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
