"""Rapport markdown Phase 4A."""

from __future__ import annotations

from typing import Any, Mapping


def render_report(bundle: Mapping[str, Any], *, tests: str = "offline Phase 4A") -> str:
    header = dict(bundle.get("header") or {})
    inputs = dict(bundle.get("input_budget") or {})
    outputs = dict(bundle.get("output_budget") or {})
    schema = dict(bundle.get("schema_identity") or {})
    fake = dict(bundle.get("fakeai") or {})
    full = dict(bundle.get("full_scale") or {})
    cache = dict(bundle.get("cache") or {})
    thinking = dict((bundle.get("contract") or {}).get("thinking") or {})
    coverage = dict(bundle.get("coverage_policy") or {})
    request = dict(inputs.get("request") or {})
    local_est = dict(request.get("local_token_estimate") or {})
    lines = [
        "# PHASE 4A — EDITORIAL PLANNER ARCHITECTURE AND OFFLINE FOUNDATION",
        "",
        "## Result",
        "",
        str(header.get("result") or "FAIL"),
        "",
        f"REAL PROVIDER CALLS = {header.get('real_provider_calls', 0)}",
        "",
        f"PHASE 3B = {header.get('phase_3b')}",
        "",
        f"SOURCE MAP PATH = {header.get('source_map_path')}",
        "",
        f"SOURCE MAP SHA256 = {header.get('source_map_sha256')}",
        "",
        f"SOURCE MAP INVENTORY = {header.get('source_map_inventory')}",
        "",
        f"SOURCE MAP VALIDATION = {header.get('source_map_validation')}",
        "",
        f"PLANNER PROVIDER = {header.get('planner_provider')}",
        "",
        f"PLANNER MODEL = {header.get('planner_model')}",
        "",
        f"PLANNER PROMPT = {header.get('planner_prompt')}",
        "",
        f"PLANNER TRANSPORT = editorial-plan-transport-1.0",
        "",
        f"CANONICAL EDITORIAL PLAN SCHEMA = {header.get('canonical_schema')}",
        "",
        f"PROVIDER SCHEMA RAW / ADAPTED = {schema.get('raw_schema_bytes')} / {schema.get('adapted_schema_bytes')}",
        "",
        f"PROVIDER SCHEMA HASH = {header.get('provider_schema_hash')}",
        "",
        f"SOURCE MAP CHARS = {header.get('source_map_chars')}",
        "",
        f"SOURCE MAP BYTES = {header.get('source_map_bytes')}",
        "",
        f"LOCAL INPUT TOKEN ESTIMATE = {header.get('local_input_token_estimate')}",
        "",
        f"PROVIDER-ADJUSTED INPUT ESTIMATE = {header.get('provider_adjusted_input_estimate')}",
        "",
        f"USABLE INPUT BUDGET = {header.get('usable_input_budget')}",
        "",
        f"ONE GLOBAL CALL FEASIBLE = {header.get('one_global_call_feasible')}",
        "",
        f"PROPOSED MAX_OUTPUT = {header.get('proposed_max_output')}",
        "",
        f"EXPECTED OUTPUT = {header.get('expected_output')}",
        "",
        f"CONSERVATIVE OUTPUT = {header.get('conservative_output')}",
        "",
        f"HARD OUTPUT = {header.get('hard_output')}",
        "",
        f"IDEA COVERAGE POLICY = {header.get('idea_coverage_policy')}",
        "",
        "SILENT IDEA OMISSION = FORBIDDEN",
        "",
        "TECHNICAL WINDOWS USED AS EDITORIAL UNITS = NO",
        "",
        "RELATION QUALITY DEBT = PRESERVED",
        "",
        f"CANONICAL RECONSTRUCTION = {header.get('canonical_reconstruction')}",
        "",
        f"EDITORIAL PLAN VALIDATOR = {header.get('editorial_plan_validator')}",
        "",
        f"FULL-SCALE FAKEAI IDEA COVERAGE = {header.get('full_scale_fakeai_idea_coverage')}",
        "",
        f"DETERMINISTIC REPLAY = {header.get('deterministic_replay')}",
        "",
        f"CACHE SIGNATURE = {header.get('cache_signature')}",
        "",
        f"TESTS = {header.get('tests') or tests}",
        "",
        f"NEW FAILURES = {header.get('new_failures')}",
        "",
        "editorial_plan.json = NOT PUBLISHED",
        "",
        "BOOK GENERATOR = NOT STARTED",
        "",
        f"PHASE 4A = {header.get('phase_4a')}",
        "",
        f"READY_FOR_EDITORIAL_PLANNER_GRAMMAR_CANARY = {header.get('ready_for_editorial_planner_grammar_canary')}",
        "",
        "READY_FOR_REAL_EDITORIAL_PLANNER_CALL = NO",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
        "## 1. Architectural freeze",
        "",
        "Source Analyzer = WHAT the source contains.",
        "Editorial Planner = HOW validated content is organized as a book.",
        "Book Generator = HOW planned content is expressed as manuscript prose.",
        "",
        "Canonical hierarchy: BOOK -> CHAPTER -> SECTION.",
        "Technical transcription windows are not editorial units.",
        "SourceMap is consumed read-only.",
        "",
        "## 2. Thinking",
        "",
        f"capabilities_known = {thinking.get('capabilities_known')}",
        f"phase4a_thinking_mode = {thinking.get('phase4a_thinking_mode')}",
        f"phase4a_effort = {thinking.get('phase4a_effort')}",
        "",
        str(thinking.get("rationale") or ""),
        "",
        "## 3. Input budget",
        "",
        f"digest chars = {(inputs.get('planner_digest') or {}).get('chars')}",
        f"request local tokens = {local_est.get('tokens')} ({local_est.get('method')})",
        f"provider-adjusted pessimistic = {request.get('provider_adjusted_pessimistic')}",
        f"usable (proposed max_output) = {header.get('usable_input_budget')}",
        f"one global call = {header.get('one_global_call_feasible')}",
        "",
        "## 4. Output budget",
        "",
        f"expected = {outputs.get('expected_output_tokens')}",
        f"conservative = {outputs.get('conservative_output_tokens')}",
        f"hard = {outputs.get('hard_output_tokens')}",
        f"proposed max_output = {outputs.get('proposed_max_output')}",
        "",
        "## 5. Coverage policy",
        "",
        f"dispositions = {coverage.get('dispositions')}",
        f"silent_omission = {coverage.get('silent_omission')}",
        "",
        "## 6. Full-scale offline",
        "",
        f"validation = {(full.get('validation') or {}).get('status')}",
        f"chapters = {full.get('chapters')}",
        f"sections = {full.get('sections')}",
        f"assigned = {full.get('assigned')}",
        f"plan sha256 = {full.get('plan_sha256')}",
        "",
        "## 7. FakeAI",
        "",
        f"status = {fake.get('status')}",
        f"engine calls = {fake.get('engine_calls')}",
        f"cost records = {fake.get('cost_records')}",
        "",
        "## 8. Cache",
        "",
        f"signature = {cache.get('signature')}",
        f"hit = {cache.get('hit_same_signature')}",
        f"miss on change = {cache.get('miss_when_signature_changes')}",
        "",
        "## 9. Publication",
        "",
        "editorial_plan.json was not published.",
        "No book.json / manuscript / Word / PDF / cover work.",
        "",
        "## 10. Next",
        "",
        "Tiny synthetic grammar/contract canary before any real Opus planning call.",
        "WAIT FOR HUMAN REVIEW.",
        "",
    ]
    return "\n".join(lines)
