"""
Phase 4B.2.29 — provisional print-review book.json constitution.

STRICTLY OFFLINE. Zero provider calls. Zero USD.
Assembles the 19 existing chapters into the production book.json contract.
Does not rewrite prose. Does not approve pending chapters.
Does not generate DOCX/PDF. Does not start visual direction.
"""

from __future__ import annotations

from app.book_full_manuscript_review_4b228.constants import (
    ACCEPTED_CHAPTER_COUNT,
    ACCEPTED_CHAPTER_IDS,
    AUTHORIZATION_SCOPE as CONSUMED_4B228_SCOPE,
    CANONICAL_CHAPTER_IDS,
    CH012_ACCEPTED_JSON_REL,
    CH012_ORIGINAL_JSON_REL,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_IDEA_COUNT,
    EXPECTED_SECTION_COUNT,
    EXPECTED_SOURCE_MAP,
    EXPECTED_TRANSCRIPT,
    GENERATED_STRUCTURALLY_VALID,
    HUMAN_ACCEPTANCE_STATUS,
    HUMAN_REVIEW_PENDING_STATUS,
    PENDING_CHAPTER_IDS,
    REMAINING_CHAPTER_COUNT,
    REMAINING_CHAPTER_IDS,
    STRENGTHENED_CLAIM_CHAPTER_IDS,
    TOTAL_CHAPTER_COUNT,
)
from app.book_generation.constants import (
    BOOK_FILENAME,
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    BOOK_SCHEMA_VERSION,
    TITLE_STATUS_WORKING,
    VALIDATION_PROJECT_NAME,
)
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE

PHASE = "4B.2.29"
PHASE_NAME = "PRINT_REVIEW_BOOK_CANONICAL"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_PRINT_REVIEW_CANONICAL_4B229_PROVISIONAL_BOOK_JSON_ONLY"
)

AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_TERRA_CALLS = 0
MAX_ENGINE_GENERATE = 0
MAX_ANTHROPIC_POST = 0
MAX_HTTP_REQUESTS = 0
RETRIES = 0
FALLBACKS = 0

PUBLICATION_AUTHORIZED = True
PROVISIONAL_BOOK_JSON_PUBLICATION = True
FINAL_PUBLICATION_AUTHORIZED = False
COMMERCIAL_PUBLICATION_AUTHORIZED = False
PUBLIC_PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
OPENAI_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = False
REAL_CHAPTER_GENERATION_AUTHORIZED = False
REAL_PROVIDERS_ENABLED = False
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
FAITHFUL_PROMPT_1_1_ACTIVATED = False
SEMANTIC_CERTIFICATION_PERFORMED = False
DOCX_GENERATION_AUTHORIZED = False
PDF_GENERATION_AUTHORIZED = False
VISUAL_DIRECTION_AUTHORIZED = False

BOOK_TITLE = "The Life You Already Inherited"
BOOK_LANGUAGE = "en"
BOOK_STATUS = "DRAFT_FOR_PRINT_REVIEW"
BOOK_VERSION = "print-review-v1"
TITLE_STATUS = TITLE_STATUS_WORKING
assert TITLE_STATUS == "working"

HUMAN_ACCEPTED_STATUS = HUMAN_ACCEPTANCE_STATUS
STRUCTURAL_STATUS = GENERATED_STRUCTURALLY_VALID
assert HUMAN_ACCEPTED_STATUS == "HUMAN_EDITORIALLY_ACCEPTED"
assert STRUCTURAL_STATUS == "GENERATED_STRUCTURALLY_VALID"
assert BOOK_STATUS == "DRAFT_FOR_PRINT_REVIEW"
assert BOOK_STATUS != HUMAN_ACCEPTED_STATUS

assert CANONICAL_CHAPTER_IDS[0] == "CH001"
assert CANONICAL_CHAPTER_IDS[-1] == "CH019"
assert len(CANONICAL_CHAPTER_IDS) == TOTAL_CHAPTER_COUNT == 19
assert ACCEPTED_CHAPTER_IDS == ("CH001", "CH002", "CH003", "CH004", "CH012", "CH018")
assert REMAINING_CHAPTER_IDS == PENDING_CHAPTER_IDS
assert ACCEPTED_CHAPTER_COUNT + REMAINING_CHAPTER_COUNT == TOTAL_CHAPTER_COUNT
assert EXPECTED_SECTION_COUNT == 72
assert EXPECTED_IDEA_COUNT == 286
assert len(STRENGTHENED_CLAIM_CHAPTER_IDS) == 8

EXPECTED_MANUSCRIPT_SHA256 = (
    "a9a5696ea4072c0c414eb406237d265b2a95a302d1ddafd1c3e39e8140e5f8fb"
)
EXPECTED_SOURCE_MAP_SHA256 = EXPECTED_SOURCE_MAP
EXPECTED_EDITORIAL_PLAN_SHA256 = EXPECTED_EDITORIAL_PLAN
EXPECTED_TRANSCRIPT_SHA256 = EXPECTED_TRANSCRIPT
assert EXPECTED_SOURCE_MAP_SHA256 == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN_SHA256 == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_TRANSCRIPT_SHA256 == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
CODE_VERSION = "app.book_print_review_canonical_4b229"
SCHEMA_VERSION = BOOK_SCHEMA_VERSION
assert SCHEMA_VERSION == "1.0"
assert BOOK_FILENAME == "book.json"
assert BOOK_GENERATION_TRANSPORT_VERSION == "book-generation-transport-1.0"
assert BOOK_GENERATOR_VALIDATOR_VERSION == "book-generation-validator-1.0.1"

MANUSCRIPT_REL = "audit/book_full_manuscript_review_4b228/manuscript_reading_draft.md"
OBSERVATION_STRENGTHENED_REL = (
    "audit/book_full_manuscript_review_4b228/strengthened_claims_review.json"
)
OBSERVATION_REFERENCES_REL = (
    "audit/book_full_manuscript_review_4b228/references_examples_review.json"
)
OBSERVATION_CONTINUITY_REL = (
    "audit/book_full_manuscript_review_4b228/continuity_review.json"
)
OBSERVATION_EDITORIAL_REL = (
    "audit/book_full_manuscript_review_4b228/editorial_global_review.json"
)
OBSERVATION_REPORT_REL = "audit/PHASE_4B228_FULL_MANUSCRIPT_EDITORIAL_REVIEW_REPORT.md"

EXPECTED_STRENGTHENED_OBSERVATIONS = 8
EXPECTED_REFERENCE_OBSERVATIONS = 19
EXPECTED_CONTINUITY_OBSERVATIONS = 13

ABSENT_EDITORIAL_FIELDS = (
    "author",
    "publisher",
    "isbn",
    "copyright",
    "preface",
    "dedication",
    "biography",
    "acknowledgements",
)

AUDIT_DIRNAME = "book_print_review_canonical_4b229"
AUDIT_BOOK_COPY = "book.json"
AUDIT_MANIFEST = "book_canonical_manifest.json"
AUDIT_CHAPTER_SOURCES = "chapter_sources_manifest.json"
AUDIT_EDITORIAL_STATUS = "editorial_status_manifest.json"
AUDIT_INTEGRITY = "book_integrity_validation.json"
AUDIT_SCHEMA = "book_schema_validation.json"
AUDIT_MARKDOWN = "book_markdown_comparison.json"
AUDIT_WORD = "word_renderer_readiness.json"
AUDIT_OBSERVATIONS = "editorial_observations_manifest.json"
AUDIT_HASHES = "canonical_hashes_pre_post.json"
AUDIT_PUBLICATION = "publication_audit.json"
AUDIT_READINESS = "readiness.json"
AUDIT_PREFLIGHT = "preflight.json"
AUDIT_TESTS = "offline_regression_tests.json"
REPORT_NAME = "PHASE_4B229_PRINT_REVIEW_BOOK_CANONICAL_REPORT.md"

NEXT_ACTION = (
    "WAIT FOR THE NEXT PHASE: VISUAL DIRECTION AND FIRST PRINTABLE PRODUCTION. "
    "DO NOT MODIFY CHAPTERS. DO NOT CORRECT EDITORIAL OBSERVATIONS. "
    "DO NOT REGENERATE CONTENT. DO NOT CALL ANTHROPIC. DO NOT CALL OPENAI. "
    "DO NOT CALL TERRA. DO NOT GENERATE IMAGES. DO NOT GENERATE DOCX. "
    "DO NOT GENERATE PDF. DO NOT LAUNCH A FINAL PUBLICATION."
)

assert AUTHORIZED_ANTHROPIC_CALLS == 0
assert AUTHORIZED_OPENAI_CALLS == 0
assert AUTHORIZED_TERRA_CALLS == 0
assert FINAL_PUBLICATION_AUTHORIZED is False
assert DOCX_GENERATION_AUTHORIZED is False
assert PDF_GENERATION_AUTHORIZED is False
assert VISUAL_DIRECTION_AUTHORIZED is False
assert SEMANTIC_CERTIFICATION_PERFORMED is False
assert CANONICAL_PYTHON.endswith("python.exe")
assert CONSUMED_4B228_SCOPE.startswith("BOOK_FULL_MANUSCRIPT_EDITORIAL_REVIEW_4B228_")
assert CH012_ACCEPTED_JSON_REL.endswith("chapter_candidate_authorial_v2.json")
assert "book_generation_4b217_ch012" in CH012_ORIGINAL_JSON_REL

__all__ = [
    "ACCEPTED_CHAPTER_IDS",
    "AUTHORIZATION_SCOPE",
    "BOOK_STATUS",
    "BOOK_TITLE",
    "BOOK_VERSION",
    "CANONICAL_CHAPTER_IDS",
    "EXPECTED_IDEA_COUNT",
    "EXPECTED_MANUSCRIPT_SHA256",
    "EXPECTED_SECTION_COUNT",
    "PENDING_CHAPTER_IDS",
    "PHASE",
    "PROJECT_NAME",
    "REPORT_NAME",
]
