"""Constantes 3B.7.7A.26 — local-lite. 0 provider. 0 fenêtre réelle."""

from __future__ import annotations

from app.source_analysis.models import IDEA_KINDS, IMPORTANCE_LEVELS
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
    SEMANTIC_TRANSPORT_VERSION_V3,
    SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE,
    WINDOW_ANALYSIS_PROMPT_VERSION_V13,
    WINDOW_ANALYSIS_PROMPT_VERSION_V131,
    WINDOW_ANALYSIS_PROMPT_VERSION_V132,
    WINDOW_ANALYSIS_PROMPT_VERSION_V140,
)
from app.source_analysis_local_v3.schema import semantic_transport_v3_fingerprint
from app.source_analysis_v3_a19_forensics.constants import (
    A19_STATUS_UNCHANGED,
    EXAMPLE_POLICY,
)
from app.source_analysis_v3_a22_forensics.constants import A22_STATUS_UNCHANGED
from app.source_analysis_v3_a25_forensics.constants import (
    A21_STATUS,
    A23_STATUS,
    A24_STATUS_UNCHANGED,
    SELECTED_ARCHITECTURE as A25_SELECTED,
)
from app.source_analysis_v3_hardened_win001.constants import (
    EXPECTED_ANALYSIS_SIGNATURE as A21_SIGNATURE,
)
from app.source_analysis_v3_a22_forensics.constants import A22_SIGNATURE
from app.source_analysis_v3_hardened_win004.constants import (
    EXPECTED_ANALYSIS_SIGNATURE as A24_SIGNATURE,
)
from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    A17_SCHEMA_FINGERPRINT,
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.26"
MODE = "IMPLEMENT_GLOBALIZED_IDEA_SUBTYPE_LOCAL_LITE"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
FUTURE_REAL_CALL_AUTHORIZED = False
WIN004_RETRY_AUTHORIZED = False

A19_STATUS = A19_STATUS_UNCHANGED
A21_STATUS_UNCHANGED = A21_STATUS
A22_STATUS = A22_STATUS_UNCHANGED
A23_STATUS_UNCHANGED = A23_STATUS
A24_STATUS = A24_STATUS_UNCHANGED
A25_STATUS = "PARTIAL"

SELECTED_ARCHITECTURE = A25_SELECTED
PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V140
TRANSPORT_VERSION = SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE
LOCAL_IDEA_SUBTYPE = "REMOVED"
LOCAL_IDEA_METADATA = "m=[importance]"
CANONICAL_IDEA_SUBTYPE = "OPTIONAL_ABSENT"
GLOBAL_IDEA_SUBTYPE_STRATEGY = "A_ABSENT_IF_OPTIONAL"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION
READY_WINDOWS = "1 / 7"
PHASE_3B_STATUS = "INCOMPLETE"
NEXT_ACTION = "HUMAN REVIEW"
NEXT_PHASE = "3B.7.7A.27_REAL_WIN004_LOCAL_LITE_CANARY"
NEXT_PHASE_LABEL = (
    "3B.7.7A.27 — REAL WIN004 LOCAL-LITE CANARY "
    "(ONE Anthropic call maximum; no grammar canary if A.18-identical; do not execute)"
)

IMPORTANCE_VOCABULARY = IMPORTANCE_LEVELS
IDEA_KIND_VOCABULARY = IDEA_KINDS
THINKING = "disabled"
MAX_OUTPUT = MAX_OUTPUT_TOKENS_FROZEN
DERIVED_LABEL = "DERIVED_COMPATIBILITY_LOCAL_LITE"

CONTRACT_ARTIFACT = "source_analysis_v31_local_lite_contract.json"
CANONICAL_ARTIFACT = "source_analysis_idea_subtype_canonical_mapping.json"
DOWNSTREAM_ARTIFACT = "source_analysis_idea_subtype_downstream_impact.json"
SCHEMA_ARTIFACT = "source_analysis_v31_local_lite_schema_identity.json"
FAKEAI_ARTIFACT = "source_analysis_v31_local_lite_fakeai_validation.json"
COMPAT_ARTIFACT = "source_analysis_v3_v31_candidate_compatibility.json"
FUTURE_ARTIFACT = "source_analysis_v31_future_win004_readiness.json"
REPORT_NAME = "PHASE_3B77A26_IMPLEMENT_GLOBALIZED_IDEA_SUBTYPE_LOCAL_LITE_REPORT.md"

assert SELECTED_ARCHITECTURE == "GLOBALIZE_IDEA_SUBTYPE"
assert PROMPT_VERSION == "window-analysis-1.4.0"
assert TRANSPORT_VERSION == "semantic-transport-v3.1-local-lite"
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert A19_STATUS == "FAIL"
assert A21_STATUS_UNCHANGED == "PASS"
assert A22_STATUS == "FAIL"
assert A23_STATUS_UNCHANGED == "PASS"
assert A24_STATUS == "FAIL"
assert A25_STATUS == "PARTIAL"
assert FUTURE_REAL_CALL_AUTHORIZED is False
assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert A17_SCHEMA_FINGERPRINT == semantic_transport_v3_fingerprint()

__all__ = [
    "A17_SCHEMA_FINGERPRINT",
    "A19_STATUS",
    "A21_SIGNATURE",
    "A21_STATUS_UNCHANGED",
    "A22_SIGNATURE",
    "A22_STATUS",
    "A23_STATUS_UNCHANGED",
    "A24_SIGNATURE",
    "A24_STATUS",
    "A25_STATUS",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER",
    "CANONICAL_ARTIFACT",
    "CANONICAL_IDEA_SUBTYPE",
    "COMPAT_ARTIFACT",
    "CONTRACT_ARTIFACT",
    "DERIVED_LABEL",
    "DOWNSTREAM_ARTIFACT",
    "EXAMPLE_POLICY",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "FAKEAI_ARTIFACT",
    "FUTURE_ARTIFACT",
    "FUTURE_REAL_CALL_AUTHORIZED",
    "GLOBAL_IDEA_SUBTYPE_STRATEGY",
    "IDEA_KIND_VOCABULARY",
    "IMPORTANCE_VOCABULARY",
    "LOCAL_IDEA_METADATA",
    "LOCAL_IDEA_SUBTYPE",
    "MAX_OUTPUT",
    "MODE",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "READY_WINDOWS",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "REPORT_NAME",
    "SCHEMA_ARTIFACT",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SEMANTIC_TRANSPORT_VERSION_V3",
    "THINKING",
    "TRANSPORT_VERSION",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V13",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V131",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V132",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V140",
    "WIN004_RETRY_AUTHORIZED",
]
