from pathlib import Path
from datetime import datetime


CHUNKS_DIR_NAME = "chunks"

_METADATA_PATTERNS = [
    "# Projet :",
    "# Chunk :",
    "# Généré le :",
    "Projet :",
    "Chunk :",
    "Généré le :",
]

# Patterns that indicate a chunk was generated by old code (contains metadata header)
_OLD_CODE_HEADER_PATTERNS = [
    "# Projet :",
    "# Chunk :",
    "# Généré le :",
]


def is_chunk_stale(chunk_path: Path) -> bool:
    """
    Returns True if the chunk file was generated by old code.

    Old code added metadata headers (# Projet :, # Chunk :, # Généré le :)
    and may have written only section titles without real transcript content.
    """
    if not chunk_path.exists():
        return True
    try:
        text = chunk_path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return True

    first_lines = text[:400]
    for pattern in _OLD_CODE_HEADER_PATTERNS:
        if pattern in first_lines:
            return True

    return False


def reset_stale_processed_files(
    project_name: str,
    chunk_names: list[str],
    output_dir: Path,
) -> list[str]:
    """
    Deletes processed/ and reviewed/ files for chunks that need reprocessing.

    Returns the list of chunk names that were reset.
    """
    processed_dir = output_dir / "processed"
    reviewed_dir = output_dir / "reviewed"
    reset: list[str] = []

    for chunk_name in chunk_names:
        md_name = chunk_name.replace(".txt", ".md")

        for d in (processed_dir, reviewed_dir):
            target = d / md_name
            if target.exists():
                try:
                    target.unlink()
                    print(
                        f"[chunk_service] Fichier obsolète supprimé : {target}"
                    )
                except Exception as exc:
                    print(
                        f"[chunk_service] Impossible de supprimer {target} : {exc}"
                    )

        reset.append(chunk_name)

    return reset


def split_text_into_chunks(
    text: str,
    max_chars: int = 8000
) -> list[str]:
    """
    Découpe un texte en chunks en respectant les frontières naturelles.

    Ordre de priorité pour les coupures :
        1. Séparateurs de section (lignes === ou ---)
        2. Timestamps (lignes de type [00:00:00])
        3. Paragraphes (double saut de ligne)
        4. Lignes simples (saut de ligne)

    Ne produit pas de chunks vides.
    """
    import re

    # Découpe prioritaire sur les séparateurs forts
    sections = re.split(r"\n(?:={3,}|-{3,})\n", text)

    raw_paragraphs: list[str] = []
    for section in sections:
        for para in re.split(r"\n\n+", section):
            para = para.strip()
            if para:
                raw_paragraphs.append(para)

    chunks: list[str] = []
    current_chunk = ""

    for paragraph in raw_paragraphs:
        if len(current_chunk) + len(paragraph) + 2 <= max_chars:
            current_chunk += paragraph + "\n\n"
        else:
            if current_chunk.strip():
                chunks.append(current_chunk.strip())

            # Si le paragraphe seul dépasse max_chars, le couper sur les lignes
            if len(paragraph) > max_chars:
                lines = paragraph.splitlines()
                sub_chunk = ""
                for line in lines:
                    if len(sub_chunk) + len(line) + 1 <= max_chars:
                        sub_chunk += line + "\n"
                    else:
                        if sub_chunk.strip():
                            chunks.append(sub_chunk.strip())
                        sub_chunk = line + "\n"
                if sub_chunk.strip():
                    current_chunk = sub_chunk
                else:
                    current_chunk = ""
            else:
                current_chunk = paragraph + "\n\n"

    if current_chunk.strip():
        chunks.append(current_chunk.strip())

    return chunks


def validate_chunk_content(chunk_text: str) -> dict:
    """
    Valide le contenu d'un chunk.

    Retourne :
    {
      "char_count": int,
      "word_count": int,
      "timestamp_count": int,
      "metadata_ratio": float,   # proportion de lignes purement metadata
      "is_valid": bool,
      "warnings": list[str]
    }
    """
    import re

    lines = chunk_text.splitlines()
    char_count = len(chunk_text)
    word_count = len(chunk_text.split())

    timestamp_count = sum(
        1 for line in lines
        if re.match(r"^\s*\[?\d{1,2}:\d{2}(:\d{2})?\]?", line.strip())
    )

    metadata_keywords = [
        "# Projet", "# Chunk", "# Généré",
        "Projet :", "Chunk :", "Généré le :",
        "Document final —", "Nombre de chunks",
        "Chunks avec corrections",
        "═══", "───",
        "PARTIE ",
    ]

    metadata_lines = sum(
        1 for line in lines
        if any(kw in line for kw in metadata_keywords)
        or (line.startswith("#") and "chunk_" in line.lower())
    )

    total_non_empty = max(1, sum(1 for l in lines if l.strip()))
    metadata_ratio = metadata_lines / total_non_empty

    warnings: list[str] = []
    is_valid = True

    if char_count < 50:
        warnings.append(f"Chunk très court ({char_count} caractères)")
        is_valid = False

    if word_count < 10:
        warnings.append(f"Chunk quasi-vide ({word_count} mots)")
        is_valid = False

    if metadata_ratio > 0.5:
        warnings.append(
            f"Chunk dominé par des métadonnées ({metadata_ratio:.0%} des lignes)"
        )

    return {
        "char_count": char_count,
        "word_count": word_count,
        "timestamp_count": timestamp_count,
        "metadata_ratio": round(metadata_ratio, 3),
        "is_valid": is_valid,
        "warnings": warnings,
    }


def create_project_chunks(
    project,
    max_chars: int = 8000
) -> list[Path]:
    merged_transcript_path = (
        project.merged_dir /
        "transcript_complet.txt"
    )

    if not merged_transcript_path.exists():
        raise FileNotFoundError(
            f"Transcript fusionné introuvable : {merged_transcript_path}"
        )

    chunks_dir = project.output_dir / CHUNKS_DIR_NAME
    chunks_dir.mkdir(parents=True, exist_ok=True)

    text = merged_transcript_path.read_text(encoding="utf-8")

    print(
        f"[chunk_service] transcript_complet.txt : "
        f"{len(text)} caractères, {len(text.split())} mots"
    )

    import re
    timestamp_count = len(re.findall(r"\[?\d{1,2}:\d{2}(:\d{2})?\]?", text))
    print(f"[chunk_service] Segments timestampés détectés : {timestamp_count}")

    chunks = split_text_into_chunks(
        text=text,
        max_chars=max_chars
    )

    print(f"[chunk_service] Nombre de chunks créés : {len(chunks)}")

    chunk_paths = []
    invalid_count = 0

    for index, chunk in enumerate(chunks, start=1):
        chunk_path = chunks_dir / f"chunk_{index:03}.txt"

        validation = validate_chunk_content(chunk)
        char_preview = chunk[:200].replace("\n", " ")

        print(
            f"[chunk_service] chunk_{index:03} : "
            f"{validation['char_count']} chars, "
            f"{validation['word_count']} mots, "
            f"ratio_meta={validation['metadata_ratio']:.2f}"
        )
        print(f"  Aperçu : {char_preview[:200]}")

        if not validation["is_valid"]:
            invalid_count += 1
            for w in validation["warnings"]:
                print(f"  [AVERTISSEMENT] {w}")

        if validation["metadata_ratio"] > 0.5:
            print(
                f"  [AVERTISSEMENT] chunk_{index:03} contient principalement "
                "des métadonnées ou séparateurs — contenu réel insuffisant."
            )

        # Écriture du chunk SANS header de métadonnées
        # Les métadonnées (projet, numéro, date) sont dans project_state.json
        chunk_path.write_text(chunk, encoding="utf-8")
        chunk_paths.append(chunk_path)

    if invalid_count:
        print(
            f"[chunk_service] {invalid_count}/{len(chunks)} chunk(s) "
            "invalides ou quasi-vides."
        )

    return chunk_paths
