"""Constantes 3B.7.7A.39 — forensics cap de sortie A.38 + architecture bornée."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis_v31_global_canary_forensics.constants import (
    A34_STATUS_PRESERVED,
    A35_STATUS_PRESERVED,
    NEXT_PROMPT_VERSION as V11_PROMPT_VERSION,
    NEXT_SCHEMA_ADAPTED_BYTES as V11_SCHEMA_ADAPTED_BYTES,
    NEXT_SCHEMA_HASH as V11_SCHEMA_HASH,
    NEXT_SCHEMA_RAW_BYTES as V11_SCHEMA_RAW_BYTES,
    NEXT_TRANSPORT_VERSION as V11_TRANSPORT_VERSION,
    OLD_PROMPT_VERSION as V10_PROMPT_VERSION,
    OLD_TRANSPORT_VERSION as V10_TRANSPORT_VERSION,
)
from app.source_analysis_v31_global_grammar_canary.constants import (
    FROZEN_GRANULARITY,
    FROZEN_PLANNER,
    FROZEN_PROMPT,
    FROZEN_SRC_POLICY,
    FROZEN_TRANSPORT,
    MODEL,
    PRODUCTION_ESTIMATED_COST_USD,
    PRODUCTION_LOCAL_ESTIMATE_TOKENS,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PRODUCTION_NORMALIZED_CHARS,
    PRODUCTION_OUTPUT_HEADROOM_TOKENS,
    PRODUCTION_PROVIDER_ADJUSTED_TOKENS,
    PRODUCTION_WORST_CASE_OUTPUT_TOKENS,
    PROJECT_NAME,
    PROVIDER,
    THINKING_CONTRACT,
    THINKING_MODE,
)
from app.source_analysis_v31_global_preflight.constants import (
    CONTEXT_WINDOW_TOKENS,
    IDEA_DISPOSITION_COVERAGE_REQUIRED,
    IDEA_KIND_POLICY,
    INPUT_COST_PER_1M,
    MODEL_MAX_OUTPUT_TOKENS,
    OUTPUT_COST_PER_1M,
    READY_COUNT,
    READY_LABEL,
    READY_WINDOWS,
    RELATION_QUALITY_TECHNICAL_DEBT,
)
from app.source_analysis_v31_global_real_consolidation.constants import (
    A36_STATUS_PRESERVED,
    A37_STATUS_PRESERVED,
    CANARY_SUBDIR as A38_CANARY_SUBDIR,
    EXPECTED_DISTINCT_SRC,
    EXPECTED_EXAMPLE,
    EXPECTED_IDEA,
    EXPECTED_REFERENCE,
    EXPECTED_RELATION,
    EXPECTED_SRC_OCCURRENCES,
    EXPECTED_TOPIC,
    EXPECTED_TOTAL_RECORDS,
    EXPECTED_UNCERTAINTY,
    REPORT_NAME as A38_REPORT_NAME,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.39"
MODE = "GLOBAL_CONSOLIDATION_OUTPUT_CAP_FORENSICS_AND_BOUNDED_OUTPUT_ARCHITECTURE"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
REAL_CONSOLIDATION_CALLS = 0
GRAMMAR_CANARY_CALLS = 0
CONSOLIDATION_AUTHORIZED = False
GRAMMAR_CANARY_AUTHORIZED = False
SOURCE_MAP_PUBLICATION_AUTHORIZED = False

A38_STATUS_PRESERVED = "FAIL"
assert A34_STATUS_PRESERVED == "PASS"
assert A35_STATUS_PRESERVED == "FAIL"
assert A36_STATUS_PRESERVED == "PASS"
assert A37_STATUS_PRESERVED == "PASS"
assert A38_STATUS_PRESERVED == "FAIL"

assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert THINKING_MODE == "disabled"
assert PRODUCTION_MAX_OUTPUT_TOKENS == 32000
assert MODEL_MAX_OUTPUT_TOKENS == 128_000
assert READY_WINDOWS == (
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
)
assert READY_COUNT == 7
assert READY_LABEL == "7 / 7"
assert EXPECTED_TOPIC == 67
assert EXPECTED_IDEA == 286
assert EXPECTED_RELATION == 127
assert EXPECTED_EXAMPLE == 49
assert EXPECTED_REFERENCE == 59
assert EXPECTED_UNCERTAINTY == 35
assert EXPECTED_TOTAL_RECORDS == 623
assert EXPECTED_SRC_OCCURRENCES == 2143
assert EXPECTED_DISTINCT_SRC == 1743
assert PRODUCTION_PROVIDER_ADJUSTED_TOKENS == 65755
assert PRODUCTION_WORST_CASE_OUTPUT_TOKENS == 24346
assert V11_PROMPT_VERSION == "global-consolidation-1.0.1"
assert V11_TRANSPORT_VERSION == "global-consolidation-transport-1.1"
assert V10_PROMPT_VERSION == "global-consolidation-1.0"
assert V10_TRANSPORT_VERSION == "global-consolidation-transport-1.0"
assert V11_SCHEMA_RAW_BYTES == 1182
assert V11_SCHEMA_ADAPTED_BYTES == 1337
assert IDEA_KIND_POLICY == "KEEP_EMPTY_GLOBALLY"
assert IDEA_DISPOSITION_COVERAGE_REQUIRED == 100
assert FROZEN_PLANNER == "window-planner-v2.1-small"
assert FROZEN_PROMPT == "window-analysis-1.4.0"
assert FROZEN_TRANSPORT == "semantic-transport-v3.1-local-lite"
assert FROZEN_GRANULARITY == "window-granularity-1.2-kind-specific"
assert FROZEN_SRC_POLICY == "src-reference-policy-1.1-narrow-canonicalization"

A38_REQUEST_ID = "req_011CfWwT6tCwU9aX9cZwvGAW"
A38_REQUEST_IDENTITY = (
    "3a1b703e2751e5c8e8823d337886f8bf60e3733130ddd238df19699fa05e8ad1"
)
A38_INPUT_HASH = "0277ec07d1122a60d191577eb7a5093ddeb2eb8008a7ccfae8309c973f8448f4"
A38_HTTP_STATUS = 200
A38_FINISH_REASON = "max_tokens"
A38_THINKING_TOKENS = 0
A38_INPUT_TOKENS = 68138
A38_OUTPUT_TOKENS = 32000
A38_MAX_OUTPUT = 32000
A38_COST_USD = 0.456276
A38_ELAPSED_SECONDS = 219.7
A38_ELAPSED_MS = 219657
A38_LOCAL_INPUT_ESTIMATE = 36954
A38_INPUT_RATIO = 1.8438599339719652
A38_RAW_TEXT_CHARS = 75150
A38_RAW_TEXT_SHA256 = (
    "320d230a5e20f203c03bee9e437d26b495d0daf8f69919c5c0509499f0e6bd02"
)
A38_UNTERMINATED_COLUMN = 74991
A38_ROOT_FAILURE = "OUTPUT_TOKEN_BUDGET_EXHAUSTED"
A38_CANDIDATE_CREATED = False
A38_SOURCE_MAP_PUBLISHED = False

A34_INPUT_PREDICTION = PRODUCTION_PROVIDER_ADJUSTED_TOKENS
A34_OUTPUT_PREDICTION = PRODUCTION_WORST_CASE_OUTPUT_TOKENS
A34_INPUT_ERROR_TOKENS = A38_INPUT_TOKENS - A34_INPUT_PREDICTION
A34_INPUT_ERROR_PERCENT = round(100.0 * A34_INPUT_ERROR_TOKENS / A34_INPUT_PREDICTION, 2)
A38_CHARS_PER_PROVIDER_OUTPUT_TOKEN = A38_RAW_TEXT_CHARS / A38_OUTPUT_TOKENS

HISTORICAL_PROMPT = V11_PROMPT_VERSION
HISTORICAL_TRANSPORT = V11_TRANSPORT_VERSION
NEXT_PROMPT_VERSION = "global-consolidation-2.0"
NEXT_TRANSPORT_VERSION = "global-consolidation-transport-2.0"

# Frozen after first offline measure of transport 2.0. Do not edit 1.1.
NEXT_SCHEMA_RAW_BYTES = 1588
NEXT_SCHEMA_ADAPTED_BYTES = 1836
NEXT_SCHEMA_HASH = (
    "90b99a38ac704d00e1304495da0c757118293e43493ddb7321b3ffb3256d8330"
)

DROP_REASONS_V20 = (
    "transport_artifact",
    "non_substantive_fragment",
)
RETIRED_DROP_REASONS_V20 = ("exact_duplicate",)
RETIRED_DISPOSITION_OPS_V20 = ("OTHER",)
DERIVED_DISPOSITION_OPS = ("KEEP", "MERGE_EQUIVALENT")

# A.39 compact-output budget bound copied into prompts 2.0 / 2.0.1 / 3.0 and
# reused as the A.46-era global validator hard gate. Not a semantic product
# requirement. Local window extraction already permits 280. Canonical
# SourceMap.author_intent.summary has no max. Anthropic Structured Outputs
# cannot enforce string maxLength — do not invent a fake schema bound.
A39_INTENT_COMPACTNESS_BOUND = 240
# A.47 selected / A.48 implemented semantic/product global intent bound.
# 320 is concise but large enough for a faithful one-sentence global intent
# (above local-window 280 and A.46's observed 290), still below theme 360.
GLOBAL_INTENT_MAX_CHARS = 320
assert A39_INTENT_COMPACTNESS_BOUND == 240
assert GLOBAL_INTENT_MAX_CHARS == 320
assert GLOBAL_INTENT_MAX_CHARS > 280
assert GLOBAL_INTENT_MAX_CHARS < 360

TEXT_LIMITS = {
    "theme": 360,
    "intent": GLOBAL_INTENT_MAX_CHARS,
    "audience": 160,
    "voice": 240,
    "topic": 100,
    "idea": 180,
}
assert TEXT_LIMITS["intent"] == GLOBAL_INTENT_MAX_CHARS
assert TEXT_LIMITS["intent"] != A39_INTENT_COMPACTNESS_BOUND

# Frozen A.39 compactness table for output-token fill / estimators only.
# Semantic validation uses TEXT_LIMITS (intent 320). Do not mix the two.
OUTPUT_BUDGET_TEXT_LIMITS = {
    **TEXT_LIMITS,
    "intent": A39_INTENT_COMPACTNESS_BOUND,
}
assert OUTPUT_BUDGET_TEXT_LIMITS["intent"] == 240
assert TEXT_LIMITS["intent"] == 320
MAX_MEMBERS_PER_IDEA = 16
MAX_MEMBERS_PER_TOPIC = 8
MAX_LOCAL_IDS_PER_SATELLITE = 4
MAX_EXAMPLE_IDEA_REFS = 4

SELECTED_ARCHITECTURE = "INVERSE_MEMBERSHIP_COMPACT_ONE_CALL"
SELECTED_OPTION = "B"
PROVIDER_EMITTED_DISPOSITION_LEDGER = False
INVERSE_IDEA_MEMBERSHIP = True
DERIVED_SRC_UNION = True
RELATION_POLICY = "RELATIONS_DEFERRED"
REPETITION_POLICY = "LATER_ENRICHMENT_OPTIONAL"
OTHER_DISPOSITION = "RETIRE"
EXACT_DUPLICATE_POLICY = "REPRESENT_AS_GLOBAL_MEMBERSHIP"
TRANSPORT_11_32000_FEASIBILITY = "NO"

NEXT_MAX_OUTPUT_TOKENS = 48000
SAFETY_RATIO = 0.75
SAFETY_TARGET_TOKENS = int(NEXT_MAX_OUTPUT_TOKENS * SAFETY_RATIO)
NEXT_MODEL = MODEL
NEXT_THINKING = THINKING_MODE

READINESS_DECISION = "READY_FOR_COMPACT_GLOBAL_GRAMMAR_CANARY"
READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY = "NO"
NEW_GRAMMAR_CANARY_REQUIRED = True
SCHEMA_CHANGED = True

LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN = "YES"
PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
NEXT_ACTION = "HUMAN REVIEW"

FORENSICS_ARTIFACT = "global_consolidation_a38_output_cap_forensics.json"
BREAKDOWN_ARTIFACT = "global_consolidation_a38_output_token_breakdown.json"
OPTIONS_ARTIFACT = "global_consolidation_output_architecture_options.json"
SELECTED_ARTIFACT = "global_consolidation_selected_output_architecture.json"
MEMBERSHIP_ARTIFACT = "global_consolidation_membership_contract.json"
RELATION_DECISION_ARTIFACT = "global_consolidation_relation_stage_decision.json"
BUDGET_ARTIFACT = "global_consolidation_next_output_budget.json"
STRESS_ARTIFACT = "global_consolidation_full_scale_synthetic_stress.json"
NEXT_SCHEMA_ARTIFACT = "global_consolidation_next_transport_schema.json"
READINESS_ARTIFACT = "global_consolidation_post_a39_readiness.json"
TEST_DELTA_ARTIFACT = "source_analysis_a39_test_delta.json"
BASELINE_ARTIFACT = "source_analysis_a39_test_baseline.json"
REPORT_NAME = (
    "PHASE_3B77A39_GLOBAL_CONSOLIDATION_OUTPUT_ARCHITECTURE_REDESIGN_REPORT.md"
)

A38_FORENSIC_RELATIVE = f"audit/canary/{A38_CANARY_SUBDIR}"
PROTECTED_HISTORICAL = (
    "audit/PHASE_3B77A34_GLOBAL_CONSOLIDATION_OFFLINE_PREFLIGHT_REPORT.md",
    "audit/PHASE_3B77A35_GLOBAL_CONSOLIDATION_TINY_GRAMMAR_CANARY_REPORT.md",
    "audit/PHASE_3B77A36_GLOBAL_CONSOLIDATION_CANARY_FORENSICS_REPORT.md",
    "audit/PHASE_3B77A37_GLOBAL_CONSOLIDATION_V11_TINY_GRAMMAR_CANARY_REPORT.md",
    f"audit/{A38_REPORT_NAME}",
    f"{A38_FORENSIC_RELATIVE}/global_consolidation_a38_execution.json",
    f"{A38_FORENSIC_RELATIVE}/global_consolidation_a38_request.json",
    f"{A38_FORENSIC_RELATIVE}/global_consolidation_a38_max_tokens_forensics.json",
    f"{A38_FORENSIC_RELATIVE}/provider_raw_content.txt",
    f"{A38_FORENSIC_RELATIVE}/provider_raw_response.bin",
)

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_output_architecture.py",
    "app/tests/test_source_analysis_v31_global_output_architecture_audit.py",
    "app/tests/test_source_analysis_v31_global_real_consolidation.py",
    "app/tests/test_source_analysis_v31_global_canary_forensics.py",
)

assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert REAL_WINDOW_CALLS == 0
assert REAL_CONSOLIDATION_CALLS == 0
assert GRAMMAR_CANARY_CALLS == 0
assert READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY == "NO"
assert RELATION_QUALITY_TECHNICAL_DEBT == "YES"
assert not source_map_path(PROJECT_NAME).is_file() or SOURCE_MAP_STATUS == "NOT PUBLISHED"

__all__ = [
    "A34_INPUT_ERROR_PERCENT",
    "A34_INPUT_ERROR_TOKENS",
    "A34_INPUT_PREDICTION",
    "A34_OUTPUT_PREDICTION",
    "A34_STATUS_PRESERVED",
    "A35_STATUS_PRESERVED",
    "A36_STATUS_PRESERVED",
    "A37_STATUS_PRESERVED",
    "A38_CANDIDATE_CREATED",
    "A38_CANARY_SUBDIR",
    "A38_CHARS_PER_PROVIDER_OUTPUT_TOKEN",
    "A38_COST_USD",
    "A38_ELAPSED_MS",
    "A38_ELAPSED_SECONDS",
    "A38_FINISH_REASON",
    "A38_FORENSIC_RELATIVE",
    "A38_HTTP_STATUS",
    "A38_INPUT_HASH",
    "A38_INPUT_RATIO",
    "A38_INPUT_TOKENS",
    "A38_LOCAL_INPUT_ESTIMATE",
    "A38_MAX_OUTPUT",
    "A38_OUTPUT_TOKENS",
    "A38_RAW_TEXT_CHARS",
    "A38_RAW_TEXT_SHA256",
    "A38_REPORT_NAME",
    "A38_REQUEST_ID",
    "A38_REQUEST_IDENTITY",
    "A38_ROOT_FAILURE",
    "A38_SOURCE_MAP_PUBLISHED",
    "A38_STATUS_PRESERVED",
    "A38_THINKING_TOKENS",
    "A38_UNTERMINATED_COLUMN",
    "BASELINE_ARTIFACT",
    "BREAKDOWN_ARTIFACT",
    "BUDGET_ARTIFACT",
    "CONSOLIDATION_AUTHORIZED",
    "CONTEXT_WINDOW_TOKENS",
    "DERIVED_DISPOSITION_OPS",
    "DERIVED_SRC_UNION",
    "DROP_REASONS_V20",
    "EXACT_DUPLICATE_POLICY",
    "EXPECTED_DISTINCT_SRC",
    "EXPECTED_EXAMPLE",
    "EXPECTED_IDEA",
    "EXPECTED_REFERENCE",
    "EXPECTED_RELATION",
    "EXPECTED_SRC_OCCURRENCES",
    "EXPECTED_TOPIC",
    "EXPECTED_TOTAL_RECORDS",
    "EXPECTED_UNCERTAINTY",
    "A39_INTENT_COMPACTNESS_BOUND",
    "FOCUSED_TEST_PATHS",
    "FORENSICS_ARTIFACT",
    "GLOBAL_INTENT_MAX_CHARS",
    "FROZEN_GRANULARITY",
    "FROZEN_PLANNER",
    "FROZEN_PROMPT",
    "FROZEN_SRC_POLICY",
    "FROZEN_TRANSPORT",
    "GRAMMAR_CANARY_AUTHORIZED",
    "GRAMMAR_CANARY_CALLS",
    "HISTORICAL_PROMPT",
    "HISTORICAL_TRANSPORT",
    "IDEA_DISPOSITION_COVERAGE_REQUIRED",
    "IDEA_KIND_POLICY",
    "INPUT_COST_PER_1M",
    "INVERSE_IDEA_MEMBERSHIP",
    "LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN",
    "MAX_EXAMPLE_IDEA_REFS",
    "MAX_LOCAL_IDS_PER_SATELLITE",
    "MAX_MEMBERS_PER_IDEA",
    "MAX_MEMBERS_PER_TOPIC",
    "MEMBERSHIP_ARTIFACT",
    "MODE",
    "MODEL",
    "MODEL_MAX_OUTPUT_TOKENS",
    "NEW_GRAMMAR_CANARY_REQUIRED",
    "NEXT_ACTION",
    "NEXT_MAX_OUTPUT_TOKENS",
    "NEXT_MODEL",
    "NEXT_PROMPT_VERSION",
    "NEXT_SCHEMA_ADAPTED_BYTES",
    "NEXT_SCHEMA_ARTIFACT",
    "NEXT_SCHEMA_HASH",
    "NEXT_SCHEMA_RAW_BYTES",
    "NEXT_THINKING",
    "NEXT_TRANSPORT_VERSION",
    "OPTIONS_ARTIFACT",
    "OTHER_DISPOSITION",
    "OUTPUT_BUDGET_TEXT_LIMITS",
    "OUTPUT_COST_PER_1M",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_ESTIMATED_COST_USD",
    "PRODUCTION_LOCAL_ESTIMATE_TOKENS",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PRODUCTION_NORMALIZED_CHARS",
    "PRODUCTION_OUTPUT_HEADROOM_TOKENS",
    "PRODUCTION_PROVIDER_ADJUSTED_TOKENS",
    "PRODUCTION_WORST_CASE_OUTPUT_TOKENS",
    "PROJECT_NAME",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "PROVIDER_EMITTED_DISPOSITION_LEDGER",
    "READINESS_ARTIFACT",
    "READINESS_DECISION",
    "READY_COUNT",
    "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY",
    "READY_LABEL",
    "READY_WINDOWS",
    "REAL_CONSOLIDATION_CALLS",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "RELATION_DECISION_ARTIFACT",
    "RELATION_POLICY",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPETITION_POLICY",
    "REPORT_NAME",
    "RETIRED_DISPOSITION_OPS_V20",
    "RETIRED_DROP_REASONS_V20",
    "SAFETY_RATIO",
    "SAFETY_TARGET_TOKENS",
    "SCHEMA_CHANGED",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SELECTED_ARTIFACT",
    "SELECTED_OPTION",
    "SOURCE_MAP_PUBLICATION_AUTHORIZED",
    "SOURCE_MAP_STATUS",
    "STRESS_ARTIFACT",
    "TEST_DELTA_ARTIFACT",
    "TEXT_LIMITS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "TRANSPORT_11_32000_FEASIBILITY",
    "V10_PROMPT_VERSION",
    "V10_TRANSPORT_VERSION",
    "V11_PROMPT_VERSION",
    "V11_SCHEMA_ADAPTED_BYTES",
    "V11_SCHEMA_HASH",
    "V11_SCHEMA_RAW_BYTES",
    "V11_TRANSPORT_VERSION",
]
