"""Rapport markdown 3B.7.7A.39."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any], *, tests: str) -> str:
    header = bundle.get("header") or {}
    prefix = header.get("raw_prefix") or {}
    complete = header.get("complete_11") or {}
    schema = header.get("schema") or {}
    estimate = header.get("next_estimate") or {}
    planning = estimate.get("provider_planning_tokens") or {}
    lines = [
        "# PHASE 3B.7.7A.39 — GLOBAL CONSOLIDATION OUTPUT ARCHITECTURE REDESIGN",
        "",
        "## Result",
        "",
        str(header.get("result")),
        "",
        "REAL PROVIDER CALLS =",
        "0",
        "",
        "A.38 STATUS =",
        "FAIL unchanged",
        "",
        "A.38 REQUEST =",
        str(header.get("a38_request")),
        "",
        "A.38 ROOT FAILURE =",
        "OUTPUT_TOKEN_BUDGET_EXHAUSTED",
        "",
        "A.38 INPUT =",
        "68138",
        "",
        "A.38 OUTPUT =",
        "32000 / 32000",
        "",
        "A.38 FINISH =",
        "max_tokens",
        "",
        "A.38 COST =",
        "0.456276 USD",
        "",
        "A.34 OUTPUT ESTIMATE =",
        "~24346",
        "",
        "A.34 OUTPUT ESTIMATE STATUS =",
        "UNDERESTIMATED",
        "",
        "RAW PREFIX TOPICS =",
        str(prefix.get("topics")),
        "",
        "RAW PREFIX IDEAS =",
        str(prefix.get("ideas")),
        "",
        "RAW PREFIX RELATIONS STARTED =",
        "NO",
        "",
        "RAW PREFIX DISPOSITIONS STARTED =",
        "NO",
        "",
        "TRANSPORT 1.1 32000 FEASIBILITY =",
        "NO",
        "",
        "MINIMUM COMPLETE 1.1 OUTPUT =",
        str(complete.get("low")),
        "",
        "EXPECTED COMPLETE 1.1 OUTPUT =",
        str(complete.get("expected")),
        "",
        "HIGH COMPLETE 1.1 OUTPUT =",
        str(complete.get("high")),
        "",
        "SELECTED ARCHITECTURE =",
        str(header.get("selected_architecture")),
        "",
        "PROVIDER-EMITTED DISPOSITION LEDGER =",
        "NO",
        "",
        "INVERSE IDEA MEMBERSHIP =",
        "YES",
        "",
        "DERIVED SRC UNION =",
        "YES",
        "",
        "RELATION POLICY =",
        "DEFERRED",
        "",
        "REPETITION POLICY =",
        "LATER_ENRICHMENT_OPTIONAL",
        "",
        "OTHER DISPOSITION =",
        "RETIRE",
        "",
        "EXACT_DUPLICATE POLICY =",
        "REPRESENT_AS_GLOBAL_MEMBERSHIP",
        "",
        "NEXT PROMPT =",
        "global-consolidation-2.0",
        "",
        "NEXT TRANSPORT =",
        "global-consolidation-transport-2.0",
        "",
        "NEXT SCHEMA RAW / ADAPTED =",
        f"{schema.get('raw_bytes')} / {schema.get('adapted_bytes')}",
        "",
        "NEXT SCHEMA HASH =",
        str(schema.get("hash")),
        "",
        "NEXT OUTPUT EXPECTED =",
        str(planning.get("expected")),
        "",
        "NEXT OUTPUT HARD/PLANNING BOUND =",
        str(planning.get("hard")),
        "",
        "NEXT OUTPUT SAFETY MARGIN =",
        str(estimate.get("margin_vs_safety")),
        "",
        "MODEL =",
        "claude-sonnet-5",
        "",
        "THINKING =",
        "disabled",
        "",
        "LOCAL EXTRACTION FUNCTIONALLY FROZEN =",
        "YES",
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        "YES",
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        str(header.get("new_failures")),
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "READINESS =",
        str(header.get("readiness")),
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## Notes",
        "",
        str(header.get("notes") or ""),
        "",
        "A.38 raw evidence was hashed and left unmodified.",
        "",
        "No provider call. No A.38 retry. No source_map publication.",
        "",
        "WAIT FOR HUMAN REVIEW.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
