"""
Phase 4B.2.21 — CH018 first real controlled generation with prompt 1.1.

NEW explicit one-shot authorization. One Anthropic claude-sonnet-5 call.
Chapter CH018 only. Cost cap 0.15 USD. Zero retries. Zero fallbacks.
Uses book-generator-faithful-restatement-1.1-candidate via the isolated
4B.2.20 selector. Does not activate prompt 1.1 globally.
Does not replace historical Book Generator prompts.
Does not publish book.json. Does not write the production cache.
Does not call Terra. Does not generate any other chapter.
Does not regenerate CH012. Does not modify the 4B.2.17 lock.
"""

from __future__ import annotations

from decimal import Decimal

from app.ai.thinking import THINKING_MODE_DISABLED
from app.book_authorial_voice_4b218.constants import (
    AUTHORIAL_VOICE_POLICY_VERSION,
    FAITHFUL_PROMPT_1_0_VERSION,
    FAITHFUL_PROMPT_1_1_VERSION,
    HISTORICAL_PROMPT_V10,
    HISTORICAL_PROMPT_V101,
)
from app.book_editorial_acceptance_4b219.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B219_SCOPE,
    EXPECTED_ACCEPTED_JSON_SHA256,
    EXPECTED_ACCEPTED_MD_SHA256,
    EXPECTED_LOCK_SHA256,
    EXPECTED_ORIGINAL_JSON_SHA256,
    EXPECTED_ORIGINAL_MD_SHA256,
)
from app.book_editorial_alignment_4b216.constants import (
    COVERAGE_CONTRACT_VERSION,
    EDITORIAL_POLICY_VERSION,
    HISTORICAL_SEMANTIC_CONTRACT,
)
from app.book_generation.constants import (
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION_V10,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    HARD_MAX_OUTPUT_TOKENS,
    MIN_MAX_OUTPUT_TOKENS,
    MODEL,
    PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_generation_4b217.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B217_SCOPE,
    HISTORICAL_CH012_CENTRAL_USD,
    SONNET_INPUT_COST_PER_1M,
    SONNET_OUTPUT_COST_PER_1M,
)
from app.book_authorial_voice_4b218.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B218_SCOPE,
)
from app.book_scale_up_preparation_4b220.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B220_SCOPE,
    EXPECTED_FIRST_CHAPTER_ID,
    EXPECTED_FIRST_CHAPTER_IDEA_COUNT,
    EXPECTED_FIRST_CHAPTER_SECTION_COUNT,
    EXPECTED_FIRST_CHAPTER_SECTIONS,
    EXPECTED_FIRST_CHAPTER_TITLE,
    EXPECTED_PROMPT_1_1_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_1_1_SHA256,
    EXPECTED_PROMPT_1_1_SYSTEM_SHA256,
    FAITHFUL_PROMPT_1_1,
)
from app.book_semantic_gate_4b215.constants import (
    HISTORICAL_4B210_STATUS,
    HISTORICAL_4B211_STATUS,
    HISTORICAL_4B212_STATUS,
    HISTORICAL_4B213_STATUS,
    HISTORICAL_4B214_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
)
from app.book_semantic_gate_4b23.constants import EXPECTED_CLEAN_TRANSCRIPT
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE

PHASE = "4B.2.21"
PHASE_NAME = "CH018_FIRST_REAL_CONTROLLED_GENERATION_WITH_FAITHFUL_PROMPT_1_1"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_GENERATION_LATER_PHASE_CH018_FIRST_REMAINING_CHAPTER_ONE_SHOT_ONLY"
)

AUTHORIZED_ANTHROPIC_CALLS = 1
AUTHORIZED_SONNET_CALLS = 1
AUTHORIZED_REMOTE_INVOCATIONS = 1
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_TERRA_CALLS = 0
MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_HTTP_REQUESTS = 1
MAX_EXECUTION_ATTEMPTS = 1
RETRIES = 0
FALLBACKS = 0
SDK_MAX_RETRIES = 0

PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
OPENAI_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = True
REAL_CHAPTER_GENERATION_AUTHORIZED = True
REAL_PROVIDERS_ENABLED = True
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
FAITHFUL_PROMPT_ACTIVATED_IN_PRODUCTION = False
FAITHFUL_PROMPT_1_1_ACTIVATED = False
EDITORIAL_POLICY_ACTIVATED_IN_PRODUCTION = False
COVERAGE_CONTROL_ACTIVATED_IN_PRODUCTION = False
SEMANTIC_GATE_202_ENABLED = False
SEMANTIC_CERTIFICATION_PERFORMED = False
BOOK_JSON_PUBLICATION = False

TARGET_CHAPTER_ID = "CH018"
TARGET_CHAPTER_TITLE = "Testimonies of Resurrection"
EXPECTED_SECTION_IDS = ("SEC067", "SEC068", "SEC069", "SEC070")
EXPECTED_IDEA_IDS = (
    "IDEA269",
    "IDEA270",
    "IDEA271",
    "IDEA272",
    "IDEA273",
    "IDEA274",
    "IDEA275",
    "IDEA276",
    "IDEA277",
    "IDEA278",
    "IDEA279",
)
EXPECTED_EXAMPLE_IDS = ("EX046", "EX047", "EX048")
EXPECTED_REFERENCE_IDS = ("REF041", "REF058")
EXPECTED_IDEA_COUNT = 11
EXPECTED_SECTION_COUNT = 4
EXPECTED_EXAMPLE_COUNT = 3
EXPECTED_REFERENCE_COUNT = 2
EXPECTED_HYDRATED_SRC_COUNT = 79
ACCEPTED_CHAPTER_ID = "CH012"

PROMPT_VERSION = FAITHFUL_PROMPT_1_1
TRANSPORT_VERSION = BOOK_GENERATION_TRANSPORT_VERSION
VALIDATOR_VERSION = BOOK_GENERATOR_VALIDATOR_VERSION
HISTORICAL_PROMPT = HISTORICAL_PROMPT_V101
HISTORICAL_PROMPT_V10_ID = HISTORICAL_PROMPT_V10
FAITHFUL_PROMPT_1_0 = FAITHFUL_PROMPT_1_0_VERSION
NARRATIVE_VOICE_CONTRACT = AUTHORIAL_VOICE_POLICY_VERSION

assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert PROMPT_VERSION == "book-generator-faithful-restatement-1.1-candidate"
assert PROMPT_VERSION == FAITHFUL_PROMPT_1_1_VERSION
assert FAITHFUL_PROMPT_1_0 == "book-generator-faithful-restatement-1.0-candidate"
assert HISTORICAL_PROMPT == BOOK_GENERATOR_PROMPT_VERSION == "book-generator-1.0.1"
assert HISTORICAL_PROMPT_V10_ID == BOOK_GENERATOR_PROMPT_VERSION_V10 == "book-generator-1.0"
assert TRANSPORT_VERSION == "book-generation-transport-1.0"
assert EDITORIAL_POLICY_VERSION == "faithful-teaching-book-editorial-policy-1.0-candidate"
assert COVERAGE_CONTRACT_VERSION == "source-coverage-control-4b216-candidate"
assert HISTORICAL_SEMANTIC_CONTRACT == "book-semantic-validator-2.0.2-candidate"
assert NARRATIVE_VOICE_CONTRACT == "authorial-voice-preservation-1.0-candidate"
assert TARGET_CHAPTER_ID == EXPECTED_FIRST_CHAPTER_ID
assert TARGET_CHAPTER_TITLE == EXPECTED_FIRST_CHAPTER_TITLE
assert EXPECTED_SECTION_IDS == EXPECTED_FIRST_CHAPTER_SECTIONS
assert EXPECTED_IDEA_COUNT == EXPECTED_FIRST_CHAPTER_IDEA_COUNT
assert EXPECTED_SECTION_COUNT == EXPECTED_FIRST_CHAPTER_SECTION_COUNT
assert CONSUMED_4B217_SCOPE == (
    "BOOK_GENERATION_4B217_CH012_FAITHFUL_REAL_PILOT_GENERATION_ONLY"
)
assert CONSUMED_4B218_SCOPE.startswith("BOOK_AUTHORIAL_VOICE_4B218_")
assert CONSUMED_4B219_SCOPE.startswith("BOOK_EDITORIAL_ACCEPTANCE_4B219_")
assert CONSUMED_4B220_SCOPE.startswith("BOOK_SCALE_UP_PREPARATION_4B220_")

THINKING_MODE = THINKING_MODE_DISABLED
assert THINKING_MODE == "disabled"

BUDGET_CAP_USD = Decimal("0.15")
BUDGET_CAP_DISPLAY = "0.15 USD"
MAX_REAL_CALL_COST_USD = BUDGET_CAP_USD
PRICING_EFFECTIVE_DATE = "2026-09-18"
PESSIMISTIC_CHARS_PER_TOKEN = Decimal("1.9365384615384615")
PHASE_4B220_EXPECTED_USD = Decimal("0.048528")
PHASE_4B220_MAX_USD = Decimal("0.113538")

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 1800.0

STAGE_CANARY = "book_generation_4b221_ch018"
CANARY_WINDOW_ID = "CANARY_BG4B221"
LOCK_NAME = "call_lock.json"
CODE_VERSION = "app.book_generation_4b221"

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_TRANSCRIPT = EXPECTED_CLEAN_TRANSCRIPT

assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert EXPECTED_ACCEPTED_MD_SHA256 == (
    "79d0ab2254e1a972e0fb5ddcbb7901425255ce887ee817fc39b001838b889919"
)
assert EXPECTED_ACCEPTED_JSON_SHA256 == (
    "8f135ac5f1df8b2e077e9cc767518d1a05e2fc22d80f5d66494cf5a8364e7fc5"
)
assert AUTHORIZED_ANTHROPIC_CALLS == 1
assert AUTHORIZED_OPENAI_CALLS == 0
assert AUTHORIZED_TERRA_CALLS == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert PUBLICATION_AUTHORIZED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert FAITHFUL_PROMPT_1_1_ACTIVATED is False
assert TARGET_CHAPTER_ID == "CH018"
assert ACCEPTED_CHAPTER_ID == "CH012"
assert BUDGET_CAP_USD == Decimal("0.15")
assert MIN_MAX_OUTPUT_TOKENS == 4096
assert HARD_MAX_OUTPUT_TOKENS == 32000
assert CANONICAL_PYTHON.endswith("python.exe")
assert SONNET_INPUT_COST_PER_1M == Decimal("2.00")
assert SONNET_OUTPUT_COST_PER_1M == Decimal("10.00")

HISTORICAL_4B215_STATUS = "PARTIAL"
HISTORICAL_4B216_STATUS = "PASS"
HISTORICAL_4B217_STATUS = "PARTIAL"
HISTORICAL_4B218_STATUS = "PASS"
HISTORICAL_4B219_STATUS = "PASS"
HISTORICAL_4B220_STATUS = "PASS"
HISTORICAL_4B221_DOES_NOT_REQUALIFY = True

LOCK_STATE_PREPARATION = "PREPARATION_NO_CALL"
LOCK_STATE_RESERVED = "CALL_RESERVED"
LOCK_STATE_POSSIBLY_SENT = "CALL_POSSIBLY_SENT"
LOCK_STATE_RESPONSE_RECEIVED = "RESPONSE_RECEIVED"
LOCK_STATE_RESPONSE_VALIDATED = "RESPONSE_VALIDATED"
LOCK_STATE_FAILED = "FAILED"
LOCK_STATE_UNCERTAIN = "UNCERTAIN"

LOCK_CONSUMED_STATES = frozenset(
    {
        LOCK_STATE_RESERVED,
        LOCK_STATE_POSSIBLY_SENT,
        LOCK_STATE_RESPONSE_RECEIVED,
        LOCK_STATE_RESPONSE_VALIDATED,
        LOCK_STATE_FAILED,
        LOCK_STATE_UNCERTAIN,
    }
)

REVIEW_NO_ISSUE = "NO_ISSUE_DETECTED"
REVIEW_RECOMMENDED = "REVIEW_RECOMMENDED"
REVIEW_POTENTIAL = "POTENTIAL_SUBSTANTIVE_ISSUE"
REVIEW_UNDETERMINED = "UNDETERMINED"

FORBIDDEN_PROMPT_CLAUSES = (
    "High stylistic freedom",
    "Stylistic expansion is allowed",
)
FORBIDDEN_PROMPTS = (
    "book-generator-1.0",
    "book-generator-1.0.1",
    "book-generator-faithful-restatement-1.0-candidate",
)

AUDIT_DIRNAME = "book_generation_4b221_ch018"
AUDIT_REAL_PARENT = "real"
AUDIT_PREFLIGHT = "preflight.json"
AUDIT_HASHES_PRE = "canonical_hashes_pre.json"
AUDIT_AUTHORIZATION = "authorization_scope.json"
AUDIT_LOCK = LOCK_NAME
AUDIT_PROMPT = "prompt_manifest.json"
AUDIT_CONTEXT = "source_context_manifest.json"
AUDIT_COST = "cost_preflight.json"
AUDIT_RESPONSE_RAW = "provider_response_raw.json"
AUDIT_USAGE = "provider_usage.json"
AUDIT_CANDIDATE_JSON = "chapter_candidate.json"
AUDIT_CANDIDATE_MD = "chapter_candidate.md"
AUDIT_STRUCTURAL = "structural_validation.json"
AUDIT_IDEA = "idea_traceability_review.json"
AUDIT_EDITORIAL = "editorial_readiness_review.json"
AUDIT_HASHES_POST = "canonical_hashes_post.json"
AUDIT_READINESS = "readiness.json"
AUDIT_TESTS = "regression_tests.json"
REPORT_NAME = "PHASE_4B221_CH018_FIRST_REAL_CONTROLLED_GENERATION_REPORT.md"

NEXT_ACTION = (
    "HUMAN EDITORIAL REVIEW OF CH018. DO NOT GENERATE THE NEXT CHAPTER. "
    "DO NOT RETRY THE PROVIDER."
)
READY_FOR_NEXT_CHAPTER = False

__all__ = [
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "BUDGET_CAP_USD",
    "CANONICAL_PYTHON",
    "EXPECTED_ACCEPTED_JSON_SHA256",
    "EXPECTED_ACCEPTED_MD_SHA256",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_HYDRATED_SRC_COUNT",
    "EXPECTED_IDEA_COUNT",
    "EXPECTED_IDEA_IDS",
    "EXPECTED_LOCK_SHA256",
    "EXPECTED_ORIGINAL_JSON_SHA256",
    "EXPECTED_ORIGINAL_MD_SHA256",
    "EXPECTED_PROMPT_1_1_SHA256",
    "EXPECTED_PROMPT_1_1_SYSTEM_SHA256",
    "EXPECTED_PROMPT_1_1_INSTRUCTIONS_SHA256",
    "EXPECTED_SECTION_IDS",
    "EXPECTED_SOURCE_MAP",
    "EXPECTED_TRANSCRIPT",
    "HISTORICAL_CH012_CENTRAL_USD",
    "LOCK_CONSUMED_STATES",
    "LOCK_NAME",
    "MODEL",
    "PHASE",
    "PROMPT_VERSION",
    "PROVIDER",
    "SONNET_INPUT_COST_PER_1M",
    "SONNET_OUTPUT_COST_PER_1M",
    "TARGET_CHAPTER_ID",
]
