"""
Phase 4B.2.7.1 — H01 semantic disagreement forensics and compact gate calibration.

Offline only. Zero provider calls. Historical 4B.2.7 remains PARTIAL.
Human labels and frozen contracts 1.0 / 1.1-candidate are not modified.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
)
from app.book_semantic_gate_4b24.constants import (
    CONNECTIVE_CASE_ID,
    EXPECTED_PROMPT_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_SYSTEM_SHA256,
    EXPECTED_SCHEMA_SHA256,
    FUNERAL_CASE_ID,
    NEGATIVE_CASE_IDS,
    P3_CASE_ID,
    P8_CASE_ID,
    POSITIVE_CASE_IDS,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE
from app.book_semantic_gate_4b261.constants import (
    CANDIDATE_PROMPT_VERSION,
    CANDIDATE_TRANSPORT_VERSION,
)
from app.book_semantic_gate_4b27.constants import (
    EXPECTED_EVIDENCE_HANDLES,
    EXPECTED_REQUEST_SHA256,
    HISTORICAL_4B241_STATUS,
    HISTORICAL_4B24_STATUS,
    HISTORICAL_4B251_STATUS,
    HISTORICAL_4B25_STATUS,
    HISTORICAL_4B261_STATUS,
    HISTORICAL_4B262_STATUS,
    HISTORICAL_4B26_STATUS,
    SELECTED_CASE_HANDLE,
    SELECTED_CASE_HUMAN_LABEL,
    SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY,
    SELECTED_CASE_ID,
    SELECTED_CASE_ROLE,
)

PHASE = "4B.2.7.1"
PHASE_NAME = "H01_SEMANTIC_DISAGREEMENT_FORENSICS_AND_COMPACT_GATE_CALIBRATION"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B271_H01_SEMANTIC_DISAGREEMENT_AND_CALIBRATION_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False

PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
PROMPT_VERSION_11 = CANDIDATE_PROMPT_VERSION
TRANSPORT_VERSION_11 = CANDIDATE_TRANSPORT_VERSION
PROMPT_VERSION_111 = "book-semantic-validator-1.1.1-candidate"
TRANSPORT_VERSION_111 = None

HISTORICAL_4B27_STATUS = "PARTIAL"
DISPUTED_CLAUSE = "that fear can calculate or bargain with"
DISPUTED_CLAIM_INDEX = 2
SEMANTIC_FINDING = "FALSE_REJECTION_SUPPORTED_BY_EVIDENCE"
SEMANTIC_FINDING_CODE = "A"

EXPECTED_PROMPT_11_SYSTEM_SHA256 = (
    "9380de399875ca7b803c1b6443d9ac53e261a39c43f357a062218771ca168f51"
)
EXPECTED_PROMPT_11_INSTRUCTIONS_SHA256 = (
    "0152479843d97327b7010ccde342e3b3c6dbc0e6c23076c748895e484c9b2e4b"
)
EXPECTED_PROMPT_11_SHA256 = (
    "3e7150651caa14f8578a346cadefa4b657829363b79f255ef919fc72c6a35908"
)
EXPECTED_SCHEMA_11_SHA256 = (
    "91922f85b033a533fba4e112ce7568d6c84dbd106e114a2612d0606a3cc1619a"
)

H01_TERRA_GAPS = ((140, 141), (209, 210))
OVERFIT_TOKENS = ("bargaining", "bargain with", "h01", "IDEA224", "4b22_p2")

assert PROMPT_VERSION_HISTORICAL == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION_HISTORICAL == "book-semantic-validation-transport-1.0"
assert PROMPT_VERSION_11 == "book-semantic-validator-1.1-candidate"
assert TRANSPORT_VERSION_11 == "book-semantic-validation-transport-1.1-candidate"
assert PROMPT_VERSION_111 != PROMPT_VERSION_11
assert PROMPT_VERSION_111 != PROMPT_VERSION_HISTORICAL
assert TRANSPORT_VERSION_111 is None
assert SELECTED_CASE_HANDLE == "h01"
assert SELECTED_CASE_ID == "4b22_p2_supported"
assert SELECTED_CASE_ROLE == "positive"
assert SELECTED_CASE_HUMAN_LABEL == CLASS_SUPPORTED
assert SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY is True
assert EXPECTED_REQUEST_SHA256 == (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B24_STATUS == "FAIL"
assert HISTORICAL_4B241_STATUS == "PASS"
assert HISTORICAL_4B25_STATUS == "FAIL"
assert HISTORICAL_4B251_STATUS == "PASS"
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert HISTORICAL_4B262_STATUS == "PASS"
assert HISTORICAL_4B27_STATUS == "PARTIAL"
assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False

AUDIT_DIRNAME = "book_semantic_gate_4b271"
AUDIT_INVENTORY = "h01_canonical_evidence_inventory.json"
AUDIT_CLAUSE = "h01_disputed_clause_analysis.json"
AUDIT_HUMAN = "h01_human_label_review.json"
AUDIT_SRC180 = "h01_src006180_evidence_review.json"
AUDIT_TERRA = "h01_terra_response_forensics.json"
AUDIT_MATRIX = "semantic_paraphrase_boundary_matrix.json"
AUDIT_SPANS = "h01_span_separator_analysis.json"
AUDIT_CALIBRATION = "compact_gate_calibration_candidate.json"
AUDIT_COMPARISON = "compact_gate_contract_comparison.json"
AUDIT_TESTS = "compact_gate_4b271_offline_tests.json"
AUDIT_READINESS = "compact_gate_4b271_readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b271_index.json"
REPORT_NAME = "PHASE_4B271_H01_SEMANTIC_DISAGREEMENT_AND_CALIBRATION_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "AUDIT_CALIBRATION",
    "AUDIT_CLAUSE",
    "AUDIT_COMPARISON",
    "AUDIT_DIRNAME",
    "AUDIT_HUMAN",
    "AUDIT_INDEX",
    "AUDIT_INVENTORY",
    "AUDIT_MATRIX",
    "AUDIT_READINESS",
    "AUDIT_SPANS",
    "AUDIT_SRC180",
    "AUDIT_TERRA",
    "AUDIT_TESTS",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CANDIDATE_PROMPT_VERSION",
    "CANDIDATE_TRANSPORT_VERSION",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CONNECTIVE_CASE_ID",
    "DISPUTED_CLAIM_INDEX",
    "DISPUTED_CLAUSE",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_EVIDENCE_HANDLES",
    "EXPECTED_PROMPT_11_INSTRUCTIONS_SHA256",
    "EXPECTED_PROMPT_11_SHA256",
    "EXPECTED_PROMPT_11_SYSTEM_SHA256",
    "EXPECTED_PROMPT_INSTRUCTIONS_SHA256",
    "EXPECTED_PROMPT_SYSTEM_SHA256",
    "EXPECTED_REQUEST_SHA256",
    "EXPECTED_SCHEMA_11_SHA256",
    "EXPECTED_SCHEMA_SHA256",
    "EXPECTED_SOURCE_MAP",
    "FUNERAL_CASE_ID",
    "H01_TERRA_GAPS",
    "HISTORICAL_4B241_STATUS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B251_STATUS",
    "HISTORICAL_4B25_STATUS",
    "HISTORICAL_4B261_STATUS",
    "HISTORICAL_4B262_STATUS",
    "HISTORICAL_4B26_STATUS",
    "HISTORICAL_4B27_STATUS",
    "NEGATIVE_CASE_IDS",
    "NEXT_ACTION",
    "OVERFIT_TOKENS",
    "P3_CASE_ID",
    "P8_CASE_ID",
    "PHASE",
    "PHASE_NAME",
    "POSITIVE_CASE_IDS",
    "PROJECT_NAME",
    "PROMPT_VERSION_11",
    "PROMPT_VERSION_111",
    "PROMPT_VERSION_HISTORICAL",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "READY_FOR_NEW_REMOTE_TERRA_CALL",
    "REPORT_NAME",
    "SCORED_CASE_ORDER",
    "SELECTED_CASE_HANDLE",
    "SELECTED_CASE_HUMAN_LABEL",
    "SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY",
    "SELECTED_CASE_ID",
    "SELECTED_CASE_ROLE",
    "SEMANTIC_FINDING",
    "SEMANTIC_FINDING_CODE",
    "TERRA_EXECUTION_AUTHORIZED",
    "TRANSPORT_VERSION_11",
    "TRANSPORT_VERSION_111",
    "TRANSPORT_VERSION_HISTORICAL",
]
