"""Generate the print-review DOCX from book.json. No invented editorial matter."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from app.book_print_review_render_4b231.constants import (
    BOOK_STATUS,
    BOOK_VERSION,
    PHASE,
    PRINT_PROFILE,
    PUBLICATION_STATUS,
)
from app.book_print_review_render_4b231.hashes import file_sha256
from app.word_renderer.document import build_print_document, serialize_in_memory
from app.word_renderer.mapping import PrintBook


def build_docx_bytes(book: PrintBook, profile: dict[str, Any]) -> bytes:
    doc = build_print_document(book, profile)
    doc.core_properties.title = book.title
    doc.core_properties.author = ""
    doc.core_properties.subject = f"Print review draft — {BOOK_VERSION}"
    doc.core_properties.category = PUBLICATION_STATUS
    doc.core_properties.comments = (
        f"{BOOK_STATUS}. Not for publication. Generated by {PHASE}."
    )
    return serialize_in_memory(doc)


def write_docx_bytes(path: Path, data: bytes) -> dict[str, Any]:
    from app.book_print_review_render_4b231.writer import write_binary_atomic

    target = write_binary_atomic(path, data)
    hashed = file_sha256(target)
    return {
        "path": hashed.get("path"),
        "sha256": hashed.get("sha256"),
        "bytes": hashed.get("bytes"),
        "exists": hashed.get("exists"),
    }


def generation_manifest(
    *,
    book: PrintBook,
    profile: dict[str, Any],
    unfinalized: dict[str, Any],
    book_sha256: str,
) -> dict[str, Any]:
    return {
        "phase": PHASE,
        "engine": "app.word_renderer.document.build_print_document",
        "profile_id": profile.get("profile_id") or PRINT_PROFILE,
        "book_title": book.title,
        "book_version": book.version,
        "book_status": book.status,
        "book_sha256": book_sha256,
        "chapter_count": book.chapter_count,
        "section_count": book.section_count,
        "paragraph_count": len(book.paragraph_texts),
        "unfinalized_docx": unfinalized,
        "invented_front_matter": False,
        "provider_calls": 0,
        "verification": "automatic",
        "secrets_included": False,
    }


__all__ = ["build_docx_bytes", "generation_manifest", "write_docx_bytes"]
