"""4B.2.4 human-readable report."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None or value == "":
        return "—"
    return str(value)


def render_report(bundle: Mapping[str, Any]) -> str:
    header = dict(bundle.get("header") or {})
    attempt2_calls = header.get("actual_terra_calls")
    lines = [
        "# PHASE 4B.2.4 — ONE REAL TERRA SEMANTIC-GATE BENCHMARK CANARY",
        "",
        "## Attempts",
        "",
        "ATTEMPT 1 =",
        "BLOCKED_PRECALL",
        "OPENAI_API_KEY missing",
        "provider calls 0",
        "",
        "ATTEMPT 2 =",
        "credential available",
        "exact frozen request reconstructed",
        f"provider call {_dash(attempt2_calls)}",
        _dash(header.get("result")),
        "",
        "## Result",
        "",
        _dash(header.get("result")),
        "",
        "AUTHORIZED TERRA CALLS =",
        "1",
        "",
        "ACTUAL TERRA CALLS =",
        _dash(header.get("actual_terra_calls")),
        "",
        "SONNET CALLS =",
        "0",
        "",
        "RETRIES =",
        "0",
        "",
        "FALLBACKS =",
        "0",
        "",
        "4B.2 =",
        "FAIL",
        "",
        "4B.2.2 =",
        "PARTIAL",
        "",
        "4B.2.3 =",
        "PASS",
        "",
        "SOURCE MAP SHA256 PRE / POST =",
        f"{_dash(header.get('source_map_sha256_pre'))} / {_dash(header.get('source_map_sha256_post'))}",
        "",
        "EDITORIAL PLAN SHA256 PRE / POST =",
        f"{_dash(header.get('editorial_plan_sha256_pre'))} / {_dash(header.get('editorial_plan_sha256_post'))}",
        "",
        "CLEAN TRANSCRIPT SHA256 PRE / POST =",
        f"{_dash(header.get('clean_transcript_sha256_pre'))} / {_dash(header.get('clean_transcript_sha256_post'))}",
        "",
        "BENCHMARK SHA256 =",
        _dash(header.get("benchmark_sha256")),
        "",
        "BENCHMARK CASES =",
        "10",
        "",
        "SUPPORTED POSITIVES =",
        "6",
        "",
        "SEMANTIC NEGATIVES =",
        "4",
        "",
        "LABEL LEAKAGE =",
        _dash(header.get("label_leakage")),
        "",
        "MODEL =",
        "OpenAI / gpt-5.6-terra",
        "",
        "PROMPT =",
        "book-semantic-validator-1.0",
        "",
        "TRANSPORT =",
        "book-semantic-validation-transport-1.0",
        "",
        "OUTPUT MODE =",
        "json_object",
        "",
        "THINKING =",
        "provider_default",
        "",
        "TEMPERATURE =",
        "omitted",
        "",
        "REQUEST SHA256 =",
        _dash(header.get("request_sha256")),
        "",
        "REQUEST DETERMINISM =",
        _dash(header.get("request_determinism")),
        "",
        "CONTEXT ESTIMATE =",
        _dash(header.get("context_estimate")),
        "",
        "LONG-CONTEXT REGIME =",
        _dash(header.get("long_context_regime")),
        "",
        "ESTIMATED COST =",
        _dash(header.get("estimated_cost")),
        "",
        "HTTP / FINISH =",
        _dash(header.get("http_finish")),
        "",
        "REQUEST ID =",
        _dash(header.get("request_id")),
        "",
        "INPUT TOKENS =",
        _dash(header.get("input_tokens")),
        "",
        "OUTPUT TOKENS =",
        _dash(header.get("output_tokens")),
        "",
        "THINKING / REASONING TOKENS =",
        _dash(header.get("thinking_tokens")),
        "",
        "ACTUAL COST =",
        _dash(header.get("actual_cost")),
        "",
        "JSON PARSE =",
        _dash(header.get("json_parse")),
        "",
        "TRANSPORT DECODE =",
        _dash(header.get("transport_decode")),
        "",
        "CASE COVERAGE =",
        _dash(header.get("case_coverage")),
        "",
        "UNKNOWN CASES =",
        _dash(header.get("unknown_cases")),
        "",
        "DUPLICATE RESULTS =",
        _dash(header.get("duplicate_results")),
        "",
        "SPAN VALIDATION =",
        _dash(header.get("span_validation")),
        "",
        "POSITIVE ACCEPTED =",
        _dash(header.get("positive_accepted")),
        "",
        "POSITIVE FALSE REJECTIONS =",
        _dash(header.get("positive_false_rejections")),
        "",
        "NEGATIVE BLOCKED =",
        _dash(header.get("negative_blocked")),
        "",
        "NEGATIVE FALSE NEGATIVES =",
        _dash(header.get("negative_false_negatives")),
        "",
        "VERDICT ACCURACY =",
        _dash(header.get("verdict_accuracy")),
        "",
        "NEGATIVE RECALL =",
        _dash(header.get("negative_recall")),
        "",
        "POSITIVE SPECIFICITY =",
        _dash(header.get("positive_specificity")),
        "",
        "REASON-CODE COMPATIBLE =",
        _dash(header.get("reason_code_compatible")),
        "",
        "FUNERAL CASE =",
        _dash(header.get("funeral_case")),
        "",
        "CONNECTIVE CASE =",
        _dash(header.get("connective_case")),
        "",
        "P3 CASE =",
        _dash(header.get("p3_case")),
        "",
        "P8 CASE =",
        _dash(header.get("p8_case")),
        "",
        "PARTIAL-PARAGRAPH DETECTION =",
        _dash(header.get("partial_paragraph_detection")),
        "",
        "EXTERNAL-KNOWLEDGE RESISTANCE =",
        _dash(header.get("external_knowledge_resistance")),
        "",
        "RATIONALE QUALITY =",
        _dash(header.get("rationale_quality")),
        "",
        "DETERMINISTIC REPLAY =",
        _dash(header.get("deterministic_replay")),
        "",
        "4B.2.2 CANDIDATE CACHE =",
        "NOT ACCEPTED",
        "",
        "book.json =",
        "NOT PUBLISHED",
        "",
        "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT =",
        _dash(header.get("ready_for_book_generator_production_preflight")),
        "",
        "READY_FOR_FULL_REAL_BOOK_GENERATION =",
        "NO",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## Notes",
        "",
        _dash(header.get("notes")),
        "",
        "10 cases are an engineering canary, not a statistical model-quality benchmark.",
        "",
        "book-generator-1.0.1 remains SUFFICIENT_WITH_SEMANTIC_GATE. This phase does not automatically change that assessment.",
        "",
        "Wait for human review.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
