"""Constantes 3B.7.7A.47 — forensics contrat intent + scanner structurel. 0 provider."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis.window_granularity import TEXT_HARD_LIMITS as LOCAL_TEXT_HARD_LIMITS
from app.source_analysis_v31_global_output_architecture.constants import TEXT_LIMITS
from app.source_analysis_v31_global_v30_real_canary.constants import (
    A34_STATUS_PRESERVED,
    A35_STATUS_PRESERVED,
    A36_STATUS_PRESERVED,
    A37_STATUS_PRESERVED,
    A38_STATUS_PRESERVED,
    A39_STATUS_PRESERVED,
    A40_STATUS_PRESERVED,
    A41_STATUS_PRESERVED,
    A42_STATUS_PRESERVED,
    A43_STATUS_PRESERVED,
    A44_STATUS_PRESERVED,
    A45_ESTIMATED_INPUT,
    A45_EXPECTED_OUTPUT,
    A45_NORMALIZED_INPUT_HASH,
    A45_REQUEST_HASH,
    A45_STATUS_PRESERVED,
    CANARY_SUBDIR as A46_CANARY_SUBDIR,
    EXPECTED_IDEA,
    LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
    MODEL,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PROJECT_NAME,
    PROMPT_VERSION as FROZEN_PROMPT_VERSION,
    PROTECTED_HISTORICAL as A46_PROTECTED_HISTORICAL,
    PROVIDER,
    RAW_RESPONSE_ARTIFACT as A46_RAW_RESPONSE_ARTIFACT,
    RELATION_QUALITY_TECHNICAL_DEBT,
    REPORT_NAME as A46_REPORT_NAME,
    RESPONSE_IDENTITY_ARTIFACT as A46_RESPONSE_IDENTITY_ARTIFACT,
    SCHEMA_ADAPTED_BYTES,
    SCHEMA_HASH,
    SCHEMA_RAW_BYTES,
    THINKING_MODE,
    TRANSPORT_VERSION as FROZEN_TRANSPORT_VERSION,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.47"
MODE = "A46_GLOBAL_INTENT_LENGTH_AND_EDITORIAL_SCAN_FORENSICS"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_ANTHROPIC_CALLS = 0
REAL_OPENAI_CALLS = 0
REAL_CONSOLIDATION_CALLS = 0
CONSOLIDATION_AUTHORIZED = False
SOURCE_MAP_PUBLICATION_AUTHORIZED = False

A46_STATUS_PRESERVED = "FAIL"
assert A34_STATUS_PRESERVED == "PASS"
assert A35_STATUS_PRESERVED == "FAIL"
assert A36_STATUS_PRESERVED == "PASS"
assert A37_STATUS_PRESERVED == "PASS"
assert A38_STATUS_PRESERVED == "FAIL"
assert A39_STATUS_PRESERVED == "PASS"
assert A40_STATUS_PRESERVED == "FAIL"
assert A41_STATUS_PRESERVED == "PASS"
assert A42_STATUS_PRESERVED == "PASS"
assert A43_STATUS_PRESERVED == "PASS"
assert A44_STATUS_PRESERVED == "PASS"
assert A45_STATUS_PRESERVED == "PASS"
assert A46_STATUS_PRESERVED == "FAIL"
assert FROZEN_PROMPT_VERSION == "global-consolidation-3.0"
assert FROZEN_TRANSPORT_VERSION == "global-consolidation-transport-3.0"
assert SCHEMA_RAW_BYTES == 1583
assert SCHEMA_ADAPTED_BYTES == 1831
assert SCHEMA_HASH == (
    "822397b642b0e1724e29686962caab32bff63effe18f05bff26b404bad9b2a90"
)
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert THINKING_MODE == "disabled"
assert LOCAL_TEXT_HARD_LIMITS["intent"] == 280

A46_HTTP_STATUS = 200
A46_FINISH_REASON = "end_turn"
A46_THINKING_TOKENS = 0
A46_INPUT_TOKENS = 67675
A46_OUTPUT_TOKENS = 13317
A46_COST_USD = 0.26852
A46_ELAPSED_SECONDS = 82.5
A46_ELAPSED_MS = 82547
A46_REQUEST_ID = "req_011CfY9i2hGM9PHtHqeipfeV"
A46_RAW_TEXT_CHARS = 23543
A46_RAW_TEXT_BYTES = 23543
A46_RAW_RESPONSE_HASH = (
    "97c06b2173a878d70574d604c7569c08118c1e0fc07b33ef2b81d67e2a3d24a5"
)
A46_NORMALIZED_INPUT_HASH = A45_NORMALIZED_INPUT_HASH
A46_REQUEST_HASH = A45_REQUEST_HASH
A46_IDEA_ACCOUNTABILITY = f"{EXPECTED_IDEA} / {EXPECTED_IDEA}"
A46_KEEP = 286
A46_MERGE = 0
A46_DROP = 0
A46_INTENT_LENGTH = 290
A46_OUTPUT_UTILIZATION_PERCENT = 27.74
A45_INPUT_ESTIMATE_ERROR_ABS = 529
A45_INPUT_ESTIMATE_ERROR_PERCENT = 0.79
A45_EXPECTED_OUTPUT_ERROR_ABS = A46_OUTPUT_TOKENS - A45_EXPECTED_OUTPUT
A45_EXPECTED_OUTPUT_ERROR_PERCENT = round(
    100.0 * A45_EXPECTED_OUTPUT_ERROR_ABS / A45_EXPECTED_OUTPUT, 2
)
assert A45_EXPECTED_OUTPUT_ERROR_ABS == 205
assert A45_EXPECTED_OUTPUT_ERROR_PERCENT == 1.56

HISTORICAL_INTENT_LIMIT = 240
SELECTED_INTENT_LIMIT = 320
LOCAL_WINDOW_INTENT_LIMIT = int(LOCAL_TEXT_HARD_LIMITS["intent"])
assert TEXT_LIMITS["intent"] == SELECTED_INTENT_LIMIT == 320
assert HISTORICAL_INTENT_LIMIT == 240
THEME_LIMIT = int(TEXT_LIMITS["theme"])
INTENT_CONTRACT_ROOT_CAUSE = "MULTI_LAYER_CONTRACT_MISMATCH"
INTENT_SEMANTIC_VERDICT = "SEMANTICALLY_VALID_BUT_OVER_LIMIT"
HISTORICAL_240_ORIGIN = (
    "A.39 output-budget compactness bound copied into prompt 2.0/2.0.1/3.0 "
    "and reused as the global validator hard gate. Not a measured semantic "
    "requirement. Local windows already allow 280. Canonical SourceMap has no max."
)
LIMIT_JUSTIFICATION = (
    "320 is large enough for a faithful one-sentence global intent "
    "(above local-window 280 and A.46's 290), still below theme 360, "
    "and far below essay-like metadata. Selected independently of making A.46 pass."
)
PROMPT_CHANGE_REQUIRED = "YES"
TRANSPORT_CHANGE_REQUIRED = "NO"
SCHEMA_CHANGE_REQUIRED = "NO"
CANONICAL_CONTRACT_CHANGE_REQUIRED = "YES"
NEXT_PROMPT_VERSION = "global-consolidation-3.0.1"
NEXT_TRANSPORT_VERSION = FROZEN_TRANSPORT_VERSION
NEXT_SCHEMA_HASH = SCHEMA_HASH
EDITORIAL_SCAN_ROOT_CAUSE = "FALSE_POSITIVE_LEXICAL_SCAN"
CORE_ARCHITECTURE_FUNCTIONALLY_FROZEN = "YES"
CAN_A46_SAVED_RESPONSE_BE_VALIDATED_UNDER_CORRECTED_CONTRACT_WITHOUT_REPAIR = "YES"
READY_FOR_A46_OFFLINE_REVALIDATION = "YES"
READY_FOR_NEW_PROVIDER_CANARY = "NO"

INTENT_CONTRACT_ARTIFACT = "global_consolidation_a47_intent_contract_forensics.json"
INTENT_SEMANTIC_ARTIFACT = "global_consolidation_a47_a46_intent_semantic_review.json"
CONTRACT_MATRIX_ARTIFACT = "global_consolidation_a47_contract_matrix.json"
EDITORIAL_SCAN_ARTIFACT = "global_consolidation_a47_editorial_structure_scan_forensics.json"
COUNTERFACTUAL_ARTIFACT = "global_consolidation_a47_a46_counterfactual_revalidation.json"
CANDIDATE_SEMANTIC_ARTIFACT = "global_consolidation_a47_candidate_semantic_review.json"
READINESS_ARTIFACT = "global_consolidation_post_a47_readiness.json"
TEST_DELTA_ARTIFACT = "source_analysis_a47_test_delta.json"
BASELINE_ARTIFACT = "source_analysis_a47_test_baseline.json"
REPORT_NAME = "PHASE_3B77A47_A46_CONTRACT_FAILURE_FORENSICS_REPORT.md"

PROTECTED_HISTORICAL = A46_PROTECTED_HISTORICAL + (
    f"audit/{A46_REPORT_NAME}",
    f"audit/{A46_CANARY_SUBDIR}/{A46_RAW_RESPONSE_ARTIFACT}",
    f"audit/{A46_CANARY_SUBDIR}/{A46_RESPONSE_IDENTITY_ARTIFACT}",
)

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_a47_contract_forensics.py",
    "app/tests/test_source_analysis_v31_global_a47_contract_forensics_audit.py",
)
BROADER_SLICE_TEST_PATHS = FOCUSED_TEST_PATHS + (
    "app/tests/test_source_analysis_v31_global_v30_real_canary.py",
    "app/tests/test_source_analysis_v31_global_v30_real_canary_audit.py",
    "app/tests/test_source_analysis_v31_global_v30_exact_preflight.py",
    "app/tests/test_source_analysis_v31_global_v30_grammar_canary.py",
    "app/tests/test_source_analysis_v31_global_reuse_output.py",
    "app/tests/test_source_analysis_v31_global_v20_grammar_canary.py",
    "app/tests/test_source_analysis_v31_global_output_architecture.py",
    "app/tests/test_source_map_validator.py",
    "app/tests/test_source_map_normalization.py",
)

PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
NEXT_ACTION = "HUMAN REVIEW"

assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert REAL_ANTHROPIC_CALLS == 0
assert REAL_OPENAI_CALLS == 0
assert SOURCE_MAP_PUBLICATION_AUTHORIZED is False
assert A46_STATUS_PRESERVED == "FAIL"
assert not source_map_path(PROJECT_NAME).is_file() or SOURCE_MAP_STATUS == "NOT PUBLISHED"

__all__ = [
    "A34_STATUS_PRESERVED",
    "A35_STATUS_PRESERVED",
    "A36_STATUS_PRESERVED",
    "A37_STATUS_PRESERVED",
    "A38_STATUS_PRESERVED",
    "A39_STATUS_PRESERVED",
    "A40_STATUS_PRESERVED",
    "A41_STATUS_PRESERVED",
    "A42_STATUS_PRESERVED",
    "A43_STATUS_PRESERVED",
    "A44_STATUS_PRESERVED",
    "A45_ESTIMATED_INPUT",
    "A45_EXPECTED_OUTPUT",
    "A45_EXPECTED_OUTPUT_ERROR_ABS",
    "A45_EXPECTED_OUTPUT_ERROR_PERCENT",
    "A45_INPUT_ESTIMATE_ERROR_ABS",
    "A45_INPUT_ESTIMATE_ERROR_PERCENT",
    "A45_NORMALIZED_INPUT_HASH",
    "A45_REQUEST_HASH",
    "A45_STATUS_PRESERVED",
    "A46_CANARY_SUBDIR",
    "A46_COST_USD",
    "A46_DROP",
    "A46_ELAPSED_MS",
    "A46_ELAPSED_SECONDS",
    "A46_FINISH_REASON",
    "A46_HTTP_STATUS",
    "A46_IDEA_ACCOUNTABILITY",
    "A46_INPUT_TOKENS",
    "A46_INTENT_LENGTH",
    "A46_KEEP",
    "A46_MERGE",
    "A46_NORMALIZED_INPUT_HASH",
    "A46_OUTPUT_TOKENS",
    "A46_OUTPUT_UTILIZATION_PERCENT",
    "A46_PROTECTED_HISTORICAL",
    "A46_RAW_RESPONSE_ARTIFACT",
    "A46_RAW_RESPONSE_HASH",
    "A46_RAW_TEXT_BYTES",
    "A46_RAW_TEXT_CHARS",
    "A46_REPORT_NAME",
    "A46_REQUEST_HASH",
    "A46_REQUEST_ID",
    "A46_RESPONSE_IDENTITY_ARTIFACT",
    "A46_STATUS_PRESERVED",
    "A46_THINKING_TOKENS",
    "BASELINE_ARTIFACT",
    "BROADER_SLICE_TEST_PATHS",
    "CANONICAL_CONTRACT_CHANGE_REQUIRED",
    "CANDIDATE_SEMANTIC_ARTIFACT",
    "CAN_A46_SAVED_RESPONSE_BE_VALIDATED_UNDER_CORRECTED_CONTRACT_WITHOUT_REPAIR",
    "CONTRACT_MATRIX_ARTIFACT",
    "CORE_ARCHITECTURE_FUNCTIONALLY_FROZEN",
    "COUNTERFACTUAL_ARTIFACT",
    "EDITORIAL_SCAN_ARTIFACT",
    "EDITORIAL_SCAN_ROOT_CAUSE",
    "EXPECTED_IDEA",
    "FOCUSED_TEST_PATHS",
    "FROZEN_PROMPT_VERSION",
    "FROZEN_TRANSPORT_VERSION",
    "HISTORICAL_240_ORIGIN",
    "HISTORICAL_INTENT_LIMIT",
    "INTENT_CONTRACT_ARTIFACT",
    "INTENT_CONTRACT_ROOT_CAUSE",
    "INTENT_SEMANTIC_ARTIFACT",
    "INTENT_SEMANTIC_VERDICT",
    "LIMIT_JUSTIFICATION",
    "LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN",
    "LOCAL_WINDOW_INTENT_LIMIT",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "NEXT_PROMPT_VERSION",
    "NEXT_SCHEMA_HASH",
    "NEXT_TRANSPORT_VERSION",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PROJECT_NAME",
    "PROMPT_CHANGE_REQUIRED",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "READINESS_ARTIFACT",
    "READY_FOR_A46_OFFLINE_REVALIDATION",
    "READY_FOR_NEW_PROVIDER_CANARY",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPORT_NAME",
    "SCHEMA_ADAPTED_BYTES",
    "SCHEMA_CHANGE_REQUIRED",
    "SCHEMA_HASH",
    "SCHEMA_RAW_BYTES",
    "SCHEMA_VERSION",
    "SELECTED_INTENT_LIMIT",
    "SOURCE_MAP_PUBLICATION_AUTHORIZED",
    "SOURCE_MAP_STATUS",
    "TEST_DELTA_ARTIFACT",
    "TEXT_LIMITS",
    "THEME_LIMIT",
    "THINKING_MODE",
    "TRANSPORT_CHANGE_REQUIRED",
]
