"""Rapport markdown 3B.7.7A.47."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any], *, tests: str) -> str:
    header = bundle.get("header") or {}
    lines = [
        "# PHASE 3B.7.7A.47 — A.46 CONTRACT FAILURE FORENSICS",
        "",
        "## Result",
        "",
        str(header.get("result")),
        "",
        "REAL PROVIDER CALLS =",
        "0",
        "",
        "A.46 HISTORICAL STATUS =",
        "FAIL unchanged",
        "",
        "A.46 REQUEST IDENTITY =",
        _dash(header.get("a46_request_identity")),
        "",
        "A.46 HTTP / FINISH / THINKING =",
        f"{header.get('a46_http')} / {header.get('a46_finish')} / {header.get('a46_thinking')}",
        "",
        "A.46 INPUT / OUTPUT =",
        f"{header.get('a46_input')} / {header.get('a46_output')}",
        "",
        "A.46 COST =",
        f"{header.get('a46_cost')} USD",
        "",
        "A.46 ELAPSED =",
        f"{header.get('a46_elapsed')} s",
        "",
        "A.46 IDEA ACCOUNTABILITY =",
        _dash(header.get("a46_idea_accountability")),
        "",
        "A.46 REUSE / MERGE / DROP =",
        _dash(header.get("a46_reuse_merge_drop")),
        "",
        "A.46 PRIMARY FAILURE =",
        _dash(header.get("a46_primary_failure")),
        "",
        "INTENT CONTRACT ROOT CAUSE =",
        _dash(header.get("intent_contract_root_cause")),
        "",
        "A.46 INTENT SEMANTIC VERDICT =",
        _dash(header.get("a46_intent_semantic_verdict")),
        "",
        "HISTORICAL 240 LIMIT ORIGIN =",
        _dash(header.get("historical_240_limit_origin")),
        "",
        "SELECTED INTENT LIMIT =",
        _dash(header.get("selected_intent_limit")),
        "",
        "LIMIT JUSTIFICATION =",
        _dash(header.get("limit_justification")),
        "",
        "PROMPT CHANGE REQUIRED =",
        _dash(header.get("prompt_change_required")),
        "",
        "TRANSPORT CHANGE REQUIRED =",
        _dash(header.get("transport_change_required")),
        "",
        "SCHEMA CHANGE REQUIRED =",
        _dash(header.get("schema_change_required")),
        "",
        "CANONICAL CONTRACT CHANGE REQUIRED =",
        _dash(header.get("canonical_contract_change_required")),
        "",
        "NEXT PROMPT =",
        _dash(header.get("next_prompt")),
        "",
        "NEXT TRANSPORT =",
        _dash(header.get("next_transport")),
        "",
        "NEXT SCHEMA HASH =",
        _dash(header.get("next_schema_hash")),
        "",
        "A.46 UNCHANGED RAW RESPONSE COUNTERFACTUAL =",
        _dash(header.get("a46_unchanged_raw_response_counterfactual")),
        "",
        "CAN_A46_SAVED_RESPONSE_BE_VALIDATED_UNDER_CORRECTED_CONTRACT_WITHOUT_REPAIR =",
        _dash(
            header.get(
                "can_a46_saved_response_be_validated_under_corrected_contract_without_repair"
            )
        ),
        "",
        "EDITORIAL SCAN ROOT CAUSE =",
        _dash(header.get("editorial_scan_root_cause")),
        "",
        "A.46 ACTUAL FORBIDDEN EDITORIAL STRUCTURE =",
        _dash(header.get("a46_actual_forbidden_editorial_structure")),
        "",
        "LEXICAL CHAPTER FALSE POSITIVE =",
        _dash(header.get("lexical_chapter_false_positive")),
        "",
        "STRUCTURAL SCANNER =",
        _dash(header.get("structural_scanner")),
        "",
        "A.46 STRUCTURAL REPLAY =",
        _dash(header.get("a46_structural_replay")),
        "",
        "A.46 OUTPUT UTILIZATION =",
        _dash(header.get("a46_output_utilization")),
        "",
        "A.45 INPUT ESTIMATE ERROR =",
        _dash(header.get("a45_input_estimate_error")),
        "",
        "A.45 EXPECTED OUTPUT ERROR =",
        _dash(header.get("a45_expected_output_error")),
        "",
        "GLOBAL CONSOLIDATION CORE ARCHITECTURE FUNCTIONALLY FROZEN =",
        _dash(header.get("core_architecture_functionally_frozen")),
        "",
        "SEMANTIC CANDIDATE REVIEW =",
        _dash(header.get("semantic_candidate_review")),
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        _dash(header.get("new_failures")),
        "",
        "READY_FOR_A46_OFFLINE_REVALIDATION =",
        _dash(header.get("ready_for_a46_offline_revalidation")),
        "",
        "READY_FOR_NEW_PROVIDER_CANARY =",
        _dash(header.get("ready_for_new_provider_canary")),
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
