"""Constantes de l'audit 3B.5.1 — aucun timeout de production autorisé."""

from __future__ import annotations

SCHEMA_VERSION = "1.0"
PHASE = "3B.5.1"
MODE = "OFFLINE"

DIAGNOSTIC_ARTIFACT_NAME = "source_analysis_long_run_timeout_config_audit.json"
REPORT_NAME = "PHASE_3B51_LONG_RUN_TIMEOUT_CONFIGURATION_REPORT.md"

PREVIOUS_CLASSIFICATION = "HTTP_READ_TIMEOUT_TOO_SHORT"
PREVIOUS_EFFECTIVE_TIMEOUT_SECONDS = 3600.0
AUTHORIZATION_WAIT_CAUSED_TIMEOUT = False

EXACT_NEXT_READ_TIMEOUT_AUTHORIZED = False
NEXT_PAID_CALL_AUTHORIZED = False
NEW_ANTHROPIC_CALL_AUTHORIZED = False
FINAL_RETRY_AUTHORIZED = False
REQUIRES_HUMAN_REVIEW = True

NEXT_PHASE = "3B.5.2_LONG_RUN_EXECUTION_POLICY"

BASELINE_PASSED = 1932
FINAL_PASSED = 1982
FINAL_FAILED = 0

EDITORIAL_STAGES = (
    "source_analysis",
    "editorial_planning",
    "book_generation",
    "book_validation",
)

__all__ = [
    "DIAGNOSTIC_ARTIFACT_NAME",
    "EXACT_NEXT_READ_TIMEOUT_AUTHORIZED",
    "FINAL_RETRY_AUTHORIZED",
    "MODE",
    "NEW_ANTHROPIC_CALL_AUTHORIZED",
    "NEXT_PAID_CALL_AUTHORIZED",
    "NEXT_PHASE",
    "PHASE",
    "PREVIOUS_CLASSIFICATION",
    "REPORT_NAME",
    "REQUIRES_HUMAN_REVIEW",
    "SCHEMA_VERSION",
]
