"""Markdown report Phase 4B.2."""

from __future__ import annotations

from typing import Any, Mapping


def render_report(bundle: Mapping[str, Any]) -> str:
    header = dict(bundle.get("header") or {})
    lines = [
        "# PHASE 4B.2 — BOOK GENERATOR ONE REAL SMALL-CHAPTER CANARY",
        "",
        "## Result",
        "",
        str(header.get("result") or "FAIL"),
        "",
        f"AUTHORIZED PROVIDER CALLS = {header.get('authorized_provider_calls', 1)}",
        "",
        f"ACTUAL PROVIDER CALLS = {header.get('actual_provider_calls', 0)}",
        "",
        f"RETRIES = {header.get('retries', 0)}",
        "",
        f"FALLBACKS = {header.get('fallbacks', 0)}",
        "",
        f"TARGET CHAPTER = {header.get('target_chapter')}",
        "",
        f"SOURCE MAP SHA256 PRE/POST = {header.get('source_map_sha256_pre')}/"
        f"{header.get('source_map_sha256_post')}",
        "",
        f"EDITORIAL PLAN SHA256 PRE/POST = {header.get('editorial_plan_sha256_pre')}/"
        f"{header.get('editorial_plan_sha256_post')}",
        "",
        f"CLEAN TRANSCRIPT SHA256 PRE/POST = {header.get('transcript_sha256_pre')}/"
        f"{header.get('transcript_sha256_post')}",
        "",
        f"INPUTS UNCHANGED = {header.get('inputs_unchanged')}",
        "",
        f"CANONICAL LANGUAGE = {header.get('canonical_language')}",
        "",
        f"MODEL = {header.get('model')}",
        "",
        f"PROMPT = {header.get('prompt')}",
        "",
        f"TRANSPORT = {header.get('transport')}",
        "",
        f"SCHEMA RAW / ADAPTED = {header.get('schema_raw_adapted')}",
        "",
        f"SCHEMA SHA256 = {header.get('schema_sha256')}",
        "",
        f"THINKING = {header.get('thinking')}",
        "",
        f"MAX_OUTPUT = {header.get('max_output')}",
        "",
        f"REQUEST SHA256 = {header.get('request_sha256')}",
        "",
        f"REQUEST DETERMINISM = {header.get('request_determinism')}",
        "",
        f"CHAPTER SECTIONS EXPECTED = {header.get('chapter_sections_expected')}",
        "",
        f"CHAPTER IDEAS EXPECTED = {header.get('chapter_ideas_expected')}",
        "",
        f"HYDRATED SRC COUNT = {header.get('hydrated_src_count')}",
        "",
        f"HYDRATED CHARS = {header.get('hydrated_chars')}",
        "",
        f"HTTP / FINISH = {header.get('http_status')} / {header.get('finish')}",
        "",
        f"REQUEST ID = {header.get('request_id')}",
        "",
        f"INPUT TOKENS = {header.get('input_tokens')}",
        "",
        f"OUTPUT TOKENS = {header.get('output_tokens')}",
        "",
        f"THINKING TOKENS = {header.get('thinking_tokens')}",
        "",
        f"ELAPSED = {header.get('elapsed')}",
        "",
        f"ACTUAL COST = {header.get('actual_cost')}",
        "",
        f"STRUCTURED PARSE = {header.get('structured_parse')}",
        "",
        f"TRANSPORT DECODER = {header.get('transport_decoder')}",
        "",
        f"RECONSTRUCTION = {header.get('reconstruction')}",
        "",
        f"SECTION COVERAGE = {header.get('section_coverage')}",
        "",
        f"SECTION ORDER = {header.get('section_order')}",
        "",
        f"IDEA COVERAGE = {header.get('idea_coverage')}",
        "",
        f"SILENT IDEA OMISSIONS = {header.get('silent_idea_omissions')}",
        "",
        f"UNKNOWN IDEA REFS = {header.get('unknown_idea_refs')}",
        "",
        f"UNKNOWN SRC REFS = {header.get('unknown_src_refs')}",
        "",
        f"UNSOURCED SUBSTANTIVE PARAGRAPHS = {header.get('unsourced_substantive_paragraphs')}",
        "",
        f"CONNECTIVE PARAGRAPHS = {header.get('connective_paragraphs')}",
        "",
        f"EDITORIAL LANGUAGE = {header.get('editorial_language')}",
        "",
        f"LOCAL VALIDATOR = {header.get('local_validator')}",
        "",
        f"PARAGRAPHS = {header.get('paragraphs')}",
        "",
        f"WORDS = {header.get('words')}",
        "",
        f"QUESTIONABLE SUPPORT PARAGRAPHS = {header.get('questionable_support')}",
        "",
        f"UNSUPPORTED PARAGRAPHS = {header.get('unsupported_paragraphs')}",
        "",
        f"SOURCE MEANING = {header.get('source_meaning')}",
        "",
        f"ORAL-TO-WRITTEN TRANSFORMATION = {header.get('oral_to_written')}",
        "",
        f"AUTHOR VOICE = {header.get('author_voice')}",
        "",
        f"INVENTED FACTS = {header.get('invented_facts')}",
        "",
        f"INVENTED ARGUMENTS = {header.get('invented_arguments')}",
        "",
        f"INVENTED EXAMPLES = {header.get('invented_examples')}",
        "",
        f"INVENTED REFERENCES = {header.get('invented_references')}",
        "",
        f"UNCERTAINTY PRESERVATION = {header.get('uncertainty_preservation')}",
        "",
        f"REPETITION CONTROL = {header.get('repetition_control')}",
        "",
        f"MANUSCRIPT QUALITY = {header.get('manuscript_quality')}",
        "",
        f"DETERMINISTIC REPLAY = {header.get('deterministic_replay')}",
        "",
        f"CANDIDATE SHA256 = {header.get('candidate_sha256')}",
        "",
        f"book.json = {header.get('book_json', 'NOT PUBLISHED')}",
        "",
        f"READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = "
        f"{header.get('ready_for_book_generator_production_preflight')}",
        "",
        f"READY_FOR_FULL_REAL_BOOK_GENERATION = "
        f"{header.get('ready_for_full_real_book_generation', 'NO')}",
        "",
        f"NEXT ACTION = {header.get('next_action', 'HUMAN REVIEW')}",
        "",
    ]
    notes = header.get("notes")
    if notes:
        lines.extend(["## Notes", "", str(notes), ""])
    return "\n".join(lines)


__all__ = ["render_report"]
