"""Phase 4B.2.14 — isolated production bridge candidate. Disabled by default."""

from app.book_generation_bridge_4b214.constants import (
    AUTHORIZED_TERRA_CALLS,
    BRIDGE_CONTRACT_ACTIVATED,
    BRIDGE_ENABLED,
    BRIDGE_ENABLED_BY_DEFAULT,
    PHASE,
    PRODUCTION_PIPELINE_HOOK,
    REAL_CHAPTER_GENERATION_AUTHORIZED,
    REAL_PROVIDERS_ENABLED,
    SEMANTIC_GATE_20_ENABLED,
    SEMANTIC_GATE_202_ENABLED,
    SONNET_EXECUTION_AUTHORIZED,
    TERRA_EXECUTION_AUTHORIZED,
)

assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert SONNET_EXECUTION_AUTHORIZED is False
assert REAL_CHAPTER_GENERATION_AUTHORIZED is False
assert REAL_PROVIDERS_ENABLED is False
assert SEMANTIC_GATE_20_ENABLED is False
assert SEMANTIC_GATE_202_ENABLED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert BRIDGE_ENABLED is False
assert BRIDGE_ENABLED_BY_DEFAULT is False
assert BRIDGE_CONTRACT_ACTIVATED is False

__all__ = [
    "PHASE",
    "AUTHORIZED_TERRA_CALLS",
    "TERRA_EXECUTION_AUTHORIZED",
    "SONNET_EXECUTION_AUTHORIZED",
    "REAL_CHAPTER_GENERATION_AUTHORIZED",
    "REAL_PROVIDERS_ENABLED",
    "SEMANTIC_GATE_20_ENABLED",
    "SEMANTIC_GATE_202_ENABLED",
    "PRODUCTION_PIPELINE_HOOK",
    "BRIDGE_ENABLED",
    "BRIDGE_ENABLED_BY_DEFAULT",
    "BRIDGE_CONTRACT_ACTIVATED",
]
