"""
Phase 4B.2.14 — Book Generator × Semantic Gate 2.0 production bridge
and cost-bounded execution preflight.

STRICTLY OFFLINE. Isolated from production. Zero provider calls.
Does not generate a real chapter. Does not activate Semantic Gate 2.0.
Does not write the production cache. Does not publish book.json.
The candidate bridge is disabled by default.
"""

from __future__ import annotations

from app.book_generation.constants import (
    BOOK_FILENAME,
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    BOOK_SCHEMA_VERSION,
    MODEL as GENERATOR_MODEL,
    PROVIDER as GENERATOR_PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_generation_integration_4b213.constants import (
    HISTORICAL_4B210_STATUS,
    HISTORICAL_4B211_COMPLETION_TOKENS,
    HISTORICAL_4B211_COST_USD,
    HISTORICAL_4B211_INPUT_TOKENS,
    HISTORICAL_4B211_REASONING_TOKENS,
    HISTORICAL_4B211_STATUS,
    INTEGRATION_CONTRACT_VERSION,
    ISOLATED_CACHE_VERSION,
    PHASE5_INTERFACE_VERSION as PHASE5_INTERFACE_VERSION_4B213,
    PREPARATION_ALGORITHM_VERSION,
    VALIDATOR_IMPLEMENTATION_VERSION,
)
from app.book_semantic_gate_4b210.constants import (
    H01_EVIDENCE_HANDLES,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
    TRANSPORT_VERSION_20_CANDIDATE,
)
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
)
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE
from app.book_semantic_gate_4b212.constants import (
    DECISION_BLOCK,
    DECISION_PASS,
    DECISION_REVIEW,
    FIXTURE_KIND,
    PROMPT_VERSION_20_CANDIDATE,
    PROMPT_VERSION_201_CANDIDATE,
    PROMPT_VERSION_202_CANDIDATE,
)
from app.book_semantic_gate_4b29.constants import OFFSET_CONVENTION, OFFSET_CONVENTION_NOTES

PHASE = "4B.2.14"
PHASE_NAME = (
    "BOOK_GENERATOR_SEMANTIC_GATE_20_PRODUCTION_BRIDGE_AND_COST_PREFLIGHT"
)

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_GENERATION_BRIDGE_4B214_BOOK_GENERATOR_SEMANTIC_GATE_20_"
    "PRODUCTION_BRIDGE_AND_COST_PREFLIGHT_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = False
REAL_CHAPTER_GENERATION_AUTHORIZED = False
REAL_PROVIDERS_ENABLED = False
SDK_MAX_RETRIES = 0
RETRIES = 0
FALLBACKS = 0

BRIDGE_ENABLED = False
BRIDGE_ENABLED_BY_DEFAULT = False
SEMANTIC_GATE_20_ENABLED = False
SEMANTIC_GATE_201_ENABLED = False
SEMANTIC_GATE_202_ENABLED = False
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
SINGLE_CHAPTER_MODE_DEFAULT = False
PHASE5_EXECUTED = False

CODE_VERSION = "app.book_generation_bridge_4b214"
BRIDGE_CONTRACT_VERSION = (
    "book-generator-semantic-gate-bridge-4b214-candidate"
)
ADAPTER_VERSION = "book-generator-semantic-gate-adapter-4b214-candidate"
BUDGET_POLICY_VERSION = "book-execution-budget-4b214-candidate"
AUTHORIZATION_VERSION = "book-human-authorization-4b214-candidate"
REVIEW_PROTOCOL_VERSION = "book-human-review-protocol-4b214-candidate"
SINGLE_CHAPTER_MODE_VERSION = "book-single-chapter-mode-4b214-candidate"
PHASE5_INTERFACE_VERSION = "book-validator-phase5-interface-4b214-candidate"

PROMPT_VERSION_20_ACTIVATED = False
PROMPT_VERSION_201_ACTIVATED = False
PROMPT_VERSION_202_ACTIVATED = False
TRANSPORT_VERSION_20_ACTIVATED = False
BRIDGE_CONTRACT_ACTIVATED = False
INTEGRATION_CONTRACT_ACTIVATED = False

FAKEAI_SOURCE = "FAKEAI_SIMULATED"
FAKEAI_GENERATOR_ROLE = "simulated_book_generator"
FAKEAI_SEMANTIC_ROLE = "simulated_semantic_validator"
NOT_TERRA = True
NOT_SONNET = True

SEMANTIC_GATE_PROVIDER = "openai"
SEMANTIC_GATE_MODEL = "gpt-5.6-terra"
PRICING_EFFECTIVE_DATE = "2026-09-18"
TERRA_INPUT_COST_PER_1M = 2.0
TERRA_OUTPUT_COST_PER_1M = 12.0
SONNET_INPUT_COST_PER_1M = 2.0
SONNET_OUTPUT_COST_PER_1M = 10.0

LEDGER_BOOK_GENERATOR = "book_generator"
LEDGER_SEMANTIC_GATE = "semantic_gate"
LEDGER_BOOK_VALIDATOR = "book_validator"
LEDGER_GLOBAL = "global"
LEDGER_NAMES = (
    LEDGER_BOOK_GENERATOR,
    LEDGER_SEMANTIC_GATE,
    LEDGER_BOOK_VALIDATOR,
    LEDGER_GLOBAL,
)

COST_ESTIMATED = "estimated"
COST_OBSERVED = "observed"
COST_RESERVED = "reserved"
COST_COMMITTED = "committed"
COST_UNKNOWN = "UNKNOWN"
COST_STATES = (
    COST_ESTIMATED,
    COST_OBSERVED,
    COST_RESERVED,
    COST_COMMITTED,
    COST_UNKNOWN,
)

STRATEGY_A = "A_ONE_REQUEST_PER_PARAGRAPH"
STRATEGY_B = "B_PARAGRAPH_GROUPING"
STRATEGY_C = "C_ONE_REQUEST_PER_CHAPTER"
CANDIDATE_GRANULARITY = STRATEGY_A

INTERRUPT_BEFORE_RESERVATION = "before_reservation"
INTERRUPT_AFTER_RESERVATION = "after_reservation"
INTERRUPT_BEFORE_SEND = "before_send"
INTERRUPT_AFTER_SEND = "after_send"
INTERRUPT_AFTER_RESPONSE = "after_response"
INTERRUPT_AFTER_VALIDATION = "after_validation"
INTERRUPT_AFTER_REVIEW = "after_review"
INTERRUPT_AFTER_BLOCK = "after_block"
INTERRUPTION_POINTS = (
    INTERRUPT_BEFORE_RESERVATION,
    INTERRUPT_AFTER_RESERVATION,
    INTERRUPT_BEFORE_SEND,
    INTERRUPT_AFTER_SEND,
    INTERRUPT_AFTER_RESPONSE,
    INTERRUPT_AFTER_VALIDATION,
    INTERRUPT_AFTER_REVIEW,
    INTERRUPT_AFTER_BLOCK,
)

REVIEW_CONFIRM_SUPPORTED = "confirm_supported"
REVIEW_REQUEST_CORRECTION = "request_correction"
REVIEW_MAINTAIN_BLOCK = "maintain_block"
REVIEW_ACTIONS = (
    REVIEW_CONFIRM_SUPPORTED,
    REVIEW_REQUEST_CORRECTION,
    REVIEW_MAINTAIN_BLOCK,
)

SYNTHETIC_PREFIX = "SYN-"
SYNTHETIC_SOURCE_MAP_HASH = "SYNTHETIC_OFFLINE_FIXTURE"
SYNTHETIC_EDITORIAL_PLAN_HASH = "SYNTHETIC_OFFLINE_FIXTURE"

HISTORICAL_4B212_STATUS = "PASS"
HISTORICAL_4B213_STATUS = "PASS"

assert PROJECT_NAME == "pastoral_retreat_v2_validation"
assert AUTHORIZED_TERRA_CALLS == 0
assert AUTHORIZED_SONNET_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert SONNET_EXECUTION_AUTHORIZED is False
assert REAL_CHAPTER_GENERATION_AUTHORIZED is False
assert REAL_PROVIDERS_ENABLED is False
assert PUBLICATION_AUTHORIZED is False
assert BRIDGE_ENABLED is False
assert BRIDGE_ENABLED_BY_DEFAULT is False
assert SEMANTIC_GATE_20_ENABLED is False
assert SEMANTIC_GATE_202_ENABLED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert SINGLE_CHAPTER_MODE_DEFAULT is False
assert PHASE5_EXECUTED is False
assert PROMPT_VERSION_202_CANDIDATE == "book-semantic-validator-2.0.2-candidate"
assert TRANSPORT_VERSION_20_CANDIDATE == (
    "book-semantic-validation-transport-2.0-candidate"
)
assert PROMPT_VERSION_202_ACTIVATED is False
assert TRANSPORT_VERSION_20_ACTIVATED is False
assert BRIDGE_CONTRACT_ACTIVATED is False
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_H11_STATUS == "PARTIAL"
assert HISTORICAL_4B210_STATUS == "PASS"
assert HISTORICAL_4B211_STATUS == "PARTIAL"
assert HISTORICAL_4B212_STATUS == "PASS"
assert HISTORICAL_4B213_STATUS == "PASS"
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert CANONICAL_PYTHON_EXECUTABLE.endswith("python.exe")
assert BOOK_FILENAME == "book.json"
assert SDK_MAX_RETRIES == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert GENERATOR_PROVIDER == "anthropic"
assert GENERATOR_MODEL == "claude-sonnet-5"
assert SEMANTIC_GATE_MODEL == "gpt-5.6-terra"
assert COST_UNKNOWN != "0"
assert CLASSIFICATIONS == (
    CLASS_SUPPORTED,
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    CLASS_NON_SUBSTANTIVE,
)

AUDIT_DIRNAME = "book_generation_bridge_4b214"
AUDIT_INVENTORY = "technical_inventory.json"
AUDIT_INTERFACES = "production_interfaces.json"
AUDIT_ARCHITECTURE = "bridge_architecture.json"
AUDIT_ADAPTER = "adapter_validation.json"
AUDIT_GRANULARITY = "validation_granularity.json"
AUDIT_VOLUMES = "canonical_volume_inventory.json"
AUDIT_SCENARIOS = "request_volume_scenarios.json"
AUDIT_COST_ASSUMPTIONS = "cost_assumptions.json"
AUDIT_COST_ESTIMATES = "cost_estimates.json"
AUDIT_BUDGET_POLICY = "budget_policy.json"
AUDIT_BUDGET_RESERVATION = "budget_reservation_tests.json"
AUDIT_BUDGET_RECONCILIATION = "budget_reconciliation_tests.json"
AUDIT_SINGLE_CHAPTER = "single_chapter_mode.json"
AUDIT_AUTHORIZATION = "human_authorization.json"
AUDIT_REVIEW = "human_review_protocol.json"
AUDIT_RECOVERY = "interruption_recovery.json"
AUDIT_IDEMPOTENCE = "idempotence.json"
AUDIT_TRACEABILITY = "traceability.json"
AUDIT_PHASE5 = "phase5_boundary.json"
AUDIT_SAFETY = "provider_safety.json"
AUDIT_HASHES = "canonical_hashes.json"
AUDIT_TESTS = "offline_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_INDEX = "book_generation_bridge_4b214_index.json"
REPORT_NAME = (
    "PHASE_4B214_BOOK_GENERATOR_SEMANTIC_GATE_20_"
    "PRODUCTION_BRIDGE_AND_COST_PREFLIGHT_REPORT.md"
)

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_BRIDGE_HUMAN_REVIEW = True
READY_FOR_ONE_REAL_CHAPTER_EXPERIMENT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "ADAPTER_VERSION",
    "AUDIT_ADAPTER",
    "AUDIT_ARCHITECTURE",
    "AUDIT_AUTHORIZATION",
    "AUDIT_BUDGET_POLICY",
    "AUDIT_BUDGET_RECONCILIATION",
    "AUDIT_BUDGET_RESERVATION",
    "AUDIT_COST_ASSUMPTIONS",
    "AUDIT_COST_ESTIMATES",
    "AUDIT_DIRNAME",
    "AUDIT_GRANULARITY",
    "AUDIT_HASHES",
    "AUDIT_IDEMPOTENCE",
    "AUDIT_INDEX",
    "AUDIT_INTERFACES",
    "AUDIT_INVENTORY",
    "AUDIT_PHASE5",
    "AUDIT_READINESS",
    "AUDIT_RECOVERY",
    "AUDIT_REVIEW",
    "AUDIT_SAFETY",
    "AUDIT_SCENARIOS",
    "AUDIT_SINGLE_CHAPTER",
    "AUDIT_TESTS",
    "AUDIT_TRACEABILITY",
    "AUDIT_VOLUMES",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZATION_VERSION",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_REMOTE_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "BOOK_FILENAME",
    "BOOK_GENERATION_TRANSPORT_VERSION",
    "BOOK_GENERATOR_PROMPT_VERSION",
    "BOOK_GENERATOR_VALIDATOR_VERSION",
    "BOOK_SCHEMA_VERSION",
    "BRIDGE_CONTRACT_ACTIVATED",
    "BRIDGE_CONTRACT_VERSION",
    "BRIDGE_ENABLED",
    "BRIDGE_ENABLED_BY_DEFAULT",
    "BUDGET_POLICY_VERSION",
    "CANDIDATE_GRANULARITY",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CODE_VERSION",
    "COST_COMMITTED",
    "COST_ESTIMATED",
    "COST_OBSERVED",
    "COST_RESERVED",
    "COST_STATES",
    "COST_UNKNOWN",
    "DECISION_BLOCK",
    "DECISION_PASS",
    "DECISION_REVIEW",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_SOURCE_MAP",
    "FAKEAI_GENERATOR_ROLE",
    "FAKEAI_SEMANTIC_ROLE",
    "FAKEAI_SOURCE",
    "FALLBACKS",
    "FIXTURE_KIND",
    "GENERATOR_MODEL",
    "GENERATOR_PROVIDER",
    "H01_EVIDENCE_HANDLES",
    "HISTORICAL_4B210_STATUS",
    "HISTORICAL_4B211_COMPLETION_TOKENS",
    "HISTORICAL_4B211_COST_USD",
    "HISTORICAL_4B211_INPUT_TOKENS",
    "HISTORICAL_4B211_REASONING_TOKENS",
    "HISTORICAL_4B211_STATUS",
    "HISTORICAL_4B212_STATUS",
    "HISTORICAL_4B213_STATUS",
    "HISTORICAL_H01_STATUS",
    "HISTORICAL_H02_STATUS",
    "HISTORICAL_H11_STATUS",
    "INTEGRATION_CONTRACT_ACTIVATED",
    "INTEGRATION_CONTRACT_VERSION",
    "INTERRUPTION_POINTS",
    "INTERRUPT_AFTER_BLOCK",
    "INTERRUPT_AFTER_RESERVATION",
    "INTERRUPT_AFTER_RESPONSE",
    "INTERRUPT_AFTER_REVIEW",
    "INTERRUPT_AFTER_SEND",
    "INTERRUPT_AFTER_VALIDATION",
    "INTERRUPT_BEFORE_RESERVATION",
    "INTERRUPT_BEFORE_SEND",
    "ISOLATED_CACHE_VERSION",
    "LEDGER_BOOK_GENERATOR",
    "LEDGER_BOOK_VALIDATOR",
    "LEDGER_GLOBAL",
    "LEDGER_NAMES",
    "LEDGER_SEMANTIC_GATE",
    "NEXT_ACTION",
    "NOT_SONNET",
    "NOT_TERRA",
    "OFFSET_CONVENTION",
    "OFFSET_CONVENTION_NOTES",
    "PHASE",
    "PHASE5_EXECUTED",
    "PHASE5_INTERFACE_VERSION",
    "PHASE5_INTERFACE_VERSION_4B213",
    "PHASE_NAME",
    "PREPARATION_ALGORITHM_VERSION",
    "PRICING_EFFECTIVE_DATE",
    "PRODUCTION_CACHE_ACCEPTANCE",
    "PRODUCTION_PIPELINE_HOOK",
    "PROJECT_NAME",
    "PROMPT_VERSION_20_ACTIVATED",
    "PROMPT_VERSION_20_CANDIDATE",
    "PROMPT_VERSION_201_ACTIVATED",
    "PROMPT_VERSION_201_CANDIDATE",
    "PROMPT_VERSION_202_ACTIVATED",
    "PROMPT_VERSION_202_CANDIDATE",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_BRIDGE_HUMAN_REVIEW",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "READY_FOR_ONE_REAL_CHAPTER_EXPERIMENT",
    "REAL_CHAPTER_GENERATION_AUTHORIZED",
    "REAL_PROVIDERS_ENABLED",
    "REPORT_NAME",
    "RETRIES",
    "REVIEW_ACTIONS",
    "REVIEW_CONFIRM_SUPPORTED",
    "REVIEW_MAINTAIN_BLOCK",
    "REVIEW_PROTOCOL_VERSION",
    "REVIEW_REQUEST_CORRECTION",
    "SDK_MAX_RETRIES",
    "SEMANTIC_GATE_20_ENABLED",
    "SEMANTIC_GATE_201_ENABLED",
    "SEMANTIC_GATE_202_ENABLED",
    "SEMANTIC_GATE_MODEL",
    "SEMANTIC_GATE_PROVIDER",
    "SINGLE_CHAPTER_MODE_DEFAULT",
    "SINGLE_CHAPTER_MODE_VERSION",
    "SONNET_EXECUTION_AUTHORIZED",
    "SONNET_INPUT_COST_PER_1M",
    "SONNET_OUTPUT_COST_PER_1M",
    "STRATEGY_A",
    "STRATEGY_B",
    "STRATEGY_C",
    "SYNTHETIC_EDITORIAL_PLAN_HASH",
    "SYNTHETIC_PREFIX",
    "SYNTHETIC_SOURCE_MAP_HASH",
    "TERRA_EXECUTION_AUTHORIZED",
    "TERRA_INPUT_COST_PER_1M",
    "TERRA_OUTPUT_COST_PER_1M",
    "TRANSPORT_VERSION_20_ACTIVATED",
    "TRANSPORT_VERSION_20_CANDIDATE",
    "VALIDATOR_IMPLEMENTATION_VERSION",
]
