"""
Phase 4B.2.16 — Faithful thematic reorganization and semantic alignment.

STRICTLY OFFLINE. Isolated from production. Zero provider calls.
Does not replace the historical Book Generator prompt.
Does not modify book-semantic-validator-2.0.2-candidate.
Does not generate a chapter. Does not publish book.json.
"""

from __future__ import annotations

from app.book_generation.constants import (
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION_V10,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    MODEL as GENERATOR_MODEL,
    PROVIDER as GENERATOR_PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_generation.prompt import (
    FROZEN_INSTRUCTIONS_SHA256,
    FROZEN_PROMPT_SHA256,
    FROZEN_SYSTEM_SHA256,
)
from app.book_semantic_gate_4b212.constants import (
    HISTORICAL_4B211_COMPLETION_TOKENS,
    HISTORICAL_4B211_COST_USD,
    HISTORICAL_4B211_INPUT_TOKENS,
    PROMPT_VERSION_202_ACTIVATED,
    PROMPT_VERSION_202_CANDIDATE,
)
from app.book_semantic_gate_4b215.constants import (
    HISTORICAL_4B210_STATUS,
    HISTORICAL_4B211_STATUS,
    HISTORICAL_4B212_STATUS,
    HISTORICAL_4B213_STATUS,
    HISTORICAL_4B214_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
)
from app.book_semantic_gate_4b23.constants import EXPECTED_CLEAN_TRANSCRIPT
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE
from app.book_semantic_gate_4b28.constants import H11_HUMAN_LABEL

PHASE = "4B.2.16"
PHASE_NAME = "FAITHFUL_THEMATIC_REORGANIZATION_AND_SEMANTIC_ALIGNMENT"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_EDITORIAL_ALIGNMENT_4B216_FAITHFUL_THEMATIC_REORGANIZATION_"
    "AND_SEMANTIC_ALIGNMENT_ONLY"
)

AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = False
REAL_CHAPTER_GENERATION_AUTHORIZED = False
REAL_PROVIDERS_ENABLED = False
RETRIES = 0
FALLBACKS = 0

PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
COVERAGE_CONTROL_ACTIVATED = False
FAITHFUL_PROMPT_ACTIVATED = False
EDITORIAL_POLICY_ACTIVATED = False
SEMANTIC_GATE_202_ENABLED = False

CODE_VERSION = "app.book_editorial_alignment_4b216"
EDITORIAL_POLICY_VERSION = "faithful-teaching-book-editorial-policy-1.0-candidate"
FAITHFUL_PROMPT_VERSION = "book-generator-faithful-restatement-1.0-candidate"
COVERAGE_CONTRACT_VERSION = "source-coverage-control-4b216-candidate"
HUMAN_RESOLUTION_VERSION = "human-resolution-protocol-4b216-candidate"
THEMATIC_RULES_VERSION = "thematic-reorganization-rules-4b216-candidate"

HISTORICAL_GENERATOR_PROMPT_V10 = BOOK_GENERATOR_PROMPT_VERSION_V10
HISTORICAL_GENERATOR_PROMPT = BOOK_GENERATOR_PROMPT_VERSION
HISTORICAL_SEMANTIC_CONTRACT = PROMPT_VERSION_202_CANDIDATE

HISTORICAL_4B215_STATUS = "PARTIAL"
HISTORICAL_4B216_DOES_NOT_REQUALIFY = True

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_TRANSCRIPT = EXPECTED_CLEAN_TRANSCRIPT

FROZEN_GENERATOR_SYSTEM_SHA256 = FROZEN_SYSTEM_SHA256
FROZEN_GENERATOR_INSTRUCTIONS_SHA256 = FROZEN_INSTRUCTIONS_SHA256
FROZEN_GENERATOR_PROMPT_SHA256 = FROZEN_PROMPT_SHA256

SONNET_PROVIDER = GENERATOR_PROVIDER
SONNET_MODEL = GENERATOR_MODEL
SEMANTIC_GATE_PROVIDER = "openai"
SEMANTIC_GATE_MODEL = "gpt-5.6-terra"
PRICING_EFFECTIVE_DATE = "2026-09-18"
SONNET_INPUT_COST_PER_1M = 2.0
SONNET_OUTPUT_COST_PER_1M = 10.0
TERRA_INPUT_COST_PER_1M = 2.0
TERRA_OUTPUT_COST_PER_1M = 12.0

H01_ANALOG_COST_USD = HISTORICAL_4B211_COST_USD
H01_ANALOG_INPUT_TOKENS = HISTORICAL_4B211_INPUT_TOKENS
H01_ANALOG_COMPLETION_TOKENS = HISTORICAL_4B211_COMPLETION_TOKENS

COST_UNKNOWN = "UNKNOWN"
EXCLUDED_PILOT_CHAPTERS = ("CH001", "CH016")
PREFERRED_IDEA_LOW = 10
PREFERRED_IDEA_HIGH = 12
ELIGIBLE_IDEA_LOW = 8
ELIGIBLE_IDEA_HIGH = 16
ELIGIBLE_SECTION_LOW = 3
ELIGIBLE_SECTION_HIGH = 5
MODEST_EVIDENCE_CHARS = 16000

AUDIT_DIRNAME = "book_editorial_alignment_4b216"
AUDIT_POLICY = "editorial_policy.json"
AUDIT_PROMPT_REVIEW = "current_prompt_review.json"
AUDIT_RISK_MAP = "editorial_plan_risk_map.json"
AUDIT_FAITHFUL_PROMPT = "faithful_generator_prompt_candidate.json"
AUDIT_COVERAGE = "source_coverage_contract.json"
AUDIT_SEMANTIC = "semantic_gate_alignment.json"
AUDIT_HUMAN = "human_resolution_protocol.json"
AUDIT_CANDIDATES = "pilot_chapter_candidates.json"
AUDIT_SELECTED = "selected_pilot_chapter.json"
AUDIT_BUDGET = "pilot_budget_estimate.json"
AUDIT_SCENARIOS = "offline_scenarios.json"
AUDIT_HASHES = "canonical_hashes.json"
AUDIT_TESTS = "regression_tests.json"
AUDIT_READINESS = "readiness.json"
REPORT_NAME = (
    "PHASE_4B216_FAITHFUL_THEMATIC_REORGANIZATION_"
    "AND_SEMANTIC_ALIGNMENT_REPORT.md"
)

assert AUTHORIZED_TERRA_CALLS == 0
assert AUTHORIZED_SONNET_CALLS == 0
assert PUBLICATION_AUTHORIZED is False
assert REAL_CHAPTER_GENERATION_AUTHORIZED is False
assert COVERAGE_CONTROL_ACTIVATED is False
assert FAITHFUL_PROMPT_ACTIVATED is False
assert EDITORIAL_POLICY_ACTIVATED is False
assert PROMPT_VERSION_202_ACTIVATED is False
assert SEMANTIC_GATE_202_ENABLED is False
assert HISTORICAL_GENERATOR_PROMPT == "book-generator-1.0.1"
assert HISTORICAL_GENERATOR_PROMPT_V10 == "book-generator-1.0"
assert HISTORICAL_SEMANTIC_CONTRACT == "book-semantic-validator-2.0.2-candidate"
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_H11_STATUS == "PARTIAL"
assert HISTORICAL_4B210_STATUS == "PASS"
assert HISTORICAL_4B211_STATUS == "PARTIAL"
assert HISTORICAL_4B212_STATUS == "PASS"
assert HISTORICAL_4B213_STATUS == "PASS"
assert HISTORICAL_4B214_STATUS == "PASS"
assert HISTORICAL_4B215_STATUS == "PARTIAL"
assert H11_HUMAN_LABEL == "UNSUPPORTED"
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert "CH001" in EXCLUDED_PILOT_CHAPTERS
assert "CH016" in EXCLUDED_PILOT_CHAPTERS
