"""Constantes 3B.7.7A.34 — preflight consolidation globale offline. 0 provider."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CURRENT_SRC_REFERENCE_POLICY_VERSION,
    SEMANTIC_TRANSPORT_VERSION_V3,
    SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE,
    SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION,
    WINDOW_ANALYSIS_PROMPT_VERSION_V140,
)
from app.source_analysis_thinking_contract.constants import (
    SELECTED_CONTRACT,
    SELECTED_THINKING_MODE,
)
from app.source_analysis_v31_src_canonicalization.constants import (
    A28_STATUS_UNCHANGED,
    A30_STATUS_UNCHANGED,
    A31_HISTORICAL_STATUS,
    A32_STATUS,
    EXPECTED_CANONICAL,
    INVENTORY_ARTIFACT as A33_INVENTORY_ARTIFACT,
    MALFORMED_TOKEN,
    POLICY_ARTIFACT as A33_POLICY_ARTIFACT,
    PROMOTION_ARTIFACT as A33_PROMOTION_ARTIFACT,
    PROTECTED_HISTORICAL as A33_PROTECTED_HISTORICAL,
    PROVENANCE_ARTIFACT as A33_PROVENANCE_ARTIFACT,
    READY_ARTIFACT as A33_READY_ARTIFACT,
    REPORT_NAME as A33_REPORT_NAME,
    REPLAY_ARTIFACT as A33_REPLAY_ARTIFACT,
    SCHEMA_ARTIFACT as A33_SCHEMA_ARTIFACT,
    SRC_POLICY_NEW,
    SRC_POLICY_OLD,
    TEST_DELTA_ARTIFACT as A33_TEST_DELTA_ARTIFACT,
    WIN007_COST_USD,
    WIN007_INPUT_TOKENS,
    WIN007_OUTPUT_TOKENS,
    WIN007_PROMOTION_LABEL,
    WIN007_REQUEST_ID,
    WINDOW_SPECS,
)
from app.source_analysis_v31_final_three.constants import WIN003_PROVENANCE
from app.source_analysis_v31_src_typo_forensics.constants import A28_STATUS

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.34"
MODE = "GLOBAL_CONSOLIDATION_OFFLINE_PREFLIGHT_AND_CONTRACT_FREEZE"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
REAL_CONSOLIDATION_CALLS = 0
CONSOLIDATION_AUTHORIZED = False
GRAMMAR_CANARY_AUTHORIZED = False
GRAMMAR_CANARY_REQUIRED = True
SOURCE_MAP_PUBLICATION_AUTHORIZED = False

A28_STATUS_PRESERVED = A28_STATUS_UNCHANGED
A30_STATUS_PRESERVED = A30_STATUS_UNCHANGED
A31_STATUS_PRESERVED = A31_HISTORICAL_STATUS
A32_STATUS_PRESERVED = A32_STATUS
A33_STATUS_PRESERVED = "PASS"
assert A28_STATUS_PRESERVED == A28_STATUS == "FAIL"
assert A30_STATUS_PRESERVED == "PASS"
assert A31_STATUS_PRESERVED == "FAIL"
assert A32_STATUS_PRESERVED == "PASS"
assert A33_STATUS_PRESERVED == "PASS"

READY_WINDOWS = (
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
)
READY_COUNT = 7
TOTAL_WINDOWS = 7
READY_LABEL = "7 / 7"
LOCAL_EXTRACTION_FREEZE_CANDIDATE = "YES"

FROZEN_PLANNER = CANDIDATE_PLANNER_VERSION
FROZEN_PROMPT = WINDOW_ANALYSIS_PROMPT_VERSION_V140
FROZEN_TRANSPORT = SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE
FROZEN_GRANULARITY = GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC
FROZEN_SRC_POLICY = SRC_REFERENCE_POLICY_VERSION_11_NARROW_CANONICALIZATION
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
HISTORICAL_V3_TRANSPORT = SEMANTIC_TRANSPORT_VERSION_V3
WIN001_PROMPT = "window-analysis-1.3.1"

assert FROZEN_PLANNER == "window-planner-v2.1-small"
assert FROZEN_PROMPT == "window-analysis-1.4.0"
assert FROZEN_TRANSPORT == "semantic-transport-v3.1-local-lite"
assert FROZEN_GRANULARITY == "window-granularity-1.2-kind-specific"
assert FROZEN_SRC_POLICY == "src-reference-policy-1.1-narrow-canonicalization"
assert PRODUCTION_PLANNER_VERSION == "window-planner-v2.0"
assert CURRENT_SRC_REFERENCE_POLICY_VERSION == FROZEN_SRC_POLICY

MIXED_PROVENANCE = {
    "WIN001": "historical V3 validated candidate",
    "WIN002": "V3.1 local-lite",
    "WIN003": "saved A.28 response revalidated A.30",
    "WIN004": "V3.1 local-lite A.27",
    "WIN005": "V3.1 local-lite A.31",
    "WIN006": "V3.1 local-lite A.31",
    "WIN007": (
        "saved A.31 response revalidated A.33 using derived SRC "
        "canonicalization"
    ),
}

WIN007_RAW_SRC = MALFORMED_TOKEN
WIN007_CANONICAL_SRC = EXPECTED_CANONICAL
assert WIN007_RAW_SRC == "SRec007337"
assert WIN007_CANONICAL_SRC == "SRC007337"

PROVIDER = "anthropic"
MODEL = "claude-sonnet-5"
FUTURE_COMPARISON_MODEL = "claude-opus-5"
CONTEXT_WINDOW_TOKENS = 1_000_000
MODEL_MAX_OUTPUT_TOKENS = 128_000
PROPOSED_MAX_OUTPUT = MAX_OUTPUT_TOKENS_FROZEN
assert PROPOSED_MAX_OUTPUT == 32000
assert SELECTED_THINKING_MODE == "disabled"

GLOBAL_PROMPT_VERSION = "global-consolidation-1.0"
GLOBAL_TRANSPORT_VERSION = "global-consolidation-transport-1.0"
GLOBAL_TRANSPORT_NOT_SOURCE_MAP = True

PROPOSED_ARCHITECTURE = "ONE_GLOBAL_CONSOLIDATION_CALL"
PROPOSED_THINKING_POLICY = "THINKING_DISABLED"
PROPOSED_RELATION_POLICY = "LOCAL_RELATIONS_AS_NON_AUTHORITATIVE_HINTS"
RELATION_POLICY_OPTION = "C"
RELATION_QUALITY_TECHNICAL_DEBT = "YES"
IDEA_KIND_POLICY = "KEEP_EMPTY_GLOBALLY"
IDEA_TEXT_REWRITE = "MINIMAL_EQUIVALENT_ONLY"
IMPORTANCE_POLICY = "PRESERVE_AS_EVIDENCE_THEN_REASSESS_AUDITABLY"
IDEA_DISPOSITION_COVERAGE_REQUIRED = 100

ALLOWED_IDEA_OPERATIONS = (
    "KEEP",
    "MERGE_EQUIVALENT",
    "LINK_RELATED",
    "REPRESENTED_AS_RELATION_OR_OTHER_APPROVED_OBJECT",
    "EXPLICITLY_DROPPED_WITH_REASON",
)
ALLOWED_DROP_REASONS = (
    "exact_duplicate",
    "transport_artifact",
    "non_substantive_fragment",
)
FORBIDDEN_DROP_REASONS = ("not_important",)
DISPOSITION_KINDS_REQUIRED = ("IDEA",)
DISPOSITION_KINDS_PREFERRED = (
    "TOPIC",
    "EXAMPLE",
    "REFERENCE",
    "UNCERTAINTY",
    "RELATION",
)

WINDOW_IS_NOT_CHAPTER = True
WINDOW_IS_NOT_SECTION = True
WINDOW_IS_NOT_EDITORIAL_UNIT = True

HISTORICAL_GLOBAL_TIMEOUTS = (3600, 7200)
CONSOLIDATION_CONNECT_TIMEOUT_SECONDS = 30.0
CONSOLIDATION_READ_TIMEOUT_SECONDS = 1800.0
CONSOLIDATION_MAX_ATTEMPTS = 1
CONSOLIDATION_RETRY = False

INPUT_COST_PER_1M = 2.00
OUTPUT_COST_PER_1M = 10.00
OPUS_INPUT_COST_PER_1M = 5.00
OPUS_OUTPUT_COST_PER_1M = 25.00

EXECUTION_ARTIFACTS = {
    "WIN001": "source_analysis_v3_hardened_win001_execution.json",
    "WIN002": "source_analysis_v31_WIN002_execution.json",
    "WIN003": "source_analysis_v31_WIN003_execution.json",
    "WIN004": "source_analysis_v31_win004_real_execution.json",
    "WIN005": "source_analysis_v31_WIN005_a31_execution.json",
    "WIN006": "source_analysis_v31_WIN006_a31_execution.json",
    "WIN007": "source_analysis_v31_WIN007_a31_execution.json",
}

NORMALIZED_ARTIFACT = "source_analysis_global_input_normalized.json"
INVENTORY_ARTIFACT = "source_analysis_global_input_inventory.json"
BOUNDARY_ARTIFACT = "source_analysis_cross_window_boundary_audit.json"
DUPLICATE_ARTIFACT = "source_analysis_cross_window_duplicate_candidates.json"
RELATION_POLICY_ARTIFACT = "source_analysis_global_relation_policy.json"
CONTRACT_ARTIFACT = "source_analysis_global_consolidation_contract.json"
TRANSPORT_SCHEMA_ARTIFACT = "source_analysis_global_consolidation_transport_schema.json"
BUDGET_ARTIFACT = "source_analysis_global_context_budget.json"
VALIDATOR_ARTIFACT = "source_analysis_global_consolidation_validator_contract.json"
REVIEW_PLAN_ARTIFACT = "source_analysis_global_semantic_review_plan.json"
FREEZE_ARTIFACT = "source_analysis_local_extraction_freeze.json"
READINESS_ARTIFACT = "source_analysis_global_consolidation_readiness.json"
TEST_DELTA_ARTIFACT = "source_analysis_a34_test_delta.json"
REPORT_NAME = "PHASE_3B77A34_GLOBAL_CONSOLIDATION_OFFLINE_PREFLIGHT_REPORT.md"

PROTECTED_A33 = (
    f"audit/{A33_REPORT_NAME}",
    f"audit/{A33_POLICY_ARTIFACT}",
    f"audit/{A33_REPLAY_ARTIFACT}",
    f"audit/{A33_PROVENANCE_ARTIFACT}",
    f"audit/{A33_PROMOTION_ARTIFACT}",
    f"audit/{A33_READY_ARTIFACT}",
    f"audit/{A33_INVENTORY_ARTIFACT}",
    f"audit/{A33_SCHEMA_ARTIFACT}",
    f"audit/{A33_TEST_DELTA_ARTIFACT}",
)
PROTECTED_HISTORICAL = tuple(A33_PROTECTED_HISTORICAL) + PROTECTED_A33

PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
NEXT_ACTION = "HUMAN REVIEW"
NEXT_PHASE = "HUMAN_REVIEW_THEN_GLOBAL_GRAMMAR_CANARY_IF_AUTHORIZED"

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_preflight.py",
    "app/tests/test_source_analysis_v31_global_preflight_audit.py",
)

assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert REAL_WINDOW_CALLS == 0
assert REAL_CONSOLIDATION_CALLS == 0
assert CONSOLIDATION_AUTHORIZED is False
assert GRAMMAR_CANARY_AUTHORIZED is False
assert not source_map_path(PROJECT_NAME).is_file() or SOURCE_MAP_STATUS == "NOT PUBLISHED"

__all__ = [
    "A28_STATUS_PRESERVED",
    "A30_STATUS_PRESERVED",
    "A31_STATUS_PRESERVED",
    "A32_STATUS_PRESERVED",
    "A33_INVENTORY_ARTIFACT",
    "A33_STATUS_PRESERVED",
    "ALLOWED_DROP_REASONS",
    "ALLOWED_IDEA_OPERATIONS",
    "BOUNDARY_ARTIFACT",
    "BUDGET_ARTIFACT",
    "CONSOLIDATION_AUTHORIZED",
    "CONSOLIDATION_CONNECT_TIMEOUT_SECONDS",
    "CONSOLIDATION_MAX_ATTEMPTS",
    "CONSOLIDATION_READ_TIMEOUT_SECONDS",
    "CONSOLIDATION_RETRY",
    "CONTEXT_WINDOW_TOKENS",
    "CONTRACT_ARTIFACT",
    "CURRENT_SRC_REFERENCE_POLICY_VERSION",
    "DISPOSITION_KINDS_PREFERRED",
    "DISPOSITION_KINDS_REQUIRED",
    "DUPLICATE_ARTIFACT",
    "EXECUTION_ARTIFACTS",
    "FOCUSED_TEST_PATHS",
    "FORBIDDEN_DROP_REASONS",
    "FREEZE_ARTIFACT",
    "FROZEN_GRANULARITY",
    "FROZEN_PLANNER",
    "FROZEN_PROMPT",
    "FROZEN_SRC_POLICY",
    "FROZEN_TRANSPORT",
    "FUTURE_COMPARISON_MODEL",
    "GLOBAL_PROMPT_VERSION",
    "GLOBAL_TRANSPORT_NOT_SOURCE_MAP",
    "GLOBAL_TRANSPORT_VERSION",
    "GRAMMAR_CANARY_AUTHORIZED",
    "GRAMMAR_CANARY_REQUIRED",
    "HISTORICAL_GLOBAL_TIMEOUTS",
    "HISTORICAL_V3_TRANSPORT",
    "IDEA_DISPOSITION_COVERAGE_REQUIRED",
    "IDEA_KIND_POLICY",
    "IDEA_TEXT_REWRITE",
    "IMPORTANCE_POLICY",
    "INPUT_COST_PER_1M",
    "INVENTORY_ARTIFACT",
    "LOCAL_EXTRACTION_FREEZE_CANDIDATE",
    "MALFORMED_TOKEN",
    "MIXED_PROVENANCE",
    "MODE",
    "MODEL",
    "MODEL_MAX_OUTPUT_TOKENS",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NORMALIZED_ARTIFACT",
    "OPUS_INPUT_COST_PER_1M",
    "OPUS_OUTPUT_COST_PER_1M",
    "OUTPUT_COST_PER_1M",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROPOSED_ARCHITECTURE",
    "PROPOSED_MAX_OUTPUT",
    "PROPOSED_RELATION_POLICY",
    "PROPOSED_THINKING_POLICY",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "READINESS_ARTIFACT",
    "READY_COUNT",
    "READY_LABEL",
    "READY_WINDOWS",
    "REAL_CONSOLIDATION_CALLS",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "RELATION_POLICY_ARTIFACT",
    "RELATION_POLICY_OPTION",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPORT_NAME",
    "REVIEW_PLAN_ARTIFACT",
    "SCHEMA_VERSION",
    "SELECTED_CONTRACT",
    "SELECTED_THINKING_MODE",
    "SOURCE_MAP_PUBLICATION_AUTHORIZED",
    "SOURCE_MAP_STATUS",
    "SRC_POLICY_NEW",
    "SRC_POLICY_OLD",
    "TEST_DELTA_ARTIFACT",
    "TOTAL_WINDOWS",
    "TRANSPORT_SCHEMA_ARTIFACT",
    "VALIDATOR_ARTIFACT",
    "WIN001_PROMPT",
    "WIN003_PROVENANCE",
    "WIN007_CANONICAL_SRC",
    "WIN007_COST_USD",
    "WIN007_INPUT_TOKENS",
    "WIN007_OUTPUT_TOKENS",
    "WIN007_PROMOTION_LABEL",
    "WIN007_RAW_SRC",
    "WIN007_REQUEST_ID",
    "WINDOW_IS_NOT_CHAPTER",
    "WINDOW_IS_NOT_EDITORIAL_UNIT",
    "WINDOW_IS_NOT_SECTION",
    "WINDOW_SPECS",
]
