"""Constantes 3B.7.7A.13 — canary V2 grammar + thinking-config. Isolé."""

from __future__ import annotations

from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    DEFERRED_KINDS,
    GRANULARITY_POLICY_VERSION,
    LOCAL_KINDS,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
    SEMANTIC_TRANSPORT_VERSION_V2,
    WINDOW_ANALYSIS_PROMPT_VERSION_V12,
)
from app.source_analysis_thinking_contract.constants import (
    AUTHORIZATION_SCOPE_SMALL_V21_V2_WIN001_ONLY,
    AUTHORIZATION_SCOPE_V2_GRAMMAR_CONFIG_CANARY_ONLY,
    SELECTED_CONTRACT,
    SELECTED_EFFORT,
    SELECTED_THINKING_MODE,
)

assert AUTHORIZATION_SCOPE_V2_GRAMMAR_CONFIG_CANARY_ONLY == (
    "V2_GRAMMAR_CONFIG_CANARY_ONLY"
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.13"
MODE = "V2_TINY_GRAMMAR_THINKING_CONFIG_CANARY"

CANARY_VERSION = "v2-grammar-thinking-canary-1.0"
PROVIDER = "anthropic"
MODEL = "claude-sonnet-5"
THINKING_CONTRACT = SELECTED_CONTRACT
THINKING_MODE = SELECTED_THINKING_MODE
EFFORT = SELECTED_EFFORT

AUTHORIZATION_SCOPE = AUTHORIZATION_SCOPE_V2_GRAMMAR_CONFIG_CANARY_ONLY
WIN001_SCOPE = AUTHORIZATION_SCOPE_SMALL_V21_V2_WIN001_ONLY

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False

# Conservative small canary allowance. Production V2 remains 32000.
CANARY_MAX_OUTPUT_TOKENS = 512
PRODUCTION_MAX_OUTPUT_TOKENS = MAX_OUTPUT_TOKENS_FROZEN

CANARY_CONNECT_TIMEOUT_SECONDS = 30.0
CANARY_READ_TIMEOUT_SECONDS = 120.0
HISTORICAL_READ_TIMEOUT_SECONDS = 7200.0
PRODUCTION_WINDOW_READ_TIMEOUT_SECONDS = 1800.0

EXPECTED_RAW_SCHEMA_BYTES = 559
EXPECTED_ADAPTED_SCHEMA_BYTES = 621

CANARY_WINDOW_ID = "WIN998"
CANARY_TRANSCRIPT_ID = "TR_CANARY_G"
SYNTHETIC_SRC_IDS = ("SRC999001", "SRC999002")
SYNTHETIC_TEXTS = (
    "The speaker says careful planning reduces avoidable mistakes.",
    "The speaker gives checking the plan twice as an example.",
)

FORBIDDEN_WINDOW_IDS = (
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
)
FORBIDDEN_TRANSCRIPT_IDS = ("TR001",)
PRODUCTION_SRC_PATTERN = r"^SRC\d{6}$"
PASTORAL_MARKERS = (
    "pastoral_retreat",
    "pastoral retreat",
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
    "SRC000001",
    "TR001",
)

STAGE_CANARY = "source_analysis_v2_grammar_canary"
CANARY_SUBDIR = "canary"
LOCK_NAME = "canary_real_call.lock"

EXECUTION_ARTIFACT = "source_analysis_v2_grammar_thinking_canary_execution.json"
PAYLOAD_ARTIFACT = "source_analysis_v2_grammar_thinking_canary_payload.json"
REPORT_NAME = "PHASE_3B77A13_V2_TINY_GRAMMAR_THINKING_CONFIG_CANARY_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION

__all__ = [
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "CANARY_CONNECT_TIMEOUT_SECONDS",
    "CANARY_MAX_OUTPUT_TOKENS",
    "CANARY_READ_TIMEOUT_SECONDS",
    "CANARY_SUBDIR",
    "CANARY_TRANSCRIPT_ID",
    "CANARY_VERSION",
    "CANARY_WINDOW_ID",
    "DEFERRED_KINDS",
    "EFFORT",
    "EXECUTION_ARTIFACT",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "FORBIDDEN_TRANSCRIPT_IDS",
    "FORBIDDEN_WINDOW_IDS",
    "GRANULARITY_POLICY_VERSION",
    "HISTORICAL_READ_TIMEOUT_SECONDS",
    "LOCAL_KINDS",
    "LOCK_NAME",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "PASTORAL_MARKERS",
    "PAYLOAD_ARTIFACT",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PRODUCTION_PLANNER_VERSION",
    "PRODUCTION_SRC_PATTERN",
    "PRODUCTION_WINDOW_READ_TIMEOUT_SECONDS",
    "PROJECT_NAME",
    "PROVIDER",
    "REPORT_NAME",
    "SCHEMA_VERSION",
    "SEMANTIC_TRANSPORT_VERSION_V2",
    "STAGE_CANARY",
    "SYNTHETIC_SRC_IDS",
    "SYNTHETIC_TEXTS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V12",
    "WIN001_SCOPE",
]
