"""Rapport markdown déterministe 3B.7.7A.13."""

from __future__ import annotations

from typing import Any, Mapping


def _yn(value: Any) -> str:
    if value is True or value == "YES":
        return "YES"
    if value is False or value == "NO":
        return "NO"
    if value is None:
        return "UNKNOWN"
    return str(value)


def _dash(value: Any) -> str:
    if value is None:
        return "UNKNOWN"
    return str(value)


def render_report(bundle: Mapping[str, Any]) -> str:
    h = bundle.get("header") or {}
    dry1 = bundle.get("dry_run_1") or {}
    dry2 = bundle.get("dry_run_2") or {}
    exe = bundle.get("execution") or {}
    audit = bundle.get("payload_audit") or {}
    schema = bundle.get("schema_metrics") or {}
    freeze = bundle.get("freeze") or {}
    fixture = bundle.get("fixture") or {}
    identity = audit.get("identity_fields") or {}
    cost = exe.get("cost") or {}
    files_created = bundle.get("files_created") or []
    files_modified = bundle.get("files_modified") or []
    tests = h.get("tests") or "UNKNOWN"

    lines = [
        "# PHASE 3B.7.7A.13 — V2 TINY GRAMMAR + THINKING-CONFIG CANARY",
        "",
        "## Result",
        "",
        str(h.get("result") or "UNKNOWN"),
        "",
        f"REAL PROVIDER CALLS = {h.get('real_provider_calls')}",
        "",
        "REAL WINDOW CALLS = 0",
        "",
        "PASTORAL CONTENT SENT = NO",
        "",
        f"AUTHORIZATION SCOPE = {h.get('authorization_scope')}",
        "",
        f"PROVIDER = {h.get('provider')}",
        "",
        f"MODEL = {h.get('model')}",
        "",
        "THINKING MODE = disabled",
        "",
        "EFFORT = omitted",
        "",
        "MANUAL BUDGET = absent",
        "",
        "V2 SCHEMA = semantic-transport-v2",
        "",
        f"RAW / ADAPTED SCHEMA = {h.get('raw_schema_bytes')} / {h.get('adapted_schema_bytes')}",
        "",
        f"SERVER GRAMMAR ACCEPTED = {h.get('server_grammar_accepted')}",
        "",
        f"THINKING DISABLED ACCEPTED = {h.get('thinking_disabled_accepted')}",
        "",
        f"HTTP STATUS = {_dash(h.get('http_status'))}",
        "",
        f"REQUEST ID = {_dash(h.get('request_id'))}",
        "",
        f"ACTUAL INPUT TOKENS = {_dash(h.get('input_tokens'))}",
        "",
        f"ACTUAL OUTPUT TOKENS = {_dash(h.get('output_tokens'))}",
        "",
        f"ACTUAL THINKING TOKENS = {_dash(h.get('thinking_tokens'))}",
        "",
        f"FINISH REASON = {_dash(h.get('finish_reason'))}",
        "",
        f"STRUCTURED PARSE = {h.get('structured_parse')}",
        "",
        f"V2 DECODER = {h.get('v2_decoder')}",
        "",
        f"V2 VALIDATOR = {h.get('v2_validator')}",
        "",
        f"CAPACITY SIGNAL = {h.get('capacity_signal')}",
        "",
        f"ACTUAL COST = {h.get('actual_cost')}",
        "",
        f"PROVIDER ELAPSED = {_dash(h.get('provider_elapsed'))}",
        "",
        f"FORENSICS = {_dash(h.get('forensics'))}",
        "",
        f"CANARY ARTIFACT ISOLATED = {h.get('canary_artifact_isolated')}",
        "",
        "REAL WINDOWS READY = 0 / 7",
        "",
        "SEMANTIC WIN001 AUTHORIZED = NO",
        "",
        "SOURCE MAP = NOT PUBLISHED",
        "",
        "PRODUCTION DEFAULT = window-planner-v2.0",
        "",
        "PHASE 3B = INCOMPLETE",
        "",
        f"TESTS = {tests}",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
        "## 1. Result",
        "",
        str(h.get("result") or "UNKNOWN"),
        "",
        f"Classification notes: {h.get('result_notes') or 'none'}",
        "",
        "## 2. Authorization",
        "",
        f"Scope required: V2_GRAMMAR_CONFIG_CANARY_ONLY",
        f"Scope used: {h.get('authorization_scope')}",
        "WIN001 authorization: NO",
        "Pastoral transcript authorization: NO",
        "",
        "## 3. Purpose",
        "",
        "Protocol/grammar/configuration canary only.",
        "Question answered: can Claude Sonnet 5 accept and return a valid",
        "structured semantic-transport-v2 response when thinking is explicitly disabled?",
        "This is NOT a semantic-quality test.",
        "",
        "## 4. Baseline",
        "",
        f"Pre-network baseline: {h.get('baseline') or 'see tests section'}",
        "If baseline had failed, no provider call would have been made.",
        "",
        "## 5. Historical freeze",
        "",
        f"window-analysis-1.0 unchanged: {_yn((freeze.get('integrity') or {}).get('prompt_1_0_unchanged'))}",
        f"window-analysis-1.1 unchanged: {_yn((freeze.get('integrity') or {}).get('prompt_1_1_unchanged'))}",
        f"semantic-transport-v1 / Generation C raw unchanged: {_yn((freeze.get('integrity') or {}).get('generation_c_raw_unchanged'))}",
        f"Generation C anthropic unchanged: {_yn((freeze.get('integrity') or {}).get('generation_c_anthropic_unchanged'))}",
        f"CLEAN unchanged: {_yn((freeze.get('integrity') or {}).get('clean_unchanged'))}",
        f"Historical provider_default thinking remains implicit (A.11 audit).",
        f"Production planner: {freeze.get('production_planner')}",
        "",
        "## 6. V2 contract",
        "",
        "prompt = window-analysis-1.2 (system prompt reused, not mutated)",
        "transport = semantic-transport-v2",
        "granularity = window-granularity-1.1-minimal",
        f"thinking contract = {THINKING_NOTE}",
        "",
        "## 7. Synthetic fixture",
        "",
        f"transcript_id = {fixture.get('transcript_id')}",
        f"window_id = {fixture.get('window_id')}",
        f"src_ids = {fixture.get('src_ids')}",
        f"fixture_hash = {fixture.get('fixture_hash')}",
        "Texts are synthetic planning/checking sentences. No pastoral content.",
        "",
        "## 8. Synthetic-only guard",
        "",
        "Fail-closed. Scope cannot receive pastoral_retreat CLEAN, WIN IDs,",
        "or production SRC###### content. Fixture builder is the only input.",
        f"Guard result: {_yn(h.get('synthetic_guard_passed'))}",
        "",
        "## 9. Prompt/wrapper",
        "",
        "window-analysis-1.2 system prompt is used unchanged.",
        "A dedicated tiny user wrapper asks for one TOPIC, one IDEA,",
        "optionally one EXAMPLE. Wrapper does not mutate 1.2 source.",
        f"wrapper_hash = {audit.get('wrapper_hash')}",
        "",
        "## 10. Schema",
        "",
        "semantic-transport-v2 generic records[] shape.",
        f"raw bytes = {schema.get('raw_bytes')}",
        f"adapted bytes = {schema.get('adapted_bytes')}",
        f"matches A.12/A.11 expected 559/621: {_yn(schema.get('matches_expected'))}",
        "",
        "## 11. Schema hashes",
        "",
        f"raw schema hash = {audit.get('raw_schema_hash')}",
        f"adapted schema hash = {audit.get('schema_hash')}",
        "",
        "## 12. Thinking contract",
        "",
        "Resolved: THINKING_DISABLED.",
        "Anthropic payload thinking = {\"type\": \"disabled\"}.",
        f"Observed thinking.type = {audit.get('thinking_type')}",
        "",
        "## 13. Effort",
        "",
        f"effort present in payload: {_yn(audit.get('effort_present'))}",
        "Required: ABSENT / omitted.",
        "",
        "## 14. Manual budget absence",
        "",
        f"budget_tokens present: {_yn(audit.get('budget_tokens_present'))}",
        "Required: ABSENT.",
        "",
        "## 15. Temperature",
        "",
        f"temperature present: {_yn(audit.get('temperature_present'))}",
        "Sonnet 5 payload builder omits temperature. Required: ABSENT.",
        "",
        "## 16. max_tokens",
        "",
        f"canary max_tokens = {audit.get('max_tokens')}",
        "Production V2 max_output remains 32000. Canary uses 512 —",
        "smallest conservative allowance that can contain a tiny valid transport.",
        "",
        "## 17. Timeout",
        "",
        "connect = 30 s, read = 120 s.",
        "Does not inherit 7200 s. Does not require production 1800 s.",
        "Bounded canary-specific timeout for a tiny structured response.",
        "",
        "## 18. Retry policy",
        "",
        "RetryPolicy.max_attempts = 1, base_delay = 0.",
        "No requests Session retry. No SDK. No engine fallback.",
        "Failed attempt consumes authorization.",
        "",
        "## 19. Request identity",
        "",
        f"request_identity = {audit.get('request_identity')}",
        f"identity fields = {identity}",
        "",
        "## 20. Cache isolation",
        "",
        "No production window result cache is read or written.",
        "Canary artifacts live under audit/canary/ only.",
        "",
        "## 21. Forensic identity",
        "",
        f"window_id = WIN998 (synthetic canary — not WIN001–WIN007)",
        f"analysis_signature = {audit.get('request_identity')}",
        f"forensic path = {_dash(h.get('forensics'))}",
        "Provider-boundary forensics captured before interpretation.",
        "",
        "## 22. Dry run #1",
        "",
        f"command = {bundle.get('dry_run_command')}",
        f"request_identity = {dry1.get('request_identity')}",
        f"schema_hash = {dry1.get('schema_hash')}",
        f"fixture_hash = {dry1.get('synthetic_fixture_hash')}",
        f"provider calls = {dry1.get('actual_real_provider_calls', 0)}",
        "",
        "## 23. Dry run #2",
        "",
        f"command = {bundle.get('dry_run_command')}",
        f"request_identity = {dry2.get('request_identity')}",
        f"schema_hash = {dry2.get('schema_hash')}",
        f"fixture_hash = {dry2.get('synthetic_fixture_hash')}",
        f"provider calls = {dry2.get('actual_real_provider_calls', 0)}",
        "",
        "## 24. Determinism",
        "",
        f"same request identity: {_yn(dry1.get('request_identity') == dry2.get('request_identity') and bool(dry1.get('request_identity')))}",
        f"same schema hash: {_yn(dry1.get('schema_hash') == dry2.get('schema_hash') and bool(dry1.get('schema_hash')))}",
        f"same fixture hash: {_yn(dry1.get('synthetic_fixture_hash') == dry2.get('synthetic_fixture_hash') and bool(dry1.get('synthetic_fixture_hash')))}",
        "provider calls on dry runs = 0",
        "",
        "## 25. Payload audit",
        "",
        f"model = {audit.get('model')}",
        f"max_tokens = {audit.get('max_tokens')}",
        f"thinking.type = {audit.get('thinking_type')}",
        f"effort = {'PRESENT' if audit.get('effort_present') else 'ABSENT'}",
        f"temperature = {'PRESENT' if audit.get('temperature_present') else 'ABSENT'}",
        f"output_config = {_yn(audit.get('output_config_present'))}",
        f"format type = {audit.get('format_type')}",
        f"schema hash = {audit.get('schema_hash')}",
        f"message count = {audit.get('message_count')}",
        f"system present = {_yn(audit.get('system_present'))}",
        f"synthetic input hash = {audit.get('synthetic_input_hash')}",
        "No secret values.",
        "",
        "## 26. Final gate",
        "",
        f"tests green before call: {_yn(h.get('pre_call_tests_green'))}",
        f"dry run green: {_yn(h.get('dry_run_green'))}",
        f"payload audit green: {_yn(h.get('payload_audit_green'))}",
        f"credential available: {_yn(h.get('credential_available'))}",
        f"synthetic-only guard green: {_yn(h.get('synthetic_guard_passed'))}",
        f"forensics ready: {_yn(h.get('forensics_ready'))}",
        f"call budget verified: {_yn(h.get('call_budget_verified'))}",
        "",
        "## 27. Real execution",
        "",
        f"command = {bundle.get('real_command')}",
        f"executed once: {_yn(h.get('executed_once'))}",
        f"error = {_dash(exe.get('error') if 'error' in exe else h.get('execution_error'))}",
        "",
        "## 28. Call accounting",
        "",
        f"engine.generate attempts = {h.get('engine_generate_attempts')}",
        f"Anthropic POST attempts = {h.get('anthropic_post_attempts')}",
        "Retry = NO. Fallback = NO.",
        "",
        "## 29. HTTP",
        "",
        f"response received = {_yn(exe.get('response_received'))}",
        f"HTTP status = {_dash(h.get('http_status'))}",
        f"request id = {_dash(h.get('request_id'))}",
        f"elapsed = {_dash(h.get('provider_elapsed'))}",
        "",
        "## 30. Provider envelope",
        "",
        f"provider envelope valid = {_yn((exe.get('http') or {}).get('provider_envelope_valid') or exe.get('airesponse_created'))}",
        f"AIResponse created = {_yn(exe.get('airesponse_created'))}",
        "",
        "## 31. Grammar acceptance",
        "",
        f"V2_SERVER_GRAMMAR_ACCEPTED = {h.get('server_grammar_accepted')}",
        "Inferred only from HTTP/provider success or explicit schema rejection.",
        "",
        "## 32. Thinking-disabled acceptance",
        "",
        f"THINKING_DISABLED_ACCEPTED = {h.get('thinking_disabled_accepted')}",
        "",
        "## 33. Usage",
        "",
        f"input tokens = {_dash(h.get('input_tokens'))}",
        f"output tokens = {_dash(h.get('output_tokens'))}",
        "Unknown is reported as UNKNOWN, never silently zero.",
        "",
        "## 34. Thinking usage",
        "",
        f"thinking tokens = {_dash(h.get('thinking_tokens'))}",
        f"thinking tokens field reported by provider = {_yn(exe.get('thinking_tokens_reported'))}",
        "If thinking is truly disabled, expected 0 or absent per provider semantics.",
        "",
        "## 35. Finish reason",
        "",
        f"finish_reason = {_dash(h.get('finish_reason'))}",
        "",
        "## 36. Structured parse",
        "",
        f"{h.get('structured_parse')}",
        "Existing structured parser. No repair. No retry.",
        "",
        "## 37. V2 decoder",
        "",
        f"{h.get('v2_decoder')}",
        "",
        "## 38. V2 validator",
        "",
        f"{h.get('v2_validator')}",
        "",
        "## 39. Record kinds",
        "",
        f"{exe.get('kinds')}",
        "Allowed: TOPIC, IDEA, RELATION, EXAMPLE, REFERENCE, UNCERTAINTY.",
        "",
        "## 40. Synthetic refs",
        "",
        f"{exe.get('source_refs')}",
        "Only SRC_TEST001 / SRC_TEST002 allowed.",
        "",
        "## 41. Deferred kinds",
        "",
        f"{exe.get('deferred_kinds') or []}",
        "REPETITION / VOICE / INTENT_KIND / AUDIENCE_KIND must be absent.",
        "",
        "## 42. Capacity signal",
        "",
        f"{h.get('capacity_signal')}",
        "analysis_capacity_exceeded is unexpected on this tiny fixture.",
        "",
        "## 43. Result isolation",
        "",
        f"canary artifact isolated = {h.get('canary_artifact_isolated')}",
        "Stored under audit/canary and audit/*.canary* only.",
        "No analysis/windows/WIN001. No production transport/result.",
        "",
        "## 44. Production isolation",
        "",
        f"source_map published = {_yn(freeze.get('source_map_present'))}",
        f"production windows touched = {_yn(freeze.get('production_windows_touched'))}",
        "REAL WINDOWS READY = 0 / 7",
        "",
        "## 45. Project state",
        "",
        f"status = {(freeze.get('project_state') or {}).get('status')}",
        f"not SUCCESS = {_yn((freeze.get('project_state') or {}).get('not_success'))}",
        "",
        "## 46. Cost",
        "",
        f"actual cost = {h.get('actual_cost')}",
        f"cost status = {cost.get('status')}",
        "If usage unavailable: UNKNOWN. Not inferred as zero.",
        "",
        "## 47. Tests",
        "",
        f"{tests}",
        "Post-call suite used no_ai_network. No network from tests.",
        "",
        "## 48. Files created",
        "",
        *([f"- {path}" for path in files_created] or ["- (none)"]),
        "",
        "## 49. Files modified",
        "",
        *([f"- {path}" for path in files_modified] or ["- (none)"]),
        "",
        "## 50. What PASS proves",
        "",
        "Server accepts V2 grammar/config.",
        "thinking-disabled request works technically.",
        "A tiny V2 structured response can be parsed and validated.",
        "",
        "## 51. What PASS does not prove",
        "",
        "Semantic quality on the pastoral transcript.",
        "Quality equivalence vs adaptive-low.",
        "That all seven windows will succeed.",
        "That WIN001 will fit.",
        "That consolidation will succeed.",
        "Phase 3B completion.",
        "",
        "## 52. Human decision required",
        "",
        "Review this canary. Do not treat technical eligibility as authorization.",
        "Semantic WIN001 remains unauthorized until a future human prompt.",
        "STOP. Wait for human review.",
        "",
        "## Required questions",
        "",
        f"Were any pastoral SRCs sent? NO",
        f"Was WIN001 called? NO",
        f"How many Anthropic POSTs occurred? {h.get('anthropic_post_attempts')}",
        f"Was the V2 schema accepted server-side? {h.get('server_grammar_accepted')}",
        f"Was thinking disabled accepted? {h.get('thinking_disabled_accepted')}",
        f"Was effort omitted? {_yn(not audit.get('effort_present'))}",
        f"Was budget_tokens absent? {_yn(not audit.get('budget_tokens_present'))}",
        f"Was task_budget absent? {_yn(not audit.get('task_budget_present'))}",
        f"Was output_config.format preserved? {_yn(audit.get('format_present'))}",
        f"Were thinking tokens actually absent/zero according to provider evidence? {_dash(h.get('thinking_tokens'))}",
        f"What was finish_reason? {_dash(h.get('finish_reason'))}",
        f"Did structured parsing pass? {h.get('structured_parse')}",
        f"Did V2 decoder pass? {h.get('v2_decoder')}",
        f"Did V2 validator pass? {h.get('v2_validator')}",
        f"Were only synthetic refs returned? {_yn(h.get('synthetic_refs_only'))}",
        f"Were deferred kinds absent? {_yn(not (exe.get('deferred_kinds') or []))}",
        f"Was capacity signal absent? {_yn(h.get('capacity_signal') == 'absent')}",
        f"Was result isolated from production? {h.get('canary_artifact_isolated')}",
        f"Did any real window become READY? NO",
        f"Was source_map published? NO",
        f"Was production planner changed? NO",
        f"Did full suite pass? {tests}",
        f"What actual cost was incurred? {h.get('actual_cost')}",
        f"Is semantic WIN001 now technically eligible for a FUTURE human authorization? {h.get('win001_technically_eligible')}",
        "Do NOT interpret eligibility as authorization.",
        "",
    ]
    return "\n".join(lines) + "\n"


THINKING_NOTE = "THINKING_DISABLED"


def header_from_result(result, *, extra: Mapping[str, Any] | None = None) -> dict[str, Any]:
    exe = result.execution or {}
    schema = result.schema_metrics or {}
    cost = (exe.get("cost") or {})
    payload = {
        "result": exe.get("result") or result.mode,
        "real_provider_calls": result.anthropic_post_attempts,
        "authorization_scope": result.authorization_scope,
        "provider": "anthropic",
        "model": "claude-sonnet-5",
        "raw_schema_bytes": schema.get("raw_bytes"),
        "adapted_schema_bytes": schema.get("adapted_bytes"),
        "server_grammar_accepted": exe.get("server_grammar_accepted", "NO"),
        "thinking_disabled_accepted": exe.get("thinking_disabled_accepted", "NO"),
        "http_status": exe.get("http_status"),
        "request_id": exe.get("request_id"),
        "input_tokens": exe.get("input_tokens"),
        "output_tokens": exe.get("output_tokens"),
        "thinking_tokens": exe.get("thinking_tokens"),
        "finish_reason": exe.get("finish_reason"),
        "structured_parse": exe.get("structured_parse", "n/a"),
        "v2_decoder": exe.get("v2_decoder", "n/a"),
        "v2_validator": exe.get("v2_validator", "n/a"),
        "capacity_signal": exe.get("capacity_signal", "n/a"),
        "actual_cost": cost.get("display", "UNKNOWN"),
        "provider_elapsed": exe.get("provider_elapsed_ms"),
        "forensics": exe.get("forensic_path"),
        "canary_artifact_isolated": "YES" if exe.get("canary_artifact_isolated") else (
            "YES" if result.mode == "DRY_RUN" else "NO"
        ),
        "engine_generate_attempts": result.engine_generate_attempts,
        "anthropic_post_attempts": result.anthropic_post_attempts,
        "synthetic_guard_passed": True,
        "synthetic_refs_only": all(
            str(ref) in ("SRC999001", "SRC999002")
            for ref in (exe.get("source_refs") or [])
        )
        if exe
        else True,
        "execution_error": result.error,
        "win001_technically_eligible": (
            "YES — future human authorization only"
            if exe.get("result") == "PASS"
            else "NO"
        ),
    }
    if extra:
        payload.update(dict(extra))
    return payload


def bundle_from_result(
    result,
    *,
    dry_run_1: Mapping[str, Any] | None = None,
    dry_run_2: Mapping[str, Any] | None = None,
    extra_header: Mapping[str, Any] | None = None,
    files_created: list[str] | None = None,
    files_modified: list[str] | None = None,
    dry_run_command: str | None = None,
    real_command: str | None = None,
) -> dict[str, Any]:
    return {
        "header": header_from_result(result, extra=extra_header),
        "dry_run_1": dict(dry_run_1 or result.dry_run or {}),
        "dry_run_2": dict(dry_run_2 or {}),
        "execution": result.execution,
        "payload_audit": result.payload_audit,
        "schema_metrics": result.schema_metrics,
        "freeze": result.freeze,
        "fixture": (result.dry_run or {}).get("fixture") or {},
        "files_created": list(files_created or []),
        "files_modified": list(files_modified or []),
        "dry_run_command": dry_run_command,
        "real_command": real_command,
    }


__all__ = ["bundle_from_result", "header_from_result", "render_report"]
