"""Phase 4B.2.5 — one real Terra semantic-gate benchmark canary."""

from app.book_semantic_gate_4b25.constants import (
    AUTHORIZED_REMOTE_TERRA_INVOCATIONS,
    AUTHORIZED_SONNET_CALLS,
    HISTORICAL_4B241_STATUS,
    HISTORICAL_4B24_STATUS,
    PHASE,
)

assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert HISTORICAL_4B24_STATUS == "FAIL"
assert HISTORICAL_4B241_STATUS == "PASS"

__all__ = [
    "PHASE",
    "AUTHORIZED_REMOTE_TERRA_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B241_STATUS",
]
