"""
Phase 4B.2.5 — One real Terra semantic-gate benchmark canary.

NEW explicit authorization. MAX_REMOTE_TERRA_INVOCATIONS = 1.
Does not retroactively alter the consumed 4B.2.4 authorization.
Historical 4B.2.4 remains FAIL. Historical 4B.2.4.1 remains PASS.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    HISTORICAL_4B21_STATUS,
    HISTORICAL_4B22_STATUS,
    HISTORICAL_4B2_STATUS,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
)
from app.book_semantic_gate_4b24.constants import (
    EXPECTED_BENCHMARK_FILE_SHA256,
    EXPECTED_NEGATIVE_CASES,
    EXPECTED_POSITIVE_CASES,
    EXPECTED_REQUEST_SHA256,
    EXPECTED_SCORED_CASES,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b241.constants import (
    CANONICAL_DEPENDENCY_MECHANISM,
    CANONICAL_PYTHON_ENV,
    OPENAI_SDK_CONSTRAINT,
)

PHASE = "4B.2.5"
PHASE_NAME = "ONE_REAL_TERRA_SEMANTIC_GATE_BENCHMARK_CANARY"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B25_ONE_REAL_TERRA_HISTORICAL_BENCHMARK_CANARY_ONLY"
)
AUTHORIZED_REMOTE_TERRA_INVOCATIONS = 1
AUTHORIZED_SONNET_CALLS = 0
MAX_ENGINE_GENERATE = 1
MAX_REMOTE_INVOCATIONS = 1
RETRIES = 0
FALLBACKS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = True

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
STAGE_CANARY = "book_semantic_validation_canary_4b25"
PROMPT_VERSION = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION = SEMANTIC_VALIDATION_TRANSPORT_VERSION
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert PROMPT_VERSION == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION == "book-semantic-validation-transport-1.0"
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"

HISTORICAL_4B23_STATUS = "PASS"
HISTORICAL_4B24_STATUS = "FAIL"
HISTORICAL_4B241_STATUS = "PASS"

assert HISTORICAL_4B2_STATUS == "FAIL"
assert HISTORICAL_4B21_STATUS == "PASS"
assert HISTORICAL_4B22_STATUS == "PARTIAL"
assert HISTORICAL_4B23_STATUS == "PASS"
assert HISTORICAL_4B24_STATUS == "FAIL"
assert HISTORICAL_4B241_STATUS == "PASS"

EXPECTED_REQUEST_SHA256_FROZEN = EXPECTED_REQUEST_SHA256
assert EXPECTED_REQUEST_SHA256_FROZEN == (
    "09d6472e544bc60231c77908e6608ff7ee7b6fd4746317f206301082e21eab53"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)

CANONICAL_PYTHON_EXECUTABLE = r"C:\TranscriptionAI\.venv\Scripts\python.exe"
EXPECTED_OPENAI_SDK_VERSION = "2.43.0"
EXPECTED_PYTHON_VERSION = (3, 11, 9)

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 300.0
CANARY_WINDOW_ID = "book-semantic-gate-4b25"

AUDIT_DIRNAME = "book_semantic_gate_4b25"
AUDIT_REAL_PARENT = "real"
AUDIT_PRECALL = "book_semantic_gate_4b25_precall.json"
AUDIT_RUNTIME = "book_semantic_gate_4b25_runtime.json"
AUDIT_REQUEST = "book_semantic_gate_4b25_request_identity.json"
AUDIT_ACCOUNTING = "book_semantic_gate_4b25_call_accounting.json"
AUDIT_PROVIDER = "book_semantic_gate_4b25_provider_evidence.json"
AUDIT_VALIDATION = "book_semantic_gate_4b25_response_validation.json"
AUDIT_CASES = "book_semantic_gate_4b25_case_results.json"
AUDIT_SCORE = "book_semantic_gate_4b25_benchmark_score.json"
AUDIT_HUMAN = "book_semantic_gate_4b25_human_review.json"
AUDIT_COST = "book_semantic_gate_4b25_cost.json"
AUDIT_READINESS = "book_semantic_gate_post_4b25_readiness.json"
AUDIT_RAW_RESPONSE = "book_semantic_gate_4b25_raw_structured_response.json"
AUDIT_RAW_TEXT = "book_semantic_gate_4b25_raw_provider_text.txt"
AUDIT_LOCK = "book_semantic_gate_4b25_real_call.lock"
AUDIT_TESTS = "book_semantic_gate_4b25_tests.json"
AUDIT_INDEX = "book_semantic_gate_4b25_index.json"
REPORT_NAME = "PHASE_4B25_ONE_REAL_TERRA_SEMANTIC_GATE_BENCHMARK_CANARY_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_FULL_REAL_BOOK_GENERATION = False

assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert PUBLICATION_AUTHORIZED is False
assert READY_FOR_FULL_REAL_BOOK_GENERATION is False

__all__ = [
    "AUDIT_ACCOUNTING",
    "AUDIT_CASES",
    "AUDIT_COST",
    "AUDIT_DIRNAME",
    "AUDIT_HUMAN",
    "AUDIT_INDEX",
    "AUDIT_LOCK",
    "AUDIT_PRECALL",
    "AUDIT_PROVIDER",
    "AUDIT_RAW_RESPONSE",
    "AUDIT_RAW_TEXT",
    "AUDIT_READINESS",
    "AUDIT_REAL_PARENT",
    "AUDIT_REQUEST",
    "AUDIT_RUNTIME",
    "AUDIT_SCORE",
    "AUDIT_TESTS",
    "AUDIT_VALIDATION",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_REMOTE_TERRA_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "CANARY_WINDOW_ID",
    "CANONICAL_DEPENDENCY_MECHANISM",
    "CANONICAL_PYTHON_ENV",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CONNECT_TIMEOUT_SECONDS",
    "CONSERVATIVE_MAX_OUTPUT_TOKENS",
    "EXPECTED_BENCHMARK_FILE_SHA256",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_NEGATIVE_CASES",
    "EXPECTED_OPENAI_SDK_VERSION",
    "EXPECTED_POSITIVE_CASES",
    "EXPECTED_PYTHON_VERSION",
    "EXPECTED_REQUEST_SHA256",
    "EXPECTED_REQUEST_SHA256_FROZEN",
    "EXPECTED_SCORED_CASES",
    "EXPECTED_SOURCE_MAP",
    "FALLBACKS",
    "HISTORICAL_4B21_STATUS",
    "HISTORICAL_4B22_STATUS",
    "HISTORICAL_4B23_STATUS",
    "HISTORICAL_4B241_STATUS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B2_STATUS",
    "MAX_ENGINE_GENERATE",
    "MAX_REMOTE_INVOCATIONS",
    "MODEL",
    "NEXT_ACTION",
    "OPENAI_SDK_CONSTRAINT",
    "OUTPUT_MODE",
    "PHASE",
    "PHASE_NAME",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROVIDER",
    "PUBLICATION_AUTHORIZED",
    "READ_TIMEOUT_SECONDS",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "REPORT_NAME",
    "RETRIES",
    "SCORED_CASE_ORDER",
    "STAGE_CANARY",
    "TEMPERATURE_POLICY",
    "TERRA_EXECUTION_AUTHORIZED",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
]
