"""4B.2.5 human-readable report."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None or value == "":
        return "—"
    return str(value)


def render_report(bundle: Mapping[str, Any]) -> str:
    header = dict(bundle.get("header") or {})
    lines = [
        "# PHASE 4B.2.5 — ONE REAL TERRA SEMANTIC-GATE BENCHMARK CANARY",
        "",
        "## Result",
        "",
        _dash(header.get("result")),
        "",
        "HISTORICAL 4B.2.4 =",
        "FAIL",
        "",
        "4B.2.4.1 =",
        "PASS",
        "",
        "AUTHORIZED REMOTE TERRA INVOCATIONS =",
        "1",
        "",
        "EXECUTION ATTEMPTS =",
        _dash(header.get("execution_attempts")),
        "",
        "REMOTE INVOCATIONS =",
        _dash(header.get("remote_invocations")),
        "",
        "HTTP REQUESTS =",
        _dash(header.get("http_requests")),
        "",
        "PROVIDER RESPONSES =",
        _dash(header.get("provider_responses")),
        "",
        "SONNET CALLS =",
        "0",
        "",
        "RETRIES =",
        "0",
        "",
        "FALLBACKS =",
        "0",
        "",
        "PYTHON EXECUTABLE =",
        _dash(header.get("python_executable")),
        "",
        "OPENAI SDK VERSION =",
        _dash(header.get("openai_sdk_version")),
        "",
        "PROVIDER READINESS =",
        _dash(header.get("provider_readiness")),
        "",
        "SOURCE MAP SHA =",
        _dash(header.get("source_map_sha")),
        "",
        "EDITORIAL PLAN SHA =",
        _dash(header.get("editorial_plan_sha")),
        "",
        "CLEAN TRANSCRIPT SHA =",
        _dash(header.get("clean_transcript_sha")),
        "",
        "BENCHMARK IDENTITY =",
        _dash(header.get("benchmark_identity")),
        "",
        "REQUEST SHA256 =",
        _dash(header.get("request_sha256")),
        "",
        "REQUEST DETERMINISM =",
        _dash(header.get("request_determinism")),
        "",
        "LABEL LEAKAGE =",
        _dash(header.get("label_leakage")),
        "",
        "CONTEXT SAFETY =",
        _dash(header.get("context_safety")),
        "",
        "LONG-CONTEXT =",
        _dash(header.get("long_context")),
        "",
        "ESTIMATED COST =",
        _dash(header.get("estimated_cost")),
        "",
        "HTTP / FINISH =",
        _dash(header.get("http_finish")),
        "",
        "REQUEST ID =",
        _dash(header.get("request_id")),
        "",
        "INPUT TOKENS =",
        _dash(header.get("input_tokens")),
        "",
        "OUTPUT TOKENS =",
        _dash(header.get("output_tokens")),
        "",
        "REASONING TOKENS =",
        _dash(header.get("reasoning_tokens")),
        "",
        "ACTUAL COST =",
        _dash(header.get("actual_cost")),
        "",
        "JSON PARSE =",
        _dash(header.get("json_parse")),
        "",
        "TRANSPORT =",
        _dash(header.get("transport_decode")),
        "",
        "CASE COVERAGE =",
        _dash(header.get("case_coverage")),
        "",
        "SPAN / CLAIM COVERAGE =",
        _dash(header.get("span_claim_coverage")),
        "",
        "POSITIVE ACCEPTED =",
        _dash(header.get("positive_accepted")),
        "",
        "POSITIVE FALSE REJECTIONS =",
        _dash(header.get("positive_false_rejections")),
        "",
        "NEGATIVE BLOCKED =",
        _dash(header.get("negative_blocked")),
        "",
        "NEGATIVE FALSE NEGATIVES =",
        _dash(header.get("negative_false_negatives")),
        "",
        "FUNERAL =",
        _dash(header.get("funeral_case")),
        "",
        "CONNECTIVE =",
        _dash(header.get("connective_case")),
        "",
        "P3 =",
        _dash(header.get("p3_case")),
        "",
        "P8 =",
        _dash(header.get("p8_case")),
        "",
        "EXTERNAL-KNOWLEDGE RESISTANCE =",
        _dash(header.get("external_knowledge_resistance")),
        "",
        "REASON-CODE COMPATIBILITY =",
        _dash(header.get("reason_code_compatible")),
        "",
        "DETERMINISTIC REPLAY =",
        _dash(header.get("deterministic_replay")),
        "",
        "FOCUSED TESTS =",
        _dash(header.get("tests")),
        "",
        "PRODUCTION CACHE =",
        "UNCHANGED",
        "",
        "book.json =",
        "NOT PUBLISHED",
        "",
        "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT =",
        _dash(header.get("ready_for_book_generator_production_preflight")),
        "",
        "READY_FOR_FULL_REAL_BOOK_GENERATION =",
        "NO",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## Historical status",
        "",
        "4B.2 = FAIL",
        "4B.2.1 = PASS",
        "4B.2.2 = PARTIAL",
        "4B.2.3 = PASS",
        "4B.2.4 = FAIL",
        "4B.2.4.1 = PASS",
        "",
        "Do not rewrite any historical result.",
        "",
        "## Notes",
        "",
        _dash(header.get("notes")),
        "",
        "10 cases are an engineering canary, not a statistical model-quality benchmark.",
        "",
        "book-generator-1.0.1 remains SUFFICIENT_WITH_SEMANTIC_GATE unless new evidence materially requires reassessment.",
        "",
        "Wait for human review.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
