"""
Phase 4B.2.4.1 — OpenAI runtime remediation + provider preflight.

Offline only. Zero provider calls. Historical 4B.2.4 remains FAIL.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b24.constants import (
    EXPECTED_BENCHMARK_FILE_SHA256,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_REQUEST_SHA256,
    EXPECTED_SOURCE_MAP,
    HISTORICAL_4B21_STATUS,
    HISTORICAL_4B22_STATUS,
    HISTORICAL_4B2_STATUS,
    MODEL,
    OUTPUT_MODE,
    PROVIDER,
)

PHASE = "4B.2.4.1"
PHASE_NAME = "OPENAI_RUNTIME_REMEDIATION_AND_PROVIDER_PREFLIGHT"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

HISTORICAL_4B24_STATUS = "FAIL"
HISTORICAL_4B23_STATUS = "PASS"

AUTHORIZATION_SCOPE = "BOOK_SEMANTIC_GATE_4B241_OFFLINE_RUNTIME_REMEDIATION_ONLY"
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False

CANONICAL_PYTHON_ENV = ".venv"
CANONICAL_PYTHON_EXECUTABLE = r".venv\Scripts\python.exe"
CANONICAL_DEPENDENCY_MECHANISM = "requirements.txt"
OPENAI_SDK_CONSTRAINT = "openai>=1.0.0,<3"
OPENAI_SDK_MIN_MAJOR = 1

EXPECTED_REQUEST_SHA256_FROZEN = EXPECTED_REQUEST_SHA256
assert EXPECTED_REQUEST_SHA256_FROZEN == (
    "09d6472e544bc60231c77908e6608ff7ee7b6fd4746317f206301082e21eab53"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert OUTPUT_MODE == "json_object"
assert HISTORICAL_4B2_STATUS == "FAIL"
assert HISTORICAL_4B21_STATUS == "PASS"
assert HISTORICAL_4B22_STATUS == "PARTIAL"

AUDIT_DIRNAME = "book_semantic_gate_4b241"
AUDIT_FORENSICS = "openai_runtime_forensics.json"
AUDIT_DEPENDENCY = "openai_dependency_remediation.json"
AUDIT_READINESS = "openai_provider_readiness.json"
AUDIT_LOCK = "provider_one_shot_lock_forensics.json"
AUDIT_PREFLIGHT_DESIGN = "provider_runtime_preflight_design.json"
AUDIT_REQUEST = "terra_request_identity_regression.json"
AUDIT_TESTS = "book_semantic_gate_4b241_tests.json"
AUDIT_POST_READINESS = "book_semantic_gate_post_4b241_readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b241_index.json"
REPORT_NAME = "PHASE_4B241_OPENAI_RUNTIME_REMEDIATION_AND_PROVIDER_PREFLIGHT_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False

__all__ = [
    "AUDIT_DEPENDENCY",
    "AUDIT_DIRNAME",
    "AUDIT_FORENSICS",
    "AUDIT_INDEX",
    "AUDIT_LOCK",
    "AUDIT_POST_READINESS",
    "AUDIT_PREFLIGHT_DESIGN",
    "AUDIT_READINESS",
    "AUDIT_REQUEST",
    "AUDIT_TESTS",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "CANONICAL_DEPENDENCY_MECHANISM",
    "CANONICAL_PYTHON_ENV",
    "CANONICAL_PYTHON_EXECUTABLE",
    "EXPECTED_BENCHMARK_FILE_SHA256",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_REQUEST_SHA256",
    "EXPECTED_REQUEST_SHA256_FROZEN",
    "EXPECTED_SOURCE_MAP",
    "HISTORICAL_4B21_STATUS",
    "HISTORICAL_4B22_STATUS",
    "HISTORICAL_4B23_STATUS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B2_STATUS",
    "MODEL",
    "NEXT_ACTION",
    "OPENAI_SDK_CONSTRAINT",
    "OPENAI_SDK_MIN_MAJOR",
    "OUTPUT_MODE",
    "PHASE",
    "PHASE_NAME",
    "PROJECT_NAME",
    "PROVIDER",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "REPORT_NAME",
    "TERRA_EXECUTION_AUTHORIZED",
]
