"""4B.2.4.1 report renderer. No secrets."""

from __future__ import annotations

from typing import Any, Mapping


def _yn(value: Any) -> str:
    if value in (True, "YES", "PASS", "yes", "pass"):
        return "YES"
    if value in (False, "NO", "FAIL", "no", "fail"):
        return "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any]) -> str:
    header = dict(bundle.get("header") or {})
    lines = [
        "# PHASE 4B.2.4.1 — OPENAI RUNTIME REMEDIATION + PROVIDER PREFLIGHT",
        "",
        "## Result",
        "",
        str(header.get("result") or "FAIL"),
        "",
        f"REAL PROVIDER CALLS =",
        str(header.get("real_provider_calls") if header.get("real_provider_calls") is not None else 0),
        "",
        f"OPENAI HTTP REQUESTS =",
        str(header.get("openai_http_requests") if header.get("openai_http_requests") is not None else 0),
        "",
        f"HISTORICAL 4B.2.4 =",
        str(header.get("historical_4b24") or "FAIL"),
        "",
        f"ROOT CAUSE =",
        str(header.get("root_cause") or ""),
        "",
        f"PYTHON EXECUTABLE =",
        str(header.get("python_executable") or ""),
        "",
        f"PYTHON VERSION =",
        str(header.get("python_version") or ""),
        "",
        f"ENVIRONMENT TYPE =",
        str(header.get("environment_type") or ""),
        "",
        f"DEPENDENCY MECHANISM =",
        str(header.get("dependency_mechanism") or ""),
        "",
        f"OPENAI SDK PREVIOUSLY DECLARED =",
        _yn(header.get("openai_sdk_previously_declared")),
        "",
        f"OPENAI SDK PREVIOUSLY INSTALLED =",
        _yn(header.get("openai_sdk_previously_installed")),
        "",
        f"OPENAI SDK NOW INSTALLED =",
        _yn(header.get("openai_sdk_now_installed")),
        "",
        f"OPENAI SDK VERSION =",
        str(header.get("openai_sdk_version") or ""),
        "",
        f"DEPENDENCY MANIFEST UPDATED =",
        str(header.get("dependency_manifest_updated") or ""),
        "",
        f"OPENAI IMPORT =",
        str(header.get("openai_import") or ""),
        "",
        f"OPENAI CLIENT CONSTRUCTION =",
        str(header.get("openai_client_construction") or ""),
        "",
        f"OPENAI PROVIDER INITIALIZATION =",
        str(header.get("openai_provider_initialization") or ""),
        "",
        f"OPENAI CREDENTIAL AVAILABLE =",
        _yn(header.get("openai_credential_available")),
        "",
        f"SECRET LEAKAGE =",
        str(header.get("secret_leakage") if header.get("secret_leakage") is not None else 0),
        "",
        f"NETWORK CALLS =",
        str(header.get("network_calls") if header.get("network_calls") is not None else 0),
        "",
        f"GENERIC PROVIDER PREFLIGHT =",
        str(header.get("generic_provider_preflight") or ""),
        "",
        f"ONE-SHOT LOCK ROOT CAUSE =",
        str(header.get("one_shot_lock_root_cause") or ""),
        "",
        f"FUTURE CALL ACCOUNTING =",
        str(header.get("future_call_accounting") or ""),
        "",
        f"FROZEN REQUEST SHA256 =",
        str(header.get("frozen_request_sha256") or ""),
        "",
        f"REQUEST IDENTITY =",
        str(header.get("request_identity") or ""),
        "",
        f"BENCHMARK IDENTITY =",
        str(header.get("benchmark_identity") or ""),
        "",
        f"SEMANTIC GATE REGRESSION =",
        str(header.get("semantic_gate_regression") or ""),
        "",
        f"TESTS =",
        str(header.get("tests") or ""),
        "",
        f"book.json =",
        "NOT PUBLISHED",
        "",
        f"PRODUCTION CACHE =",
        "UNCHANGED",
        "",
        f"READY_FOR_ONE_NEW_EXPLICITLY_AUTHORIZED_TERRA_CANARY =",
        _yn(header.get("ready_for_one_new_explicitly_authorized_terra_canary")),
        "",
        f"READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT =",
        "NO",
        "",
        f"READY_FOR_FULL_REAL_BOOK_GENERATION =",
        "NO",
        "",
        f"NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## Notes",
        "",
        str(header.get("notes") or ""),
        "",
        "This phase does not authorize another Terra call.",
        "Wait for human review.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
