"""Constantes 3B.7.7A.11 — extraction locale bornée. FakeAI / offline only."""

from __future__ import annotations

from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_output_ceiling_review.constants import (
    CALL_C_COST,
    CALL_C_FINISH,
    CALL_C_LOCAL,
    CALL_C_OUTPUT,
    CALL_C_PROVIDER_INPUT,
    CALL_C_THINKING_TOKENS,
    CLEAN_SHA,
    GENERATION_C_ANTHROPIC_SHA,
    GENERATION_C_RAW_SHA,
    PRIMARY_ROOT_CAUSE,
    PRODUCTION_PLANNER_VERSION,
    PROJECT_NAME,
    PROMPT_10_SHA,
    PROMPT_11_SHA,
    PROTECTED_EVIDENCE,
    SELECTED_ARCHITECTURE,
    SMALL_HTTP_RAW_SHA,
    SMALL_RAW_TEXT_SHA,
    SMALL_SIGNATURE,
    WINDOW_ID,
)
from app.source_analysis_provider_boundary.constants import (
    CALL1_SIGNATURE,
    CALL2_SIGNATURE,
)
from app.source_analysis_small_window_hierarchy.constants import (
    CANDIDATE_PLANNER_VERSION,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.11"
MODE = "OFFLINE_OUTPUT_BOUNDED_LOCAL_EXTRACTION_IMPLEMENTATION"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
NEW_WIN001_CALLS = 0
REAL_WINDOW_CALLS = 0
REAL_PROVIDER_CALL_AUTHORIZED_NEXT = False

WINDOW_ANALYSIS_PROMPT_VERSION_V12 = "window-analysis-1.2"
WINDOW_ANALYSIS_PROMPT_VERSION_V121 = "window-analysis-1.2.1"
CANDIDATE_WINDOW_ANALYSIS_PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V121
SEMANTIC_TRANSPORT_VERSION_V2 = "semantic-transport-v2"
GRANULARITY_POLICY_VERSION = "window-granularity-1.1-minimal"
GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC = "window-granularity-1.2-kind-specific"
CONSOLIDATION_RECOVERY_VERSION = "consolidation-recovery-v1"
SUBDIVISION_POLICY_VERSION = "local-v2-subdivision-1.0"

LOCAL_KINDS = (
    "TOPIC",
    "IDEA",
    "RELATION",
    "EXAMPLE",
    "REFERENCE",
    "UNCERTAINTY",
)
DEFERRED_KINDS = (
    "REPETITION",
    "VOICE",
    "INTENT_KIND",
    "AUDIENCE_KIND",
)

HARD_CEILINGS = {
    "TOPIC": 14,
    "IDEA": 56,
    "RELATION": 24,
    "EXAMPLE": 14,
    "REFERENCE": 14,
    "UNCERTAINTY": 12,
}
SOFT_TARGETS = {
    "TOPIC": 8,
    "IDEA": 40,
    "RELATION": 18,
    "EXAMPLE": 10,
    "REFERENCE": 8,
    "UNCERTAINTY": 8,
}
TOTAL_SOFT_TARGET = 92
TOTAL_HARD_CEILING = 134
SOURCE_REFS_HARD_MAX = 48
DESIGN_SOURCE_REFS_WORST = 12
TARGET_JSON_LOCAL_TOKENS = 12000
RESERVED_THINKING_TOKENS = 8000
MAX_OUTPUT_TOKENS_FROZEN = 32000

OVERFLOW_TOKEN = "analysis_capacity_exceeded"
OVERFLOW_UNCERTAINTY_KIND = "interrupted_thought"
OVERFLOW_UNCERTAINTY_SEVERITY = "high"

SUBDIVISION_MAX_DEPTH = 2
SUBDIVISION_MIN_OWNED_SRC = 2
CHILD_SUFFIXES = ("A", "B")

TRANSPORT_ARTIFACT = "source_analysis_semantic_transport_v2_design.json"
OUTPUT_BUDGET_ARTIFACT = "source_analysis_local_v2_output_budget.json"
THINKING_ARTIFACT = "source_analysis_anthropic_thinking_budget_capability.json"
SUBDIVISION_ARTIFACT = "source_analysis_local_v2_subdivision_policy.json"
E2E_ARTIFACT = "source_analysis_local_v2_fake_ai_e2e.json"
COMPAT_ARTIFACT = "source_analysis_local_v2_canonical_compatibility.json"
REPORT_NAME = (
    "PHASE_3B77A11_OUTPUT_BOUNDED_LOCAL_SEMANTIC_EXTRACTION_IMPLEMENTATION_REPORT.md"
)

NEXT_PHASE = "3B.7.7A.12_ANTHROPIC_THINKING_BUDGET_CONTRACT_VERIFICATION"
NEXT_PHASE_LABEL = (
    "3B.7.7A.12 — ANTHROPIC THINKING-BUDGET CONTRACT VERIFICATION "
    "& REAL-CALL READINESS — prefer official-contract verification first"
)
NEXT_ACTION = "HUMAN REVIEW"

SMALL_PLANNER_STATUS = "KEEP"
ADAPTIVE_HIERARCHY_STATUS = "KEEP"

PROTECTED_EVIDENCE_A11 = PROTECTED_EVIDENCE + (
    "audit/PHASE_3B77A10_SMALL_WIN001_OUTPUT_CEILING_STRUCTURED_PARSE_FAILURE_REVIEW_REPORT.md",
    "audit/source_analysis_small_win001_output_ceiling_forensics.json",
    "audit/source_analysis_window_output_contract_analysis.json",
    "audit/source_analysis_output_bounding_architecture_options.json",
    "audit/source_analysis_output_bounding_architecture_decision.json",
    "audit/source_analysis_forensic_vs_publication_isolation.json",
)

__all__ = [
    "ADAPTIVE_HIERARCHY_STATUS",
    "CALL1_SIGNATURE",
    "CALL2_SIGNATURE",
    "CALL_C_COST",
    "CALL_C_FINISH",
    "CALL_C_LOCAL",
    "CALL_C_OUTPUT",
    "CALL_C_PROVIDER_INPUT",
    "CALL_C_THINKING_TOKENS",
    "CANDIDATE_PLANNER_VERSION",
    "CANDIDATE_WINDOW_ANALYSIS_PROMPT_VERSION",
    "CHILD_SUFFIXES",
    "CLEAN_SHA",
    "COMPAT_ARTIFACT",
    "CONSOLIDATION_RECOVERY_VERSION",
    "DEFERRED_KINDS",
    "DESIGN_SOURCE_REFS_WORST",
    "E2E_ARTIFACT",
    "GENERATION_C_ANTHROPIC_SHA",
    "GENERATION_C_RAW_SHA",
    "GRANULARITY_POLICY_VERSION",
    "GRANULARITY_POLICY_VERSION_12_KIND_SPECIFIC",
    "HARD_CEILINGS",
    "LOCAL_KINDS",
    "MAX_OUTPUT_TOKENS_FROZEN",
    "MODE",
    "NEW_WIN001_CALLS",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "OUTPUT_BUDGET_ARTIFACT",
    "OVERFLOW_TOKEN",
    "OVERFLOW_UNCERTAINTY_KIND",
    "OVERFLOW_UNCERTAINTY_SEVERITY",
    "PHASE",
    "PLANNER_VERSION",
    "PRIMARY_ROOT_CAUSE",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_10_SHA",
    "PROMPT_11_SHA",
    "PROTECTED_EVIDENCE_A11",
    "REAL_PROVIDER_CALL_AUTHORIZED_NEXT",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "REPORT_NAME",
    "RESERVED_THINKING_TOKENS",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SEMANTIC_TRANSPORT_VERSION_V2",
    "SMALL_HTTP_RAW_SHA",
    "SMALL_PLANNER_STATUS",
    "SMALL_RAW_TEXT_SHA",
    "SMALL_SIGNATURE",
    "SOFT_TARGETS",
    "SOURCE_REFS_HARD_MAX",
    "SUBDIVISION_ARTIFACT",
    "SUBDIVISION_MAX_DEPTH",
    "SUBDIVISION_MIN_OWNED_SRC",
    "SUBDIVISION_POLICY_VERSION",
    "TARGET_JSON_LOCAL_TOKENS",
    "THINKING_ARTIFACT",
    "TOTAL_HARD_CEILING",
    "TOTAL_SOFT_TARGET",
    "TRANSPORT_ARTIFACT",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V12",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V121",
    "WINDOW_ID",
]
