"""Rapport markdown déterministe 3B.7.7A.11."""

from __future__ import annotations

from typing import Any, Mapping


def render_report(
    *,
    header: Mapping[str, Any],
    schemas: Mapping[str, Any],
    worst: Mapping[str, Any],
    thinking: Mapping[str, Any],
    subdivision: Mapping[str, Any],
    e2e: Mapping[str, Any],
    compat: Mapping[str, Any],
    replay: Mapping[str, Any],
    integrity: Mapping[str, Any],
) -> str:
    h = header
    v2 = schemas["v2_generic"]
    v1 = schemas["v1"]
    call = h["call_c"]
    lines = [
        "# PHASE 3B.7.7A.11 — OUTPUT-BOUNDED LOCAL SEMANTIC EXTRACTION IMPLEMENTATION",
        "",
        "## Result",
        "",
        str(h["result"]),
        "",
        f"REAL PROVIDER CALLS = {h['real_provider_calls']}",
        "",
        f"REAL WINDOW CALLS = {h['real_window_calls']}",
        "",
        f"ROOT CAUSE CARRIED FORWARD = {h['root_cause']}",
        "",
        f"NEW PROMPT = {h['new_prompt']}",
        "",
        f"NEW TRANSPORT = {h['new_transport']}",
        "",
        f"LOCAL KINDS = {' / '.join(h['local_kinds'])}",
        "",
        f"DEFERRED KINDS = {' / '.join(h['deferred_kinds'])}",
        "",
        f"LOCAL GRANULARITY POLICY = {h['local_granularity_policy']}",
        "",
        f"SYNTHETIC WORST-CASE JSON = {h['synthetic_worst_case_tokens']} tokens",
        "",
        f"TARGET = <={h['target']}",
        "",
        f"THINKING RESERVE DESIGN = {h['thinking_reserve_design']}",
        "",
        f"THINKING CAP CONTROL = {h['thinking_cap_control']}",
        "",
        f"PROVIDER-ENFORCED OUTPUT BOUNDEDNESS = {h['provider_enforced_output_boundedness']}",
        "",
        f"V2 RAW SCHEMA = {h['v2_raw_schema_bytes']} bytes",
        "",
        f"V2 ANTHROPIC-ADAPTED SCHEMA = {h['v2_adapted_schema_bytes']} bytes",
        "",
        f"V2 SERVER GRAMMAR = {h['v2_server_grammar']}",
        "",
        f"CAPACITY SUBDIVISION = {h['capacity_subdivision']}",
        "",
        f"DIRECT FAKEAI E2E = {h['direct_fakeai_e2e']}",
        "",
        f"HIERARCHICAL FAKEAI E2E = {h['hierarchical_fakeai_e2e']}",
        "",
        f"DEFERRED GLOBAL FIELDS RECOVERED = {h['deferred_global_fields_recovered']}",
        "",
        f"CANONICAL SOURCEMAP = {h['canonical_sourcemap']}",
        "",
        f"SMALL PLANNER = {h['small_planner']}",
        "",
        f"ADAPTIVE HIERARCHY = {h['adaptive_hierarchy']}",
        "",
        f"PRODUCTION DEFAULT CHANGED = {h['production_default_changed']}",
        "",
        f"REAL SOURCE MAP = {h['real_source_map']}",
        "",
        f"PROJECT STATE = {h['project_state']}",
        "",
        "TESTS = additive FakeAI/offline; full suite expected 2459 + new / 0 failed",
        "",
        f"REAL PROVIDER CALL AUTHORIZED NEXT = {str(h['real_provider_call_authorized_next']).upper()}",
        "",
        f"NEXT ACTION = {h['next_action']}",
        "",
        f"Reason: {h['result_reason']}",
        "",
        "## 1. Result",
        "",
        f"{h['result']} — {h['result_reason']}",
        "",
        "## 2. Objective",
        "",
        "Implement MINIMAL_LOCAL_TRANSPORT_WITH_RESERVED_OUTPUT_BUDGET using FakeAI and offline tests only.",
        "",
        "## 3. Baseline",
        "",
        "Expected 2459 passed / 0 failed before this phase. New tests are additive.",
        "",
        "## 4. Root cause",
        "",
        f"{h['root_cause']} — thinking tokens share max_output. Record ceiling 160 was not exceeded.",
        "",
        "## 5. CALL C evidence",
        "",
        f"provider input {call['input']}; max output {call['output']}; actual output {call['output']};",
        f"finish {call['finish']}; thinking {call['thinking']}; cost {call['cost']}.",
        "",
        "## 6. Architecture selected",
        "",
        f"{h['architecture']} with {h['new_prompt']} and {h['new_transport']}.",
        "",
        "## 7. Historical contract freeze",
        "",
        f"prompt 1.0 unchanged = {integrity['prompt_1_0_unchanged']}",
        f"prompt 1.1 unchanged = {integrity['prompt_1_1_unchanged']}",
        f"Generation C raw unchanged = {integrity['generation_c_raw_unchanged']}",
        f"window-granularity-1.0 unchanged = {integrity['granularity_1_0_unchanged']}",
        "",
        "## 8. Prompt 1.2",
        "",
        f"{h['new_prompt']} is a new module. It states LOCAL semantic extraction, not global analysis, not editorial planning, not book generation.",
        "",
        "## 9. Transport v2",
        "",
        f"{h['new_transport']} is versioned separately. Not an alias of v1. Generic records[] shape retained for grammar compactness.",
        "",
        "## 10. Allowed local kinds",
        "",
        ", ".join(h["local_kinds"]),
        "",
        "## 11. Deferred kinds",
        "",
        ", ".join(h["deferred_kinds"]),
        "",
        "## 12. Deferred-field recovery",
        "",
        "REPETITION via global REP ops. VOICE/INTENT/AUDIENCE via consolidation-recovery-v1 supplied by FakeAI, grounded to TOPIC/IDEA SRC evidence. Python does not invent them.",
        "",
        "## 13. Local/global responsibility",
        "",
        "Local: TOPIC/IDEA/RELATION/EXAMPLE/REFERENCE/UNCERTAINTY. Global: metadata, cross-window repetition, cross-window relations, semantic merges.",
        "",
        "## 14. Schema design",
        "",
        f"Selected shape = {schemas['selected_shape']}. {schemas['selected_reason']}",
        "",
        "## 15. Raw schema metrics",
        "",
        f"V2 raw {v2['raw_bytes']} bytes; objects {v2['raw']['object_nodes']}; arrays {v2['raw']['array_nodes']}; properties {v2['raw']['total_properties']}; constraints {v2['raw']['constraints']}; depth {v2['raw']['maximum_nesting_depth']}.",
        "",
        "## 16. Anthropic-adapted metrics",
        "",
        f"V2 adapted {v2['adapted_bytes']} bytes; maxItems in adapted = {v2['maxItems_in_adapted']}.",
        "",
        "## 17. V1 vs V2",
        "",
        f"V1 raw {v1['raw_bytes']} / adapted {v1['adapted_bytes']}. V2 raw {v2['raw_bytes']} / adapted {v2['adapted_bytes']}. Delta raw {schemas['v2_vs_v1_raw_bytes_delta']}.",
        "",
        "## 18. Grammar risk",
        "",
        "UNVERIFIED. No provider grammar canary. Future tiny schema-only canary recommended before any semantic call.",
        "",
        "## 19. Granularity policy",
        "",
        f"{h['local_granularity_policy']} — not a silent reuse of 1.0.",
        "",
        "## 20. Per-kind ceilings",
        "",
        str(worst["per_kind_ceilings"]),
        "",
        "## 21. Value limits",
        "",
        "Application-level TEXT_HARD_LIMITS, validated after parse. Not provider-enforced.",
        "",
        "## 22. Source-ref limits",
        "",
        f"Application hard max {worst['application_source_refs_hard_max']}. Designed worst-case refs {worst['designed_source_refs']}. Sparse SRC only. No range expansion.",
        "",
        "## 23. Capacity signal",
        "",
        "analysis_capacity_exceeded on UNCERTAINTY. Result NOT READY. Does not itself stop the provider before max_tokens.",
        "",
        "## 24. Synthetic worst case",
        "",
        f"{worst['record_count']} records; {worst['designed']['json_bytes']} bytes; {worst['designed']['json_chars']} chars; {worst['local_tokens']} local tokens; kinds {worst['kind_counts']}.",
        "",
        "## 25. JSON budget",
        "",
        f"Designed worst-case {worst['local_tokens']} vs target {worst['target_json_local_tokens']}. within={worst['within_json_target']}. Headroom to 32000 = {worst['headroom_to_32000']}.",
        "",
        "## 26. Thinking reserve",
        "",
        f"Design reserve {worst['thinking_reserve_design']}. Not provider-enforced.",
        "",
        "## 27. Total output accounting",
        "",
        "TOTAL OUTPUT = THINKING TOKENS + VISIBLE/STRUCTURED OUTPUT TOKENS. CALL C: 21911 thinking + remaining text inside 32000.",
        "",
        "## 28. Current Anthropic payload",
        "",
        str(thinking.get("current_payload_thinking_config")),
        "",
        "## 29. CALL C thinking metadata",
        "",
        str(thinking.get("call_c_thinking_metadata")),
        "",
        "## 30. Thinking-cap capability",
        "",
        f"{thinking.get('THINKING_CAP_CONTROL')}. verified_locally={thinking.get('verified_locally')}. No guessed parameter implemented.",
        "",
        "## 31. Provider enforcement",
        "",
        "max_tokens is provider-enforced. Cardinality, value length, and thinking reserve are not.",
        "",
        "## 32. True boundedness classification",
        "",
        "PARTIALLY_PROVIDER_BOUNDED. JSON/thinking split is APPLICATION_POLICY_BOUNDED_ONLY.",
        "",
        "## 33. Fixed-slot comparison",
        "",
        f"Fixed-slot adapted delta vs generic = {schemas['fixed_slots_vs_generic_adapted_delta']}. Higher complexity.",
        "",
        "## 34. Generic-record comparison",
        "",
        "Generic records[] matches Generation C grammar shape and existing decoder architecture.",
        "",
        "## 35. Selected transport shape",
        "",
        "generic_records. Provider grammar acceptance UNVERIFIED.",
        "",
        "## 36. V2 decoder",
        "",
        "Strict. No repair. Deferred/unknown kinds fail closed.",
        "",
        "## 37. V2 validator",
        "",
        "Kinds, counts, compactness, SRC membership, capacity, relations, no deferred kinds, detectable editorial leakage.",
        "",
        "## 38. Transport-first behavior",
        "",
        "Parsed transport is retained on validator failure. Result is absent.",
        "",
        "## 39. Over-limit behavior",
        "",
        "Hard count exceeded → NOT READY, no retry, transport retained.",
        "",
        "## 40. Capacity behavior",
        "",
        "Valid capacity signal → NOT READY + offline subdivision plan. No provider retry.",
        "",
        "## 41. Subdivision trigger",
        "",
        str(subdivision.get("trigger")),
        "",
        "## 42. Subdivision algorithm",
        "",
        str(subdivision.get("algorithm")),
        "",
        "## 43. Child identity",
        "",
        str(subdivision.get("child_id_scheme")),
        "",
        "## 44. Child cache",
        "",
        "Binds parent identity, child identity, owned SRC+content, prompt/transport/policy, provider config, schema hash.",
        "",
        "## 45. Subdivision depth",
        "",
        f"max_depth={subdivision.get('max_depth')}",
        "",
        "## 46. Minimum unit",
        "",
        f"Fail-closed if owned SRC < {subdivision.get('minimum_unit_owned_src')} still signals overflow.",
        "",
        "## 47. No subdivision on parse failure",
        "",
        "PASS — LocalV2SubdivisionNotTriggered.",
        "",
        "## 48. No subdivision on provider failure",
        "",
        "PASS — LocalV2SubdivisionNotTriggered.",
        "",
        "## 49. Child consolidation",
        "",
        str(subdivision.get("child_consolidation")),
        "",
        "## 50. Consolidation compatibility",
        "",
        "V2 adapter builds historical ConsolidationInput without mutating consolidation-1.0. Category C absence is intentional.",
        "",
        "## 51. Regional compatibility",
        "",
        "Regional FakeAI KEEP/MERGE only. Regional does not decide final global metadata.",
        "",
        "## 52. Global consolidation",
        "",
        "Owns global metadata, cross-window repetition, cross-window relations, semantic merges.",
        "",
        "## 53. Repetition recovery",
        "",
        "Global REP ops with IDEA members and SRC union. No local REPETITION records.",
        "",
        "## 54. Voice recovery",
        "",
        "FakeAI consolidation-recovery-v1 voice_profile grounded to TOPIC/IDEA evidence.",
        "",
        "## 55. Intent recovery",
        "",
        "gm.in from consolidation-1.0 plus recovery intent_kinds. Not invented by Python.",
        "",
        "## 56. Audience recovery",
        "",
        "gm.au plus recovery audience_kinds. Not invented by Python.",
        "",
        "## 57. Cross-window relations",
        "",
        "Global REL ops between KEEP/MERGE idea nodes.",
        "",
        "## 58. Canonical reconstruction",
        "",
        "External SourceMap contract unchanged. Versioned intermediate adapters only.",
        "",
        "## 59. Direct E2E",
        "",
        str(e2e.get("direct")),
        "",
        "## 60. Hierarchical E2E",
        "",
        str(e2e.get("hierarchical")),
        "",
        "## 61. Deferred-fields E2E",
        "",
        f"Local deferred kinds absent={e2e.get('direct', {}).get('deferred_local_kinds_absent')}. Final fields recovered={h['deferred_global_fields_recovered']}.",
        "",
        "## 62. Traceability",
        "",
        "Ideas, examples, references, uncertainties, repetitions, and recovery evidence remain grounded to original SRCs.",
        "",
        "## 63. NO-DROP",
        "",
        f"direct no_drop={e2e.get('direct', {}).get('no_drop')}; hierarchical no_drop={e2e.get('hierarchical', {}).get('no_drop')}.",
        "",
        "## 64. CALL C forensic replay",
        "",
        str(replay),
        "",
        "## 65. No repair",
        "",
        "Truncated prefix is not salvaged into a production result.",
        "",
        "## 66. Small planner",
        "",
        f"{h['small_planner']} — window-planner-v2.1-small not activated globally.",
        "",
        "## 67. Adaptive hierarchy",
        "",
        f"{h['adaptive_hierarchy']} — DIRECT_GLOBAL / REGIONAL_THEN_GLOBAL unchanged.",
        "",
        "## 68. Production freeze",
        "",
        f"Production planner remains {integrity['production_planner']}. analyzer.py / main.py not wired.",
        "",
        "## 69. Cost implications",
        "",
        f"Old CALL C: input {call['input']}, thinking {call['thinking']}, cost {call['cost']}. V2 input similar; JSON structurally smaller; thinking controllable only if provider cap is later verified. No actual cost predicted.",
        "",
        "## 70. Future grammar verification",
        "",
        "Recommend a tiny schema-only grammar canary before any semantic call. Not run.",
        "",
        "## 71. Future thinking verification",
        "",
        "Prefer official-contract / offline verification first. No semantic provider call automatically.",
        "",
        "## 72. Real-call readiness",
        "",
        "BLOCKED. V2 FakeAI validated. Grammar UNVERIFIED. Thinking cap UNVERIFIED. Authorization NO.",
        "",
        "## 73. Tests",
        "",
        "Additive FakeAI/offline coverage listed in test_source_analysis_local_v2.py.",
        "",
        "## 74. Network",
        "",
        "0. Package forbids network clients. Tests use no_ai_network.",
        "",
        "## 75. Historical artifacts",
        "",
        "3B.7.7A through A.10 evidence intended byte-identical. New files only.",
        "",
        "## 76. CLEAN",
        "",
        f"unchanged={integrity['clean_unchanged']}",
        "",
        "## 77. Prompt 1.1",
        "",
        f"unchanged={integrity['prompt_1_1_unchanged']}",
        "",
        "## 78. Generation C",
        "",
        f"raw unchanged={integrity['generation_c_raw_unchanged']}; anthropic unchanged={integrity['generation_c_anthropic_unchanged']}",
        "",
        "## 79. Isolation guard",
        "",
        "Forensics allowed. Unauthorized semantic artifacts forbidden. Real source_map absent.",
        "",
        "## 80. SourceMap",
        "",
        f"present={integrity['source_map_present']}",
        "",
        "## 81. Project state",
        "",
        f"not_success={integrity['project_state']['not_success']}",
        "",
        "## 82. Files added",
        "",
        "app/source_analysis_local_v2/* ; app/tests/test_source_analysis_local_v2.py ; app/tests/test_source_analysis_local_v2_audit.py ; audit A.11 artifacts.",
        "",
        "## 83. Files modified",
        "",
        "None required for historical contracts. Production analyzer/main untouched.",
        "",
        "## 84. Remaining blockers",
        "",
        "THINKING_CAP_CONTROL=UNVERIFIED. V2 server grammar UNVERIFIED. Real-call authorization NO.",
        "",
        "## 85. Recommended next phase",
        "",
        f"{h['next_phase']} — official-contract verification first. No automatic semantic provider call.",
        "",
    ]
    return "\n".join(lines) + "\n"
