"""Markdown report Phase 4A.3."""

from __future__ import annotations

from typing import Any, Mapping


def render_report(bundle: Mapping[str, Any]) -> str:
    header = dict(bundle.get("header") or {})
    lines = [
        "# PHASE 4A.3 — EDITORIAL PLANNER ONE REAL PRODUCTION CANARY",
        "",
        "## Result",
        "",
        str(header.get("result") or "FAIL"),
        "",
        f"AUTHORIZED PROVIDER CALLS = {header.get('authorized_provider_calls', 1)}",
        "",
        f"ACTUAL PROVIDER CALLS = {header.get('actual_provider_calls', 0)}",
        "",
        f"RETRIES = {header.get('retries', 0)}",
        "",
        f"SOURCE MAP SHA256 PRE = {header.get('source_map_sha256_pre')}",
        "",
        f"SOURCE MAP SHA256 POST = {header.get('source_map_sha256_post')}",
        "",
        f"SOURCE MAP UNCHANGED = {header.get('source_map_unchanged')}",
        "",
        f"PROMPT = {header.get('prompt')}",
        "",
        f"TRANSPORT = {header.get('transport')}",
        "",
        f"SCHEMA RAW / ADAPTED = {header.get('schema_raw_adapted')}",
        "",
        f"SCHEMA HASH = {header.get('schema_hash')}",
        "",
        f"SCHEMA IDENTITY = {header.get('schema_identity')}",
        "",
        f"EXPECTED REQUEST SHA256 = {header.get('expected_request_sha256')}",
        "",
        f"ACTUAL REQUEST SHA256 = {header.get('actual_request_sha256')}",
        "",
        f"REQUEST IDENTITY = {header.get('request_identity')}",
        "",
        f"REQUEST CHARS / BYTES = {header.get('request_chars')} / {header.get('request_bytes')}",
        "",
        f"MODEL = {header.get('model')}",
        "",
        f"THINKING MODE = {header.get('thinking_mode')}",
        "",
        f"MAX_OUTPUT = {header.get('max_output')}",
        "",
        f"CONNECT / READ TIMEOUT = {header.get('connect_timeout')} / {header.get('read_timeout')}",
        "",
        f"HTTP / STATUS = {header.get('http_status')}",
        "",
        f"FINISH = {header.get('finish')}",
        "",
        f"REQUEST ID = {header.get('request_id')}",
        "",
        f"INPUT TOKENS = {header.get('input_tokens')}",
        "",
        f"OUTPUT TOKENS = {header.get('output_tokens')}",
        "",
        f"THINKING TOKENS = {header.get('thinking_tokens')}",
        "",
        f"OUTPUT UTILIZATION = {header.get('output_utilization')}",
        "",
        f"ELAPSED = {header.get('elapsed')}",
        "",
        f"ACTUAL COST = {header.get('cost')}",
        "",
        f"A.2 EXPECTED COST = {header.get('a2_expected_cost')}",
        "",
        f"A.2 CONSERVATIVE COST = {header.get('a2_conservative_cost')}",
        "",
        f"A.2 HARD COST = {header.get('a2_hard_cost')}",
        "",
        f"STRUCTURED PARSE = {header.get('structured_parse')}",
        "",
        f"TRANSPORT DECODER = {header.get('transport_decoder')}",
        "",
        f"HANDLE VALIDATION = {header.get('handle_validation')}",
        "",
        f"CANONICAL RECONSTRUCTION = {header.get('canonical_reconstruction')}",
        "",
        f"CANONICAL CANDIDATE SHA256 = {header.get('canonical_candidate_sha256')}",
        "",
        f"CHAPTERS = {header.get('chapters')}",
        "",
        f"SECTIONS = {header.get('sections')}",
        "",
        f"IDEA COVERAGE = {header.get('idea_coverage')}",
        "",
        f"SILENT OMISSIONS = {header.get('silent_omissions')}",
        "",
        f"ASSIGNED = {header.get('assigned')}",
        "",
        f"DEFERRED = {header.get('deferred')}",
        "",
        f"EXCLUDED = {header.get('excluded')}",
        "",
        f"REUSED IDEAS = {header.get('reused')}",
        "",
        f"EXTRA SECTION ASSIGNMENTS = {header.get('extra_section_assignments')}",
        "",
        f"UNKNOWN IDEA REFS = {header.get('unknown_idea_refs')}",
        "",
        f"UNKNOWN TOPIC REFS = {header.get('unknown_topic_refs')}",
        "",
        f"UNKNOWN EXAMPLE REFS = {header.get('unknown_example_refs')}",
        "",
        f"UNKNOWN REFERENCE REFS = {header.get('unknown_reference_refs')}",
        "",
        f"UNKNOWN UNCERTAINTY REFS = {header.get('unknown_uncertainty_refs')}",
        "",
        f"TRACEABILITY = {header.get('traceability')}",
        "",
        f"INVENTION BOUNDARY = {header.get('invention_boundary')}",
        "",
        f"UNCERTAINTY PRESERVATION = {header.get('uncertainty_preservation')}",
        "",
        f"TITLE REVIEW = {header.get('title_review')}",
        "",
        f"EDITORIAL ANGLE REVIEW = {header.get('editorial_angle_review')}",
        "",
        f"TARGET READER REVIEW = {header.get('target_reader_review')}",
        "",
        f"BOOK CONCEPT REVIEW = {header.get('book_concept_review')}",
        "",
        f"CHAPTER REVIEW = {header.get('chapter_review')}",
        "",
        f"SECTION REVIEW = {header.get('section_review')}",
        "",
        f"BALANCE = {header.get('balance')}",
        "",
        f"MANUSCRIPT LEAKAGE = {header.get('manuscript_leakage')}",
        "",
        f"EDITORIAL PLAN VALIDATOR = {header.get('editorial_plan_validator')}",
        "",
        f"DETERMINISTIC REPLAY = {header.get('deterministic_replay')}",
        "",
        f"SEMANTIC REVIEW = {header.get('semantic_review')}",
        "",
        f"PUBLICATION_ELIGIBLE = {header.get('publication_eligible')}",
        "",
        f"TESTS = {header.get('tests')}",
        "",
        f"NEW FAILURES = {header.get('new_failures')}",
        "",
        "editorial_plan.json = NOT PUBLISHED",
        "",
        f"READY_FOR_CONTROLLED_EDITORIAL_PLAN_PUBLICATION = {header.get('ready_for_controlled_editorial_plan_publication')}",
        "",
        "BOOK GENERATOR = NOT STARTED",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
        "## Notes",
        "",
        str(header.get("notes") or ""),
        "",
        "WAIT FOR HUMAN REVIEW.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
