"""
Phase 4B.2.23 — BATCH-01 first controlled real generation of four chapters.

NEW explicit batch authorization. Four Anthropic claude-sonnet-5 calls
maximum, one per chapter, zero retries, zero fallbacks.
Chapters CH001, CH002, CH003, CH004 only.
Prompt: book-generator-faithful-restatement-1.1-candidate via the isolated
selector. Does not activate prompt 1.1 globally.
Does not regenerate CH012 or CH018. Does not publish book.json.
Does not write the production cache. Does not call Terra or OpenAI.
Does not launch BATCH-02.
"""

from __future__ import annotations

from decimal import Decimal

from app.ai.thinking import THINKING_MODE_DISABLED
from app.book_authorial_voice_4b218.constants import (
    AUTHORIAL_VOICE_POLICY_VERSION,
    FAITHFUL_PROMPT_1_0_VERSION,
    FAITHFUL_PROMPT_1_1_VERSION,
    HISTORICAL_PROMPT_V10,
    HISTORICAL_PROMPT_V101,
)
from app.book_authorial_voice_4b218.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B218_SCOPE,
)
from app.book_batch_preparation_4b222.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B222_SCOPE,
    BATCH_CHAPTERS,
    EXPECTED_CH018_JSON_SHA256,
    EXPECTED_CH018_MD_SHA256,
    FIRST_BATCH_ID,
)
from app.book_editorial_acceptance_4b219.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B219_SCOPE,
    EXPECTED_ACCEPTED_JSON_SHA256,
    EXPECTED_ACCEPTED_MD_SHA256,
    EXPECTED_LOCK_SHA256,
    EXPECTED_ORIGINAL_JSON_SHA256,
    EXPECTED_ORIGINAL_MD_SHA256,
)
from app.book_editorial_alignment_4b216.constants import (
    COVERAGE_CONTRACT_VERSION,
    EDITORIAL_POLICY_VERSION,
    HISTORICAL_SEMANTIC_CONTRACT,
)
from app.book_generation.constants import (
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION_V10,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    HARD_MAX_OUTPUT_TOKENS,
    MIN_MAX_OUTPUT_TOKENS,
    MODEL,
    PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_generation_4b217.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B217_SCOPE,
    HISTORICAL_CH012_CENTRAL_USD,
    SONNET_INPUT_COST_PER_1M,
    SONNET_OUTPUT_COST_PER_1M,
)
from app.book_generation_4b221.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B221_SCOPE,
)
from app.book_scale_up_preparation_4b220.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B220_SCOPE,
    EXPECTED_PROMPT_1_1_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_1_1_SHA256,
    EXPECTED_PROMPT_1_1_SYSTEM_SHA256,
    FAITHFUL_PROMPT_1_1,
)
from app.book_semantic_gate_4b23.constants import EXPECTED_CLEAN_TRANSCRIPT
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE

PHASE = "4B.2.23"
PHASE_NAME = "BATCH01_FIRST_CONTROLLED_REAL_GENERATION_OF_FOUR_CHAPTERS"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = "BOOK_GENERATION_BATCH_01_CH001_CH004_ONE_SHOT_PER_CHAPTER"

AUTHORIZED_ANTHROPIC_CALLS = 4
AUTHORIZED_SONNET_CALLS = 4
AUTHORIZED_REMOTE_INVOCATIONS = 4
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_TERRA_CALLS = 0
MAX_ENGINE_GENERATE = 4
MAX_ANTHROPIC_POST = 4
MAX_HTTP_REQUESTS = 4
MAX_EXECUTION_ATTEMPTS = 1
MAX_CALLS_PER_CHAPTER = 1
RETRIES = 0
FALLBACKS = 0
SDK_MAX_RETRIES = 0

PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
OPENAI_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = True
REAL_CHAPTER_GENERATION_AUTHORIZED = True
REAL_PROVIDERS_ENABLED = True
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
FAITHFUL_PROMPT_ACTIVATED_IN_PRODUCTION = False
FAITHFUL_PROMPT_1_1_ACTIVATED = False
EDITORIAL_POLICY_ACTIVATED_IN_PRODUCTION = False
COVERAGE_CONTROL_ACTIVATED_IN_PRODUCTION = False
SEMANTIC_GATE_202_ENABLED = False
SEMANTIC_CERTIFICATION_PERFORMED = False
BOOK_JSON_PUBLICATION = False
BATCH02_AUTHORIZED = False

BATCH_ID = FIRST_BATCH_ID
AUTHORIZED_CHAPTER_IDS = BATCH_CHAPTERS[BATCH_ID]
assert BATCH_ID == "BATCH-01"
assert AUTHORIZED_CHAPTER_IDS == ("CH001", "CH002", "CH003", "CH004")
FORBIDDEN_CHAPTER_IDS = ("CH012", "CH018")
ACCEPTED_CH012_ID = "CH012"
ACCEPTED_CH018_ID = "CH018"

PROMPT_VERSION = FAITHFUL_PROMPT_1_1
TRANSPORT_VERSION = BOOK_GENERATION_TRANSPORT_VERSION
VALIDATOR_VERSION = BOOK_GENERATOR_VALIDATOR_VERSION
HISTORICAL_PROMPT = HISTORICAL_PROMPT_V101
HISTORICAL_PROMPT_V10_ID = HISTORICAL_PROMPT_V10
FAITHFUL_PROMPT_1_0 = FAITHFUL_PROMPT_1_0_VERSION
NARRATIVE_VOICE_CONTRACT = AUTHORIAL_VOICE_POLICY_VERSION

assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert PROMPT_VERSION == "book-generator-faithful-restatement-1.1-candidate"
assert PROMPT_VERSION == FAITHFUL_PROMPT_1_1_VERSION
assert FAITHFUL_PROMPT_1_0 == "book-generator-faithful-restatement-1.0-candidate"
assert HISTORICAL_PROMPT == BOOK_GENERATOR_PROMPT_VERSION == "book-generator-1.0.1"
assert HISTORICAL_PROMPT_V10_ID == BOOK_GENERATOR_PROMPT_VERSION_V10 == "book-generator-1.0"
assert TRANSPORT_VERSION == "book-generation-transport-1.0"
assert EDITORIAL_POLICY_VERSION == "faithful-teaching-book-editorial-policy-1.0-candidate"
assert COVERAGE_CONTRACT_VERSION == "source-coverage-control-4b216-candidate"
assert HISTORICAL_SEMANTIC_CONTRACT == "book-semantic-validator-2.0.2-candidate"
assert NARRATIVE_VOICE_CONTRACT == "authorial-voice-preservation-1.0-candidate"
assert CONSUMED_4B217_SCOPE == (
    "BOOK_GENERATION_4B217_CH012_FAITHFUL_REAL_PILOT_GENERATION_ONLY"
)
assert CONSUMED_4B218_SCOPE.startswith("BOOK_AUTHORIAL_VOICE_4B218_")
assert CONSUMED_4B219_SCOPE.startswith("BOOK_EDITORIAL_ACCEPTANCE_4B219_")
assert CONSUMED_4B220_SCOPE.startswith("BOOK_SCALE_UP_PREPARATION_4B220_")
assert CONSUMED_4B221_SCOPE == (
    "BOOK_GENERATION_LATER_PHASE_CH018_FIRST_REMAINING_CHAPTER_ONE_SHOT_ONLY"
)
assert CONSUMED_4B222_SCOPE.startswith("BOOK_BATCH_PREPARATION_4B222_")

THINKING_MODE = THINKING_MODE_DISABLED
assert THINKING_MODE == "disabled"

BUDGET_CAP_USD = Decimal("0.66")
BUDGET_CAP_DISPLAY = "0.66 USD"
MAX_REAL_CALL_COST_USD = BUDGET_CAP_USD
PREPARATION_CALCULABLE_MAXIMUM_USD = Decimal("0.569342")
PRICING_EFFECTIVE_DATE = "2026-09-18"
PESSIMISTIC_CHARS_PER_TOKEN = Decimal("1.9365384615384615")

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 1800.0

STAGE_CANARY = "book_generation_4b223_batch01"
CANARY_WINDOW_ID = "CANARY_BG4B223"
LOCK_NAME = "call_lock.json"
BATCH_LOCK_NAME = "batch_lock.json"
CODE_VERSION = "app.book_generation_4b223"

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_TRANSCRIPT = EXPECTED_CLEAN_TRANSCRIPT

assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert EXPECTED_ACCEPTED_MD_SHA256 == (
    "79d0ab2254e1a972e0fb5ddcbb7901425255ce887ee817fc39b001838b889919"
)
assert EXPECTED_ACCEPTED_JSON_SHA256 == (
    "8f135ac5f1df8b2e077e9cc767518d1a05e2fc22d80f5d66494cf5a8364e7fc5"
)
assert EXPECTED_CH018_MD_SHA256 == (
    "3f8e0590567d431af18812505e2a5f5fa454e1648d06f2b895ceae30278df1cb"
)
assert EXPECTED_CH018_JSON_SHA256 == (
    "e4902da92b05dbe0875222a41d59eb99f7b3e669b685f50f36b06864a327d38b"
)
assert EXPECTED_PROMPT_1_1_SHA256 == (
    "e39084dc9ed3b048bfdaa2e112b380d15957085eeb613dd74c97a32b880cec50"
)
assert AUTHORIZED_ANTHROPIC_CALLS == 4
assert AUTHORIZED_OPENAI_CALLS == 0
assert AUTHORIZED_TERRA_CALLS == 0
assert MAX_CALLS_PER_CHAPTER == 1
assert RETRIES == 0
assert FALLBACKS == 0
assert PUBLICATION_AUTHORIZED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert FAITHFUL_PROMPT_1_1_ACTIVATED is False
assert BATCH02_AUTHORIZED is False
assert BUDGET_CAP_USD == Decimal("0.66")
assert PREPARATION_CALCULABLE_MAXIMUM_USD <= BUDGET_CAP_USD
assert MIN_MAX_OUTPUT_TOKENS == 4096
assert HARD_MAX_OUTPUT_TOKENS == 32000
assert CANONICAL_PYTHON.endswith("python.exe")
assert SONNET_INPUT_COST_PER_1M == Decimal("2.00")
assert SONNET_OUTPUT_COST_PER_1M == Decimal("10.00")

LOCK_STATE_NOT_STARTED = "NOT_STARTED"
LOCK_STATE_PREFLIGHT = "PREFLIGHT_VALIDATED"
LOCK_STATE_RESERVED = "CALL_RESERVED"
LOCK_STATE_MAY_HAVE_BEEN_SENT = "CALL_MAY_HAVE_BEEN_SENT"
LOCK_STATE_RESPONSE_RECEIVED = "RESPONSE_RECEIVED"
LOCK_STATE_RESPONSE_VALIDATED = "RESPONSE_VALIDATED"
LOCK_STATE_FAILED = "FAILED"
LOCK_STATE_UNCERTAIN = "UNCERTAIN"

LOCK_CONSUMED_STATES = frozenset(
    {
        LOCK_STATE_RESERVED,
        LOCK_STATE_MAY_HAVE_BEEN_SENT,
        LOCK_STATE_RESPONSE_RECEIVED,
        LOCK_STATE_RESPONSE_VALIDATED,
        LOCK_STATE_FAILED,
        LOCK_STATE_UNCERTAIN,
    }
)

LOCK_RESUME_WITHOUT_RECALL = frozenset({LOCK_STATE_RESPONSE_VALIDATED})
LOCK_STOP_STATES = frozenset(
    {
        LOCK_STATE_RESERVED,
        LOCK_STATE_MAY_HAVE_BEEN_SENT,
        LOCK_STATE_RESPONSE_RECEIVED,
        LOCK_STATE_FAILED,
        LOCK_STATE_UNCERTAIN,
    }
)

REVIEW_NO_ISSUE = "NO_ISSUE_DETECTED"
REVIEW_RECOMMENDED = "REVIEW_RECOMMENDED"
REVIEW_POTENTIAL = "POTENTIAL_SUBSTANTIVE_ISSUE"
REVIEW_UNDETERMINED = "UNDETERMINED"

FORBIDDEN_PROMPT_CLAUSES = (
    "High stylistic freedom",
    "Stylistic expansion is allowed",
)
FORBIDDEN_PROMPTS = (
    "book-generator-1.0",
    "book-generator-1.0.1",
    "book-generator-faithful-restatement-1.0-candidate",
)

AUDIT_DIRNAME = "book_generation_4b223_batch01"
AUDIT_REAL_PARENT = "real"
AUDIT_CHAPTERS_DIR = "chapters"
AUDIT_PREFLIGHT = "preflight.json"
AUDIT_HASHES_PRE = "canonical_hashes_pre.json"
AUDIT_AUTHORIZATION = "batch_authorization.json"
AUDIT_LOCK = LOCK_NAME
AUDIT_BATCH_LOCK = BATCH_LOCK_NAME
AUDIT_PROMPT = "prompt_manifest.json"
AUDIT_CONTEXT = "source_context_manifest.json"
AUDIT_COST = "cost_preflight.json"
AUDIT_RESPONSE_RAW = "provider_response_raw.json"
AUDIT_USAGE = "provider_usage.json"
AUDIT_CANDIDATE_JSON = "chapter_candidate.json"
AUDIT_CANDIDATE_MD = "chapter_candidate.md"
AUDIT_STRUCTURAL = "structural_validation.json"
AUDIT_IDEA = "idea_traceability_review.json"
AUDIT_EX_REF = "ex_ref_traceability_review.json"
AUDIT_EDITORIAL = "editorial_readiness_review.json"
AUDIT_HASHES_POST = "canonical_hashes_post.json"
AUDIT_READINESS = "readiness.json"
AUDIT_TESTS = "regression_tests.json"
AUDIT_MANIFEST = "batch_manifest.json"
AUDIT_LEDGER = "batch_budget_ledger.json"
AUDIT_PROGRESS = "batch_progress.json"
AUDIT_SUMMARY = "batch_summary.json"
REPORT_NAME = "PHASE_4B223_BATCH01_REAL_GENERATION_REPORT.md"

PREP_AUDIT_DIRNAME = "book_batch_preparation_4b222"
PREP_PLAN_NAME = "batch_generation_plan.json"
PREP_ENVELOPE_NAME = "batch_cost_envelope.json"
PREP_INVENTORY_NAME = "remaining_17_chapters_inventory.json"
CH012_MANIFEST_REL = "audit/book_editorial_acceptance_4b219/ch012_accepted_editorial_manifest.json"
CH018_MANIFEST_REL = "audit/book_batch_preparation_4b222/ch018_accepted_editorial_manifest.json"

NEXT_ACTION = (
    "HUMAN EDITORIAL REVIEW OF BATCH-01 CANDIDATES. "
    "DO NOT LAUNCH BATCH-02. DO NOT GENERATE THE REMAINING 13 CHAPTERS. "
    "DO NOT RETRY A FAILED CHAPTER. DO NOT SPEND THE REMAINING BUDGET."
)
READY_FOR_BATCH02 = False

__all__ = [
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_CHAPTER_IDS",
    "BATCH_ID",
    "BUDGET_CAP_USD",
    "CANONICAL_PYTHON",
    "EXPECTED_ACCEPTED_JSON_SHA256",
    "EXPECTED_ACCEPTED_MD_SHA256",
    "EXPECTED_CH018_JSON_SHA256",
    "EXPECTED_CH018_MD_SHA256",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_LOCK_SHA256",
    "EXPECTED_ORIGINAL_JSON_SHA256",
    "EXPECTED_ORIGINAL_MD_SHA256",
    "EXPECTED_PROMPT_1_1_SHA256",
    "EXPECTED_SOURCE_MAP",
    "EXPECTED_TRANSCRIPT",
    "LOCK_CONSUMED_STATES",
    "LOCK_NAME",
    "MODEL",
    "PHASE",
    "PROMPT_VERSION",
    "PROVIDER",
    "SONNET_INPUT_COST_PER_1M",
    "SONNET_OUTPUT_COST_PER_1M",
]
