"""Rapport markdown 3B.7.7A.44."""

from __future__ import annotations

from typing import Any, Mapping

from app.source_analysis_v31_global_v30_grammar_canary.constants import (
    CANARY_MAX_OUTPUT_TOKENS,
    LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
    MODEL,
    PRODUCTION_ABSOLUTE_HEADROOM,
    PRODUCTION_CONSERVATIVE_OUTPUT_TOKENS,
    PRODUCTION_EXPECTED_OUTPUT_TOKENS,
    PRODUCTION_HARD_PLANNING_TOKENS,
    PRODUCTION_HARD_UTILIZATION,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PRODUCTION_OUTPUT_RISK,
    PROMPT_VERSION,
    RELATION_QUALITY_TECHNICAL_DEBT,
    SCHEMA_ADAPTED_BYTES,
    SCHEMA_HASH,
    SCHEMA_RAW_BYTES,
    TRANSPORT_VERSION,
)
from app.source_analysis_v31_global_v30_grammar_canary.runner import CanaryRunResult


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(
    result: CanaryRunResult,
    *,
    tests: str,
    extra_header: Mapping[str, Any] | None = None,
) -> str:
    exe = result.execution or {}
    dry = result.dry_run or {}
    extra = dict(extra_header or {})
    verdict = exe.get("result") or extra.get("result") or result.mode
    schema_raw = exe.get("schema_raw_bytes") or dry.get("schema_raw_bytes") or SCHEMA_RAW_BYTES
    schema_adapted = (
        exe.get("schema_adapted_bytes")
        or dry.get("schema_adapted_bytes")
        or SCHEMA_ADAPTED_BYTES
    )
    schema_hash = exe.get("schema_hash") or dry.get("schema_hash") or SCHEMA_HASH
    cost = (exe.get("cost") or {}).get("display") or (exe.get("cost") or {}).get("total_cost")
    elapsed = exe.get("provider_elapsed_ms")
    elapsed_display = f"{elapsed} ms" if elapsed is not None else "n/a"
    estimator_error = exe.get("estimator_error") or {}
    error_display = "n/a"
    if estimator_error:
        error_display = (
            f"{estimator_error.get('tokens')} tokens / "
            f"{estimator_error.get('percent')}%"
        )
    predicted = exe.get("predicted_canary_output")
    if predicted is None:
        predicted = ((dry.get("output_estimate") or {}).get("expected_provider_tokens"))
    actual_calls = exe.get("actual_calls") if exe else result.anthropic_post_attempts
    reuse_eq = exe.get("reuse_text_exact_equality")
    reuse_display = f"{reuse_eq}%" if reuse_eq is not None else "n/a"
    hard_util = f"{PRODUCTION_HARD_UTILIZATION * 100:.1f}%"
    lines = [
        "# PHASE 3B.7.7A.44 — GLOBAL CONSOLIDATION V3.0 REUSE GRAMMAR CANARY",
        "",
        "## Result",
        "",
        str(verdict),
        "",
        "AUTHORIZED PROVIDER CALLS =",
        "1",
        "",
        "ACTUAL PROVIDER CALLS =",
        str(actual_calls if actual_calls is not None else 0),
        "",
        "SUCCESSFUL PROVIDER CALLS =",
        str(exe.get("successful_calls") if exe else 0),
        "",
        "RETRIES =",
        "0",
        "",
        "PASTORAL DATA SENT =",
        "NO",
        "",
        "REAL CONSOLIDATION EXECUTED =",
        "NO",
        "",
        "MODEL =",
        MODEL,
        "",
        "PROMPT =",
        PROMPT_VERSION,
        "",
        "TRANSPORT =",
        TRANSPORT_VERSION,
        "",
        "SCHEMA RAW / ADAPTED =",
        f"{_dash(schema_raw)} / {_dash(schema_adapted)}",
        "",
        "SCHEMA HASH =",
        _dash(schema_hash),
        "",
        "SCHEMA IDENTITY =",
        _dash(exe.get("schema_identity") or dry.get("schema_identity")),
        "",
        "HTTP =",
        _dash(exe.get("http_status")),
        "",
        "FINISH =",
        _dash(exe.get("finish_reason")),
        "",
        "THINKING =",
        "disabled",
        "",
        "THINKING TOKENS =",
        _dash(exe.get("thinking_tokens")),
        "",
        "CANARY MAX OUTPUT =",
        str(exe.get("max_output_canary") or CANARY_MAX_OUTPUT_TOKENS),
        "",
        "REQUEST ID =",
        _dash(exe.get("request_id")),
        "",
        "INPUT TOKENS =",
        _dash(exe.get("input_tokens") or exe.get("provider_input")),
        "",
        "OUTPUT TOKENS =",
        _dash(exe.get("output_tokens")),
        "",
        "COST =",
        _dash(cost),
        "",
        "ELAPSED =",
        elapsed_display,
        "",
        "STRUCTURED PARSE =",
        _dash(exe.get("structured_parse")),
        "",
        "TRANSPORT DECODER =",
        _dash(exe.get("transport_decoder")),
        "",
        "HANDLES =",
        _dash(exe.get("handle_validation")),
        "",
        "LOCAL IDEAS =",
        _dash(exe.get("local_ideas")),
        "",
        "GLOBAL IDEAS =",
        _dash(exe.get("global_ideas")),
        "",
        "SINGLE-MEMBER GLOBAL IDEAS =",
        _dash(exe.get("single_member_global_ideas")),
        "",
        "MULTI-MEMBER GLOBAL IDEAS =",
        _dash(exe.get("multi_member_global_ideas")),
        "",
        "SINGLE_MEMBER_WITH_V =",
        _dash(exe.get("SINGLE_MEMBER_WITH_V")),
        "",
        "MULTI_MEMBER_WITHOUT_V =",
        _dash(exe.get("MULTI_MEMBER_WITHOUT_V")),
        "",
        "MERGE V MAX LENGTH =",
        _dash(exe.get("merge_v_max_length")),
        "",
        "REUSE TEXT EXACT EQUALITY =",
        reuse_display,
        "",
        "NON_IDEA_IN_MEMBERS =",
        _dash(exe.get("NON_IDEA_IN_MEMBERS")),
        "",
        "NON_IDEA_IN_DROP =",
        _dash(exe.get("NON_IDEA_IN_DROP")),
        "",
        "RELATION_HINT_IN_MEMBERS =",
        _dash(exe.get("RELATION_HINT_IN_MEMBERS")),
        "",
        "RELATION_HINT_IN_DROP =",
        _dash(exe.get("RELATION_HINT_IN_DROP")),
        "",
        "IDEA ACCOUNTABILITY =",
        _dash(exe.get("accountability_coverage")),
        "",
        "DERIVED KEEP =",
        _dash(exe.get("keep_count")),
        "",
        "DERIVED MERGE_EQUIVALENT =",
        _dash(exe.get("merge_equivalent_count")),
        "",
        "DERIVED DROP =",
        _dash(exe.get("drop_count")),
        "",
        "DERIVED SRC UNION =",
        _dash(exe.get("derived_src_union")),
        "",
        "GLOBAL VALIDATOR =",
        _dash(exe.get("global_validator")),
        "",
        "CANONICAL RECONSTRUCTION =",
        _dash(exe.get("canonical_reconstruction")),
        "",
        "CANONICAL VALIDATION =",
        _dash(exe.get("canonical_validation")),
        "",
        "EMPTY RELATIONS VALID =",
        _dash(exe.get("empty_relations_valid")),
        "",
        "INVALID TRANSPORT PUBLICATION GATE =",
        _dash(exe.get("invalid_transport_publication_gate")),
        "",
        "DETERMINISTIC REPLAY =",
        _dash(exe.get("deterministic_replay")),
        "",
        "SEMANTIC FIXTURE REVIEW =",
        _dash(exe.get("semantic_fixture_review")),
        "",
        "GLOBAL_TRANSPORT_3_0_GRAMMAR_PROOF =",
        _dash(exe.get("global_transport_3_0_grammar_proof")),
        "",
        "GLOBAL_CONSOLIDATION_3_0_REUSE_CONTRACT_CANARY =",
        _dash(exe.get("global_consolidation_3_0_reuse_contract_canary")),
        "",
        "PREDICTED CANARY OUTPUT =",
        _dash(predicted),
        "",
        "ACTUAL CANARY OUTPUT =",
        _dash(exe.get("actual_canary_output") or exe.get("output_tokens")),
        "",
        "ESTIMATOR ERROR =",
        error_display,
        "",
        "ACTUAL CHARS/TOKEN =",
        _dash(exe.get("actual_chars_per_token")),
        "",
        "PRODUCTION EXPECTED =",
        str(PRODUCTION_EXPECTED_OUTPUT_TOKENS),
        "",
        "PRODUCTION CONSERVATIVE =",
        str(PRODUCTION_CONSERVATIVE_OUTPUT_TOKENS),
        "",
        "PRODUCTION HARD =",
        str(PRODUCTION_HARD_PLANNING_TOKENS),
        "",
        "PRODUCTION MAX_OUTPUT =",
        str(PRODUCTION_MAX_OUTPUT_TOKENS),
        "",
        "HARD UTILIZATION =",
        hard_util,
        "",
        "ABSOLUTE HEADROOM =",
        str(PRODUCTION_ABSOLUTE_HEADROOM),
        "",
        "PRODUCTION OUTPUT RISK =",
        PRODUCTION_OUTPUT_RISK,
        "",
        "LOCAL EXTRACTION FUNCTIONALLY FROZEN =",
        LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        RELATION_QUALITY_TECHNICAL_DEBT,
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        _dash(extra.get("new_failures") or "0"),
        "",
        "READY_FOR_REAL_GLOBAL_CONSOLIDATION_PREFLIGHT =",
        _dash(exe.get("ready_for_real_global_consolidation_preflight") or "NO"),
        "",
        "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY =",
        "NO",
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## Notes",
        "",
        f"Authorization scope = {result.authorization_scope}",
        "",
        f"Error = {_dash(result.error)}",
        "",
        "A.44 is a tiny synthetic grammar + reuse-contract canary for transport 3.0.",
        "",
        "Tiny-canary output size cannot automatically promote real-call readiness.",
        "",
        "A.44 does not authorize real consolidation even if the contract canary passes.",
        "",
        "WAIT FOR HUMAN REVIEW.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
