"""
Phase 4B.2.20 — Controlled scale-up preparation and first-chapter readiness.

STRICTLY OFFLINE. Isolated from production. Zero provider calls.
Does not generate remaining chapters. Does not regenerate CH012.
Does not activate prompt 1.1 globally. Does not publish book.json.
Does not write the production cache. Does not promote the Semantic Gate.
"""

from __future__ import annotations

from decimal import Decimal

from app.book_authorial_voice_4b218.constants import (
    AUTHORIAL_VOICE_POLICY_VERSION,
    FAITHFUL_PROMPT_1_0_VERSION,
    FAITHFUL_PROMPT_1_1_VERSION,
    HISTORICAL_PROMPT_V10,
    HISTORICAL_PROMPT_V101,
)
from app.book_editorial_acceptance_4b219.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B219_SCOPE,
    CHAPTER_ID as ACCEPTED_CHAPTER_ID,
    EXPECTED_ACCEPTED_JSON_SHA256,
    EXPECTED_ACCEPTED_MD_SHA256,
    EXPECTED_LOCK_SHA256,
    EXPECTED_ORIGINAL_JSON_SHA256,
    EXPECTED_ORIGINAL_MD_SHA256,
    FAITHFUL_PROMPT_1_1 as FAITHFUL_PROMPT_1_1_ID,
    HISTORICAL_4B217_STATUS,
    HISTORICAL_4B218_STATUS,
    REMAINING_CHAPTER_COUNT,
    TOTAL_CHAPTER_COUNT,
)
from app.book_editorial_alignment_4b216.constants import (
    COVERAGE_CONTRACT_VERSION,
    EDITORIAL_POLICY_VERSION,
    HISTORICAL_SEMANTIC_CONTRACT,
)
from app.book_generation.constants import (
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION_V10,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    MODEL,
    PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_generation_4b217.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B217_SCOPE,
    HISTORICAL_CH012_CENTRAL_USD,
    SONNET_INPUT_COST_PER_1M,
    SONNET_OUTPUT_COST_PER_1M,
    TERRA_H01_ANALOG_USD,
)
from app.book_authorial_voice_4b218.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B218_SCOPE,
)
from app.book_semantic_gate_4b215.constants import (
    HISTORICAL_4B210_STATUS,
    HISTORICAL_4B211_STATUS,
    HISTORICAL_4B212_STATUS,
    HISTORICAL_4B213_STATUS,
    HISTORICAL_4B214_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
)
from app.book_semantic_gate_4b23.constants import EXPECTED_CLEAN_TRANSCRIPT
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE

PHASE = "4B.2.20"
PHASE_NAME = "CONTROLLED_SCALE_UP_PREPARATION_AND_FIRST_CHAPTER_READINESS"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SCALE_UP_PREPARATION_4B220_CONTROLLED_SCALE_UP_PREPARATION_"
    "AND_FIRST_CHAPTER_READINESS_ONLY"
)

AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = False
REAL_CHAPTER_GENERATION_AUTHORIZED = False
REAL_PROVIDERS_ENABLED = False
RETRIES = 0
FALLBACKS = 0
SDK_MAX_RETRIES = 0

PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
COVERAGE_CONTROL_ACTIVATED = False
FAITHFUL_PROMPT_ACTIVATED = False
FAITHFUL_PROMPT_1_1_ACTIVATED = False
EDITORIAL_POLICY_ACTIVATED = False
AUTHORIAL_VOICE_POLICY_ACTIVATED = False
SEMANTIC_GATE_202_ENABLED = False
SEMANTIC_CERTIFICATION_PERFORMED = False
BOOK_JSON_PUBLICATION = False

CODE_VERSION = "app.book_scale_up_preparation_4b220"
PROGRESS_MANIFEST_VERSION = "scale-up-progress-manifest-4b220-1.0"
CONTRACT_MATRIX_VERSION = "generation-contract-matrix-4b220-1.0"
PROMPT_SELECT_VERSION = "isolated-prompt-11-select-4b220-1.0"

FAITHFUL_PROMPT_1_0 = FAITHFUL_PROMPT_1_0_VERSION
FAITHFUL_PROMPT_1_1 = FAITHFUL_PROMPT_1_1_ID
HISTORICAL_PROMPT_V10_ID = HISTORICAL_PROMPT_V10
HISTORICAL_PROMPT_V101_ID = HISTORICAL_PROMPT_V101
NARRATIVE_VOICE_CONTRACT = AUTHORIAL_VOICE_POLICY_VERSION
EDITORIAL_POLICY = EDITORIAL_POLICY_VERSION
COVERAGE_CONTRACT = COVERAGE_CONTRACT_VERSION
TRANSPORT_VERSION = BOOK_GENERATION_TRANSPORT_VERSION
VALIDATOR_VERSION = BOOK_GENERATOR_VALIDATOR_VERSION
HISTORICAL_SEMANTIC = HISTORICAL_SEMANTIC_CONTRACT

assert FAITHFUL_PROMPT_1_0 == "book-generator-faithful-restatement-1.0-candidate"
assert FAITHFUL_PROMPT_1_1 == "book-generator-faithful-restatement-1.1-candidate"
assert FAITHFUL_PROMPT_1_1 == FAITHFUL_PROMPT_1_1_VERSION
assert NARRATIVE_VOICE_CONTRACT == "authorial-voice-preservation-1.0-candidate"
assert EDITORIAL_POLICY == "faithful-teaching-book-editorial-policy-1.0-candidate"
assert HISTORICAL_PROMPT_V101_ID == BOOK_GENERATOR_PROMPT_VERSION == "book-generator-1.0.1"
assert HISTORICAL_PROMPT_V10_ID == BOOK_GENERATOR_PROMPT_VERSION_V10 == "book-generator-1.0"
assert TRANSPORT_VERSION == "book-generation-transport-1.0"
assert VALIDATOR_VERSION == "book-generation-validator-1.0.1"
assert HISTORICAL_SEMANTIC == "book-semantic-validator-2.0.2-candidate"
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert CONSUMED_4B217_SCOPE == (
    "BOOK_GENERATION_4B217_CH012_FAITHFUL_REAL_PILOT_GENERATION_ONLY"
)
assert CONSUMED_4B218_SCOPE.startswith("BOOK_AUTHORIAL_VOICE_4B218_")
assert CONSUMED_4B219_SCOPE.startswith("BOOK_EDITORIAL_ACCEPTANCE_4B219_")

ACCEPTED_CHAPTER = ACCEPTED_CHAPTER_ID
assert ACCEPTED_CHAPTER == "CH012"
assert REMAINING_CHAPTER_COUNT == 18
assert TOTAL_CHAPTER_COUNT == 19

EXPECTED_FIRST_CHAPTER_ID = "CH018"
EXPECTED_FIRST_CHAPTER_TITLE = "Testimonies of Resurrection"
EXPECTED_FIRST_CHAPTER_SECTIONS = ("SEC067", "SEC068", "SEC069", "SEC070")
EXPECTED_FIRST_CHAPTER_IDEA_COUNT = 11
EXPECTED_FIRST_CHAPTER_SECTION_COUNT = 4

STATUS_PENDING = "PENDING"
STATUS_READY = "READY"
STATUS_AUTHORIZED = "AUTHORIZED"
STATUS_GENERATING = "GENERATING"
STATUS_GENERATED = "GENERATED"
STATUS_STRUCTURE_FAILED = "STRUCTURE_FAILED"
STATUS_AWAITING_REVIEW = "AWAITING_REVIEW"
STATUS_ACCEPTED = "ACCEPTED"
STATUS_BLOCKED = "BLOCKED"

PROGRESS_STATES = (
    STATUS_PENDING,
    STATUS_READY,
    STATUS_AUTHORIZED,
    STATUS_GENERATING,
    STATUS_GENERATED,
    STATUS_STRUCTURE_FAILED,
    STATUS_AWAITING_REVIEW,
    STATUS_ACCEPTED,
    STATUS_BLOCKED,
)

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_TRANSCRIPT = EXPECTED_CLEAN_TRANSCRIPT

assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert AUTHORIZED_TERRA_CALLS == 0
assert AUTHORIZED_SONNET_CALLS == 0
assert AUTHORIZED_ANTHROPIC_CALLS == 0
assert AUTHORIZED_OPENAI_CALLS == 0
assert PUBLICATION_AUTHORIZED is False
assert REAL_CHAPTER_GENERATION_AUTHORIZED is False
assert FAITHFUL_PROMPT_1_1_ACTIVATED is False
assert SEMANTIC_CERTIFICATION_PERFORMED is False
assert CANONICAL_PYTHON.endswith("python.exe")

EXPECTED_PROMPT_1_1_SHA256 = (
    "e39084dc9ed3b048bfdaa2e112b380d15957085eeb613dd74c97a32b880cec50"
)
EXPECTED_PROMPT_1_1_SYSTEM_SHA256 = (
    "f1ba90063e8dd54ad45924924361ff3f7409132983185b2b6d974df03706f901"
)
EXPECTED_PROMPT_1_1_INSTRUCTIONS_SHA256 = (
    "aad6cddbf6418fda0092b90c8295e3801f8413dce79234b97e652e0b7f6f41ed"
)

CH012_ACTUAL_COST_USD = Decimal("0.036152")
CH012_ACTUAL_INPUT_TOKENS = 8586
CH012_ACTUAL_OUTPUT_TOKENS = 1898
H01_ANALOG_USD = TERRA_H01_ANALOG_USD
HISTORICAL_CHAPTER_CENTRAL_USD = HISTORICAL_CH012_CENTRAL_USD
AUTHORIZED_SPEND_USD = Decimal("0")
PRICING_EFFECTIVE_DATE = "2026-09-18"
PESSIMISTIC_CHARS_PER_TOKEN = Decimal("1.9365384615384615")

HISTORICAL_4B215_STATUS = "PARTIAL"
HISTORICAL_4B216_STATUS = "PASS"
HISTORICAL_4B219_STATUS = "PASS"
HISTORICAL_4B220_DOES_NOT_REQUALIFY = True

AUDIT_DIRNAME = "book_scale_up_preparation_4b220"
AUDIT_PREFLIGHT = "preflight.json"
AUDIT_HASHES_PRE = "canonical_hashes_pre.json"
AUDIT_INVENTORY = "remaining_chapters_inventory.json"
AUDIT_SELECTION = "first_chapter_selection.json"
AUDIT_CONTRACT = "generation_contract_matrix.json"
AUDIT_PROMPT = "prompt_11_readiness.json"
AUDIT_CONTEXT = "first_chapter_source_context_manifest.json"
AUDIT_COST = "scale_up_cost_envelope.json"
AUDIT_PLAN = "scale_up_execution_plan.json"
AUDIT_PROGRESS = "scale_up_progress_manifest.json"
AUDIT_STOP = "hard_stop_conditions.json"
AUDIT_TESTS = "regression_tests.json"
AUDIT_HASHES_POST = "canonical_hashes_post.json"
AUDIT_READINESS = "readiness.json"
REPORT_NAME = "PHASE_4B220_CONTROLLED_SCALE_UP_PREPARATION_REPORT.md"

NEXT_ACTION = (
    "HUMAN DECISION ON A DISTINCT ONE-CHAPTER AUTHORIZATION FOR THE "
    "SELECTED FIRST REMAINING CHAPTER. DO NOT RUN 18 CHAPTERS."
)
READY_FOR_18_CHAPTER_RUN = False

__all__ = [
    "ACCEPTED_CHAPTER",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_SPEND_USD",
    "CANONICAL_PYTHON",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_FIRST_CHAPTER_ID",
    "EXPECTED_SOURCE_MAP",
    "EXPECTED_TRANSCRIPT",
    "FAITHFUL_PROMPT_1_1",
    "PHASE",
    "PROGRESS_STATES",
]
