"""
Phase 4B.2.10 — Semantic Gate 2.0 offline contract hardening and real-canary readiness.

STRICTLY OFFLINE. Isolated from production. Zero provider calls.
Historical canaries are not relaunched. Frozen 1.0 / 1.1 / 1.1.1 / 1.1.2 /
1.1.3-candidate / 2.0-proposal / 2.0-candidate are not modified.
2.0.1-candidate is not activated. Transport 2.0 is not enabled for a real call.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
)
from app.book_semantic_gate_4b23.reasons import REASON_CODES, REASON_DEFINITIONS
from app.book_semantic_gate_4b24.constants import (
    CONNECTIVE_CASE_ID,
    FUNERAL_CASE_ID,
    NEGATIVE_CASE_IDS,
    P3_CASE_ID,
    P8_CASE_ID,
    POSITIVE_CASE_IDS,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    SEMANTIC_TOKEN_BUDGET,
)
from app.book_semantic_gate_4b261.constants import CANDIDATE_PROMPT_VERSION
from app.book_semantic_gate_4b271.constants import (
    DISPUTED_CLAUSE as H01_DISPUTED_CLAUSE,
    TRANSPORT_VERSION_11,
)
from app.book_semantic_gate_4b272.constants import DISPUTED_CAUSAL_CLAUSE
from app.book_semantic_gate_4b274.constants import (
    OVERFIT_TOKENS as OVERFIT_TOKENS_112,
    PROMPT_VERSION_112,
)
from app.book_semantic_gate_4b275.constants import (
    EXPECTED_PROMPT_113_SHA256,
    OVERFIT_TOKENS as OVERFIT_TOKENS_113,
    PROMPT_VERSION_113,
)
from app.book_semantic_gate_4b276.constants import DISPUTED_CLAUSE as H11_DISPUTED_CLAUSE
from app.book_semantic_gate_4b28.constants import (
    H01_CASE_HANDLE,
    H01_CASE_ID,
    H01_COMPLETION_TOKENS,
    H01_COST_USD,
    H01_EVIDENCE_HANDLES,
    H01_HUMAN_LABEL,
    H01_INPUT_TOKENS,
    H01_REASONING_TOKENS,
    H01_REQUEST_SHA256,
    H02_CASE_HANDLE,
    H02_CASE_ID,
    H02_EVIDENCE_HANDLES,
    H02_HUMAN_LABEL,
    H02_REQUEST_SHA256,
    H11_CASE_HANDLE,
    H11_CASE_ID,
    H11_COST_USD,
    H11_EVIDENCE_HANDLES,
    H11_HUMAN_LABEL,
    H11_INPUT_TOKENS,
    H11_COMPLETION_TOKENS,
    H11_REASONING_TOKENS,
    H11_REQUEST_SHA256,
    HISTORICAL_4B261_STATUS,
    HISTORICAL_4B262_STATUS,
    HISTORICAL_4B26_STATUS,
    HISTORICAL_4B271_STATUS,
    HISTORICAL_4B272_STATUS,
    HISTORICAL_4B273_STATUS,
    HISTORICAL_4B274_STATUS,
    HISTORICAL_4B275_STATUS,
    HISTORICAL_4B276_STATUS,
    HISTORICAL_4B277_STATUS,
    HISTORICAL_4B27_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
    PROMPT_VERSION_11,
    PROMPT_VERSION_20_PROPOSAL,
    TARGET_ARCHITECTURE,
    TRANSPORT_VERSION_20_PROPOSAL,
)
from app.book_semantic_gate_4b29.constants import (
    HISTORICAL_4B28_STATUS,
    OFFSET_CONVENTION,
    PROMPT_VERSION_20_CANDIDATE,
    TRANSPORT_VERSION_20_CANDIDATE,
)

PHASE = "4B.2.10"
PHASE_NAME = "SEMANTIC_GATE_20_OFFLINE_CONTRACT_HARDENING_AND_REAL_CANARY_READINESS"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B210_SEMANTIC_GATE_20_OFFLINE_CONTRACT_HARDENING_"
    "AND_REAL_CANARY_READINESS_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
REAL_TERRA_CANARY_AUTHORIZED = False
SDK_MAX_RETRIES = 0
RETRIES = 0
FALLBACKS = 0

SEMANTIC_GATE_20_ENABLED = False
SEMANTIC_GATE_201_ENABLED = False
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"
TOKEN_FIELD = "max_completion_tokens"
PRODUCTION_SDK_METHOD = "client.chat.completions.create"
PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION

PROMPT_VERSION_20_ACTIVATED = False
TRANSPORT_VERSION_20_ACTIVATED = False
PROMPT_VERSION_201_CANDIDATE = "book-semantic-validator-2.0.1-candidate"
PROMPT_VERSION_201_ACTIVATED = False
TRANSPORT_VERSION_201_CANDIDATE = None

CODE_VERSION = "app.book_semantic_gate_4b210"

SELECTED_CASE_HANDLE = H01_CASE_HANDLE
SELECTED_CASE_ID = "4b210_h01"
SELECTED_CASE_ROLE = "historical_positive_problematic"
SELECTED_CASE_ORIGIN = "REPRISE_OF_HISTORICAL_H01_SUPPORTED_PARAPHRASE"
SELECTED_CASE_HUMAN_LABEL = H01_HUMAN_LABEL
SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY = True
SELECTED_CASE_ACCEPTED_CLASSES = (CLASS_SUPPORTED,)
TARGET_FAILURE_FAMILY = "FALSE_REJECTION_OF_FAITHFUL_PARAPHRASE"
CHAPTER_HANDLE = "CH016"

REQUEST_SERIALIZATION = "json.dumps(payload, ensure_ascii=False, sort_keys=True)"
REQUEST_HASH_ENCODING = "utf-8"
REQUEST_HASH_ALGORITHM = "sha256"

HISTORICAL_4B29_STATUS = "PASS"

OVERFIT_TOKENS = tuple(dict.fromkeys(OVERFIT_TOKENS_112 + OVERFIT_TOKENS_113))

H02_COST_USD = 0.066036
H02_INPUT_TOKENS = 1692
H02_COMPLETION_TOKENS = 5221
H02_REASONING_TOKENS = 4595

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert SELECTED_CASE_HANDLE == "h01"
assert SELECTED_CASE_ID == "4b210_h01"
assert SELECTED_CASE_HUMAN_LABEL == CLASS_SUPPORTED
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
assert TOKEN_FIELD == "max_completion_tokens"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert PROMPT_VERSION_HISTORICAL == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION_HISTORICAL == "book-semantic-validation-transport-1.0"
assert PROMPT_VERSION_11 == "book-semantic-validator-1.1-candidate"
assert TRANSPORT_VERSION_11 == "book-semantic-validation-transport-1.1-candidate"
assert PROMPT_VERSION_112 == "book-semantic-validator-1.1.2-candidate"
assert PROMPT_VERSION_113 == "book-semantic-validator-1.1.3-candidate"
assert PROMPT_VERSION_20_PROPOSAL == "book-semantic-validator-2.0-proposal"
assert TRANSPORT_VERSION_20_PROPOSAL == "book-semantic-validation-transport-2.0-proposal"
assert PROMPT_VERSION_20_CANDIDATE == "book-semantic-validator-2.0-candidate"
assert TRANSPORT_VERSION_20_CANDIDATE == "book-semantic-validation-transport-2.0-candidate"
assert PROMPT_VERSION_201_CANDIDATE != PROMPT_VERSION_20_CANDIDATE
assert PROMPT_VERSION_201_CANDIDATE != PROMPT_VERSION_20_PROPOSAL
assert PROMPT_VERSION_201_CANDIDATE != PROMPT_VERSION_113
assert TRANSPORT_VERSION_201_CANDIDATE is None
assert PROMPT_VERSION_20_ACTIVATED is False
assert PROMPT_VERSION_201_ACTIVATED is False
assert TRANSPORT_VERSION_20_ACTIVATED is False
assert SEMANTIC_GATE_20_ENABLED is False
assert SEMANTIC_GATE_201_ENABLED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert REAL_TERRA_CANARY_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False
assert SDK_MAX_RETRIES == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert H01_REQUEST_SHA256 == (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
assert H02_REQUEST_SHA256 == (
    "5ace261296d808437910f8f9efe247a80daebbb2237bc8af46bda56bf98d7897"
)
assert H11_REQUEST_SHA256 == (
    "b3cc1574858acdd5bdd0e223aa136d5058c4eb1deb1495cd9ad312d332e8c30f"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert EXPECTED_PROMPT_113_SHA256 == (
    "9febdcdda08a31179081564ac33842b434dcc8bcb95ca9d96f386b63addb3059"
)
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert HISTORICAL_4B262_STATUS == "PASS"
assert HISTORICAL_4B27_STATUS == "PARTIAL"
assert HISTORICAL_4B271_STATUS == "PASS"
assert HISTORICAL_4B272_STATUS == "PASS"
assert HISTORICAL_4B273_STATUS == "PARTIAL"
assert HISTORICAL_4B274_STATUS == "PASS"
assert HISTORICAL_4B275_STATUS == "PASS"
assert HISTORICAL_4B276_STATUS == "PASS"
assert HISTORICAL_4B277_STATUS == "PARTIAL"
assert HISTORICAL_4B28_STATUS == "PASS"
assert HISTORICAL_4B29_STATUS == "PASS"
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_H11_STATUS == "PARTIAL"
assert H01_DISPUTED_CLAUSE == "that fear can calculate or bargain with"
assert DISPUTED_CAUSAL_CLAUSE == (
    "because it still works wherever it is not resisted by truth"
)
assert H11_DISPUTED_CLAUSE == (
    "which means that every believer is guaranteed a fearless death"
)
assert TARGET_ARCHITECTURE == "C_HYBRID_TWO_LEVEL_WITH_CONSERVATIVE_PRESEGMENTATION"
assert len(REASON_CODES) == 16
assert CLASSIFICATIONS == (
    CLASS_SUPPORTED,
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    CLASS_NON_SUBSTANTIVE,
)
assert CANONICAL_PYTHON_EXECUTABLE.endswith("python.exe")
assert CANDIDATE_PROMPT_VERSION == PROMPT_VERSION_11
assert SELECTED_CASE_ID not in POSITIVE_CASE_IDS
assert SELECTED_CASE_ID not in NEGATIVE_CASE_IDS
assert H01_CASE_ID == "4b22_p2_supported"

AUDIT_DIRNAME = "book_semantic_gate_4b210"
AUDIT_INVENTORY = "technical_inventory.json"
AUDIT_CONTRACT = "contract_20_review.json"
AUDIT_INSTRUCTIONS = "semantic_instruction_review.json"
AUDIT_UNITS = "unit_integrity_review.json"
AUDIT_TRANSPORT = "transport_20_preflight.json"
AUDIT_SDK = "sdk_compatibility.json"
AUDIT_SELECTION = "candidate_selection.json"
AUDIT_REQUEST = "selected_canary_provider_request.json"
AUDIT_REQUEST_SHA = "selected_canary_request_sha256.txt"
AUDIT_LEAK = "label_leakage_check.json"
AUDIT_DETERMINISM = "request_determinism.json"
AUDIT_SERIALIZATION = "sdk_serialization_preflight.json"
AUDIT_FAKEAI = "fakeai_contract_tests.json"
AUDIT_CRITERIA = "canary_success_criteria.json"
AUDIT_STOP = "strategic_stop_rule.json"
AUDIT_COST = "cost_estimate.json"
AUDIT_SAFETY = "provider_safety.json"
AUDIT_TESTS = "offline_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b210_index.json"
REPORT_NAME = "PHASE_4B210_SEMANTIC_GATE_20_OFFLINE_CONTRACT_HARDENING_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_SEMANTIC_GATE_20_HUMAN_REVIEW = True
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False
