"""Constantes 3B.7.7A.38 — premier canary réel de consolidation globale."""

from __future__ import annotations

from app.source_analysis.writer import source_map_path
from app.source_analysis_v31_global_canary_forensics.constants import (
    A34_SCHEMA_ADAPTED,
    A34_SCHEMA_HASH,
    A34_SCHEMA_RAW,
    A34_STATUS_PRESERVED,
    A35_STATUS_PRESERVED,
    NEXT_PROMPT_VERSION,
    NEXT_SCHEMA_ADAPTED_BYTES,
    NEXT_SCHEMA_HASH,
    NEXT_SCHEMA_RAW_BYTES,
    NEXT_TRANSPORT_VERSION,
    OLD_PROMPT_VERSION,
    OLD_TRANSPORT_VERSION,
)
from app.source_analysis_v31_global_canary_forensics.transport_v11 import (
    DROP_REASON_CODES,
    NON_DROP_REASON_CODE,
    REASON_CODES,
    REPRESENTATION_OPS,
    RETIRED_OPS,
)
from app.source_analysis_v31_global_grammar_canary.constants import (
    FROZEN_GRANULARITY,
    FROZEN_PLANNER,
    FROZEN_PROMPT,
    FROZEN_SRC_POLICY,
    FROZEN_TRANSPORT,
    HANDLE_PREFIX_BY_KIND,
    MODEL,
    NODE_KINDS,
    NORMAL_FINISH_REASONS,
    PRODUCTION_ESTIMATED_COST_USD,
    PRODUCTION_LOCAL_ESTIMATE_TOKENS,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PRODUCTION_NORMALIZED_CHARS,
    PRODUCTION_OUTPUT_HEADROOM_TOKENS,
    PRODUCTION_PROVIDER_ADJUSTED_TOKENS,
    PRODUCTION_WORST_CASE_OUTPUT_TOKENS,
    PROJECT_NAME,
    PROVIDER,
    THINKING_CONTRACT,
    THINKING_MODE,
)
from app.source_analysis_v31_global_preflight.constants import (
    CONSOLIDATION_CONNECT_TIMEOUT_SECONDS,
    CONSOLIDATION_READ_TIMEOUT_SECONDS,
    IDEA_DISPOSITION_COVERAGE_REQUIRED,
    IDEA_KIND_POLICY,
    MIXED_PROVENANCE,
    READY_COUNT,
    READY_LABEL,
    READY_WINDOWS,
    RELATION_POLICY_OPTION,
    RELATION_QUALITY_TECHNICAL_DEBT,
    WIN007_CANONICAL_SRC,
    WIN007_RAW_SRC,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.38"
MODE = "FIRST_REAL_GLOBAL_CONSOLIDATION_CANARY"
AUTHORIZATION_SCOPE = "REAL_GLOBAL_CONSOLIDATION_CANARY_ALL_7_READY_WINDOWS_ONLY"

A36_STATUS_PRESERVED = "PASS"
A37_STATUS_PRESERVED = "PASS"
assert A34_STATUS_PRESERVED == "PASS"
assert A35_STATUS_PRESERVED == "FAIL"
assert A36_STATUS_PRESERVED == "PASS"
assert A37_STATUS_PRESERVED == "PASS"

PROMPT_VERSION = NEXT_PROMPT_VERSION
TRANSPORT_VERSION = NEXT_TRANSPORT_VERSION
SCHEMA_RAW_BYTES = NEXT_SCHEMA_RAW_BYTES
SCHEMA_ADAPTED_BYTES = NEXT_SCHEMA_ADAPTED_BYTES
SCHEMA_HASH = NEXT_SCHEMA_HASH

assert PROMPT_VERSION == "global-consolidation-1.0.1"
assert TRANSPORT_VERSION == "global-consolidation-transport-1.1"
assert SCHEMA_RAW_BYTES == 1182
assert SCHEMA_ADAPTED_BYTES == 1337
assert SCHEMA_HASH == (
    "c98e57c3497843abdf294abfb2b691638ed54bdd86e651ab813efca563c6b3e6"
)
assert OLD_PROMPT_VERSION == "global-consolidation-1.0"
assert OLD_TRANSPORT_VERSION == "global-consolidation-transport-1.0"
assert A34_SCHEMA_RAW == 1040
assert A34_SCHEMA_ADAPTED == 1195
assert PROVIDER == "anthropic"
assert MODEL == "claude-sonnet-5"
assert THINKING_MODE == "disabled"
assert PRODUCTION_MAX_OUTPUT_TOKENS == 32000
assert READY_WINDOWS == (
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
)
assert READY_COUNT == 7
assert READY_LABEL == "7 / 7"
assert REPRESENTATION_OPS == ("KEEP", "MERGE_EQUIVALENT", "DROP", "OTHER")
assert REASON_CODES == (
    "none",
    "exact_duplicate",
    "transport_artifact",
    "non_substantive_fragment",
)
assert DROP_REASON_CODES == (
    "exact_duplicate",
    "transport_artifact",
    "non_substantive_fragment",
)
assert NON_DROP_REASON_CODE == "none"
assert RETIRED_OPS == ("LINK_RELATED",)
assert IDEA_KIND_POLICY == "KEEP_EMPTY_GLOBALLY"
assert WIN007_RAW_SRC == "SRec007337"
assert WIN007_CANONICAL_SRC == "SRC007337"
assert FROZEN_PLANNER == "window-planner-v2.1-small"
assert FROZEN_PROMPT == "window-analysis-1.4.0"
assert FROZEN_TRANSPORT == "semantic-transport-v3.1-local-lite"
assert FROZEN_GRANULARITY == "window-granularity-1.2-kind-specific"
assert FROZEN_SRC_POLICY == "src-reference-policy-1.1-narrow-canonicalization"

A37_GRAMMAR_PROOF = "PASS"
A37_REQUEST_ID = "req_011CfWW9vr5GRSeGTyAeS2oX"
GLOBAL_TRANSPORT_1_1_GRAMMAR_PROOF = A37_GRAMMAR_PROOF

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False
EFFORT = None
MAX_OUTPUT_TOKENS = PRODUCTION_MAX_OUTPUT_TOKENS
CONNECT_TIMEOUT_SECONDS = CONSOLIDATION_CONNECT_TIMEOUT_SECONDS
READ_TIMEOUT_SECONDS = CONSOLIDATION_READ_TIMEOUT_SECONDS
assert MAX_OUTPUT_TOKENS == 32000
assert CONNECT_TIMEOUT_SECONDS == 30.0
assert READ_TIMEOUT_SECONDS == 1800.0

EXPECTED_TOTAL_RECORDS = 623
EXPECTED_TOPIC = 67
EXPECTED_IDEA = 286
EXPECTED_RELATION = 127
EXPECTED_EXAMPLE = 49
EXPECTED_REFERENCE = 59
EXPECTED_UNCERTAINTY = 35
EXPECTED_SRC_OCCURRENCES = 2143
EXPECTED_DISTINCT_SRC = 1743
EXPECTED_CROSS_WINDOW_OWNERSHIP_VIOLATIONS = 0
EXPECTED_NORMALIZED_CHARS = PRODUCTION_NORMALIZED_CHARS
EXPECTED_LOCAL_ESTIMATE_TOKENS = PRODUCTION_LOCAL_ESTIMATE_TOKENS
EXPECTED_PROVIDER_ADJUSTED_TOKENS = PRODUCTION_PROVIDER_ADJUSTED_TOKENS
SIZE_DELTA_BLOCK_RATIO = 0.02

assert EXPECTED_NORMALIZED_CHARS == 141682
assert EXPECTED_LOCAL_ESTIMATE_TOKENS == 36531
assert EXPECTED_PROVIDER_ADJUSTED_TOKENS == 65755
assert EXPECTED_IDEA == 286

OUTPUT_HEADROOM_PERCENT = round(
    100.0 * PRODUCTION_OUTPUT_HEADROOM_TOKENS / PRODUCTION_MAX_OUTPUT_TOKENS, 1
)
OUTPUT_HEADROOM_LABEL = "MARGINAL"
assert PRODUCTION_WORST_CASE_OUTPUT_TOKENS == 24346
assert PRODUCTION_OUTPUT_HEADROOM_TOKENS == 7654
assert OUTPUT_HEADROOM_PERCENT == 23.9
assert OUTPUT_HEADROOM_LABEL == "MARGINAL"

CANARY_VERSION = "global-consolidation-real-canary-a38-1.0"
STAGE_CANARY = "source_analysis_v31_global_real_consolidation"
CANARY_SUBDIR = "canary/real_global_consolidation_a38"
LOCK_NAME = "canary_real_call.lock"
CANDIDATE_SOURCE_MAP_NAME = "candidate_source_map.json"
PRODUCTION_SOURCE_MAP_RELATIVE = "analysis/source_map.json"

PREFLIGHT_ARTIFACT = "global_consolidation_a38_preflight.json"
REQUEST_ARTIFACT = "global_consolidation_a38_request.json"
RAW_INVENTORY_ARTIFACT = "global_consolidation_a38_raw_output_inventory.json"
DISPOSITION_ARTIFACT = "global_consolidation_a38_disposition_audit.json"
DROP_ARTIFACT = "global_consolidation_a38_drop_review.json"
OTHER_ARTIFACT = "global_consolidation_a38_other_review.json"
MERGE_ARTIFACT = "global_consolidation_a38_merge_review.json"
RELATION_ARTIFACT = "global_consolidation_a38_relation_review.json"
SEMANTIC_ARTIFACT = "global_consolidation_a38_semantic_review.json"
COVERAGE_ARTIFACT = "global_consolidation_a38_global_coverage.json"
CANONICAL_ARTIFACT = "global_consolidation_a38_canonical_reconstruction.json"
USAGE_ARTIFACT = "global_consolidation_a38_usage_cost.json"
TEST_DELTA_ARTIFACT = "global_consolidation_a38_test_delta.json"
READINESS_ARTIFACT = "global_consolidation_post_a38_readiness.json"
EXECUTION_ARTIFACT = "global_consolidation_a38_execution.json"
REPORT_NAME = "PHASE_3B77A38_FIRST_REAL_GLOBAL_CONSOLIDATION_CANARY_REPORT.md"
BASELINE_ARTIFACT = "source_analysis_a38_test_baseline.json"
POST_TEST_ARTIFACT = TEST_DELTA_ARTIFACT

FOCUSED_TEST_PATHS = (
    "app/tests/test_source_analysis_v31_global_real_consolidation.py",
    "app/tests/test_source_analysis_v31_global_real_consolidation_audit.py",
    "app/tests/test_source_analysis_v31_global_v11_grammar_canary.py",
    "app/tests/test_source_analysis_v31_global_canary_forensics.py",
    "app/tests/test_source_analysis_v31_global_preflight.py",
)

DRY_RUN_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v31_global_real_consolidation "
    "pastoral_retreat_v2_validation "
    "--authorization-scope REAL_GLOBAL_CONSOLIDATION_CANARY_ALL_7_READY_WINDOWS_ONLY "
    "--dry-run"
)
REAL_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v31_global_real_consolidation "
    "pastoral_retreat_v2_validation "
    "--authorization-scope REAL_GLOBAL_CONSOLIDATION_CANARY_ALL_7_READY_WINDOWS_ONLY "
    "--execute-real"
)

PHASE_3B_STATUS = "INCOMPLETE"
SOURCE_MAP_STATUS = "NOT PUBLISHED"
NEXT_ACTION = "HUMAN REVIEW"
LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN = "YES"
READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY = "YES"
CONSOLIDATION_AUTHORIZED = True
SOURCE_MAP_PUBLICATION_AUTHORIZED = False
WINDOW_IS_NOT_CHAPTER = True
WINDOW_IS_NOT_SECTION = True
WINDOW_IS_NOT_EDITORIAL_UNIT = True

assert not source_map_path(PROJECT_NAME).is_file() or SOURCE_MAP_STATUS == "NOT PUBLISHED"
assert RELATION_QUALITY_TECHNICAL_DEBT == "YES"
assert SOURCE_MAP_PUBLICATION_AUTHORIZED is False
assert PHASE_3B_STATUS == "INCOMPLETE"

BEGINNING_WINDOWS = ("WIN001", "WIN002")
MIDDLE_WINDOWS = ("WIN003", "WIN004", "WIN005")
END_WINDOWS = ("WIN006", "WIN007")
CROSS_WINDOW_BOUNDARIES = (
    ("WIN001", "WIN002"),
    ("WIN002", "WIN003"),
    ("WIN003", "WIN004"),
    ("WIN004", "WIN005"),
    ("WIN005", "WIN006"),
    ("WIN006", "WIN007"),
)

__all__ = [
    "A34_SCHEMA_ADAPTED",
    "A34_SCHEMA_HASH",
    "A34_SCHEMA_RAW",
    "A34_STATUS_PRESERVED",
    "A35_STATUS_PRESERVED",
    "A36_STATUS_PRESERVED",
    "A37_GRAMMAR_PROOF",
    "A37_REQUEST_ID",
    "A37_STATUS_PRESERVED",
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "BASELINE_ARTIFACT",
    "BEGINNING_WINDOWS",
    "CANARY_SUBDIR",
    "CANARY_VERSION",
    "CANONICAL_ARTIFACT",
    "CANDIDATE_SOURCE_MAP_NAME",
    "CONSOLIDATION_AUTHORIZED",
    "CONNECT_TIMEOUT_SECONDS",
    "COVERAGE_ARTIFACT",
    "CROSS_WINDOW_BOUNDARIES",
    "DISPOSITION_ARTIFACT",
    "DROP_ARTIFACT",
    "DROP_REASON_CODES",
    "DRY_RUN_COMMAND",
    "EFFORT",
    "END_WINDOWS",
    "EXECUTION_ARTIFACT",
    "EXPECTED_CROSS_WINDOW_OWNERSHIP_VIOLATIONS",
    "EXPECTED_DISTINCT_SRC",
    "EXPECTED_EXAMPLE",
    "EXPECTED_IDEA",
    "EXPECTED_LOCAL_ESTIMATE_TOKENS",
    "EXPECTED_NORMALIZED_CHARS",
    "EXPECTED_PROVIDER_ADJUSTED_TOKENS",
    "EXPECTED_REFERENCE",
    "EXPECTED_RELATION",
    "EXPECTED_SRC_OCCURRENCES",
    "EXPECTED_TOPIC",
    "EXPECTED_TOTAL_RECORDS",
    "EXPECTED_UNCERTAINTY",
    "FOCUSED_TEST_PATHS",
    "FROZEN_GRANULARITY",
    "FROZEN_PLANNER",
    "FROZEN_PROMPT",
    "FROZEN_SRC_POLICY",
    "FROZEN_TRANSPORT",
    "GLOBAL_TRANSPORT_1_1_GRAMMAR_PROOF",
    "HANDLE_PREFIX_BY_KIND",
    "IDEA_DISPOSITION_COVERAGE_REQUIRED",
    "IDEA_KIND_POLICY",
    "LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN",
    "LOCK_NAME",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MAX_OUTPUT_TOKENS",
    "MERGE_ARTIFACT",
    "MIDDLE_WINDOWS",
    "MIXED_PROVENANCE",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "NODE_KINDS",
    "NON_DROP_REASON_CODE",
    "NORMAL_FINISH_REASONS",
    "OLD_PROMPT_VERSION",
    "OLD_TRANSPORT_VERSION",
    "OTHER_ARTIFACT",
    "OUTPUT_HEADROOM_LABEL",
    "OUTPUT_HEADROOM_PERCENT",
    "PHASE",
    "PHASE_3B_STATUS",
    "POST_TEST_ARTIFACT",
    "PREFLIGHT_ARTIFACT",
    "PRODUCTION_ESTIMATED_COST_USD",
    "PRODUCTION_LOCAL_ESTIMATE_TOKENS",
    "PRODUCTION_MAX_OUTPUT_TOKENS",
    "PRODUCTION_NORMALIZED_CHARS",
    "PRODUCTION_OUTPUT_HEADROOM_TOKENS",
    "PRODUCTION_PROVIDER_ADJUSTED_TOKENS",
    "PRODUCTION_SOURCE_MAP_RELATIVE",
    "PRODUCTION_WORST_CASE_OUTPUT_TOKENS",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROVIDER",
    "RAW_INVENTORY_ARTIFACT",
    "READINESS_ARTIFACT",
    "READY_COUNT",
    "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY",
    "READY_LABEL",
    "READY_WINDOWS",
    "READ_TIMEOUT_SECONDS",
    "REAL_COMMAND",
    "REASON_CODES",
    "RELATION_ARTIFACT",
    "RELATION_POLICY_OPTION",
    "RELATION_QUALITY_TECHNICAL_DEBT",
    "REPORT_NAME",
    "REPRESENTATION_OPS",
    "REQUEST_ARTIFACT",
    "RETIRED_OPS",
    "SCHEMA_ADAPTED_BYTES",
    "SCHEMA_HASH",
    "SCHEMA_RAW_BYTES",
    "SCHEMA_VERSION",
    "SEMANTIC_ARTIFACT",
    "SIZE_DELTA_BLOCK_RATIO",
    "SOURCE_MAP_PUBLICATION_AUTHORIZED",
    "SOURCE_MAP_STATUS",
    "STAGE_CANARY",
    "TEST_DELTA_ARTIFACT",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
    "USAGE_ARTIFACT",
    "WIN007_CANONICAL_SRC",
    "WIN007_RAW_SRC",
    "WINDOW_IS_NOT_CHAPTER",
    "WINDOW_IS_NOT_EDITORIAL_UNIT",
    "WINDOW_IS_NOT_SECTION",
]
