"""Rapport markdown 3B.7.7A.46."""

from __future__ import annotations

from typing import Any, Mapping

from app.source_analysis_v31_global_v30_real_canary.constants import (
    A45_CONSERVATIVE_COST_USD,
    A45_CONSERVATIVE_OUTPUT,
    A45_ESTIMATED_INPUT,
    A45_EXPECTED_COST_USD,
    A45_EXPECTED_OUTPUT,
    A45_HARD_COST_USD,
    A45_HARD_OUTPUT,
    A45_NORMALIZED_INPUT_HASH,
    A45_REQUEST_HASH,
    LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
    MODEL,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PROMPT_VERSION,
    RELATION_QUALITY_TECHNICAL_DEBT,
    SCHEMA_ADAPTED_BYTES,
    SCHEMA_HASH,
    SCHEMA_RAW_BYTES,
    TRANSPORT_VERSION,
)
from app.source_analysis_v31_global_v30_real_canary.runner import CanaryRunResult


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(
    result: CanaryRunResult,
    *,
    tests: str,
    extra_header: Mapping[str, Any] | None = None,
) -> str:
    exe = result.execution or {}
    dry = result.dry_run or {}
    extra = dict(extra_header or {})
    verdict = exe.get("result") or extra.get("result") or result.mode
    actual_calls = exe.get("actual_calls")
    if actual_calls is None:
        actual_calls = result.anthropic_post_attempts
    successful = exe.get("successful_calls")
    if successful is None:
        successful = 0
    cost = exe.get("actual_cost")
    if cost is None:
        cost = (exe.get("cost") or {}).get("total_cost")
    elapsed = exe.get("elapsed_seconds")
    if elapsed is None and exe.get("provider_elapsed_ms") is not None:
        elapsed = f"{exe.get('provider_elapsed_ms')} ms"
    input_err = exe.get("input_estimate_error") or {}
    input_err_display = "n/a"
    if input_err:
        input_err_display = f"{input_err.get('absolute')} tokens / {input_err.get('percent')}%"
    util = exe.get("output_utilization")
    util_display = f"{util}" if util is None else f"{round(100.0 * float(util), 2)}%"
    lines = [
        "# PHASE 3B.7.7A.46 — GLOBAL CONSOLIDATION V3.0 ONE REAL CANARY",
        "",
        "## Result",
        "",
        str(verdict),
        "",
        "AUTHORIZED PROVIDER CALLS =",
        "1",
        "",
        "ACTUAL PROVIDER CALLS =",
        _dash(actual_calls),
        "",
        "SUCCESSFUL PROVIDER CALLS =",
        _dash(successful),
        "",
        "RETRIES =",
        "0",
        "",
        "A.45 NORMALIZED INPUT HASH =",
        A45_NORMALIZED_INPUT_HASH,
        "",
        "ACTUAL NORMALIZED INPUT HASH =",
        _dash(exe.get("normalized_input_hash") or dry.get("normalized_input_hash")),
        "",
        "A.45 REQUEST HASH =",
        A45_REQUEST_HASH,
        "",
        "ACTUAL REQUEST HASH =",
        _dash(exe.get("request_hash") or dry.get("request_identity")),
        "",
        "REQUEST IDENTITY =",
        _dash(exe.get("request_identity") or dry.get("request_identity_match")),
        "",
        "READY WINDOWS =",
        "7 / 7",
        "",
        "LOCAL RECORDS =",
        "623",
        "",
        "LOCAL IDEAS =",
        "286",
        "",
        "MODEL =",
        MODEL,
        "",
        "PROMPT =",
        PROMPT_VERSION,
        "",
        "TRANSPORT =",
        TRANSPORT_VERSION,
        "",
        "SCHEMA RAW / ADAPTED =",
        f"{SCHEMA_RAW_BYTES} / {SCHEMA_ADAPTED_BYTES}",
        "",
        "SCHEMA HASH =",
        SCHEMA_HASH,
        "",
        "THINKING =",
        "disabled",
        "",
        "MAX_OUTPUT =",
        str(PRODUCTION_MAX_OUTPUT_TOKENS),
        "",
        "CONNECT / READ TIMEOUT =",
        "30 / 600",
        "",
        "HTTP =",
        _dash(exe.get("http_status")),
        "",
        "FINISH =",
        _dash(exe.get("finish_reason")),
        "",
        "THINKING TOKENS =",
        _dash(exe.get("thinking_tokens")),
        "",
        "REQUEST ID =",
        _dash(exe.get("request_id")),
        "",
        "INPUT TOKENS =",
        _dash(exe.get("input_tokens")),
        "",
        "OUTPUT TOKENS =",
        _dash(exe.get("output_tokens")),
        "",
        "ELAPSED =",
        _dash(elapsed),
        "",
        "ACTUAL COST =",
        _dash(cost),
        "",
        "RAW RESPONSE CHARS =",
        _dash(exe.get("raw_text_chars")),
        "",
        "RAW RESPONSE BYTES =",
        _dash(exe.get("raw_text_bytes")),
        "",
        "RAW RESPONSE HASH =",
        _dash(exe.get("raw_response_hash")),
        "",
        "STRUCTURED PARSE =",
        _dash(exe.get("structured_parse")),
        "",
        "TRANSPORT DECODER =",
        _dash(exe.get("transport_decoder")),
        "",
        "HANDLE VALIDATION =",
        _dash(exe.get("handle_validation")),
        "",
        "GLOBAL IDEAS =",
        _dash(exe.get("global_ideas")),
        "",
        "REUSE IDEAS =",
        _dash(exe.get("reuse_ideas")),
        "",
        "SYNTHESIZED MERGES =",
        _dash(exe.get("synthesized_merges")),
        "",
        "DROPPED IDEAS =",
        _dash(exe.get("dropped_ideas")),
        "",
        "SINGLE_MEMBER_WITH_V =",
        _dash(exe.get("SINGLE_MEMBER_WITH_V")),
        "",
        "MULTI_MEMBER_WITHOUT_V =",
        _dash(exe.get("MULTI_MEMBER_WITHOUT_V")),
        "",
        "NON_IDEA_IN_MEMBERS =",
        _dash(exe.get("NON_IDEA_IN_MEMBERS")),
        "",
        "NON_IDEA_IN_DROP =",
        _dash(exe.get("NON_IDEA_IN_DROP")),
        "",
        "UNKNOWN IDEA HANDLES =",
        _dash(exe.get("unknown_members")),
        "",
        "DUPLICATE MEMBERSHIP =",
        _dash(exe.get("duplicate_members")),
        "",
        "MISSING IDEAS =",
        _dash(exe.get("missing_members")),
        "",
        "MEMBER/DROP OVERLAP =",
        _dash(exe.get("member_drop_overlap")),
        "",
        "IDEA ACCOUNTABILITY =",
        _dash(exe.get("idea_accountability")),
        "",
        "DERIVED KEEP =",
        _dash(exe.get("keep_count")),
        "",
        "DERIVED MERGE_EQUIVALENT =",
        _dash(exe.get("merge_equivalent_count")),
        "",
        "DERIVED DROP =",
        _dash(exe.get("drop_count")),
        "",
        "DERIVED SRC UNION =",
        _dash(exe.get("derived_src_union")),
        "",
        "TOPICS =",
        _dash(exe.get("topics")),
        "",
        "EXAMPLES =",
        _dash(exe.get("examples")),
        "",
        "REFERENCES =",
        _dash(exe.get("references")),
        "",
        "UNCERTAINTIES =",
        _dash(exe.get("uncertainties")),
        "",
        "GLOBAL VALIDATOR =",
        _dash(exe.get("global_validator")),
        "",
        "CANONICAL RECONSTRUCTION =",
        _dash(exe.get("canonical_reconstruction")),
        "",
        "CANONICAL VALIDATION =",
        _dash(exe.get("canonical_validation")),
        "",
        "DETERMINISTIC REPLAY =",
        _dash(exe.get("deterministic_replay")),
        "",
        "MERGE SEMANTIC REVIEW =",
        _dash(exe.get("merge_semantic_review")),
        "",
        "DROP SEMANTIC REVIEW =",
        _dash(exe.get("drop_semantic_review")),
        "",
        "TOPIC SEMANTIC REVIEW =",
        _dash(exe.get("topic_semantic_review")),
        "",
        "METADATA SEMANTIC REVIEW =",
        _dash(exe.get("metadata_semantic_review")),
        "",
        "UNCERTAINTY PRESERVATION =",
        _dash(exe.get("uncertainty_preservation")),
        "",
        "COMPLETENESS =",
        _dash(exe.get("completeness")),
        "",
        "NO EDITORIAL STRUCTURE =",
        _dash(exe.get("no_editorial_structure")),
        "",
        "SEMANTIC REVIEW =",
        _dash(exe.get("semantic_review")),
        "",
        "PUBLICATION_ELIGIBLE =",
        _dash(exe.get("publication_eligible")),
        "",
        "A.45 ESTIMATED INPUT =",
        str(A45_ESTIMATED_INPUT),
        "",
        "INPUT ESTIMATE ERROR =",
        input_err_display,
        "",
        "A.45 EXPECTED OUTPUT =",
        str(A45_EXPECTED_OUTPUT),
        "",
        "A.45 CONSERVATIVE OUTPUT =",
        str(A45_CONSERVATIVE_OUTPUT),
        "",
        "A.45 HARD OUTPUT =",
        str(A45_HARD_OUTPUT),
        "",
        "ACTUAL OUTPUT UTILIZATION =",
        util_display,
        "",
        "ACTUAL OUTPUT HEADROOM =",
        _dash(exe.get("output_headroom")),
        "",
        "ACTUAL CHARS/TOKEN =",
        _dash(exe.get("actual_chars_per_token")),
        "",
        "EXPECTED COST =",
        str(A45_EXPECTED_COST_USD),
        "",
        "CONSERVATIVE COST =",
        str(A45_CONSERVATIVE_COST_USD),
        "",
        "HARD COST =",
        str(A45_HARD_COST_USD),
        "",
        "ACTUAL COST POSITION =",
        _dash(exe.get("actual_cost_position")),
        "",
        "LOCAL EXTRACTION FUNCTIONALLY FROZEN =",
        LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        RELATION_QUALITY_TECHNICAL_DEBT,
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        _dash(extra.get("new_failures", exe.get("new_failures", "pending"))),
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "READY_FOR_SOURCE_MAP_PUBLICATION_REVIEW =",
        _dash(exe.get("ready_for_source_map_publication_review") or "NO"),
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
    ]
    if result.error:
        lines.extend(["ERROR =", result.error, ""])
    return "\n".join(lines)


__all__ = ["render_report"]
