"""
Phase 4A.3.3 — one real canonical-language production canary.

Uses editorial-planner-1.0.1. Does not mutate historical 1.0, schema,
transport, or the A.3 French audit candidate.
"""

from __future__ import annotations

from app.editorial_planner_canary_4a1.constants import (
    PHASE_4A_ADAPTED_SCHEMA_BYTES,
    PHASE_4A_ADAPTED_SCHEMA_SHA256,
    PHASE_4A_INSTRUCTIONS_SHA256,
    PHASE_4A_PROMPT_SHA256,
    PHASE_4A_RAW_SCHEMA_BYTES,
    PHASE_4A_RAW_SCHEMA_SHA256,
    PHASE_4A_SYSTEM_SHA256,
)
from app.editorial_planner_canary_4a3.constants import (
    A2_CONSERVATIVE_OUTPUT_TOKENS,
    A2_EXPECTED_OUTPUT_TOKENS,
    A2_HARD_OUTPUT_TOKENS,
    EXPECTED_EXAMPLE_COUNT,
    EXPECTED_IDEA_COUNT,
    EXPECTED_REFERENCE_COUNT,
    EXPECTED_SOURCE_MAP_BYTES,
    EXPECTED_SOURCE_MAP_CHARS,
    EXPECTED_SOURCE_MAP_SHA256,
    EXPECTED_TOPIC_COUNT,
    EXPECTED_UNCERTAINTY_COUNT,
    HISTORICAL_PROPOSED_MAX_OUTPUT,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PROJECT_NAME,
)
from app.editorial_planner_language_policy_4a32.constants import (
    A3_CANDIDATE_SHA256,
    A3_COST_USD,
    A3_FINISH,
    A3_INPUT_TOKENS,
    A3_OUTPUT_TOKENS,
    A3_REQUEST_SHA256,
    A3_THINKING_TOKENS,
    NEW_PROMPT,
)
from app.editorial_planning.constants import (
    EDITORIAL_PLAN_TRANSPORT_VERSION,
    EDITORIAL_PLANNER_PROMPT_VERSION,
    MODEL,
    PROVIDER,
    STAGE_EDITORIAL_PLANNING,
)
from app.editorial_planning.language_policy import (
    DOCUMENT_LANGUAGE_POLICY,
    FIELD_TRANSCRIPT_PRIMARY,
    SUCCESSOR_PROMPT_VERSION,
)

PHASE = "4A.3.3"
PHASE_NAME = "EDITORIAL_PLANNER_ONE_REAL_CANONICAL_LANGUAGE_PRODUCTION_CANARY"
CANARY_VERSION = "editorial-planner-canary-4a33-1.0"

AUTHORIZATION_SCOPE = "EDITORIAL_PLANNER_4A33_ONE_REAL_ENGLISH_PRODUCTION_CANARY_ONLY"

assert PROVIDER == "anthropic"
assert MODEL == "claude-opus-5"

HISTORICAL_PROMPT = EDITORIAL_PLANNER_PROMPT_VERSION
PROMPT_VERSION = SUCCESSOR_PROMPT_VERSION
TRANSPORT_VERSION = EDITORIAL_PLAN_TRANSPORT_VERSION
assert HISTORICAL_PROMPT == "editorial-planner-1.0"
assert PROMPT_VERSION == "editorial-planner-1.0.1"
assert NEW_PROMPT == PROMPT_VERSION
assert TRANSPORT_VERSION == "editorial-plan-transport-1.0"
assert DOCUMENT_LANGUAGE_POLICY == "TRANSCRIPTION_DERIVED_PRIMARY_LANGUAGE"

STAGE_CANARY = STAGE_EDITORIAL_PLANNING
assert STAGE_CANARY == "editorial_planning"

PROJECT_NAME = PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
RETRIES = 0
AUTHORIZED_PROVIDER_CALLS = 1

assert HISTORICAL_PROPOSED_MAX_OUTPUT == 16384
assert PRODUCTION_MAX_OUTPUT_TOKENS == 65536

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 1800.0

assert EXPECTED_SOURCE_MAP_SHA256 == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_SOURCE_MAP_BYTES == 202398
assert EXPECTED_SOURCE_MAP_CHARS == 202365
assert EXPECTED_TOPIC_COUNT == 67
assert EXPECTED_IDEA_COUNT == 286
assert EXPECTED_EXAMPLE_COUNT == 49
assert EXPECTED_REFERENCE_COUNT == 59
assert EXPECTED_UNCERTAINTY_COUNT == 35

RAW_SCHEMA_SHA256 = PHASE_4A_RAW_SCHEMA_SHA256
ADAPTED_SCHEMA_SHA256 = PHASE_4A_ADAPTED_SCHEMA_SHA256
RAW_SCHEMA_BYTES = PHASE_4A_RAW_SCHEMA_BYTES
ADAPTED_SCHEMA_BYTES = PHASE_4A_ADAPTED_SCHEMA_BYTES
SYSTEM_SHA256 = PHASE_4A_SYSTEM_SHA256
INSTRUCTIONS_SHA256 = PHASE_4A_INSTRUCTIONS_SHA256
PROMPT_SHA256 = PHASE_4A_PROMPT_SHA256
assert RAW_SCHEMA_BYTES == 3661
assert ADAPTED_SCHEMA_BYTES == 3909
assert ADAPTED_SCHEMA_SHA256 == (
    "1cebcf97ed7fa5cfa4b4758d1eb1451b6770347e9508772e8287228a768ba77e"
)

THINKING_MODE = "provider_default"
EFFORT = None
BUDGET_TOKENS = None

EXPECTED_REQUEST_SHA256 = (
    "8ae3170b79a148979a6480a06c922116fc4b2982bd4965cc2bc6ce74d51b3b69"
)
HISTORICAL_A3_REQUEST_SHA256 = A3_REQUEST_SHA256
assert HISTORICAL_A3_REQUEST_SHA256 == (
    "99ee7e8f4f9a732b52fceab667d9d1fe8b9ce9acedc1e7b1e7c08c1f62b7b734"
)
assert EXPECTED_REQUEST_SHA256 != HISTORICAL_A3_REQUEST_SHA256

EXPECTED_REQUEST_CHARS = 115305
EXPECTED_REQUEST_UTF8_BYTES = 115431

A32_PLANNING_INPUT_ESTIMATE = 59542
A32_ESTIMATED_COST_USD = 0.51446
A32_ESTIMATED_COST_DISPLAY = "0.5144600 USD"
A3_ACTUAL_INPUT_TOKENS = A3_INPUT_TOKENS
A3_ACTUAL_OUTPUT_TOKENS = A3_OUTPUT_TOKENS
A3_ACTUAL_THINKING_TOKENS = A3_THINKING_TOKENS
A3_ACTUAL_COST_USD = A3_COST_USD
A3_ACTUAL_FINISH = A3_FINISH
assert A3_ACTUAL_INPUT_TOKENS == 41425
assert A3_ACTUAL_OUTPUT_TOKENS == 17791
assert A3_ACTUAL_THINKING_TOKENS == 6443
assert A3_ACTUAL_COST_USD == 0.6519

A2_EXPECTED_OUTPUT_TOKENS = A2_EXPECTED_OUTPUT_TOKENS
A2_CONSERVATIVE_OUTPUT_TOKENS = A2_CONSERVATIVE_OUTPUT_TOKENS
A2_HARD_OUTPUT_TOKENS = A2_HARD_OUTPUT_TOKENS
assert A2_EXPECTED_OUTPUT_TOKENS == 8670
assert A2_CONSERVATIVE_OUTPUT_TOKENS == 19666
assert A2_HARD_OUTPUT_TOKENS == 34555

CANONICAL_LANGUAGE_SOURCE = FIELD_TRANSCRIPT_PRIMARY
EXPECTED_CANONICAL_DOCUMENT_LANGUAGE = "en"
LANGUAGE_POLICY = DOCUMENT_LANGUAGE_POLICY

A3_CANDIDATE_SHA256 = A3_CANDIDATE_SHA256
assert A3_CANDIDATE_SHA256 == (
    "abc87e082878e0281689ecc022ed8b40ca318510fc90d960c31795d6186bd95e"
)

HISTORICAL_QUESTIONABLE_FIT_IDEAS = (
    "IDEA054",
    "IDEA100",
    "IDEA112",
    "IDEA113",
    "IDEA168",
    "IDEA283",
    "IDEA286",
)
HISTORICAL_LEFTOVER_SECTION = "SEC028"
HISTORICAL_FRENCH_TITLE = "Déjà héritiers"

CANARY_WINDOW_ID = "CANARY_EP4A33"
LOCK_NAME = "canary_real_call.lock"

AUDIT_DIRNAME = "editorial_planner_4a33"
AUDIT_REAL_PARENT = "real"
AUDIT_PRECALL = "editorial_planner_4a33_precall_identity.json"
AUDIT_PROVIDER = "editorial_planner_4a33_provider_evidence.json"
AUDIT_RESPONSE = "editorial_planner_4a33_response_identity.json"
AUDIT_THINKING = "editorial_planner_4a33_thinking_observation.json"
AUDIT_BUDGET = "editorial_planner_4a33_budget_calibration.json"
AUDIT_LANGUAGE = "editorial_planner_4a33_language_validation.json"
AUDIT_TECHNICAL = "editorial_planner_4a33_technical_validation.json"
AUDIT_COVERAGE = "editorial_planner_4a33_idea_coverage.json"
AUDIT_CHAPTER = "editorial_planner_4a33_chapter_review.json"
AUDIT_SECTION = "editorial_planner_4a33_section_review.json"
AUDIT_SEMANTIC = "editorial_planner_4a33_semantic_review.json"
AUDIT_PUBLICATION = "editorial_planner_4a33_publication_eligibility.json"
AUDIT_READINESS = "editorial_planner_post_4a33_readiness.json"
AUDIT_CANDIDATE = "editorial_plan_candidate.json"
AUDIT_RAW_RESPONSE = "editorial_planner_4a33_raw_structured_response.json"
AUDIT_RAW_TEXT = "editorial_planner_4a33_raw_provider_text.txt"
AUDIT_EXECUTION = "editorial_planner_4a33_execution.json"
REPORT_NAME = (
    "PHASE_4A33_EDITORIAL_PLANNER_ONE_REAL_ENGLISH_PRODUCTION_CANARY_REPORT.md"
)

PUBLICATION_AUTHORIZED = False
BOOK_GENERATOR = "NOT STARTED"
NEXT_ACTION = "HUMAN REVIEW"
FINAL_TITLE_APPROVED = False

assert PUBLICATION_AUTHORIZED is False
assert RETRIES == 0
assert MAX_ENGINE_GENERATE == 1
assert THINKING_MODE == "provider_default"
assert EFFORT is None
assert BUDGET_TOKENS is None
assert FINAL_TITLE_APPROVED is False
