"""Markdown report Phase 4A.3.3."""

from __future__ import annotations

from typing import Any, Mapping


def render_report(bundle: Mapping[str, Any]) -> str:
    header = dict(bundle.get("header") or {})
    lines = [
        "# PHASE 4A.3.3 — ONE REAL CANONICAL-LANGUAGE EDITORIAL PLANNER CANARY",
        "",
        "## Result",
        "",
        str(header.get("result") or "FAIL"),
        "",
        f"AUTHORIZED PROVIDER CALLS = {header.get('authorized_provider_calls', 1)}",
        "",
        f"ACTUAL PROVIDER CALLS = {header.get('actual_provider_calls', 0)}",
        "",
        f"RETRIES = {header.get('retries', 0)}",
        "",
        f"SOURCE MAP SHA256 PRE = {header.get('source_map_sha256_pre')}",
        "",
        f"SOURCE MAP SHA256 POST = {header.get('source_map_sha256_post')}",
        "",
        f"SOURCE MAP UNCHANGED = {header.get('source_map_unchanged')}",
        "",
        f"CANONICAL LANGUAGE SOURCE = {header.get('canonical_language_source')}",
        "",
        f"CANONICAL DOCUMENT LANGUAGE = {header.get('canonical_document_language')}",
        "",
        f"PROMPT = {header.get('prompt')}",
        "",
        f"TRANSPORT = {header.get('transport')}",
        "",
        f"SCHEMA RAW / ADAPTED = {header.get('schema_raw_adapted')}",
        "",
        f"SCHEMA HASH = {header.get('schema_hash')}",
        "",
        f"SCHEMA IDENTITY = {header.get('schema_identity')}",
        "",
        f"EXPECTED REQUEST SHA256 = {header.get('expected_request_sha256')}",
        "",
        f"ACTUAL REQUEST SHA256 = {header.get('actual_request_sha256')}",
        "",
        f"REQUEST IDENTITY = {header.get('request_identity')}",
        "",
        f"MODEL = {header.get('model')}",
        "",
        f"THINKING = {header.get('thinking_mode')}",
        "",
        f"MAX_OUTPUT = {header.get('max_output')}",
        "",
        f"HTTP / FINISH = {header.get('http_status')} / {header.get('finish')}",
        "",
        f"REQUEST ID = {header.get('request_id')}",
        "",
        f"INPUT TOKENS = {header.get('input_tokens')}",
        "",
        f"OUTPUT TOKENS = {header.get('output_tokens')}",
        "",
        f"THINKING TOKENS = {header.get('thinking_tokens')}",
        "",
        f"OUTPUT UTILIZATION = {header.get('output_utilization')}",
        "",
        f"ELAPSED = {header.get('elapsed')}",
        "",
        f"ACTUAL COST = {header.get('cost')}",
        "",
        f"A.3.2 ESTIMATED COST = {header.get('a32_estimated_cost')}",
        "",
        f"STRUCTURED PARSE = {header.get('structured_parse')}",
        "",
        f"TRANSPORT DECODER = {header.get('transport_decoder')}",
        "",
        f"HANDLES = {header.get('handle_validation')}",
        "",
        f"CANONICAL RECONSTRUCTION = {header.get('canonical_reconstruction')}",
        "",
        f"CANONICAL CANDIDATE SHA256 = {header.get('canonical_candidate_sha256')}",
        "",
        f"CHAPTERS = {header.get('chapters')}",
        "",
        f"SECTIONS = {header.get('sections')}",
        "",
        f"IDEA COVERAGE = {header.get('idea_coverage')}",
        "",
        f"SILENT OMISSIONS = {header.get('silent_omissions')}",
        "",
        f"ASSIGNED = {header.get('assigned')}",
        "",
        f"DEFERRED = {header.get('deferred')}",
        "",
        f"EXCLUDED = {header.get('excluded')}",
        "",
        f"REUSED IDEAS = {header.get('reused')}",
        "",
        f"UNKNOWN REFS = {header.get('unknown_refs_total')}",
        "",
        f"EDITORIAL LANGUAGE EXPECTED = {header.get('editorial_language_expected')}",
        "",
        f"EDITORIAL LANGUAGE RESULT = {header.get('editorial_language_result')}",
        "",
        f"TRACEABILITY = {header.get('traceability')}",
        "",
        f"INVENTION BOUNDARY = {header.get('invention_boundary')}",
        "",
        f"UNCERTAINTY = {header.get('uncertainty_preservation')}",
        "",
        f"VALIDATOR = {header.get('editorial_plan_validator')}",
        "",
        f"DETERMINISTIC REPLAY = {header.get('deterministic_replay')}",
        "",
        f"TITLE REVIEW = {header.get('title_review')}",
        "",
        f"BOOK CONCEPT REVIEW = {header.get('book_concept_review')}",
        "",
        f"CHAPTER REVIEW = {header.get('chapter_review')}",
        "",
        f"SECTION REVIEW = {header.get('section_review')}",
        "",
        f"SEMANTIC REVIEW = {header.get('semantic_review')}",
        "",
        f"PUBLICATION_ELIGIBLE = {header.get('publication_eligible')}",
        "",
        f"TESTS = {header.get('tests')}",
        "",
        f"NEW FAILURES = {header.get('new_failures')}",
        "",
        "editorial_plan.json = NOT PUBLISHED",
        "",
        f"READY_FOR_CONTROLLED_EDITORIAL_PLAN_PUBLICATION = {header.get('ready_for_controlled_editorial_plan_publication')}",
        "",
        "BOOK GENERATOR = NOT STARTED",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
        "## Notes",
        "",
        str(header.get("notes") or ""),
        "",
        "WAIT FOR HUMAN REVIEW.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
