"""Phase 4B.2.7.7 — one real Terra h11 discriminating semantic canary."""

from app.book_semantic_gate_4b277.constants import (
    AUTHORIZED_REMOTE_TERRA_INVOCATIONS,
    AUTHORIZED_SONNET_CALLS,
    HISTORICAL_4B276_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    PHASE,
    SELECTED_CASE_HANDLE,
)

assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_4B276_STATUS == "PASS"
assert SELECTED_CASE_HANDLE == "h11"

__all__ = [
    "PHASE",
    "AUTHORIZED_REMOTE_TERRA_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "HISTORICAL_H01_STATUS",
    "HISTORICAL_H02_STATUS",
    "HISTORICAL_4B276_STATUS",
]
