"""
Phase 4B.2.7.7 — One real Terra h11 discriminating semantic canary.

NEW explicit authorization. MAX_REMOTE_TERRA_INVOCATIONS = 1.
Reuses the frozen 4B.2.7.6 request. Does not relaunch h01 or h02.
Does not modify frozen 1.0 / 1.1 / 1.1.1 / 1.1.2 / 1.1.3-candidate.
1.1.3-candidate is not promoted.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
    VERDICT_FAIL,
    VERDICT_PASS,
    VERDICT_REVIEW,
)
from app.book_semantic_gate_4b24.constants import SCORED_CASE_ORDER
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    SEMANTIC_TOKEN_BUDGET,
)
from app.book_semantic_gate_4b261.constants import CANDIDATE_PROMPT_VERSION
from app.book_semantic_gate_4b27.constants import (
    EXPECTED_REQUEST_SHA256 as H01_REQUEST_SHA256,
    HISTORICAL_4B261_STATUS,
    HISTORICAL_4B262_STATUS,
    HISTORICAL_4B26_STATUS,
)
from app.book_semantic_gate_4b271.constants import (
    EXPECTED_PROMPT_11_SHA256,
    EXPECTED_PROMPT_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_SYSTEM_SHA256,
    HISTORICAL_4B27_STATUS,
    TRANSPORT_VERSION_11,
)
from app.book_semantic_gate_4b272.constants import HISTORICAL_4B271_STATUS
from app.book_semantic_gate_4b273.constants import (
    EXPECTED_REQUEST_SHA256 as H02_REQUEST_SHA256,
    HISTORICAL_4B272_STATUS,
)
from app.book_semantic_gate_4b274.constants import HISTORICAL_4B273_STATUS
from app.book_semantic_gate_4b275.constants import (
    EXPECTED_PROMPT_111_SHA256,
    EXPECTED_PROMPT_112_SHA256,
    EXPECTED_PROMPT_113_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_113_SHA256,
    EXPECTED_PROMPT_113_SYSTEM_SHA256,
    HISTORICAL_4B274_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    PROMPT_VERSION_113,
)
from app.book_semantic_gate_4b276.constants import (
    DISPUTED_CLAUSE,
    H01_COMPLETION_TOKENS,
    H01_COST_USD,
    H01_INPUT_TOKENS,
    H01_REASONING_TOKENS,
    H02_COMPLETION_TOKENS,
    H02_COST_USD,
    H02_INPUT_TOKENS,
    H02_REASONING_TOKENS,
    P4_EVIDENCE_HANDLES,
    SELECTED_CASE_ACCEPTED_CLASSES,
    SELECTED_CASE_HANDLE,
    SELECTED_CASE_HUMAN_LABEL,
    SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY,
    SELECTED_CASE_ID,
    SELECTED_CASE_ORIGIN,
    SELECTED_CASE_REASON_CODES_ACCEPTABLE_AUDIT_ONLY,
    SELECTED_CASE_REASON_CODES_AUDIT_ONLY,
    SELECTED_CASE_ROLE,
    SOURCE_CASE_HANDLE,
    SOURCE_CASE_ID,
    TARGET_FAILURE_FAMILY,
)

PHASE = "4B.2.7.7"
PHASE_NAME = "ONE_REAL_TERRA_H11_DISCRIMINATING_CANARY"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B277_ONE_REAL_TERRA_H11_DISCRIMINATING_CANARY_ONLY"
)
AUTHORIZED_REMOTE_TERRA_INVOCATIONS = 1
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
MAX_ENGINE_GENERATE = 1
MAX_REMOTE_INVOCATIONS = 1
RETRIES = 0
FALLBACKS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = True
SDK_MAX_RETRIES = 0

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
STAGE_CANARY = "book_semantic_validation_canary_4b277"
PROMPT_VERSION = PROMPT_VERSION_113
TRANSPORT_VERSION = TRANSPORT_VERSION_11
PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
PROMPT_VERSION_11 = CANDIDATE_PROMPT_VERSION
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"
TOKEN_FIELD = "max_completion_tokens"
PRODUCTION_SDK_METHOD = "client.chat.completions.create"

EXPECTED_REQUEST_SHA256 = (
    "b3cc1574858acdd5bdd0e223aa136d5058c4eb1deb1495cd9ad312d332e8c30f"
)
EXPECTED_CLAUSE_START = 294
EXPECTED_CLAUSE_END = 356
RELEVANT_REASON_CODES = (
    "NEW_IMPLICATION",
    "UNCERTAINTY_STRENGTHENED",
)
ACCEPTABLE_REASON_CODES = SELECTED_CASE_REASON_CODES_ACCEPTABLE_AUDIT_ONLY
BLOCKING_VERDICTS = (
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    VERDICT_REVIEW,
    VERDICT_FAIL,
    "REVIEW",
    "FAIL",
    "QUESTIONABLE",
    "UNSUPPORTED",
)
ACCEPTING_VERDICTS = (VERDICT_PASS, CLASS_SUPPORTED, "PASS", "SUPPORTED")

HISTORICAL_4B275_STATUS = "PASS"
HISTORICAL_4B276_STATUS = "PASS"

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert PROMPT_VERSION == "book-semantic-validator-1.1.3-candidate"
assert TRANSPORT_VERSION == "book-semantic-validation-transport-1.1-candidate"
assert PROMPT_VERSION_HISTORICAL == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION_HISTORICAL == "book-semantic-validation-transport-1.0"
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
assert TOKEN_FIELD == "max_completion_tokens"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert SELECTED_CASE_HANDLE == "h11"
assert SELECTED_CASE_ID == "4b276_p4_new_implication"
assert SELECTED_CASE_ORIGIN == "SYNTHETIC_VARIANT_OF_4B22_P4_SUPPORTED"
assert SELECTED_CASE_ROLE == "synthetic_negative"
assert SELECTED_CASE_HUMAN_LABEL == CLASS_UNSUPPORTED
assert SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY is True
assert DISPUTED_CLAUSE == (
    "which means that every believer is guaranteed a fearless death"
)
assert TARGET_FAILURE_FAMILY == "NEW_IMPLICATION_AND_UNCERTAINTY_STRENGTHENED"
assert P4_EVIDENCE_HANDLES == (
    "IDEA226",
    "SRC006192",
    "SRC006193",
    "SRC006195",
)
assert EXPECTED_REQUEST_SHA256 != H01_REQUEST_SHA256
assert EXPECTED_REQUEST_SHA256 != H02_REQUEST_SHA256
assert H01_REQUEST_SHA256 == (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
assert H02_REQUEST_SHA256 == (
    "5ace261296d808437910f8f9efe247a80daebbb2237bc8af46bda56bf98d7897"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert HISTORICAL_4B262_STATUS == "PASS"
assert HISTORICAL_4B27_STATUS == "PARTIAL"
assert HISTORICAL_4B271_STATUS == "PASS"
assert HISTORICAL_4B272_STATUS == "PASS"
assert HISTORICAL_4B273_STATUS == "PARTIAL"
assert HISTORICAL_4B274_STATUS == "PASS"
assert HISTORICAL_4B275_STATUS == "PASS"
assert HISTORICAL_4B276_STATUS == "PASS"
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert AUTHORIZED_REMOTE_TERRA_INVOCATIONS == 1
assert AUTHORIZED_SONNET_CALLS == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert SDK_MAX_RETRIES == 0
assert PUBLICATION_AUTHORIZED is False
assert SOURCE_CASE_HANDLE == "h03"
assert SOURCE_CASE_ID == "4b22_p4_supported"
assert SCORED_CASE_ORDER[2] == (SOURCE_CASE_HANDLE, SOURCE_CASE_ID)
assert SELECTED_CASE_HANDLE not in {opaque for opaque, _ in SCORED_CASE_ORDER}
assert CANONICAL_PYTHON_EXECUTABLE.endswith("python.exe")

CONNECT_TIMEOUT_SECONDS = 30.0
READ_TIMEOUT_SECONDS = 600.0
CANARY_WINDOW_ID = "book-semantic-gate-4b277"

AUDIT_DIRNAME = "book_semantic_gate_4b277"
AUDIT_REAL_PARENT = "real"
AUDIT_PREFLIGHT = "preflight_integrity.json"
AUDIT_REQUEST = "frozen_request_verification.json"
AUDIT_LEAK = "label_leakage_verification.json"
AUDIT_SERIALIZATION = "sdk_serialization_verification.json"
AUDIT_INVOCATION = "provider_invocation.json"
AUDIT_RAW_RESPONSE = "provider_response_raw.json"
AUDIT_RAW_TEXT = "provider_response_text.txt"
AUDIT_USAGE = "provider_usage.json"
AUDIT_COST = "cost_accounting.json"
AUDIT_VALIDATION = "structural_validation.json"
AUDIT_SEMANTIC = "claim_by_claim_semantic_review.json"
AUDIT_HUMAN = "human_reference_comparison.json"
AUDIT_REPLAY = "offline_replay.json"
AUDIT_TESTS = "regression_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_LOCK = "h11_real_call.lock"
AUDIT_INDEX = "book_semantic_gate_4b277_index.json"
REPORT_NAME = "PHASE_4B277_ONE_REAL_TERRA_H11_DISCRIMINATING_CANARY_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False
