"""Rapport markdown 3B.7.7A.37."""

from __future__ import annotations

from typing import Any, Mapping

from app.source_analysis_v31_global_v11_grammar_canary.constants import (
    CANARY_MAX_OUTPUT_TOKENS,
    LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
    MODEL,
    OUTPUT_HEADROOM_LABEL,
    OUTPUT_HEADROOM_PERCENT,
    PRODUCTION_ESTIMATED_COST_USD,
    PRODUCTION_MAX_OUTPUT_TOKENS,
    PRODUCTION_OUTPUT_HEADROOM_TOKENS,
    PRODUCTION_PROVIDER_ADJUSTED_TOKENS,
    PRODUCTION_WORST_CASE_OUTPUT_TOKENS,
    PROMPT_VERSION,
    RELATION_QUALITY_TECHNICAL_DEBT,
    SCHEMA_ADAPTED_BYTES,
    SCHEMA_HASH,
    SCHEMA_RAW_BYTES,
    TRANSPORT_VERSION,
)
from app.source_analysis_v31_global_v11_grammar_canary.runner import CanaryRunResult


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    return str(value)


def render_report(
    result: CanaryRunResult,
    *,
    tests: str,
    extra_header: Mapping[str, Any] | None = None,
) -> str:
    exe = result.execution or {}
    dry = result.dry_run or {}
    extra = dict(extra_header or {})
    verdict = exe.get("result") or extra.get("result") or result.mode
    schema_raw = exe.get("schema_raw_bytes") or dry.get("schema_raw_bytes") or SCHEMA_RAW_BYTES
    schema_adapted = (
        exe.get("schema_adapted_bytes")
        or dry.get("schema_adapted_bytes")
        or SCHEMA_ADAPTED_BYTES
    )
    schema_hash = exe.get("schema_hash") or dry.get("schema_hash") or SCHEMA_HASH
    cost = (exe.get("cost") or {}).get("display") or (exe.get("cost") or {}).get("total_cost")
    elapsed = exe.get("provider_elapsed_ms")
    elapsed_display = f"{elapsed} ms" if elapsed is not None else "n/a"
    lines = [
        "# PHASE 3B.7.7A.37 — GLOBAL CONSOLIDATION V1.1 TINY GRAMMAR CANARY",
        "",
        "## Result",
        "",
        str(verdict),
        "",
        "AUTHORIZED PROVIDER CALLS =",
        "1",
        "",
        "ACTUAL PROVIDER CALLS =",
        str(exe.get("actual_calls") if exe else result.anthropic_post_attempts),
        "",
        "SUCCESSFUL PROVIDER CALLS =",
        str(exe.get("successful_calls") if exe else 0),
        "",
        "RETRIES =",
        "0",
        "",
        "PASTORAL DATA SENT =",
        "NO",
        "",
        "REAL CONSOLIDATION EXECUTED =",
        "NO",
        "",
        "MODEL =",
        MODEL,
        "",
        "PROMPT =",
        PROMPT_VERSION,
        "",
        "TRANSPORT =",
        TRANSPORT_VERSION,
        "",
        "SCHEMA RAW / ADAPTED =",
        f"{_dash(schema_raw)} / {_dash(schema_adapted)}",
        "",
        "SCHEMA HASH =",
        _dash(schema_hash),
        "",
        "SCHEMA IDENTITY =",
        _dash(exe.get("schema_identity") or dry.get("schema_identity")),
        "",
        "HTTP =",
        _dash(exe.get("http_status")),
        "",
        "FINISH =",
        _dash(exe.get("finish_reason")),
        "",
        "THINKING =",
        "disabled",
        "",
        "ACTUAL THINKING TOKENS =",
        _dash(exe.get("thinking_tokens")),
        "",
        "MAX OUTPUT CANARY =",
        str(exe.get("max_output_canary") or CANARY_MAX_OUTPUT_TOKENS),
        "",
        "REQUEST ID =",
        _dash(exe.get("request_id")),
        "",
        "INPUT TOKENS =",
        _dash(exe.get("input_tokens") or exe.get("provider_input")),
        "",
        "OUTPUT TOKENS =",
        _dash(exe.get("output_tokens")),
        "",
        "COST =",
        _dash(cost),
        "",
        "ELAPSED =",
        elapsed_display,
        "",
        "STRUCTURED PARSE =",
        _dash(exe.get("structured_parse")),
        "",
        "D.O ENUM =",
        _dash(exe.get("d_o_enum")),
        "",
        "D.W ENUM =",
        _dash(exe.get("d_w_enum")),
        "",
        "FREE-TEXT DROP REASON =",
        _dash(exe.get("free_text_drop_reason")),
        "",
        "LINK_RELATED =",
        _dash(exe.get("link_related")),
        "",
        "OPERATION/REASON MATRIX =",
        _dash(exe.get("operation_reason_matrix")),
        "",
        "TRANSPORT DECODER =",
        _dash(exe.get("transport_decoder")),
        "",
        "HANDLES =",
        _dash(exe.get("handle_validation")),
        "",
        "IDEA DISPOSITION COVERAGE =",
        _dash(exe.get("idea_disposition_coverage")),
        "",
        "SILENT DROPS =",
        _dash(exe.get("silent_drops")),
        "",
        "MERGE SOURCE UNION =",
        _dash(exe.get("merge_source_union")),
        "",
        "TRACEABILITY =",
        _dash(exe.get("traceability")),
        "",
        "GLOBAL VALIDATOR =",
        _dash(exe.get("global_validator")),
        "",
        "CANONICAL RECONSTRUCTION =",
        _dash(exe.get("canonical_reconstruction")),
        "",
        "CANONICAL VALIDATION =",
        _dash(exe.get("canonical_validation")),
        "",
        "DETERMINISTIC REPLAY =",
        _dash(exe.get("deterministic_replay")),
        "",
        "SEMANTIC FIXTURE REVIEW =",
        _dash(exe.get("semantic_fixture_review")),
        "",
        "A.35 ROOT DEFECT =",
        _dash(exe.get("a35_root_defect")),
        "",
        "GLOBAL_TRANSPORT_1_1_GRAMMAR_PROOF =",
        _dash(exe.get("global_transport_1_1_grammar_proof")),
        "",
        "LOCAL EXTRACTION FUNCTIONALLY FROZEN =",
        LOCAL_EXTRACTION_FUNCTIONALLY_FROZEN,
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        RELATION_QUALITY_TECHNICAL_DEBT,
        "",
        "PRODUCTION INPUT ESTIMATE =",
        f"~{PRODUCTION_PROVIDER_ADJUSTED_TOKENS} provider-adjusted tokens",
        "",
        "PRODUCTION MAX OUTPUT =",
        str(PRODUCTION_MAX_OUTPUT_TOKENS),
        "",
        "WORST-CASE OUTPUT ESTIMATE =",
        f"~{PRODUCTION_WORST_CASE_OUTPUT_TOKENS}",
        "",
        "OUTPUT HEADROOM =",
        (
            f"~{PRODUCTION_OUTPUT_HEADROOM_TOKENS} / ~{OUTPUT_HEADROOM_PERCENT}% "
            f"({OUTPUT_HEADROOM_LABEL})"
        ),
        "",
        "ESTIMATED REAL CONSOLIDATION COST =",
        PRODUCTION_ESTIMATED_COST_USD,
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        _dash(extra.get("new_failures") or "0"),
        "",
        "READY_FOR_REAL_GLOBAL_CONSOLIDATION_CANARY =",
        _dash(exe.get("ready_for_real_global_consolidation_canary") or "NO"),
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## Notes",
        "",
        f"Authorization scope = {result.authorization_scope}",
        "",
        f"Error = {_dash(result.error)}",
        "",
        "A.37 does not authorize real consolidation even if readiness is YES.",
        "",
        "Do not automatically run the real global consolidation canary.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
