"""Constantes 3B.7.7A.25 — architecture metadata + forensics A.24. 0 provider."""

from __future__ import annotations

from app.source_analysis.models import EXAMPLE_KINDS, IDEA_KINDS, IMPORTANCE_LEVELS
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
    SELECTED_ARCHITECTURE as V3_HANDLE_ARCHITECTURE,
    SEMANTIC_TRANSPORT_VERSION_V3,
    WINDOW_ANALYSIS_PROMPT_VERSION_V13,
    WINDOW_ANALYSIS_PROMPT_VERSION_V131,
    WINDOW_ANALYSIS_PROMPT_VERSION_V132,
)
from app.source_analysis_local_v3.schema import semantic_transport_v3_fingerprint
from app.source_analysis_v3_a19_forensics.constants import (
    A19_STATUS_UNCHANGED,
    EXAMPLE_POLICY,
    EXAMPLE_POLICY_LABEL,
)
from app.source_analysis_v3_a22_forensics.constants import A22_STATUS_UNCHANGED
from app.source_analysis_v3_hardened_win001.constants import (
    EXPECTED_SCHEMA_HASH,
    REPORT_NAME as A21_REPORT_NAME,
)
from app.source_analysis_v3_hardened_win004.constants import (
    A21_RESULT,
    A23_RESULT,
    COMPARISON_ARTIFACT as A24_COMPARISON_ARTIFACT,
    EXECUTION_ARTIFACT as A24_EXECUTION_ARTIFACT,
    EXPECTED_ANALYSIS_SIGNATURE as A24_SIGNATURE,
    EXPECTED_FORENSIC_IDENTITY as A24_FORENSIC_IDENTITY,
    EXPECTED_LOCAL_INPUT_ESTIMATE as A24_LOCAL_INPUT,
    EXPECTED_PROMPT_FINGERPRINT as A24_PROMPT_FINGERPRINT,
    EXPECTED_PROMPT_SHA256 as A24_PROMPT_SHA256,
    HANDLE_ARTIFACT as A24_HANDLE_ARTIFACT,
    LOCK_NAME as A24_LOCK_NAME,
    METADATA_ARTIFACT as A24_METADATA_ARTIFACT,
    PREFLIGHT_ARTIFACT as A24_PREFLIGHT_ARTIFACT,
    PROTECTED_HISTORICAL as A24_PROTECTED_HISTORICAL,
    REPORT_NAME as A24_REPORT_NAME,
    REVIEW_ARTIFACT as A24_REVIEW_ARTIFACT,
    SRC_ARTIFACT as A24_SRC_ARTIFACT,
    WINDOW_ID,
)
from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.25"
MODE = "POST_A24_METADATA_ARCHITECTURE_AND_SEMANTIC_DELTA_FORENSICS"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
WIN004_RETRY_AUTHORIZED = False
FUTURE_REAL_CALL_AUTHORIZED = False

A19_STATUS = A19_STATUS_UNCHANGED
A21_STATUS = A21_RESULT
A22_STATUS = A22_STATUS_UNCHANGED
A23_STATUS = A23_RESULT
A24_STATUS_UNCHANGED = "FAIL"

A24_TARGET = "WIN004"
A24_SRC_RANGE = "SRC003607 → SRC004786"
A24_OWNED = 1180
A24_WORDS = 5662
A24_PROVIDER_INPUT = 48725
A24_OUTPUT = 10559
A24_MAX_OUTPUT = MAX_OUTPUT_TOKENS_FROZEN
A24_THINKING = "disabled"
A24_THINKING_TOKENS = 0
A24_FINISH = "end_turn"
A24_HTTP = 200
A24_STRUCTURED_PARSE = "PASS"
A24_CAPACITY_SIGNAL = "absent"
A24_RECORDS = 103
A24_TOPIC = 12
A24_IDEA = 47
A24_RELATION = 22
A24_EXAMPLE = 9
A24_REFERENCE = 8
A24_UNCERTAINTY = 5
A24_TOTAL_SRC_OCCURRENCES = 359
A24_VALID_SRC_OCCURRENCES = 359
A24_DISTINCT_SRC = 272
A24_COVERAGE_PCT = 23.05
A24_REQUEST_ID = "req_011CfT17hSUwd7uT8fKw32Gd"

A24_RAW_SHA256 = (
    "b394d3ff190eefc6a4f1dd31a0244dc5fcc3034cc51d310ec2259fe00d310db4"
)
A24_RAW_SIZE = 27450

A24_FORENSIC_RELATIVE = (
    "audit/canary/v3_hardened_win004/provider_forensics/WIN004/" + A24_SIGNATURE
)
A24_LOCK_RELATIVE = f"audit/canary/v3_hardened_win004/{A24_LOCK_NAME}"

PROTECTED_A24 = (
    f"audit/{A24_REPORT_NAME}",
    f"audit/{A24_PREFLIGHT_ARTIFACT}",
    f"audit/{A24_EXECUTION_ARTIFACT}",
    f"audit/{A24_METADATA_ARTIFACT}",
    f"audit/{A24_SRC_ARTIFACT}",
    f"audit/{A24_HANDLE_ARTIFACT}",
    f"audit/{A24_REVIEW_ARTIFACT}",
    f"audit/{A24_COMPARISON_ARTIFACT}",
    A24_LOCK_RELATIVE,
    f"{A24_FORENSIC_RELATIVE}/provider_raw_response.bin",
    f"{A24_FORENSIC_RELATIVE}/provider_http_envelope.json",
)

PROTECTED_HISTORICAL = tuple(A24_PROTECTED_HISTORICAL) + PROTECTED_A24

INVALID_IDEA_INDEX = 55
INVALID_IDEA_HANDLE = "I44"
VALID_IDEA_KINDS = IDEA_KINDS
VALID_EXAMPLE_KINDS = EXAMPLE_KINDS
VALID_IMPORTANCE = IMPORTANCE_LEVELS

IDEA_KIND_COUNTS_EXPECTED = {
    "claim": 23,
    "explanation": 5,
    "principle": 2,
    "instruction": 2,
    "observation": 4,
    "question": 1,
    "testimony": 9,
    "example": 1,
}

A22_RECORDS = 127
A22_IDEA = 58
A22_RELATION = 35
A22_EXAMPLE = 9
A22_REFERENCE = 8
A22_UNCERTAINTY = 5

SEMANTIC_REVIEW_STATUS = "FORENSIC_SEMANTIC_REVIEW_OF_INVALID_A24_WIN004_TRANSPORT"
SEMANTIC_COUNTERFACTUAL = "SEMANTICALLY_ACCEPTABLE_BUT_FOR_METADATA"
I44_CLASSIFICATION = "REDUNDANT_COLLAPSED_PROPOSITION_PLUS_ILLUSTRATION"
PROMPT_132_EFFECT = "IMPROVED_NOT_RELIABLY_ENFORCED"
M_OVERLOADED = True
IDEA_SUBTYPE_REQUIRED_LOCALLY = False
IDEA_SUBTYPE_REQUIRED_CANONICALLY = "OPTIONAL"
SELECTED_ARCHITECTURE = "GLOBALIZE_IDEA_SUBTYPE"
IMPLEMENTATION_SCOPE = "DESIGN_ONLY"
NEW_PROMPT_DESIGNED = "window-analysis-1.4.0"
NEW_TRANSPORT_DESIGNED = "semantic-transport-v3.1-local-lite"
NEW_PROMPT_ACTIVATED = False
NEW_TRANSPORT_ACTIVATED = False
SCHEMA_CHANGED = False
SERVER_GRAMMAR_STATUS = "A18_PROOF_APPLICABLE"
THINKING_DISABLED_QUALITY_ISSUE = "UNPROVEN"
MISSING_IDEA_AUTOMATED = (
    "The Fall: life cut off; knowing good and evil; inherited condition."
)
MISSING_IDEA_INDEPENDENT = "PRESENT_AS_T9_I28_I31_NEEDLE_FALSE_NEGATIVE"
MISSING_IDEA_MATERIALITY = "MINOR"
PARTIAL_IDEA = (
    "Jesus' commission was simple; no uniform extra conditions; "
    "unique spiritual fingerprint."
)
PARTIAL_IDEA_VS_A23 = "DIFFERENT"
FUTURE_REAL_CALL_TYPE = "OFFLINE_IMPLEMENTATION_FOLLOW_UP"
FUTURE_REAL_CALL_READY = False
READY_WINDOWS = "1 / 7"

VIOLATION_ARTIFACT = "source_analysis_v3_a24_exhaustive_violation_inventory.json"
I44_ARTIFACT = "source_analysis_v3_a24_i44_decomposition.json"
METADATA_ARTIFACT = "source_analysis_local_metadata_necessity_analysis.json"
ARCHITECTURE_ARTIFACT = "source_analysis_local_transport_architecture_decision.json"
DELTA_ARTIFACT = "source_analysis_v3_a22_vs_a24_semantic_delta.json"
SEMANTIC_ARTIFACT = "source_analysis_v3_a24_forensic_semantic_review.json"
POLICY_ARTIFACT = "source_analysis_local_semantic_acceptance_policy.json"
FUTURE_ARTIFACT = "source_analysis_post_a24_future_call_readiness.json"
REPORT_NAME = "PHASE_3B77A25_POST_A24_METADATA_ARCHITECTURE_DECISION_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
NEXT_PHASE = "3B.7.7A.26_OFFLINE_GLOBALIZE_IDEA_SUBTYPE_IMPLEMENTATION"
NEXT_PHASE_LABEL = (
    "3B.7.7A.26 — OFFLINE GLOBALIZE-IDEA-SUBTYPE IMPLEMENTATION "
    "(design follow-up; 0 provider calls; do not execute in A.25)"
)
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION

assert EXPECTED_SCHEMA_HASH == semantic_transport_v3_fingerprint()
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert A24_MAX_OUTPUT == 32000
assert A24_OWNED == 1180
assert A24_WORDS == 5662
assert A19_STATUS == "FAIL"
assert A21_STATUS == "PASS"
assert A22_STATUS == "FAIL"
assert A23_STATUS == "PASS"
assert A24_STATUS_UNCHANGED == "FAIL"
assert WINDOW_ANALYSIS_PROMPT_VERSION_V132 == "window-analysis-1.3.2"
assert "example" not in IDEA_KINDS
assert "example" in EXAMPLE_KINDS
assert "testimony" in IDEA_KINDS and "testimony" in EXAMPLE_KINDS
assert SELECTED_ARCHITECTURE == "GLOBALIZE_IDEA_SUBTYPE"
assert SCHEMA_CHANGED is False
assert WIN004_RETRY_AUTHORIZED is False
assert FUTURE_REAL_CALL_AUTHORIZED is False
assert REAL_PROVIDER_CALLS_THIS_PHASE == 0

__all__ = [
    "A19_STATUS",
    "A21_REPORT_NAME",
    "A21_STATUS",
    "A22_EXAMPLE",
    "A22_IDEA",
    "A22_RECORDS",
    "A22_REFERENCE",
    "A22_RELATION",
    "A22_STATUS",
    "A22_UNCERTAINTY",
    "A23_STATUS",
    "A24_CAPACITY_SIGNAL",
    "A24_COMPARISON_ARTIFACT",
    "A24_COVERAGE_PCT",
    "A24_DISTINCT_SRC",
    "A24_EXAMPLE",
    "A24_EXECUTION_ARTIFACT",
    "A24_FINISH",
    "A24_FORENSIC_IDENTITY",
    "A24_FORENSIC_RELATIVE",
    "A24_HANDLE_ARTIFACT",
    "A24_HTTP",
    "A24_IDEA",
    "A24_LOCAL_INPUT",
    "A24_LOCK_NAME",
    "A24_LOCK_RELATIVE",
    "A24_MAX_OUTPUT",
    "A24_METADATA_ARTIFACT",
    "A24_OUTPUT",
    "A24_OWNED",
    "A24_PREFLIGHT_ARTIFACT",
    "A24_PROMPT_FINGERPRINT",
    "A24_PROMPT_SHA256",
    "A24_PROVIDER_INPUT",
    "A24_RAW_SHA256",
    "A24_RAW_SIZE",
    "A24_RECORDS",
    "A24_REFERENCE",
    "A24_RELATION",
    "A24_REPORT_NAME",
    "A24_REQUEST_ID",
    "A24_REVIEW_ARTIFACT",
    "A24_SIGNATURE",
    "A24_SRC_ARTIFACT",
    "A24_SRC_RANGE",
    "A24_STATUS_UNCHANGED",
    "A24_STRUCTURED_PARSE",
    "A24_TARGET",
    "A24_THINKING",
    "A24_THINKING_TOKENS",
    "A24_TOPIC",
    "A24_TOTAL_SRC_OCCURRENCES",
    "A24_UNCERTAINTY",
    "A24_VALID_SRC_OCCURRENCES",
    "A24_WORDS",
    "ARCHITECTURE_ARTIFACT",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER",
    "DELTA_ARTIFACT",
    "EXAMPLE_POLICY",
    "EXAMPLE_POLICY_LABEL",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "EXPECTED_SCHEMA_HASH",
    "FUTURE_ARTIFACT",
    "FUTURE_REAL_CALL_AUTHORIZED",
    "FUTURE_REAL_CALL_READY",
    "FUTURE_REAL_CALL_TYPE",
    "I44_ARTIFACT",
    "I44_CLASSIFICATION",
    "IDEA_KIND_COUNTS_EXPECTED",
    "IDEA_SUBTYPE_REQUIRED_CANONICALLY",
    "IDEA_SUBTYPE_REQUIRED_LOCALLY",
    "IMPLEMENTATION_SCOPE",
    "INVALID_IDEA_HANDLE",
    "INVALID_IDEA_INDEX",
    "METADATA_ARTIFACT",
    "MISSING_IDEA_AUTOMATED",
    "MISSING_IDEA_INDEPENDENT",
    "MISSING_IDEA_MATERIALITY",
    "MODE",
    "M_OVERLOADED",
    "NEW_PROMPT_ACTIVATED",
    "NEW_PROMPT_DESIGNED",
    "NEW_TRANSPORT_ACTIVATED",
    "NEW_TRANSPORT_DESIGNED",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "PARTIAL_IDEA",
    "PARTIAL_IDEA_VS_A23",
    "PHASE",
    "PHASE_3B_STATUS",
    "POLICY_ARTIFACT",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_132_EFFECT",
    "PROTECTED_A24",
    "PROTECTED_HISTORICAL",
    "READY_WINDOWS",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "REPORT_NAME",
    "SCHEMA_CHANGED",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SEMANTIC_ARTIFACT",
    "SEMANTIC_COUNTERFACTUAL",
    "SEMANTIC_REVIEW_STATUS",
    "SEMANTIC_TRANSPORT_VERSION_V3",
    "SERVER_GRAMMAR_STATUS",
    "THINKING_DISABLED_QUALITY_ISSUE",
    "VALID_EXAMPLE_KINDS",
    "VALID_IDEA_KINDS",
    "VALID_IMPORTANCE",
    "VIOLATION_ARTIFACT",
    "V3_HANDLE_ARCHITECTURE",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V13",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V131",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V132",
    "WINDOW_ID",
    "WIN004_RETRY_AUTHORIZED",
]
