"""Rapport 3B.7.7A.25."""

from __future__ import annotations

from typing import Any, Mapping


def render_report(
    *,
    header: Mapping[str, Any],
    inventory: Mapping[str, Any],
    src_audit: Mapping[str, Any],
    metadata: Mapping[str, Any],
    i44: Mapping[str, Any],
    semantic: Mapping[str, Any],
    coverage: Mapping[str, Any],
    delta: Mapping[str, Any],
    architecture: Mapping[str, Any],
    policy: Mapping[str, Any],
    future: Mapping[str, Any],
    handles: Mapping[str, Any],
    isolation: Mapping[str, Any],
    tests: str,
) -> str:
    example_q = header.get("a24_example_quality") or {}
    spec = architecture.get("selected_spec") or {}
    fall = (delta.get("major_idea_delta") or {}).get("missing_idea_automated") or {}
    lines = [
        "# PHASE 3B.7.7A.25 — POST-A.24 METADATA ARCHITECTURE DECISION",
        "",
        "## Result",
        "",
        str(header.get("result")),
        "",
        f"REAL PROVIDER CALLS = {header.get('real_provider_calls')}",
        "",
        f"REAL WINDOW CALLS = {header.get('real_window_calls')}",
        "",
        "A.24 STATUS = FAIL unchanged",
        "",
        f"A.24 ROOT VIOLATIONS = {header.get('a24_root_violations')}",
        "",
        f"A.24 CASCADE VIOLATIONS = {header.get('a24_cascade_violations')}",
        "",
        f"I44 CLASSIFICATION = {header.get('i44_classification')}",
        "",
        f"M[] OVERLOADED = {'YES' if header.get('m_overloaded') else 'NO'}",
        "",
        f"IDEA SUBTYPE REQUIRED LOCALLY = {'YES' if header.get('idea_subtype_required_locally') else 'NO'}",
        "",
        f"IDEA SUBTYPE REQUIRED CANONICALLY = {header.get('idea_subtype_required_canonically')}",
        "",
        f"IDEA SUBTYPE DOWNSTREAM CONSUMERS = {header.get('idea_subtype_downstream_consumers')}",
        "",
        f"A.24 MISSING MAJOR IDEA = {header.get('a24_missing_major_idea')}",
        "",
        f"MISSING IDEA MATERIALITY = {header.get('missing_idea_materiality')}",
        "",
        f"A.24 PARTIAL IDEA = {header.get('a24_partial_idea')}",
        "",
        f"A.24 SEMANTIC COUNTERFACTUAL = {header.get('a24_semantic_counterfactual')}",
        "",
        f"A.22→A.24 RECORD DELTA = {header.get('a22_to_a24_record_delta')}",
        "",
        f"A.24 RELATION QUALITY = {header.get('a24_relation_quality')}",
        "",
        (
            "A.24 EXAMPLE QUALITY = "
            f"{example_q.get('count')} source-grounded; "
            f"{example_q.get('idea_separation')}"
        ),
        "",
        f"UNSUPPORTED CONTENT = {header.get('unsupported_content')}",
        "",
        f"SEMANTIC SRC COVERAGE = {header.get('semantic_src_coverage')}",
        "",
        f"THINKING_DISABLED QUALITY ISSUE = {header.get('thinking_disabled_quality_issue')}",
        "",
        f"SELECTED ARCHITECTURE = {header.get('selected_architecture')}",
        "",
        f"NEW PROMPT = {header.get('new_prompt')} (designed, not activated)",
        "",
        f"NEW TRANSPORT = {header.get('new_transport')} (designed, not activated)",
        "",
        f"SCHEMA CHANGED = {'YES' if header.get('schema_changed') else 'NO'}",
        "",
        f"RAW SCHEMA BYTES = {header.get('raw_schema_bytes')}",
        "",
        f"ADAPTED SCHEMA BYTES = {header.get('adapted_schema_bytes')}",
        "",
        f"SERVER GRAMMAR STATUS = {header.get('server_grammar_status')}",
        "",
        "FAKEAI 7 WINDOWS = existing V3 contract only (no new transport activated)",
        "",
        "DIRECT CONSOLIDATION = existing V3 FakeAI (unchanged contract)",
        "",
        "HIERARCHICAL CONSOLIDATION = existing V3 FakeAI (unchanged contract)",
        "",
        "CANONICAL RECONSTRUCTION = existing V3 FakeAI (unchanged contract)",
        "",
        f"SEMANTIC ACCEPTANCE POLICY = {header.get('semantic_acceptance_policy')}",
        "",
        f"FUTURE REAL CALL TYPE = {header.get('future_real_call_type')}",
        "",
        f"FUTURE REAL CALL READY = {'YES' if header.get('future_real_call_ready') else 'NO'}",
        "",
        "FUTURE REAL CALL AUTHORIZED = NO",
        "",
        f"REAL WINDOWS READY = {header.get('real_windows_ready')}",
        "",
        f"PRODUCTION DEFAULT = {header.get('production_default')}",
        "",
        "SOURCE MAP = NOT PUBLISHED",
        "",
        "PHASE 3B = INCOMPLETE",
        "",
        f"TESTS = {tests}",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
        "## 1. Provider calls",
        "",
        "How many provider calls occurred? 0",
        "Real window calls? 0",
        "WIN004 retried? NO",
        "Remaining windows called? NO",
        "Consolidation executed for real? NO",
        "A.24 mutated? NO",
        "source_map published? NO",
        "",
        "## 2. Historical status",
        "",
        f"A.19 = {header.get('a19_status')} (unchanged)",
        f"A.21 = {header.get('a21_status')} (unchanged)",
        f"A.22 = {header.get('a22_status')} (unchanged)",
        f"A.23 = {header.get('a23_status')} (unchanged)",
        "A.24 = FAIL unchanged",
        "READY remains 1 / 7 (WIN001 only).",
        "",
        "## 3. A.24 exhaustive violations",
        "",
        f"Root = {header.get('a24_root_violations')} (expected 1; independently verified).",
        f"Cascade = {header.get('a24_cascade_violations')}.",
        f"Codes = {inventory.get('by_code')}.",
        f"SRC valid = {src_audit.get('valid_canonical_owned_occurrences')} / "
        f"{src_audit.get('total_src_reference_occurrences')}.",
        f"Numeric link regression = {header.get('numeric_link_regression')}.",
        f"Handle gate = {header.get('handle_gate_pass')}.",
        "Production decoder remains fail-fast. A.24 is not repaired or promoted.",
        "",
        "## 4. I44",
        "",
        f"Handle={i44.get('raw', {}).get('h')} index={i44.get('index')} m={i44.get('raw', {}).get('m')}.",
        f"Classification={i44.get('classification')}.",
        f"Valid EXAMPLE for same national-leader/economy material="
        f"{(i44.get('duplicate_example_check') or {}).get('valid_example_for_same_material')}.",
        (i44.get("why_kind_example_after_1_3_2") or {}).get("q1_answer") or "",
        "Proposition / illustration / supporting relation are recorded in the I44 artifact.",
        "Historical payload was not repaired.",
        "",
        "## 5. m[] necessity",
        "",
        f"Overloaded={metadata.get('m_overloaded')}.",
        (metadata.get("idea_subtype_necessity") or {}).get("q2_answer") or "",
        (metadata.get("idea_subtype_necessity") or {}).get("q4_answer") or "",
        "IDEA kind is canonical at source_map publication and is copied today by "
        "the reconstructor. It is not required for local extraction. Book/"
        "Editorial Planner do not consume it. It can be classified later.",
        "",
        "## 6. Prompt 1.3.2 effectiveness",
        "",
        f"{header.get('prompt_1_3_2_effect')}.",
        "invalid IDEA example 4 → 1. Three known patterns corrected. One persisted.",
        "IMPROVED is not RELIABLY_ENFORCED. A third prompt-only prohibition is rejected.",
        "",
        "## 7. A.22 → A.24 semantic delta",
        "",
        f"Record delta={header.get('a22_to_a24_record_delta')}.",
        (delta.get("record_distribution") or {})
        .get("reduction_analysis", {})
        .get("overall"),
        f"Automated missing idea={fall.get('automated_missing_label')}.",
        f"Independent class={fall.get('independent_class')}.",
        f"Materiality={fall.get('materiality')}.",
        f"Partial idea (different from A.23)={header.get('a24_partial_idea')}.",
        "Do not blame the reported miss on transport failure. Output/input pressure unsupported.",
        "",
        "## 8. Semantic review",
        "",
        f"Status={semantic.get('status')}.",
        f"Counterfactual={semantic.get('semantic_counterfactual')}.",
        f"Unsupported={semantic.get('unsupported_content')}.",
        f"Coverage={coverage.get('verified_semantic_src_coverage_pct')} "
        f"({coverage.get('verified_distinct_canonical_owned')} / "
        f"{coverage.get('owned_src_count')}).",
        f"Beginning/middle/end={semantic.get('beginning_middle_end')}.",
        f"Relations={header.get('a24_relation_quality')}.",
        "A.24 is semantically acceptable but for metadata. One missing major "
        "idea on needles is not independently inadequate.",
        "",
        "## 9. Thinking",
        "",
        f"THINKING_DISABLED quality issue={header.get('thinking_disabled_quality_issue')}.",
        semantic.get("thinking_disabled_note"),
        "Do not switch to ADAPTIVE_LOW. Adaptive thinking consumes shared max output (CALL C).",
        "",
        "## 10. Architecture",
        "",
        f"Selected={architecture.get('selected')}.",
        spec.get("why_not_prompt_1_3_3"),
        spec.get("why_not_v4_structural"),
        f"Local IDEA.m designed as {spec.get('local_representation')}.",
        f"Implementation scope={spec.get('implementation_scope')}.",
        "V4 structural transport was evaluated and not selected. No v4 design file written.",
        "Historical semantic-transport-v3 and window-analysis-1.3.2 are unmutated.",
        "",
        "## 11. Semantic acceptance policy",
        "",
        f"Policy={policy.get('policy_id')} status={policy.get('status')}.",
        "No raw SRC percentage. No minimum TOPIC/IDEA/RELATION counts.",
        (policy.get("material_omission") or {}).get("definition"),
        "",
        "## 12. Future call",
        "",
        f"Type={future.get('future_real_call_type')}.",
        "Ready=NO. Authorized=NO. WIN004 retry=NO. Grammar canary=NO.",
        "Next phase candidate A: offline implementation follow-up. Do not execute here.",
        "",
        "## 13. Isolation",
        "",
        f"source_map_present={isolation.get('source_map_present')}.",
        f"candidate_cache_present={isolation.get('candidate_cache_present')}.",
        f"read_only={isolation.get('read_only')}.",
        f"A.24 raw present={isolation.get('raw_present')}.",
        f"Handles inspected={bool(handles)}.",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
    ]
    return "\n".join(str(line) if line is not None else "" for line in lines)


__all__ = ["render_report"]
