"""Constantes 3B.7.7A.16 — forensics A.15 offline. 0 provider."""

from __future__ import annotations

from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    CANDIDATE_WINDOW_ANALYSIS_PROMPT_VERSION,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
    SEMANTIC_TRANSPORT_VERSION_V2,
    TARGET_JSON_LOCAL_TOKENS,
    WINDOW_ANALYSIS_PROMPT_VERSION_V121,
)
from app.source_analysis_small_window_hierarchy.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
)
from app.source_analysis_v2_grammar_canary.constants import (
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)
from app.source_analysis_v2_link_semantics.constants import A13_REQUEST_IDENTITY
from app.source_analysis_v2_real_win001.constants import (
    EXPECTED_ANALYSIS_SIGNATURE,
    EXPECTED_CLEAN_SHA,
    EXPECTED_FIRST_OWNED_SRC,
    EXPECTED_LAST_OWNED_SRC,
    EXPECTED_OWNED_SRC_COUNT,
    EXPECTED_WINDOW_INPUT_HASH,
    EXPECTED_WORD_COUNT,
    WINDOW_ID,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.16"
MODE = "OFFLINE_A15_INVALID_LINK_FORENSICS_AND_SEMANTIC_REVIEW"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
WIN001_RETRY_AUTHORIZED = False
FUTURE_REAL_CALL_AUTHORIZED = False
SEMANTIC_REVIEW_STATUS = "FORENSIC_SEMANTIC_REVIEW_OF_INVALID_TRANSPORT"

A15_PHASE = "3B.7.7A.15"
A15_SIGNATURE = EXPECTED_ANALYSIS_SIGNATURE
A15_RAW_SHA256 = (
    "c77466f84b2c1614c8c4cd4b6d8a725de94a79a6011370bca36e1e92a6d1f36b"
)
A15_RAW_SIZE = 21328
A15_HTTP_STATUS = 200
A15_THINKING_TOKENS = 0
A15_OUTPUT_TOKENS = 8206
A15_MAX_OUTPUT = MAX_OUTPUT_TOKENS_FROZEN
A15_FINISH = "end_turn"
A15_STRUCTURED_PARSE = "PASS"
A15_DECODER = "FAIL"
A15_VALIDATOR = "FAIL"
A15_RECORDS = 92
A15_INVALID_LINKS = 7
A15_TOPIC = 13
A15_IDEA = 44
A15_RELATION = 18
A15_EXAMPLE = 5
A15_REFERENCE = 8
A15_UNCERTAINTY = 4
A15_OWNED = EXPECTED_OWNED_SRC_COUNT
A15_WORDS = EXPECTED_WORD_COUNT
A15_DISTINCT_SRC = 238
A15_COVERAGE_PCT = 19.92
A15_COST_DISPLAY = "0.1770520 USD"
A15_LOCAL_INPUT = 21934
A15_PROVIDER_INPUT = 47496
A15_INPUT_RATIO = 2.165405
A15_REQUEST_ID = "req_011CfSReD4LDWrpdvpG9gBZX"

A15_FORENSIC_RELATIVE = (
    "audit/canary/provider_forensics/WIN001/" + A15_SIGNATURE
)
A15_EXECUTION_ARTIFACT = "source_analysis_v2_real_win001_execution.json"
A15_PREFLIGHT_ARTIFACT = "source_analysis_v2_real_win001_preflight.json"
A15_COMPARISON_ARTIFACT = "source_analysis_v2_win001_vs_call_c_comparison.json"
A15_REPORT_NAME = "PHASE_3B77A15_REAL_V2_SMALL_WIN001_SEMANTIC_CANARY_REPORT.md"
A15_LOCK_NAME = "a15_real_v2_win001.lock"

FORENSICS_ARTIFACT = "source_analysis_v2_a15_invalid_link_forensics.json"
SEMANTIC_ARTIFACT = "source_analysis_v2_a15_forensic_semantic_review.json"
COVERAGE_ARTIFACT = "source_analysis_v2_a15_semantic_coverage_analysis.json"
OPTIONS_ARTIFACT = "source_analysis_v2_link_transport_options.json"
DECISION_ARTIFACT = "source_analysis_v2_post_a15_architecture_decision.json"
REPORT_NAME = (
    "PHASE_3B77A16_A15_INVALID_LINK_FORENSICS_OFFLINE_SEMANTIC_REVIEW_REPORT.md"
)

PROTECTED_A15 = (
    f"{A15_FORENSIC_RELATIVE}/provider_raw_response.bin",
    f"{A15_FORENSIC_RELATIVE}/provider_http_envelope.json",
    f"audit/{A15_EXECUTION_ARTIFACT}",
    f"audit/{A15_PREFLIGHT_ARTIFACT}",
    f"audit/{A15_COMPARISON_ARTIFACT}",
    f"audit/{A15_REPORT_NAME}",
    f"audit/canary/{A15_LOCK_NAME}",
)

NEXT_PHASE = "3B.7.7A.17_OFFLINE_TRANSPORT_PROMPT_REDESIGN_IMPLEMENTATION"
NEXT_ACTION = "HUMAN REVIEW"
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION

SELECTED_LINK_ARCHITECTURE = "LOCAL_SYMBOLIC_HANDLES"
SELECTED_ARCHITECTURE_STATUS = "SELECTED_NOT_IMPLEMENTED"
NEW_PROMPT_VERSION = None
NEW_TRANSPORT_VERSION = None
SCHEMA_CHANGED = False
ADAPTIVE_LOW_JUSTIFIED = False

SEMANTIC_CONTENT_CLASSIFICATION = (
    "SEMANTIC_CONTENT_ACCEPTABLE_LINK_ENCODING_DEFECT"
)
LINK_FAILURE_PATTERN = "SEMANTIC_LINK_TARGET_KIND_VIOLATION"
GLOBAL_INDEX_HYPOTHESIS = (
    "CONFIRMED_NUMBERING_SYSTEM — valid RELATION/EXAMPLE/IDEA links use "
    "global 0-based transport indexes"
)
PER_KIND_ORDINAL_HYPOTHESIS = (
    "REJECTED_FOR_INVALID_LINKS — invalid l values are TOPIC global indexes, "
    "not IDEA-subset ordinals"
)
PROMPT_AMBIGUITY_REMAINING = True

__all__ = [
    "A13_REQUEST_IDENTITY",
    "A15_COMPARISON_ARTIFACT",
    "A15_COST_DISPLAY",
    "A15_COVERAGE_PCT",
    "A15_DECODER",
    "A15_DISTINCT_SRC",
    "A15_EXAMPLE",
    "A15_EXECUTION_ARTIFACT",
    "A15_FINISH",
    "A15_FORENSIC_RELATIVE",
    "A15_HTTP_STATUS",
    "A15_IDEA",
    "A15_INPUT_RATIO",
    "A15_INVALID_LINKS",
    "A15_LOCAL_INPUT",
    "A15_LOCK_NAME",
    "A15_MAX_OUTPUT",
    "A15_OUTPUT_TOKENS",
    "A15_OWNED",
    "A15_PHASE",
    "A15_PREFLIGHT_ARTIFACT",
    "A15_PROVIDER_INPUT",
    "A15_RAW_SHA256",
    "A15_RAW_SIZE",
    "A15_RECORDS",
    "A15_REFERENCE",
    "A15_RELATION",
    "A15_REPORT_NAME",
    "A15_REQUEST_ID",
    "A15_SIGNATURE",
    "A15_STRUCTURED_PARSE",
    "A15_THINKING_TOKENS",
    "A15_TOPIC",
    "A15_UNCERTAINTY",
    "A15_VALIDATOR",
    "A15_WORDS",
    "ADAPTIVE_LOW_JUSTIFIED",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER_VERSION",
    "CANDIDATE_WINDOW_ANALYSIS_PROMPT_VERSION",
    "COVERAGE_ARTIFACT",
    "DECISION_ARTIFACT",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_CLEAN_SHA",
    "EXPECTED_FIRST_OWNED_SRC",
    "EXPECTED_LAST_OWNED_SRC",
    "EXPECTED_OWNED_SRC_COUNT",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "EXPECTED_WINDOW_INPUT_HASH",
    "EXPECTED_WORD_COUNT",
    "FORENSICS_ARTIFACT",
    "FUTURE_REAL_CALL_AUTHORIZED",
    "GLOBAL_INDEX_HYPOTHESIS",
    "LINK_FAILURE_PATTERN",
    "MAX_OUTPUT_TOKENS_FROZEN",
    "MODE",
    "NEW_PROMPT_VERSION",
    "NEW_TRANSPORT_VERSION",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "OPTIONS_ARTIFACT",
    "PER_KIND_ORDINAL_HYPOTHESIS",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_AMBIGUITY_REMAINING",
    "PROTECTED_A15",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "REPORT_NAME",
    "SCHEMA_CHANGED",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE_STATUS",
    "SELECTED_LINK_ARCHITECTURE",
    "SEMANTIC_ARTIFACT",
    "SEMANTIC_CONTENT_CLASSIFICATION",
    "SEMANTIC_REVIEW_STATUS",
    "SEMANTIC_TRANSPORT_VERSION_V2",
    "TARGET_JSON_LOCAL_TOKENS",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V121",
    "WINDOW_ID",
    "WIN001_RETRY_AUTHORIZED",
]
