"""Constantes 3B.7.7A.15 — canary sémantique V2 WIN001 réel. 1 appel max."""

from __future__ import annotations

from app.source_analysis.window_models import (
    WINDOW_CONNECT_TIMEOUT_SECONDS,
    WINDOW_READ_TIMEOUT_SECONDS,
)
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    CANDIDATE_WINDOW_ANALYSIS_PROMPT_VERSION,
    CLEAN_SHA,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
    SEMANTIC_TRANSPORT_VERSION_V2,
    WINDOW_ANALYSIS_PROMPT_VERSION_V121,
)
from app.source_analysis_output_ceiling_review.constants import (
    CALL1_SIGNATURE,
    CALL2_SIGNATURE,
    CALL_C_COST,
    CALL_C_FINISH,
    CALL_C_LOCAL,
    CALL_C_OUTPUT,
    CALL_C_PROVIDER_INPUT,
    CALL_C_THINKING_TOKENS,
    SMALL_SIGNATURE,
)
from app.source_analysis_small_window_hierarchy.constants import (
    CANDIDATE_CONTEXT_POLICY,
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
)
from app.source_analysis_small_window_readiness.constants import A7_WIN001_INPUT_HASH
from app.source_analysis_thinking_contract.constants import (
    AUTHORIZATION_SCOPE_SMALL_V21_V2_WIN001_ONLY,
    SELECTED_CONTRACT,
    SELECTED_EFFORT,
    SELECTED_THINKING_MODE,
)
from app.source_analysis_v2_grammar_canary.constants import (
    CANARY_SUBDIR,
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)
from app.source_analysis_v2_link_semantics.constants import A13_REQUEST_IDENTITY

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.15"
MODE = "REAL_V2_SMALL_WIN001_SEMANTIC_CANARY"

AUTHORIZATION_SCOPE = AUTHORIZATION_SCOPE_SMALL_V21_V2_WIN001_ONLY
WINDOW_ID = "WIN001"
FORBIDDEN_WINDOW_IDS = (
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
)

PROVIDER = "anthropic"
MODEL = "claude-sonnet-5"
THINKING_CONTRACT = SELECTED_CONTRACT
THINKING_MODE = SELECTED_THINKING_MODE
EFFORT = SELECTED_EFFORT

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False

MAX_OUTPUT_TOKENS = MAX_OUTPUT_TOKENS_FROZEN
CONNECT_TIMEOUT_SECONDS = WINDOW_CONNECT_TIMEOUT_SECONDS
READ_TIMEOUT_SECONDS = WINDOW_READ_TIMEOUT_SECONDS
HISTORICAL_READ_TIMEOUT_SECONDS = 7200.0

EXPECTED_ANALYSIS_SIGNATURE = (
    "a5cf967871c270a588da0a9f7510741f77c7bdacd84af9815aad7291c4b88012"
)
EXPECTED_WINDOW_INPUT_HASH = A7_WIN001_INPUT_HASH
EXPECTED_FIRST_OWNED_SRC = "SRC000001"
EXPECTED_LAST_OWNED_SRC = "SRC001201"
EXPECTED_OWNED_SRC_COUNT = 1195
EXPECTED_WORD_COUNT = 5447
EXPECTED_CLEAN_SHA = CLEAN_SHA
EXPECTED_CONTEXT_COUNT = 0
EXPECTED_CONTEXT_POLICY = CANDIDATE_CONTEXT_POLICY
A13_SYNTHETIC_IDENTITY = A13_REQUEST_IDENTITY

LOCK_NAME = "a15_real_v2_win001.lock"
CANDIDATE_WINDOWS_SUBDIR = "v2_windows"
CANDIDATE_CACHE_SUBDIR = "v2_cache"

PREFLIGHT_ARTIFACT = "source_analysis_v2_real_win001_preflight.json"
EXECUTION_ARTIFACT = "source_analysis_v2_real_win001_execution.json"
REVIEW_ARTIFACT = "source_analysis_v2_real_win001_semantic_review.json"
COMPARISON_ARTIFACT = "source_analysis_v2_win001_vs_call_c_comparison.json"
REPORT_NAME = "PHASE_3B77A15_REAL_V2_SMALL_WIN001_SEMANTIC_CANARY_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION
PROMPT_VERSION = CANDIDATE_WINDOW_ANALYSIS_PROMPT_VERSION
TRANSPORT_VERSION = SEMANTIC_TRANSPORT_VERSION_V2

PROTECTED_HISTORICAL = (
    "audit/PHASE_3B77A13_V2_TINY_GRAMMAR_THINKING_CONFIG_CANARY_REPORT.md",
    "audit/source_analysis_v2_grammar_thinking_canary_execution.json",
    "audit/source_analysis_v2_grammar_thinking_canary_payload.json",
    "audit/PHASE_3B77A14_V2_LINK_SEMANTICS_HARDENING_SEMANTIC_WIN001_READINESS_REPORT.md",
    "audit/source_analysis_v2_future_win001_identity.json",
    "audit/PHASE_3B77A9_REAL_SMALL_WIN001_CANARY_REPORT.md",
    "audit/source_analysis_real_small_win001_execution.json",
)

__all__ = [
    "A13_SYNTHETIC_IDENTITY",
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "CANDIDATE_CACHE_SUBDIR",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER",
    "CANDIDATE_WINDOWS_SUBDIR",
    "CALL1_SIGNATURE",
    "CALL2_SIGNATURE",
    "CALL_C_COST",
    "CALL_C_FINISH",
    "CALL_C_LOCAL",
    "CALL_C_OUTPUT",
    "CALL_C_PROVIDER_INPUT",
    "CALL_C_THINKING_TOKENS",
    "CANARY_SUBDIR",
    "COMPARISON_ARTIFACT",
    "CONNECT_TIMEOUT_SECONDS",
    "EFFORT",
    "EXECUTION_ARTIFACT",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_ANALYSIS_SIGNATURE",
    "EXPECTED_CLEAN_SHA",
    "EXPECTED_CONTEXT_COUNT",
    "EXPECTED_CONTEXT_POLICY",
    "EXPECTED_FIRST_OWNED_SRC",
    "EXPECTED_LAST_OWNED_SRC",
    "EXPECTED_OWNED_SRC_COUNT",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "EXPECTED_WINDOW_INPUT_HASH",
    "EXPECTED_WORD_COUNT",
    "FORBIDDEN_WINDOW_IDS",
    "HISTORICAL_READ_TIMEOUT_SECONDS",
    "LOCK_NAME",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MAX_OUTPUT_TOKENS",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "PHASE",
    "PHASE_3B_STATUS",
    "PREFLIGHT_ARTIFACT",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "READ_TIMEOUT_SECONDS",
    "REPORT_NAME",
    "REVIEW_ARTIFACT",
    "SCHEMA_VERSION",
    "SMALL_SIGNATURE",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V121",
    "WINDOW_ID",
]
