"""Rapport markdown 3B.7.7A.17."""

from __future__ import annotations

from typing import Any, Mapping


def render_report(
    *,
    header: Mapping[str, Any],
    design: Mapping[str, Any],
    schema: Mapping[str, Any],
    resolution: Mapping[str, Any],
    fakeai: Mapping[str, Any],
    preflight: Mapping[str, Any],
    canary: Mapping[str, Any],
    worst: Mapping[str, Any],
    replay: Mapping[str, Any],
    identity: Mapping[str, Any],
) -> str:
    h = header
    windows = preflight.get("windows") or []
    window_lines = []
    for row in windows:
        window_lines.append(
            f"- {row['window_id']}: {row['src_range']} | "
            f"{row['owned_src_count']} SRC | {row['word_count']} words | "
            f"{row['local_request_estimate']} tokens | {row['hard_limit_status']}"
        )
    lines = [
        "# PHASE 3B.7.7A.17 — LOCAL SYMBOLIC HANDLES TRANSPORT REDESIGN",
        "",
        "## Result",
        "",
        str(h.get("result")),
        "",
        f"REAL PROVIDER CALLS = {h.get('real_provider_calls')}",
        "",
        f"REAL WINDOW CALLS = {h.get('real_window_calls')}",
        "",
        f"BASELINE = {h.get('baseline')}",
        "",
        f"A.15 SEMANTIC CONTENT = {h.get('a15_semantic_content')}",
        "",
        f"SELECTED ARCHITECTURE = {h.get('selected_architecture')}",
        "",
        f"PROMPT = {h.get('prompt')}",
        "",
        f"TRANSPORT = {h.get('transport')}",
        "",
        f"HANDLE OWNER KINDS = {h.get('handle_owner_kinds')}",
        "",
        f"LINK HANDLE KINDS = {h.get('link_handle_kinds')}",
        "",
        f"HANDLE INDEX BASE = {h.get('handle_index_base')}",
        "",
        f"GLOBAL NUMERIC LINK INDEXES = {h.get('global_numeric_link_indexes')}",
        "",
        f"FORWARD REFERENCES = {h.get('forward_references')}",
        "",
        f"SCHEMA CHANGED = {h.get('schema_changed')}",
        "",
        f"RAW SCHEMA BYTES = {h.get('raw_schema_bytes')}",
        "",
        f"ANTHROPIC-ADAPTED SCHEMA BYTES = {h.get('adapted_schema_bytes')}",
        "",
        f"SERVER GRAMMAR VERIFIED = {h.get('server_grammar_verified')}",
        "",
        f"THINKING = {h.get('thinking')}",
        "",
        f"EFFORT = {h.get('effort')}",
        "",
        f"MAX OUTPUT = {h.get('max_output')}",
        "",
        f"SYNTHETIC WORST CASE = {h.get('synthetic_worst_case')}",
        "",
        f"FUTURE WIN001 INPUT ESTIMATE = {h.get('future_win001_input_estimate')}",
        "",
        f"FUTURE WIN001 SIGNATURE = {h.get('future_win001_signature')}",
        "",
        f"FUTURE WIN001 CACHE = {h.get('future_win001_cache')}",
        "",
        f"FAKEAI LOCAL = {h.get('fakeai_local')}",
        "",
        f"7-WINDOW FAKEAI = {h.get('seven_window_fakeai')}",
        "",
        f"DIRECT CONSOLIDATION = {h.get('direct_consolidation')}",
        "",
        f"HIERARCHICAL CONSOLIDATION = {h.get('hierarchical_consolidation')}",
        "",
        f"CANONICAL VALIDATION = {h.get('canonical_validation')}",
        "",
        f"NO-DROP = {h.get('no_drop')}",
        "",
        f"SRC TRACEABILITY = {h.get('src_traceability')}",
        "",
        f"GRAMMAR CANARY READY = {h.get('grammar_canary_ready')}",
        "",
        f"REAL CALL AUTHORIZED = {h.get('real_call_authorized')}",
        "",
        f"PRODUCTION DEFAULT = {h.get('production_default')}",
        "",
        f"SOURCE MAP = {h.get('source_map')}",
        "",
        f"PHASE 3B = {h.get('phase_3b')}",
        "",
        f"TESTS = {h.get('tests')}",
        "",
        f"NEXT ACTION = {h.get('next_action')}",
        "",
        "## 1. Design",
        "",
        f"Selected wire form: {design.get('wire_representation', {}).get('selected')}.",
        "",
        "h is the explicit owner handle. l is a string-handle array.",
        "Handles were not placed in m: m keeps kind-specific metadata.",
        "I37-style aliases of global indexes were rejected.",
        "",
        f"Owner kinds: {design.get('owner_kinds')}.",
        f"IDEA links T handles. RELATION and EXAMPLE link I handles.",
        f"Forward references: {design.get('forward_references')}.",
        f"Gap-free numbering: {design.get('gap_free_numbering')}.",
        "",
        "## 2. Schema",
        "",
        f"Raw bytes: {schema.get('raw_bytes')}.",
        f"Anthropic-adapted bytes: {schema.get('adapted_bytes')}.",
        "Server grammar verified: NO.",
        "A.13 remains proof only for semantic-transport-v2. It did not verify v3.",
        "",
        "## 3. Resolution",
        "",
        "Python builds a handle registry after the full parse, rejects",
        "duplicates / unknown / wrong-kind / self-relations / malformed",
        "labels, then maps handles to internal indexes for reconstruction.",
        "No semantic guessing. No fuzzy repair. Forward references allowed.",
        "",
        f"A.15 V2 replay decoder = {resolution.get('a15_v2_replay', {}).get('decoder')}.",
        "A.15 was not reinterpreted as symbolic. It remains invalid.",
        f"Synthetic diagnostic (not repaired A.15) resolves RELATION/EXAMPLE to IDEA: "
        f"{resolution.get('a15_synthetic_diagnostic', {}).get('relation_and_example_resolve_to_ideas')}.",
        "",
        "## 4. Prompt",
        "",
        "window-analysis-1.3 assigns T1… / I1… labels and forbids arithmetic.",
        "RELATION and EXAMPLE may NEVER target T handles.",
        "IDEA may NEVER target I handles.",
        "The compact example contains 2 TOPIC, 3 IDEA, 1 RELATION, 1 EXAMPLE.",
        "",
        "## 5. Output budget",
        "",
        f"V2 worst-case tokens: {worst.get('v2', {}).get('local_estimated_tokens')}.",
        f"V3 worst-case tokens: {worst.get('local_tokens')}.",
        f"Token delta: {worst.get('token_delta')} ({worst.get('percentage_overhead')}%).",
        f"Byte delta: {worst.get('byte_delta')}.",
        f"Within 12000: {worst.get('within_json_target')}.",
        "",
        "## 6. Future windows",
        "",
        *window_lines,
        "",
        f"All seven ≤ 35000: {preflight.get('all_within_35000')}.",
        f"Future WIN001 signature: {identity.get('analysis_signature')}.",
        f"Differs from A.15: {identity.get('differs_from_a15')}.",
        f"Cache: {identity.get('cache')}.",
        f"Forensic collisions: {identity.get('cache_collisions')}.",
        "",
        "## 7. FakeAI",
        "",
        f"Local: {fakeai.get('local')}.",
        f"Seven-window: {fakeai.get('seven_window')}.",
        f"Direct: {fakeai.get('direct', {}).get('status')}.",
        f"Hierarchical: {fakeai.get('hierarchical', {}).get('status')}.",
        f"Deferred recovered (direct): {fakeai.get('direct', {}).get('deferred_recovered')}.",
        f"Canonical IDs remain TOP… / IDEA…: {fakeai.get('canonical_ids_are_top_idea')}.",
        "",
        "## 8. Grammar canary readiness",
        "",
        f"Prepared: {canary.get('prepared')}. Executed: {canary.get('executed')}.",
        f"Materially different from V2: {canary.get('materially_different_from_v2')}.",
        "Do not execute A.18 from this phase.",
        "",
        "## 9. Required questions",
        "",
        "Were any provider calls made? NO.",
        "",
        "Was WIN001 retried? NO.",
        "",
        "What exact symbolic representation was selected? "
        "h owner handle + l string-handle array (kind-local T1… / I1…).",
        "",
        "Why was it selected over putting handles in m? "
        "m keeps metadata semantics; ownership is a new explicit wire concept.",
        "",
        "Did transport version change? YES — semantic-transport-v3.",
        "",
        "Did prompt version change? YES — window-analysis-1.3.",
        "",
        "Which record kinds own handles? TOPIC (Tn), IDEA (In).",
        "",
        "Which record kinds link to T handles? IDEA.",
        "",
        "Which record kinds link to I handles? RELATION, EXAMPLE.",
        "",
        "Can symbolic handles point forward? YES.",
        "",
        "Must numbering be gap-free? NO. Uniqueness and type matter more.",
        "",
        "Are duplicate handles rejected? YES.",
        "",
        "Are unknown handles rejected? YES.",
        "",
        "Are wrong-kind handles rejected? YES.",
        "",
        "Are self-relations rejected? YES.",
        "",
        "Can insertion/reordering change semantic targets? "
        "NO, when handles remain unchanged.",
        "",
        "Does Python only resolve structure rather than decide semantics? YES.",
        "",
        "Is canonical SourceMap unchanged? YES.",
        "",
        f"Did schema size remain small? YES ({h.get('adapted_schema_bytes')} adapted bytes).",
        "",
        f"What are raw/adapted schema sizes? {h.get('raw_schema_bytes')} / {h.get('adapted_schema_bytes')}.",
        "",
        "Does the new schema require a new provider grammar canary? YES.",
        "",
        "Is A.13 still proof for V2 only? YES.",
        "",
        "Is thinking still disabled? YES.",
        "",
        "Why was adaptive-low not selected? "
        "A.16 found semantic content acceptable; the defect was link encoding.",
        "",
        f"Does synthetic worst-case remain <=12000? {h.get('worst_within_12000')}.",
        "",
        f"Are all seven future requests <=35000? {h.get('all_windows_within_35000')}.",
        "",
        f"Does future WIN001 signature differ from A.15? {h.get('a15_signature_isolated')}.",
        "",
        f"Does future WIN001 cache miss? {h.get('future_win001_cache')}.",
        "",
        f"Does forensic identity differ? {h.get('forensic_isolated')}.",
        "",
        f"Did FakeAI local pass? {h.get('fakeai_local')}.",
        "",
        f"Did seven-window FakeAI pass? {h.get('seven_window_fakeai')}.",
        "",
        f"Did direct consolidation pass? {h.get('direct_consolidation')}.",
        "",
        f"Did hierarchical consolidation pass? {h.get('hierarchical_consolidation')}.",
        "",
        f"Did deferred-field recovery pass? {fakeai.get('direct', {}).get('deferred_recovered')}.",
        "",
        f"Did canonical validation pass? {h.get('canonical_validation')}.",
        "",
        f"Did NO-DROP pass? {h.get('no_drop')}.",
        "",
        f"Did SRC traceability pass? {h.get('src_traceability')}.",
        "",
        "Was production changed? NO.",
        "",
        "Was source_map published? NO.",
        "",
        f"Did full suite pass? {h.get('tests')}.",
        "",
        f"What is the exact recommended next phase? {h.get('next_phase')}.",
        "",
        "## 10. Isolation",
        "",
        f"A.15 V2 decoder still FAIL: {replay.get('v2_decoder')}.",
        f"Historical evidence unchanged: {h.get('historical_hashes_unchanged')}.",
        "Production planner remains window-planner-v2.0.",
        "Candidate planner remains window-planner-v2.1-small.",
        "Analyzer is not wired to v3.",
        "",
        "## 11. Next phase",
        "",
        "If A.17 PASS and the new schema is materially changed, the next",
        "separately authorized phase is 3B.7.7A.18 — SYMBOLIC-HANDLE TINY",
        "GRAMMAR CANARY. One tiny synthetic Anthropic call maximum.",
        "No pastoral transcript. No WIN001. thinking disabled.",
        "max_attempts=1. no retry. mandatory STOP.",
        "",
        "Do NOT execute A.18 now.",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
    ]
    return "\n".join(lines) + "\n"


__all__ = ["render_report"]
