"""
Phase 4B.2.3 — Independent chapter semantic gate.

Offline architecture + forensic benchmark. Zero provider calls.
"""

from __future__ import annotations

from app.book_generation.constants import (
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    MODEL as GENERATOR_MODEL,
    PROVIDER as GENERATOR_PROVIDER,
    VALIDATION_PROJECT_NAME,
)
from app.book_generator_canary_4b2.constants import (
    PHASE_4B1_CH016_EVIDENCE_SHA256,
    PHASE_4B1_TRANSCRIPT_CONTENT_SHA256,
)
from app.book_generator_canary_4b22.constants import (
    EXPECTED_CACHE_SIGNATURE_V101,
    FROZEN_PROMPT_V101_SHA256,
    HISTORICAL_CANDIDATE_CANONICAL_SHA256 as HISTORICAL_4B2_CANDIDATE_SHA256,
    HISTORICAL_CANDIDATE_FILE_SHA256 as HISTORICAL_4B2_CANDIDATE_FILE_SHA256,
    HISTORICAL_RAW_SHA256 as HISTORICAL_4B2_RAW_SHA256,
)
from app.book_generator_forensics_4b21.constants import (
    HISTORICAL_CANDIDATE_SHA256 as HISTORICAL_4B2_CANDIDATE_CANONICAL,
)

PHASE = "4B.2.3"
PHASE_NAME = "INDEPENDENT_SEMANTIC_GATE_ARCHITECTURE_AND_OFFLINE_BENCHMARK"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

TARGET_CHAPTER_ID = "CH016"
TARGET_SECTION_ID = "SEC063"

HISTORICAL_4B2_STATUS = "FAIL"
HISTORICAL_4B21_STATUS = "PASS"
HISTORICAL_4B22_STATUS = "PARTIAL"

REAL_PROVIDER_CALLS = 0
PUBLICATION_AUTHORIZED = False

GENERATOR_PROVIDER_NAME = GENERATOR_PROVIDER
GENERATOR_MODEL_NAME = GENERATOR_MODEL
GENERATOR_PROMPT_VERSION = BOOK_GENERATOR_PROMPT_VERSION
DETERMINISTIC_VALIDATOR_VERSION = BOOK_GENERATOR_VALIDATOR_VERSION
GENERATOR_TRANSPORT_VERSION = BOOK_GENERATION_TRANSPORT_VERSION

assert GENERATOR_PROVIDER_NAME == "anthropic"
assert GENERATOR_MODEL_NAME == "claude-sonnet-5"
assert GENERATOR_PROMPT_VERSION == "book-generator-1.0.1"
assert DETERMINISTIC_VALIDATOR_VERSION == "book-generation-validator-1.0.1"
assert GENERATOR_TRANSPORT_VERSION == "book-generation-transport-1.0"

SEMANTIC_GATE_PROVIDER = "openai"
SEMANTIC_GATE_MODEL = "gpt-5.6-terra"
SEMANTIC_GATE_STAGE = "book_validation"
SEMANTIC_VALIDATOR_PROMPT_VERSION = "book-semantic-validator-1.0"
SEMANTIC_VALIDATION_TRANSPORT_VERSION = "book-semantic-validation-transport-1.0"
SEMANTIC_GATE_VALIDATOR_VERSION = "book-semantic-gate-validator-1.0"
SEMANTIC_GATE_SETTINGS_VERSION = "book-semantic-gate-settings-1.0"

# Terra thinking is unverified. Do not copy Sonnet disabled/adaptive settings.
THINKING_MODE = "provider_default"
THINKING_EFFORT = None
TEMPERATURE_POLICY = "omit"
# Structured output: existing OpenAI engine uses json_object, not json_schema.
STRUCTURED_OUTPUT_MODE = "json_object"

GRANULARITY = "CLAIM_LEVEL_AUDIT_WITH_PARAGRAPH_ANCHORING"
EVIDENCE_SCOPE = "DECLARED_FIRST_PLUS_BOUNDED_SECTION_EVIDENCE"

CLASS_SUPPORTED = "SUPPORTED"
CLASS_QUESTIONABLE = "QUESTIONABLE"
CLASS_UNSUPPORTED = "UNSUPPORTED"
CLASS_NON_SUBSTANTIVE = "NON_SUBSTANTIVE"
CLASSIFICATIONS = (
    CLASS_SUPPORTED,
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    CLASS_NON_SUBSTANTIVE,
)

VERDICT_PASS = "PASS"
VERDICT_REVIEW = "REVIEW"
VERDICT_FAIL = "FAIL"

EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_CLEAN_TRANSCRIPT = PHASE_4B1_TRANSCRIPT_CONTENT_SHA256
EXPECTED_EVIDENCE_SHA256 = PHASE_4B1_CH016_EVIDENCE_SHA256
EXPECTED_GENERATOR_PROMPT_SHA256 = FROZEN_PROMPT_V101_SHA256
EXPECTED_CACHE_SIGNATURE_V101 = EXPECTED_CACHE_SIGNATURE_V101

assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B2_CANDIDATE_CANONICAL == HISTORICAL_4B2_CANDIDATE_SHA256
assert HISTORICAL_4B2_CANDIDATE_SHA256 == (
    "51635cedf7fee34b34fd80466c2361968494e2e98c15d861682401bddd2aaad5"
)
assert HISTORICAL_4B2_CANDIDATE_FILE_SHA256 == (
    "6b1a1f2308a88576d38211c32ec569d9a94441cc27936fd0d4c0f3cb7b3d8e76"
)
assert HISTORICAL_4B2_RAW_SHA256 == (
    "3a291c879d852daec8a00d0bf9f18e3e1c902643658f9e6f3aaa5066206e9749"
)

HISTORICAL_4B22_CANDIDATE_CANONICAL_SHA256 = (
    "e218bea95aaa46f45de66d3532da28fc05807eb9a436bf2e22fe6e9daaa8147c"
)
# 4B.2.2 report recorded file SHA-256 4c0bd8aaa7... Content identity is canonical.
HISTORICAL_4B22_CANDIDATE_FILE_SHA256_REPORTED = (
    "4c0bd8aaa7b8ed760ea48b34877581d8822272daed6b18388386f8fa94aa87e9"
)

PREVIOUS_19_CHAPTER_COST_USD = 0.668268
PREVIOUS_INPUT_TOKENS_PER_CALL = 8586
PREVIOUS_OUTPUT_TOKENS_PER_CALL = 1500

DEFAULT_MAX_OUTPUT_TOKENS = 4096
CONSERVATIVE_MAX_OUTPUT_TOKENS = 8192
HARD_MAX_OUTPUT_TOKENS = 16384

AUDIT_DIRNAME = "book_semantic_gate_4b23"
AUDIT_ARCHITECTURE = "book_semantic_gate_4b23_architecture.json"
AUDIT_EVIDENCE = "book_semantic_gate_4b23_evidence_contract.json"
AUDIT_CLAIMS = "book_semantic_gate_4b23_claim_contract.json"
AUDIT_REASONS = "book_semantic_gate_4b23_reason_codes.json"
AUDIT_PROMPT = "book_semantic_gate_4b23_prompt_identity.json"
AUDIT_TRANSPORT = "book_semantic_gate_4b23_transport_identity.json"
AUDIT_SCHEMA = "book_semantic_gate_4b23_schema_identity.json"
AUDIT_BENCHMARK = "book_semantic_gate_4b23_historical_benchmark.json"
AUDIT_MANIFEST = "book_semantic_gate_4b23_benchmark_manifest.json"
AUDIT_ACCEPTANCE = "book_semantic_gate_4b23_acceptance_policy.json"
AUDIT_CACHE = "book_semantic_gate_4b23_cache_contract.json"
AUDIT_BUDGET = "book_semantic_gate_4b23_budget.json"
AUDIT_COST = "book_semantic_gate_4b23_cost_estimate.json"
AUDIT_SUFFICIENCY = "book_generator_101_sufficiency_assessment.json"
AUDIT_READINESS = "book_semantic_gate_post_4b23_readiness.json"
REPORT_NAME = (
    "PHASE_4B23_INDEPENDENT_SEMANTIC_GATE_ARCHITECTURE_AND_OFFLINE_BENCHMARK_REPORT.md"
)

READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False
NEXT_ACTION = "HUMAN REVIEW"

assert REAL_PROVIDER_CALLS == 0
assert PUBLICATION_AUTHORIZED is False
assert READY_FOR_FULL_REAL_BOOK_GENERATION is False
assert SEMANTIC_VALIDATOR_PROMPT_VERSION == "book-semantic-validator-1.0"
assert SEMANTIC_VALIDATION_TRANSPORT_VERSION == "book-semantic-validation-transport-1.0"
assert SEMANTIC_GATE_PROVIDER == "openai"
assert SEMANTIC_GATE_MODEL == "gpt-5.6-terra"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
