"""Constantes 3B.7.7A.20 — forensics A.19 offline. 0 provider."""

from __future__ import annotations

from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
    SELECTED_ARCHITECTURE,
    SEMANTIC_TRANSPORT_VERSION_V3,
    WINDOW_ANALYSIS_PROMPT_VERSION_V13,
)
from app.source_analysis_local_v3.schema import semantic_transport_v3_fingerprint
from app.source_analysis_v3_real_win001.constants import (
    EXPECTED_ANALYSIS_SIGNATURE,
    EXPECTED_FORENSIC_IDENTITY,
    EXPECTED_LOCAL_INPUT_ESTIMATE,
    EXPECTED_OWNED_SRC_COUNT,
    EXPECTED_SCHEMA_HASH,
    EXPECTED_WORD_COUNT,
    PROTECTED_HISTORICAL,
    SYNTHETIC_WORST_CASE_LOCAL_TOKENS,
    WINDOW_ID,
)
from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.20"
MODE = "OFFLINE_A19_FULL_LATENT_VIOLATION_FORENSICS_AND_SRC_CONTRACT_HARDENING"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
WIN001_RETRY_AUTHORIZED = False
FUTURE_REAL_CALL_AUTHORIZED = False
A19_STATUS_UNCHANGED = "FAIL"

WINDOW_ANALYSIS_PROMPT_VERSION_V131 = "window-analysis-1.3.1"
SEMANTIC_REVIEW_STATUS = "FORENSIC_SEMANTIC_REVIEW_OF_INVALID_V3_TRANSPORT"
EXAMPLE_POLICY = "B_OPTIONAL_ASSOCIATION_CANONICAL"
EXAMPLE_POLICY_LABEL = (
    "EXAMPLE may have l=[] if no semantically appropriate extracted IDEA exists. "
    "Canonical supports_idea_refs is optional. Source grounding remains via s[]."
)

A19_RAW_SHA256 = (
    "23d0a29ec6bd09ce3f2c74215d17942fd85c40581f62e67bdce5b5899bace15f"
)
A19_RAW_SIZE = 28161
A19_HTTP = 200
A19_FINISH = "end_turn"
A19_THINKING = "disabled"
A19_THINKING_TOKENS = 0
A19_INPUT_TOKENS = 48559
A19_OUTPUT_TOKENS = 10897
A19_MAX_OUTPUT = MAX_OUTPUT_TOKENS_FROZEN
A19_STRUCTURED_PARSE = "PASS"
A19_CAPACITY_SIGNAL = "absent"
A19_RECORDS = 106
A19_FIRST_DECODER_FAILURE = "records[50].s[6] = SRc000609"
A19_MALFORMED_SRC = "SRc000609"
A19_HYPOTHETICAL_INTENDED_SRC = "SRC000609"
A19_SIGNATURE = EXPECTED_ANALYSIS_SIGNATURE
A19_FORENSIC_IDENTITY = EXPECTED_FORENSIC_IDENTITY
A19_DISTINCT_SRC_REPORTED = 325
A19_COVERAGE_PCT_REPORTED = 27.11
A19_OWNED = EXPECTED_OWNED_SRC_COUNT
A19_WORDS = EXPECTED_WORD_COUNT
A19_LOCAL_INPUT = EXPECTED_LOCAL_INPUT_ESTIMATE

A19_FORENSIC_RELATIVE = (
    "audit/canary/v3_real_win001/provider_forensics/WIN001/" + A19_SIGNATURE
)
A19_LOCK_RELATIVE = "audit/canary/v3_real_win001/a19_real_v3_win001.lock"
A19_EXECUTION_ARTIFACT = "source_analysis_v3_real_win001_execution.json"
A19_PREFLIGHT_ARTIFACT = "source_analysis_v3_real_win001_preflight.json"
A19_HANDLE_ARTIFACT = "source_analysis_v3_real_win001_handle_analysis.json"
A19_REPORT_NAME = (
    "PHASE_3B77A19_REAL_V3_SMALL_WIN001_SYMBOLIC_HANDLE_CANARY_REPORT.md"
)

PROTECTED_A19 = (
    f"{A19_FORENSIC_RELATIVE}/provider_raw_response.bin",
    f"{A19_FORENSIC_RELATIVE}/provider_http_envelope.json",
    A19_LOCK_RELATIVE,
    f"audit/{A19_EXECUTION_ARTIFACT}",
    f"audit/{A19_PREFLIGHT_ARTIFACT}",
    f"audit/{A19_HANDLE_ARTIFACT}",
    f"audit/{A19_REPORT_NAME}",
)

VIOLATION_ARTIFACT = "source_analysis_v3_a19_exhaustive_violation_inventory.json"
SRC_CONTRACT_ARTIFACT = "source_analysis_v3_src_reference_contract_analysis.json"
EXAMPLE_POLICY_ARTIFACT = "source_analysis_v3_example_link_policy_analysis.json"
SEMANTIC_ARTIFACT = "source_analysis_v3_a19_forensic_semantic_review.json"
COVERAGE_ARTIFACT = "source_analysis_v3_a19_semantic_coverage_analysis.json"
FUTURE_RETRY_ARTIFACT = "source_analysis_v3_future_win001_retry_readiness.json"
REPORT_NAME = (
    "PHASE_3B77A20_A19_FULL_LATENT_VIOLATION_FORENSICS_SRC_HARDENING_REPORT.md"
)

NEXT_ACTION = "HUMAN REVIEW"
NEXT_PHASE = "3B.7.7A.21_REAL_V3_SMALL_WIN001_HARDENED_RETRY"
NEXT_PHASE_LABEL = (
    "3B.7.7A.21 — REAL V3 SMALL WIN001 HARDENED RETRY "
    "(ONE provider call maximum, only after separate human authorization)"
)
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION
SCHEMA_CHANGED = False
SERVER_GRAMMAR_STATUS = "A18_PROOF_APPLICABLE"
V3_HANDLE_ARCHITECTURE = "V3_HANDLES_CONFIRMED_EFFECTIVE"
SRC_FAILURE_CLASSIFICATION = "ISOLATED_PROVIDER_COPY_TYPO"

assert EXPECTED_SCHEMA_HASH == semantic_transport_v3_fingerprint()
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert A19_MAX_OUTPUT == 32000
assert SYNTHETIC_WORST_CASE_LOCAL_TOKENS == 12185

__all__ = [
    "A19_CAPACITY_SIGNAL",
    "A19_COVERAGE_PCT_REPORTED",
    "A19_DISTINCT_SRC_REPORTED",
    "A19_EXECUTION_ARTIFACT",
    "A19_FINISH",
    "A19_FIRST_DECODER_FAILURE",
    "A19_FORENSIC_IDENTITY",
    "A19_FORENSIC_RELATIVE",
    "A19_HANDLE_ARTIFACT",
    "A19_HTTP",
    "A19_HYPOTHETICAL_INTENDED_SRC",
    "A19_INPUT_TOKENS",
    "A19_LOCAL_INPUT",
    "A19_LOCK_RELATIVE",
    "A19_MALFORMED_SRC",
    "A19_MAX_OUTPUT",
    "A19_OUTPUT_TOKENS",
    "A19_OWNED",
    "A19_PREFLIGHT_ARTIFACT",
    "A19_RAW_SHA256",
    "A19_RAW_SIZE",
    "A19_RECORDS",
    "A19_REPORT_NAME",
    "A19_SIGNATURE",
    "A19_STATUS_UNCHANGED",
    "A19_STRUCTURED_PARSE",
    "A19_THINKING",
    "A19_THINKING_TOKENS",
    "A19_WORDS",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER",
    "COVERAGE_ARTIFACT",
    "EXAMPLE_POLICY",
    "EXAMPLE_POLICY_ARTIFACT",
    "EXAMPLE_POLICY_LABEL",
    "FUTURE_REAL_CALL_AUTHORIZED",
    "FUTURE_RETRY_ARTIFACT",
    "MODE",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROTECTED_A19",
    "PROTECTED_HISTORICAL",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "REPORT_NAME",
    "SCHEMA_CHANGED",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SEMANTIC_ARTIFACT",
    "SEMANTIC_REVIEW_STATUS",
    "SEMANTIC_TRANSPORT_VERSION_V3",
    "SERVER_GRAMMAR_STATUS",
    "SRC_CONTRACT_ARTIFACT",
    "SRC_FAILURE_CLASSIFICATION",
    "SYNTHETIC_WORST_CASE_LOCAL_TOKENS",
    "VIOLATION_ARTIFACT",
    "V3_HANDLE_ARCHITECTURE",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V13",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V131",
    "WINDOW_ID",
    "WIN001_RETRY_AUTHORIZED",
]
