"""Rapport 3B.7.7A.20."""

from __future__ import annotations

from typing import Any, Mapping


def render_report(
    *,
    header: Mapping[str, Any],
    inventory: Mapping[str, Any],
    src_audit: Mapping[str, Any],
    src_contract: Mapping[str, Any],
    examples: Mapping[str, Any],
    semantic: Mapping[str, Any],
    coverage: Mapping[str, Any],
    future: Mapping[str, Any],
    handles: Mapping[str, Any],
    isolation: Mapping[str, Any],
    tests: str,
) -> str:
    grounding = header.get("semantic_record_grounding") or {}
    rec87 = examples.get("record_87") or {}
    counts = inventory.get("counts") or {}
    lines = [
        "# PHASE 3B.7.7A.20 — A.19 FULL LATENT-VIOLATION FORENSICS & SRC HARDENING",
        "",
        "## Result",
        "",
        str(header.get("result")),
        "",
        f"REAL PROVIDER CALLS = {header.get('real_provider_calls')}",
        "",
        f"REAL WINDOW CALLS = {header.get('real_window_calls')}",
        "",
        f"A.19 STATUS = {header.get('a19_status')} unchanged",
        "",
        f"A.19 STRUCTURED PARSE = {header.get('a19_structured_parse')}",
        "",
        f"A.19 FIRST DECODER FAILURE = {header.get('a19_first_decoder_failure')}",
        "",
        f"TOTAL LATENT ROOT VIOLATIONS = {header.get('total_latent_root_violations')}",
        "",
        f"TOTAL CASCADE VIOLATIONS = {header.get('total_cascade_violations')}",
        "",
        f"MALFORMED SRC REFS = {header.get('malformed_src_refs')}",
        "",
        f"WRONG-CASE SRC REFS = {header.get('wrong_case_src_refs')}",
        "",
        f"UNKNOWN SRC REFS = {header.get('unknown_src_refs')}",
        "",
        f"OUT-OF-WINDOW SRC REFS = {header.get('out_of_window_src_refs')}",
        "",
        f"DUPLICATE SRC REFS = {header.get('duplicate_src_refs')}",
        "",
        f"HANDLE ROOT VIOLATIONS = {header.get('handle_root_violations')}",
        "",
        f"UNKNOWN HANDLES = {header.get('unknown_handles')}",
        "",
        f"WRONG-KIND HANDLES = {header.get('wrong_kind_handles')}",
        "",
        f"DUPLICATE OWNERS = {header.get('duplicate_owners')}",
        "",
        f"SELF RELATIONS = {header.get('self_relations')}",
        "",
        f"NUMERIC LINK REGRESSION = {header.get('numeric_link_regression')}",
        "",
        f"EXAMPLE EMPTY-LINK VIOLATIONS = {header.get('example_empty_link_violations')}",
        "",
        f"EXAMPLE POLICY = {header.get('example_policy')}",
        "",
        f"A.15 TARGET-KIND DEFECT = {header.get('a15_target_kind_defect')}",
        "",
        f"SEMANTIC RECORD GROUNDING = {grounding}",
        "",
        f"UNSUPPORTED CONTENT = {header.get('unsupported_content')}",
        "",
        f"MAJOR IDEA COVERAGE = {header.get('major_idea_coverage')}",
        "",
        f"SEMANTIC SRC COVERAGE = {header.get('semantic_src_coverage')}",
        "",
        f"THINKING_DISABLED CONTENT = {header.get('thinking_disabled_content')}",
        "",
        f"V3 HANDLE ARCHITECTURE = {header.get('v3_handle_architecture')}",
        "",
        f"SRC FAILURE CLASSIFICATION = {header.get('src_failure_classification')}",
        "",
        f"PROMPT = {header.get('prompt')}",
        "",
        f"TRANSPORT = {header.get('transport')}",
        "",
        f"SCHEMA CHANGED = {'YES' if header.get('schema_changed') else 'NO'}",
        "",
        f"SERVER GRAMMAR STATUS = {header.get('server_grammar_status')}",
        "",
        f"SYNTHETIC WORST CASE = {header.get('synthetic_worst_case')}",
        "",
        f"FUTURE WIN001 INPUT ESTIMATE = {header.get('future_win001_input_estimate')}",
        "",
        f"FUTURE WIN001 SIGNATURE = {header.get('future_win001_signature')}",
        "",
        f"FUTURE CACHE = {header.get('future_cache')}",
        "",
        f"FUTURE REAL CALL READY = {'YES' if header.get('future_real_call_ready') else 'NO'}",
        "",
        f"FUTURE REAL CALL AUTHORIZED = NO",
        "",
        f"PRODUCTION DEFAULT = {header.get('production_default')}",
        "",
        "SOURCE MAP = NOT PUBLISHED",
        "",
        "PHASE 3B = INCOMPLETE",
        "",
        f"TESTS = {tests}",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
        "## 1. Provider isolation",
        "",
        "Were any provider calls made? NO.",
        "Was WIN001 retried? NO.",
        "WIN002–WIN007 untouched. Consolidation untouched. Grammar canary not run.",
        "",
        "## 2. A.19 evidence",
        "",
        "A.19 remains FAIL. Structured parse PASS. Decoder FAIL on "
        f"{header.get('a19_first_decoder_failure')}.",
        "Raw provider response, structured payload, forensics, preflight, "
        "execution, report, and historical A.13–A.18 / CALL C / CLEAN hashes "
        "are byte-identical. No salvage, cache, promotion, or WIN001 write.",
        f"source_map present={isolation.get('source_map_present')}.",
        "",
        "## 3. Exhaustive violation inventory",
        "",
        f"Diagnostic validator collected {len(inventory.get('violations') or [])} "
        f"rows ({inventory.get('total_latent_root_violations')} ROOT, "
        f"{inventory.get('total_cascade_violations')} CASCADE, "
        f"{inventory.get('total_observations')} OBSERVATION).",
        f"By code: {inventory.get('by_code')}.",
        "Production fail-fast decoder is unchanged in role: it still rejects "
        "malformed SRC and does not accept SRc000609. The forensic collector "
        "does not replace it.",
        "",
        "## 4. SRC audit",
        "",
        f"Total SRC occurrences={src_audit.get('total_src_reference_occurrences')}.",
        f"Valid canonical owned occurrences={src_audit.get('valid_canonical_owned_occurrences')}.",
        f"Distinct raw tokens={src_audit.get('distinct_src_refs_raw')}.",
        f"Distinct canonical owned={src_audit.get('distinct_canonical_owned_src_refs')}.",
        f"SRc000609 is the only casing error={src_audit.get('src000609_is_only_casing_error')}.",
        f"Unknown well-formed={len(src_audit.get('unknown_well_formed_refs') or [])}.",
        f"Out-of-window={len(src_audit.get('out_of_window_refs') or [])}.",
        f"Duplicates within records={len(src_audit.get('duplicate_refs_within_records') or [])}.",
        f"Empty s[] by kind={src_audit.get('empty_s_by_kind')}.",
        "No silent .upper() / casefold / zero-pad / nearest-SRC.",
        "",
        "## 5. SRC contract",
        "",
        f"Canonical grammar={src_contract.get('canonical_pattern')}.",
        "Case-sensitive prefix SRC. Width 6. Duplicates REJECT. s[] order not semantic.",
        f"Ownership={src_contract.get('ownership')}.",
        f"Prompt 1.3 copy-exactly explicit="
        f"{(src_contract.get('prompt_1_3') or {}).get('copy_source_ids_exactly_explicit')}.",
        "1.3 says « N'utilise que les identifiants SRC listés » and « Pas de SRC inventé » "
        "but does not say case-sensitive / do not generate from number / do not alter padding.",
        f"Classification={src_contract.get('src_failure_classification')}.",
        "Preferred remediation: compact prompt 1.3.1. Do not change SRC representation. "
        "Do not put thousands of SRC IDs in schema enum. Do not replace SRC with numeric ordinals.",
        "Python must reject malformed provider SRC refs.",
        "",
        "## 6. EXAMPLE policy",
        "",
        f"Settled={examples.get('settled_policy')} — {examples.get('settled_policy_label')}",
        "Canonical supports_idea_refs is optional / allowed empty. source_refs remain required.",
        "Traceability through s[] is independent of idea association.",
        f"Record 87 value={rec87.get('value')!r}.",
        f"Record 87 s={rec87.get('source_refs')}. l={rec87.get('l')}.",
        f"Would fail A.19-era resolver={examples.get('record_87_would_fail_a19_era_resolver')}.",
        f"Violates settled contract={examples.get('record_87_violates_settled_contract')}.",
        "Policy A is too broad. Policy C is a completeness aspiration, not a validity rule.",
        "",
        "## 7. Handles",
        "",
        f"Handle gate pass={header.get('handle_gate_pass')}.",
        f"T owners={handles.get('t_handles')} I owners={handles.get('i_handles')}.",
        f"Unknown={counts.get('unknown_handles')} wrong-kind={counts.get('wrong_kind_handles')} "
        f"duplicate owners={counts.get('duplicate_owners')} self-relations={counts.get('self_relations')} "
        f"numeric regression={counts.get('numeric_link_regression')}.",
        "Exhaustive raw-graph inspection remains clean. Official pipeline still FAIL.",
        "",
        "## 8. Forensic semantic review",
        "",
        header.get("semantic_review_status"),
        "This is not a validated candidate.",
        f"Quality={semantic.get('semantic_quality')}.",
        f"Unsupported={semantic.get('unsupported_content')}.",
        f"Major outline represented={header.get('major_idea_coverage')}.",
        f"A.15 target-kind defect={header.get('a15_target_kind_defect')}.",
        "Daughter/meat and grandmother/clay-pots remain EXAMPLE→IDEA. "
        "Long-lived sinner is IDEA/UNCERTAINTY, not EXAMPLE→TOPIC.",
        f"Thinking-disabled evidence={semantic.get('thinking_disabled_local_extraction')}.",
        "",
        "## 9. Coverage",
        "",
        f"Reported 325 / 27.11 verified: distinct raw={coverage.get('verified_distinct_src_refs_raw')} "
        f"owned canonical={coverage.get('verified_distinct_canonical_owned')} "
        f"pct={coverage.get('verified_semantic_src_coverage_pct')}.",
        "325 includes the malformed token; coverage 27.11 is 324/1195 owned intersection.",
        "More coverage is not automatically better. A.15 was 19.92 with different quality defects.",
        f"Beginning/middle/end={coverage.get('beginning')}/{coverage.get('middle')}/{coverage.get('end')}.",
        "",
        "## 10. Prompt / schema / future retry",
        "",
        f"1.3 untouched={header.get('prompt_1_3_untouched')}.",
        f"1.3.1 created and contains hardening={header.get('prompt_1_3_1_contains_hardening')}.",
        f"Schema changed={'YES' if header.get('schema_changed') else 'NO'}.",
        f"A.18 grammar proof still applies. New grammar canary required=NO.",
        "Thinking remains disabled. max_output 32000. Planner window-planner-v2.1-small.",
        f"Future input estimate={future.get('future_win001_input_estimate')} "
        f"(A.19 {future.get('a19_local_input')} + overhead "
        f"{future.get('hardening_overhead_tokens')}). Must be <=35000: "
        f"{future.get('within_35000')}.",
        f"Future signature={future.get('future_win001_signature')}.",
        "Differs from A.19. Cache MISS. Identity isolated.",
        "Future real WIN001 retry technically ready only after this inventory; "
        "AUTHORIZED=NO. Do not execute 3B.7.7A.21 without human review.",
        "",
        "## 11. Required questions",
        "",
        "Were any provider calls made? NO.",
        "Was WIN001 retried? NO.",
        f"Is SRc000609 the only malformed SRC? {src_audit.get('src000609_is_only_casing_error')}.",
        f"How many SRC occurrences were valid? {src_audit.get('valid_canonical_owned_occurrences')}.",
        f"Unknown but well-formed SRCs? {len(src_audit.get('unknown_well_formed_refs') or [])}.",
        f"Out-of-window SRCs? {len(src_audit.get('out_of_window_refs') or [])}.",
        f"Duplicate SRC refs? {len(src_audit.get('duplicate_refs_within_records') or [])}.",
        f"Exact SRC grammar? {src_contract.get('canonical_pattern')}.",
        "Does 1.3 tell the model to copy SRC IDs exactly (case/width)? NO — gap closed in 1.3.1.",
        "Is source casing sufficiently explicit in 1.3? NO.",
        "Isolated copy typo or systematic fragility? ISOLATED_PROVIDER_COPY_TYPO.",
        "Should Python normalize source IDs? NO.",
        "Should the source-reference representation change? NO.",
        f"Does EXAMPLE 87 violate the intended contract? {examples.get('record_87_violates_settled_contract')}.",
        "Is the current EXAMPLE empty-link rule actually correct? NO vs canonical; settled B.",
        "What does canonical SourceMap permit? empty supports_idea_refs; required source_refs.",
        f"Root violations beyond the first decoder error? "
        f"{max(0, int(header.get('total_latent_root_violations') or 0) - 1)} additional ROOT rows.",
        f"Exhaustive handle validation clean? {header.get('handle_gate_pass')}.",
        f"A.15 target-kind defect fully eliminated in A.19 raw graph? {header.get('a15_target_kind_defect')}.",
        "Is V3 handle architecture effective? V3_HANDLES_CONFIRMED_EFFECTIVE.",
        "Is A.19 semantic content acceptable despite invalid transport? "
        f"{semantic.get('semantic_quality')}.",
        f"Unsupported claims? {semantic.get('unsupported_content')}.",
        f"Major ideas represented? {header.get('major_idea_coverage')}.",
        f"Forensic semantic SRC coverage? {header.get('semantic_src_coverage')}.",
        f"Beginning/middle/end? {coverage.get('beginning')}/{coverage.get('middle')}/{coverage.get('end')}.",
        "Does evidence still support thinking-disabled for this same source window? YES (forensic only).",
        "Was prompt 1.3.1 created? YES.",
        "Was schema changed? NO.",
        "Does A.18 grammar proof still apply? YES.",
        "Is another grammar canary required? NO.",
        f"Future WIN001 input estimate? {future.get('future_win001_input_estimate')}.",
        f"Future signature? {future.get('future_win001_signature')}.",
        "Does cache miss? YES.",
        "Have ALL observable A.19 violations been addressed before another paid retry? "
        "Inventoried and contract-hardened; not repaired in A.19 evidence.",
        f"Is a future WIN001 retry technically ready? {header.get('future_real_call_ready')}.",
        "Is it authorized? NO.",
        f"Did full suite pass? {tests}.",
        "",
        "## 12. Next phase",
        "",
        "Do NOT pre-authorize. If this report is PASS and only compact prompt/"
        "contract hardening was required, recommend 3B.7.7A.21 — REAL V3 SMALL "
        "WIN001 HARDENED RETRY, ONE provider call maximum, only after separate "
        "human authorization. Do not execute.",
        "",
        "STOP. WAIT FOR HUMAN REVIEW.",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
