"""Constantes 3B.7.7A.26.1 — audit de frontière schema.py vs kind canonique."""

from __future__ import annotations

from app.source_analysis.models import IDEA_KINDS, IMPORTANCE_LEVELS
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import PROJECT_NAME
from app.source_analysis_v31_local_lite.constants import (
    A19_STATUS,
    A21_STATUS_UNCHANGED,
    A22_STATUS,
    A23_STATUS_UNCHANGED,
    A24_STATUS,
    A25_STATUS,
    CANONICAL_IDEA_SUBTYPE,
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
    GLOBAL_IDEA_SUBTYPE_STRATEGY,
    LOCAL_IDEA_METADATA,
    LOCAL_IDEA_SUBTYPE,
    PRODUCTION_PLANNER_VERSION,
    PROMPT_VERSION,
    READY_WINDOWS,
    SELECTED_ARCHITECTURE,
    TRANSPORT_VERSION,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.26.1"
MODE = "LOCAL_LITE_CANONICAL_SCHEMA_BOUNDARY_AUDIT"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
FUTURE_REAL_CALL_AUTHORIZED = False
WIN004_RETRY_AUTHORIZED = False
A26_STATUS = "PASS"
PHASE_3B_STATUS = "INCOMPLETE"
NEXT_ACTION = "HUMAN REVIEW"
NEXT_PHASE = "3B.7.7A.27_REAL_WIN004_LOCAL_LITE_CANARY"
A27_AUTHORIZATION = "READY_FOR_HUMAN_AUTHORIZATION"

MISMATCH_CLASSIFICATION = "EXPECTED_STAGE_SPECIFIC_SCHEMA"
BLOCKS_A27 = False
PRODUCTION_CHANGED = False
SOURCE_MAP_STATUS = "NOT PUBLISHED"

ABSENCE_REPRESENTATION = "empty string"
OPTIONAL_KIND_SEMANTICS = "FIELD_PRESENT_WITH_EMPTY_STRING"

BOUNDARY_ARTIFACT = "source_analysis_v31_schema_boundary_analysis.json"
ROUNDTRIP_ARTIFACT = "source_analysis_v31_canonical_kind_roundtrip.json"
MIXED_ARTIFACT = "source_analysis_v31_mixed_version_boundary.json"
REPORT_NAME = "PHASE_3B77A261_LOCAL_LITE_CANONICAL_SCHEMA_BOUNDARY_REPORT.md"

assert SELECTED_ARCHITECTURE == "GLOBALIZE_IDEA_SUBTYPE"
assert GLOBAL_IDEA_SUBTYPE_STRATEGY == "A_ABSENT_IF_OPTIONAL"
assert CANONICAL_IDEA_SUBTYPE == "OPTIONAL_ABSENT"
assert LOCAL_IDEA_SUBTYPE == "REMOVED"
assert LOCAL_IDEA_METADATA == "m=[importance]"
assert TRANSPORT_VERSION == "semantic-transport-v3.1-local-lite"
assert PROMPT_VERSION == "window-analysis-1.4.0"
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert A26_STATUS == "PASS"
assert A19_STATUS == "FAIL"
assert A21_STATUS_UNCHANGED == "PASS"
assert A22_STATUS == "FAIL"
assert A23_STATUS_UNCHANGED == "PASS"
assert A24_STATUS == "FAIL"
assert A25_STATUS == "PARTIAL"
assert MISMATCH_CLASSIFICATION == "EXPECTED_STAGE_SPECIFIC_SCHEMA"
assert BLOCKS_A27 is False
assert PRODUCTION_CHANGED is False
assert REAL_PROVIDER_CALLS_THIS_PHASE == 0
assert not set(IDEA_KINDS) & set(IMPORTANCE_LEVELS)
assert PLANNER_VERSION == PRODUCTION_PLANNER_VERSION == "window-planner-v2.0"

__all__ = [
    "A19_STATUS",
    "A21_STATUS_UNCHANGED",
    "A22_STATUS",
    "A23_STATUS_UNCHANGED",
    "A24_STATUS",
    "A25_STATUS",
    "A26_STATUS",
    "A27_AUTHORIZATION",
    "ABSENCE_REPRESENTATION",
    "BLOCKS_A27",
    "BOUNDARY_ARTIFACT",
    "CANONICAL_IDEA_SUBTYPE",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "FUTURE_REAL_CALL_AUTHORIZED",
    "GLOBAL_IDEA_SUBTYPE_STRATEGY",
    "LOCAL_IDEA_METADATA",
    "LOCAL_IDEA_SUBTYPE",
    "MISMATCH_CLASSIFICATION",
    "MIXED_ARTIFACT",
    "MODE",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "OPTIONAL_KIND_SEMANTICS",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_CHANGED",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "READY_WINDOWS",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "REPORT_NAME",
    "ROUNDTRIP_ARTIFACT",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SOURCE_MAP_STATUS",
    "TRANSPORT_VERSION",
    "WIN004_RETRY_AUTHORIZED",
]
