"""Constantes 3B.7.7A.27 — canary réel WIN004 v3.1-local-lite. 1 appel max."""

from __future__ import annotations

from app.source_analysis.models import IDEA_KINDS, IMPORTANCE_LEVELS
from app.source_analysis.window_models import (
    WINDOW_CONNECT_TIMEOUT_SECONDS,
    WINDOW_READ_TIMEOUT_SECONDS,
)
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    CLEAN_SHA,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
    SEMANTIC_TRANSPORT_VERSION_V3,
    SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE,
    WINDOW_ANALYSIS_PROMPT_VERSION_V13,
    WINDOW_ANALYSIS_PROMPT_VERSION_V131,
    WINDOW_ANALYSIS_PROMPT_VERSION_V132,
    WINDOW_ANALYSIS_PROMPT_VERSION_V140,
)
from app.source_analysis_local_v3.schema import (
    semantic_transport_v3_fingerprint,
    semantic_transport_v31_local_lite_fingerprint,
)
from app.source_analysis_output_ceiling_review.constants import (
    CALL1_SIGNATURE,
    CALL2_SIGNATURE,
    SMALL_SIGNATURE,
)
from app.source_analysis_small_window_hierarchy.constants import (
    CANDIDATE_CONTEXT_POLICY,
)
from app.source_analysis_thinking_contract.constants import (
    SELECTED_CONTRACT,
    SELECTED_EFFORT,
    SELECTED_THINKING_MODE,
)
from app.source_analysis_v2_a15_forensics.constants import A15_SIGNATURE
from app.source_analysis_v2_link_semantics.constants import A13_REQUEST_IDENTITY
from app.source_analysis_v3_a19_forensics.constants import (
    A19_STATUS_UNCHANGED,
    EXAMPLE_POLICY,
    EXAMPLE_POLICY_LABEL,
    V3_HANDLE_ARCHITECTURE,
)
from app.source_analysis_v3_a22_forensics.constants import (
    A21_RESULT,
    A22_COVERAGE_PCT,
    A22_DISTINCT_SRC,
    A22_EXAMPLE,
    A22_FINISH,
    A22_FORENSIC_IDENTITY,
    A22_HTTP,
    A22_IDEA,
    A22_INPUT_HASH,
    A22_LOCAL_INPUT,
    A22_OUTPUT,
    A22_OWNED,
    A22_PROMPT_FINGERPRINT,
    A22_PROMPT_SHA256,
    A22_PROVIDER_INPUT,
    A22_QUALITY_REASON_REPORTED,
    A22_QUALITY_REPORTED,
    A22_RECORDS,
    A22_REFERENCE,
    A22_RELATION,
    A22_REQUEST_ID,
    A22_SIGNATURE,
    A22_SRC_RANGE,
    A22_STATUS_UNCHANGED,
    A22_STRUCTURED_PARSE,
    A22_TARGET,
    A22_THINKING,
    A22_THINKING_TOKENS,
    A22_TOPIC,
    A22_TOTAL_SRC_OCCURRENCES,
    A22_UNCERTAINTY,
    A22_VALID_SRC_OCCURRENCES,
    A22_WORDS,
    REPORT_NAME as A23_REPORT_NAME,
)
from app.source_analysis_v3_a25_forensics.constants import (
    A23_STATUS,
    A24_COVERAGE_PCT,
    A24_EXAMPLE,
    A24_FINISH,
    A24_FORENSIC_IDENTITY,
    A24_HTTP,
    A24_IDEA,
    A24_LOCAL_INPUT,
    A24_OUTPUT,
    A24_PROMPT_FINGERPRINT,
    A24_PROMPT_SHA256,
    A24_PROVIDER_INPUT,
    A24_RECORDS,
    A24_REFERENCE,
    A24_RELATION,
    A24_REQUEST_ID,
    A24_SIGNATURE,
    A24_SRC_RANGE,
    A24_STATUS_UNCHANGED,
    A24_STRUCTURED_PARSE,
    A24_THINKING,
    A24_THINKING_TOKENS,
    A24_TOPIC,
    A24_TOTAL_SRC_OCCURRENCES,
    A24_VALID_SRC_OCCURRENCES,
    PROTECTED_HISTORICAL as A25_PROTECTED_HISTORICAL,
    REPORT_NAME as A25_REPORT_NAME,
)
from app.source_analysis_v3_hardened_win001.constants import (
    AUTHORIZATION_SCOPE as A21_AUTHORIZATION_SCOPE,
    EXPECTED_ANALYSIS_SIGNATURE as A21_SIGNATURE,
    EXPECTED_FORENSIC_IDENTITY as A21_FORENSIC,
    WINDOW_ID as A21_WINDOW_ID,
)
from app.source_analysis_v3_real_win001.constants import (
    EXPECTED_A18_REQUEST_IDENTITY,
    EXPECTED_ANALYSIS_SIGNATURE as A19_SIGNATURE,
    EXPECTED_FORENSIC_IDENTITY as A19_FORENSIC,
)
from app.source_analysis_v3_second_window.constants import (
    AUTHORIZATION_SCOPE as A22_AUTHORIZATION_SCOPE,
    EXPECTED_SCHEMA_HASH,
    EXPECTED_WIN004_FIRST_OWNED_SRC,
    EXPECTED_WIN004_INPUT_HASH,
    EXPECTED_WIN004_LAST_OWNED_SRC,
    EXPECTED_WIN004_OWNED_SRC_COUNT,
    EXPECTED_WIN004_WORD_COUNT,
)
from app.source_analysis_v3_hardened_win004.constants import (
    AUTHORIZATION_SCOPE as A24_AUTHORIZATION_SCOPE,
)
from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    A17_SCHEMA_FINGERPRINT,
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)
from app.source_analysis_v31_local_lite.constants import (
    A25_STATUS,
    FUTURE_ARTIFACT as A26_FUTURE_ARTIFACT,
    REPORT_NAME as A26_REPORT_NAME,
)
from app.source_analysis_v31_schema_boundary.constants import (
    A26_STATUS,
    REPORT_NAME as A261_REPORT_NAME,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.27"
MODE = "REAL_WIN004_LOCAL_LITE_CANARY"

AUTHORIZATION_SCOPE = "SMALL_V21_V31_LOCAL_LITE_WIN004_ONLY"
WINDOW_ID = "WIN004"
FORBIDDEN_WINDOW_IDS = (
    "WIN001",
    "WIN002",
    "WIN003",
    "WIN005",
    "WIN006",
    "WIN007",
    "WIN996",
)

PROVIDER = "anthropic"
MODEL = "claude-sonnet-5"
THINKING_CONTRACT = SELECTED_CONTRACT
THINKING_MODE = SELECTED_THINKING_MODE
EFFORT = SELECTED_EFFORT

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False

MAX_OUTPUT_TOKENS = MAX_OUTPUT_TOKENS_FROZEN
CONNECT_TIMEOUT_SECONDS = WINDOW_CONNECT_TIMEOUT_SECONDS
READ_TIMEOUT_SECONDS = WINDOW_READ_TIMEOUT_SECONDS
HISTORICAL_READ_TIMEOUT_SECONDS = 7200.0

EXPECTED_ANALYSIS_SIGNATURE = (
    "a751d06e88b7ac1f36c4435e5a1c684e34300e64eae47254d63ff94afee7a724"
)
EXPECTED_FORENSIC_IDENTITY = (
    "83900399fe6c7428a96d9eeb582e6d2d9b3a5c92ddba23b85dd9962d0c3a35e1"
)
EXPECTED_PROMPT_SHA256 = (
    "32240d6f63cd646888ceea3d0d87c1d9cd40091565b5067e24acdfe1edc60259"
)
EXPECTED_PROMPT_FINGERPRINT = (
    "e78d75f919986a34db39c9480dbd49bc91f979a6d1e6a75f3d398b165892f9ec"
)
EXPECTED_SCHEMA_HASH = EXPECTED_SCHEMA_HASH
EXPECTED_WINDOW_INPUT_HASH = EXPECTED_WIN004_INPUT_HASH
EXPECTED_OWNED_SRC_COUNT = EXPECTED_WIN004_OWNED_SRC_COUNT
EXPECTED_WORD_COUNT = EXPECTED_WIN004_WORD_COUNT
EXPECTED_FIRST_OWNED_SRC = EXPECTED_WIN004_FIRST_OWNED_SRC
EXPECTED_LAST_OWNED_SRC = EXPECTED_WIN004_LAST_OWNED_SRC
EXPECTED_CLEAN_SHA = CLEAN_SHA
EXPECTED_CLEAN_FILE_SHA = CLEAN_SHA
EXPECTED_CONTEXT_COUNT = 0
EXPECTED_CONTEXT_POLICY = CANDIDATE_CONTEXT_POLICY
EXPECTED_LOCAL_INPUT_ESTIMATE = 23046

A13_SYNTHETIC_IDENTITY = A13_REQUEST_IDENTITY
A15_V2_SIGNATURE = A15_SIGNATURE
A18_REQUEST_IDENTITY = EXPECTED_A18_REQUEST_IDENTITY
A19_V3_SIGNATURE = A19_SIGNATURE
A19_V3_FORENSIC = A19_FORENSIC
A19_RESULT = A19_STATUS_UNCHANGED
A21_V3_SIGNATURE = A21_SIGNATURE
A21_V3_FORENSIC = A21_FORENSIC
A21_RESULT = A21_RESULT
A22_V3_SIGNATURE = A22_SIGNATURE
A22_V3_FORENSIC = A22_FORENSIC_IDENTITY
A22_RESULT = A22_STATUS_UNCHANGED
A23_RESULT = A23_STATUS
A24_V3_SIGNATURE = A24_SIGNATURE
A24_V3_FORENSIC = A24_FORENSIC_IDENTITY
A24_RESULT = A24_STATUS_UNCHANGED
A25_RESULT = A25_STATUS
A26_RESULT = A26_STATUS
A261_RESULT = "PASS"

A22_PROMPT = WINDOW_ANALYSIS_PROMPT_VERSION_V131
A24_PROMPT = WINDOW_ANALYSIS_PROMPT_VERSION_V132
A22_READY = "1 / 7"

IMPORTANCE_VOCABULARY = IMPORTANCE_LEVELS
IDEA_SUBTYPE_TOKENS = IDEA_KINDS + ("example",)
OLD_V3_IDEA_SHAPE = ("claim", "primary")
A24_INVALID_IDEA_SHAPE = ("example", "supporting")

LOCK_NAME = "a27_real_v31_local_lite_win004.lock"
CANARY_SUBDIR = "canary/v31_local_lite_win004"
CANDIDATE_WINDOWS_SUBDIR = "v31_windows"
CANDIDATE_CACHE_SUBDIR = "v31_cache"

BASELINE_ARTIFACT = "source_analysis_v31_win004_test_baseline.json"
PREFLIGHT_ARTIFACT = "source_analysis_v31_win004_real_preflight.json"
EXECUTION_ARTIFACT = "source_analysis_v31_win004_real_execution.json"
LOCAL_LITE_ARTIFACT = "source_analysis_v31_win004_local_lite_analysis.json"
SRC_ARTIFACT = "source_analysis_v31_win004_src_analysis.json"
HANDLE_ARTIFACT = "source_analysis_v31_win004_handle_analysis.json"
REVIEW_ARTIFACT = "source_analysis_v31_win004_semantic_review.json"
CANONICAL_ARTIFACT = "source_analysis_v31_win004_canonical_reconstruction.json"
COMPARISON_ARTIFACT = "source_analysis_v31_win004_vs_a22_a24.json"
POST_TEST_ARTIFACT = "source_analysis_v31_win004_post_test_delta.json"
REPORT_NAME = "PHASE_3B77A27_REAL_WIN004_LOCAL_LITE_CANARY_REPORT.md"

SEMANTIC_REVIEW_STATUS = "FORENSIC_SEMANTIC_REVIEW_OF_VALID_V31_LOCAL_LITE_WIN004_CANDIDATE"
SEMANTIC_REVIEW_INVALID = "FORENSIC_SEMANTIC_REVIEW_OF_INVALID_V31_LOCAL_LITE_TRANSPORT"
EXAMPLE_POLICY = EXAMPLE_POLICY
EXAMPLE_POLICY_LABEL = EXAMPLE_POLICY_LABEL
SERVER_GRAMMAR_STATUS = "A18_PROOF_APPLICABLE"
SUBTYPE_FAILURE_CLASS_IF_PASS = "ELIMINATED_BY_ARCHITECTURE"

PROTECTED_A25_A26 = (
    f"audit/{A25_REPORT_NAME}",
    f"audit/{A26_REPORT_NAME}",
    f"audit/{A26_FUTURE_ARTIFACT}",
    f"audit/{A261_REPORT_NAME}",
)
PROTECTED_HISTORICAL = tuple(A25_PROTECTED_HISTORICAL) + PROTECTED_A25_A26

DRY_RUN_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v31_real_win004 "
    "pastoral_retreat_v2_validation "
    "--authorization-scope SMALL_V21_V31_LOCAL_LITE_WIN004_ONLY "
    "--window WIN004 --dry-run"
)
REAL_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v31_real_win004 "
    "pastoral_retreat_v2_validation "
    "--authorization-scope SMALL_V21_V31_LOCAL_LITE_WIN004_ONLY "
    "--window WIN004 --execute-real"
)

NEXT_ACTION = "HUMAN REVIEW"
NEXT_PHASE = "3B.7.7A.28_BOUNDED_REMAINING_REAL_WINDOWS"
NEXT_PHASE_LABEL = (
    "3B.7.7A.28 — BOUNDED REMAINING REAL WINDOWS "
    "(WIN002/003/005/006/007, 5 calls maximum; NOT authorized here)"
)
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION
PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V140
TRANSPORT_VERSION = SEMANTIC_TRANSPORT_VERSION_V31_LOCAL_LITE
SELECTED_ARCHITECTURE = "GLOBALIZE_IDEA_SUBTYPE"

assert EXPECTED_SCHEMA_HASH == (
    "de42ce0f3c271e67b902a94d2f528eae56f82b1a2a5740e65161987038849425"
)
assert semantic_transport_v31_local_lite_fingerprint() == EXPECTED_SCHEMA_HASH
assert semantic_transport_v3_fingerprint() == EXPECTED_SCHEMA_HASH
assert A17_SCHEMA_FINGERPRINT == EXPECTED_SCHEMA_HASH
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert MAX_OUTPUT_TOKENS == 32000
assert THINKING_MODE == "disabled"
assert EFFORT is None
assert AUTHORIZATION_SCOPE == "SMALL_V21_V31_LOCAL_LITE_WIN004_ONLY"
assert AUTHORIZATION_SCOPE != A21_AUTHORIZATION_SCOPE
assert AUTHORIZATION_SCOPE != A22_AUTHORIZATION_SCOPE
assert AUTHORIZATION_SCOPE != A24_AUTHORIZATION_SCOPE
assert WINDOW_ID == "WIN004"
assert WINDOW_ID != A21_WINDOW_ID
assert EXPECTED_ANALYSIS_SIGNATURE != A22_V3_SIGNATURE
assert EXPECTED_ANALYSIS_SIGNATURE != A24_V3_SIGNATURE
assert EXPECTED_ANALYSIS_SIGNATURE != A21_V3_SIGNATURE
assert EXPECTED_ANALYSIS_SIGNATURE != A19_V3_SIGNATURE
assert EXPECTED_FORENSIC_IDENTITY != A22_V3_FORENSIC
assert EXPECTED_FORENSIC_IDENTITY != A24_V3_FORENSIC
assert EXPECTED_LOCAL_INPUT_ESTIMATE == 23046
assert EXPECTED_OWNED_SRC_COUNT == 1180
assert EXPECTED_WORD_COUNT == 5662
assert A19_RESULT == "FAIL"
assert A21_RESULT == "PASS"
assert A22_RESULT == "FAIL"
assert A23_RESULT == "PASS"
assert A24_RESULT == "FAIL"
assert A25_RESULT == "PARTIAL"
assert A26_RESULT == "PASS"
assert A261_RESULT == "PASS"
assert PROMPT_VERSION == "window-analysis-1.4.0"
assert TRANSPORT_VERSION == "semantic-transport-v3.1-local-lite"
assert WINDOW_ANALYSIS_PROMPT_VERSION_V13 == "window-analysis-1.3"
assert WINDOW_ANALYSIS_PROMPT_VERSION_V131 == "window-analysis-1.3.1"
assert WINDOW_ANALYSIS_PROMPT_VERSION_V132 == "window-analysis-1.3.2"
assert not set(IDEA_KINDS) & set(IMPORTANCE_LEVELS)

__all__ = [
    "A13_SYNTHETIC_IDENTITY",
    "A15_V2_SIGNATURE",
    "A17_SCHEMA_FINGERPRINT",
    "A18_REQUEST_IDENTITY",
    "A19_RESULT",
    "A19_V3_FORENSIC",
    "A19_V3_SIGNATURE",
    "A21_AUTHORIZATION_SCOPE",
    "A21_RESULT",
    "A21_V3_FORENSIC",
    "A21_V3_SIGNATURE",
    "A21_WINDOW_ID",
    "A22_AUTHORIZATION_SCOPE",
    "A22_COVERAGE_PCT",
    "A22_DISTINCT_SRC",
    "A22_EXAMPLE",
    "A22_FINISH",
    "A22_HTTP",
    "A22_IDEA",
    "A22_INPUT_HASH",
    "A22_LOCAL_INPUT",
    "A22_OUTPUT",
    "A22_OWNED",
    "A22_PROMPT",
    "A22_PROMPT_FINGERPRINT",
    "A22_PROMPT_SHA256",
    "A22_PROVIDER_INPUT",
    "A22_QUALITY_REASON_REPORTED",
    "A22_QUALITY_REPORTED",
    "A22_READY",
    "A22_RECORDS",
    "A22_REFERENCE",
    "A22_RELATION",
    "A22_REQUEST_ID",
    "A22_RESULT",
    "A22_SRC_RANGE",
    "A22_STRUCTURED_PARSE",
    "A22_TARGET",
    "A22_THINKING",
    "A22_THINKING_TOKENS",
    "A22_TOPIC",
    "A22_TOTAL_SRC_OCCURRENCES",
    "A22_UNCERTAINTY",
    "A22_VALID_SRC_OCCURRENCES",
    "A22_V3_FORENSIC",
    "A22_V3_SIGNATURE",
    "A22_WORDS",
    "A23_RESULT",
    "A24_AUTHORIZATION_SCOPE",
    "A24_COVERAGE_PCT",
    "A24_EXAMPLE",
    "A24_FINISH",
    "A24_HTTP",
    "A24_IDEA",
    "A24_INVALID_IDEA_SHAPE",
    "A24_LOCAL_INPUT",
    "A24_OUTPUT",
    "A24_PROMPT",
    "A24_PROMPT_FINGERPRINT",
    "A24_PROMPT_SHA256",
    "A24_PROVIDER_INPUT",
    "A24_RECORDS",
    "A24_REFERENCE",
    "A24_RELATION",
    "A24_REQUEST_ID",
    "A24_RESULT",
    "A24_SRC_RANGE",
    "A24_STRUCTURED_PARSE",
    "A24_THINKING",
    "A24_THINKING_TOKENS",
    "A24_TOPIC",
    "A24_TOTAL_SRC_OCCURRENCES",
    "A24_VALID_SRC_OCCURRENCES",
    "A24_V3_FORENSIC",
    "A24_V3_SIGNATURE",
    "A25_RESULT",
    "A26_RESULT",
    "A261_RESULT",
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "BASELINE_ARTIFACT",
    "CALL1_SIGNATURE",
    "CALL2_SIGNATURE",
    "CANARY_SUBDIR",
    "CANONICAL_ARTIFACT",
    "CANDIDATE_CACHE_SUBDIR",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER",
    "CANDIDATE_WINDOWS_SUBDIR",
    "COMPARISON_ARTIFACT",
    "CONNECT_TIMEOUT_SECONDS",
    "DRY_RUN_COMMAND",
    "EFFORT",
    "EXAMPLE_POLICY",
    "EXAMPLE_POLICY_LABEL",
    "EXECUTION_ARTIFACT",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_ANALYSIS_SIGNATURE",
    "EXPECTED_CLEAN_FILE_SHA",
    "EXPECTED_CLEAN_SHA",
    "EXPECTED_CONTEXT_COUNT",
    "EXPECTED_CONTEXT_POLICY",
    "EXPECTED_FIRST_OWNED_SRC",
    "EXPECTED_FORENSIC_IDENTITY",
    "EXPECTED_LAST_OWNED_SRC",
    "EXPECTED_LOCAL_INPUT_ESTIMATE",
    "EXPECTED_OWNED_SRC_COUNT",
    "EXPECTED_PROMPT_FINGERPRINT",
    "EXPECTED_PROMPT_SHA256",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "EXPECTED_SCHEMA_HASH",
    "EXPECTED_WINDOW_INPUT_HASH",
    "EXPECTED_WORD_COUNT",
    "FORBIDDEN_WINDOW_IDS",
    "HANDLE_ARTIFACT",
    "HISTORICAL_READ_TIMEOUT_SECONDS",
    "IDEA_SUBTYPE_TOKENS",
    "IMPORTANCE_VOCABULARY",
    "LOCAL_LITE_ARTIFACT",
    "LOCK_NAME",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MAX_OUTPUT_TOKENS",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "OLD_V3_IDEA_SHAPE",
    "PHASE",
    "PHASE_3B_STATUS",
    "POST_TEST_ARTIFACT",
    "PREFLIGHT_ARTIFACT",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "READ_TIMEOUT_SECONDS",
    "REAL_COMMAND",
    "REPORT_NAME",
    "REVIEW_ARTIFACT",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SEMANTIC_REVIEW_INVALID",
    "SEMANTIC_REVIEW_STATUS",
    "SEMANTIC_TRANSPORT_VERSION_V3",
    "SERVER_GRAMMAR_STATUS",
    "SMALL_SIGNATURE",
    "SRC_ARTIFACT",
    "SUBTYPE_FAILURE_CLASS_IF_PASS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
    "V3_HANDLE_ARCHITECTURE",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V13",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V131",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V132",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V140",
    "WINDOW_ID",
]
