"""Phase 4B.2.13 — isolated Book Generator × Semantic Gate 2.0 preflight."""

from app.book_generation_integration_4b213.constants import (
    AUTHORIZED_TERRA_CALLS,
    INTEGRATION_CONTRACT_ACTIVATED,
    PHASE,
    PRODUCTION_PIPELINE_HOOK,
    REAL_CHAPTER_GENERATION_AUTHORIZED,
    SEMANTIC_GATE_20_ENABLED,
    SEMANTIC_GATE_202_ENABLED,
    SONNET_EXECUTION_AUTHORIZED,
    TERRA_EXECUTION_AUTHORIZED,
)

assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert SONNET_EXECUTION_AUTHORIZED is False
assert REAL_CHAPTER_GENERATION_AUTHORIZED is False
assert SEMANTIC_GATE_20_ENABLED is False
assert SEMANTIC_GATE_202_ENABLED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert INTEGRATION_CONTRACT_ACTIVATED is False

__all__ = [
    "PHASE",
    "AUTHORIZED_TERRA_CALLS",
    "TERRA_EXECUTION_AUTHORIZED",
    "SONNET_EXECUTION_AUTHORIZED",
    "REAL_CHAPTER_GENERATION_AUTHORIZED",
    "SEMANTIC_GATE_20_ENABLED",
    "SEMANTIC_GATE_202_ENABLED",
    "PRODUCTION_PIPELINE_HOOK",
    "INTEGRATION_CONTRACT_ACTIVATED",
]
