"""
Phase 4B.2.13 — Book Generator × Semantic Gate 2.0 controlled integration preflight.

STRICTLY OFFLINE. Isolated from production. Zero provider calls.
Does not generate a real chapter. Does not activate Semantic Gate 2.0.
Does not write the production cache. Does not publish book.json.
"""

from __future__ import annotations

from app.book_generation.constants import (
    BOOK_FILENAME,
    BOOK_GENERATION_TRANSPORT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_VALIDATOR_VERSION,
    BOOK_SCHEMA_VERSION,
    VALIDATION_PROJECT_NAME,
)
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
)
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE
from app.book_semantic_gate_4b210.constants import (
    H01_EVIDENCE_HANDLES,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
    TRANSPORT_VERSION_20_CANDIDATE,
)
from app.book_semantic_gate_4b211.constants import HISTORICAL_4B210_STATUS
from app.book_semantic_gate_4b212.constants import (
    DECISION_BLOCK,
    DECISION_PASS,
    DECISION_REVIEW,
    FIXTURE_KIND,
    HISTORICAL_4B211_COST_USD,
    HISTORICAL_4B211_COMPLETION_TOKENS,
    HISTORICAL_4B211_INPUT_TOKENS,
    HISTORICAL_4B211_REASONING_TOKENS,
    HISTORICAL_4B211_STATUS,
    PROMPT_VERSION_20_CANDIDATE,
    PROMPT_VERSION_201_CANDIDATE,
    PROMPT_VERSION_202_CANDIDATE,
)
from app.book_semantic_gate_4b29.constants import OFFSET_CONVENTION, OFFSET_CONVENTION_NOTES

PHASE = "4B.2.13"
PHASE_NAME = "BOOK_GENERATOR_SEMANTIC_GATE_20_CONTROLLED_INTEGRATION_PREFLIGHT"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_GENERATION_INTEGRATION_4B213_BOOK_GENERATOR_SEMANTIC_GATE_20_"
    "CONTROLLED_INTEGRATION_PREFLIGHT_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = False
REAL_CHAPTER_GENERATION_AUTHORIZED = False
SDK_MAX_RETRIES = 0
RETRIES = 0
FALLBACKS = 0

SEMANTIC_GATE_20_ENABLED = False
SEMANTIC_GATE_201_ENABLED = False
SEMANTIC_GATE_202_ENABLED = False
PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False

CODE_VERSION = "app.book_generation_integration_4b213"
INTEGRATION_CONTRACT_VERSION = (
    "book-generator-semantic-gate-integration-4b213-candidate"
)
PREPARATION_ALGORITHM_VERSION = (
    "book-semantic-preparation-4b28-conservative-via-4b29"
)
VALIDATOR_IMPLEMENTATION_VERSION = (
    "app.book_semantic_gate_4b212.validator.validate_response_202"
)
ISOLATED_CACHE_VERSION = "book-generation-integration-cache-4b213-isolated"
PHASE5_INTERFACE_VERSION = "book-validator-phase5-interface-4b213-candidate"

PROMPT_VERSION_20_ACTIVATED = False
PROMPT_VERSION_201_ACTIVATED = False
PROMPT_VERSION_202_ACTIVATED = False
TRANSPORT_VERSION_20_ACTIVATED = False
INTEGRATION_CONTRACT_ACTIVATED = False

FAKEAI_SOURCE = "FAKEAI_SIMULATED"
FAKEAI_GENERATOR_ROLE = "simulated_book_generator"
FAKEAI_SEMANTIC_ROLE = "simulated_semantic_validator"
NOT_TERRA = True
NOT_SONNET = True

CACHE_GENERATION_OBTAINED = "GENERATION_OBTAINED"
CACHE_VALIDATION_PENDING = "VALIDATION_PENDING"
CACHE_VALIDATION_PASS = "VALIDATION_PASS"
CACHE_VALIDATION_REVIEW = "VALIDATION_REVIEW"
CACHE_VALIDATION_BLOCK = "VALIDATION_BLOCK"
CACHE_TECHNICAL_ERROR = "TECHNICAL_ERROR"
CACHE_INTERRUPTED = "INTERRUPTED"
ISOLATED_CACHE_STATES = (
    CACHE_GENERATION_OBTAINED,
    CACHE_VALIDATION_PENDING,
    CACHE_VALIDATION_PASS,
    CACHE_VALIDATION_REVIEW,
    CACHE_VALIDATION_BLOCK,
    CACHE_TECHNICAL_ERROR,
    CACHE_INTERRUPTED,
)

INTERRUPT_AFTER_GENERATION = "after_generation"
INTERRUPT_BEFORE_VALIDATION = "before_validation"
INTERRUPT_DURING_VALIDATION = "during_validation"
INTERRUPT_AFTER_PASS = "after_pass"
INTERRUPT_AFTER_REVIEW = "after_review"
INTERRUPT_AFTER_BLOCK = "after_block"
INTERRUPTION_POINTS = (
    INTERRUPT_AFTER_GENERATION,
    INTERRUPT_BEFORE_VALIDATION,
    INTERRUPT_DURING_VALIDATION,
    INTERRUPT_AFTER_PASS,
    INTERRUPT_AFTER_REVIEW,
    INTERRUPT_AFTER_BLOCK,
)

SYNTHETIC_PREFIX = "SYN-"
SYNTHETIC_SOURCE_MAP_HASH = "SYNTHETIC_OFFLINE_FIXTURE"
SYNTHETIC_EDITORIAL_PLAN_HASH = "SYNTHETIC_OFFLINE_FIXTURE"

assert PROJECT_NAME == "pastoral_retreat_v2_validation"
assert AUTHORIZED_TERRA_CALLS == 0
assert AUTHORIZED_SONNET_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert SONNET_EXECUTION_AUTHORIZED is False
assert REAL_CHAPTER_GENERATION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False
assert SEMANTIC_GATE_20_ENABLED is False
assert SEMANTIC_GATE_202_ENABLED is False
assert PRODUCTION_PIPELINE_HOOK is False
assert PRODUCTION_CACHE_ACCEPTANCE is False
assert PROMPT_VERSION_202_CANDIDATE == "book-semantic-validator-2.0.2-candidate"
assert TRANSPORT_VERSION_20_CANDIDATE == (
    "book-semantic-validation-transport-2.0-candidate"
)
assert PROMPT_VERSION_202_ACTIVATED is False
assert TRANSPORT_VERSION_20_ACTIVATED is False
assert INTEGRATION_CONTRACT_ACTIVATED is False
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert HISTORICAL_H11_STATUS == "PARTIAL"
assert HISTORICAL_4B210_STATUS == "PASS"
assert HISTORICAL_4B211_STATUS == "PARTIAL"
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert CANONICAL_PYTHON_EXECUTABLE.endswith("python.exe")
assert BOOK_FILENAME == "book.json"
assert SDK_MAX_RETRIES == 0
assert RETRIES == 0
assert FALLBACKS == 0
assert CLASSIFICATIONS == (
    CLASS_SUPPORTED,
    CLASS_QUESTIONABLE,
    CLASS_UNSUPPORTED,
    CLASS_NON_SUBSTANTIVE,
)

AUDIT_DIRNAME = "book_generation_integration_4b213"
AUDIT_INVENTORY = "technical_inventory.json"
AUDIT_ARCHITECTURE = "integration_architecture.json"
AUDIT_CONTRACT = "integration_contract.json"
AUDIT_PREPARATION = "deterministic_preparation.json"
AUDIT_FAKEAI_GENERATION = "fakeai_generation_scenarios.json"
AUDIT_FAKEAI_SEMANTIC = "fakeai_semantic_scenarios.json"
AUDIT_CHAPTER = "chapter_validation.json"
AUDIT_CACHE = "isolated_cache.json"
AUDIT_INVALIDATION = "cache_invalidation.json"
AUDIT_RECOVERY = "interruption_recovery.json"
AUDIT_TRACEABILITY = "traceability.json"
AUDIT_PHASE5 = "phase5_interface.json"
AUDIT_COST = "cost_estimates.json"
AUDIT_STRATEGY = "controlled_generation_strategy.json"
AUDIT_SAFETY = "provider_safety.json"
AUDIT_HASHES = "canonical_hashes.json"
AUDIT_TESTS = "offline_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_INDEX = "book_generation_integration_4b213_index.json"
REPORT_NAME = (
    "PHASE_4B213_BOOK_GENERATOR_SEMANTIC_GATE_20_CONTROLLED_INTEGRATION_PREFLIGHT_REPORT.md"
)

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_CONTROLLED_INTEGRATION_HUMAN_REVIEW = True
READY_FOR_ONE_REAL_CHAPTER_EXPERIMENT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "AUDIT_ARCHITECTURE",
    "AUDIT_CACHE",
    "AUDIT_CHAPTER",
    "AUDIT_CONTRACT",
    "AUDIT_COST",
    "AUDIT_DIRNAME",
    "AUDIT_FAKEAI_GENERATION",
    "AUDIT_FAKEAI_SEMANTIC",
    "AUDIT_HASHES",
    "AUDIT_INDEX",
    "AUDIT_INVALIDATION",
    "AUDIT_INVENTORY",
    "AUDIT_PHASE5",
    "AUDIT_PREPARATION",
    "AUDIT_READINESS",
    "AUDIT_RECOVERY",
    "AUDIT_SAFETY",
    "AUDIT_STRATEGY",
    "AUDIT_TESTS",
    "AUDIT_TRACEABILITY",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_REMOTE_INVOCATIONS",
    "AUTHORIZED_SONNET_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "BOOK_FILENAME",
    "BOOK_GENERATION_TRANSPORT_VERSION",
    "BOOK_GENERATOR_PROMPT_VERSION",
    "BOOK_GENERATOR_VALIDATOR_VERSION",
    "BOOK_SCHEMA_VERSION",
    "CACHE_GENERATION_OBTAINED",
    "CACHE_INTERRUPTED",
    "CACHE_TECHNICAL_ERROR",
    "CACHE_VALIDATION_BLOCK",
    "CACHE_VALIDATION_PASS",
    "CACHE_VALIDATION_PENDING",
    "CACHE_VALIDATION_REVIEW",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CODE_VERSION",
    "DECISION_BLOCK",
    "DECISION_PASS",
    "DECISION_REVIEW",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_SOURCE_MAP",
    "FAKEAI_GENERATOR_ROLE",
    "FAKEAI_SEMANTIC_ROLE",
    "FAKEAI_SOURCE",
    "FALLBACKS",
    "FIXTURE_KIND",
    "H01_EVIDENCE_HANDLES",
    "HISTORICAL_4B210_STATUS",
    "HISTORICAL_4B211_COMPLETION_TOKENS",
    "HISTORICAL_4B211_COST_USD",
    "HISTORICAL_4B211_INPUT_TOKENS",
    "HISTORICAL_4B211_REASONING_TOKENS",
    "HISTORICAL_4B211_STATUS",
    "HISTORICAL_H01_STATUS",
    "HISTORICAL_H02_STATUS",
    "HISTORICAL_H11_STATUS",
    "INTEGRATION_CONTRACT_ACTIVATED",
    "INTEGRATION_CONTRACT_VERSION",
    "INTERRUPTION_POINTS",
    "INTERRUPT_AFTER_BLOCK",
    "INTERRUPT_AFTER_GENERATION",
    "INTERRUPT_AFTER_PASS",
    "INTERRUPT_AFTER_REVIEW",
    "INTERRUPT_BEFORE_VALIDATION",
    "INTERRUPT_DURING_VALIDATION",
    "ISOLATED_CACHE_STATES",
    "ISOLATED_CACHE_VERSION",
    "NEXT_ACTION",
    "NOT_SONNET",
    "NOT_TERRA",
    "OFFSET_CONVENTION",
    "OFFSET_CONVENTION_NOTES",
    "PHASE",
    "PHASE5_INTERFACE_VERSION",
    "PHASE_NAME",
    "PREPARATION_ALGORITHM_VERSION",
    "PRODUCTION_CACHE_ACCEPTANCE",
    "PRODUCTION_PIPELINE_HOOK",
    "PROJECT_NAME",
    "PROMPT_VERSION_20_ACTIVATED",
    "PROMPT_VERSION_20_CANDIDATE",
    "PROMPT_VERSION_201_ACTIVATED",
    "PROMPT_VERSION_201_CANDIDATE",
    "PROMPT_VERSION_202_ACTIVATED",
    "PROMPT_VERSION_202_CANDIDATE",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_CONTROLLED_INTEGRATION_HUMAN_REVIEW",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "READY_FOR_ONE_REAL_CHAPTER_EXPERIMENT",
    "REAL_CHAPTER_GENERATION_AUTHORIZED",
    "REPORT_NAME",
    "RETRIES",
    "SDK_MAX_RETRIES",
    "SEMANTIC_GATE_20_ENABLED",
    "SEMANTIC_GATE_201_ENABLED",
    "SEMANTIC_GATE_202_ENABLED",
    "SONNET_EXECUTION_AUTHORIZED",
    "SYNTHETIC_EDITORIAL_PLAN_HASH",
    "SYNTHETIC_PREFIX",
    "SYNTHETIC_SOURCE_MAP_HASH",
    "TERRA_EXECUTION_AUTHORIZED",
    "TRANSPORT_VERSION_20_ACTIVATED",
    "TRANSPORT_VERSION_20_CANDIDATE",
    "VALIDATOR_IMPLEMENTATION_VERSION",
]
