"""Rapport déterministe 3B.7.7A.3."""

from __future__ import annotations

from typing import Any, Mapping

from app.source_analysis.window_granularity import (
    HARD_CEILINGS,
    IDEA_HARD_CEILING,
    RELATION_HARD_CEILING,
    SOFT_TARGETS,
    TOTAL_HARD_CEILING,
)
from app.source_analysis_bounded_win001_retry_readiness.constants import (
    DRY_RUN_COMMAND,
    FUTURE_REAL_COMMAND,
    HISTORICAL_SPEND_USD,
    NEXT_ACTION,
    NEXT_PHASE_LABEL,
    PHASE,
    REAL_PROVIDER_CALLS_THIS_PHASE,
    WIN001_RETRIED,
)


def _yn(value: bool) -> str:
    return "YES" if value else "NO"


def render_report(payload: Mapping[str, Any]) -> str:
    request = payload["request"]
    cache = payload["cache"]
    collision = payload["collision"]
    cost = payload["cost_risk"]
    study = payload["size_study"]
    dry = payload["dry_run"]
    facts = payload["implementation"]
    prompts = payload["prompts"]
    generation = payload["generation_c"]
    state = payload["project_state"]
    max_valid = study["max_policy_valid_local_tokens"]
    ratio_tokens = cost["input_scenarios"]["HISTORICAL_RATIO"]["tokens"]
    local = request["local_estimated_input"]
    readiness = payload["readiness"]
    result = payload["result"]
    lines = [
        f"# PHASE {PHASE} — BOUNDED WIN001 RETRY READINESS & COST/RISK REVIEW",
        "",
        "## Result",
        "",
        result,
        "",
        f"READINESS = {readiness}",
        "",
        f"REAL PROVIDER CALLS THIS PHASE = {REAL_PROVIDER_CALLS_THIS_PHASE}",
        "",
        f"WIN001 RETRIED = {_yn(WIN001_RETRIED)}",
        "",
        "WINDOW = WIN001",
        "",
        f"PROMPT = {request['prompt_version']}",
        "",
        f"PROMPT SIGNATURE = {request['window_signature']}",
        "",
        f"TRANSPORT = {request['transport_version']}",
        "",
        f"LOCAL INPUT ESTIMATE = {local}",
        "",
        "HISTORICAL PROVIDER RATIO = 2.155975 OBSERVATION ONLY",
        "",
        f"HISTORICAL-RATIO INPUT SCENARIO = {ratio_tokens}",
        "",
        f"MAX OUTPUT = {request['max_output']}",
        "",
        f"MAX-POLICY-VALID STRUCTURAL OUTPUT = {max_valid} local estimated tokens",
        "",
        f"TOTAL HARD RECORD CEILING = {TOTAL_HARD_CEILING}",
        "",
        f"IDEA HARD CEILING = {IDEA_HARD_CEILING}",
        "",
        f"RELATION HARD CEILING = {RELATION_HARD_CEILING}",
        "",
        "TIMEOUT = 30 / 1800",
        "",
        "MAX NEW CALLS FOR FUTURE AUTHORIZATION = 1",
        "",
        "MAX ATTEMPTS = 1",
        "",
        "AUTO RETRY = NO",
        "",
        "FORENSIC PRESERVATION = "
        + ("READY" if collision["collision_safe"] else "BLOCKED"),
        "",
        f"CURRENT 1.1 CACHE = {cache['WIN001_1_1']['cache_state']}",
        "",
        f"HISTORICAL SPEND = USD {HISTORICAL_SPEND_USD}",
        "",
        "POTENTIAL NEW SPEND = SCENARIO RANGE, NOT PREDICTION",
        "",
        "SOURCE MAP = NOT PUBLISHED"
        if not payload["source_map_published"]
        else "SOURCE MAP = PRESENT",
        "",
        "PROJECT STATE = "
        f"{state.get('project_state_status') or 'unknown'} / "
        f"{state.get('project_state_error') or 'n/a'}",
        "",
        "PHASE 3B = INCOMPLETE",
        "",
        f"NEXT ACTION = {NEXT_ACTION}",
        "",
        "## 1. Result",
        "",
        f"{result}. Offline readiness only. No provider call. No WIN001 retry.",
        f"READINESS = {readiness}.",
        "",
        "## 2. Objective",
        "",
        "Determine whether a second paid WIN001 canary is technically justified",
        "under window-analysis-1.1. This phase does not execute it.",
        "",
        "## 3. Baseline",
        "",
        f"Baseline pytest: {payload['baseline']['passed']} passed, "
        f"{payload['baseline']['failed']} failed.",
        "",
        "## 4. Historical WIN001 call",
        "",
        "window-analysis-1.0. One paid call. FAIL controlled.",
        "1 engine.generate, 1 Anthropic POST, 0 retries.",
        "provider input_tokens = 106973; output_tokens = 32000 = ceiling.",
        "Proximate failure: AIStructuredOutputError after HTTP success.",
        "Not reinterpreted. Remains historical evidence.",
        "",
        "## 5. Historical spend",
        "",
        f"USD {HISTORICAL_SPEND_USD}. HISTORICAL SPEND only. Not future budget.",
        "",
        "## 6. 3B.7.7A.1 findings",
        "",
        "Raw provider content existed then was discarded. stop_reason not",
        "persisted. Output reached configured ceiling. Input ratio 2.155975",
        "observation only. Future structured-output failures now preserve",
        "forensic evidence.",
        "",
        "## 7. 3B.7.7A.2 bounded design",
        "",
        "Successor prompt window-analysis-1.1. Transport unchanged.",
        "Generation C unchanged. max_output 32000 unchanged. 3 windows.",
        f"Total hard 160. Idea soft 40 / hard 64. Relation hard 36.",
        f"MAX_POLICY_VALID = {max_valid} local tokens.",
        "",
        "## 8. Current implementation",
        "",
        f"Production default prompt = {request['prompt_version']}.",
        f"Bounded canary scope resolves 1.1 = {_yn(facts['bounded_prompt_resolves_to_1_1'])}.",
        f"Historical WIN001_ONLY remains 1.0 = {_yn(facts['historical_win001_only_resolves_to_1_0'])}.",
        "",
        "## 9. Runner version selection",
        "",
        "Historical dry-run WIN001_ONLY stays window-analysis-1.0.",
        "BOUNDED_WIN001_ONLY requires window-analysis-1.1 and fails closed.",
        "Real provider execute without 1.1 / BOUNDED scope is rejected.",
        f"Dry-run prompt = {dry.get('prompt_version')}.",
        f"Dry-run policy = {dry.get('granularity_policy_version')}.",
        "",
        "## 10. Prompt 1.0 integrity",
        "",
        f"SHA = {prompts['historical_sha256']}.",
        f"Byte-identical across calls = {_yn(prompts['historical_byte_identical_across_calls'])}.",
        "",
        "## 11. Prompt 1.1 integrity",
        "",
        f"SHA = {prompts['successor_sha256']}.",
        f"Matches accepted 3B.7.7A.2 = {_yn(facts['prompt_1_1_matches_accepted_3b77a2'])}.",
        "",
        "## 12. Prompt signature",
        "",
        f"1.0 = {request['historical_signature']}",
        f"1.1 = {request['window_signature']}",
        f"Differ = {_yn(request['signatures_differ'])}.",
        "",
        "## 13. Cache identity",
        "",
        "Cache identity is WindowAnalysisSignature. Prompt version and SHA",
        "are inputs. 1.1 cannot HIT a 1.0 result.",
        "",
        "## 14. Cache status",
        "",
        f"WIN001 1.0 result present = {_yn(cache['WIN001_1_0']['result_present'])} "
        f"(failed historical call evidence; valid cache HIT = "
        f"{_yn(cache['WIN001_1_0']['valid_cache_entry'])}).",
        f"WIN001 1.1 = {cache['WIN001_1_1']['cache_state']}.",
        f"WIN002 = {cache['WIN002']['cache_state']}.",
        f"WIN003 = {cache['WIN003']['cache_state']}.",
        f"Matches expected MISS table = {_yn(cache['matches_expected'])}.",
        "",
        "## 15. Artifact collision audit",
        "",
        "Production path remains analysis/windows/WIN001/{transport,result,metadata}.json.",
        "1.0 transport/result absent. Audit 3B.7.7A evidence lives under audit/.",
        "Signature-aware cache treats a different prompt as STALE, not HIT.",
        f"Overwrite risk of 1.0 production evidence = "
        f"{_yn(collision['overwrite_risk_production_1_0_evidence'])}.",
        f"Overwrite risk of 3B.7.7A audit = {_yn(collision['overwrite_risk_audit_3b77a'])}.",
        "",
        "## 16. Forensic collision audit",
        "",
        "Forensics are now keyed by WIN001/<analysis_signature>/.",
        "A future 1.1 failure cannot overwrite a different signature.",
        "Identity is the deterministic analysis signature, not a random id.",
        f"Collision safe = {_yn(collision['collision_safe'])}.",
        "",
        "## 17. Exact bounded request",
        "",
        f"stage = {request['stage']}",
        f"provider = {request['provider']}",
        f"model = {request['model']}",
        f"prompt version = {request['prompt_version']}",
        f"prompt SHA = {request['prompt_sha256']}",
        f"schema version = {request['schema_version']}",
        f"schema SHA = {request['schema_sha256']}",
        f"window signature = {request['window_signature']}",
        f"system chars = {request['system_chars']}",
        f"user chars = {request['user_chars']}",
        f"combined chars = {request['combined_chars']}",
        f"local estimated input = {local}",
        f"payload bytes = {request['payload_bytes']}",
        f"temperature = {request['temperature']}",
        f"output language = {request['output_language']}",
        f"max output = {request['max_output']}",
        f"connect timeout = {request['connect_timeout_seconds']}",
        f"read timeout = {request['read_timeout_seconds']}",
        f"max attempts = {request['max_attempts']}",
        "",
        "## 18. Local input estimate",
        "",
        f"{local}. Within hard max {request['hard_max_local']} = "
        f"{_yn(request['within_hard_max'])}.",
        "",
        "## 19. Historical provider ratio",
        "",
        "106973 / 49617 = 2.155975. OBSERVATION ONLY. Not a calibrated tokenizer.",
        "",
        "## 20. Input scenarios",
        "",
        f"LOCAL ESTIMATE = {local} SCENARIO NOT PREDICTION.",
        f"HISTORICAL-RATIO = {ratio_tokens} SCENARIO NOT PREDICTION.",
        f"STRESS 2.5X = {cost['input_scenarios']['STRESS_2_5X']['tokens']} "
        "SCENARIO NOT PREDICTION.",
        "",
        "## 21. Context capacity",
        "",
        f"usable_context = {cost['context']['usable_context']}.",
        f"historical-ratio fits usable = {_yn(cost['context']['historical_ratio_fits_usable'])}.",
        "Input context overflow is not the primary retry risk.",
        "",
        "## 22. Long-context threshold",
        "",
        f"Phase 2B protocol threshold = {cost['long_context']['threshold_protocol']}.",
        f"Historical-ratio crosses 272k = "
        f"{_yn(cost['long_context']['historical_ratio_crosses_threshold'])}.",
        "",
        "## 23. Input cost scenarios",
        "",
        f"LOCAL ESTIMATE USD {cost['input_cost_scenarios']['LOCAL_ESTIMATE']['usd']} "
        "SCENARIO.",
        f"HISTORICAL-RATIO USD {cost['input_cost_scenarios']['HISTORICAL_RATIO']['usd']} "
        "SCENARIO.",
        "",
        "## 24. Output policy",
        "",
        "max_output remains 32000. Semantic policy constrains expected output.",
        "Local validator enforces hard limits. Overflow signals capacity.",
        "32k is transport headroom, not a target.",
        "",
        "## 25. MAX_POLICY_VALID evidence",
        "",
        f"Recomputed = {max_valid} local estimated tokens "
        f"({study['percent_of_32000']}% of 32000).",
        f"Safety margin = {study['safety_margin_tokens']} tokens.",
        "",
        "## 26. Output cost scenarios",
        "",
    ]
    for tokens, row in cost["output_cost_scenarios"].items():
        lines.append(f"{tokens} tokens = USD {row['usd']} SCENARIO.")
    lines.extend(
        [
            "",
            "## 27. Total cost matrix",
            "",
            "Input rows: LOCAL_ESTIMATE, HISTORICAL_RATIO, STRESS_2_5X.",
            "Output columns: 8000, 13023, 16000, 20000, 32000.",
            "No cell is expected actual cost.",
            "",
        ]
    )
    for in_name, outs in cost["total_cost_matrix"].items():
        for out_name, cell in outs.items():
            lines.append(f"{in_name} × {out_name} = USD {cell['usd']} SCENARIO.")
    lines.extend(
        [
            "",
            "## 28. Granularity policy",
            "",
            f"Version = {facts['granularity_policy']['policy_version']}.",
            "Active on the 1.1 analyze_window path. Soft targets are prompt-only.",
            "Hard ceilings are locally enforced.",
            "",
            "## 29. Topic limits",
            "",
            f"TOPIC soft {SOFT_TARGETS['TOPIC']} / hard {HARD_CEILINGS['TOPIC']}.",
            "",
            "## 30. Idea limits",
            "",
            f"IDEA soft {facts['idea_soft_target']} / hard {facts['idea_hard_ceiling']}.",
            "Soft exceedance alone does not fail if below hard ceiling.",
            "",
            "## 31. Relation limits",
            "",
            f"RELATION soft {SOFT_TARGETS['RELATION']} / hard {facts['relation_hard_ceiling']}.",
            "Prompt forbids exhaustive pairwise relations. Validator caps at 36.",
            "",
            "## 32. Other kind limits",
            "",
        ]
    )
    for kind in (
        "EXAMPLE",
        "REFERENCE",
        "UNCERTAINTY",
        "REPETITION",
        "VOICE",
        "INTENT_KIND",
        "AUDIENCE_KIND",
    ):
        lines.append(
            f"{kind} soft {SOFT_TARGETS[kind]} / hard {HARD_CEILINGS[kind]}."
        )
    lines.extend(
        [
            "",
            "## 33. Total limit",
            "",
            f"{TOTAL_HARD_CEILING} applies to len(records) of every kind,",
            "including VOICE, INTENT_KIND, AUDIENCE_KIND, RELATION, and overflow",
            "UNCERTAINTY if present. Root theme/intent/aud are not records.",
            "Record metadata items do not count as records.",
            "",
            "## 34. Text-size policy",
            "",
            "Hard character limits. Reject if exceeded. No Python truncation.",
            "",
            "## 35. Source-ref volume",
            "",
            f"MAX_POLICY_VALID refs by kind = {facts['source_ref_volume']['refs_by_kind']}.",
            f"Largest kind total = {facts['source_ref_volume']['largest_kind_total_refs']}.",
            f"Per-record hard max = {facts['source_refs_hard_max']}.",
            "",
            "## 36. Overflow signal",
            "",
            "UNCERTAINTY.v == analysis_capacity_exceeded.",
            "",
            "## 37. Overflow validation",
            "",
            "WindowSemanticCapacityExceeded. NOT READY. Result not promoted.",
            "Authorized call consumed. No automatic retry.",
            "",
            "## 38. Over-limit behavior",
            "",
            "Valid transport above hard limit: transport persisted, result absent,",
            "WIN001 not READY, no retry.",
            "",
            "## 39. Silent omission prohibition",
            "",
            "Prompt forbids silently stopping to stay below ceilings.",
            "Faithful overflow requires the capacity signal.",
            "",
            "## 40. Generation C",
            "",
            f"Unchanged = {_yn(generation['unchanged'])}.",
            f"raw = {generation['raw_sha256']}.",
            f"anthropic = {generation['anthropic_sha256']}.",
            "",
            "## 41. Grammar status",
            "",
            "Generation C was previously server accepted. Prompt-only change.",
            "No new grammar canary required. None called.",
            "",
            "## 42. Structured-output forensics",
            "",
            "3B.7.7A.1 hardening is on the 1.1 analyze_window path.",
            "AIStructuredOutputError persists usage, finish_reason, request_id,",
            "parse kind, raw SHA256, raw size, and raw text. No secrets.",
            "",
            "## 43. Stop-reason preservation",
            "",
            "finish_reason is persisted when the provider supplies it.",
            "",
            "## 44. Raw-response preservation",
            "",
            "Raw failed content is written before the exception escapes.",
            "No JSON repair. No transport/result fabrication.",
            "",
            "## 45. Parse classification",
            "",
            "empty / json_decode / schema where the parser exposes them.",
            "",
            "## 46. One-call safety",
            "",
            "AUTHORIZATION_SCOPE = BOUNDED_WIN001_ONLY. MAX_NEW_CALLS = 1.",
            "AUTO_* all false. Plan restricted to WIN001.",
            "",
            "## 47. Max attempts",
            "",
            "Canary engine retry_policy.max_attempts = 1.",
            "Does not use get_engine_for_stage() (would inherit AI_MAX_ATTEMPTS=3).",
            "",
            "## 48. HTTP retry audit",
            "",
            f"hidden HTTP POST retry = {_yn(facts['retry_audit']['hidden_http_post_retry'])}.",
            f"canary retry safe = {_yn(facts['retry_audit']['canary_retry_safe'])}.",
            "One engine.generate = at most one Anthropic POST.",
            "",
            "## 49. Timeout",
            "",
            "connect 30 / read 1800. First call completed in ~256 s.",
            "No 7200 leak. No timeout redesign around the 3B.7.7A failure.",
            "",
            "## 50. Dry run",
            "",
            f"accepted = {_yn(bool(dry.get('accepted')))}.",
            f"prompt = {dry.get('prompt_version')}.",
            f"signature = {dry.get('analysis_signature')}.",
            f"cache = {dry.get('cache_state')}.",
            f"local estimate = {dry.get('estimated_input_tokens')}.",
            f"max output = {dry.get('max_output_tokens')}.",
            f"policy = {dry.get('granularity_policy_version')}.",
            f"timeout = {dry.get('connect_timeout_seconds')}/{dry.get('read_timeout_seconds')}.",
            f"max attempts = {dry.get('max_attempts')}.",
            f"execution = {_yn(bool(dry.get('execution')))}.",
            f"provider calls = {dry.get('provider_calls', 0)}.",
            "",
            "## 51. Exact dry-run command",
            "",
            DRY_RUN_COMMAND,
            "",
            "## 52. Exact future real command",
            "",
            FUTURE_REAL_COMMAND,
            "",
            "NOT EXECUTED.",
            "",
            "## 53. FakeAI bounded runner",
            "",
            "Covered by tests: BOUNDED_WIN001_ONLY + 1.1, one window, READY,",
            "one FakeAI call, no WIN002/WIN003, no consolidation, no source_map.",
            "",
            "## 54. FakeAI capacity",
            "",
            "Covered by tests: NOT READY, one call, no retry, transport retained,",
            "result absent.",
            "",
            "## 55. FakeAI over-limit",
            "",
            "Covered by tests: transport retained, result absent, no retry.",
            "",
            "## 56. Fake parse-forensics test",
            "",
            "Covered by tests: signature-keyed forensic evidence preserved.",
            "No network.",
            "",
            "## 57. Future success criteria",
            "",
            "Exactly one Anthropic POST. Provider response. Transport persisted.",
            "Structured parse succeeds. Bounded validation succeeds. No overflow.",
            "WindowResultValidator passes. Result persisted. 1.1 cache HIT.",
            "Usage/cost captured. stop_reason captured if provided.",
            "Semantic human review finds no blocker.",
            "",
            "## 58. Future output review",
            "",
            "Compare actual output tokens to 13023 study and 32000 ceiling.",
            "Do not require output <= 13023. Report structure/counts + stop_reason.",
            "",
            "## 59. Failure: ceiling",
            "",
            "If output_tokens == 32000 and parse fails or stop_reason is max tokens:",
            "STOP. Do not authorize a third WIN001 call.",
            "",
            "## 60. Failure: capacity",
            "",
            "If analysis_capacity_exceeded: STOP. Consider smaller semantic windows",
            "in a later architecture review. No immediate retry.",
            "",
            "## 61. Failure: over-limit",
            "",
            "If provider ignores policy and exceeds hard semantic limits:",
            "transport preserved, result rejected, STOP. Do not raise limits.",
            "",
            "## 62. Failure: parse",
            "",
            "If parse fails, stop_reason is not max_tokens, and output is below",
            "ceiling: diagnose from preserved raw forensics before any further call.",
            "",
            "## 63. Failure: timeout/HTTP",
            "",
            "Fail closed. No retry.",
            "",
            "## 64. Human review gate",
            "",
            "Even READY_FOR_BOUNDED_WIN001_CANARY does not execute.",
            "New human authorization is mandatory.",
            "",
            "## 65. WIN002/WIN003 prohibition",
            "",
            "Even future PASS: STOP. No automatic continuation.",
            "",
            "## 66. Consolidation prohibition",
            "",
            "Unauthorized. Auto consolidation = false.",
            "",
            "## 67. SourceMap prohibition",
            "",
            f"source_map present = {_yn(payload['source_map_published'])}.",
            "",
            "## 68. Project state",
            "",
            f"status = {state.get('project_state_status')}.",
            f"error = {state.get('project_state_error')}.",
            "Not SUCCESS. Not changed.",
            "",
            "## 69. Risk register",
            "",
            "1. Input token accounting mismatch — evidence: 2.155975 observation.",
            "   Impact: billed input higher than local estimate. Mitigation:",
            "   treat as scenario; usable context still large. STOP: none for input.",
            "2. Provider may ignore semantic soft targets — impact: denser output.",
            "   Mitigation: local hard ceilings. STOP if over-limit or overflow.",
            "3. Provider may still hit 32000 output ceiling — impact: parse fail.",
            "   Mitigation: 1.1 bounding + forensics. STOP. No third call.",
            "4. Structured parser may fail below ceiling — impact: lost result.",
            "   Mitigation: raw forensic retain. STOP for diagnosis.",
            "5. Semantic capacity may genuinely exceed policy — impact: NOT READY.",
            "   Mitigation: overflow signal. STOP. Architecture review later.",
            "6. Forensic path collision — mitigated: signature-keyed directories.",
            "7. Hidden retry — mitigated: max_attempts=1, no Session retry.",
            "8. Artifact collision — mitigated: 1.0 result absent; audit disjoint;",
            "   cache signature-aware.",
            "",
            "## 70. Technical information value",
            "",
            "One future call would answer: does 1.1 prevent output explosion?",
            "Does structured response complete? Actual provider input accounting?",
            "Actual output tokens? Actual stop_reason? Does bounded transport",
            "validate? Is semantic quality acceptable?",
            "",
            "## 71. Readiness blockers",
            "",
        ]
    )
    for name, value in facts["blockers"].items():
        lines.append(f"- {name} = {_yn(bool(value))}")
    lines.extend(
        [
            "",
            "## 72. Tests",
            "",
            "Baseline 2340 plus new 3B.7.7A.3 tests. Expected 0 failed.",
            "",
            "## 73. Network",
            "",
            "0.",
            "",
            "## 74. Protected artifacts",
            "",
            "Hashed through 3B.7.7A.2. Byte-identical if this phase did not rewrite them.",
            "",
            "## 75. CLEAN integrity",
            "",
            f"present = {_yn(bool(payload['clean']['present']))}. Not rewritten.",
            f"sha256 = {payload['clean']['sha256']}.",
            "",
            "## 76. Files added",
            "",
            "- app/source_analysis_bounded_win001_retry_readiness/",
            "- app/tests/test_source_analysis_bounded_win001_retry_readiness.py",
            "",
            "## 77. Files modified",
            "",
            "- app/ai/structured_forensics.py (signature-keyed forensic path)",
            "- app/source_analysis/window_analyzer.py (pass analysis_signature)",
            "- app/source_analysis_hybrid_readiness/canary.py (1.1 fail-closed)",
            "- app/source_analysis_hybrid_readiness/canary_cli.py",
            "- app/source_analysis_hybrid_readiness/constants.py",
            "- app/tests/test_source_analysis_win001_failure_diagnosis.py",
            "",
            "## 78. Final readiness decision",
            "",
            f"READINESS = {readiness}.",
            "STOP. Do not execute. Wait for explicit human authorization.",
            f"Next phase if authorized: {NEXT_PHASE_LABEL}.",
            "",
        ]
    )
    return "\n".join(lines)
