"""
Phase 4B.2.32 — remove interchapter blank pages created by ODD_PAGE starts.

STRICTLY OFFLINE. Zero provider calls. Zero USD.
Presentation correction only. book.json and chapter sources stay immutable.
print-review-v1 is preserved. Output is print-review-v1.1.
"""

from __future__ import annotations

from app.book_print_review_canonical_4b229.constants import (
    ACCEPTED_CHAPTER_COUNT,
    ACCEPTED_CHAPTER_IDS,
    AUTHORIZATION_SCOPE as CONSUMED_4B229_SCOPE,
    BOOK_STATUS,
    BOOK_TITLE,
    BOOK_VERSION,
    CANONICAL_CHAPTER_IDS,
    EXPECTED_IDEA_COUNT,
    EXPECTED_SECTION_COUNT,
    PENDING_CHAPTER_IDS,
    PROJECT_NAME,
    REMAINING_CHAPTER_COUNT,
)
from app.book_print_review_render_4b231.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B231_SCOPE,
    EXPECTED_BOOK_SHA256 as RENDER_BOOK_SHA256,
)
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE
from app.word_print_profile_4b230.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B230_SCOPE,
)
from app.word_renderer.constants import PROFILE_NAME

PHASE = "4B.2.32"
PHASE_NAME = "INTERCHAPTER_BLANK_PAGE_REMOVAL"

assert PROJECT_NAME == "pastoral_retreat_v2_validation"
assert BOOK_TITLE == "The Life You Already Inherited"
assert BOOK_VERSION == "print-review-v1"
assert BOOK_STATUS == "DRAFT_FOR_PRINT_REVIEW"

AUTHORIZATION_SCOPE = "BOOK_PRINT_REVIEW_PAGINATION_FIX_4B232_NEXT_PAGE_ONLY"

AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_TERRA_CALLS = 0
MAX_ENGINE_GENERATE = 0
MAX_ANTHROPIC_POST = 0
MAX_HTTP_REQUESTS = 0

DOCX_GENERATION_AUTHORIZED = True
PDF_GENERATION_AUTHORIZED = True
COVER_GENERATION_AUTHORIZED = False
VISUAL_DIRECTION_AUTHORIZED = False
FINAL_PUBLICATION_AUTHORIZED = False
COMMERCIAL_PUBLICATION_AUTHORIZED = False
PUBLIC_PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
OPENAI_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = False
REAL_CHAPTER_GENERATION_AUTHORIZED = False
BOOK_JSON_MUTATION_AUTHORIZED = False
PUBLICATION_STATUS = "PRINT_REVIEW_ONLY"

EXPECTED_BOOK_SHA256 = (
    "adde6e2344f4b94da0f7df183341885574e89abc90781c426459e850cc2b6550"
)
assert EXPECTED_BOOK_SHA256 == RENDER_BOOK_SHA256

EXPECTED_CHAPTER_COUNT = 19
EXPECTED_PARAGRAPH_COUNT = 335
EXPECTED_TRANSITION_COUNT = 18
EXPECTED_FRONT_MATTER_PAGE_BREAKS = 2
EXPECTED_HUMAN_ACCEPTED = ACCEPTED_CHAPTER_COUNT
EXPECTED_STRUCTURAL = REMAINING_CHAPTER_COUNT
ORIGINAL_PDF_PAGE_COUNT = 80
ORIGINAL_INTERCHAPTER_BLANK_PAGES = 18
ORIGINAL_CHAPTER1_PHYSICAL_PAGE = 5
ORIGINAL_FRONT_MATTER_PAGE_COUNT = 4
CHAPTER_BREAK_POLICY = "NEXT_PAGE"
SOURCE_VERSION = "print-review-v1"
OUTPUT_VERSION = "print-review-v1.1"

assert EXPECTED_CHAPTER_COUNT == 19
assert EXPECTED_SECTION_COUNT == 72
assert EXPECTED_PARAGRAPH_COUNT == 335
assert EXPECTED_TRANSITION_COUNT == 18
assert EXPECTED_IDEA_COUNT == 286
assert EXPECTED_HUMAN_ACCEPTED == 6
assert EXPECTED_STRUCTURAL == 13
assert len(CANONICAL_CHAPTER_IDS) == 19
assert len(ACCEPTED_CHAPTER_IDS) == 6
assert len(PENDING_CHAPTER_IDS) == 13

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
CODE_VERSION = "app.book_print_review_pagination_fix_4b232"
PRINT_PROFILE = PROFILE_NAME
PRINT_FORMAT = "6 × 9 inches"
BOOK_SLUG = "The_Life_You_Already_Inherited_print_review_v1_1"
DOCX_FILENAME = f"{BOOK_SLUG}.docx"
PDF_FILENAME = f"{BOOK_SLUG}.pdf"
UNFINALIZED_DOCX_FILENAME = f"{BOOK_SLUG}_before_finalization.docx"
WORKING_DOCX_FILENAME = f"{BOOK_SLUG}_word_working.docx"
ORIGINAL_BOOK_SLUG = "The_Life_You_Already_Inherited_print_review_v1"
ORIGINAL_DOCX_FILENAME = f"{ORIGINAL_BOOK_SLUG}.docx"
ORIGINAL_PDF_FILENAME = f"{ORIGINAL_BOOK_SLUG}.pdf"

AUDIT_DIRNAME = "book_print_review_pagination_fix_4b232"
PUBLICATION_REL = f"sortie/{PROJECT_NAME}/publication/print_review_v1_1"
ORIGINAL_PUBLICATION_REL = f"sortie/{PROJECT_NAME}/publication/print_review_v1"
AUDIT_POLICY = "chapter_break_policy_before_after.json"
AUDIT_TRANSITIONS = "chapter_transition_validation.json"
AUDIT_FRONT_MATTER = "front_matter_comparison.json"
AUDIT_INTEGRITY = "docx_integrity_validation.json"
AUDIT_PDF = "pdf_integrity_validation.json"
AUDIT_TOC = "toc_pagination_validation.json"
AUDIT_HASHES = "canonical_hashes_pre_post.json"
AUDIT_PUBLICATION = "publication_manifest.json"
AUDIT_TESTS = "offline_tests.json"
REPORT_NAME = "PHASE_4B232_INTERCHAPTER_BLANK_PAGE_REMOVAL_REPORT.md"

NEXT_ACTION_PASS = (
    "STOP. DO NOT MODIFY CHAPTERS. DO NOT GENERATE NEW CONTENT. "
    "DO NOT MODIFY book.json. DO NOT GENERATE A COVER. DO NOT CALL "
    "ANTHROPIC. DO NOT CALL OPENAI. DO NOT CALL TERRA. DO NOT LAUNCH "
    "A NEW PHASE WITHOUT INSTRUCTION."
)
NEXT_ACTION_PARTIAL = (
    "KEEP THE UNFINALIZED DOCX. OPEN IT IN MICROSOFT WORD, UPDATE FIELDS "
    "AND THE TABLE OF CONTENTS, STABILIZE PAGINATION, EXPORT A PRINT PDF, "
    "THEN RE-RUN VERIFICATION. DO NOT MODIFY CHAPTERS. DO NOT MODIFY "
    "book.json. DO NOT GENERATE A COVER. DO NOT OVERWRITE print-review-v1."
)
NEXT_ACTION_FAIL = (
    "STOP. DO NOT PUBLISH print-review-v1.1. DO NOT OVERWRITE "
    "print-review-v1. DO NOT MODIFY CHAPTERS. DO NOT MODIFY book.json."
)

assert AUTHORIZED_ANTHROPIC_CALLS == 0
assert AUTHORIZED_OPENAI_CALLS == 0
assert AUTHORIZED_TERRA_CALLS == 0
assert DOCX_GENERATION_AUTHORIZED is True
assert PDF_GENERATION_AUTHORIZED is True
assert FINAL_PUBLICATION_AUTHORIZED is False
assert BOOK_JSON_MUTATION_AUTHORIZED is False
assert COVER_GENERATION_AUTHORIZED is False
assert CANONICAL_PYTHON.endswith("python.exe")
assert CONSUMED_4B229_SCOPE.startswith("BOOK_PRINT_REVIEW_CANONICAL_4B229_")
assert CONSUMED_4B230_SCOPE.startswith("BOOK_WORD_PRINT_PROFILE_4B230_")
assert CONSUMED_4B231_SCOPE.startswith("BOOK_PRINT_REVIEW_RENDER_4B231_")

__all__ = [
    "AUTHORIZATION_SCOPE",
    "BOOK_STATUS",
    "BOOK_TITLE",
    "BOOK_VERSION",
    "CHAPTER_BREAK_POLICY",
    "EXPECTED_BOOK_SHA256",
    "EXPECTED_PARAGRAPH_COUNT",
    "EXPECTED_TRANSITION_COUNT",
    "OUTPUT_VERSION",
    "PHASE",
    "PRINT_PROFILE",
    "PROJECT_NAME",
    "PUBLICATION_STATUS",
    "REPORT_NAME",
    "SOURCE_VERSION",
]
