"""Generate the v1.1 print-review DOCX. No invented editorial matter."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from app.book_print_review_pagination_fix_4b232.constants import (
    BOOK_STATUS,
    BOOK_VERSION,
    OUTPUT_VERSION,
    PHASE,
    PRINT_PROFILE,
    PUBLICATION_STATUS,
    SOURCE_VERSION,
)
from app.book_print_review_pagination_fix_4b232.hashes import file_sha256
from app.word_renderer.document import build_print_document, serialize_in_memory
from app.word_renderer.mapping import PrintBook


def build_docx_bytes(book: PrintBook, profile: dict[str, Any]) -> bytes:
    doc = build_print_document(book, profile)
    doc.core_properties.title = book.title
    doc.core_properties.author = ""
    doc.core_properties.subject = (
        f"Print review draft — {SOURCE_VERSION} presentation correction {OUTPUT_VERSION}"
    )
    doc.core_properties.category = PUBLICATION_STATUS
    doc.core_properties.comments = (
        f"{BOOK_STATUS}. Not for publication. Generated by {PHASE}. "
        f"Canonical version remains {BOOK_VERSION}."
    )
    return serialize_in_memory(doc)


def write_docx_bytes(path: Path, data: bytes) -> dict[str, Any]:
    from app.book_print_review_pagination_fix_4b232.writer import write_binary_atomic

    target = write_binary_atomic(path, data)
    hashed = file_sha256(target)
    return {
        "path": hashed.get("path"),
        "sha256": hashed.get("sha256"),
        "bytes": hashed.get("bytes"),
        "exists": hashed.get("exists"),
    }


def generation_manifest(
    *,
    book: PrintBook,
    profile: dict[str, Any],
    unfinalized: dict[str, Any],
    book_sha256: str,
) -> dict[str, Any]:
    chapter = profile.get("chapter") or {}
    body = (profile.get("pagination") or {}).get("body") or {}
    front = (profile.get("pagination") or {}).get("front_matter") or {}
    return {
        "phase": PHASE,
        "engine": "app.word_renderer.document.build_print_document",
        "profile_id": profile.get("profile_id") or PRINT_PROFILE,
        "book_title": book.title,
        "book_version": book.version,
        "output_version": OUTPUT_VERSION,
        "book_status": book.status,
        "book_sha256": book_sha256,
        "chapter_count": book.chapter_count,
        "section_count": book.section_count,
        "paragraph_count": len(book.paragraph_texts),
        "chapter_start": body.get("chapter_start") or chapter.get("start"),
        "front_matter_section_start": front.get("section_start"),
        "unfinalized_docx": unfinalized,
        "invented_front_matter": False,
        "provider_calls": 0,
        "verification": "automatic",
        "secrets_included": False,
    }


__all__ = ["build_docx_bytes", "generation_manifest", "write_docx_bytes"]
