"""Constantes 3B.7.7A.10 — revue offline. 0 appel provider."""

from __future__ import annotations

from app.source_analysis_provider_boundary.constants import (
    CALL1_SIGNATURE,
    CALL2_SIGNATURE,
    CLEAN_SHA,
    GENERATION_C_ANTHROPIC_SHA,
    GENERATION_C_RAW_SHA,
    PROMPT_10_SHA,
    PROMPT_11_SHA,
)
from app.source_analysis_small_window_hierarchy.constants import (
    CANDIDATE_PLANNER_VERSION,
)
from app.source_analysis_win001_failure_diagnosis.constants import (
    OBSERVED_COST_USD,
    OBSERVED_LOCAL_ESTIMATE,
    OBSERVED_PROVIDER_INPUT,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.10"
MODE = "OFFLINE_OUTPUT_CEILING_ARCHITECTURE_REVIEW"
PROJECT_NAME = "pastoral_retreat_v2_validation"
WINDOW_ID = "WIN001"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
NEW_WIN001_CALLS = 0
REAL_PROVIDER_CALL_AUTHORIZED_NEXT = False

SMALL_SIGNATURE = (
    "e97e2bb15f2b71e436e256477014d6826e4586b549f710273975c6a9c6fd6802"
)
SMALL_RAW_TEXT_SHA = (
    "38b7429b61b27efde4ec8a8f99ab5156d7a8e07921a73c5f7626d00021fe7c3f"
)
SMALL_HTTP_RAW_SHA = (
    "827457fba93744dccdb2487955ca3e1596364adfe15d32ac7f7bb13a9248cec4"
)

CALL_A_LOCAL = OBSERVED_LOCAL_ESTIMATE
CALL_A_PROVIDER_INPUT = OBSERVED_PROVIDER_INPUT
CALL_A_OUTPUT = 32000
CALL_A_COST = OBSERVED_COST_USD
CALL_A_RATIO = "2.155975"
CALL_A_FINISH = "UNKNOWN"

CALL_B_LOCAL = 50299
CALL_B_PROVIDER_INPUT = None
CALL_B_OUTPUT = None
CALL_B_COST = "UNKNOWN"
CALL_B_FINISH = "UNKNOWN"

CALL_C_LOCAL = 23618
CALL_C_PROVIDER_INPUT = 50603
CALL_C_OUTPUT = 32000
CALL_C_COST = "0.421206"
CALL_C_RATIO = "2.142561"
CALL_C_FINISH = "max_tokens"
CALL_C_THINKING_TOKENS = 21911

SELECTED_ARCHITECTURE = "MINIMAL_LOCAL_TRANSPORT_WITH_RESERVED_OUTPUT_BUDGET"
PRIMARY_ROOT_CAUSE = "THINKING_TOKENS_SHARED_MAX_OUTPUT"
PROPOSED_TRANSPORT = "semantic-transport-v2"
PROPOSED_PROMPT = "window-analysis-1.2"
SMALL_PLANNER_STATUS = "KEEP"
ADAPTIVE_HIERARCHY_STATUS = "KEEP"

FORENSICS_ARTIFACT = "source_analysis_small_win001_output_ceiling_forensics.json"
CONTRACT_ARTIFACT = "source_analysis_window_output_contract_analysis.json"
OPTIONS_ARTIFACT = "source_analysis_output_bounding_architecture_options.json"
DECISION_ARTIFACT = "source_analysis_output_bounding_architecture_decision.json"
ISOLATION_ARTIFACT = "source_analysis_forensic_vs_publication_isolation.json"
REPORT_NAME = (
    "PHASE_3B77A10_SMALL_WIN001_OUTPUT_CEILING_STRUCTURED_PARSE_FAILURE_REVIEW_REPORT.md"
)

PROTECTED_EVIDENCE = (
    "audit/PHASE_3B77A9_REAL_SMALL_WIN001_CANARY_REPORT.md",
    "audit/source_analysis_real_small_win001_execution.json",
    "audit/PHASE_3B77A8_SMALL_WINDOW_PRODUCTION_READINESS_STAGED_REAL_CALL_PLAN_REPORT.md",
    "audit/PHASE_3B77A7_SMALL_WINDOW_ADAPTIVE_HIERARCHY_IMPLEMENTATION_REPORT.md",
    "audit/PHASE_3B77A5_AIRESPONSEERROR_PROVIDER_BOUNDARY_FORENSICS_ARCHITECTURE_REVIEW_REPORT.md",
    "audit/PHASE_3B77A4_REAL_BOUNDED_WIN001_CANARY_REPORT.md",
    "audit/source_analysis_real_bounded_win001_execution.json",
    "audit/source_analysis_real_win001_canary_execution.json",
)

NEXT_PHASE = "3B.7.7A.11_OUTPUT_BOUNDED_LOCAL_SEMANTIC_EXTRACTION_IMPLEMENTATION"
NEXT_PHASE_LABEL = (
    "3B.7.7A.11 — OUTPUT-BOUNDED LOCAL SEMANTIC EXTRACTION IMPLEMENTATION "
    "— FAKEAI ONLY — 0 provider calls"
)
NEXT_ACTION = "HUMAN REVIEW"

PRODUCTION_PLANNER_VERSION = "window-planner-v2.0"
CANDIDATE_SMALL_PLANNER = CANDIDATE_PLANNER_VERSION

__all__ = [
    "ADAPTIVE_HIERARCHY_STATUS",
    "CALL1_SIGNATURE",
    "CALL2_SIGNATURE",
    "CALL_A_COST",
    "CALL_A_FINISH",
    "CALL_A_LOCAL",
    "CALL_A_OUTPUT",
    "CALL_A_PROVIDER_INPUT",
    "CALL_A_RATIO",
    "CALL_B_COST",
    "CALL_B_FINISH",
    "CALL_B_LOCAL",
    "CALL_B_OUTPUT",
    "CALL_B_PROVIDER_INPUT",
    "CALL_C_COST",
    "CALL_C_FINISH",
    "CALL_C_LOCAL",
    "CALL_C_OUTPUT",
    "CALL_C_PROVIDER_INPUT",
    "CALL_C_RATIO",
    "CALL_C_THINKING_TOKENS",
    "CANDIDATE_SMALL_PLANNER",
    "CLEAN_SHA",
    "CONTRACT_ARTIFACT",
    "DECISION_ARTIFACT",
    "FORENSICS_ARTIFACT",
    "GENERATION_C_ANTHROPIC_SHA",
    "GENERATION_C_RAW_SHA",
    "ISOLATION_ARTIFACT",
    "MODE",
    "NEW_WIN001_CALLS",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "OPTIONS_ARTIFACT",
    "PHASE",
    "PRIMARY_ROOT_CAUSE",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_10_SHA",
    "PROMPT_11_SHA",
    "PROPOSED_PROMPT",
    "PROPOSED_TRANSPORT",
    "PROTECTED_EVIDENCE",
    "REAL_PROVIDER_CALL_AUTHORIZED_NEXT",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REPORT_NAME",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SMALL_HTTP_RAW_SHA",
    "SMALL_PLANNER_STATUS",
    "SMALL_RAW_TEXT_SHA",
    "SMALL_SIGNATURE",
    "WINDOW_ID",
]
