"""Markdown report for Phase 4A.4."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any], *, tests: str) -> str:
    header = bundle.get("header") or {}
    lines = [
        "# PHASE 4A.4 — EDITORIAL PLAN CONTROLLED PUBLICATION + PHASE 4 FREEZE",
        "",
        "## Result",
        "",
        _dash(header.get("result")),
        "",
        "REAL PROVIDER CALLS =",
        "0",
        "",
        "APPROVED CANDIDATE PATH =",
        _dash(header.get("approved_candidate_path")),
        "",
        "EXPECTED CANDIDATE SHA256 =",
        "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440",
        "",
        "ACTUAL CANDIDATE SHA256 =",
        _dash(header.get("actual_candidate_sha256")),
        "",
        "CANDIDATE IDENTITY =",
        _dash(header.get("candidate_identity")),
        "",
        "SOURCE MAP SHA256 PRE =",
        _dash(header.get("source_map_sha256_pre")),
        "",
        "SOURCE MAP SHA256 POST =",
        _dash(header.get("source_map_sha256_post")),
        "",
        "SOURCE MAP UNCHANGED =",
        _dash(header.get("source_map_unchanged")),
        "",
        "CANONICAL LANGUAGE =",
        _dash(header.get("canonical_language")),
        "",
        "LANGUAGE POLICY =",
        "TRANSCRIPTION_DERIVED_PRIMARY_LANGUAGE",
        "",
        "PROMPT =",
        "editorial-planner-1.0.2",
        "",
        "TRANSPORT =",
        "editorial-plan-transport-1.0",
        "",
        "SCHEMA HASH =",
        "1cebcf97ed7fa5cfa4b4758d1eb1451b6770347e9508772e8287228a768ba77e",
        "",
        "PROVIDER PROVENANCE =",
        "Anthropic / claude-opus-5",
        "",
        "REQUEST ID =",
        "req_011CfamLewgH5N8GFiojFCBi",
        "",
        "REQUEST SHA256 =",
        "a059adfe3b05725aabaf5df84b1d492f09090370bcc471ce985583333a718c61",
        "",
        "PUBLICATION PATH =",
        _dash(header.get("publication_path")),
        "",
        "ATOMIC PUBLICATION =",
        _dash(header.get("atomic_publication")),
        "",
        "PUBLISHED SHA256 =",
        _dash(header.get("published_sha256")),
        "",
        "BYTE IDENTITY =",
        _dash(header.get("byte_identity")),
        "",
        "RELOAD =",
        _dash(header.get("reload")),
        "",
        "VALIDATOR =",
        _dash(header.get("validator")),
        "",
        "CHAPTERS =",
        _dash(header.get("chapters")),
        "",
        "SECTIONS =",
        _dash(header.get("sections")),
        "",
        "IDEA COVERAGE =",
        _dash(header.get("idea_coverage")),
        "",
        "ASSIGNED =",
        _dash(header.get("assigned")),
        "",
        "DEFERRED =",
        _dash(header.get("deferred")),
        "",
        "EXCLUDED =",
        _dash(header.get("excluded")),
        "",
        "SILENT OMISSIONS =",
        _dash(header.get("silent_omissions")),
        "",
        "DUPLICATE PRIMARY DISPOSITIONS =",
        _dash(header.get("duplicate_primary_dispositions")),
        "",
        "UNKNOWN REFS =",
        _dash(header.get("unknown_refs")),
        "",
        "EDITORIAL LANGUAGE =",
        _dash(header.get("editorial_language")),
        "",
        "WORKING TITLE =",
        "The Life You Already Inherited",
        "",
        "WORKING TITLE STATUS =",
        "SUPPORTED_WORKING_TITLE",
        "",
        "FINAL_TITLE_APPROVED =",
        "NO",
        "",
        "PHASE 4 CONTRACT FREEZE =",
        _dash(header.get("phase_4_contract_freeze")),
        "",
        "PHASE 4 AI COST =",
        "0 USD",
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        _dash(header.get("new_failures")),
        "",
        "editorial_plan.json =",
        _dash(header.get("editorial_plan_json")),
        "",
        "PHASE 4 STATUS =",
        _dash(header.get("phase_4_status")),
        "",
        "READY_FOR_BOOK_GENERATOR_PHASE_4B =",
        _dash(header.get("ready_for_book_generator_phase_4b")),
        "",
        "BOOK GENERATOR =",
        "NOT STARTED",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
