"""Constantes 3B.7.7A.23 — forensics A.22 offline. 0 provider. 0 WIN004 retry."""

from __future__ import annotations

from app.source_analysis.models import EXAMPLE_KINDS, IDEA_KINDS
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
    SELECTED_ARCHITECTURE,
    SEMANTIC_TRANSPORT_VERSION_V3,
    WINDOW_ANALYSIS_PROMPT_VERSION_V13,
    WINDOW_ANALYSIS_PROMPT_VERSION_V131,
    WINDOW_ANALYSIS_PROMPT_VERSION_V132,
)
from app.source_analysis_local_v3.schema import semantic_transport_v3_fingerprint
from app.source_analysis_v3_a19_forensics.constants import (
    A19_STATUS_UNCHANGED,
    EXAMPLE_POLICY,
    EXAMPLE_POLICY_LABEL,
    PROTECTED_A19,
)
from app.source_analysis_v3_hardened_win001.constants import (
    EXPECTED_PROMPT_SHA256,
    EXPECTED_SCHEMA_HASH,
    REPORT_NAME as A21_REPORT_NAME,
)
from app.source_analysis_v3_second_window.constants import (
    A21_RESULT,
    COMPARISON_ARTIFACT as A22_COMPARISON_ARTIFACT,
    EXECUTION_ARTIFACT as A22_EXECUTION_ARTIFACT,
    EXPECTED_WIN004_FIRST_OWNED_SRC,
    EXPECTED_WIN004_INPUT_HASH,
    EXPECTED_WIN004_LAST_OWNED_SRC,
    EXPECTED_WIN004_OWNED_SRC_COUNT,
    EXPECTED_WIN004_WORD_COUNT,
    HANDLE_ARTIFACT as A22_HANDLE_ARTIFACT,
    LOCK_NAME as A22_LOCK_NAME,
    PREFERRED_WINDOW_ID,
    PREFLIGHT_ARTIFACT as A22_PREFLIGHT_ARTIFACT,
    PROTECTED_A21,
    PROTECTED_HISTORICAL as A22_PROTECTED_HISTORICAL,
    REPORT_NAME as A22_REPORT_NAME,
    REVIEW_ARTIFACT as A22_REVIEW_ARTIFACT,
    SELECTION_ARTIFACT as A22_SELECTION_ARTIFACT,
    SRC_ARTIFACT as A22_SRC_ARTIFACT,
    V3_HANDLE_ARCHITECTURE,
)
from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.23"
MODE = "A22_WIN004_OFFLINE_TYPE_CONTRACT_AND_SEMANTIC_FORENSICS"

REAL_PROVIDER_CALLS_THIS_PHASE = 0
REAL_WINDOW_CALLS = 0
WIN004_RETRY_AUTHORIZED = False
FUTURE_REAL_CALL_AUTHORIZED = False
A19_STATUS = A19_STATUS_UNCHANGED
A21_STATUS = A21_RESULT
A22_STATUS_UNCHANGED = "FAIL"

WINDOW_ID = PREFERRED_WINDOW_ID
A22_TARGET = "WIN004"
A22_SRC_RANGE = "SRC003607 → SRC004786"
A22_OWNED = EXPECTED_WIN004_OWNED_SRC_COUNT
A22_WORDS = EXPECTED_WIN004_WORD_COUNT
A22_LOCAL_INPUT = 22656
A22_PROVIDER_INPUT = 48249
A22_OUTPUT = 12719
A22_MAX_OUTPUT = MAX_OUTPUT_TOKENS_FROZEN
A22_THINKING = "disabled"
A22_THINKING_TOKENS = 0
A22_FINISH = "end_turn"
A22_HTTP = 200
A22_STRUCTURED_PARSE = "PASS"
A22_CAPACITY_SIGNAL = "absent"
A22_RECORDS = 127
A22_TOPIC = 12
A22_IDEA = 58
A22_RELATION = 35
A22_EXAMPLE = 9
A22_REFERENCE = 8
A22_UNCERTAINTY = 5
A22_TOTAL_SRC_OCCURRENCES = 480
A22_VALID_SRC_OCCURRENCES = 480
A22_DISTINCT_SRC = 389
A22_COVERAGE_PCT = 32.97
A22_QUALITY_REPORTED = "INADEQUATE"
A22_QUALITY_REASON_REPORTED = "technical V3 gate failed"
A22_REQUEST_ID = "req_011CfSmab6cS4RfsY48fcB78"

A22_RAW_SHA256 = (
    "40dc024e2b2f05fac4322f269dc9a32d2b337baa67e60b5a8ff3e40084c55333"
)
A22_RAW_SIZE = 32803
A22_SIGNATURE = (
    "770bb1de18a722d09178901fd1447f47680ad723a3ba663bc0a94f07e69d25bf"
)
A22_FORENSIC_IDENTITY = (
    "5725d61529f152e5f52acc81ad9958c629f714fe9cbfe4909266dd76514bb7fc"
)
A22_PROMPT_SHA256 = EXPECTED_PROMPT_SHA256
A22_PROMPT_FINGERPRINT = (
    "14f40f93cca8ce022adc2e2c8ef75bf0306dc1c7545a904224aab60ad637fbb0"
)
A22_INPUT_HASH = EXPECTED_WIN004_INPUT_HASH

A22_FORENSIC_RELATIVE = (
    "audit/canary/v3_second_window/provider_forensics/WIN004/" + A22_SIGNATURE
)
A22_LOCK_RELATIVE = f"audit/canary/v3_second_window/{A22_LOCK_NAME}"

PROTECTED_A22 = (
    f"audit/{A22_REPORT_NAME}",
    f"audit/{A22_PREFLIGHT_ARTIFACT}",
    f"audit/{A22_EXECUTION_ARTIFACT}",
    f"audit/{A22_SELECTION_ARTIFACT}",
    f"audit/{A22_SRC_ARTIFACT}",
    f"audit/{A22_HANDLE_ARTIFACT}",
    f"audit/{A22_REVIEW_ARTIFACT}",
    f"audit/{A22_COMPARISON_ARTIFACT}",
    A22_LOCK_RELATIVE,
    f"{A22_FORENSIC_RELATIVE}/provider_raw_response.bin",
    f"{A22_FORENSIC_RELATIVE}/provider_http_envelope.json",
)

PROTECTED_HISTORICAL = tuple(A22_PROTECTED_HISTORICAL) + PROTECTED_A22

INVALID_IDEA_EXAMPLE_INDEXES = (30, 38, 62, 64)
INVALID_IDEA_HANDLES = ("I19", "I27", "I51", "I53")
VALID_IDEA_KINDS = IDEA_KINDS
VALID_EXAMPLE_KINDS = EXAMPLE_KINDS

IDEA_KIND_COUNTS_EXPECTED = {
    "claim": 32,
    "explanation": 9,
    "principle": 2,
    "instruction": 3,
    "observation": 5,
    "question": 0,
    "testimony": 3,
    "example": 4,
}

SEMANTIC_REVIEW_STATUS = "FORENSIC_SEMANTIC_REVIEW_OF_INVALID_V3_WIN004_TRANSPORT"
EXAMPLE_POLICY = EXAMPLE_POLICY
EXAMPLE_POLICY_LABEL = EXAMPLE_POLICY_LABEL

IDEA_EXAMPLE_ROOT_CAUSE = "PROMPT_VOCABULARY_AMBIGUITY"
IDEA_EXAMPLE_ROOT_CAUSE_SECONDARY = (
    "METADATA_FIELD_OVERLOADING",
    "IDEA_EXAMPLE_CONCEPTUAL_OVERLAP",
    "PROMPT_EXAMPLE_INSUFFICIENT",
    "EXAMPLE_KIND_TOKEN_COLLIDES_WITH_RECORD_KIND",
)

SEMANTIC_COUNTERFACTUAL = "SEMANTICALLY_ACCEPTABLE_BUT_FOR_TRANSPORT_METADATA"
SEMANTIC_INADEQUACY_ROOT_CAUSE = "TYPE_METADATA_ONLY"
SELECTED_NEXT_STRATEGY = "THINKING_DISABLED_PLUS_HARDENED_PROMPT_1_3_2"
THINKING_DISABLED_EVIDENCE = (
    "NOT_THE_CAUSE_OF_INDEPENDENT_SEMANTIC_INADEQUACY"
)

VIOLATION_ARTIFACT = "source_analysis_v3_a22_exhaustive_violation_inventory.json"
CONTRACT_ARTIFACT = "source_analysis_v3_idea_example_contract_analysis.json"
FOUR_RECORDS_ARTIFACT = "source_analysis_v3_a22_invalid_idea_example_records.json"
SEMANTIC_ARTIFACT = "source_analysis_v3_a22_forensic_semantic_review.json"
COVERAGE_ARTIFACT = "source_analysis_v3_a22_semantic_coverage_analysis.json"
REASONING_ARTIFACT = "source_analysis_v3_post_a22_reasoning_decision.json"
FUTURE_RETRY_ARTIFACT = "source_analysis_v3_future_win004_retry_readiness.json"
REPORT_NAME = (
    "PHASE_3B77A23_A22_IDEA_EXAMPLE_TYPE_CONTRACT_FORENSICS_REPORT.md"
)

NEXT_ACTION = "HUMAN REVIEW"
NEXT_PHASE = "3B.7.7A.24_REAL_WIN004_HARDENED_TYPE_CONTRACT_RETRY"
NEXT_PHASE_LABEL = (
    "3B.7.7A.24 — REAL WIN004 HARDENED TYPE-CONTRACT RETRY "
    "(ONE provider call maximum, only after separate human authorization)"
)
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION
SCHEMA_CHANGED = False
SERVER_GRAMMAR_STATUS = "A18_PROOF_APPLICABLE"
READY_WINDOWS = "1 / 7"

assert EXPECTED_SCHEMA_HASH == semantic_transport_v3_fingerprint()
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert A22_MAX_OUTPUT == 32000
assert A22_OWNED == 1180
assert A22_WORDS == 5662
assert A19_STATUS == "FAIL"
assert A21_STATUS == "PASS"
assert A22_STATUS_UNCHANGED == "FAIL"
assert WINDOW_ANALYSIS_PROMPT_VERSION_V132 == "window-analysis-1.3.2"
assert "example" not in IDEA_KINDS
assert "example" in EXAMPLE_KINDS

__all__ = [
    "A19_STATUS",
    "A21_REPORT_NAME",
    "A21_STATUS",
    "A22_CAPACITY_SIGNAL",
    "A22_COVERAGE_PCT",
    "A22_DISTINCT_SRC",
    "A22_EXAMPLE",
    "A22_EXECUTION_ARTIFACT",
    "A22_FINISH",
    "A22_FORENSIC_IDENTITY",
    "A22_FORENSIC_RELATIVE",
    "A22_HANDLE_ARTIFACT",
    "A22_HTTP",
    "A22_IDEA",
    "A22_INPUT_HASH",
    "A22_LOCAL_INPUT",
    "A22_LOCK_RELATIVE",
    "A22_MAX_OUTPUT",
    "A22_OUTPUT",
    "A22_OWNED",
    "A22_PREFLIGHT_ARTIFACT",
    "A22_PROMPT_FINGERPRINT",
    "A22_PROMPT_SHA256",
    "A22_PROVIDER_INPUT",
    "A22_QUALITY_REASON_REPORTED",
    "A22_QUALITY_REPORTED",
    "A22_RAW_SHA256",
    "A22_RAW_SIZE",
    "A22_RECORDS",
    "A22_REFERENCE",
    "A22_RELATION",
    "A22_REPORT_NAME",
    "A22_REQUEST_ID",
    "A22_REVIEW_ARTIFACT",
    "A22_SIGNATURE",
    "A22_SRC_ARTIFACT",
    "A22_SRC_RANGE",
    "A22_STATUS_UNCHANGED",
    "A22_STRUCTURED_PARSE",
    "A22_TARGET",
    "A22_THINKING",
    "A22_THINKING_TOKENS",
    "A22_TOPIC",
    "A22_TOTAL_SRC_OCCURRENCES",
    "A22_UNCERTAINTY",
    "A22_VALID_SRC_OCCURRENCES",
    "A22_WORDS",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER",
    "CONTRACT_ARTIFACT",
    "COVERAGE_ARTIFACT",
    "EXAMPLE_POLICY",
    "EXAMPLE_POLICY_LABEL",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "EXPECTED_SCHEMA_HASH",
    "EXPECTED_WIN004_FIRST_OWNED_SRC",
    "EXPECTED_WIN004_LAST_OWNED_SRC",
    "FOUR_RECORDS_ARTIFACT",
    "FUTURE_REAL_CALL_AUTHORIZED",
    "FUTURE_RETRY_ARTIFACT",
    "IDEA_EXAMPLE_ROOT_CAUSE",
    "IDEA_KIND_COUNTS_EXPECTED",
    "INVALID_IDEA_EXAMPLE_INDEXES",
    "INVALID_IDEA_HANDLES",
    "MODE",
    "NEXT_ACTION",
    "NEXT_PHASE",
    "NEXT_PHASE_LABEL",
    "PHASE",
    "PHASE_3B_STATUS",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROTECTED_A19",
    "PROTECTED_A21",
    "PROTECTED_A22",
    "PROTECTED_HISTORICAL",
    "READY_WINDOWS",
    "REAL_PROVIDER_CALLS_THIS_PHASE",
    "REAL_WINDOW_CALLS",
    "REASONING_ARTIFACT",
    "REPORT_NAME",
    "SCHEMA_CHANGED",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SELECTED_NEXT_STRATEGY",
    "SEMANTIC_ARTIFACT",
    "SEMANTIC_COUNTERFACTUAL",
    "SEMANTIC_INADEQUACY_ROOT_CAUSE",
    "SEMANTIC_REVIEW_STATUS",
    "SEMANTIC_TRANSPORT_VERSION_V3",
    "SERVER_GRAMMAR_STATUS",
    "THINKING_DISABLED_EVIDENCE",
    "VALID_EXAMPLE_KINDS",
    "VALID_IDEA_KINDS",
    "VIOLATION_ARTIFACT",
    "V3_HANDLE_ARCHITECTURE",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V13",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V131",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V132",
    "WINDOW_ID",
    "WIN004_RETRY_AUTHORIZED",
]
