"""Rapport 3B.7.7A.23."""

from __future__ import annotations

from typing import Any, Mapping


def render_report(
    *,
    header: Mapping[str, Any],
    inventory: Mapping[str, Any],
    src_audit: Mapping[str, Any],
    metadata: Mapping[str, Any],
    four: Mapping[str, Any],
    contract: Mapping[str, Any],
    semantic: Mapping[str, Any],
    coverage: Mapping[str, Any],
    reasoning: Mapping[str, Any],
    future: Mapping[str, Any],
    handles: Mapping[str, Any],
    isolation: Mapping[str, Any],
    tests: str,
) -> str:
    grades = header.get("relation_quality") or {}
    prompt_132 = contract.get("prompt_1_3_2") or {}
    lines = [
        "# PHASE 3B.7.7A.23 — A.22 IDEA/EXAMPLE TYPE-CONTRACT FORENSICS",
        "",
        "## Result",
        "",
        str(header.get("result")),
        "",
        f"REAL PROVIDER CALLS = {header.get('real_provider_calls')}",
        "",
        f"REAL WINDOW CALLS = {header.get('real_window_calls')}",
        "",
        "A.22 STATUS = FAIL unchanged",
        "",
        f"A.22 TARGET = {header.get('a22_target')}",
        "",
        f"A.22 STRUCTURED PARSE = {header.get('a22_structured_parse')}",
        "",
        f"TOTAL LATENT ROOT VIOLATIONS = {header.get('total_latent_root_violations')}",
        "",
        f"TOTAL CASCADE VIOLATIONS = {header.get('total_cascade_violations')}",
        "",
        f"INVALID IDEA METADATA = {header.get('invalid_idea_metadata')}",
        "",
        f"OTHER METADATA VIOLATIONS = {header.get('other_metadata_violations')}",
        "",
        f"SRC VIOLATIONS = {header.get('src_violations')}",
        "",
        f"HANDLE VIOLATIONS = {header.get('handle_violations')}",
        "",
        f"NUMERIC LINK REGRESSION = {header.get('numeric_link_regression')}",
        "",
        f"IDEA/EXAMPLE ROOT CAUSE = {header.get('idea_example_root_cause')}",
        "",
        f"FOUR INVALID RECORDS CLASSIFICATION = {header.get('four_invalid_records_classification')}",
        "",
        f"SEMANTIC GROUNDING = {header.get('semantic_grounding')}",
        "",
        f"UNSUPPORTED CONTENT = {header.get('unsupported_content')}",
        "",
        f"MAJOR IDEAS REPRESENTED = {header.get('major_ideas_represented')}",
        "",
        f"MAJOR IDEAS PARTIAL = {header.get('major_ideas_partial')}",
        "",
        f"MAJOR IDEAS MISSING = {header.get('major_ideas_missing')}",
        "",
        (
            "RELATION QUALITY = "
            f"{grades.get('well_supported')} well-supported / "
            f"{grades.get('plausible_but_loose')} plausible-loose / "
            f"{grades.get('incorrect')} incorrect / "
            f"{grades.get('unverifiable')} unverifiable"
        ),
        "",
        f"EXAMPLE QUALITY = {header.get('example_quality')}",
        "",
        f"SEMANTIC SRC COVERAGE = {header.get('semantic_src_coverage')}",
        "",
        f"BEGINNING/MIDDLE/END = {header.get('beginning_middle_end')}",
        "",
        f"SEMANTIC INADEQUACY ROOT CAUSE = {header.get('semantic_inadequacy_root_cause')}",
        "",
        f"A.22 SEMANTIC COUNTERFACTUAL = {header.get('a22_semantic_counterfactual')}",
        "",
        f"THINKING_DISABLED WIN004 EVIDENCE = {header.get('thinking_disabled_win004_evidence')}",
        "",
        f"SELECTED NEXT STRATEGY = {header.get('selected_next_strategy')}",
        "",
        f"PROMPT = {header.get('prompt')}",
        "",
        f"TRANSPORT = {header.get('transport')}",
        "",
        f"SCHEMA CHANGED = {'YES' if header.get('schema_changed') else 'NO'}",
        "",
        f"SERVER GRAMMAR STATUS = {header.get('server_grammar_status')}",
        "",
        f"FUTURE WIN004 INPUT ESTIMATE = {header.get('future_win004_input_estimate')}",
        "",
        f"FUTURE WIN004 SIGNATURE = {header.get('future_win004_signature')}",
        "",
        f"FUTURE CACHE = {header.get('future_cache')}",
        "",
        f"FUTURE REAL CALL READY = {'YES' if header.get('future_real_call_ready') else 'NO'}",
        "",
        "FUTURE REAL CALL AUTHORIZED = NO",
        "",
        f"REAL WINDOWS READY = {header.get('real_windows_ready')}",
        "",
        f"PRODUCTION DEFAULT = {header.get('production_default')}",
        "",
        "SOURCE MAP = NOT PUBLISHED",
        "",
        "PHASE 3B = INCOMPLETE",
        "",
        f"TESTS = {tests}",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
        "## 1. Isolation",
        "",
        "Were any provider calls made? NO.",
        "Was WIN004 retried? NO.",
        "WIN001–WIN003 / WIN005–WIN007 untouched. Consolidation untouched.",
        "A.19 remains FAIL. A.21 remains PASS. A.22 remains FAIL. No reclassification.",
        f"source_map present={isolation.get('source_map_present')}.",
        f"A.22 candidate cache present={isolation.get('candidate_cache_present')}.",
        "",
        "## 2. A.22 replay",
        "",
        "Structured parse PASS. V3 decoder FAIL on four IDEA kinds `example`.",
        "Raw provider response, execution, preflight, review, report, lock, "
        "and historical A.13–A.21 hashes are byte-identical. No salvage, cache, "
        "promotion, metadata rewrite, or WIN004 write.",
        "",
        "## 3. Exhaustive violation inventory",
        "",
        f"Diagnostic validator collected {len(inventory.get('violations') or [])} "
        f"rows ({inventory.get('total_latent_root_violations')} ROOT, "
        f"{inventory.get('total_cascade_violations')} CASCADE, "
        f"{inventory.get('total_observations')} OBSERVATION).",
        f"By code: {inventory.get('by_code')}.",
        "Expected four metadata-vocabulary roots. Verified. No other latent "
        "SRC / handle / cardinality / EXAMPLE-policy roots.",
        "Production fail-fast decoder is unchanged. `example` is not added to IDEA_KINDS.",
        "",
        "## 4. SRC and handles",
        "",
        f"Total SRC occurrences={src_audit.get('total_src_reference_occurrences')}.",
        f"Valid canonical owned={src_audit.get('valid_canonical_owned_occurrences')}.",
        f"Malformed={len(src_audit.get('malformed_lexical_refs') or [])}.",
        f"Unknown={len(src_audit.get('unknown_well_formed_refs') or [])}.",
        f"Out-of-window={len(src_audit.get('out_of_window_refs') or [])}.",
        f"Duplicates={len(src_audit.get('duplicate_refs_within_records') or [])}.",
        f"Handle gate pass={header.get('handle_gate_pass')}.",
        f"T owners={handles.get('topic_owner_handles') and len(handles.get('topic_owner_handles') or [])}.",
        f"I owners={handles.get('idea_owner_handles') and len(handles.get('idea_owner_handles') or [])}.",
        "480/480 SRC valid. 0 structural handle violations. Numeric link regression=NO.",
        "",
        "## 5. IDEA metadata vocabulary",
        "",
        f"Counts={metadata.get('idea_kind_counts')}.",
        "Valid closed set remains claim, explanation, principle, instruction, "
        "observation, question, testimony. `example` is not a valid IDEA kind.",
        f"Other metadata violations={metadata.get('other_metadata_violation_count')}.",
        "",
        "## 6. Four invalid records",
        "",
        f"Duplication={four.get('duplication_summary')}.",
        "I19 / I27 / I51 / I53 each have a matching valid EXAMPLE (108, 110, 111, 112) "
        "plus an illustrates RELATION into the surrounding teaching.",
        "I27 is a true proposition mislabeled example. I19/I51 collapse illustration "
        "into IDEA.v. I53 is the illustration of I52 emitted again as IDEA.",
        "Do not convert historical IDEA+example into EXAMPLE. Do not rewrite m[].",
        "",
        "## 7. IDEA versus EXAMPLE contract",
        "",
        "window-analysis-1.3.1 lists idea.kind and example.kind as adjacent "
        "controlled vocabularies. m[0] is overloaded across kinds. The compact "
        "example never forbids IDEA m=[example,…]. The exact negative rule is absent.",
        f"Root cause={contract.get('root_cause')}.",
        "Schema cannot enforce per-kind m[] enums without losing 588/650 compactness.",
        "m is overloaded, but four slips do not justify redesigning m.",
        "Prompt hardening is sufficient. supports_idea_refs remains optional (A.20).",
        "",
        "## 8. Semantic forensic review",
        "",
        header.get("semantic_review_status"),
        "A.22 classified quality INADEQUATE solely because the technical V3 gate failed.",
        "Independent review against exact CLEAN WIN004: 0 UNSUPPORTED, "
        "beginning/middle/end True/True/True, 58 ideas, 12 topics.",
        f"Counterfactual if metadata were valid={semantic.get('counterfactual_if_transport_metadata_valid')}.",
        f"Dimensions={semantic.get('dimensions')}.",
        "Secondary pattern EXAMPLE_IDEA_COLLAPSE exists but is not independently fatal: "
        "the illustrations were also emitted as EXAMPLE records.",
        "",
        "## 9. Coverage and major ideas",
        "",
        f"Verified distinct owned SRC={coverage.get('verified_distinct_canonical_owned')} "
        f"/ {coverage.get('owned_src_count')} = {coverage.get('verified_semantic_src_coverage_pct')}%.",
        "Percentage is not a quality threshold.",
        f"Major ideas represented/partial/missing="
        f"{coverage.get('major_ideas_represented')}/"
        f"{coverage.get('major_ideas_partial')}/"
        f"{coverage.get('major_ideas_missing')}.",
        "Largest unreferenced gap is session wrap-up / tomorrow-practicals, not a missing teaching.",
        "Lucifer/devil distinction and Davos aside are partial via UNCERTAINTY, not omitted.",
        "",
        "## 10. Relations, examples, references, uncertainties",
        "",
        f"35 relations: {grades}.",
        "Handle validity is not treated as semantic validity.",
        "9 EXAMPLE records are source-grounded and linked to IDEAs. Four overlap the invalid IDEAs.",
        "8 REFERENCES are biblical and source-said. 5 UNCERTAINTIES use canonical vocabulary.",
        "",
        "## 11. Thinking-disabled and next strategy",
        "",
        f"Evidence class={reasoning.get('thinking_disabled_evidence')}.",
        "Do not switch to adaptive-low because A.22 said INADEQUATE.",
        "No max-token pressure. No capacity signal. Window size comparable to WIN001.",
        f"Selected={reasoning.get('selected_next_strategy')}.",
        "Path A: separately authorized 3B.7.7A.24 REAL WIN004 HARDENED TYPE-CONTRACT RETRY, "
        "ONE call maximum. Do not execute from this phase.",
        "",
        "## 12. Prompt 1.3.2 / schema / future request",
        "",
        f"1.3 untouched={header.get('prompt_1_3_untouched')}.",
        f"1.3.1 untouched / lacks negative rule={header.get('prompt_1_3_1_lacks_negative_rule')}.",
        f"1.3.2 created={header.get('prompt_1_3_2_contains_hardening')}.",
        f"1.3.2 overhead chars system/user="
        f"{prompt_132.get('system_overhead_chars')}/{prompt_132.get('user_overhead_chars')}.",
        f"1.3.2 local tokens={prompt_132.get('local_tokens_1_3_2')} "
        f"(+{prompt_132.get('input_overhead_tokens')} vs 1.3.1).",
        "Schema unchanged 588/650. A.18 grammar proof remains applicable.",
        f"Future signature={future.get('future_win004_signature')}. Differs from A.22. Cache MISS.",
        f"Future input={future.get('future_win004_input_estimate')} <= 35000: "
        f"{future.get('within_35000')}.",
        "FUTURE REAL CALL AUTHORIZED = NO.",
        "",
        "## 13. Required questions",
        "",
        "Why did Claude emit IDEA + example? Prompt vocabulary ambiguity plus "
        "m[] overload and IDEA/EXAMPLE conceptual overlap. Not a clear-contract "
        "defiance, not a taxonomy hole, not a missing EXAMPLE fallback.",
        "Would A.22 have been semantically acceptable but for transport metadata? YES.",
        "Is another disabled-thinking retry reasonable after hardening? YES, if separately authorized.",
        "Should remaining windows be spent first? NO.",
        "",
        "NEXT ACTION = HUMAN REVIEW",
        "",
    ]
    return "\n".join(lines) + "\n"


__all__ = ["render_report"]
