"""Rapport markdown 3B.7.7A.48."""

from __future__ import annotations

from typing import Any, Mapping


def _dash(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "YES" if value else "NO"
    return str(value)


def render_report(bundle: Mapping[str, Any], *, tests: str) -> str:
    header = bundle.get("header") or {}
    lines = [
        "# PHASE 3B.7.7A.48 — A.46 OFFLINE REVALIDATION UNDER CORRECTED CONTRACT",
        "",
        "## Result",
        "",
        str(header.get("result")),
        "",
        "REAL PROVIDER CALLS =",
        "0",
        "",
        "A.46 HISTORICAL STATUS =",
        "FAIL unchanged",
        "",
        "A.47 STATUS =",
        _dash(header.get("a47_status")),
        "",
        "A.46 RAW RESPONSE IDENTITY =",
        _dash(header.get("a46_raw_response_identity")),
        "",
        "A.46 INPUT / OUTPUT =",
        f"{header.get('a46_input')} / {header.get('a46_output')}",
        "",
        "A.46 HISTORICAL COST =",
        f"{header.get('a46_historical_cost')} USD",
        "",
        "A.48 COST =",
        "0.00 USD",
        "",
        "HISTORICAL PROMPT =",
        _dash(header.get("historical_prompt")),
        "",
        "FUTURE PROMPT =",
        _dash(header.get("future_prompt")),
        "",
        "TRANSPORT =",
        _dash(header.get("transport")),
        "",
        "SCHEMA RAW / ADAPTED =",
        f"{header.get('schema_raw')} / {header.get('schema_adapted')}",
        "",
        "SCHEMA HASH =",
        _dash(header.get("schema_hash")),
        "",
        "GLOBAL INTENT LIMIT =",
        _dash(header.get("global_intent_limit")),
        "",
        "A.46 INTENT LENGTH =",
        _dash(header.get("a46_intent_length")),
        "",
        "A.46 INTENT UNCHANGED =",
        _dash(header.get("a46_intent_unchanged")),
        "",
        "STRUCTURED PARSE =",
        _dash(header.get("structured_parse")),
        "",
        "TRANSPORT DECODER =",
        _dash(header.get("transport_decoder")),
        "",
        "HANDLE VALIDATION =",
        _dash(header.get("handle_validation")),
        "",
        "IDEA ACCOUNTABILITY =",
        _dash(header.get("idea_accountability")),
        "",
        "REUSE / MERGE / DROP =",
        _dash(header.get("reuse_merge_drop")),
        "",
        "REUSE TEXT EXACT =",
        _dash(header.get("reuse_text_exact")),
        "",
        "SINGLE_MEMBER_WITH_V =",
        _dash(header.get("SINGLE_MEMBER_WITH_V")),
        "",
        "MULTI_MEMBER_WITHOUT_V =",
        _dash(header.get("MULTI_MEMBER_WITHOUT_V")),
        "",
        "NON_IDEA_IN_MEMBERS =",
        _dash(header.get("NON_IDEA_IN_MEMBERS")),
        "",
        "NON_IDEA_IN_DROP =",
        _dash(header.get("NON_IDEA_IN_DROP")),
        "",
        "UNKNOWN HANDLES =",
        _dash(header.get("unknown_handles")),
        "",
        "DUPLICATE MEMBERSHIP =",
        _dash(header.get("duplicate_membership")),
        "",
        "MISSING IDEAS =",
        _dash(header.get("missing_ideas")),
        "",
        "MEMBER/DROP OVERLAP =",
        _dash(header.get("member_drop_overlap")),
        "",
        "DERIVED SRC =",
        _dash(header.get("derived_src")),
        "",
        "CORRECTED GLOBAL VALIDATOR =",
        _dash(header.get("corrected_global_validator")),
        "",
        "CANONICAL RECONSTRUCTION =",
        _dash(header.get("canonical_reconstruction")),
        "",
        "CANONICAL VALIDATION =",
        _dash(header.get("canonical_validation")),
        "",
        "STRUCTURAL EDITORIAL SCANNER =",
        _dash(header.get("structural_editorial_scanner")),
        "",
        "FORBIDDEN EDITORIAL STRUCTURE =",
        _dash(header.get("forbidden_editorial_structure")),
        "",
        "DETERMINISTIC REPLAY =",
        _dash(header.get("deterministic_replay")),
        "",
        "THEME REVIEW =",
        _dash(header.get("theme_review")),
        "",
        "INTENT REVIEW =",
        _dash(header.get("intent_review")),
        "",
        "AUDIENCE REVIEW =",
        _dash(header.get("audience_review")),
        "",
        "VOICE REVIEW =",
        _dash(header.get("voice_review")),
        "",
        "TOPIC REVIEW =",
        _dash(header.get("topic_review")),
        "",
        "EXAMPLE REVIEW =",
        _dash(header.get("example_review")),
        "",
        "REFERENCE REVIEW =",
        _dash(header.get("reference_review")),
        "",
        "UNCERTAINTY PRESERVATION =",
        _dash(header.get("uncertainty_preservation")),
        "",
        "COMPLETENESS =",
        _dash(header.get("completeness")),
        "",
        "SEMANTIC REVIEW =",
        _dash(header.get("semantic_review")),
        "",
        "PUBLICATION_ELIGIBLE =",
        _dash(header.get("publication_eligible")),
        "",
        "GLOBAL_CONSOLIDATION_CORE_ARCHITECTURE_FUNCTIONALLY_FROZEN =",
        _dash(header.get("global_consolidation_core_architecture_functionally_frozen")),
        "",
        "NEW_GRAMMAR_CANARY_REQUIRED =",
        "NO",
        "",
        "NEW_PROVIDER_CANARY_REQUIRED_FOR_A46 =",
        "NO",
        "",
        "A.46 OUTPUT UTILIZATION =",
        _dash(header.get("a46_output_utilization")),
        "",
        "A.45 INPUT ESTIMATE ERROR =",
        _dash(header.get("a45_input_estimate_error")),
        "",
        "A.45 EXPECTED OUTPUT ERROR =",
        _dash(header.get("a45_expected_output_error")),
        "",
        "RELATION_QUALITY_TECHNICAL_DEBT =",
        "YES",
        "",
        "TESTS =",
        tests,
        "",
        "NEW FAILURES =",
        _dash(header.get("new_failures")),
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "READY_FOR_CONTROLLED_SOURCE_MAP_PUBLICATION =",
        _dash(header.get("ready_for_controlled_source_map_publication")),
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_report"]
