"""Constantes du canary 3B.4.5 — pas des règles métier du Source Analyzer."""

from __future__ import annotations

from app.source_analysis.canonical_vocabulary import (
    GENERATION_C_ANTHROPIC_SHA256_3B43,
    GENERATION_C_RAW_SHA256_3B43,
    OBSERVED_3B43_INVALID_UNCERTAINTY_KINDS,
)
from app.source_analysis_ultra_compact_canary.constants import (
    HISTORICAL_SRC_IDS,
    REFERENCE_3B42_ANTHROPIC_BYTES,
    REFERENCE_3B42_ANTHROPIC_SHA256,
    REFERENCE_3B42_RAW_BYTES,
    REFERENCE_3B42_RAW_SHA256,
    SELECTION_RULE_HISTORICAL,
)

CANARY_SCHEMA_VERSION = "1.0"
CANARY_PROMPT_ADDENDUM_VERSION = "1.0"
STAGE = "source_analysis_vocabulary_compliance_canary"
CACHE_NAMESPACE = "vocabulary-compliance-canary-3b45"
SIGNATURE_MARK = "vocabulary-compliance-canary-3b45"

EXPECTED_PROVIDER = "anthropic"
EXPECTED_MODEL = "claude-sonnet-5"
TRANSPORT_VERSION = "semantic-transport-v1"
EXPECTED_PROMPT_VERSION = "1.3"

MAX_REAL_CALLS = 1
MAX_ATTEMPTS = 1
REAL_CALL_TIMEOUT_SECONDS = 600.0

# Budget de sortie du canary uniquement — ne change PAS la config globale.
CANARY_MAX_OUTPUT_TOKENS = 8192

MAX_ESTIMATED_INPUT_TOKENS = 20_000
GLOBAL_ESTIMATED_TOKENS_REFERENCE = 141_775

# SHA production Prompt 1.3 capturé en 3B.4.4 (recalculé, jamais une preuve).
REFERENCE_3B44_PROMPT_SHA256 = (
    "b9f72cc4b9fe225a4952171c2045d252725a64c4aa28d667cc44541af1ce35c8"
)

INPUT_ARTIFACT_NAME = "source_analysis_vocabulary_compliance_canary_input.json"
DRY_RUN_ARTIFACT_NAME = "source_analysis_vocabulary_compliance_canary_dry_run.json"
RESULT_ARTIFACT_NAME = "source_analysis_vocabulary_compliance_canary_result.json"
TRANSPORT_ARTIFACT_NAME = "source_analysis_vocabulary_compliance_canary_transport.json"
CANARY_SOURCEMAP_NAME = "source_analysis_vocabulary_compliance_canary_source_map.json"
REPORT_NAME = "PHASE_3B45_CANONICAL_VOCABULARY_COMPLIANCE_CANARY_REPORT.md"

GRAMMAR_ACCEPTED = "ACCEPTED"
GRAMMAR_REJECTED = "REJECTED"
GRAMMAR_UNKNOWN = "UNKNOWN"

GRAMMAR_ACCEPTANCE_VERIFIED = "VERIFIED"
GRAMMAR_ACCEPTANCE_PREVIOUSLY_VERIFIED = "PREVIOUSLY VERIFIED"
GRAMMAR_ACCEPTANCE_REJECTED = "REJECTED"
GRAMMAR_ACCEPTANCE_UNKNOWN = "UNKNOWN"

VOCAB_COMPLIANCE_PASS = "PASS"
VOCAB_COMPLIANCE_FAIL = "FAIL"
VOCAB_COMPLIANCE_NA = "N/A"

VOCAB_PROMPT_VERIFIED = "VERIFIED"
VOCAB_PROMPT_FAILED = "FAILED"
VOCAB_PROMPT_UNVERIFIED = "UNVERIFIED"

OUTCOME_PASS = "PASS"
OUTCOME_PARTIAL = "PARTIAL"
OUTCOME_FAIL = "FAIL"
STOP_PRE_CALL = "PRE_CALL_FAILURE"

CLASS_PRE_CALL_SCHEMA_DRIFT = "PRE_CALL_SCHEMA_DRIFT"
CLASS_PRE_CALL_CREDENTIAL_MISSING = "PRE_CALL_CREDENTIAL_MISSING"
CLASS_PRE_CALL_HISTORICAL_UNAVAILABLE = "PRE_CALL_HISTORICAL_INPUT_UNAVAILABLE"
CLASS_PRE_CALL_PARITY = "PRE_CALL_VOCABULARY_PARITY"
CLASS_SERVER_GRAMMAR_REGRESSION = "SERVER_GRAMMAR_REGRESSION"

__all__ = [
    "CANARY_MAX_OUTPUT_TOKENS",
    "CACHE_NAMESPACE",
    "EXPECTED_MODEL",
    "EXPECTED_PROMPT_VERSION",
    "EXPECTED_PROVIDER",
    "GENERATION_C_ANTHROPIC_SHA256_3B43",
    "GENERATION_C_RAW_SHA256_3B43",
    "HISTORICAL_SRC_IDS",
    "OBSERVED_3B43_INVALID_UNCERTAINTY_KINDS",
    "REFERENCE_3B42_ANTHROPIC_BYTES",
    "REFERENCE_3B42_ANTHROPIC_SHA256",
    "REFERENCE_3B42_RAW_BYTES",
    "REFERENCE_3B42_RAW_SHA256",
    "REFERENCE_3B44_PROMPT_SHA256",
    "SELECTION_RULE_HISTORICAL",
    "SIGNATURE_MARK",
    "STAGE",
    "TRANSPORT_VERSION",
]
