"""
Phase 4B.2.6.2 — Compact semantic gate, single-case canary freeze.

Offline only. Zero provider calls. Historical 4B.2.6 remains FAIL.
Historical 4B.2.6.1 remains PASS. Contract 1.0 is not modified.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    CONSERVATIVE_MAX_OUTPUT_TOKENS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_GATE_MODEL,
    SEMANTIC_GATE_PROVIDER,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
    STRUCTURED_OUTPUT_MODE,
    TEMPERATURE_POLICY,
    THINKING_MODE,
    VERDICT_FAIL,
    VERDICT_PASS,
    VERDICT_REVIEW,
)
from app.book_semantic_gate_4b24.constants import (
    CONNECTIVE_CASE_ID,
    EXPECTED_BENCHMARK_FILE_SHA256,
    EXPECTED_NEGATIVE_CASES,
    EXPECTED_POSITIVE_CASES,
    EXPECTED_SCORED_CASES,
    FUNERAL_CASE_ID,
    NEGATIVE_CASE_IDS,
    P3_CASE_ID,
    P8_CASE_ID,
    POSITIVE_CASE_IDS,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import (
    CANONICAL_PYTHON_EXECUTABLE,
    EXPECTED_OPENAI_SDK_VERSION,
    EXPECTED_PYTHON_VERSION,
    EXPECTED_REQUEST_SHA256 as EXPECTED_REQUEST_SHA256_4B26,
    EXPECTED_REQUEST_SHA256_HISTORICAL_4B25,
    HISTORICAL_4B21_STATUS,
    HISTORICAL_4B22_STATUS,
    HISTORICAL_4B23_STATUS,
    HISTORICAL_4B241_STATUS,
    HISTORICAL_4B24_STATUS,
    HISTORICAL_4B251_STATUS,
    HISTORICAL_4B25_STATUS,
    HISTORICAL_4B2_STATUS,
    SEMANTIC_TOKEN_BUDGET,
)
from app.book_semantic_gate_4b261.constants import (
    CANDIDATE_PROMPT_VERSION,
    CANDIDATE_TRANSPORT_VERSION,
    HISTORICAL_4B26_STATUS,
    OBSERVED_4B26_COST_USD,
    OBSERVED_4B26_FINISH_REASON,
    OBSERVED_4B26_INPUT_TOKENS,
    OBSERVED_4B26_OUTPUT_TOKENS,
)

PHASE = "4B.2.6.2"
PHASE_NAME = "TERRA_COMPACT_SINGLE_CASE_CANARY_FREEZE"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B262_TERRA_COMPACT_SINGLE_CASE_CANARY_FREEZE_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False

PROVIDER = SEMANTIC_GATE_PROVIDER
MODEL = SEMANTIC_GATE_MODEL
PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
OUTPUT_MODE = STRUCTURED_OUTPUT_MODE
PRODUCTION_ENDPOINT = "chat.completions"
TOKEN_FIELD = "max_completion_tokens"
PRODUCTION_SDK_METHOD = "client.chat.completions.create"

SELECTED_CASE_HANDLE = "h01"
SELECTED_CASE_ID = SCORED_CASE_ORDER[0][1]
SELECTED_CASE_ROLE = "positive"
SELECTED_CASE_HUMAN_LABEL = CLASS_SUPPORTED
SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY = True

REQUEST_SERIALIZATION = "json.dumps(payload, ensure_ascii=False, sort_keys=True)"
REQUEST_HASH_ENCODING = "utf-8"
REQUEST_HASH_ALGORITHM = "sha256"

HISTORICAL_4B261_STATUS = "PASS"

assert PROVIDER == "openai"
assert MODEL == "gpt-5.6-terra"
assert PROMPT_VERSION_HISTORICAL == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION_HISTORICAL == "book-semantic-validation-transport-1.0"
assert CANDIDATE_PROMPT_VERSION == "book-semantic-validator-1.1-candidate"
assert CANDIDATE_TRANSPORT_VERSION == "book-semantic-validation-transport-1.1-candidate"
assert CANDIDATE_PROMPT_VERSION != PROMPT_VERSION_HISTORICAL
assert CANDIDATE_TRANSPORT_VERSION != TRANSPORT_VERSION_HISTORICAL
assert OUTPUT_MODE == "json_object"
assert THINKING_MODE == "provider_default"
assert TEMPERATURE_POLICY == "omit"
assert TOKEN_FIELD == "max_completion_tokens"
assert SEMANTIC_TOKEN_BUDGET == CONSERVATIVE_MAX_OUTPUT_TOKENS == 8192
assert SELECTED_CASE_HANDLE == "h01"
assert SELECTED_CASE_ID == "4b22_p2_supported"
assert SELECTED_CASE_ROLE == "positive"
assert SELECTED_CASE_HUMAN_LABEL == CLASS_SUPPORTED
assert EXPECTED_REQUEST_SHA256_4B26 == (
    "8a92848e412763f0e67468245f9c007ee9537ffa4f2f5469af9a6934d9ebeb31"
)
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B2_STATUS == "FAIL"
assert HISTORICAL_4B21_STATUS == "PASS"
assert HISTORICAL_4B22_STATUS == "PARTIAL"
assert HISTORICAL_4B23_STATUS == "PASS"
assert HISTORICAL_4B24_STATUS == "FAIL"
assert HISTORICAL_4B241_STATUS == "PASS"
assert HISTORICAL_4B25_STATUS == "FAIL"
assert HISTORICAL_4B251_STATUS == "PASS"
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False

AUDIT_DIRNAME = "book_semantic_gate_4b262"
AUDIT_CONTRACT = "compact_contract_11_specification.json"
AUDIT_INVARIANTS = "compact_contract_11_semantic_invariants.json"
AUDIT_SELECTION = "single_case_selection_review.json"
AUDIT_EVIDENCE = "single_case_evidence_manifest.json"
AUDIT_TELEMETRY = "terra_reasoning_token_telemetry_tests.json"
AUDIT_SERIALIZATION = "terra_single_case_sdk_serialization.json"
AUDIT_REQUEST = "terra_single_case_request_identity.json"
AUDIT_BUDGET = "terra_single_case_context_budget.json"
AUDIT_COST = "terra_single_case_cost_estimate.json"
AUDIT_PREFLIGHT = "terra_single_case_preflight.json"
AUDIT_TESTS = "terra_compact_contract_regression_tests.json"
AUDIT_READINESS = "terra_4b262_readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b262_index.json"
REPORT_NAME = "PHASE_4B262_TERRA_COMPACT_SINGLE_CASE_CANARY_FREEZE_REPORT.md"

CONFIDENCE_CONFIRMED = "CONFIRMED"
CONFIDENCE_LOCAL = "LOCALLY_VERIFIED"
CONFIDENCE_UNKNOWN = "UNKNOWN_SERVER_SIDE"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "AUDIT_BUDGET",
    "AUDIT_CONTRACT",
    "AUDIT_COST",
    "AUDIT_DIRNAME",
    "AUDIT_EVIDENCE",
    "AUDIT_INDEX",
    "AUDIT_INVARIANTS",
    "AUDIT_PREFLIGHT",
    "AUDIT_READINESS",
    "AUDIT_REQUEST",
    "AUDIT_SELECTION",
    "AUDIT_SERIALIZATION",
    "AUDIT_TELEMETRY",
    "AUDIT_TESTS",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "CANDIDATE_PROMPT_VERSION",
    "CANDIDATE_TRANSPORT_VERSION",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CONFIDENCE_CONFIRMED",
    "CONFIDENCE_LOCAL",
    "CONFIDENCE_UNKNOWN",
    "CONNECTIVE_CASE_ID",
    "CONSERVATIVE_MAX_OUTPUT_TOKENS",
    "EXPECTED_BENCHMARK_FILE_SHA256",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_NEGATIVE_CASES",
    "EXPECTED_OPENAI_SDK_VERSION",
    "EXPECTED_POSITIVE_CASES",
    "EXPECTED_PYTHON_VERSION",
    "EXPECTED_REQUEST_SHA256_4B26",
    "EXPECTED_REQUEST_SHA256_HISTORICAL_4B25",
    "EXPECTED_SCORED_CASES",
    "EXPECTED_SOURCE_MAP",
    "FUNERAL_CASE_ID",
    "HISTORICAL_4B21_STATUS",
    "HISTORICAL_4B22_STATUS",
    "HISTORICAL_4B23_STATUS",
    "HISTORICAL_4B241_STATUS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B251_STATUS",
    "HISTORICAL_4B25_STATUS",
    "HISTORICAL_4B261_STATUS",
    "HISTORICAL_4B26_STATUS",
    "HISTORICAL_4B2_STATUS",
    "MODEL",
    "NEGATIVE_CASE_IDS",
    "NEXT_ACTION",
    "OBSERVED_4B26_COST_USD",
    "OBSERVED_4B26_FINISH_REASON",
    "OBSERVED_4B26_INPUT_TOKENS",
    "OBSERVED_4B26_OUTPUT_TOKENS",
    "OUTPUT_MODE",
    "P3_CASE_ID",
    "P8_CASE_ID",
    "PHASE",
    "PHASE_NAME",
    "POSITIVE_CASE_IDS",
    "PRODUCTION_ENDPOINT",
    "PRODUCTION_SDK_METHOD",
    "PROJECT_NAME",
    "PROMPT_VERSION_HISTORICAL",
    "PROVIDER",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "READY_FOR_NEW_REMOTE_TERRA_CALL",
    "REPORT_NAME",
    "REQUEST_HASH_ALGORITHM",
    "REQUEST_HASH_ENCODING",
    "REQUEST_SERIALIZATION",
    "SCORED_CASE_ORDER",
    "SELECTED_CASE_HANDLE",
    "SELECTED_CASE_HUMAN_LABEL",
    "SELECTED_CASE_HUMAN_LABEL_AUDIT_ONLY",
    "SELECTED_CASE_ID",
    "SELECTED_CASE_ROLE",
    "SEMANTIC_TOKEN_BUDGET",
    "TEMPERATURE_POLICY",
    "TERRA_EXECUTION_AUTHORIZED",
    "THINKING_MODE",
    "TOKEN_FIELD",
    "TRANSPORT_VERSION_HISTORICAL",
    "VERDICT_FAIL",
    "VERDICT_PASS",
    "VERDICT_REVIEW",
]
