"""Constantes 3B.7.7A.19 — canary sémantique V3 WIN001 réel. 1 appel max."""

from __future__ import annotations

from app.source_analysis.window_models import (
    WINDOW_CONNECT_TIMEOUT_SECONDS,
    WINDOW_READ_TIMEOUT_SECONDS,
)
from app.source_analysis_hybrid.constants import PLANNER_VERSION
from app.source_analysis_local_v2.constants import (
    CANDIDATE_PLANNER_VERSION,
    CLEAN_SHA,
    MAX_OUTPUT_TOKENS_FROZEN,
    PROJECT_NAME,
)
from app.source_analysis_local_v3.constants import (
    CANDIDATE_HARD_MAX_INPUT_TOKENS,
    SELECTED_ARCHITECTURE,
    SEMANTIC_TRANSPORT_VERSION_V3,
    TARGET_JSON_LOCAL_TOKENS,
    WINDOW_ANALYSIS_PROMPT_VERSION_V13,
)
from app.source_analysis_local_v3.schema import semantic_transport_v3_fingerprint
from app.source_analysis_output_ceiling_review.constants import (
    CALL1_SIGNATURE,
    CALL2_SIGNATURE,
    SMALL_SIGNATURE,
)
from app.source_analysis_small_window_hierarchy.constants import (
    CANDIDATE_CONTEXT_POLICY,
)
from app.source_analysis_small_window_readiness.constants import A7_WIN001_INPUT_HASH
from app.source_analysis_thinking_contract.constants import (
    SELECTED_CONTRACT,
    SELECTED_EFFORT,
    SELECTED_THINKING_MODE,
)
from app.source_analysis_v2_a15_forensics.constants import (
    A15_COST_DISPLAY,
    A15_COVERAGE_PCT,
    A15_DISTINCT_SRC,
    A15_EXAMPLE,
    A15_FINISH,
    A15_IDEA,
    A15_INPUT_RATIO,
    A15_INVALID_LINKS,
    A15_LOCAL_INPUT,
    A15_OUTPUT_TOKENS,
    A15_PROVIDER_INPUT,
    A15_RECORDS,
    A15_REFERENCE,
    A15_RELATION,
    A15_SIGNATURE,
    A15_THINKING_TOKENS,
    A15_TOPIC,
    A15_UNCERTAINTY,
    SEMANTIC_CONTENT_CLASSIFICATION,
)
from app.source_analysis_v2_link_semantics.constants import A13_REQUEST_IDENTITY
from app.source_analysis_v2_real_win001.constants import (
    EXPECTED_FIRST_OWNED_SRC,
    EXPECTED_LAST_OWNED_SRC,
    EXPECTED_OWNED_SRC_COUNT,
    EXPECTED_WORD_COUNT,
    WINDOW_ID,
)
from app.source_analysis_v3_symbolic_grammar_canary.constants import (
    EXPECTED_ADAPTED_SCHEMA_BYTES,
    EXPECTED_RAW_SCHEMA_BYTES,
)
from app.source_analysis_v3_symbolic_handles.constants import (
    REPORT_NAME as A17_REPORT,
    SCHEMA_ARTIFACT as A17_SCHEMA_ARTIFACT,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.7.7A.19"
MODE = "REAL_V3_SMALL_WIN001_SYMBOLIC_HANDLE_CANARY"

AUTHORIZATION_SCOPE = "SMALL_V21_V3_SYMBOLIC_WIN001_ONLY"
FORBIDDEN_WINDOW_IDS = (
    "WIN002",
    "WIN003",
    "WIN004",
    "WIN005",
    "WIN006",
    "WIN007",
    "WIN996",
)

PROVIDER = "anthropic"
MODEL = "claude-sonnet-5"
THINKING_CONTRACT = SELECTED_CONTRACT
THINKING_MODE = SELECTED_THINKING_MODE
EFFORT = SELECTED_EFFORT

MAX_ENGINE_GENERATE = 1
MAX_ANTHROPIC_POST = 1
MAX_ATTEMPTS = 1
AUTO_RETRY = False
AUTO_FALLBACK = False
AUTO_CONTINUE = False

MAX_OUTPUT_TOKENS = MAX_OUTPUT_TOKENS_FROZEN
CONNECT_TIMEOUT_SECONDS = WINDOW_CONNECT_TIMEOUT_SECONDS
READ_TIMEOUT_SECONDS = WINDOW_READ_TIMEOUT_SECONDS
HISTORICAL_READ_TIMEOUT_SECONDS = 7200.0

EXPECTED_ANALYSIS_SIGNATURE = (
    "e2b5019216624fac4b32dd5bd0b90e1a0cde860c805982dde0820a5ef47f3c1d"
)
EXPECTED_FORENSIC_IDENTITY = (
    "5a46bb534d575e03f6f2786928ca667cc3c61b4e6902d6271e454d96a65ed993"
)
EXPECTED_SCHEMA_HASH = semantic_transport_v3_fingerprint()
EXPECTED_WINDOW_INPUT_HASH = A7_WIN001_INPUT_HASH
EXPECTED_OWNED_SRC_COUNT = EXPECTED_OWNED_SRC_COUNT
EXPECTED_WORD_COUNT = EXPECTED_WORD_COUNT
EXPECTED_FIRST_OWNED_SRC = EXPECTED_FIRST_OWNED_SRC
EXPECTED_LAST_OWNED_SRC = EXPECTED_LAST_OWNED_SRC
EXPECTED_CLEAN_SHA = CLEAN_SHA
EXPECTED_CLEAN_FILE_SHA = CLEAN_SHA
EXPECTED_CONTEXT_COUNT = 0
EXPECTED_CONTEXT_POLICY = CANDIDATE_CONTEXT_POLICY
EXPECTED_LOCAL_INPUT_ESTIMATE = 22428
EXPECTED_A18_REQUEST_IDENTITY = (
    "b85d65ae5c77a7497e280a3b1e749c2386143680f47c3792a0cb567fd92d90b7"
)
A13_SYNTHETIC_IDENTITY = A13_REQUEST_IDENTITY
A15_V2_SIGNATURE = A15_SIGNATURE
A15_INVALID_RECORDS = 5
A15_SEMANTIC_CONTENT = SEMANTIC_CONTENT_CLASSIFICATION

SYNTHETIC_WORST_CASE_LOCAL_TOKENS = 12185
TARGET_12000_EXCEEDED_BY = 364

LOCK_NAME = "a19_real_v3_win001.lock"
CANARY_SUBDIR = "canary/v3_real_win001"
CANDIDATE_WINDOWS_SUBDIR = "v3_windows"
CANDIDATE_CACHE_SUBDIR = "v3_cache"

PREFLIGHT_ARTIFACT = "source_analysis_v3_real_win001_preflight.json"
EXECUTION_ARTIFACT = "source_analysis_v3_real_win001_execution.json"
HANDLE_ARTIFACT = "source_analysis_v3_real_win001_handle_analysis.json"
REVIEW_ARTIFACT = "source_analysis_v3_real_win001_semantic_review.json"
COMPARISON_ARTIFACT = "source_analysis_v3_win001_vs_v2_a15_comparison.json"
REPORT_NAME = "PHASE_3B77A19_REAL_V3_SMALL_WIN001_SYMBOLIC_HANDLE_CANARY_REPORT.md"

SEMANTIC_REVIEW_STATUS = "FORENSIC_SEMANTIC_REVIEW_OF_VALID_V3_WIN001_CANDIDATE"

DRY_RUN_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v3_real_win001 "
    "pastoral_retreat_v2_validation "
    "--authorization-scope SMALL_V21_V3_SYMBOLIC_WIN001_ONLY "
    "--window WIN001 --dry-run"
)
REAL_COMMAND = (
    r".venv\Scripts\python.exe -m app.source_analysis_v3_real_win001 "
    "pastoral_retreat_v2_validation "
    "--authorization-scope SMALL_V21_V3_SYMBOLIC_WIN001_ONLY "
    "--window WIN001 --execute-real"
)

NEXT_ACTION = "HUMAN REVIEW"
PHASE_3B_STATUS = "INCOMPLETE"
PRODUCTION_PLANNER_VERSION = PLANNER_VERSION
CANDIDATE_PLANNER = CANDIDATE_PLANNER_VERSION
PROMPT_VERSION = WINDOW_ANALYSIS_PROMPT_VERSION_V13
TRANSPORT_VERSION = SEMANTIC_TRANSPORT_VERSION_V3

A16_REPORT = (
    "PHASE_3B77A16_A15_INVALID_LINK_FORENSICS_OFFLINE_SEMANTIC_REVIEW_REPORT.md"
)
A17_REPORT_NAME = A17_REPORT
A18_REPORT = "PHASE_3B77A18_SYMBOLIC_HANDLE_TINY_GRAMMAR_CANARY_REPORT.md"
A18_EXECUTION = "source_analysis_v3_symbolic_grammar_canary_execution.json"
A18_PAYLOAD = "source_analysis_v3_symbolic_grammar_canary_payload.json"

PROTECTED_HISTORICAL = (
    "audit/PHASE_3B77A13_V2_TINY_GRAMMAR_THINKING_CONFIG_CANARY_REPORT.md",
    "audit/source_analysis_v2_grammar_thinking_canary_execution.json",
    "audit/source_analysis_v2_grammar_thinking_canary_payload.json",
    "audit/PHASE_3B77A14_V2_LINK_SEMANTICS_HARDENING_SEMANTIC_WIN001_READINESS_REPORT.md",
    "audit/source_analysis_v2_future_win001_identity.json",
    "audit/PHASE_3B77A15_REAL_V2_SMALL_WIN001_SEMANTIC_CANARY_REPORT.md",
    "audit/source_analysis_v2_real_win001_execution.json",
    "audit/source_analysis_v2_real_win001_preflight.json",
    "audit/source_analysis_v2_win001_vs_call_c_comparison.json",
    "audit/canary/a15_real_v2_win001.lock",
    f"audit/{A16_REPORT}",
    f"audit/{A17_REPORT_NAME}",
    f"audit/{A17_SCHEMA_ARTIFACT}",
    f"audit/{A18_REPORT}",
    f"audit/{A18_EXECUTION}",
    f"audit/{A18_PAYLOAD}",
)

assert EXPECTED_SCHEMA_HASH == (
    "de42ce0f3c271e67b902a94d2f528eae56f82b1a2a5740e65161987038849425"
)
assert EXPECTED_RAW_SCHEMA_BYTES == 588
assert EXPECTED_ADAPTED_SCHEMA_BYTES == 650
assert MAX_OUTPUT_TOKENS == 32000
assert THINKING_MODE == "disabled"
assert EFFORT is None

__all__ = [
    "A13_SYNTHETIC_IDENTITY",
    "A15_COST_DISPLAY",
    "A15_COVERAGE_PCT",
    "A15_DISTINCT_SRC",
    "A15_EXAMPLE",
    "A15_FINISH",
    "A15_IDEA",
    "A15_INPUT_RATIO",
    "A15_INVALID_LINKS",
    "A15_INVALID_RECORDS",
    "A15_LOCAL_INPUT",
    "A15_OUTPUT_TOKENS",
    "A15_PROVIDER_INPUT",
    "A15_RECORDS",
    "A15_REFERENCE",
    "A15_RELATION",
    "A15_SEMANTIC_CONTENT",
    "A15_THINKING_TOKENS",
    "A15_TOPIC",
    "A15_UNCERTAINTY",
    "A15_V2_SIGNATURE",
    "A16_REPORT",
    "A17_REPORT_NAME",
    "A18_EXECUTION",
    "A18_PAYLOAD",
    "A18_REPORT",
    "AUTHORIZATION_SCOPE",
    "AUTO_CONTINUE",
    "AUTO_FALLBACK",
    "AUTO_RETRY",
    "CALL1_SIGNATURE",
    "CALL2_SIGNATURE",
    "CANARY_SUBDIR",
    "CANDIDATE_CACHE_SUBDIR",
    "CANDIDATE_HARD_MAX_INPUT_TOKENS",
    "CANDIDATE_PLANNER",
    "CANDIDATE_WINDOWS_SUBDIR",
    "COMPARISON_ARTIFACT",
    "CONNECT_TIMEOUT_SECONDS",
    "DRY_RUN_COMMAND",
    "EFFORT",
    "EXECUTION_ARTIFACT",
    "EXPECTED_ADAPTED_SCHEMA_BYTES",
    "EXPECTED_ANALYSIS_SIGNATURE",
    "EXPECTED_A18_REQUEST_IDENTITY",
    "EXPECTED_CLEAN_FILE_SHA",
    "EXPECTED_CLEAN_SHA",
    "EXPECTED_CONTEXT_COUNT",
    "EXPECTED_CONTEXT_POLICY",
    "EXPECTED_FIRST_OWNED_SRC",
    "EXPECTED_FORENSIC_IDENTITY",
    "EXPECTED_LAST_OWNED_SRC",
    "EXPECTED_LOCAL_INPUT_ESTIMATE",
    "EXPECTED_OWNED_SRC_COUNT",
    "EXPECTED_RAW_SCHEMA_BYTES",
    "EXPECTED_SCHEMA_HASH",
    "EXPECTED_WINDOW_INPUT_HASH",
    "EXPECTED_WORD_COUNT",
    "FORBIDDEN_WINDOW_IDS",
    "HANDLE_ARTIFACT",
    "HISTORICAL_READ_TIMEOUT_SECONDS",
    "LOCK_NAME",
    "MAX_ANTHROPIC_POST",
    "MAX_ATTEMPTS",
    "MAX_ENGINE_GENERATE",
    "MAX_OUTPUT_TOKENS",
    "MODE",
    "MODEL",
    "NEXT_ACTION",
    "PHASE",
    "PHASE_3B_STATUS",
    "PREFLIGHT_ARTIFACT",
    "PRODUCTION_PLANNER_VERSION",
    "PROJECT_NAME",
    "PROMPT_VERSION",
    "PROTECTED_HISTORICAL",
    "PROVIDER",
    "READ_TIMEOUT_SECONDS",
    "REAL_COMMAND",
    "REPORT_NAME",
    "REVIEW_ARTIFACT",
    "SCHEMA_VERSION",
    "SELECTED_ARCHITECTURE",
    "SEMANTIC_REVIEW_STATUS",
    "SMALL_SIGNATURE",
    "SYNTHETIC_WORST_CASE_LOCAL_TOKENS",
    "TARGET_12000_EXCEEDED_BY",
    "TARGET_JSON_LOCAL_TOKENS",
    "THINKING_CONTRACT",
    "THINKING_MODE",
    "TRANSPORT_VERSION",
    "WINDOW_ANALYSIS_PROMPT_VERSION_V13",
    "WINDOW_ID",
]
