"""
Phase 4B.2.18 — Authorial voice preservation and CH012 targeted correction.

STRICTLY OFFLINE. Isolated from production. Zero provider calls.
Does not regenerate CH012. Does not reuse the consumed 4B.2.17 Sonnet
authorization. Does not replace historical Book Generator prompts.
Does not modify book-generator-faithful-restatement-1.0-candidate.
Does not publish book.json. Does not write the production cache.
"""

from __future__ import annotations

from app.book_editorial_alignment_4b216.constants import (
    COVERAGE_CONTRACT_VERSION,
    EDITORIAL_POLICY_VERSION,
    FAITHFUL_PROMPT_VERSION,
    HISTORICAL_GENERATOR_PROMPT,
    HISTORICAL_GENERATOR_PROMPT_V10,
    HISTORICAL_SEMANTIC_CONTRACT,
    HUMAN_RESOLUTION_VERSION,
    THEMATIC_RULES_VERSION,
)
from app.book_generation.constants import (
    BOOK_GENERATOR_PROMPT_VERSION,
    BOOK_GENERATOR_PROMPT_VERSION_V10,
    EXPECTED_EDITORIAL_PLAN_SHA256,
    EXPECTED_SOURCE_MAP_SHA256,
    VALIDATION_PROJECT_NAME,
)
from app.book_generation_4b217.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B217_SCOPE,
    LOCK_NAME as ORIGINAL_LOCK_NAME,
    TARGET_CHAPTER_ID as CHAPTER_4B217,
    TARGET_CHAPTER_TITLE as TITLE_4B217,
)
from app.book_semantic_gate_4b215.constants import (
    HISTORICAL_4B210_STATUS,
    HISTORICAL_4B211_STATUS,
    HISTORICAL_4B212_STATUS,
    HISTORICAL_4B213_STATUS,
    HISTORICAL_4B214_STATUS,
    HISTORICAL_H01_STATUS,
    HISTORICAL_H02_STATUS,
    HISTORICAL_H11_STATUS,
)
from app.book_semantic_gate_4b23.constants import EXPECTED_CLEAN_TRANSCRIPT
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE

PHASE = "4B.2.18"
PHASE_NAME = "AUTHORIAL_VOICE_PRESERVATION_AND_CH012_TARGETED_CORRECTION"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_AUTHORIAL_VOICE_4B218_AUTHORIAL_VOICE_PRESERVATION_"
    "AND_CH012_TARGETED_CORRECTION_ONLY"
)

AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
AUTHORIZED_REMOTE_INVOCATIONS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False
SONNET_EXECUTION_AUTHORIZED = False
REAL_CHAPTER_GENERATION_AUTHORIZED = False
REAL_PROVIDERS_ENABLED = False
RETRIES = 0
FALLBACKS = 0

PRODUCTION_PIPELINE_HOOK = False
PRODUCTION_CACHE_ACCEPTANCE = False
COVERAGE_CONTROL_ACTIVATED = False
FAITHFUL_PROMPT_ACTIVATED = False
FAITHFUL_PROMPT_1_1_ACTIVATED = False
EDITORIAL_POLICY_ACTIVATED = False
AUTHORIAL_VOICE_POLICY_ACTIVATED = False
SEMANTIC_GATE_202_ENABLED = False

CODE_VERSION = "app.book_authorial_voice_4b218"
AUTHORIAL_VOICE_POLICY_VERSION = "authorial-voice-preservation-1.0-candidate"
FAITHFUL_PROMPT_1_0_VERSION = FAITHFUL_PROMPT_VERSION
FAITHFUL_PROMPT_1_1_VERSION = "book-generator-faithful-restatement-1.1-candidate"
COVERAGE_CONTRACT = COVERAGE_CONTRACT_VERSION
EDITORIAL_POLICY = EDITORIAL_POLICY_VERSION

HISTORICAL_PROMPT_V10 = HISTORICAL_GENERATOR_PROMPT_V10
HISTORICAL_PROMPT_V101 = HISTORICAL_GENERATOR_PROMPT
HISTORICAL_SEMANTIC = HISTORICAL_SEMANTIC_CONTRACT

assert FAITHFUL_PROMPT_1_0_VERSION == "book-generator-faithful-restatement-1.0-candidate"
assert FAITHFUL_PROMPT_1_1_VERSION == "book-generator-faithful-restatement-1.1-candidate"
assert AUTHORIAL_VOICE_POLICY_VERSION == "authorial-voice-preservation-1.0-candidate"
assert HISTORICAL_PROMPT_V101 == BOOK_GENERATOR_PROMPT_VERSION == "book-generator-1.0.1"
assert HISTORICAL_PROMPT_V10 == BOOK_GENERATOR_PROMPT_VERSION_V10 == "book-generator-1.0"
assert THEMATIC_RULES_VERSION == "thematic-reorganization-rules-4b216-candidate"
assert HUMAN_RESOLUTION_VERSION == "human-resolution-protocol-4b216-candidate"
assert HISTORICAL_SEMANTIC == "book-semantic-validator-2.0.2-candidate"
assert CONSUMED_4B217_SCOPE == (
    "BOOK_GENERATION_4B217_CH012_FAITHFUL_REAL_PILOT_GENERATION_ONLY"
)

TARGET_CHAPTER_ID = CHAPTER_4B217
TARGET_CHAPTER_TITLE = TITLE_4B217
EXPECTED_SECTION_IDS = ("SEC047", "SEC048", "SEC049", "SEC050")
EXPECTED_PARAGRAPH_IDS = (
    "P000001",
    "P000002",
    "P000003",
    "P000004",
    "P000005",
    "P000006",
    "P000007",
    "P000008",
    "P000009",
    "P000010",
    "P000011",
    "P000012",
    "P000013",
    "P000014",
)
EXPECTED_PARAGRAPH_COUNT = 14
EXPECTED_IDEA_COUNT = 11
EXPECTED_UNCERTAINTY_ID = "UNC029"
ORIGINAL_LOCK = ORIGINAL_LOCK_NAME

assert TARGET_CHAPTER_ID == "CH012"
assert TARGET_CHAPTER_TITLE == "Prayer Corrected"
assert ORIGINAL_LOCK == "ch012_real_call.lock"

CLASS_AUTHORIAL_OK = "AUTHORIAL_VOICE_OK"
CLASS_EXTERNAL_CONFIRMED = "EXTERNAL_NARRATOR_CONFIRMED"
CLASS_POSSIBLE_EXTERNAL = "POSSIBLE_EXTERNAL_NARRATOR"
CLASS_ATTRIBUTION_UNCERTAIN = "ATTRIBUTION_UNCERTAIN"
CLASS_THIRD_PERSON_LEGITIMATE = "THIRD_PERSON_LEGITIMATE"

STATUS_APPLIED = "APPLIED"
STATUS_REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"
STATUS_ATTRIBUTION_UNCERTAIN = "ATTRIBUTION_UNCERTAIN"
STATUS_UNCHANGED = "UNCHANGED"

CANONICAL_PYTHON = CANONICAL_PYTHON_EXECUTABLE
EXPECTED_SOURCE_MAP = EXPECTED_SOURCE_MAP_SHA256
EXPECTED_EDITORIAL_PLAN = EXPECTED_EDITORIAL_PLAN_SHA256
EXPECTED_TRANSCRIPT = EXPECTED_CLEAN_TRANSCRIPT

assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert AUTHORIZED_TERRA_CALLS == 0
assert AUTHORIZED_SONNET_CALLS == 0
assert AUTHORIZED_ANTHROPIC_CALLS == 0
assert AUTHORIZED_OPENAI_CALLS == 0
assert PUBLICATION_AUTHORIZED is False
assert REAL_CHAPTER_GENERATION_AUTHORIZED is False
assert FAITHFUL_PROMPT_1_1_ACTIVATED is False
assert AUTHORIAL_VOICE_POLICY_ACTIVATED is False
assert CANONICAL_PYTHON.endswith("python.exe")

HISTORICAL_4B215_STATUS = "PARTIAL"
HISTORICAL_4B216_STATUS = "PASS"
HISTORICAL_4B217_STATUS = "PARTIAL"
HISTORICAL_4B218_DOES_NOT_REQUALIFY = True

AUDIT_DIRNAME = "book_authorial_voice_4b218"
AUDIT_PREFLIGHT = "preflight.json"
AUDIT_HASHES_PRE = "canonical_hashes_pre.json"
AUDIT_POLICY = "authorial_voice_policy.json"
AUDIT_NARRATIVE = "narrative_audit.json"
AUDIT_ATTRIBUTION = "speaker_attribution_evidence.json"
AUDIT_CORRECTIONS = "targeted_corrections.json"
AUDIT_CHAPTER_V2_JSON = "chapter_candidate_authorial_v2.json"
AUDIT_CHAPTER_V2_MD = "chapter_candidate_authorial_v2.md"
AUDIT_DIFF = "chapter_diff.md"
AUDIT_PROMPT_11 = "generator_prompt_1_1_candidate.json"
AUDIT_IDEA_DIAGNOSIS = "idea_traceability_diagnosis.json"
AUDIT_IDEA_MAPPINGS = "idea_paragraph_mapping_proposals.json"
AUDIT_COVERAGE = "source_coverage_review.json"
AUDIT_HUMAN = "human_review_required.json"
AUDIT_HASHES_POST = "canonical_hashes_post.json"
AUDIT_TESTS = "regression_tests.json"
AUDIT_READINESS = "readiness.json"
REPORT_NAME = (
    "PHASE_4B218_AUTHORIAL_VOICE_PRESERVATION_"
    "AND_CH012_TARGETED_CORRECTION_REPORT.md"
)

ORIGINAL_CHAPTER_JSON = "chapter_candidate.json"
ORIGINAL_CHAPTER_MD = "chapter_candidate.md"

COVERAGE_FLAGGED_UNITS = (
    "IDEA238",
    "EX030",
    "REF037",
    "REF038",
    "REF043",
    "UNC029",
)

FORBIDDEN_EXTERNAL_FRAMES = (
    "The speaker explained",
    "The preacher said",
    "The author recalled",
    "The speaker recounted",
    "He taught that",
    "The speaker emphasized",
    "The preacher described",
    "According to the speaker",
)

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_FULL_BOOK_GENERATION = False

__all__ = [
    "AUTHORIZATION_SCOPE",
    "AUTHORIAL_VOICE_POLICY_VERSION",
    "CANONICAL_PYTHON",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_PARAGRAPH_COUNT",
    "EXPECTED_SOURCE_MAP",
    "EXPECTED_TRANSCRIPT",
    "FAITHFUL_PROMPT_1_1_VERSION",
    "PHASE",
    "TARGET_CHAPTER_ID",
]
