"""Phase 4B.2.34.1 constants. Offline. Zero USD. No image."""

from __future__ import annotations

from app.cover_flux2_pro_4b234.constants import (
    AUTHORIZATION_SCOPE as CONSUMED_4B234_SCOPE,
    BOOK_TITLE,
    EXPECTED_BOOK_SHA256,
    EXPECTED_INTERIOR_DOCX_SHA256,
    EXPECTED_INTERIOR_PDF_SHA256,
    INTERIOR_VERSION,
    PROJECT_NAME,
)
from app.cover_generator_foundation_4b233.constants import INTERIOR_PDF_PAGES

PHASE = "4B.2.34.1"
PHASE_NAME = "FLUX2_PRO_UNBLOCK"
AUTHORIZATION_SCOPE = "COVER_FLUX2_PRO_4B2341_OFFLINE_ONLY"
AUDIT_DIRNAME = "cover_generator_flux2_pro_unblock_4b2341"
REPORT_NAME = "PHASE_4B2341_FLUX2_PRO_UNBLOCK_REPORT.md"
ART_DIRECTION = "The Door Already Open"
DECISION = "BLOCKED_PRICING"
RESULT = "BLOCKED"

assert PROJECT_NAME == "pastoral_retreat_v2_validation"
assert BOOK_TITLE == "The Life You Already Inherited"
assert INTERIOR_VERSION == "print-review-v1.1"
assert INTERIOR_PDF_PAGES == 67
assert EXPECTED_BOOK_SHA256 == (
    "adde6e2344f4b94da0f7df183341885574e89abc90781c426459e850cc2b6550"
)
assert CONSUMED_4B234_SCOPE == "COVER_FLUX2_PRO_4B234_OFFLINE_ONLY"

__all__ = [
    "ART_DIRECTION",
    "AUDIT_DIRNAME",
    "AUTHORIZATION_SCOPE",
    "BOOK_TITLE",
    "DECISION",
    "EXPECTED_BOOK_SHA256",
    "EXPECTED_INTERIOR_DOCX_SHA256",
    "EXPECTED_INTERIOR_PDF_SHA256",
    "INTERIOR_PDF_PAGES",
    "INTERIOR_VERSION",
    "PHASE",
    "PHASE_NAME",
    "PROJECT_NAME",
    "REPORT_NAME",
    "RESULT",
]
