"""Constantes de l'audit 3B.5 — aucun réglage de timeout de production."""

from __future__ import annotations

from app.source_analysis_global_clean.constants import (
    EXPECTED_MODEL,
    EXPECTED_MODEL_MAX_OUTPUT,
    EXPECTED_PROVIDER,
    MAX_ATTEMPTS,
    MAX_REAL_CALLS,
    REAL_CALL_TIMEOUT_SECONDS,
    STAGE,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B.5"
MODE = "OFFLINE"

DIAGNOSTIC_ARTIFACT_NAME = "source_analysis_timeout_root_cause_audit.json"
REPORT_NAME = "PHASE_3B5_GLOBAL_TIMEOUT_ROOT_CAUSE_AUDIT_REPORT.md"

PRIMARY_CLASSIFICATION = "HTTP_READ_TIMEOUT_TOO_SHORT"
SECONDARY_RISKS = (
    "GLOBAL_RUN_ARCHITECTURE_RISK",
    "UPSTREAM_LIMIT_POSSIBLE",
)

TIMEOUT_CLOCK_STARTS_AT = (
    "requests.post() inside app.ai.providers._http.post_json, "
    "called from AnthropicEngine._invoke after BaseAIEngine.generate() "
    "has entered call_with_retry. The HTTP connect/read clocks start when "
    "the POST is issued, not during preflight or human authorization."
)

ANTHROPIC_RESPONSE_MODE = "NON_STREAMING"
HTTP_TIMEOUT_FORM = "scalar"
INCREASE_3600_ONLY_SUFFICIENT = "LIKELY"
LOWER_TIMEOUT_ELSEWHERE = "NO"
AUTHORIZATION_WAIT_COUNTS = False
NEXT_TIMEOUT_CANDIDATE = None
NEXT_TIMEOUT_JUSTIFICATION = "NO_EVIDENCE_BASED_EXACT_TIMEOUT"
RECOMMENDATION_CONFIDENCE = "HIGH"
NEXT_TIMEOUT_CONFIDENCE = "LOW"
NEXT_STEP = "3B.5.1_LONG_RUN_TIMEOUT_CONFIG_AND_OBSERVABILITY_HARDENING"
NEW_ANTHROPIC_CALL_AUTHORIZED = False
CANARY_SCALING_IS_NOT_LINEARLY_PREDICTIVE = True

PROVIDER_MAY_HAVE_CONTINUED = "UNKNOWN"
REQUEST_ID_RECOVERABLE = False
COST_MEANS = "application_received_no_usage_data_not_zero_charge"

__all__ = [
    "ANTHROPIC_RESPONSE_MODE",
    "AUTHORIZATION_WAIT_COUNTS",
    "CANARY_SCALING_IS_NOT_LINEARLY_PREDICTIVE",
    "DIAGNOSTIC_ARTIFACT_NAME",
    "EXPECTED_MODEL",
    "EXPECTED_MODEL_MAX_OUTPUT",
    "EXPECTED_PROVIDER",
    "INCREASE_3600_ONLY_SUFFICIENT",
    "LOWER_TIMEOUT_ELSEWHERE",
    "MAX_ATTEMPTS",
    "MAX_REAL_CALLS",
    "MODE",
    "NEW_ANTHROPIC_CALL_AUTHORIZED",
    "NEXT_STEP",
    "NEXT_TIMEOUT_CANDIDATE",
    "NEXT_TIMEOUT_JUSTIFICATION",
    "PHASE",
    "PRIMARY_CLASSIFICATION",
    "REAL_CALL_TIMEOUT_SECONDS",
    "REPORT_NAME",
    "RECOMMENDATION_CONFIDENCE",
    "SCHEMA_VERSION",
    "SECONDARY_RISKS",
    "STAGE",
    "TIMEOUT_CLOCK_STARTS_AT",
]
