"""Rapport markdown 3B.7.7A.32. Offline."""

from __future__ import annotations

from typing import Any, Mapping


def _yn(value: bool | None) -> str:
    if value is True:
        return "YES"
    if value is False:
        return "NO"
    return "UNKNOWN"


def render_report(bundle: Mapping[str, Any], *, tests: str) -> str:
    header = bundle["header"]
    replay = bundle["replay"]
    root = bundle["root_cascade"]
    transformation = bundle["transformation"]
    intended = bundle["intended"]
    history = bundle["history"]
    counter = bundle["counterfactual"]
    decision = bundle["decision"]
    semantic = counter.get("semantic_review") or {}
    coverage = semantic.get("coverage") or {}
    relations = semantic.get("relation_quality_summary") or {}
    checklist = semantic.get("major_idea_checklist") or {}
    mixed = counter.get("mixed") or counter.get("canonical") or {}
    local = mixed.get("local") or mixed
    inventory = replay.get("src_inventory") or {}
    material_unsupported = semantic.get("unsupported_content")
    if material_unsupported is None:
        material_unsupported = semantic.get("unsupported_count")
    lines = [
        "# PHASE 3B.7.7A.32 — WIN007 STRICT SRC TYPO FORENSICS",
        "",
        "## Result",
        "",
        str(header["result"]),
        "",
        "REAL PROVIDER CALLS =",
        str(header["real_provider_calls"]),
        "",
        "REAL WINDOW CALLS =",
        str(header["real_window_calls"]),
        "",
        "A.31 STATUS =",
        "FAIL unchanged",
        "",
        "READY =",
        "6 / 7",
        "",
        "WIN007 =",
        "NOT READY",
        "",
        "ORIGINAL REQUEST ID =",
        str(replay.get("request_id") or header.get("original_request_id")),
        "",
        "ROOT SRC VIOLATIONS =",
        str(root.get("root_src_violations")),
        "",
        "CASCADE VIOLATIONS =",
        str(root.get("cascade_src_violations")),
        "",
        "MALFORMED TOKEN =",
        "SRec007337",
        "",
        "EXPECTED CANONICAL CANDIDATE =",
        "SRC007337",
        "",
        "EDIT DISTANCE =",
        str(transformation.get("edit_distance_case_sensitive")),
        "",
        "NUMERIC PAYLOAD PRESERVED =",
        _yn(bool(transformation.get("numeric_payload_preserved"))),
        "",
        "CANONICAL CANDIDATE OWNED BY WIN007 =",
        _yn(bool((intended.get("numeric_owned") or {}).get("owned_by_win007"))),
        "",
        "INTENDED SOURCE CLASS =",
        str(intended.get("intended_source_class")),
        "",
        "OTHER SRC ROOT VIOLATIONS =",
        str(root.get("other_src_root_violations")),
        "",
        "HISTORICAL A.19 SAME GENERAL CLASS =",
        _yn(bool(decision.get("a19_same_general_class"))),
        "",
        "REAL SRC OCCURRENCES AUDITED =",
        str(history.get("total_real_src_occurrences_inspected")),
        "",
        "REAL MALFORMED SRC RATE =",
        str(history.get("malformed_rate")),
        "",
        "COUNTERFACTUAL SINGLE CORRECTION =",
        str(counter.get("technical")),
        "",
        "OTHER TECHNICAL FAILURES AFTER CORRECTION =",
        str(counter.get("other_technical_failures_after_correction") or []),
        "",
        "COUNTERFACTUAL SEMANTIC QUALITY =",
        str(semantic.get("semantic_quality") or "NOT_ELIGIBLE"),
        "",
        "MATERIAL UNSUPPORTED CONTENT =",
        str(material_unsupported if material_unsupported is not None else "N/A"),
        "",
        "MATERIAL OMISSIONS =",
        str(semantic.get("material_omissions") if semantic else "N/A"),
        "",
        "COUNTERFACTUAL CANONICAL RECONSTRUCTION =",
        str(local.get("idea_validation") or "NOT_ELIGIBLE"),
        "",
        "MIXED COMPATIBILITY =",
        str(mixed.get("mixed_compatibility") or "NOT_ELIGIBLE"),
        "",
        "SELECTED POLICY =",
        str(decision.get("selected_policy")),
        "",
        "PROMPT CHANGE REQUIRED =",
        "NO",
        "",
        "TRANSPORT CHANGE REQUIRED =",
        "NO",
        "",
        "SCHEMA CHANGE REQUIRED =",
        "NO",
        "",
        "A.18 GRAMMAR PROOF =",
        "APPLIES",
        "",
        "FUTURE WIN007 ACTION =",
        str(decision.get("future_win007_action")),
        "",
        "TESTS =",
        tests,
        "",
        "READY AFTER =",
        "6 / 7",
        "",
        "SOURCE MAP =",
        "NOT PUBLISHED",
        "",
        "PHASE 3B =",
        "INCOMPLETE",
        "",
        "NEXT ACTION =",
        "HUMAN REVIEW",
        "",
        "## Identity",
        "",
        f"window = {replay.get('window_id')}",
        f"prompt = {replay.get('prompt')}",
        f"transport = {replay.get('transport')}",
        f"granularity = {replay.get('granularity')}",
        f"thinking = {replay.get('thinking')}",
        f"finish = {replay.get('finish')}",
        f"HTTP = {replay.get('http')}",
        f"input_tokens = {replay.get('input_tokens')}",
        f"output_tokens = {replay.get('output_tokens')}",
        f"elapsed_ms = {replay.get('elapsed_ms')}",
        f"cost_usd = {replay.get('cost_usd')}",
        f"raw_sha256 = {replay.get('raw_sha256')}",
        f"raw_size = {replay.get('raw_size')}",
        "",
        "## Exact failure reproduction",
        "",
        f"reproduced = {_yn(bool(replay.get('reproduced')))}",
        f"observed = {replay.get('observed_token')}",
        f"v31_decoder = {replay.get('v31_decoder')}",
        f"handle_registry = {replay.get('handle_registry')}",
        f"handle_resolution = {replay.get('handle_resolution')}",
        f"v31_validator = {replay.get('v31_validator')}",
        f"errors = {replay.get('validation_errors')}",
        "normalized = NO",
        "repaired = NO",
        "",
        "## Exhaustive WIN007 SRC inventory",
        "",
        f"total = {inventory.get('total_src_occurrences')}",
        f"exact valid = {inventory.get('exact_valid_occurrences')}",
        f"malformed = {inventory.get('malformed_occurrences')}",
        f"unknown = {inventory.get('unknown')}",
        f"out-of-window = {inventory.get('out_of_window')}",
        f"wrong-case = {inventory.get('wrong_case')}",
        f"wrong-prefix = {inventory.get('wrong_prefix')}",
        f"inserted-character = {inventory.get('inserted_character')}",
        f"other = {inventory.get('other')}",
        f"SRec007337 is only root SRC violation = {_yn(bool(inventory.get('srec007337_is_only_root')))}",
        f"class counts = {inventory.get('class_counts')}",
        "",
        "## Root vs cascade",
        "",
        f"root SRC = {root.get('root_src_violations')}",
        f"cascade SRC = {root.get('cascade_src_violations')}",
        f"cascade pipeline gates = {root.get('cascade_pipeline_gates')}",
        str(root.get("note")),
        "",
        "## SRec007337 transformation",
        "",
        f"SRC007337 → SRec007337",
        f"case-sensitive edit distance = {transformation.get('edit_distance_case_sensitive')}",
        f"case-insensitive edit distance = {transformation.get('edit_distance_case_insensitive')}",
        f"inserted = {transformation.get('inserted')}",
        f"deleted = {transformation.get('deleted')}",
        f"substituted = {transformation.get('substituted')}",
        f"case changes = {transformation.get('case_changes')}",
        f"prefix {transformation.get('prefix_from')} → {transformation.get('prefix_to')}",
        f"numeric preserved = {_yn(bool(transformation.get('numeric_payload_preserved')))}",
        "production correction = NO",
        "",
        "## Source content / neighborhood",
        "",
        f"owned = {_yn(bool((intended.get('numeric_owned') or {}).get('owned_by_win007')))}",
        f"intended class = {intended.get('intended_source_class')}",
        f"shared content words = {(intended.get('comparison') or {}).get('shared_count')}",
        f"best neighbor overlap = {(intended.get('neighborhood') or {}).get('best_overlap_src')}",
        f"other plausible neighbor = {_yn(bool((intended.get('neighborhood') or {}).get('other_plausible_neighbor')))}",
        "Digits alone do not prove intent.",
        "",
        "## Historical A.19 comparison",
        "",
        "A.19 token = SRc000609 ; A.31 token = SRec007337",
        "Both = PROVIDER_SRC_LITERAL_COPY_ERROR",
        "A.19 manifestation = 3-letter prefix case-only (wrong_case)",
        "A.31 manifestation = 4-letter prefix insertion + case (SRec)",
        "Both preserve the numeric payload exactly.",
        "A.19 prompt generation = window-analysis-1.3 ; hardening published 1.3.1",
        "A.31 prompt = window-analysis-1.4.0 (still includes the 1.3.1 SRC copy block)",
        "A.31 transport = semantic-transport-v3.1-local-lite",
        "SRC hardening did not eliminate the class.",
        "",
        "## Frequency",
        "",
        f"responses inspected = {len(history.get('responses') or [])}",
        f"occurrences = {history.get('total_real_src_occurrences_inspected')}",
        f"malformed = {history.get('malformed')}",
        f"rate = {history.get('malformed_rate')}",
        f"responses with ≥1 malformed = {history.get('responses_with_ge1_malformed')}",
        f"forms = {history.get('malformed_forms_observed')}",
        f"by generation = {history.get('by_generation')}",
        "",
        "## Counterfactual",
        "",
        f"technical = {counter.get('technical')}",
        f"sole root cause = {_yn(bool(counter.get('sole_root_cause')))}",
        f"raw unchanged = {_yn(bool(counter.get('original_raw_unchanged')))}",
        f"original token still SRec007337 = {_yn(bool(counter.get('original_payload_token_still_srec')))}",
        "",
        "## Semantic review (if eligible)",
        "",
        f"quality = {semantic.get('semantic_quality') or 'NOT_ELIGIBLE'}",
        f"grounding = {semantic.get('grounding_counts')}",
        f"major ideas represented/partial/missing = {checklist.get('represented')}/{checklist.get('partial')}/{checklist.get('missing')}",
        f"beginning/middle/end = {coverage.get('beginning')}/{coverage.get('middle')}/{coverage.get('end')}",
        f"material unsupported = {material_unsupported}",
        f"material omissions = {semantic.get('material_omissions')}",
        f"relations W/P/I/U = {relations.get('well-supported')}/{relations.get('plausible-loose')}/{relations.get('incorrect')}/{relations.get('unverifiable')}",
        "RELATION_QUALITY_TECHNICAL_DEBT = YES",
        f"distinct canonical SRC = {coverage.get('distinct_src_refs')}",
        f"coverage % = {coverage.get('semantic_src_coverage_pct')}",
        f"largest gap = {coverage.get('largest_substantive_gap')}",
        "",
        "## Canonical (forensic only)",
        "",
        f"kind expected = \"\" ; all_kinds_empty = {local.get('all_kinds_empty')}",
        f"importance→kind contamination = {local.get('importance_to_kind_contamination')}",
        f"mixed compatibility with WIN001–WIN006 = {mixed.get('mixed_compatibility')}",
        "production candidate cache = NOT WRITTEN",
        "",
        "## Decision",
        "",
        str(decision.get("selected_policy")),
        "",
        *[f"- {item}" for item in (decision.get("rationale") or [])],
        "",
        "WIN007 remains NOT READY. READY remains 6 / 7.",
        "",
        "WAIT FOR HUMAN REVIEW. Do not implement canonicalization. "
        "Do not retry WIN007. Do not consolidate. Do not publish source_map.",
        "",
    ]
    return "\n".join(lines) + "\n"


__all__ = ["render_report"]
