"""
Phase 4B.2.7.4 — Offline semantic gate consolidation.

Offline only. Zero provider calls. Historical canaries are not relaunched.
Historical 4B.2.6 remains FAIL. 4B.2.6.1 remains PASS. 4B.2.6.2 remains PASS.
Historical 4B.2.7 remains PARTIAL. 4B.2.7.1 remains PASS. 4B.2.7.2 remains PASS.
Historical 4B.2.7.3 remains PARTIAL. h01 and h02 remain PARTIAL.
Frozen 1.0 / 1.1-candidate / 1.1.1-candidate are not modified.
1.1.2-candidate is a proposal only and is not promoted.
"""

from __future__ import annotations

from app.book_generation.constants import VALIDATION_PROJECT_NAME
from app.book_semantic_gate_4b23.constants import (
    CLASS_NON_SUBSTANTIVE,
    CLASS_QUESTIONABLE,
    CLASS_SUPPORTED,
    CLASS_UNSUPPORTED,
    CLASSIFICATIONS,
    EXPECTED_CLEAN_TRANSCRIPT,
    EXPECTED_EDITORIAL_PLAN,
    EXPECTED_SOURCE_MAP,
    SEMANTIC_VALIDATION_TRANSPORT_VERSION,
    SEMANTIC_VALIDATOR_PROMPT_VERSION,
)
from app.book_semantic_gate_4b24.constants import (
    CONNECTIVE_CASE_ID,
    EXPECTED_PROMPT_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_SYSTEM_SHA256,
    EXPECTED_SCHEMA_SHA256,
    FUNERAL_CASE_ID,
    NEGATIVE_CASE_IDS,
    P3_CASE_ID,
    P8_CASE_ID,
    POSITIVE_CASE_IDS,
    SCORED_CASE_ORDER,
)
from app.book_semantic_gate_4b26.constants import CANONICAL_PYTHON_EXECUTABLE
from app.book_semantic_gate_4b261.constants import (
    CANDIDATE_PROMPT_VERSION,
    CANDIDATE_TRANSPORT_VERSION,
)
from app.book_semantic_gate_4b27.constants import (
    EXPECTED_REQUEST_SHA256 as H01_REQUEST_SHA256,
    HISTORICAL_4B241_STATUS,
    HISTORICAL_4B24_STATUS,
    HISTORICAL_4B251_STATUS,
    HISTORICAL_4B25_STATUS,
    HISTORICAL_4B261_STATUS,
    HISTORICAL_4B262_STATUS,
    HISTORICAL_4B26_STATUS,
)
from app.book_semantic_gate_4b271.constants import (
    DISPUTED_CLAUSE as H01_DISPUTED_CLAUSE,
    EXPECTED_PROMPT_11_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_11_SHA256,
    EXPECTED_PROMPT_11_SYSTEM_SHA256,
    EXPECTED_SCHEMA_11_SHA256,
    HISTORICAL_4B27_STATUS,
    PROMPT_VERSION_111,
    TRANSPORT_VERSION_11,
    TRANSPORT_VERSION_111,
)
from app.book_semantic_gate_4b272.constants import (
    DISPUTED_CAUSAL_CLAUSE,
    EXPECTED_PROMPT_111_INSTRUCTIONS_SHA256,
    EXPECTED_PROMPT_111_SHA256,
    EXPECTED_PROMPT_111_SYSTEM_SHA256,
    HISTORICAL_4B271_STATUS,
    OBSERVED_4B27_COMPLETION_TOKENS,
    OBSERVED_4B27_COST_USD,
    OBSERVED_4B27_INPUT_TOKENS,
    OBSERVED_4B27_REASONING_TOKENS,
    P3_EVIDENCE_HANDLES,
)
from app.book_semantic_gate_4b273.constants import (
    EXPECTED_CLAUSE_END,
    EXPECTED_CLAUSE_START,
    EXPECTED_REQUEST_SHA256 as H02_REQUEST_SHA256,
    HISTORICAL_4B272_STATUS,
)

PHASE = "4B.2.7.4"
PHASE_NAME = "OFFLINE_SEMANTIC_GATE_CONSOLIDATION"

PROJECT_NAME = VALIDATION_PROJECT_NAME
assert PROJECT_NAME == "pastoral_retreat_v2_validation"

AUTHORIZATION_SCOPE = (
    "BOOK_SEMANTIC_GATE_4B274_OFFLINE_SEMANTIC_GATE_CONSOLIDATION_ONLY"
)
AUTHORIZED_TERRA_CALLS = 0
AUTHORIZED_OPENAI_CALLS = 0
AUTHORIZED_ANTHROPIC_CALLS = 0
AUTHORIZED_SONNET_CALLS = 0
PUBLICATION_AUTHORIZED = False
TERRA_EXECUTION_AUTHORIZED = False

PROMPT_VERSION_HISTORICAL = SEMANTIC_VALIDATOR_PROMPT_VERSION
TRANSPORT_VERSION_HISTORICAL = SEMANTIC_VALIDATION_TRANSPORT_VERSION
PROMPT_VERSION_11 = CANDIDATE_PROMPT_VERSION
PROMPT_VERSION_112 = "book-semantic-validator-1.1.2-candidate"
TRANSPORT_VERSION_112 = None
REASON_NORMALIZATION_VERSION = "reason-code-normalization-1.1.2-audit-only"
COVERAGE_POLICY_VERSION = "coverage-validator-1.1.2-candidate"

HISTORICAL_4B273_STATUS = "PARTIAL"
HISTORICAL_H01_STATUS = "PARTIAL"
HISTORICAL_H02_STATUS = "PARTIAL"

H01_CASE_HANDLE = "h01"
H01_CASE_ID = "4b22_p2_supported"
H01_HUMAN_LABEL = CLASS_SUPPORTED
H01_MODEL = "gpt-5.6-terra"
H01_CONTRACT = "book-semantic-validator-1.1-candidate"
H01_COST_USD = OBSERVED_4B27_COST_USD
H01_INPUT_TOKENS = OBSERVED_4B27_INPUT_TOKENS
H01_COMPLETION_TOKENS = OBSERVED_4B27_COMPLETION_TOKENS
H01_REASONING_TOKENS = OBSERVED_4B27_REASONING_TOKENS

H02_CASE_HANDLE = "h02"
H02_CASE_ID = P3_CASE_ID
H02_HUMAN_LABEL = CLASS_QUESTIONABLE
H02_MODEL = "gpt-5.6-terra"
H02_CONTRACT = "book-semantic-validator-1.1.1-candidate"
H02_COST_USD = 0.066036
H02_INPUT_TOKENS = 1692
H02_COMPLETION_TOKENS = 5221
H02_REASONING_TOKENS = 4595
H02_GAPS = ((93, 96), (124, 126), (270, 272), (404, 406))
H01_GAPS = ((140, 141), (209, 210))

OBSERVED_H02_REASON_CODES = (
    "INVENTED_CAUSAL_LINK",
    "NO_EVIDENCE",
    "UNJUSTIFIED_STRENGTHENING",
    "UNSUPPORTED_IMPLICATION",
    "PARTIAL_REFERENCE_EXPANSION",
)

OVERFIT_TOKENS = (
    "bargaining",
    "bargain with",
    "h01",
    "h02",
    "IDEA224",
    "4b22_p2",
    "4b22_p3_new_causal",
    "because it still works wherever it is not resisted by truth",
)

assert PROMPT_VERSION_HISTORICAL == "book-semantic-validator-1.0"
assert TRANSPORT_VERSION_HISTORICAL == "book-semantic-validation-transport-1.0"
assert PROMPT_VERSION_11 == "book-semantic-validator-1.1-candidate"
assert TRANSPORT_VERSION_11 == "book-semantic-validation-transport-1.1-candidate"
assert PROMPT_VERSION_111 == "book-semantic-validator-1.1.1-candidate"
assert TRANSPORT_VERSION_111 is None
assert PROMPT_VERSION_112 != PROMPT_VERSION_111
assert PROMPT_VERSION_112 != PROMPT_VERSION_11
assert PROMPT_VERSION_112 != PROMPT_VERSION_HISTORICAL
assert TRANSPORT_VERSION_112 is None
assert H01_REQUEST_SHA256 == (
    "9520a4f3e5ff36ec2957b74e82d492019ff630f764e1413853b19d9b96dec6af"
)
assert H02_REQUEST_SHA256 == (
    "5ace261296d808437910f8f9efe247a80daebbb2237bc8af46bda56bf98d7897"
)
assert H01_REQUEST_SHA256 != H02_REQUEST_SHA256
assert EXPECTED_SOURCE_MAP == (
    "df32f5943a21ed4013c5344d7579dbaaa46d35a77df342e1b2f6718794fc2855"
)
assert EXPECTED_EDITORIAL_PLAN == (
    "01cfb86aed8d32a7228b7c10a8351e2ebc0832fbfe6051e35686b0fd84836440"
)
assert EXPECTED_CLEAN_TRANSCRIPT == (
    "1f33ac732eb82ec1d55f274a152747058c9138cd394dea9c956d28d7e2739958"
)
assert HISTORICAL_4B26_STATUS == "FAIL"
assert HISTORICAL_4B261_STATUS == "PASS"
assert HISTORICAL_4B262_STATUS == "PASS"
assert HISTORICAL_4B27_STATUS == "PARTIAL"
assert HISTORICAL_4B271_STATUS == "PASS"
assert HISTORICAL_4B272_STATUS == "PASS"
assert HISTORICAL_4B273_STATUS == "PARTIAL"
assert HISTORICAL_H01_STATUS == "PARTIAL"
assert HISTORICAL_H02_STATUS == "PARTIAL"
assert DISPUTED_CAUSAL_CLAUSE == (
    "because it still works wherever it is not resisted by truth"
)
assert H01_DISPUTED_CLAUSE == "that fear can calculate or bargain with"
assert AUTHORIZED_TERRA_CALLS == 0
assert TERRA_EXECUTION_AUTHORIZED is False
assert PUBLICATION_AUTHORIZED is False
assert H02_CASE_ID == "4b22_p3_new_causal"

AUDIT_DIRNAME = "book_semantic_gate_4b274"
AUDIT_INVENTORY = "historical_canary_inventory.json"
AUDIT_COMPARISON = "h01_h02_comparative_analysis.json"
AUDIT_CLAIMS = "h02_claim_by_claim_review.json"
AUDIT_DISAGREEMENT = "h02_semantic_disagreement_matrix.json"
AUDIT_REASON_CATALOG = "reason_code_catalog_audit.json"
AUDIT_REASON_POLICY = "reason_code_policy.json"
AUDIT_PUNCTUATION = "punctuation_coverage_inventory.json"
AUDIT_COVERAGE_DESIGN = "coverage_validator_design.json"
AUDIT_CONTRACT = "contract_112_candidate_review.json"
AUDIT_TRANSPORT = "transport_compatibility.json"
AUDIT_REPLAYS = "historical_response_replays.json"
AUDIT_BENCHMARK = "benchmark_regression.json"
AUDIT_COST = "cost_comparison.json"
AUDIT_TESTS = "offline_tests.json"
AUDIT_READINESS = "readiness.json"
AUDIT_INDEX = "book_semantic_gate_4b274_index.json"
REPORT_NAME = "PHASE_4B274_OFFLINE_SEMANTIC_GATE_CONSOLIDATION_REPORT.md"

NEXT_ACTION = "HUMAN REVIEW"
READY_FOR_NEW_REMOTE_TERRA_CALL = False
READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT = False
READY_FOR_FULL_REAL_BOOK_GENERATION = False

__all__ = [
    "AUDIT_BENCHMARK",
    "AUDIT_CLAIMS",
    "AUDIT_COMPARISON",
    "AUDIT_CONTRACT",
    "AUDIT_COST",
    "AUDIT_COVERAGE_DESIGN",
    "AUDIT_DIRNAME",
    "AUDIT_DISAGREEMENT",
    "AUDIT_INDEX",
    "AUDIT_INVENTORY",
    "AUDIT_PUNCTUATION",
    "AUDIT_READINESS",
    "AUDIT_REASON_CATALOG",
    "AUDIT_REASON_POLICY",
    "AUDIT_REPLAYS",
    "AUDIT_TESTS",
    "AUDIT_TRANSPORT",
    "AUTHORIZATION_SCOPE",
    "AUTHORIZED_ANTHROPIC_CALLS",
    "AUTHORIZED_OPENAI_CALLS",
    "AUTHORIZED_SONNET_CALLS",
    "AUTHORIZED_TERRA_CALLS",
    "CANONICAL_PYTHON_EXECUTABLE",
    "CLASSIFICATIONS",
    "CLASS_NON_SUBSTANTIVE",
    "CLASS_QUESTIONABLE",
    "CLASS_SUPPORTED",
    "CLASS_UNSUPPORTED",
    "CONNECTIVE_CASE_ID",
    "COVERAGE_POLICY_VERSION",
    "DISPUTED_CAUSAL_CLAUSE",
    "EXPECTED_CLEAN_TRANSCRIPT",
    "EXPECTED_CLAUSE_END",
    "EXPECTED_CLAUSE_START",
    "EXPECTED_EDITORIAL_PLAN",
    "EXPECTED_PROMPT_111_INSTRUCTIONS_SHA256",
    "EXPECTED_PROMPT_111_SHA256",
    "EXPECTED_PROMPT_111_SYSTEM_SHA256",
    "EXPECTED_PROMPT_11_INSTRUCTIONS_SHA256",
    "EXPECTED_PROMPT_11_SHA256",
    "EXPECTED_PROMPT_11_SYSTEM_SHA256",
    "EXPECTED_PROMPT_INSTRUCTIONS_SHA256",
    "EXPECTED_PROMPT_SYSTEM_SHA256",
    "EXPECTED_SCHEMA_11_SHA256",
    "EXPECTED_SCHEMA_SHA256",
    "EXPECTED_SOURCE_MAP",
    "FUNERAL_CASE_ID",
    "H01_CASE_HANDLE",
    "H01_CASE_ID",
    "H01_COMPLETION_TOKENS",
    "H01_CONTRACT",
    "H01_COST_USD",
    "H01_DISPUTED_CLAUSE",
    "H01_GAPS",
    "H01_HUMAN_LABEL",
    "H01_INPUT_TOKENS",
    "H01_MODEL",
    "H01_REASONING_TOKENS",
    "H01_REQUEST_SHA256",
    "H02_CASE_HANDLE",
    "H02_CASE_ID",
    "H02_COMPLETION_TOKENS",
    "H02_CONTRACT",
    "H02_COST_USD",
    "H02_GAPS",
    "H02_HUMAN_LABEL",
    "H02_INPUT_TOKENS",
    "H02_MODEL",
    "H02_REASONING_TOKENS",
    "H02_REQUEST_SHA256",
    "HISTORICAL_4B241_STATUS",
    "HISTORICAL_4B24_STATUS",
    "HISTORICAL_4B251_STATUS",
    "HISTORICAL_4B25_STATUS",
    "HISTORICAL_4B261_STATUS",
    "HISTORICAL_4B262_STATUS",
    "HISTORICAL_4B26_STATUS",
    "HISTORICAL_4B271_STATUS",
    "HISTORICAL_4B272_STATUS",
    "HISTORICAL_4B273_STATUS",
    "HISTORICAL_4B27_STATUS",
    "HISTORICAL_H01_STATUS",
    "HISTORICAL_H02_STATUS",
    "NEGATIVE_CASE_IDS",
    "NEXT_ACTION",
    "OBSERVED_H02_REASON_CODES",
    "OVERFIT_TOKENS",
    "P3_CASE_ID",
    "P3_EVIDENCE_HANDLES",
    "P8_CASE_ID",
    "PHASE",
    "PHASE_NAME",
    "POSITIVE_CASE_IDS",
    "PROJECT_NAME",
    "PROMPT_VERSION_11",
    "PROMPT_VERSION_111",
    "PROMPT_VERSION_112",
    "PROMPT_VERSION_HISTORICAL",
    "PUBLICATION_AUTHORIZED",
    "READY_FOR_BOOK_GENERATOR_PRODUCTION_PREFLIGHT",
    "READY_FOR_FULL_REAL_BOOK_GENERATION",
    "READY_FOR_NEW_REMOTE_TERRA_CALL",
    "REASON_NORMALIZATION_VERSION",
    "REPORT_NAME",
    "SCORED_CASE_ORDER",
    "TERRA_EXECUTION_AUTHORIZED",
    "TRANSPORT_VERSION_11",
    "TRANSPORT_VERSION_111",
    "TRANSPORT_VERSION_112",
    "TRANSPORT_VERSION_HISTORICAL",
]
