"""Constantes de l'essai #2 — n'écrase pas l'historique de l'essai #1."""

from __future__ import annotations

from app.source_analysis_long_run_policy.constants import (
    GLOBAL_ATTEMPT_NUMBER,
    SELECTED_OPERATIONAL_CONNECT_TIMEOUT_SECONDS,
    SELECTED_OPERATIONAL_READ_TIMEOUT_SECONDS,
    SOURCE_ANALYSIS_CONNECT_ENV,
    SOURCE_ANALYSIS_READ_ENV,
    THIRD_GLOBAL_TIMEOUT_ESCALATION_ALLOWED,
)

SCHEMA_VERSION = "1.0"
PHASE = "3B_FINAL"
PURPOSE = "global_clean_source_analysis_attempt2"
ATTEMPT_NUMBER = GLOBAL_ATTEMPT_NUMBER  # 2

EXPECTED_CONNECT_TIMEOUT_SECONDS = float(SELECTED_OPERATIONAL_CONNECT_TIMEOUT_SECONDS)
EXPECTED_READ_TIMEOUT_SECONDS = float(SELECTED_OPERATIONAL_READ_TIMEOUT_SECONDS)
EXPECTED_TIMEOUT_SOURCE = "stage_env"
EXPECTED_REQUESTS_TIMEOUT = (
    EXPECTED_CONNECT_TIMEOUT_SECONDS,
    EXPECTED_READ_TIMEOUT_SECONDS,
)

DRY_RUN_ARTIFACT_NAME = "source_analysis_global_clean_attempt2_dry_run.json"
TRANSPORT_ARTIFACT_NAME = "source_analysis_global_clean_attempt2_transport.json"
RESULT_ARTIFACT_NAME = "source_analysis_global_clean_attempt2_result.json"
FAILED_RAW_NAME = "source_analysis_global_clean_attempt2_failed_canonical_raw.json"
FAILED_NORMALIZED_NAME = "source_analysis_global_clean_attempt2_failed_normalized.json"
REPORT_NAME = "PHASE_3B_FINAL_GLOBAL_CLEAN_SOURCE_ANALYZER_ATTEMPT2_REPORT.md"

POLICY_ARTIFACT_NAME = "source_analysis_second_global_attempt_policy.json"
POLICY_REPORT_NAME = "PHASE_3B52_LONG_RUN_EXECUTION_POLICY_REPORT.md"

CLASS_PRE_CALL_TIMEOUT_MISMATCH = "PRE_CALL_TIMEOUT_MISMATCH"
CLASS_PRE_CALL_POLICY_MISMATCH = "PRE_CALL_POLICY_MISMATCH"
CLASS_PRE_CALL_STATE_UNEXPECTED = "PRE_CALL_PROJECT_STATE_UNEXPECTED"

NEXT_PHASE_ON_TIMEOUT = "3B.6_GLOBAL_ANALYSIS_EXECUTION_STRATEGY_REVIEW"
NEXT_PHASE_ON_PASS = "PHASE_3B_COMPLETE_HUMAN_REVIEW"
NEXT_PHASE_ON_PARTIAL = "OFFLINE_DIAGNOSIS"
NEXT_PHASE_ON_FAIL = "STOP_NO_RETRY"

FORBIDDEN_THIRD_TIMEOUTS = (9000, 10800, 14400)

ATTEMPT1_ARTIFACTS = (
    "audit/source_analysis_global_clean_dry_run.json",
    "audit/source_analysis_global_clean_result.json",
    "audit/PHASE_3B_FINAL_GLOBAL_CLEAN_SOURCE_ANALYZER_REPORT.md",
)

__all__ = [
    "ATTEMPT_NUMBER",
    "CLASS_PRE_CALL_POLICY_MISMATCH",
    "CLASS_PRE_CALL_TIMEOUT_MISMATCH",
    "DRY_RUN_ARTIFACT_NAME",
    "EXPECTED_CONNECT_TIMEOUT_SECONDS",
    "EXPECTED_READ_TIMEOUT_SECONDS",
    "EXPECTED_REQUESTS_TIMEOUT",
    "EXPECTED_TIMEOUT_SOURCE",
    "PHASE",
    "PURPOSE",
    "REPORT_NAME",
    "RESULT_ARTIFACT_NAME",
    "SOURCE_ANALYSIS_CONNECT_ENV",
    "SOURCE_ANALYSIS_READ_ENV",
    "THIRD_GLOBAL_TIMEOUT_ESCALATION_ALLOWED",
    "TRANSPORT_ARTIFACT_NAME",
]
